### DISCUSSION TITLE
Coordinates in Debug Mode

### DISCUSSION THREAD

**Discussion by Quotenjunkie** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#112] [Q&A] [answered]
Hi,

after the V2 update of the cloud map extractor I am able to succesfully retrieve the map for mit Viomi V8 (Xioami Mi Mop Pro EU Version).

But when I try to find out the coordinates for my zones in the debug mode of the lovelace card, I get 5 values for a zone.
Am I doing something wrong?

BR

![image](https://user-images.githubusercontent.com/6428023/122653832-b5eca480-d147-11eb-872e-b4b46e709e37.png)

**Comment by PiotrMachowski** [comment, marked as answer]
This card does not work with Viomi models at this moment.

**Reply by Quotenjunkie** [reply]
Hi,

thx for the quick response. Is it planned to implement the Viomi models?

BR

**Reply by PiotrMachowski** [reply]
Sure, but give me some time ;)

**Reply by Quotenjunkie** [reply]
Sorry I was just too excited 🙂

**Reply by PiotrMachowski** [reply]
It works now ;)

**Comment by PilgrimToHyperion** [comment]
I have the same vacuum cleaner and I also get similar coordinates (using map extractor) that are whole numbers e.g. 1, 2, -2, -3 etc. These are not very accurate to set up zones, rooms etc.

E.g. here I am trying to get the coordinates to the corner of my kitchen.
![image](https://user-images.githubusercontent.com/28935079/156719771-5081721c-869c-4019-8083-1e4ac32343cc.png)

And here I'm trying to see the coordinates of a clean area block:
![image](https://user-images.githubusercontent.com/28935079/156720025-db156f8a-5551-4c69-9ea9-3ae3d75dd62e.png)

EDIT - I now understand these numbers that are 0-based is related to the platform I selected (in this case send_command). I am using send_command platform as the viomi v8 is not detected as supported by miio integration so I have to use Xiaomi Miot Auto intergration.

If I use config generator, I get values likes these for the room icons where are more accurate (numbers with decimals). This is what I was hoping for using map extractor. How do I get coordinates with decimals using map extractor or what should my approach be?

```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.viomi_v8_32e5_robot_cleaner
vacuum_platform: send_command
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_modes:
  - template: vacuum_goto
  - template: vacuum_clean_zone
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 18
        icon:
          name: "mdi:broom"
          x: 2.525
          y: -11.425
      - id: 19
        icon:
          name: "mdi:broom"
          x: 3.425
          y: -7.4
      - id: 10
        icon:
          name: "mdi:broom"
          x: -0.2749999999999999
          y: -7.75
      - id: 16
        icon:
          name: "mdi:broom"
          x: 3.125
          y: -3.1500000000000004
      - id: 11
        icon:
          name: "mdi:broom"
          x: -0.6
          y: -2.675
```

config in configuration.yaml
```yaml
  - platform: xiaomi_cloud_map_extractor
    host: 192.x.x.x
    token: xxxx
    username: xxxx
    password: xxxx
    draw: ['all']
    scan_interval: 10
    attributes:
      - calibration_points
      - rooms
```

**Reply by PiotrMachowski** [reply]
Does your vacuum work with `send_command` platform?

You can disable coordinates rounding using following config:

```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.viomi_v8_32e5_robot_cleaner
vacuum_platform: send_command
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_modes:
  - template: vacuum_goto
    coordinates_rounding: false
  - template: vacuum_clean_zone
    coordinates_rounding: false
  - template: vacuum_clean_segment
    coordinates_rounding: false
    predefined_selections:
      - id: 18
        icon:
          name: "mdi:broom"
          x: 2.525
          y: -11.425
      - id: 19
        icon:
          name: "mdi:broom"
          x: 3.425
          y: -7.4
      - id: 10
        icon:
          name: "mdi:broom"
          x: -0.2749999999999999
          y: -7.75
      - id: 16
        icon:
          name: "mdi:broom"
          x: 3.125
          y: -3.1500000000000004
      - id: 11
        icon:
          name: "mdi:broom"
          x: -0.6
          y: -2.675
```
