### DISCUSSION TITLE
V.2 Predefined zones not showing on map

### DISCUSSION THREAD

**Discussion by nickdos** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#139] [Q&A] [answered]
I've followed the instructions for migrating from the v1 to v2 config syntax but my custom zones are not showing up when I select the `zones list` option (see screenshot at bottom).

Here is my config:

```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.roborock_vacuum
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_clean_zone_predefined
    predefined_selections:
      - zones:
          - - 26162
            - 26421
            - 30241
            - 30186
      - zones:
          - - 19918
            - 28052
            - 25409
            - 30218
      - zones:
          - - 22428
            - 23597
            - 26099
            - 28052
      - zones:
          - - 18976
            - 23597
            - 22334
            - 28021
      - zones:
          - - 23244
            - 22091
            - 27291
            - 23440
          - - 26287
            - 19298
            - 27291
            - 21996
      - zones:
          - - 22302
            - 16254
            - 26162
            - 22091
      - zones:
          - - 26413
            - 16160
            - 30492
            - 19235
      - zones:
          - - 27354
            - 21055
            - 30398
            - 24977
```

I'm wondering if there is anything obvious I've missed as I've now checked it 3 times, unsuccessfully. Thanks

![image](https://user-images.githubusercontent.com/532845/141873407-11aaddde-9afb-4962-854c-bec99dba57da.png)
