### DISCUSSION TITLE
Sample Config showing Rooms or even perhaps all available configs

### DISCUSSION THREAD

**Discussion by sheminasalam** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#141] [General]
Hi there, can you share a sample config which shows how to add rooms to this card? I tried going through docs but it seems I am not able to figure it out. I usually gets my rooms cleaned by using the following service call.
```
service: vacuum.send_command
data:
  command: set_mode_withroom
  params:
    - 0
    - 1
    - 1
    - 16
entity_id: vacuum.robo_vacuum
```
Where room id is 16. It a styj02ym
