### DISCUSSION TITLE
Disabling icons/tiles

### DISCUSSION THREAD

**Discussion by PiotrMachowski** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#162] [FAQ]
If you want to hide icons or tiles (or both) you just have to use any of these configs:

## Hiding all tiles
```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.xiaomi_vacuum
vacuum_platform: default
tiles: []
```

![image](https://user-images.githubusercontent.com/6118709/142098735-6e5525ed-fe63-4f6c-b9e8-dba2ed7fb0a2.png)

## Hiding all icons
```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.xiaomi_vacuum
vacuum_platform: default
icons: []
```
![image](https://user-images.githubusercontent.com/6118709/142097372-d09d21b5-aedc-49a4-b08d-f342e0be96e8.png)

## Hiding all tiles and icons
```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.xiaomi_vacuum
vacuum_platform: default
icons: []
tiles: []
```

![image](https://user-images.githubusercontent.com/6118709/142099309-6a88fd07-f4ae-48f1-be07-0ea1bfc88452.png)

## Hiding specific tiles
1. Open card editor
2. Hover over the tile you want to hide to find out its ID
3. Add following config to the card's yaml config:
   ```yaml
   append_tiles: true
   tiles:
     - tile_id: PUT_THE_ID_HERE
       replace_config: true
       remove: true
   ```
4. Save changes

## Hiding specific icons
1. Open card editor
2. Hover over the icon you want to hide to find out its ID
3. Add following config to the card's yaml config:
   ```yaml
   append_icons: true
   icons:
     - icon_id: PUT_THE_ID_HERE
       replace_config: true
       remove: true
   ```
4. Save changes

**Comment by michelotten** [comment]
Hi @PiotrMachowski,

First of all, thanks for this amazing v2 release!
I would like to modify the tiles a little further by hiding some of the tiles, but not all.
Could you point me in the right direction here?

Maybe there is a default config you can share, which I can use as a base to modify it to my wishes in my ui-lovelace.yaml file?

**Reply by Stooovie** [reply]
Same. I want to keep the default tiles but without Fan speed. I never adjust that and it makes the tiles overflow to three lines ;)

**Reply by PiotrMachowski** [reply]
It is already possible, I will make an appropriate guide soon :)

**Reply by dm0xa** [reply]
hey! 
Thanks for your time creating this awesome thingy. Is there a way to hide a map?

**Reply by PiotrMachowski** [reply]
@dimppk Well, map is kinda a main part of this card, but if you really want to hide it you can do it with card mod:
```yaml
  .map-wrapper {
    display: none;
  }
```

**Reply by ztevns** [reply]
Do you have an update on how keep the default tiles? I'm struggling to find fan and battery information. In my setup there is no entity or attribute available with this information. But the battery and fan information is there when i just have default tiles.

**Reply by PiotrMachowski** [reply]
@ztevns You have to add `append_tiles: true` to your config

**Reply by Dejvic** [reply]
> Same. I want to keep the default tiles but without Fan speed. I never adjust that and it makes the tiles overflow to three lines ;)

You can disable a specific entity that you do not want to display. you will not have any data, but it will not be displayed in the vacuum cleaner card. That's how I solved it.

**Reply by PiotrMachowski** [reply]
@Dejvic but it is not possible to disable fan speed this way

**Reply by Dejvic** [reply]
sorry, we didn't test it on fan speed. I only tried to hide the number of cleanings, this value is useless to me. and I found no other way than to turn off the entity. I would like you to be able to create some short manual on how to customize the information panel.

**Reply by mattdevo1** [reply]
> @dimppk Well, map is kinda a main part of this card, but if you really want to hide it you can do it with card mod:
> 
> ```yaml
>   .map-wrapper {
>     display: none;
>   }
> ```

Hey @PiotrMachowski, I'm trying to disable the map also (so I can split the card into two, with the map and tiles displayed horizontally instead of vertically). However, I can't seem to get this to work with card-mod (I am using card-mod elsewhere, so it definitely works).

Where exactly should I insert the above code to hide the map?

Thanks in advance!

**Reply by PiotrMachowski** [reply]
@mattdevo1 I'm a bit lost here:

> I'm trying to disable the map also (so I can split the card into two, with the map and tiles displayed horizontally instead of vertically).

Can you show do what you want to achieve?

**Reply by mattdevo1** [reply]
What I'm trying to achieve is something like this:

![142415101-33c08de6-a51a-49ab-9f3d-4cde64195b29](https://user-images.githubusercontent.com/24498328/178993264-00b4812b-1657-4628-addf-2fbbd8e2797e.png)

I tried using card-mod per your recommendation [here](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/183), but I can't seem to get that to work either.

**Comment by filikun** [comment]
Is it possible to just show the map without any buttons and also have it locked?

**Reply by PiotrMachowski** [reply]
```yaml
tiles: []
icons: []
map_locked: true
map_modes:
  - template: vacuum_clean_zone_predefined
    run_immediately: true
```

Wouldn't it be better to just use built-in picture-entity card at this point?

**Reply by filikun** [reply]
It seems that your card get's a much better picture quality than the picture-entity for some reason. 

Your code above still renders the "x1" button. 

![image](https://user-images.githubusercontent.com/9947929/195415000-c3f08d34-2f96-4e84-957b-c89bde6e7bc1.png)

**Reply by filikun** [reply]
Adding `repeats_type: "NONE"` did take it away but a portion of the card still remains, I guess I need some card mod shenanigans to get rid of it completely? 
```
map_modes:
  - template: vacuum_clean_zone_predefined
    run_immediately: true 
    repeats_type: "NONE" 
```

**Reply by PiotrMachowski** [reply]
This should do the trick:

```yaml
tiles: []
icons: []
map_locked: true
map_modes:
  - template: vacuum_clean_zone_predefined
    run_immediately: true
    repeats_type: NONE
```

It should be possible to get the same quality in picture entity card using card mod and `image-rendering: pixelated;` in css

**Reply by filikun** [reply]
I still have a little bar left with that code.

```yaml
- type: custom:xiaomi-vacuum-map-card
  map_source:
    camera: camera.xiaomi_cloud_map_extractor
  calibration_source:
    camera: true
  entity: vacuum.robobork
  vacuum_platform: default
  tiles: []
  icons: []
  map_locked: true
  map_modes:
    - template: vacuum_clean_zone_predefined
      run_immediately: true
      repeats_type: NONE    
```

![image](https://user-images.githubusercontent.com/9947929/195419111-efe1c332-a154-4dbb-8ca9-f0a835d3019a.png)


Edit: Not sure where I should but that css though.

**Reply by filikun** [reply]
Just adding `--ha-card-background: none` did solve it :)

**Comment by bboudewijns** [comment]
Hi All!
Would there be any way to change the colors of the icons? In my theme they are unreadable but I can't find any way to change them?

Thanks for some great work!

![IMG_5442_2_30](https://user-images.githubusercontent.com/53646683/198990638-74246953-b01a-4735-8c88-b157464f43a9.jpg)

**Reply by PiotrMachowski** [reply]
https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/320

**Comment by rodolfomachado** [comment]
Hi,

Is there a way to remove locate and start button? 

![image](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/42542786/2e12f20a-a28d-453d-a530-2147924a0d7f)

I never use the mais start and always use room or segment. Also, I want to prevent my wife to click there.

**Reply by PiotrMachowski** [reply]
@rodolfomachado can you attach your config?

**Reply by rodolfomachado** [reply]
Yes... here it is

```
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.caca_map
  crop:
    top: 120
    bottom: 120
    left: 130
    right: 80
calibration_source:
  camera: true
entity: vacuum.caca
vacuum_platform: humbertogontijo/homeassistant-roborock
two_finger_pan: true
map_modes:
  - template: vacuum_clean_segment
    predefined_selections:
      - id: '16'
        icon:
          name: mdi:broom
          x: 22425
          'y': 27000
        label:
          text: Cozinha
          x: 22425
          'y': 27000
          offset_x: 8
          offset_y: 30
      - id: '17'
        icon:
          name: mdi:broom
          x: 27000
          'y': 27000
        label:
          text: Sala
          x: 27000
          'y': 27000
          offset_y: 25
      - id: '18'
        icon:
          name: mdi:broom
          x: 22175
          'y': 22450
        label:
          text: Lavanderia
          x: 22175
          'y': 22450
          offset_y: 35
      - id: '19'
        icon:
          name: mdi:broom
          x: 24300
          'y': 23000
        label:
          text: Escritório
          x: 24300
          'y': 23000
          offset_x: 15
          offset_y: 30
      - id: '20'
        icon:
          name: mdi:broom
          x: 27500
          'y': 22500
        label:
          text: Q Lara
          x: 27500
          'y': 22500
          offset_x: 5
          offset_y: 25
      - id: '21'
        icon:
          name: mdi:broom
          x: 32000
          'y': 23500
        label:
          text: Suíte
          x: 32000
          'y': 23500
          offset_y: 35
      - id: '22'
        icon:
          name: mdi:broom
          x: 26000
          'y': 24000
        label:
          text: Corredor
          x: 26000
          'y': 24000
          offset_x: 40
          offset_y: -5
  - template: vacuum_clean_zone
  - template: vacuum_clean_zone_predefined
    predefined_selections:
      - zones:
          - - 22574
            - 25230
            - 24596
            - 26716
        label:
          text: Comida
          x: 25000
          'y': 27500
          offset_y: 35
        icon:
          name: mdi:food
          x: 25000
          'y': 27500
      - zones:
          - - 19758
            - 27051
            - 23328
            - 28072
        label:
          text: Entrada
          x: 21500
          'y': 26500
          offset_y: 30
        icon:
          name: mdi:broom
          x: 21500
          'y': 26500
  - template: vacuum_goto
card_mod:
  style: |
    ha-card {
      --map-card-room-label-color: white;
      --map-card-room-label-font-size: 15px;
      --map-card-room-icon-background-color: white;
      --map-card-predefined-rectangle-label-color: white;
      --map-card-predefined-rectangle-label-font-size: 15px; 
      --map-card-predefined-rectangle-icon-background-color: white;
      --map-card-predefined-rectangle-fill-color-selected: grey;
      --map-card-predefined-rectangle-line-color: blue; 
      --map-card-zoomer-background: black;
    }
    svg text {
      stroke: black;
      font-weight: bold;
```

**Reply by PiotrMachowski** [reply]
You can follow these steps:
1. Open card editor
2. Click "Generate static config"
3. Open yaml card code editor
4. Copy whole `icons` section
5. Close the editor **without saving**
6. Open the editor again and paste copied `icons` section
7. Remove unwanted icons from config

**Reply by rodolfomachado** [reply]
That worked! Tks
gonna send you some coffe

**Reply by lindsaymarkward** [reply]
Thanks for this card :) 
I have 14 tiles and want to keep 13 of them.
Am I right that the way to disable one tile is to follow this 7-step process, copying the manual config and removing the tiles you don't want, but keeping all the others?

**Reply by PiotrMachowski** [reply]
There's a simpler way now:
1. Open card editor
2. Hover over the icon you want to hide to find out its id
3. Add following config to the card's yaml config:
   ```yaml
   append_icons: true
   icons:
     - icon_id: PUT_THE_ID_HERE
       replace_config: true
       remove: true
   ```
4. Done

**Reply by lindsaymarkward** [reply]
Great, thanks. I was interested in removing a tile (not icon). So for others looking at this in the future...  
First, edit the card; then hovering will show you the tile_id. The code I used to hide the tight mopping tile was as below. I did not need to change anything else.

```
    append_tiles: true
    tiles:
    - tile_id: tight_mopping
      replace_config: true
      remove: true
```
