### DISCUSSION TITLE
Disabling map controls

### DISCUSSION THREAD

**Discussion by PiotrMachowski** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#163] [FAQ]
If you want to use the map just as a preview (e.g. because your vacuum doesn't handle map properly - _I'm looking at you gen1!_) you can disable map controls using following config:
```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.roborock_vacuum_s5
vacuum_platform: default
map_locked: false
map_modes:
  - template: vacuum_goto_predefined
    run_immediately: true
```
![image](https://user-images.githubusercontent.com/6118709/142119054-8ab10d36-1d26-4ca1-a17c-ebd0def5ee2f.png)
