### DISCUSSION TITLE
map rotation

### DISCUSSION THREAD

**Discussion by AlexKash500** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#179] [General]
Hello

Is there way to rotate map and zones coordinates with some option in the card?

**Comment by PiotrMachowski** [comment]
Hi, could you describe this case a little bit more?

**Comment by AlexKash500** [comment]
for example
now card is: 
![image](https://user-images.githubusercontent.com/69472472/142404888-4902774b-67b2-4342-8af1-1036d9899381.png)


is there way to rotate like this:
![image](https://user-images.githubusercontent.com/69472472/142405268-e06d6f4a-44ea-4b70-afd7-4875383a12de.png)

**Comment by PiotrMachowski** [comment]
Well, can't you just rotate the image...?

**Comment by AlexKash500** [comment]
Yes I can. do calibration points need to be changed too?

**Reply by PiotrMachowski** [reply]
Yes, they have to be updated

**Comment by AlexKash500** [comment]
so there is no option to do rotate automatically. pitty :). thank for you great work!

**Comment by gogenzuller** [comment]
I am also looking for a way to use the map at different angles of rotation. My first version robot often rotates the map at 180 degrees. Earlier I made two cards with two different sets of coordinates for predefined zones. And I used the one that fits the current angle of rotation of the map.
But I would like to have one card. This could be done, for example, if templates could be used in the card. For example, make several files with coordinates for different angles of map rotation and refer to them as 
```
  - template: vacuum_clean_zone_predefined
    predefined_selections: 
      - zones: >
      [[[      
        return "!include /config/livingroom_"+states['input_number.map_current_rotation_angel'].state+"_deg.yaml"
      ]]]
```
But, if I understand correctly, now it is impossible to do this.

**Reply by PiotrMachowski** [reply]
@gogenzuller this is a completely different topic ;) buuuuuuuuuut it is already possible to use entities as input for zones (I have forgot to mention it in documentation though...)

```yaml
  - template: vacuum_clean_zone_predefined
    predefined_selections: 
      - zones: sensor.zones_after_rotation
```
or
```yaml
  - template: vacuum_clean_zone_predefined
    predefined_selections: 
      - zones: sensor.zones_after_rotation.attributes.kitchen
```
