### DISCUSSION TITLE
Change the language

### DISCUSSION THREAD

**Discussion by m4r0n** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#181] [Q&A] [answered]
Please let me know how to change the language of this card?

**Comment by PiotrMachowski** [comment, marked as answer]
Language should be automatically set to language set in HA. If it doesn't work you can force selected language using following config:
```
type: custom:xiaomi-vacuum-map-card
entity: vacuum.xiaomi_vacuum
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
language: it
```
