### DISCUSSION TITLE
Zone

### DISCUSSION THREAD

**Discussion by m4r0n** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#185] [General]
Please let me know why the zones are displayed in this way?

```
 "zone": [
      [
        -0.772357723577235,
        0.7101626016260152,
        3.894308943089432,
        -3.2898373983739857
      ]
```

What is the reason for this? I compare this data with the general configuration, and it is completely different there.

**Comment by PiotrMachowski** [comment]
Everything is ok.

Different vacuum use different coordinate systems, the one from general configuration uses 25500-based coordinate system, where every coordinate must be an integer. Your vacuum uses 0-based system, where every coordinate is a floating-point number.

**Comment by m4r0n** [comment]
How then to find x and y and also the offset_y?
```
- template: vacuum_clean_segment
    predefined_selections:
      - id: 1
        outline: [[ ... ]]
        label:
          text: "Bedroom"
          x: 22932
          y: 30339
          offset_y: 35
        icon:
          name: "mdi:bed"
          x: 22932
          y: 30339
```
