### DISCUSSION TITLE
Clean room service

### DISCUSSION THREAD

**Discussion by Flavio5** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#187] [Q&A] [answered]
Hi, I have a Xiaomi Vacuum Mop P, it works well in your new card as KrzysztofHajdamowicz/miio2 platform.
About clean room service, normally I use this template:

```
service: vacuum.send_command
data:
  command: set_mode_withroom
  params:
    - 0
    - 1
    - 1
    - 11
target:
  entity_id: vacuum.aspirapolvere_pro
```
where params:
params:
- 0 (0=Normal Vacuum, 1=Edge only)
- 1 (Number of repeats)
- 1 (Quantity of rooms)
- 14 (Room ID)

I tried to configure the service in the card but something goes wrong. I think the problem is '[[selection]]' because if i replace it with the number of a room, the robot starts.
What is wrong?

```
type: custom:xiaomi-vacuum-map-card
entity: vacuum.aspirapolvere_pro
title: Aspirapolvere Pro
vacuum_platform: KrzysztofHajdamowicz/miio2
map_source:
  camera: camera.mappa_aspirapolvere_pro
calibration_source:
  camera: true
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - name: Pulisci stanze
    icon: mdi:floor-plan
    selection_type: ROOM
    max_selections: 1
    repeats_type: NONE
    service_call_schema:
      service: vacuum.send_command
      service_data:
        entity_id: '[[entity_id]]'
        command: set_mode_withroom
        params:
          - 0
          - 1
          - 1
          - '[[selection]]'
    predefined_selections:
      - id: 10
        label:
          text: Studio
          x: 2
          'y': -0.2
        icon:
          name: mdi:desk
          x: 2
          'y': 0.7
      - id: 11
        label:
          text: Bagno
          x: 6.4
          'y': 0.5
        icon:
          name: mdi:bathtub
          x: 6.4
          'y': 1.3
      - id: 12
        label:
          text: Anticamera
          x: 5.1
          'y': -0.3
        icon:
          name: mdi:home-floor-a
          x: 5.1
          'y': 0.5
language: it
```

**Comment by PiotrMachowski** [comment, marked as answer]
Can you try to hold the play button and see how does service call look like? If it will be too big for popup it will be written in browser's console as well

**Reply by Flavio5** [reply]
The service call looks like this.
Probably the error are the extra square brackets in id_room

```
{
  "domain": "vacuum",
  "service": "send_command",
  "serviceData": {
    "entity_id": "vacuum.aspirapolvere_pro",
    "command": "set_mode_withroom",
    "params": [
      0,
      1,
      1,
      [
        12
      ]
    ]
  }
}
```

**Reply by PiotrMachowski** [reply]
It's not an error, it works as designed (it is not aware about external brackets). You can create a script that will "unpack" this data and use it instead (_DISCLAIMER: not tested code_):
```yaml
vacuum_set_mode_withroom:
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: "{{ entity_id }}"
        command: set_mode_withroom
        params: "{{ [0, 1, 1, room[0]] }}"
```
and in card:
```yaml
  - name: Pulisci stanze
    icon: mdi:floor-plan
    selection_type: ROOM
    max_selections: 1
    repeats_type: NONE
    service_call_schema:
      service: script.vacuum_set_mode_withroom
      service_data:
        entity_id: '[[entity_id]]'
        room: '[[selection]]'
```

**Reply by Flavio5** [reply]
Thanks!

It works with
params: [ 0, 1, 1, "{{room[0]}}"]

Thanks for this new card!

**Reply by PiotrMachowski** [reply]
Right, I have forgot about braces (updated)

**Reply by PiotrMachowski** [reply]
By the way, you can add repeats as well:
```yaml
vacuum_set_mode_withroom:
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: "{{ entity_id }}"
        command: set_mode_withroom
        params: "{{ [0, repeats, 1, room[0]] }}"
```
```yaml
  - name: Pulisci stanze
    icon: mdi:floor-plan
    selection_type: ROOM
    max_selections: 1
    repeats_type: EXTERNAL
    max_repeats: 5
    service_call_schema:
      service: script.vacuum_set_mode_withroom
      service_data:
        entity_id: '[[entity_id]]'
        room: '[[selection]]'
        repeats: '[[repeats]]'
```

**Reply by baggein** [reply]
Hi! Sorry, I'm a big newbie :)

I am trying to do a multi-select of rooms.
I create a script from your post and I get the error: "Message malformed: extra keys not allowed @ data ['vacuum_set_mode_withroom']"

What am I doing wrong?

**Reply by PiotrMachowski** [reply]
@baggein where have you put this code?

**Reply by baggein** [reply]
> @baggein where have you put this code?

Scripts->New script->
```
vacuum_set_mode_withroom:
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: "{{ entity_id }}"
        command: set_mode_withroom
        params: "{{ [0, 1, 1, room[0]] }}"
```
add: The formatting in the script is correct, it's just not inserted correctly here.

PS: I continue to get acquainted with the new version - it seems I begin to understand that this can be done differently :)
I beg your pardon.

**Reply by PiotrMachowski** [reply]
@baggein If you paste it in UI script editor you just have to skip first line: `vacuum_set_mode_withroom:`

**Comment by soulcola** [comment]
will it works, if i select more than 1 room in card?

**Reply by PiotrMachowski** [reply]
No, it won't

**Comment by soulcola** [comment]
So is it possible to send [[selection]] data without brackets?
Maybe you can add set_mode_withroom method to marotoweb/viomise to vacuum_clean_segment template, because it is only way to clean by room ID in this integration

**Reply by PiotrMachowski** [reply]
Yes, it's possible now using `[[selection_unwrapped]]`.

Card's config can look like this:
```yaml
  - name: Clean room
    icon: mdi:floor-plan
    selection_type: ROOM
    max_selections: 1
    repeats_type: EXTERNAL
    max_repeats: 5
    service_call_schema:
      service: vacuum.send_command
      service_data:
        entity_id: '[[entity_id]]'
        command: set_mode_withroom
        params:
          - 0
          - '[[repeats]]'
          - 1
          - '[[selection_unwrapped]]'
```

I will add it to template if you confirm that it works.

**Comment by soulcola** [comment]
Unfortunately not working.
 ```{
  "domain": "vacuum",
  "service": "send_command",
  "serviceData": {
    "entity_id": "vacuum.viomi_se",
    "command": "set_mode_withroom",
    "params": [
      0,
      1,
      1,
      "13"
    ]
  }
}
```



I think service wait integer, but card send "string"

**Reply by PiotrMachowski** [reply]
Yeah, that's what I was afraid of. This version should work:
```yaml
  - name: Clean room
    icon: mdi:floor-plan
    selection_type: ROOM
    max_selections: 1
    repeats_type: EXTERNAL
    max_repeats: 5
    service_call_schema:
      service: vacuum.send_command
      service_data:
        entity_id: '[[entity_id]]'
        command: set_mode_withroom
        params: "[ 0, [[repeats]], 1, [[selection_unwrapped]] ]|[[jsonify]]"
```

btw, please reply in the same thread.

**Comment by soulcola** [comment]
Yes, it works correct with room IDs.

But there is first parameter with vacuum type (0=Sweep, 1=Sweep&Mop, 2=Mop). 
Is it possible to add there attribute value? In my my case template would be {{ state_attr("vacuum.viomi_se", "is_mop")}}?

**Reply by PiotrMachowski** [reply]
No, it's not possible

**Reply by soulcola** [reply]
In this case it will work only with 1 selected room with this config:
```
    service_call_schema:
      service: vacuum.send_command
      service_data:
        entity_id: '[[entity_id]]'
        command: set_mode_withroom
        params:
          - '{{state_attr("vacuum.viomi_se", "is_mop")}}'
          - 1
          - 1
          - '[[selection_unwrapped]]|[[jsonify]]'
```

**Reply by PiotrMachowski** [reply]
Nope, it won't work

**Reply by soulcola** [reply]
I can confirm, that it works with 1 selected room
```
{
  "domain": "vacuum",
  "service": "send_command",
  "serviceData": {
    "entity_id": "vacuum.viomi_se",
    "command": "set_mode_withroom",
    "params": [
      "{{state_attr(\"vacuum.viomi_se\", \"is_mop\")}}",
      1,
      1,
      13
    ]
  }
}
```

**Reply by PiotrMachowski** [reply]
But you can't use these templates in this card: `{{state_attr("vacuum.viomi_se", "is_mop")}}`, how have you executed it?

**Reply by PiotrMachowski** [reply]
Hmmmmm, I have checked it and it actually seems to be possible...

**Reply by PiotrMachowski** [reply]
Ok, I am actually surprised. In this case the universal config is:
```yaml

  - name: Clean room
    icon: mdi:floor-plan
    selection_type: ROOM
    max_selections: 1
    repeats_type: EXTERNAL
    max_repeats: 5
    service_call_schema:
      service: vacuum.send_command
      service_data:
        entity_id: '[[entity_id]]'
        command: set_mode_withroom
        params:
          - '{{state_attr("[[entity_id]]", "is_mop")}}'
          - '[[repeats]]'
          - 1
          - '[[selection_unwrapped]]|[[jsonify]]'
```

**Reply by soulcola** [reply]
I don't know how, but it correctly takes is_mop attribute and vacuum goes to the selected room and with selected sweep type

**Reply by soulcola** [reply]
but if selected more than 1 room - nothing happens and long press "play" button doesn't show service call

**Reply by soulcola** [reply]
```
'[[selection_unwrapped]]| replace('' " '', '''')'

```
this template also work, but also with 1 selected room

**Reply by PiotrMachowski** [reply]
Yup, that's why there was `max_selections: 1` config ;)

Here you have an updated version that supports multiple selections:
```yaml
  - name: Clean room
    icon: mdi:floor-plan
    selection_type: ROOM
    max_selections: 5
    repeats_type: EXTERNAL
    max_repeats: 5
    service_call_schema:
      service: vacuum.send_command
      service_data:
        entity_id: '[[entity_id]]'
        command: set_mode_withroom
        params: '[ "{{state_attr(\"[[entity_id]]\", \"is_mop\")}}", [[repeats]], [[selection_size]], [[selection_unwrapped]] ]|[[jsonify]]'
```

**Reply by soulcola** [reply]
I think 2nd arg is not repeats count.
Seems it is vacuum operation (0=stop, 1=start, 2=pause)
Need to test it
3rd argument - selected rooms count

**Reply by soulcola** [reply]
It seems that it work properly! 2nd param must be always 1, it is not clear, what it means, but works only with value 1.
Thank you for your help!

**Reply by PiotrMachowski** [reply]
Ok, I have found somewhere that it is repeats number, maybe it was for a different model.

I will add it to viomise platform

**Reply by thumDer** [reply]
Unfortunately the above example is not working for me. It says `name 'selection_size' is not defined`
I've found an alternate method using your additional script workaround: https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/187#discussioncomment-3023712:

**Comment by thumDer** [comment]
Thanks @PiotrMachowski for the additional script trick! Since the zone cleaning is not working with viomi se anymore this is how I solved multiroom cleaning:

card config, with room data extracted from [camera](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/317):
```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.viomi_se
vacuum_platform: marotoweb/viomise
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_modes:
  - name: Rooms
    icon: mdi:floor-plan
    selection_type: ROOM
    service_call_schema:
      service: script.viomi_set_mode_withroom
      service_data:
        entity_id: '[[entity_id]]'
        rooms: '[[selection]]'
    predefined_selections:
      - id: 13
        label:
          text: Bedroom
          x: -1.15
          'y': -5.2
          offset_y: 35
        icon:
          name: mdi:broom
          x: -1.15
          'y': -5.2
      - id: 11
        label:
          text: Bathroom
          x: 1.6749999999999998
          'y': -5.5
          offset_y: 35
        icon:
          name: mdi:broom
          x: 1.6749999999999998
          'y': -5.5
      - id: 12
        label:
          text: Lobby
          x: 1.45
          'y': -4.125
          offset_y: 35
        icon:
          name: mdi:broom
          x: 1.45
          'y': -4.125
      - id: 10
        label:
          text: Living Room
          x: -0.3750000000000001
          'y': -1.35
          offset_y: 35
        icon:
          name: mdi:broom
          x: -0.3750000000000001
          'y': -1.35
```

and the script:
```yaml
viomi_set_mode_withroom:
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: "{{ entity_id }}"
        command: set_mode_withroom
        params: "{{ [0, 1, rooms|count] + rooms }}"
```

**Reply by PiotrMachowski** [reply]
@thumDer nicely done 👍 you can use this service directly in the card as well:

```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.viomi_se
vacuum_platform: marotoweb/viomise
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_modes:
  - name: Rooms
    icon: mdi:floor-plan
    selection_type: ROOM
    service_call_schema:
      service: vacuum.send_command
      service_data:
        entity_id: '[[entity_id]]'
        command: set_mode_withroom
        params: '[ 0, 1, [[selection_size]], [[selection_unwrapped]] ]'
    predefined_selections:
      ...
```

**Reply by thumDer** [reply]
unfortunately, as I mentioned in https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/187#discussioncomment-3023755 , this way I get an error `name 'selection_size' is not defined`

**Reply by PiotrMachowski** [reply]
@thumDer do you have the latest version of the card installed?

**Reply by thumDer** [reply]
yes, it is v2.0.11

**Reply by PiotrMachowski** [reply]
That's weird, it should work without any problems. Have you tried this config that I have posted?

**Reply by thumDer** [reply]
I'll try the exact same config tonight, and get back to you!

**Reply by thumDer** [reply]
Sorry for the late answer, just wanted to say that I created a new card for testing purposes, copied your config, and it worked perfectly. I have no idea what is different since then, just wanted to report back.
Thanks for your efforts and this great card!

**Comment by mggl89** [comment]
Hey! Can you help me please. I have a Xiaomi Trouver LDS finder (p2036)& I don't understand why it doesn't work. I have this error...
Failed to call service xiaomi_miot/call_action. Service not found 
```yaml
 - type: custom:xiaomi-vacuum-map-card
              title: Vacuum
              entity: vacuum.p2036_2418c6128faa
              vacuum_platform: default
              map_source:
                camera: camera.xiaomi_cloud_map_extractor
              calibration_source:
                camera: true
              map_modes:
                - template: vacuum_goto
                - template: vacuum_clean_zone
                  max_selections: 1
                  repeats_type: 5
                  service_call_schema:
                    service: xiaomi_miot.call_action
                    service_data:
                      entity_id: vacuum.p2036_2418c6128faa
                      siid: 4
                      aiid: 1
                      params:
                        - piid: 1
                          value: 19
                        - piid: 10
                          value: '{"areas":[[[[selection_unwrapped]],[[repeats]],1,1]]}'
                      force_params: true
```

**Reply by PiotrMachowski** [reply]
Which integration do you use?

**Reply by mggl89** [reply]
I use Xiaomi_miot

**Comment by mggl89** [comment]
so, I understand what's wrong: I had to use this service: **service: xiaomi_miot_raw.call_action**. But I've got another error: extra keys not allowed @ data['params']. I think it happens cause my robot has only 6 objects in MiOT

**Reply by PiotrMachowski** [reply]
Please respond in the same thread.

You use Xiaomi MIoT Raw, not Xiaomi MIoT i doing know how service calls work there

**Reply by cataseven** [reply]
> Please respond in the same thread.
> 
> You use Xiaomi MIoT Raw, not Xiaomi MIoT i doing know how service calls work there

Can you please add Miot integration also.

I am trying to call https://home.miot-spec.com/spec/viomi.vacuum.v13

siid:4
aiid:13

but cant get room cleaning

https://home.miot-spec.com/spec/viomi.vacuum.v13 (please right click and select translate to english)

```
type: custom:xiaomi-vacuum-map-card
entity: vacuum.v13_cloud_638430
preset_name: Downstairs
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_modes:
  - template: vacuum_clean_segment
    repeats_type: NONE
    max_selections: 4
    predefined_selections:
      - id: 10
        outline:
          - - -2
            - -12.85
          - - -2
            - -12.5
          - - -2
            - -9.25
          - - -2.85
            - -9.25
          - - -2.85
            - -8.7
          - - -2.85
            - -7.85
          - - -1.75
            - -7.85
          - - -1.75
            - -7.5
          - - 0.4
            - -7.5
          - - 0.4
            - -12.85
      - id: 11
        outline:
          - - -4.45
            - -11.7
          - - -4.45
            - -8.05
          - - -2.85
            - -8.05
          - - -2.85
            - -11.7
      - id: 12
        outline:
          - - -6.6
            - -13.75
          - - -6.6
            - -13.75
          - - -6.6
            - -10.9
          - - -4.4
            - -10.9
          - - -4.4
            - -12.05
          - - -4.8
            - -12.05
          - - -4.8
            - -13.75
      - id: 13
        outline:
          - - -4.45
            - -9
          - - -5.95
            - -9
          - - -5.95
            - -7.2
          - - -4.9
            - -7.2
          - - -4.9
            - -8.05
          - - -4.45
            - -8.05
      - id: 14
        outline:
          - - -4.9
            - -8.05
          - - -4.9
            - -6.4
          - - -4.6
            - -6.4
          - - -4.6
            - -5.3
          - - -6
            - -5.3
          - - -6
            - -1.2
          - - -2.95
            - -1.2
          - - -2.95
            - 0.35
          - - 0.7
            - 0.35
          - - 0.7
            - -6.9
          - - -2.85
            - -6.9
          - - -2.85
            - -8.05
  - template: vacuum_goto
    repeats_type: NONE
  - template: vacuum_clean_zone
    repeats_type: NONE
  - template: vacuum_follow_path
    repeats_type: NONE
map_locked: false
two_finger_pan: true
icons: []
tiles: []
```

```
service: xiaomi_miot_raw.call_action
data:
  entity_id: vacuum.v13_cloud_638430
  siid: 4
  aiid: 13
  inn:
    - piid: 21
      value: 1
    - piid: 22
      value: 1
    - piid: 20
      value: "????"
```

**Reply by PiotrMachowski** [reply]
@cataseven I think it should look like this:

```yaml
service: xiaomi_miot_raw.call_action
data:
  entity_id: vacuum.v13_cloud_638430
  siid: 4
  aiid: 13
  inn:
    - piid: 21
      value: 1
    - piid: 22
      value: 1
    - piid: 20
      value: "11,12,13"
```

**Reply by AYgrik** [reply]
Hello,
Is it possible, after installing the mop into the vacuum cleaner, to start cleaning with the mop?
If you start a full cleaning or select zone cleaning, then the vacuum cleaner does not move in a straight line when cleaning, but as if wiping the floor.
But if you select map_modes:  - template: vacuum_clean_segment or use in the script
```
      sequence:
        - service: vacuum.send_command
          data:
            entity_id: "{{ entity_id }}"
            command: set_mode_withroom
            params: "{{ [0, 1, rooms|count] + rooms }}"
```

 , then the vacuum cleaner moves in a straight line, but at the same time it consumes water.
I found a way to do this by calling the service manually. Changing the first digit in the parameters, replacing 0 with 1.
```
service: vacuum.send_command
data:
  command: set_mode_withroom
  params:
    - 1
    - 1
    - 1
    - 16
target:
  entity_id: vacuum.vacuum
```
Is it possible to run a vacuum cleaner in several rooms by choice with this parameter if a mop is installed (in the attributes "Mop available" = 1)?

I am using the integration "vacuum-styj02ym" and platform "KrzysztofHajdamowicz/miio2"

**Reply by PiotrMachowski** [reply]
Is there an entity/attribute that tells if the mop is attached to the vacuum?

**Reply by AYgrik** [reply]
Yes. Attribute: "Is mop" = 1.

**Reply by PiotrMachowski** [reply]
In such case you can just use `{{ state_attr('vacuum.vacuum', 'is_mop') }}`

```yaml
    sequence:
        - service: vacuum.send_command
          data:
            entity_id: "{{ entity_id }}"
            command: set_mode_withroom
            params: "{{ [state_attr('vacuum.vacuum', 'is_mop'), 1, rooms|count] + rooms }}"
```
