### DISCUSSION TITLE
Trying to figure out autogenerated map_modes

### DISCUSSION THREAD

**Discussion by gsotiriou** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#193] [Q&A]
Hello, according to documentation `map_modes` are auto-generated. My initial question would be based on what are the `map_modes` auto-generated? Because with a configuration like this (ommiting `map_modes` as it is *Optional*):
```yaml
cards:
  - type: custom:xiaomi-vacuum-map-card
    title: Vacuum Cleaner
    preset_name: Live map
    entity: vacuum.vacuum_cleaner
    map_source:
      camera: camera.xiaomi_cloud_map_extractor
    calibration_source:
      camera: true
```
I am only getting 2 possible options:
![image](https://user-images.githubusercontent.com/34280016/142739074-bc758a7a-2288-4351-8d9a-51d8534ca11e.png)

On the other hand if I go with the way of specifying `map_modes` according to the [demo config](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/blob/master/docs/demo_config.yaml#L33) then I don't know how to obtain coordinates for `outline` or `x` , `y` for the `label:`

If the `map_modes` depend on data returned from my Mi Account , then my account and my vacuum seemingly support rooms. So they should be working out of the box, am I correct?

I guess I'm a little confused. Again this is a **tremendous** update. You brought us the whole MiHome app inside of Home Assistant and I couldn't be more grateful for this.

Kind regards,
-G
