### DISCUSSION TITLE
Room cleaning with repeats - another way

### DISCUSSION THREAD

**Discussion by PiotrMachowski** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#204] [FAQ]
If you want to clean rooms using room numbers with repeats you can add following entry in `map_modes`:
```yaml
  - template: vacuum_clean_segment
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: vacuum.send_command
      service_data:
        command: app_segment_clean
        entity_id: '[[entity_id]]'
        params:
          - segments: '[[selection]]'
            repeat: '[[repeats]]'
```

| :warning: **WARNING** :warning: |
| --- |
| This configuration might not work for all vacuum models! |
