### DISCUSSION TITLE
Room cleaning issues

### DISCUSSION THREAD

**Discussion by ITHKS** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#207] [Q&A] [answered]
Hi there,

I've just started to implement the lovelace card for my Roborock S5 Max and so far it's been going good but I'm facing issues with vacuum_clean_segment where the vacuum will start, back out of the dock, stop, then say "Selective room cleaning complete" and go right back into the dock.

![Vacuum](https://user-images.githubusercontent.com/3344072/142929797-d755aef5-5812-4b62-b4fc-8ef0463f1aa9.PNG)

I'm using the xiami cloud map extractor to get the map, for the lovelace and I used the FloleVac app to get the coordinate for the different outlines and positions.

Here is my config
```yaml
type: custom:xiaomi-vacuum-map-card
title: Dalek
preset_name: Live map
entity: vacuum.dalek
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_locked: true
vacuum_platform: default
map_modes:
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 1
        outline:
          - - 20300
            - 25100
          - - 20300
            - 27150
          - - 21150
            - 27150
          - - 21150
            - 26800
          - - 21350
            - 26800
          - - 21350
            - 29850
          - - 26800
            - 29850
          - - 26800
            - 25100
          - - 24250
            - 25100
          - - 24250
            - 24850
          - - 22350
            - 24850
          - - 22350
            - 26250
          - - 22050
            - 26250
          - - 22000
            - 25900
          - - 21350
            - 25900
          - - 21350
            - 25100
        label:
          text: Livingroom
          x: 23950
          'y': 27300
          offset_y: 35
        icon:
          name: mdi:television
          x: 23950
          'y': 27300
      - id: 2
        outline:
          - - 23050
            - 24900
          - - 24500
            - 24900
          - - 24500
            - 24200
          - - 23900
            - 24200
          - - 23900
            - 21400
          - - 20550
            - 21400
          - - 20550
            - 22350
          - - 22050
            - 22350
          - - 22050
            - 24200
          - - 23050
            - 24200
        label:
          text: Kitchen
          x: 23050
          'y': 23350
          offset_y: 35
        icon:
          name: mdi:broom
          x: 23050
          'y': 23350
      - id: 3
        outline:
          - - 19650
            - 22000
          - - 19950
            - 22000
          - - 19950
            - 22300
          - - 20550
            - 22350
          - - 20550
            - 21400
          - - 20550
            - 20550
          - - 20750
            - 20550
          - - 20750
            - 19550
          - - 20500
            - 19550
          - - 20500
            - 19100
          - - 19900
            - 19100
          - - 19900
            - 18800
          - - 18300
            - 18800
          - - 18300
            - 20800
        label:
          text: Entry
          x: 19600
          'y': 20150
          offset_y: 35
        icon:
          name: mdi:door
          x: 19600
          'y': 20150
  - template: vacuum_goto
  - template: vacuum_goto_predefined
    predefined_selections:
      - position:
          - 25500
          - 29350
        label:
          text: Sofa
          x: 25500
          'y': 29350
          offset_y: 35
        icon:
          name: mdi:sofa
          x: 25500
          'y': 29350
  - template: vacuum_clean_zone
  - template: vacuum_clean_zone_predefined
    predefined_selections:
      - zones:
          - - 20143
            - 24856
            - 26893
            - 29856
        label:
          text: Livingroom
          x: 23950
          'y': 27300
          offset_y: 35
        icon:
          name: mdi:television
          x: 23950
          'y': 27300
```

Pin & Go, Points, Zone cleanup and Zone list works flawless but for some reason not the room cleanup.
