### DISCUSSION TITLE
Error "Invalid calibration" when using Map Extractor

### DISCUSSION THREAD

**Discussion by cranxi** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#209] [Q&A] [answered]
Hi there, first of all thanks for all your time in making this card.

I tried to set-up the card by using the map extractor. When following the instructions I'm getting the error in the card: "Invalid calibration, please check your configuration".

The code so far:
```
type: custom:xiaomi-vacuum-map-card
title: Xiaomi Vacuum Map Card
preset_name: Live map
entity: vacuum.hanna
vacuum_platform: KrzysztofHajdamowicz/miio2
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
```

The map extractor is working, I got the Roborock map in Home Assistant:
![image](https://user-images.githubusercontent.com/67916888/142952432-679a8270-8817-488a-ba73-7fd98fc99f88.png)

Not sure what I'm doing wrong here.

Thanks!

Darryl
