### DISCUSSION TITLE
Automatically zoom in the map

### DISCUSSION THREAD

**Discussion by Gooman-rus** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#227] [Q&A] [answered]
When I reload the page with the component or click the lock button, the map zooms out and becomes very small:
![image](https://user-images.githubusercontent.com/3216521/143535213-dd41bd75-e381-4092-9766-3efe95cbd5e8.png)

I can zoom it in using mouse wheel. But is there any ablity to zoom it in automatically with the predefined value?

**Comment by PiotrMachowski** [comment, marked as answer]
Actually from `v2.0.6` map doesn't automatically zoom in after locking.

You can configure default zoom level by adding `crop:` section in [map_source](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card#map-source-options):
```yaml
map_source:
  camera: camera.xyz
  crop:
    top: 100
    bottom: 140
    left: 10
    right: 39
```
