### DISCUSSION TITLE
The vacuum doesn't go to the coordinates in the lovecard

### DISCUSSION THREAD

**Discussion by amibumping** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#231] [Q&A] [answered]
Hi, first of all thank you for this awesome tool..

I wrote my config yesterday and today, but after the hard work of getting the coordinates for every room, when I click in one and send the vacuum, the card says for a moment invalid coordinates and then the vacuum starts moving but not in that room area.

This is my card config:
```
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.robot_aspirador
vacuum_platform: default
map_locked: true
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_zone_predefined
    predefined_selections:
      - zones:
          - - 24936
            - 22600
            - 29000
            - 25776
        label:
          text: Salón
          x: 27000
          'y': 24500
          offset_y: 35
        icon:
          name: mdi:television
          x: 27000
          'y': 24500
      - zones:
          - - 21600
            - 20600
            - 23075
            - 25300
        label:
          text: Cocina
          x: 22400
          'y': 23500
          offset_y: 35
        icon:
          name: mdi:microwave
          x: 22400
          'y': 23500
      - zones:
          - - 23220
            - 20600
            - 24800
            - 24400
        label:
          text: Noa
          x: 24000
          'y': 23500
          offset_y: 35
        icon:
          name: mdi:bed
          x: 24000
          'y': 23500
      - zones:
          - - 25436
            - 19700
            - 29000
            - 22350
        label:
          text: Juegos
          x: 27000
          'y': 21500
          offset_y: 35
        icon:
          name: mdi:teddy-bear
          x: 27000
          'y': 21500
      - zones:
          - - 24710
            - 26050
            - 29000
            - 28776
        label:
          text: Papás
          x: 27000
          'y': 27700
          offset_y: 35
        icon:
          name: mdi:bed
          x: 27000
          'y': 27700
      - zones:
          - - 21600
            - 25550
            - 23205
            - 27300
        label:
          text: Baño
          x: 22400
          'y': 26750
          offset_y: 35
        icon:
          name: mdi:paper-roll-outline
          x: 22400
          'y': 26750
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 1
        outline:
          - - 20800
            - 29100
          - - 24500
            - 29100
          - - 24500
            - 24409
          - - 23300
            - 24409
          - - 23300
            - 27350
          - - 20800
            - 27350
        label:
          text: Pasillo
          x: 22632
          'y': 28500
          offset_y: 35
        icon:
          name: mdi:coat-rack
          x: 22632
          'y': 28500
```
And map extractor config:
```
#Xiaomi Vacuum Map
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.1.10
    token: !secret
    username: !secret
    password: !secret
    draw: ['all']
    attributes:
      - calibration_points
```
This is the zones, I made them when the vacuum made the whole house plan after cleaning:
[https://i.imgur.com/NNAgXVj.png](https://i.imgur.com/NNAgXVj.png)

Thank you!
