### DISCUSSION TITLE
Best way to get coordinates

### DISCUSSION THREAD

**Discussion by nkgiovannivl** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#240] [General]
Hi All,

I want to know, how many ways are to get coordinates?, 

I can not find a tutorial for this, so below my way.

I'm using the raw map option on [Map Extrator](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor) to open with [roboMapViewer](https://github.com/marcelrv/XiaomiRobotVacuumProtocol/tree/master/RRMapFile), as [@PiotrMachowski](https://github.com/PiotrMachowski) indicates. Thanks PiotrMachowski!! awsome card!!!!

Mapextractor - camera conf:
```
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']     
    store_map_raw: true
    store_map_image: true
    store_map_path: "/tmp"
``` 
Re-start just map Extractor:
![image](https://user-images.githubusercontent.com/48342344/144894168-d135658c-cd19-43dc-b8dc-a5ab6ab95feb.png)

Copy RR Map File fto /tmp folder (as condigured in camera), sugested command on SSH Terminal [Map Extrator Retrieveng Map](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#retrieving-map), so pull the file to my local pc.

Extract all files of roboMapViewer and extecute .bat file:

![image](https://user-images.githubusercontent.com/48342344/144894842-2b91759a-49cf-4b27-a04b-b44c0e6fc4fd.png)

Pressing zoom buttons (1) will reset the "console" information (2):

![image](https://user-images.githubusercontent.com/48342344/144895029-b1d264e8-a22b-4a2c-8dfe-a17ae10441dc.png)

Press left click on any part of map will show the coordinates, for one point just one click.

![image](https://user-images.githubusercontent.com/48342344/144895268-f29bcc86-4823-4760-918d-5ae9eaabd64e.png)

For multiple points i need to post prcess the result, select text and copy to excel:

![image](https://user-images.githubusercontent.com/48342344/144895472-e999847f-18c4-4816-83c2-5f71d70041cd.png)

Delete A,B,C columns and replace text 'Goto command:  app_goto_target' with empty in D colums and copy result to notepad++

![image](https://user-images.githubusercontent.com/48342344/144895897-0d265b34-4e5d-4c3e-ba9b-44edf9d46807.png)

Replace /n/r to ',' (notepad ++ can create macros to make this task in a fast way).

![image](https://user-images.githubusercontent.com/48342344/144896693-34aa63bd-9014-4fea-9bd6-0f9bee184406.png)

Copy and Paste the result in your card configuration.

Reset console presing zoom buttons, to cick more points.

I'm using this procedure, but i'm havig curiosity how many ways are to get and process multiple coordinates in a good way, thanks!

PD:Sorry for my English, i'm not good...
