### DISCUSSION TITLE
Selecting more than 5 zones

### DISCUSSION THREAD

**Discussion by idogrf** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#264] [Q&A] [answered]
Hi,

Is there a way of selecting more than 5 zones when using Zones List?

**Comment by PiotrMachowski** [comment, marked as answer]
Sure, it's possible, but keep in mind that by default vacuums support max 5 zones.
```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.xiaomi_vacuum
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_modes:
  - template: vacuum_clean_zone
    max_selections: 42
```
