### DISCUSSION TITLE
Map reset after start a full cleanup

### DISCUSSION THREAD

**Discussion by skawsk** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#281] [General]
Hello there, I have a Roborock S1 and I setup lovelace-xiaomi-vacuum-map-card.
I spent several hours setting up the zones but the scheme displayed on the screen was simply recreated after activating a complete cleaning (scheduled task on the Xiaomi home application)

How can I prevent this from happening again and not lose the zones I created?

**Comment by PiotrMachowski** [comment]
You have to use zoned cleaning only

**Comment by skawsk** [comment]
I thank you for your answer.
Ok i will use zoned cleaning only.
I just recreate my room but for an unknown raison select the room and press play as not effect.
The ping "Successful" appears but the roborock not go to clean up.
This is my code : 
```
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_map
calibration_source:
  camera: true
entity: vacuum.rockrobo_vacuum_v1
vacuum_platform: default
map_locked: 'yes'
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_follow_path
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 1
        outline:
          - - 35636
            - 22851
          - - 35469
            - 21642
          - - 29005
            - 22643
          - - 29213
            - 23686
          - - 35594
            - 22768
        label:
          text: Couloir
          x: 1500000
          'y': 22678
          offset_y: 35
        icon:
          name: mdi:coat-rack
          x: 32218
          'y': 22678
      - id: 2
        outline:
          - - 35700
            - 22856
          - - 35488
            - 21585
          - - 37267
            - 21204
          - - 37521
            - 22602
          - - 35742
            - 22898
        label:
          text: SDB
          x: 1500000
          'y': 22106
        icon:
          name: mdi:shower
          x: 36603
          'y': 22106
      - id: 3
        outline:
          - - 34259
            - 23068
          - - 34979
            - 26456
          - - 38156
            - 25948
          - - 37479
            - 22432
          - - 34259
            - 23068
        label:
          text: Bureau
          x: 1500000
          'y': 25133
        icon:
          name: mdi:laptop
          x: 36166
          'y': 24720
      - id: 4
        outline:
          - - 32964
            - 23189
          - - 33121
            - 23895
          - - 31315
            - 24092
          - - 31708
            - 26841
          - - 34417
            - 26527
          - - 33985
            - 23699
          - - 33868
            - 22953
          - - 32964
            - 23189
        label:
          text: Chambre
          x: 1500000
          'y': 24720
        icon:
          name: mdi:bed
          x: 32887
          'y': 25133

```
