### DISCUSSION TITLE
Error message when using [[selection]]

### DISCUSSION THREAD

**Discussion by mellowism** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#282] [Q&A] [answered]
I've been struggling with understanding what I am doing wrong for some time now. I can't get map modes to work.
```
type: custom:xiaomi-vacuum-map-card
title: Første etasje
entity: vacuum.roborock_s6_pure
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_locked: true
map_modes:
  - name: Zones
    template: vacuum_clean_zone
    icon: mdi:select-drag
    selection_type: MANUAL_RECTANGLE
    max_selections: 5
    repeats_type: INTERNAL
    max_repeats: 5
    service_call_schema:
      service: xiaomi_miio.vacuum_clean_zone
      service_data:
        zone: '[[selection]]'
        repeats: '[[repeats]]'
        entity_id: '[[entity_id]]'
```

When I press the play button when adding a selection, I get an error message:
_Failed to call service xiaomi_miio/vacuum_clean_zone. None @ data['zone'][0]_

Any help is much appriciated.

**Comment by PiotrMachowski** [comment, marked as answer]
Have you tried this config?
```yaml
type: custom:xiaomi-vacuum-map-card
title: Første etasje
entity: vacuum.roborock_s6_pure
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_locked: true
map_modes:
  - template: vacuum_clean_zone
```
Or do you want to override service call schema?
