### DISCUSSION TITLE
I own 3 xiaomi vacuum cleaner robots

### DISCUSSION THREAD

**Discussion by lucrom61** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#329] [Q&A]
Is there a way to view the three maps on as many cards?
I don't understand where I'm wrong, the same map always appears.

**Comment by PiotrMachowski** [comment]
Each vacuum must have its own camera (you have to add `name` to cameras' configs), then you can configure 3 cards or 1 card with 2 additional presets

**Comment by lucrom61** [comment]
Configuration.Yaml I wrote it like this:

```yaml
   camera:
     - platform: xiaomi_cloud_map_extractor
       host: 192.168.188.161
       token: xxxxxxxxxxxx
       username: xxxxxxxxxxxxx
       password: xxxxxxx
       draw: ['all']
       name: Ambrogio
       attributes:
         - calibration_points
     - platform: xiaomi_cloud_map_extractor
       host: 192.168.188.160
       token: xxxxxxxxxxxx
       username: xxxxxxxxxxxxx
       password: xxxxxxxx
       draw: ['all']
       name: Spartaco
       attributes:
         - calibration_points
```
