### DISCUSSION TITLE
Xiaomi vacuum mop - water level

### DISCUSSION THREAD

**Discussion by kozlovdk** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#341] [Q&A] [answered]
Hi,
There is possibility after installation mop in vacuum, to change on card water level ? Like on official xiaomi app ?![IMG_20220129_195858.jpg](https://user-images.githubusercontent.com/97250361/151674063-aac77f93-ddd8-4114-a722-c9c313a8a3cb.jpg)

**Comment by PiotrMachowski** [comment, marked as answer]
Is it possible to do it using HA service call?

**Reply by kozlovdk** [reply]
After installation mop and water tank on the vacuum, on home assistant i just start vacuum and is working like a mop.
And also after changing water level on xiaomi app, on card in HA status Water Grade changed like on picture, 
1. low :11,
2. medium: 12, 
3. high: 13

Sorry if I mixed something, Im new with home assistance.
![mop](https://user-images.githubusercontent.com/97250361/151675640-9de40ada-c50a-4bfd-bca4-2d61f1c7f102.png)
![poziom](https://user-images.githubusercontent.com/97250361/151675807-9b3beaf9-fda1-4968-a984-ff7896d8867a.png)

**Reply by PiotrMachowski** [reply]
Which integration do you use?

**Reply by kozlovdk** [reply]
vacuum-styj02ym @KrzysztofHajdamowicz

**Reply by KrzysztofHajdamowicz** [reply]
I have this in scripts for HA:
```YAML
vacuum_water_grade_low:
  alias: Ilość wody niski
  sequence:
    - data:
        command: set_suction
        params: 11
      entity_id: vacuum.odkurzacz
      service: vacuum.send_command

vacuum_water_grade_medium:
  alias: Ilość wody średni
  sequence:
    - data:
        command: set_suction
        params: 12
      entity_id: vacuum.odkurzacz
      service: vacuum.send_command

vacuum_water_grade_high:
  alias: Ilość wody wysoki
  sequence:
    - data:
        command: set_suction
        params: 13
      entity_id: vacuum.odkurzacz
      service: vacuum.send_command

vacuum_set_silente:
  sequence:
    - data:
        fan_speed: Silent
      entity_id: vacuum.odkurzacz
      service: vacuum.set_fan_speed

vacuum_set_standard:
  sequence:
    - data:
        fan_speed: Standard
      entity_id: vacuum.odkurzacz
      service: vacuum.set_fan_speed

vacuum_set_medium:
  sequence:
    - data:
        fan_speed: Medium
      entity_id: vacuum.odkurzacz
      service: vacuum.set_fan_speed

vacuum_set_turbo:
  sequence:
    - data:
        fan_speed: Turbo
      entity_id: vacuum.odkurzacz
      service: vacuum.set_fan_speed

vacuum_set_light_on:
  sequence:
    - data:
        command: set_light
        params: 1
      entity_id: vacuum.odkurzacz
      service: vacuum.send_command

vacuum_set_light_off:
  sequence:
    - data:
        command: set_light
        params: 0
      entity_id: vacuum.odkurzacz
      service: vacuum.send_command

vacuum_set_mop_0:
  sequence:
    - data:
        command: set_mop
        params: 0
      entity_id: vacuum.odkurzacz
      service: vacuum.send_command

vacuum_set_mop_1:
  sequence:
    - data:
        command: set_mop
        params: 1
      entity_id: vacuum.odkurzacz
      service: vacuum.send_command

vacuum_set_mop_2:
  sequence:
    - data:
        command: set_mop
        params: 2
      entity_id: vacuum.odkurzacz
      service: vacuum.send_command
      ```

**Reply by PiotrMachowski** [reply]
Thanks @KrzysztofHajdamowicz, I will post an appropriate config (probably) tomorrow

**Reply by PiotrMachowski** [reply]
Can you check out this config? You can paste it in [![Open your Home Assistant instance and show your template developer tools.](https://my.home-assistant.io/badges/developer_template.svg)](https://my.home-assistant.io/redirect/developer_template/), provide entity id in the first line and append result to card's config
```yaml
{% set vacuum_entity = "vacuum.xiaomi_vacuum" %}
append_icons: true
icons:
  - icon: mdi:water-outline
    conditions:
      - entity: {{ vacuum_entity }}
        attribute: is_mop
        value: 1
      - entity: {{ vacuum_entity }}
        attribute: water_grade
        value: 11
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: {{ vacuum_entity }}
        command: set_suction
        params: 12
  - icon: mdi:water-opacity
    conditions:
      - entity: {{ vacuum_entity }}
        attribute: is_mop
        value: 1
      - entity: {{ vacuum_entity }}
        attribute: water_grade
        value: 12
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: {{ vacuum_entity }}
        command: set_suction
        params: 13
  - icon: mdi:water
    conditions:
      - entity: {{ vacuum_entity }}
        attribute: is_mop
        value: 1
      - entity: {{ vacuum_entity }}
        attribute: water_grade
        value: 13
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: {{ vacuum_entity }}
        command: set_suction
        params: 11
```

**Reply by kozlovdk** [reply]
Working! 
After installation mop and water tank on the card is the icon "drop". And after changing water lever on HA also change on official app.
![image](https://user-images.githubusercontent.com/97250361/151865965-0b8fbef1-326f-4775-915a-7177065defbd.png)

**Reply by johny-mnemonic** [reply]
Thanks for this, but seems like not all vacuums do have these attributes, at least not by default.
I am trying to do this for my S5 Max and it only have fan speed in attributes, while in original app it supports changing the amount of water it uses for mopping.
Is this something we can do here, or is this more for the vacuum integration i.e. Xiaomi Miio for S5 Max?

**Reply by PiotrMachowski** [reply]
@johny-mnemonic I'm afraid it needs to be added to Xiaomi Miio integration (at least appropriate attribute/entity)

**Reply by weemaba999** [reply]
> Working! After installation mop and water tank on the card is the icon "drop". And after changing water lever on HA also change on official app. ![image](https://user-images.githubusercontent.com/97250361/151865965-0b8fbef1-326f-4775-915a-7177065defbd.png)

Do you mind sharing your code @kozlovdk  ? I also added to my card, but it won't work...

**Reply by PiotrMachowski** [reply]
@weemaba999 that's my code from comment above

**Reply by weemaba999** [reply]
Oh yes, I meent when I adder your code to the card, the icons are not changing, thats why I wanten to see the final card of kozlov :-)

**Reply by weemaba999** [reply]
This is the code I use for mopping. But in this code, I need to use a input_select with room names to start the corresponding script. Maybe, you'll use this as inspiration for your config and expand your vacuum map card ? :-) I'd love to use the zone select also for the mopping. Actually it's pretty simple script, but need to know how to embed in your layout.

So actually:
* Embed the drop for water intensity as above
* embed the mop route : Standard vs Deep
* Also use the zones select for the mopping

below the code:

```yaml
  set_mopping_route:
    alias: Set mopping route
    fields:
      route:
        description: 'Mopping route - can be: standard | deep'
        example: standard
    sequence:
      - alias: Config variables
        variables:
          config_mopping_route:
            standard: 300
            deep: 301
          mopping_route: '{{ config_mopping_route[route]}}'
      - choose:
          - alias: Invalid mopping route value
            conditions:
              - condition: template
                value_template: '{{ route not in config_mopping_route|list }}'
            sequence:
              - service: system_log.write
                data:
                  message: >-
                    Invalid mopping_route value '{{ route }}'. Valid values are {{
                    config_mopping_route|list|join(', ') }}
                  level: warning
                  logger: roborock
        default:
          - alias: Set mopping route
            service: vacuum.send_command
            target:
              entity_id: vacuum.jarvis
            data:
              command: set_mop_mode
              params: '[{{ mopping_route }}]'
    mode: single

mop_gang:
    alias: Mop Gang
    sequence:
      - service: xiaomi_miio.vacuum_remote_control_stop
        target:
          entity_id: vacuum.jarvis
        data: {}
      - delay:
          hours: 0
          minutes: 0
          seconds: 2
          milliseconds: 0
      - service: script.set_mopping_route
        target:
          entity_id: vacuum.jarvis
        data:
          route: standard
      - service: vacuum.send_command
        target:
          entity_id: vacuum.jarvis
        data:
          command: app_segment_clean
          params:
            - 19
      
    mode: single
    icon: mdi:robot-vacuum
```

**Reply by PiotrMachowski** [reply]
Does your vacuum have an attribute/entity that shows current status of mop water intensity and mop route?

**Reply by weemaba999** [reply]
No, not as attributes, but I can change intensity & route

**Reply by PiotrMachowski** [reply]
Ok, in this case you can use following approach:
- create 2 input_selects to make it possible to read "current" value of water intensity/mop route
- create 2 automations that will send selected values to the vacuum
- add controls to the map card. Example:
  ```yaml
  append_icons: true
  icons:
    - icon: mdi:gauge-empty
      conditions:
        - entity: input_select.jarvis_mop_route
          value: "standard"
      tap_action:
        action: call-service
        service: input_select.select_next
        service_data:
          entity_id: input_select.jarvis_mop_route
          cycle: true
    - icon: mdi:gauge-full
      conditions:
        - entity: input_select.jarvis_mop_route
          value: "deep"
      tap_action:
        action: call-service
        service: input_select.select_next
        service_data:
          entity_id: input_select.jarvis_mop_route
          cycle: true
  ```
