### DISCUSSION TITLE
Adding/disabling icons/tiles

### DISCUSSION THREAD

**Discussion by Eckart0** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#351] [Q&A]
Hi,

everything works now!
I have added a section "icons" and another one "tiles" to append custom tiles/switches.

But I have still have a few questions that I can't figure out from the Github page.

- Is it possible to hide just some (not all) of the autogenerated tiles or icons without disabling the their entity globally in HA?
- I can't use the item "translations: true" oder "translation: de" in the tiles section. The whole card dissapears without a failure massage.
- "conditions:" Is it possible to set a condition like "less than" or "greater than"? E.g. to show the maintenance tiles only shortly before a maintenance is due.

Regards,
Eckart

**Comment by PiotrMachowski** [comment]
* No, you can only replace them with your own tiles/icons. You can:
  * Retrieve autogenerated configuration by double-clicking play button
  * Convert json to yaml using https://www.json2yaml.com/
  * Modify config and apply it to your card
* This feature works in a different way, you can check it out by retrieving autogenerated config (as described above)
  ```yaml
  translations:
    "Idle": "Inaktiv"
    "Remote control active": "Fernsteuerung aktiv"
    "Cleaning": "Säubern"
    "Returning home": "Kehre zur Ladestation zurück"
  ```  
* No, it's not possible. You can achieve it by creating an appropriate binary sensor
