### DISCUSSION TITLE
Odd shaped room mapping

### DISCUSSION THREAD

**Discussion by Fzibi21** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#372] [Q&A] [answered]
I have 2 rooms that are not square but L shaped.  How do I map those rooms out ?

**Comment by PiotrMachowski** [comment, marked as answer]
You can use cleaning by room id instead (if your vacuum supports it)
https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/317

**Reply by Fzibi21** [reply]
unfortunately not  that would be the only way ?

**Reply by PiotrMachowski** [reply]
You can also combine multiple rectangular zones into one "room" to be always selected at once:
```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.xiaomi_vacuum
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_clean_zone_predefined
    predefined_selections:
      - zones: [[25500, 25500, 26500, 26500]] # zone consisting of one rectangular selection
      - zones: [[24245, 25190, 27495, 27940], [27492, 26789, 28942, 27889]] # zone consisting of two rectangular selections
```
