### DISCUSSION TITLE
How to overlay a second "map_source"?

### DISCUSSION THREAD

**Discussion by Photelegy** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#389] [Q&A] [answered]
First of all, thank you very, very much for this awsome lovelace-card!!!

How can I use a .PNG-image (with transparent parts) as an overlay over the "camera.xiaomi_cloud_map_extractor"?

Before I found this lovelace-card ("lovelace-xiaomi-vacuum-map-card") I tried it with the "picture-elements"-card to see where my cleaner exactly is in my home.
This is the code and how it looked:
```
type: picture-elements
image: /local/homeplan/HomePlan3OG_Wohnung_WHITE.png
elements:
  - type: custom:xiaomi-vacuum-map-card
    entity: vacuum.roborock_vacuum_s5e
    calibration_points: null
    camera_calibration: true
    map_source:
      camera: camera.xiaomi_cloud_map_extractor
      crop:
        top: -75
        bottom: 50
        left: -24
        right: -79
    calibration_source:
      camera: true
    hold_action:
      action: vacuum.roborock_vacuum_s5e
    style:
      left: 14%
      top: 25.5%
      transform: scale(1.79)
      opacity: 80%
  - type: image
    image: /local/homeplan/HomePlan3OG_Wohnung_transp.png?v=1
    style:
      left: 0%
      top: 0%
      transform: scale(1)
      opacity: 100%
```
     
![Screenshot_picture-card](https://user-images.githubusercontent.com/61714583/165076923-249af6cb-ba96-4c5a-a11f-fd9829abc905.PNG)

Thank all of you for your ideas!!!
