### DISCUSSION TITLE
I don't know how to adjust the code for Rooms to work

### DISCUSSION THREAD

**Discussion by ericodeoliveira** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#396] [Q&A] [answered]
Good night,

I created the card, with some room settings, but I am not able to adjust the code so that it cleans the selected area of the room.

![image](https://user-images.githubusercontent.com/6044701/167532395-93678529-c019-432f-9028-8049b9bfbb27.png)

![image](https://user-images.githubusercontent.com/6044701/167532478-d52cddb6-8abc-4a93-b5ef-6d2529f12dc5.png)

```
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.roborock_s5_max
vacuum_platform: KrzysztofHajdamowicz/miio2
map_locked: false
language: pt-BR
map_modes:
  - template: vacuum_clean_zone_predefined
    predefined_selections:
      - zones:
          - - 23848
            - 24833
            - 24819
            - 25671
          - - 21851
            - 22210
            - 28146
            - 25035
      - zones:
          - - 21327
            - 25610
            - 24752
            - 27190
      - zones:
          - - 24785
            - 25061
            - 28243
            - 28128
      - zones:
          - - 24817
            - 28260
            - 27629
            - 31779
      - zones:
          - - 21198
            - 27194
            - 24752
            - 30584
title: Robô Aspirador
```
