### DISCUSSION TITLE
Problem with Dreame D9 integration

### DISCUSSION THREAD

**Discussion by foxx99** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#420] [Q&A] [answered]
Could You please help me, I'm trying to put my dreame D9 to work with HA. I've got maps from cloud map extractor, I've integrated D9 using Xiaomi miot (I've only got few attributes, if I use HACS dreame D9 integration I've got more like filter time left, brush time left). I've created this script in HA script menu:
```
alias: vacuum_clean_rooms
sequence:
  - service: xiaomi_miot.call_action
    data:
      entity_id: '{{entity_id}}'
      siid: 4
      aiid: 1
      params:
        - piid: 1
          value: 18
        - piid: 10
          value: >
            {% set ns = namespace(str_rooms='{"selects":[') %}  {%- for x in
            rooms -%}
              {% set ns.str_rooms = ns.str_rooms ~ '[' ~ x ~ ',' ~ repeats ~ ',0,2,' ~ loop.index ~ ']' %}
              {%- if not loop.last %}
               {%  set ns.str_rooms = ns.str_rooms ~ ',' %}
              {%- endif %}
            {%- endfor -%}  {% set ns.str_rooms = ns.str_rooms ~ ']}' %}   
            '{{ns.str_rooms}} 
      force_params: true
fields:
  rooms:
    description: Array of rooms ID
  repeats:
    description: Repeat zone
  entity_id:
    description: Id
mode: single
icon: mdi:vacuum-outline
```
and this is my UI card
```
type: custom:xiaomi-vacuum-map-card
entity: vacuum.p2009_d4d2d6f9d6cd
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_modes:
  - template: vacuum_goto
  - template: vacuum_clean_zone
    max_selections: 1
    repeats_type: EXTERNAL
    max_repeats: 5
    service_call_schema: null
    service: xiaomi_miot.call_action
    service_data:
      entity_id: '[[entity_id]]'
      siid: 4
      aiid: 1
      params:
        - piid: 1
          value: 19
        - piid: 10
          value: '{"areas":[[[[selection_unwrapped]],[[repeats]],1,1]]}'
      force_params: true
  - template: vacuum_clean_segment
    max_selections: 1
    repeats_type: EXTERNAL
    max_repeats: 5
    service_call_schema:
    service: xiaomi_miot.call_action
    service_data:
      entity_id: '[[entity_id]]'
      siid: 4
      aiid: 1
      params:
        - piid: 1
          value: 18
        - piid: 10
          value: '{"selects":[[[[selection_unwrapped]],[[repeats]],3,3,1]]}'
      force_params: true
    predefined_selections:
      - id: 4
        label:
          text: Room 4
          x: 300
          'y': 2925
          offset_y: 35
        icon:
          name: mdi:broom
          x: 300
          'y': 2925
      - id: 5
        label:
          text: Room 5
          x: -3975
          'y': 1950
          offset_y: 35
        icon:
          name: mdi:broom
          x: -3975
          'y': 1950
      - id: 1
        label:
          text: Room 1
          x: 950
          'y': 3050
          offset_y: 35
        icon:
          name: mdi:broom
          x: 950
          'y': 3050
      - id: 6
        label:
          text: Room 6
          x: 1350
          'y': 5075
          offset_y: 35
        icon:
          name: mdi:broom
          x: 1350
          'y': 5075
      - id: 3
        label:
          text: Room 3
          x: -3575
          'y': 7050
          offset_y: 35
        icon:
          name: mdi:broom
          x: -3575
          'y': 7050
      - id: 2
        label:
          text: Room 2
          x: 650
          'y': 7775
          offset_y: 35
        icon:
          name: mdi:broom
          x: 650
          'y': 7775
vacuum_platform: send_command
```
this show after holding start button:
![image](https://user-images.githubusercontent.com/97547613/174325645-28e04116-703d-4418-8a57-fae445c8515a.png)
and this is log:
Logger: homeassistant.components.websocket_api.http.connection
Source: components/vacuum/__init__.py:292
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 16:35:20 (4 occurrences)
Last logged: 17:07:26

[140114656299904]
[140114396363024]
[140114487001872]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1704, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1741, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py", line 301, in async_send_command
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py", line 292, in send_command
    raise NotImplementedError()
NotImplementedError

what am I doing wrong?

**Comment by PiotrMachowski** [comment, marked as answer]
You have invalid indentation in your card config
```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.p2009_d4d2d6f9d6cd
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_modes:
  - template: vacuum_goto
  - template: vacuum_clean_zone
    max_selections: 1
    repeats_type: EXTERNAL
    max_repeats: 5
    service_call_schema:
      service: xiaomi_miot.call_action
      service_data:
        entity_id: '[[entity_id]]'
        siid: 4
        aiid: 1
        params:
          - piid: 1
            value: 19
          - piid: 10
            value: '{"areas":[[[[selection_unwrapped]],[[repeats]],1,1]]}'
        force_params: true
  - template: vacuum_clean_segment
    max_selections: 1
    repeats_type: EXTERNAL
    max_repeats: 5
    service_call_schema:
      service: xiaomi_miot.call_action
      service_data:
        entity_id: '[[entity_id]]'
        siid: 4
        aiid: 1
        params:
          - piid: 1
            value: 18
          - piid: 10
            value: '{"selects":[[[[selection_unwrapped]],[[repeats]],3,3,1]]}'
        force_params: true
    predefined_selections:
      - id: 4
        label:
          text: Room 4
          x: 300
          'y': 2925
          offset_y: 35
        icon:
          name: mdi:broom
          x: 300
          'y': 2925
      - id: 5
        label:
          text: Room 5
          x: -3975
          'y': 1950
          offset_y: 35
        icon:
          name: mdi:broom
          x: -3975
          'y': 1950
      - id: 1
        label:
          text: Room 1
          x: 950
          'y': 3050
          offset_y: 35
        icon:
          name: mdi:broom
          x: 950
          'y': 3050
      - id: 6
        label:
          text: Room 6
          x: 1350
          'y': 5075
          offset_y: 35
        icon:
          name: mdi:broom
          x: 1350
          'y': 5075
      - id: 3
        label:
          text: Room 3
          x: -3575
          'y': 7050
          offset_y: 35
        icon:
          name: mdi:broom
          x: -3575
          'y': 7050
      - id: 2
        label:
          text: Room 2
          x: 650
          'y': 7775
          offset_y: 35
        icon:
          name: mdi:broom
          x: 650
          'y': 7775
vacuum_platform: send_command
```
