### DISCUSSION TITLE
service_call_schema for segment repeats Roborock S5 Max

### DISCUSSION THREAD

**Discussion by nkgiovannivl** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#426] [Q&A] [answered]
Hi All,

I'm trying to make a repeats cleanings for selected segments using the map card, but i'm stuck, below my procedure:

1. Test call service from HOASS, it works, my vacuum clean twice:

```
service: vacuum.send_command
data:
  command: app_segment_clean
  params:
    - segments:
        - 21
      repeat: 2
target:
  entity_id: vacuum.bruno
```

Implement service_call_schema into map card:

```
map_modes:
  - template: vacuum_clean_segment
    max_selections: 5
    repeats_type: EXTERNAL
    max_repeats: 5
    service_call_schema:
        service: vacuum.send_command
        service_data:
            command: app_segment_clean
            params:
                segments: '[[selection]]'
                repeat: '[[repeats]]'
        target:
            entity_id: '[[entity_id]]'
```

Check service call from map card (hold click on play) and check console:

```
{
  "domain": "vacuum",
  "service": "send_command",
  "serviceData": {
    "command": "app_segment_clean",
    "params": {
      "segments": [
        21
      ],
      "repeat": 2
    }
  },
  "target": {
    "entity_id": "vacuum.bruno"
  }
}
```

But after select the segmen and click on play, just shows me  "Success", and nothing happends:

![image](https://user-images.githubusercontent.com/48342344/176557764-ec5ec525-bc05-4077-8016-3c7f3a02c34b.png)

What am I missing on my config? Thanks for your support!!

**Comment by PiotrMachowski** [comment, marked as answer]
Try using this config:
```yaml
map_modes:
  - template: vacuum_clean_segment
    max_selections: 5
    repeats_type: EXTERNAL
    max_repeats: 5
    service_call_schema:
        service: vacuum.send_command
        service_data:
            entity_id: '[[entity_id]]'
            command: app_segment_clean
            params:
                segments: '[[selection]]'
                repeat: '[[repeats]]'
```

**Reply by nkgiovannivl** [reply]
Thanks @PiotrMachowski !

I did two changes, the entity_id and add '-' on segements! now it works!

```
map_modes:
  - template: vacuum_clean_segment
    max_selections: 5
    repeats_type: EXTERNAL
    max_repeats: 5
    service_call_schema:
      service: vacuum.send_command
      service_data:
        command: app_segment_clean
        entity_id: '[[entity_id]]'
        params:
          - segments: '[[selection]]'
            repeat: '[[repeats]]'
```
