### DISCUSSION TITLE
Dreame L10 Pro

### DISCUSSION THREAD

**Discussion by g-guglielmi** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#428] [Q&A]
Hello to everyone,

I jut added my Dreame L10 Pro to home assistant using "Xiaomi Miot Auto" HACS integration.

On the entities i see every sensor of the robot:
![image](https://user-images.githubusercontent.com/60267857/178303051-7b37d1fb-5e20-48fd-8fb9-c30db5c0216f.png)

But when i add the dashboard, i don't see all the tabs about the sensors, i can see only battery and fan speed:
![image](https://user-images.githubusercontent.com/60267857/178303290-607d5626-4c45-48af-b85a-f7f3beab76d2.png)

Is there something that i'm missing?
This is the card config:
![image](https://user-images.githubusercontent.com/60267857/178303424-46159cbe-0a44-4df0-ba73-5e2fc3d8202c.png)

Thanks
Gianluca

**Comment by PiotrMachowski** [comment]
Currently you have to add them manually, as this integration is not supported out of the box.

**Reply by PiotrMachowski** [reply]
@ginlik1996 can you show attributes of vacuum entity? (from dev tools)

**Reply by g-guglielmi** [reply]
Here you can find them:
Edit: removed attachment

**Reply by PiotrMachowski** [reply]
@ginlik1996 can you post it as a raw value? (click on entity ID and copy it from text area above). Current approach looses structure of data and exposes URL of your HA

**Reply by g-guglielmi** [reply]
Sure, I'll do it tomorrow morning!

**Reply by g-guglielmi** [reply]
Entity: vacuum.dreame_p2029_85fe_robot_cleaner
```yaml
fan_speed_list:
  - Silent
  - Basic
  - Strong
  - Full Speed
battery_level: 100
battery_icon: mdi:battery
fan_speed: Basic
model: dreame.vacuum.p2029
lan_ip: 
mac_address: 
entity_class: MiotVacuumEntity
exclude_miot_services:
  - consumable
  - annoy
  - remote
  - time
exclude_miot_properties:
  - delete_timer
  - clean_info
  - map_view
  - frame_info
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:dreame-p2029:3
vacuum.status: 2
vacuum.fault: 0
vacuum.mode: 1
clean_logs.first_clean_time: 1642096695
clean_logs.total_clean_time: 3843
clean_logs.total_clean_times: 114
clean_logs.total_clean_area: 3110
audio.volume: 41
audio.voice_packet_id: IT
audio.voice_change_state: '{\"id\":\"\",\"state\":\"idle\",\"progress\":0}'
audio.set_voice.error: '-1'
map.map_extend_data.error: '-1'
map.mult_map_state: 0
map.mult_map_info: >-
  {"object_name":"1596488506/447401722/9","md5":"3ce1dd782faeefe9d4f4d2c98ccce15a"}
do_not_disturb.enable: true
do_not_disturb.start_time: '23:00'
do_not_disturb.end_time: '08:00'
vacuum_extend.work_mode: 14
vacuum_extend.cleaning_time: 69
vacuum_extend.cleaning_area: 46
vacuum_extend.cleaning_mode: 1
vacuum_extend.mop_mode: 2
vacuum_extend.waterbox_status: 0
vacuum_extend.task_status: 0
vacuum_extend.clean_extend_data.error: '-1'
break_point_restart-4-11: 1
vacuum_extend.carpet_press: 1
vacuum_extend.serial_number: 
vacuum_extend.remote_state.error: '-1'
vacuum_extend.clean_rags_tip: 0
vacuum_extend.keep_sweeper_time: 0
vacuum_extend.faults: ''
vacuum_extend.nation_matched: unknown
vacuum_extend.relocation_status: 0
vacuum_extend.laser_switch: 1
filter.filter_life_level: 57
filter.filter_left_time: 85
brush_left_time-10-1: 135
brush_life_level-10-2: 67
brush_cleaner.brush_left_time: 235
brush_cleaner.brush_life_level: 78
battery.charging_state: 1
state_updater: lan
vacuum.status_desc: Idle
sub_entities:
  - vacuum-2.status-1
  - filter-11.filter_life_level-1
  - filter-11.filter_left_time-2
  - battery-3.battery_level-1
  - battery-3.charging_state-2
  - brush_cleaner-9.brush_left_time-1
  - brush_cleaner-9.brush_life_level-2
  - brush_cleaner-10.brush_left_time-1
  - brush_cleaner-10.brush_life_level-2
friendly_name: Alfred Robot Cleaner
supported_features: 13048
```

Let me know if you need the attributes of the sub-entities too.

In the meantime, I was able to add the remaining tabs.

Thanks
Gianluca

**Comment by mcrespov** [comment]
Hi @PiotrMachowski ,

I have detected that when _vacuum_extend.waterbox_status: 1_ (the water tank is installed), it should be possible to change the value of _vacuum_extend.mop_mode_, setting the amount of water to 1, 2 or 3 (min, med, max), but I don't know how to do it through a button and service, could you help me?

The way I've started doing it is like this in the card (Entity: vacuum.dreame_p2029_81b2_robot_cleaner):

```
icons:
   - icon:mdi:water-outline
     conditions:
       - entity: vacuum.dreame_p2029_81b2_robot_cleaner
         attribute: vacuum_extend.waterbox_status
         value: 1
       - entity: vacuum.dreame_p2029_81b2_robot_cleaner
         attribute: vacuum_extend.mop_mode
         value: 2
     tap_action:
       action: call-service
       service: xiaomi_miot.call_action
       service_data:
         entity_id: vacuum.dreame_p2029_81b2_robot_cleaner
         command: ???
         parameters: ???
```

Thanks!
