### DISCUSSION TITLE
Send-command through icons for custom fan/mop modes

### DISCUSSION THREAD

**Discussion by wigster** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#451] [Q&A]
Hi,

my Roborock S7 (with mop) through the core Xiaomi integration supports the custom mop/fan modes during segment/room cleaning if it is sent the appropriate commands. In this custom mode, the vacuum takes the appropriate fan/mop intensity level from the Xiaomi app (not sure if tghe cloud, or it it's saved in the vacuum) and changes it according to the individual room's setting (e.g. in my case it is on Turbo with intensive mopping in the kitchen and medium with no mopping in the living room). These extra modes are (currently) not supported as statuses in the attributes of the vacuum's entity.

Is it possible for me to configure my own version of the default fan icon (and also add a similar icon for the mop), so that an "Auto" mode could be added for the fan as an additional mode so that I could cycle through the fan/mop modes? Basically the Auto modes are set using:
```
service: vacuum.send_command
target:
  entity_id: vacuum.mrbobot
data:
  command: set_water_box_custom_mode
  params: 204
```
and
```
service: vacuum.send_command
target:
  entity_id: vacuum.mrbobot
data:
  command: set_custom_mode
  params: 106
```
Not sure how your fan setting icon works, but I wouldn't mind replacing it with something that cycled through the fan commands from 101 to 106. And I could copy this for my mop icon. The extra fan mode can be dealt with some translation keys, and I guess the mop status is currently not possible to read at all.
