### DISCUSSION TITLE
Cannot get rooms working with second map

### DISCUSSION THREAD

**Discussion by alanthecritic** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#460] [Q&A] [answered]
Hi there, 

I have got this working, to a point. The one last functionality I am trying to figure out in the card is how to get rooms on the second floor set up in the card. I've basically run the template editor on both maps, separately to get the paramaters and then added them into the existing card. My card code now looks like this: 

```type: custom:xiaomi-vacuum-map-card
entity: vacuum.victor
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_modes:
  - template: vacuum_goto
  - template: vacuum_clean_zone
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 17
        label:
          text: Room 17
          x: 23725
          'y': 22200
          offset_y: 35
        icon:
          name: mdi:broom
          x: 23725
          'y': 22200
      - id: 16
        label:
          text: Room 16
          x: 26350
          'y': 23200
          offset_y: 35
        icon:
          name: mdi:broom
          x: 26350
          'y': 23200
      - id: 22
        label:
          text: Room 22
          x: 21850
          'y': 24700
          offset_y: 35
        icon:
          name: mdi:broom
          x: 21850
          'y': 24700
      - id: 20
        label:
          text: Room 20
          x: 29100
          'y': 25025
          offset_y: 35
        icon:
          name: mdi:broom
          x: 29100
          'y': 25025
      - id: 21
        label:
          text: Room 21
          x: 25075
          'y': 26900
          offset_y: 35
        icon:
          name: mdi:broom
          x: 25075
          'y': 26900
      - id: 18
        label:
          text: Room 18
          x: 28550
          'y': 27375
          offset_y: 35
        icon:
          name: mdi:broom
          x: 28550
          'y': 27375
      - id: 19
        label:
          text: Room 19
          x: 21300
          'y': 27600
          offset_y: 35
        icon:
          name: mdi:broom
          x: 21300
          'y': 27600
predefined_selections:
  - id: 1
    label:
      text: Room 1
      x: 21775
      'y': 22250
      offset_y: 35
    icon:
      name: mdi:broom
      x: 21775
      'y': 22250
  - id: 2
    label:
      text: Room 2
      x: 30250
      'y': 22200
      offset_y: 35
    icon:
      name: mdi:broom
      x: 30250
      'y': 22200
  - id: 3
    label:
      text: Room 3
      x: 26125
      'y': 20925
      offset_y: 35
    icon:
      name: mdi:broom
      x: 26125
      'y': 20925
  - id: 17
    label:
      text: Room 4
      x: 24600
      'y': 24350
      offset_y: 35
    icon:
      name: mdi:broom
      x: 24600
      'y': 24350
  - id: 16
    label:
      text: Room 5
      x: 27075
      'y': 26100
      offset_y: 35
    icon:
      name: mdi:broom
      x: 27075
      'y': 26100
append_icons: true
icons:
  - icon: mdi:numeric-0-box
    tooltip: Map 0
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.victor
        command: load_multi_map
        params: 0
  - icon: mdi:numeric-1-box
    tooltip: Map 1
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.victor
        command: load_multi_map
        params: 1
title: Victor
```

The Q&A section here was extremely helpful in getting both rooms and multi_map set but I can't find anything related to this last piece of functionality (rooms within multimap)

**Comment by PiotrMachowski** [comment, marked as answer]
You can achieve it using another mode or additional preset:
```yaml
entity: vacuum.victor
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_modes:
  - template: vacuum_goto
  - template: vacuum_clean_zone
  - template: vacuum_clean_segment
    name: Floor 1
    predefined_selections:
      - id: 17
        label:
          text: Room 17
          x: 23725
          'y': 22200
          offset_y: 35
        icon:
          name: mdi:broom
          x: 23725
          'y': 22200
      - id: 16
        label:
          text: Room 16
          x: 26350
          'y': 23200
          offset_y: 35
        icon:
          name: mdi:broom
          x: 26350
          'y': 23200
      - id: 22
        label:
          text: Room 22
          x: 21850
          'y': 24700
          offset_y: 35
        icon:
          name: mdi:broom
          x: 21850
          'y': 24700
      - id: 20
        label:
          text: Room 20
          x: 29100
          'y': 25025
          offset_y: 35
        icon:
          name: mdi:broom
          x: 29100
          'y': 25025
      - id: 21
        label:
          text: Room 21
          x: 25075
          'y': 26900
          offset_y: 35
        icon:
          name: mdi:broom
          x: 25075
          'y': 26900
      - id: 18
        label:
          text: Room 18
          x: 28550
          'y': 27375
          offset_y: 35
        icon:
          name: mdi:broom
          x: 28550
          'y': 27375
      - id: 19
        label:
          text: Room 19
          x: 21300
          'y': 27600
          offset_y: 35
        icon:
          name: mdi:broom
          x: 21300
          'y': 27600
  - template: vacuum_clean_segment
    name: Floor 2
    predefined_selections:
      - id: 1
        label:
          text: Room 1
          x: 21775
          'y': 22250
          offset_y: 35
        icon:
          name: mdi:broom
          x: 21775
          'y': 22250
      - id: 2
        label:
          text: Room 2
          x: 30250
          'y': 22200
          offset_y: 35
        icon:
          name: mdi:broom
          x: 30250
          'y': 22200
      - id: 3
        label:
          text: Room 3
          x: 26125
          'y': 20925
          offset_y: 35
        icon:
          name: mdi:broom
          x: 26125
          'y': 20925
      - id: 17
        label:
          text: Room 4
          x: 24600
          'y': 24350
          offset_y: 35
        icon:
          name: mdi:broom
          x: 24600
          'y': 24350
      - id: 16
        label:
          text: Room 5
          x: 27075
          'y': 26100
          offset_y: 35
        icon:
          name: mdi:broom
          x: 27075
          'y': 26100
append_icons: true
icons:
  - icon: mdi:numeric-0-box
    tooltip: Map 0
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.victor
        command: load_multi_map
        params: 0
  - icon: mdi:numeric-1-box
    tooltip: Map 1
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.victor
        command: load_multi_map
        params: 1
title: Victor
```
or
```yaml
entity: vacuum.victor
preset_name: Floor 1
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_modes:
  - template: vacuum_goto
  - template: vacuum_clean_zone
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 17
        label:
          text: Room 17
          x: 23725
          'y': 22200
          offset_y: 35
        icon:
          name: mdi:broom
          x: 23725
          'y': 22200
      - id: 16
        label:
          text: Room 16
          x: 26350
          'y': 23200
          offset_y: 35
        icon:
          name: mdi:broom
          x: 26350
          'y': 23200
      - id: 22
        label:
          text: Room 22
          x: 21850
          'y': 24700
          offset_y: 35
        icon:
          name: mdi:broom
          x: 21850
          'y': 24700
      - id: 20
        label:
          text: Room 20
          x: 29100
          'y': 25025
          offset_y: 35
        icon:
          name: mdi:broom
          x: 29100
          'y': 25025
      - id: 21
        label:
          text: Room 21
          x: 25075
          'y': 26900
          offset_y: 35
        icon:
          name: mdi:broom
          x: 25075
          'y': 26900
      - id: 18
        label:
          text: Room 18
          x: 28550
          'y': 27375
          offset_y: 35
        icon:
          name: mdi:broom
          x: 28550
          'y': 27375
      - id: 19
        label:
          text: Room 19
          x: 21300
          'y': 27600
          offset_y: 35
        icon:
          name: mdi:broom
          x: 21300
          'y': 27600
append_icons: true
icons:
  - icon: mdi:numeric-0-box
    tooltip: Map 0
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.victor
        command: load_multi_map
        params: 0
  - icon: mdi:numeric-1-box
    tooltip: Map 1
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.victor
        command: load_multi_map
        params: 1
title: Victor
additional_presets:
  - entity: vacuum.victor
    preset_name: Floor 2
    map_source:
      camera: camera.xiaomi_cloud_map_extractor
    calibration_source:
      camera: true
    map_modes:
      - template: vacuum_goto
      - template: vacuum_clean_zone
      - template: vacuum_clean_segment
      - template: vacuum_clean_segment
        predefined_selections:
          - id: 1
            label:
              text: Room 1
              x: 21775
              'y': 22250
              offset_y: 35
            icon:
              name: mdi:broom
              x: 21775
              'y': 22250
          - id: 2
            label:
              text: Room 2
              x: 30250
              'y': 22200
              offset_y: 35
            icon:
              name: mdi:broom
              x: 30250
              'y': 22200
          - id: 3
            label:
              text: Room 3
              x: 26125
              'y': 20925
              offset_y: 35
            icon:
              name: mdi:broom
              x: 26125
              'y': 20925
          - id: 17
            label:
              text: Room 4
              x: 24600
              'y': 24350
              offset_y: 35
            icon:
              name: mdi:broom
              x: 24600
              'y': 24350
          - id: 16
            label:
              text: Room 5
              x: 27075
              'y': 26100
              offset_y: 35
            icon:
              name: mdi:broom
              x: 27075
              'y': 26100
    append_icons: true
    icons:
      - icon: mdi:numeric-0-box
        tooltip: Map 0
        tap_action:
          action: call-service
          service: vacuum.send_command
          service_data:
            entity_id: vacuum.victor
            command: load_multi_map
            params: 0
      - icon: mdi:numeric-1-box
        tooltip: Map 1
        tap_action:
          action: call-service
          service: vacuum.send_command
          service_data:
            entity_id: vacuum.victor
            command: load_multi_map
            params: 1
```

**Reply by alanthecritic** [reply]
Piotr, wow thanks so much. That is working perfectly now! not only is this a relief for me, it gets the wife approval factor. Honestly, thanks so much for your work on this!

**Comment by doutor-ice** [comment]
Hello. Thanks for a great add-on. I managed to integrate my Roborock S5 max, but am having trouble to make it work with 2 maps (2 floor home). I can switch between maps by pressing numbers 0 or 1, and coordinates for rooms work great on floor 0. But my 2nd floor rooms appear as the image attached bellow (I only have 6 rooms on the coordinates, but 7 rooms appear on the map, it seems it is using my floor 0 coordinates). I used the code provided above on this thread, but can't seem to make it work. Another thing I notice is the room numbering, I seem to have duplicated numbers in use for the different floors. I followed your guide to get the coordinates through developer tools -> templates.
Here's my current card code:

```type: custom:xiaomi-vacuum-map-card
entity: vacuum.roborock_s5_max
preset_name: Floor Baixo
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_modes:
  - template: vacuum_goto
  - template: vacuum_clean_zone
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 19
        label:
          text: Cozinha
          x: 31675
          'y': 16800
          offset_y: 35
        icon:
          name: mdi:broom
          x: 31675
          'y': 16800
      - id: 20
        label:
          text: Room 20
          x: 26700
          'y': 17525
          offset_y: 35
        icon:
          name: mdi:broom
          x: 26700
          'y': 17525
      - id: 18
        label:
          text: Room 18
          x: 30150
          'y': 19875
          offset_y: 35
        icon:
          name: mdi:broom
          x: 30150
          'y': 19875
      - id: 16
        label:
          text: Room 16
          x: 31325
          'y': 19425
          offset_y: 35
        icon:
          name: mdi:broom
          x: 31325
          'y': 19425
      - id: 21
        label:
          text: Room 21
          x: 26175
          'y': 20600
          offset_y: 35
        icon:
          name: mdi:broom
          x: 26175
          'y': 20600
      - id: 22
        label:
          text: Room 22
          x: 25800
          'y': 25325
          offset_y: 35
        icon:
          name: mdi:broom
          x: 25800
          'y': 25325
      - id: 17
        label:
          text: Room 17
          x: 32500
          'y': 25175
          offset_y: 35
        icon:
          name: mdi:broom
          x: 32500
          'y': 25175
append_icons: true
icons:
  - icon: mdi:numeric-0-box
    tooltip: Map 0
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.roborock_s5_max
        command: load_multi_map
        params: 0
  - icon: mdi:numeric-1-box
    tooltip: Map 1
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.roborock_s5_max
        command: load_multi_map
        params: 1
title: Belvedere
additional_presets:
  - entity: vacuum.roborock_s5_max
    preset_name: Floor Cima
    map_source:
      camera: camera.xiaomi_cloud_map_extractor
    calibration_source:
      camera: true
    map_modes:
      - template: vacuum_goto
      - template: vacuum_clean_zone
      - template: vacuum_clean_segment
    predefined_selections:
      - id: 18
        label:
          text: Test
          x: 27200
          'y': 21425
          offset_y: 35
        icon:
          name: mdi:broom
          x: 27200
          'y': 21425
      - id: 19
        label:
          text: Room 19
          x: 21950
          'y': 22600
          offset_y: 35
        icon:
          name: mdi:broom
          x: 21950
          'y': 22600
      - id: 21
        label:
          text: Room 21
          x: 22725
          'y': 23950
          offset_y: 35
        icon:
          name: mdi:broom
          x: 22725
          'y': 23950
      - id: 20
        label:
          text: Room 20
          x: 24850
          'y': 23950
          offset_y: 35
        icon:
          name: mdi:broom
          x: 24850
          'y': 23950
      - id: 16
        label:
          text: Room 16
          x: 27050
          'y': 26625
          offset_y: 35
        icon:
          name: mdi:broom
          x: 27050
          'y': 26625
      - id: 17
        label:
          text: Teste 17
          x: 22475
          'y': 26650
          offset_y: 35
        icon:
          name: mdi:broom
          x: 22475
          'y': 26650
    append_icons: true
    icons:
      - icon: mdi:numeric-0-box
        tooltip: Map 0
        tap_action:
          action: call-service
          service: vacuum.send_command
          service_data:
            entity_id: vacuum.roborock_s5_max
            command: load_multi_map
            params: 0
      - icon: mdi:numeric-1-box
        tooltip: Map 1
        tap_action:
          action: call-service
          service: vacuum.send_command
          service_data:
            entity_id: vacuum.roborock_s5_max
            command: load_multi_map
            params: 1
```

![Roborock](https://user-images.githubusercontent.com/89936881/188501223-1d910bd6-0885-4994-a9d5-f98aaafe9029.jpg)

**Reply by PiotrMachowski** [reply]
Rooms from a second floor should appear when you change preset to "Belvedere" and select "Rooms" mode. Your config was also a bit incorrect (invalid indentation), here's a corrected one:

```yaml
entity: vacuum.roborock_s5_max
preset_name: Floor Baixo
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_modes:
  - template: vacuum_goto
  - template: vacuum_clean_zone
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 19
        label:
          text: Cozinha
          x: 31675
          'y': 16800
          offset_y: 35
        icon:
          name: mdi:broom
          x: 31675
          'y': 16800
      - id: 20
        label:
          text: Room 20
          x: 26700
          'y': 17525
          offset_y: 35
        icon:
          name: mdi:broom
          x: 26700
          'y': 17525
      - id: 18
        label:
          text: Room 18
          x: 30150
          'y': 19875
          offset_y: 35
        icon:
          name: mdi:broom
          x: 30150
          'y': 19875
      - id: 16
        label:
          text: Room 16
          x: 31325
          'y': 19425
          offset_y: 35
        icon:
          name: mdi:broom
          x: 31325
          'y': 19425
      - id: 21
        label:
          text: Room 21
          x: 26175
          'y': 20600
          offset_y: 35
        icon:
          name: mdi:broom
          x: 26175
          'y': 20600
      - id: 22
        label:
          text: Room 22
          x: 25800
          'y': 25325
          offset_y: 35
        icon:
          name: mdi:broom
          x: 25800
          'y': 25325
      - id: 17
        label:
          text: Room 17
          x: 32500
          'y': 25175
          offset_y: 35
        icon:
          name: mdi:broom
          x: 32500
          'y': 25175
append_icons: true
icons:
  - icon: mdi:numeric-0-box
    tooltip: Map 0
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.roborock_s5_max
        command: load_multi_map
        params: 0
  - icon: mdi:numeric-1-box
    tooltip: Map 1
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.roborock_s5_max
        command: load_multi_map
        params: 1
title: Belvedere
additional_presets:
  - entity: vacuum.roborock_s5_max
    preset_name: Floor Cima
    map_source:
      camera: camera.xiaomi_cloud_map_extractor
    calibration_source:
      camera: true
    map_modes:
      - template: vacuum_goto
      - template: vacuum_clean_zone
      - template: vacuum_clean_segment
        predefined_selections:
          - id: 18
            label:
              text: Test
              x: 27200
              'y': 21425
              offset_y: 35
            icon:
              name: mdi:broom
              x: 27200
              'y': 21425
          - id: 19
            label:
              text: Room 19
              x: 21950
              'y': 22600
              offset_y: 35
            icon:
              name: mdi:broom
              x: 21950
              'y': 22600
          - id: 21
            label:
              text: Room 21
              x: 22725
              'y': 23950
              offset_y: 35
            icon:
              name: mdi:broom
              x: 22725
              'y': 23950
          - id: 20
            label:
              text: Room 20
              x: 24850
              'y': 23950
              offset_y: 35
            icon:
              name: mdi:broom
              x: 24850
              'y': 23950
          - id: 16
            label:
              text: Room 16
              x: 27050
              'y': 26625
              offset_y: 35
            icon:
              name: mdi:broom
              x: 27050
              'y': 26625
          - id: 17
            label:
              text: Teste 17
              x: 22475
              'y': 26650
              offset_y: 35
            icon:
              name: mdi:broom
              x: 22475
              'y': 26650
    append_icons: true
    icons:
      - icon: mdi:numeric-0-box
        tooltip: Map 0
        tap_action:
          action: call-service
          service: vacuum.send_command
          service_data:
            entity_id: vacuum.roborock_s5_max
            command: load_multi_map
            params: 0
      - icon: mdi:numeric-1-box
        tooltip: Map 1
        tap_action:
          action: call-service
          service: vacuum.send_command
          service_data:
            entity_id: vacuum.roborock_s5_max
            command: load_multi_map
            params: 1
```
