### DISCUSSION TITLE
[SOLVED] Cannot draw zones in card

### DISCUSSION THREAD

**Discussion by andreag85** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#463] [Q&A] [answered]
###Sorry. I'm wrong. All work as expected###

Hi there,
I'm trying to draw zones on the card but without success, map is show but no zones are drawn.
I'm using Home Assistant 2022.8.7 but same happen with 2022.8.4-6.
A Roborock S5 Max configured with Xiaomi Miio (https://www.home-assistant.io/integrations/xiaomi_miio)
Xiaomi Cloud Map Extractor v2.2.0 and Xiaomi Vacuum Map Card v2.0.11 installed via HACS.
In configuration.yaml I have:
````
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
````

And a card configured as below:
````
type: custom:xiaomi-vacuum-map-card
entity: vacuum.roborock_vacuum_s5e
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
vacuum_platform: default
title: Roborock S5 Max
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_clean_zone_predefined
    predefined_selections:
      - zones:
          - - 17914
            - 26181
            - 21404
            - 28276
        label:
          text: Tavolo
          x: 19658
          'y': 27149
      - zones:
          - - 23157
            - 23375
            - 26179
            - 28588
        label:
          text: Studio
          x: 24690
          'y': 25827
````
camera.xiaomi_cloud_map_extractor state is:
```
access_token: XXXX
calibration_points: 
- vacuum:
    x: 25500
    'y': 25500
  map:
    x: 216
    'y': 152
- vacuum:
    x: 26500
    'y': 25500
  map:
    x: 236
    'y': 152
- vacuum:
    x: 25500
    'y': 26500
  map:
    x: 216
    'y': 132

model: roborock.vacuum.s5e
used_api: xiaomi
entity_picture: /api/camera_proxy/camera.xiaomi_cloud_map_extractor?token=XXXX
friendly_name: Xiaomi Cloud Map Extractor
supported_features: 1
```

What I'm wrong?
