### DISCUSSION TITLE
MIOT viomi.vacuum.v8

### DISCUSSION THREAD

**Discussion by itsmartinho** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#476] [Q&A]
Hello,

I've been reading a lot of older threads but can't seem to find a solution.
The more I'm touching this, the worst it's getting. It used to work the clean, speeds, etc, just didn't work to send to specific spots OR on rooms. 

So far, my config looks like this:
```yaml
# Mi Robot Map Extractor - Camera Mapa
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
      - rooms
    store_map_raw: true
    store_map_path: /config
    force_api: viomi
```
    
The card looks like this:

```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.viomi_v8_3811_robot_cleaner
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_modes:
  - template: vacuum_clean_segment
    max_selections: 1
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema: null
    service: xiaomi_miot.call_action
    service_data:
      entity_id: '[[entity_id]]'
      siid: 18
      aiid: 1
      params:
        - piid: 1
          value: 18
        - piid: 21
          value: '{"selects":[[[[selection_unwrapped]],[[repeats]],3,3,1]]}'
      force_params: true
    predefined_selections:
      - id: '10'
        icon:
          name: mdi:broom
          x: 3.75
          'y': -13.55
        label:
          text: Office
          x: 3.75
          'y': -13.55
          offset_y: 35
        outline:
          - - 2.4
            - -16.05
          - - 5.1
            - -16.05
          - - 5.1
            - -11.05
          - - 2.4
            - -11.05
      - id: '11'
        icon:
          name: mdi:broom
          x: 0.8750000000000001
          'y': -13.525
        label:
          text: Bedroom
          x: 0.8750000000000001
          'y': -13.525
          offset_y: 35
        outline:
          - - -0.45
            - -16.05
          - - 2.2
            - -16.05
          - - 2.2
            - -11
          - - -0.45
            - -11
      - id: '12'
        icon:
          name: mdi:broom
          x: 0.42500000000000004
          'y': -8.425
        label:
          text: Bathroom
          x: 0.42500000000000004
          'y': -8.425
          offset_y: 35
        outline:
          - - -0.5
            - -9.5
          - - 1.35
            - -9.5
          - - 1.35
            - -7.35
          - - -0.5
            - -7.35
      - id: '13'
        icon:
          name: mdi:broom
          x: 0.45000000000000007
          'y': -5.675000000000001
        label:
          text: Bathroom
          x: 0.45000000000000007
          'y': -5.675000000000001
          offset_y: 35
        outline:
          - - -0.45
            - -6.9
          - - 1.35
            - -6.9
          - - 1.35
            - -4.45
          - - -0.45
            - -4.45
      - id: '14'
        icon:
          name: mdi:broom
          x: 1.025
          'y': -1.625
        label:
          text: Guestroom
          x: 1.025
          'y': -1.625
          offset_y: 35
        outline:
          - - -0.45
            - -6.2
          - - 2.5
            - -6.2
          - - 2.5
            - 2.95
          - - -0.45
            - 2.95
      - id: '15'
        icon:
          name: mdi:broom
          x: 4.875
          'y': 1.95
        label:
          text: Cômodo6
          x: 4.875
          'y': 1.95
          offset_y: 35
        outline:
          - - 2.95
            - 0.85
          - - 6.8
            - 0.85
          - - 6.8
            - 3.05
          - - 2.95
            - 3.05
      - id: '16'
        icon:
          name: mdi:broom
          x: 4.75
          'y': -2.6500000000000004
        label:
          text: Bedroom
          x: 4.75
          'y': -2.6500000000000004
          offset_y: 35
        outline:
          - - 2.75
            - -6.15
          - - 6.75
            - -6.15
          - - 6.75
            - 0.85
          - - 2.75
            - 0.85
      - id: '17'
        icon:
          name: mdi:broom
          x: 2.1500000000000004
          'y': -8.675
        label:
          text: Hall
          x: 2.1500000000000004
          'y': -8.675
          offset_y: 35
        outline:
          - - 1.35
            - -11.1
          - - 2.95
            - -11.1
          - - 2.95
            - -6.25
          - - 1.35
            - -6.25
      - id: '18'
        icon:
          name: mdi:broom
          x: 6.4
          'y': -13.125
        label:
          text: Kitchen
          x: 6.4
          'y': -13.125
          offset_y: 35
        outline:
          - - 5.3
            - -16.3
          - - 7.5
            - -16.3
          - - 7.5
            - -9.95
          - - 5.3
            - -9.95
      - id: '19'
        icon:
          name: mdi:broom
          x: 4
          'y': -9
        label:
          text: Hall
          x: 4
          'y': -9
          offset_y: 35
        outline:
          - - 3
            - -11.05
          - - 5.3
            - -11.05
          - - 5.3
            - -6.15
          - - 3
            - -6.15
    variables: {}
vacuum_platform: al-one/hass-xiaomi-miot
tiles:
  - tile_id: battery_level
    entity: vacuum.viomi_v8_3811_robot_cleaner
    label: Battery
    attribute: battery_level
    icon: mdi:battery-90
    unit: '%'
  - tile_id: fan_speed
    entity: vacuum.viomi_v8_3811_robot_cleaner
    label: Fan speed
    attribute: fan_speed
    icon: mdi:fan
    translations:
      silent: Silent
      standard: Standard
      medium: Medium
      turbo: Turbo
      auto: Auto
      gentle: Gentle
  - tile_id: status
    attribute: vacuum.status_desc
    label: Status
    icon: mdi:robot-vacuum
    entity: vacuum.viomi_v8_3811_robot_cleaner
    precision: 0
    translations:
      starting: Starting
      charger disconnected: Charger disconnected
      idle: Idle
      remote control active: Remote control active
      cleaning: Cleaning
      returning home: Returning home
      manual mode: Manual mode
      charging: Charging
      charging problem: Charging problem
      paused: Paused
      spot cleaning: Spot cleaning
      error: Error
      shutting down: Shutting down
      updating: Updating
      docking: Docking
      going to target: Going to target
      zoned cleaning: Zoned cleaning
      segment cleaning: Segment cleaning
      emptying the bin: Emptying the bin
      charging complete: Charging complete
      device offline: Device offline
icons:
  - icon: mdi:play
    conditions:
      - entity: vacuum.viomi_v8_3811_robot_cleaner
        value_not: cleaning
      - entity: vacuum.viomi_v8_3811_robot_cleaner
        value_not: error
      - entity: vacuum.viomi_v8_3811_robot_cleaner
        value_not: returning
    tooltip: Start
    tap_action:
      action: call-service
      service: vacuum.start
      service_data:
        entity_id: vacuum.viomi_v8_3811_robot_cleaner
  - icon: mdi:pause
    conditions:
      - entity: vacuum.viomi_v8_3811_robot_cleaner
        value_not: docked
      - entity: vacuum.viomi_v8_3811_robot_cleaner
        value_not: idle
      - entity: vacuum.viomi_v8_3811_robot_cleaner
        value_not: error
      - entity: vacuum.viomi_v8_3811_robot_cleaner
        value_not: paused
    tooltip: Pause
    tap_action:
      action: call-service
      service: vacuum.pause
      service_data:
        entity_id: vacuum.viomi_v8_3811_robot_cleaner
  - icon: mdi:stop
    conditions:
      - entity: vacuum.viomi_v8_3811_robot_cleaner
        value_not: docked
      - entity: vacuum.viomi_v8_3811_robot_cleaner
        value_not: idle
      - entity: vacuum.viomi_v8_3811_robot_cleaner
        value_not: error
      - entity: vacuum.viomi_v8_3811_robot_cleaner
        value_not: paused
    tooltip: Stop
    tap_action:
      action: call-service
      service: vacuum.stop
      service_data:
        entity_id: vacuum.viomi_v8_3811_robot_cleaner
  - icon: mdi:home-map-marker
    conditions:
      - entity: vacuum.viomi_v8_3811_robot_cleaner
        value_not: docked
      - entity: vacuum.viomi_v8_3811_robot_cleaner
        value_not: returning
    tooltip: Return to base
    tap_action:
      action: call-service
      service: vacuum.return_to_base
      service_data:
        entity_id: vacuum.viomi_v8_3811_robot_cleaner
  - icon: mdi:map-marker
    tooltip: Locate
    tap_action:
      action: call-service
      service: vacuum.locate
      service_data:
        entity_id: vacuum.viomi_v8_3811_robot_cleaner
  - icon: mdi:fan-remove
    conditions:
      - entity: vacuum.viomi_v8_3811_robot_cleaner
        attribute: fan_speed
        value: Silent
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.viomi_v8_3811_robot_cleaner
        fan_speed: Basic
  - icon: mdi:fan-speed-1
    conditions:
      - entity: vacuum.viomi_v8_3811_robot_cleaner
        attribute: fan_speed
        value: Basic
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.viomi_v8_3811_robot_cleaner
        fan_speed: Medium
  - icon: mdi:fan-speed-2
    conditions:
      - entity: vacuum.viomi_v8_3811_robot_cleaner
        attribute: fan_speed
        value: Medium
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.viomi_v8_3811_robot_cleaner
        fan_speed: Strong
  - icon: mdi:fan-speed-2
    conditions:
      - entity: vacuum.viomi_v8_3811_robot_cleaner
        attribute: fan_speed
        value: Strong
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.viomi_v8_3811_robot_cleaner
        fan_speed: Silent
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.viomi_v8_3811_robot_cleaner
        attribute: fan_speed
        value_not: Silent
      - entity: vacuum.viomi_v8_3811_robot_cleaner
        attribute: fan_speed
        value_not: Basic
      - entity: vacuum.viomi_v8_3811_robot_cleaner
        attribute: fan_speed
        value_not: Medium
      - entity: vacuum.viomi_v8_3811_robot_cleaner
        attribute: fan_speed
        value_not: Strong
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.viomi_v8_3811_robot_cleaner
        fan_speed: Silent
```

So far I seem to have broken something on the card cus some buttons are missing and used to show. 
I'm sure the token and the device name is correct, I've triple checked at this point.

The error I'm getting says: "Falha ao chamar o serviço xiaomi_miot/call_action. required key not provided @ data['siid']"

Screenshots: https://i.postimg.cc/rsmjChHN/error-vacuum.jpg

I'm really sorry for bothering you with this, but I really can't seem to reach a solution without help.
My knowledge is still kinda limited, so anything you need to try and find a fix for this let me know.

Other relevant information is that I'm using Mi Home - on European Servers. And the Integration is MiOT.

**Comment by PiotrMachowski** [comment]
Have you clicked "Generate static config" button? Your setup seems a bit excessive.

The problem with your config is that `service` and `service_data` should be under `service_call_schema`. Here you have a corrected version:
```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.viomi_v8_3811_robot_cleaner
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_modes:
  - template: vacuum_clean_segment
    max_selections: 1
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: xiaomi_miot.call_action
      service_data:
        entity_id: '[[entity_id]]'
        siid: 18
        aiid: 1
        params:
          - piid: 1
            value: 18
          - piid: 21
            value: '{"selects":[[[[selection_unwrapped]],[[repeats]],3,3,1]]}'
        force_params: true
    predefined_selections:
      - id: '10'
        icon:
          name: mdi:broom
          x: 3.75
          'y': -13.55
        label:
          text: Office
          x: 3.75
          'y': -13.55
          offset_y: 35
        outline:
          - - 2.4
            - -16.05
          - - 5.1
            - -16.05
          - - 5.1
            - -11.05
          - - 2.4
            - -11.05
      - id: '11'
        icon:
          name: mdi:broom
          x: 0.8750000000000001
          'y': -13.525
        label:
          text: Bedroom
          x: 0.8750000000000001
          'y': -13.525
          offset_y: 35
        outline:
          - - -0.45
            - -16.05
          - - 2.2
            - -16.05
          - - 2.2
            - -11
          - - -0.45
            - -11
      - id: '12'
        icon:
          name: mdi:broom
          x: 0.42500000000000004
          'y': -8.425
        label:
          text: Bathroom
          x: 0.42500000000000004
          'y': -8.425
          offset_y: 35
        outline:
          - - -0.5
            - -9.5
          - - 1.35
            - -9.5
          - - 1.35
            - -7.35
          - - -0.5
            - -7.35
      - id: '13'
        icon:
          name: mdi:broom
          x: 0.45000000000000007
          'y': -5.675000000000001
        label:
          text: Bathroom
          x: 0.45000000000000007
          'y': -5.675000000000001
          offset_y: 35
        outline:
          - - -0.45
            - -6.9
          - - 1.35
            - -6.9
          - - 1.35
            - -4.45
          - - -0.45
            - -4.45
      - id: '14'
        icon:
          name: mdi:broom
          x: 1.025
          'y': -1.625
        label:
          text: Guestroom
          x: 1.025
          'y': -1.625
          offset_y: 35
        outline:
          - - -0.45
            - -6.2
          - - 2.5
            - -6.2
          - - 2.5
            - 2.95
          - - -0.45
            - 2.95
      - id: '15'
        icon:
          name: mdi:broom
          x: 4.875
          'y': 1.95
        label:
          text: Cômodo6
          x: 4.875
          'y': 1.95
          offset_y: 35
        outline:
          - - 2.95
            - 0.85
          - - 6.8
            - 0.85
          - - 6.8
            - 3.05
          - - 2.95
            - 3.05
      - id: '16'
        icon:
          name: mdi:broom
          x: 4.75
          'y': -2.6500000000000004
        label:
          text: Bedroom
          x: 4.75
          'y': -2.6500000000000004
          offset_y: 35
        outline:
          - - 2.75
            - -6.15
          - - 6.75
            - -6.15
          - - 6.75
            - 0.85
          - - 2.75
            - 0.85
      - id: '17'
        icon:
          name: mdi:broom
          x: 2.1500000000000004
          'y': -8.675
        label:
          text: Hall
          x: 2.1500000000000004
          'y': -8.675
          offset_y: 35
        outline:
          - - 1.35
            - -11.1
          - - 2.95
            - -11.1
          - - 2.95
            - -6.25
          - - 1.35
            - -6.25
      - id: '18'
        icon:
          name: mdi:broom
          x: 6.4
          'y': -13.125
        label:
          text: Kitchen
          x: 6.4
          'y': -13.125
          offset_y: 35
        outline:
          - - 5.3
            - -16.3
          - - 7.5
            - -16.3
          - - 7.5
            - -9.95
          - - 5.3
            - -9.95
      - id: '19'
        icon:
          name: mdi:broom
          x: 4
          'y': -9
        label:
          text: Hall
          x: 4
          'y': -9
          offset_y: 35
        outline:
          - - 3
            - -11.05
          - - 5.3
            - -11.05
          - - 5.3
            - -6.15
          - - 3
            - -6.15
vacuum_platform: al-one/hass-xiaomi-miot
```

**Comment by ksga** [comment]
Hope I'm not necromancing this - but thought it better to continue this thread since I'm using the same unit and think I've made a bit of progress.
Still need a bit of work/help though :) 

The setup is:

- Xiaomi Miot For HomeAssistant v0.7.11 - 2023-08-11 (with the 7df0d46 commit added manually to vacuum.py)
- Xiaomi Cloud Map Extractor v2.2.1
- Lovelace Vacuum Map card v2.2.2
- Mi Robot Vacuum-Mop P FW 3.5.3_0017(viomi.vacuum.v8)
- Mi Home (vevs edition) v8.5.707

Based on the solution here https://github.com/al-one/hass-xiaomi-miot/issues/1035, I am using the send_command platform in my lovelace card. The commands have been tested in developer tools, and work as expected, so if I can get the card tweaked I think I got things sorted :)

My card config:
```
type: custom:xiaomi-vacuum-map-card
title: Nuller
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
camera_calibration: true
entity: vacuum.viomi_v8_38aa_robot_cleaner
vacuum_platform: send_command
map_locked: true
map_modes:
  - template: vacuum_clean_segment
    max_selections: 5
    service_call_schema:
      service: vacuum.send_command
      service_data:
        entity_id: '[[entity_id]]'
        command: set_mode_withroom
        params:
          - 0,1,0,[[selection_unwrapped]]
    predefined_selections:
      - id: '10'
        icon:
          name: mdi:bed
          x: -3.2
          'y': -1.175
        label:
          text: Soveværelse
          x: -3.2
          'y': -1.175
          offset_y: 25
      - id: '11'
        icon:
          name: mdi:stove
          x: 0.2
          'y': -5.5
        label:
          text: Køkken
          x: 0.2
          'y': -5.5
          offset_y: 25
      - id: '12'
        icon:
          name: mdi:sofa
          x: 1
          'y': -2.225
        label:
          text: Stue
          x: 1
          'y': -2.225
          offset_y: 25
      - id: '13'
        icon:
          name: mdi:shoe-print
          x: -3.85
          'y': -3.525
        label:
          text: Entre
          x: -3.85
          'y': -3.525
          offset_y: 25
      - id: '14'
        icon:
          name: mdi:broom
          x: -3.85
          'y': -5.5
        label:
          text: Badeværelse
          x: -3.85
          'y': -5.5
          offset_y: 25
  - template: vacuum_clean_zone
    max_selections: 1
    coordinates_rounding: false
    service_call_schema:
      service: vacuum.send_command
      service_data:
        entity_id: '[[entity_id]]'
        command: set_zone
        params:
          - 1
          - 0_0_[[selection_unwrapped]]
  - template: vacuum_goto
    coordinates_rounding: false
    service_call_schema:
      service: vacuum.send_command
      service_data:
        entity_id: '[[entity_id]]'
        command: set_point_clean
        params:
          - 1,[[selection_unwrapped]]
tiles:
  - label: Status
    entity: vacuum.viomi_v8_38aa_robot_cleaner
    icon: mdi:robot-vacuum
    attribute: vacuum.status_desc
  - label: Battery
    entity: vacuum.viomi_v8_38aa_robot_cleaner
    icon: mdi:battery-charging-100
    attribute: battery_level
  - label: Fan Speed
    entity: vacuum.viomi_v8_38aa_robot_cleaner
    icon: mdi:fan
    attribute: fan_speed
  - label: Main brush
    entity: vacuum.viomi_v8_38aa_robot_cleaner
    icon: mdi:broom
    attribute: viomi_vacuum.main_brush_life
  - label: Side brush
    entity: vacuum.viomi_v8_38aa_robot_cleaner
    icon: mdi:broom
    attribute: viomi_vacuum.side_brush_life
  - label: Filter
    entity: vacuum.viomi_v8_38aa_robot_cleaner
    icon: mdi:air-filter
    attribute: viomi_vacuum.hypa_life
  - label: Mop
    entity: vacuum.viomi_v8_38aa_robot_cleaner
    icon: mdi:flag-remove-outline
    attribute: viomi_vacuum.mop_life
```

Room and point cleaning generate code that is almost correct - just need to get rid of the quotes... How can I do that?
Output from MiHome:
Room:
`2023-08-23 13:16:59 -> {"id":9980,"method":"set_mode_withroom","params":[0,1,1,12]}`
Point:
`2023-08-23 18:14:01 -> {"id":7667,"method":"set_pointclean","params":[1,-1.2056882343595021,-5.331961394617798]}`

The output from the card is very similar, but the quotes around the params need to go for the robot to understand the command:
Room:
```
{
  "domain": "vacuum",
  "service": "send_command",
  "serviceData": {
    "entity_id": "vacuum.viomi_v8_38aa_robot_cleaner",
    "command": "set_mode_withroom",
    "params": [
      "0,1,0,11" #need to loose the quotes
    ]
  }
}
```
Point:
```
{
  "domain": "vacuum",
  "service": "send_command",
  "serviceData": {
    "entity_id": "vacuum.viomi_v8_38aa_robot_cleaner",
    "command": "set_point_clean",
    "params": [
      "1,-1.2351464435146449,-5.682635983263598" #need to loose the quotes
    ]
  }
}
```

Rectangle is another story. The card generates two sets of x/y coordinates followed by ",1" separated by commas. However, the output from MiHome is four x/y coordinates with underscores... Some sort of jinja trickery could sort it perhaps?
MiHome output:
`2023-08-24 09:34:04 -> {"id":1936,"method":"set_zone","params":[1,"0_0_0.1118_-0.0284_0.1118_-1.0284_1.2758_-1.0284_1.2758_-0.0284"]} # Four x,y coordinates CCW starting top left `
and from the card:
```
{
  "domain": "vacuum",
  "service": "send_command",
  "serviceData": {
    "entity_id": "vacuum.viomi_v8_38aa_robot_cleaner",
    "command": "set_zone",
    "params": [
      1,
      "0_0_0.17629009762900782,-0.7930962343096231,1.0103207810320756,-0.09100418410041877,1" #need four coordinates and no ",1" at the end
    ]
  }
}
```

Any help much appreciated :D

**Reply by PiotrMachowski** [reply]
Try these ones:

```yaml
  - template: vacuum_clean_segment
    repeats_type: NONE
    id_type: number
    max_selections: 5
    service_call_schema:
      service: vacuum.send_command
      service_data:
        entity_id: '[[entity_id]]'
        command: set_mode_withroom
        params:
          - 0
          - 1
          - 0
          - "[[selection_unwrapped]]"
```
```yaml
  - template: vacuum_goto
    coordinates_rounding: false
    service_call_schema:
      service: vacuum.send_command
      service_data:
        entity_id: '[[entity_id]]'
        command: set_point_clean
        params:
          - 1
          - "[[point_x]]"
          - "[[point_y]]"
```
```yaml
  - template: vacuum_clean_zone
    repeats_type: NONE
    max_selections: 1
    coordinates_rounding: false
    service_call_schema:
      evaluate_data_as_template: true
      service: vacuum.send_command
      service_data:
        entity_id: '[[entity_id]]'
        command: set_zone
        params:
          - 1
          - "{% set s =[[[selection_unwrapped]]] %}0_0_{{s[0]|round(4)}}_{{s[1]|round(4)}}_{{s[2]|round(4)}}_{{s[1]|round(4)}}_{{s[2]|round(4)}}_{{s[3]|round(4)}}_{{s[0]|round(4)}}_{{s[3]|round(4)}}"
```

**Comment by ksga** [comment]
Getting there :) Pin & Go works like a charm 🕺
Weirdly it does not play well with the app/card extractor. The status changes from charging to standby, no track is shown, and it appears the vacuum is parked right next to the charging station - but the job is done.

The output from the card when trying room looks like this now:
```
{
  "domain": "vacuum",
  "service": "send_command",
  "serviceData": {
    "entity_id": "vacuum.viomi_v8_38aa_robot_cleaner",
    "command": "set_mode_withroom",
    "params": [
      0,
      1,
      0,
      "11"
    ]
  }
}
```
The vacuum just start cleaning the whole house - so the quotes around room number seems to confuse it. Can we drop them somehow so only the numbers remain?

Rectangle is a bit weird. The code you made seems to be working, but nothing happens when I send the command.
The output from the card now:
```
{
  "domain": "vacuum",
  "service": "send_command",
  "serviceData": {
    "entity_id": "vacuum.viomi_v8_38aa_robot_cleaner",
    "command": "set_zone",
    "params": [
      1,
      "0_0_-2.287308228730823_-6.50941422594142_-1.1453277545327767_-6.50941422594142_-1.1453277545327767_-5.6918410041840986_-2.287308228730823_-5.6918410041840986"
    ]
  }
}
```
Could it be that the command is too long because we include quite a lot of decimals? Can we reduce to four like in the app?

**Reply by PiotrMachowski** [reply]
Please respond in the same thread.

Room cleaning: try changing room IDs to not include single quotes. 

Zone cleaning: add rounding to coordinates `{{s[0]|round(4)}}`

**Reply by ksga** [reply]
Sorry - wrong "Write" box  🤦

Room cleaning: removed the single quotes, looks right on selection when editing the card, but the call is still including double quotes.

Zone cleaning: Shortened the call, and it looks exactly like the one from MiHome. Will try and make a few more commands from the app and see if I can spot some sort of inconsistency.

**Reply by PiotrMachowski** [reply]
Room cleaning: try adding `id_type: number` (I have added it to the config above)

Zone cleaning: try cleaning the same area as in the map and check if coordinates match (maybe points are in a different order)

**Reply by ksga** [reply]
So - after a bit more investigating, and adding the id_type: number, this is how my Room config looks:
```
  - template: vacuum_clean_segment
    repeats_type: NONE
    max_selections: 5
    id_type: number
    service_call_schema:
      service: vacuum.send_command
      service_data:
        entity_id: '[[entity_id]]'
        command: set_mode_withroom
        params:
          - 0
          - 1
          - 1
          - '[[selection_unwrapped]]'
    predefined_selections:
      - id: 10
      ...
```
The output still include quotes, and the unit wakes up, leaves the dock, but after a second or two returns to it :
```
{
  "domain": "vacuum",
  "service": "send_command",
  "serviceData": {
    "entity_id": "vacuum.viomi_v8_38aa_robot_cleaner",
    "command": "set_mode_withroom",
    "params": [
      0,
      1,
      1,
      "10"
    ]
  }
}
```
I realized that the third parameter is a counter - how many rooms are selected, so at one point it would be nice to make it reflect that (can we grab that somehow in the card?).

The coordinates had to be rearranged, so the zone cleaning looks like this:
```
  - template: vacuum_clean_zone
    max_selections: 1
    coordinates_rounding: false
    service_call_schema:
      service: vacuum.send_command
      evaluate_data_as_template: true
      service_data:
        entity_id: '[[entity_id]]'
        command: set_zone
        params:
          - 1
          - >-
            {% set s =[[[selection_unwrapped]]]
            %}0_0_{{s[0]|round(4)}}_{{s[3]|round(4)}}_{{s[0]|round(4)}}_{{s[1]|round(4)}}_{{s[2]|round(4)}}_{{s[1]|round(4)}}_{{s[2]|round(4)}}_{{s[3]|round(4)}}
```
Output from the card:
```
{
  "domain": "vacuum",
  "service": "send_command",
  "serviceData": {
    "entity_id": "vacuum.viomi_v8_38aa_robot_cleaner",
    "command": "set_zone",
    "params": [
      1,
      "0_0_-4.7084_0.0336_-4.7084_-2.6754_-1.811_-2.6754_-1.811_0.0336"
    ]
  }
}
```
and from MiHome:
```
"method":"set_zone","params":[1,"0_0_-4.7394_0.0774_-4.7394_-2.5441_-1.7947_-2.5441_-1.7947_0.0774"]
```
As far as I can tell they are identical, but nothing happens when sending the command. I tried sending the method/parameters from developer tools, usiong vacuum.send_command and xiaomi_miot_.send_command, but still nothing - so I'm leaning towards something not related to the card could be the issue. I will try to see if the guys over at al-one can help.

**Reply by ksga** [reply]
Feeling rather dumb...
Just realized "set_zone" might just be preloading coordinates to the unit....
Looked through MiHome logs, and behold - a second command is sent:
```
2023-08-25 10:25:55 -> {"id":5032,"method":"set_zone","params":[1,"0_0_-0.3327_0.0668_-0.3327_-0.9332_1.8790_-0.9332_1.8790_0.0668"]}
2023-08-25 10:25:55 <- {"code":0,"exe_time":0,"id":5032,"message":"ok","net_cost":0,"ot_cost":0,"otlocalts":1692951953816806,"result":["ok"]}
2023-08-25 10:25:55 -> {"id":5033,"method":"set_mode","params":[3,1]}
```
Can we send a second command (set_mode) directly from the card? Or is automation needed.

**Reply by PiotrMachowski** [reply]
> I realized that the third parameter is a counter - how many rooms are selected, so at one point it would be nice to make it reflect that (can we grab that somehow in the card?).

Sure, just show how the service call looks like

> Can we send a second command (set_mode) directly from the card? Or is automation needed.

It's not possible, you have to make a script and pass the data to it or create an automation with a matching`service_call` event trigger

**Reply by ksga** [reply]
Great - will try to setup an automation :)

The service calls should look lige this:
Single room:
```
"method":"set_mode_withroom","params":[0,1,1,10]
```
Two rooms:
```
"method":"set_mode_withroom","params":[0,1,2,10,11]
```
and so forth...
First parameter is the vacuum mode:
0 - Vacuum
1 - Vacuum & mop
3 - Mop

Second parameter seems to always be a 1

**Reply by ksga** [reply]
Almost there :)

Decided to take another look at the logs, and of course I missed a couple of calls...
Now I've setup text helpers and automations for room, point and zone. The card updates the helpers, and when they change the automations run. I will combine them into one and just use the trigger to determine the corresponding action when I'm confident everything works as expected. When everything is put together I'll share the config in https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/406

For now, the card and automations look like this if anyone is interested.
Card:
```
type: custom:xiaomi-vacuum-map-card
title: Nuller
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
camera_calibration: true
entity: vacuum.viomi_v8_38aa_robot_cleaner
vacuum_platform: send_command
map_locked: true
map_modes:
  - template: vacuum_clean_segment
    repeats_type: NONE
    max_selections: 5
    id_type: number
    service_call_schema:
      service: input_text.set_value
      service_data:
        entity_id: input_text.vacuum_room_list
        value: '[0,1,[[selection_size]],[[selection_unwrapped]]]'
    predefined_selections:
      - id: 10
        icon:
          name: mdi:bed
          x: -3.2
          'y': -1.175
        label:
          text: Soveværelse
          x: -3.2
          'y': -1.175
          offset_y: 25
      - id: 11
        icon:
          name: mdi:stove
          x: 0.2
          'y': -5.5
        label:
          text: Køkken
          x: 0.2
          'y': -5.5
          offset_y: 25
      - id: 12
        icon:
          name: mdi:sofa
          x: 1
          'y': -2.225
        label:
          text: Stue
          x: 1
          'y': -2.225
          offset_y: 25
      - id: 13
        icon:
          name: mdi:shoe-print
          x: -3.85
          'y': -3.525
        label:
          text: Entre
          x: -3.85
          'y': -3.525
          offset_y: 25
      - id: 14
        icon:
          name: mdi:broom
          x: -3.85
          'y': -5.5
        label:
          text: Badeværelse
          x: -3.85
          'y': -5.5
          offset_y: 25
  - template: vacuum_clean_zone
    max_selections: 1
    coordinates_rounding: false
    service_call_schema:
      service: input_text.set_value
      evaluate_data_as_template: true
      service_data:
        entity_id: input_text.vacuum_zone_coordinates
        value: >-
          {% set s =[[[selection_unwrapped]]]
          %}0_0_{{s[0]|round(4)}}_{{s[3]|round(4)}}_{{s[0]|round(4)}}_{{s[1]|round(4)}}_{{s[2]|round(4)}}_{{s[1]|round(4)}}_{{s[2]|round(4)}}_{{s[3]|round(4)}}
  - template: vacuum_goto
    coordinates_rounding: false
    service_call_schema:
      service: input_text.set_value
      evaluate_data_as_template: true
      service_data:
        entity_id: input_text.vacuum_point_coordinates
        value: '[1,[[point_x]],[[point_y]]]'
tiles:
  - label: Status
    entity: vacuum.viomi_v8_38aa_robot_cleaner
    icon: mdi:robot-vacuum
    attribute: vacuum.status_desc
  - label: Battery
    entity: vacuum.viomi_v8_38aa_robot_cleaner
    icon: mdi:battery-charging-100
    attribute: battery_level
  - label: Fan Speed
    entity: vacuum.viomi_v8_38aa_robot_cleaner
    icon: mdi:fan
    attribute: fan_speed
  - label: Main brush
    entity: vacuum.viomi_v8_38aa_robot_cleaner
    icon: mdi:broom
    attribute: viomi_vacuum.main_brush_life
  - label: Side brush
    entity: vacuum.viomi_v8_38aa_robot_cleaner
    icon: mdi:broom
    attribute: viomi_vacuum.side_brush_life
  - label: Filter
    entity: vacuum.viomi_v8_38aa_robot_cleaner
    icon: mdi:air-filter
    attribute: viomi_vacuum.hypa_life
  - label: Mop
    entity: vacuum.viomi_v8_38aa_robot_cleaner
    icon: mdi:broom
    attribute: viomi_vacuum.mop_life
```
Room automation:
```
alias: VACUUM_ROOM_START
description: ""
trigger:
  - platform: state
    entity_id:
      - input_text.vacuum_room_list
condition: []
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - service: vacuum.send_command
    data:
      command: set_mode_withroom
      params: "{{ states('input_text.vacuum_room_list') }}"
    target:
      entity_id: vacuum.viomi_v8_38aa_robot_cleaner
mode: single
```
Zone automation:
```
alias: VACUUM_ZONE_START
description: ""
trigger:
  - platform: state
    entity_id:
      - input_text.vacuum_zone_coordinates
condition: []
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - service: vacuum.send_command
    data:
      command: set_uploadmap
      params:
        - 1
    target:
      entity_id: vacuum.viomi_v8_38aa_robot_cleaner
  - delay:
      hours: 0
      minutes: 0
      seconds: 7
      milliseconds: 0
  - service: vacuum.send_command
    data:
      command: set_zone
      params:
        - 1
        - "{{ states('input_text.vacuum_zone_coordinates') | string }}"
    target:
      entity_id: vacuum.viomi_v8_38aa_robot_cleaner
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: vacuum.send_command
    data:
      command: set_mode
      params:
        - 3
        - 1
    target:
      entity_id: vacuum.viomi_v8_38aa_robot_cleaner
mode: single
```
Point automation:
```
alias: VACUUM_POINT_START
description: ""
trigger:
  - platform: state
    entity_id:
      - input_text.vacuum_point_coordinates
condition: []
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - service: vacuum.send_command
    data:
      command: set_uploadmap
      params:
        - 0
    target:
      entity_id: vacuum.viomi_v8_38aa_robot_cleaner
  - delay:
      hours: 0
      minutes: 0
      seconds: 7
      milliseconds: 0
  - service: vacuum.send_command
    data:
      command: set_pointclean
      params: "{{ states('input_text.vacuum_point_coordinates') }}"
    target:
      entity_id: vacuum.viomi_v8_38aa_robot_cleaner
mode: single
```

Thank you for all the help!!!
