### DISCUSSION TITLE
Cannot get zones to show in zone selector

### DISCUSSION THREAD

**Discussion by mppilat** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#483] [General]
Hey,

I got Roborock S1 and was using old version of this awesome integration. I had a prepared zone for cleaning whole apartament, created automation for cleaning. Everything was working properly. I could also select predefined zone and start cleanup manually.
After some time camera lovelace stopped working, so i updated to new version.

I modified lovelace config to show camera, but i cannot manage to show my predefined zone. If i enable drawing zones in map config it is always visible, but i only want it when choosing zones.

```
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_clean_zone_predefined
    predefinied_selections:
      - zones:
          - - 21829
            - 21674
            - 29169
            - 29284
            - 1
vacuum_platform: default

```

I even created new zones, getting coordinates through lovelace edit, and using `- zones: [[xxx, yyy, xxx, yyy]]` format. But they still are not present for selection

Zone always visible form camera:
![image](https://user-images.githubusercontent.com/20710855/192288881-2446ee0e-a39d-4741-b6a3-c28626230799.png)

Old zone coords:
![image](https://user-images.githubusercontent.com/20710855/192288331-6a954412-5d78-49dc-8489-18bdd4b5f2e4.png)

New zone coords:
![image](https://user-images.githubusercontent.com/20710855/192289591-0eeeabbc-9245-4234-9334-e4ad33f2160e.png)

Automation with old zone coords is still working fine. Only problem is with showing the zone in lovelace card.

Also, when saving card configuration with  `- zones: [[xxx, yyy, xxx, yyy]]` format, it reverts to multiple lines after saving config
![image](https://user-images.githubusercontent.com/20710855/192290771-948258fb-0d5e-4a08-a37a-86161a388e92.png)

Am i missing something? What is the issue here?

**Comment by PiotrMachowski** [comment]
> Zone always visible form camera: ![image](https://user-images.githubusercontent.com/20710855/192288881-2446ee0e-a39d-4741-b6a3-c28626230799.png)

This zone is a part of map image (it shows last zone cleaning) and will disappear after first vacuum action (another zone cleaning/full cleaning).

> Old zone coords:
> ![image](https://user-images.githubusercontent.com/20710855/192288331-6a954412-5d78-49dc-8489-18bdd4b5f2e4.png)

Old coordinates should work fine, you just have to remove last line (`- 1`) from its config. 

> Also, when saving card configuration with `- zones: [[xxx, yyy, xxx, yyy]]` format, it reverts to multiple lines after saving config

It is a normal behavior of UI editor, both of these formats are correct 

> Am i missing something? What is the issue here?

Mode that is visible on all your screenshots (Zone cleanup) allows you to create free-drawn zone to clean. Predefined zones are available in "Zones list" mode

**Reply by mppilat** [reply]
I dont have ability to choose zones in "Zones list", when they are defined as predefined. I admit, my screenchots may be wrong, but the issue is still there
![image](https://user-images.githubusercontent.com/20710855/192461952-9658eb73-ac48-46c5-ac12-10f1303fb469.png)

With predefined zone (with label) nothing appears on map. Demos indicate that rectangles with dashed lines should appear.

**Reply by PiotrMachowski** [reply]
Ok, can you show calibration points from camera.robocamera entity?

**Reply by mppilat** [reply]
```
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password 
    country: "de"
    name: "RoboKamera"
    colors:
      color_map_inside: [32, 115, 185]
      color_map_outside: [19, 87, 148]
      color_map_wall: [100, 196, 254]
      color_map_wall_v2: [93, 109, 126]
      color_grey_wall: [93, 109, 126]
      color_path: [147, 194, 238]
      color_goto_path: [0, 255, 0]
      color_predicted_path: [255, 255, 0, 0]
      color_zones: [0xAD, 0xD8, 0xFF, 0x8F]
      color_zones_outline: [0xAD, 0xD8, 0xFF]
      color_virtual_walls: [255, 0, 0]
      color_no_go_zones: [255, 33, 55, 127]
      color_no_go_zones_outline: [255, 0, 0]
      color_no_mop_zones: [163, 130, 211, 127]
      color_no_mop_zones_outline: [163, 130, 211]
      color_charger: [0x66, 0xfe, 0xda, 0x7f]
      color_robo: [75, 235, 149]
      color_unknown: [0, 0, 0]
      color_scan: [0xDF, 0xDF, 0xDF]
    map_transformation:
      scale: 2
      trim:
        top: 8
        bottom: 18
        left: 18
        right: 20
    attributes:
      - calibration_points
      - zones
    draw:
      - charger
      - goto_path
      - predicted_path
      - vacuum_position
      - path
    scan_interval:
      seconds: 20
    auto_update: true
```

This is my config for camera, calibration_points are only in attributes. Do you need something different? Can i extract calibration points somehow?

From entity i can only see camera image:
![image](https://user-images.githubusercontent.com/20710855/192499399-af5eeb41-b053-4760-aa1f-d270a58448cd.png)

**Reply by PiotrMachowski** [reply]
I need to check out values of calibration points, they are in attributes of camera entity. It's possible to check them out in dev tools

**Reply by mppilat** [reply]
```
access_token: xxx
calibration_points: 
- vacuum:
    x: 25500
    'y': 25500
  map:
    x: 178
    'y': 226
- vacuum:
    x: 26500
    'y': 25500
  map:
    x: 218
    'y': 226
- vacuum:
    x: 25500
    'y': 26500
  map:
    x: 178
    'y': 186

zones: 
model: rockrobo.vacuum.v1
used_api: xiaomi
entity_picture: /api/camera_proxy/camera.robokamera?token=xxx
friendly_name: RoboKamera
supported_features: 1
```
