### DISCUSSION TITLE
Lovelace button config for specific room cleaning

### DISCUSSION THREAD

**Discussion by doutor-ice** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#508] [Q&A] [answered]
Hello,
I have a two floor map config for my roborock S5 max working with lovelace integration, but I have been searching on how to create 2 buttons since I have some very frequent room cleaning I usually do (for example: a button on a lovelace dashboard to clean kitchen 2x on floor 0, or another button to clean kids room and bathroom 2x on floor 1).
Any ideas how can I create a button like this? As far as I could find through reading many posts and documentation, I figure I have to create some service calls, right?
I also have another doubt, since I have two floors, the service call must tell the roborock on which floor map he should be working with in each button, right?

Bellow is my current card configuration:

```yaml
entity: vacuum.roborock_s5_max
preset_name: Floor Baixo
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_modes:
  - template: vacuum_goto
  - template: vacuum_clean_zone
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 19
        label:
          text: Cozinha
          x: 31675
          'y': 16800
          offset_y: 35
        icon:
          name: mdi:broom
          x: 31675
          'y': 16800
      - id: 20
        label:
          text: Room 20
          x: 26700
          'y': 17525
          offset_y: 35
        icon:
          name: mdi:broom
          x: 26700
          'y': 17525
      - id: 18
        label:
          text: Room 18
          x: 30150
          'y': 19875
          offset_y: 35
        icon:
          name: mdi:broom
          x: 30150
          'y': 19875
      - id: 16
        label:
          text: Room 16
          x: 31325
          'y': 19425
          offset_y: 35
        icon:
          name: mdi:broom
          x: 31325
          'y': 19425
      - id: 21
        label:
          text: Room 21
          x: 26175
          'y': 20600
          offset_y: 35
        icon:
          name: mdi:broom
          x: 26175
          'y': 20600
      - id: 22
        label:
          text: Room 22
          x: 25800
          'y': 25325
          offset_y: 35
        icon:
          name: mdi:broom
          x: 25800
          'y': 25325
      - id: 17
        label:
          text: Room 17
          x: 32500
          'y': 25175
          offset_y: 35
        icon:
          name: mdi:broom
          x: 32500
          'y': 25175
append_icons: true
icons:
  - icon: mdi:numeric-0-box
    tooltip: Map 0
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.roborock_s5_max
        command: load_multi_map
        params: 0
  - icon: mdi:numeric-1-box
    tooltip: Map 1
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.roborock_s5_max
        command: load_multi_map
        params: 1
title: Belvedere
additional_presets:
  - entity: vacuum.roborock_s5_max
    preset_name: Floor Cima
    map_source:
      camera: camera.xiaomi_cloud_map_extractor
    calibration_source:
      camera: true
    map_modes:
      - template: vacuum_goto
      - template: vacuum_clean_zone
      - template: vacuum_clean_segment
        predefined_selections:
          - id: 18
            label:
              text: Test
              x: 27200
              'y': 21425
              offset_y: 35
            icon:
              name: mdi:broom
              x: 27200
              'y': 21425
          - id: 19
            label:
              text: Room 19
              x: 21950
              'y': 22600
              offset_y: 35
            icon:
              name: mdi:broom
              x: 21950
              'y': 22600
          - id: 21
            label:
              text: Room 21
              x: 22725
              'y': 23950
              offset_y: 35
            icon:
              name: mdi:broom
              x: 22725
              'y': 23950
          - id: 20
            label:
              text: Room 20
              x: 24850
              'y': 23950
              offset_y: 35
            icon:
              name: mdi:broom
              x: 24850
              'y': 23950
          - id: 16
            label:
              text: Room 16
              x: 27050
              'y': 26625
              offset_y: 35
            icon:
              name: mdi:broom
              x: 27050
              'y': 26625
          - id: 17
            label:
              text: Teste 17
              x: 22475
              'y': 26650
              offset_y: 35
            icon:
              name: mdi:broom
              x: 22475
              'y': 26650
    append_icons: true
    icons:
      - icon: mdi:numeric-0-box
        tooltip: Map 0
        tap_action:
          action: call-service
          service: vacuum.send_command
          service_data:
            entity_id: vacuum.roborock_s5_max
            command: load_multi_map
            params: 0
      - icon: mdi:numeric-1-box
        tooltip: Map 1
        tap_action:
          action: call-service
          service: vacuum.send_command
          service_data:
            entity_id: vacuum.roborock_s5_max
            command: load_multi_map
            params: 1
```

**Comment by PiotrMachowski** [comment, marked as answer]
```yaml
sequence:
  - service: vacuum.send_command
    data:
      entity_id: vacuum.roborock_s5_max
      command: load_multi_map
      params: 1
  - delay: 00:00:05 # might not be necessary
  - service: xiaomi_miio.vacuum_clean_segment
    data:
      entity_id: vacuum.roborock_s5_max
      segments: 23
```

**Reply by doutor-ice** [reply]
@PiotrMachowski , many thanks once again for your quick reply. It works very good, and I have used that code to create scripts to allow me to use a button on lovelace for each specific routine, and tested it on both floors, with no flaws going to where I wanted the roborock to go.

The only thing I can't seem to sort out is how to repeat rooms. On the "xiaomi_miio.vacuum_clean_segment" documentation it says to use segments: [23,23] in order to repeat. I have tried it but the roborock only cleans the desired room once. Also tried "repeats", but it isn't allowed with the xiaomi_miio.vacuum_clean_segment service.

Any ideas how to sort this out?
Many thanks once again.

**Reply by PiotrMachowski** [reply]
Unfortunately this is an issue inside HA

**Reply by doutor-ice** [reply]
After searching forums, I found a workaround that works. With the code bellow the vacuum does the 2x room cleaning I was looking for.

```
sequence:
  - service: vacuum.send_command
    data:
      entity_id: vacuum.roborock_s5_max
      command: load_multi_map
      params: 1
  - delay: "00:00:01"
  - service: vacuum.send_command
    target:
      entity_id: vacuum.roborock_s5_max
    data:
      command: app_segment_clean
      params:
        - segments:
            - 20
            - 19
            - 18
          repeat: 2
mode: single
```
