### DISCUSSION TITLE
Roidmi Eva Room Cleaning

### DISCUSSION THREAD

**Discussion by jask747** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#527] [Q&A] [answered]
Hi, I have set up the Roidmi Eva (roidmi_v66_2276_robot_cleaner) in Map Extractor which works fine and am now trying to setup cleaning via vacuum map card. Testing with HA Dev Tools > Services, I clean rooms as needed and have also created a script for a room which works:

```yaml
alias: Clean Kitchen
sequence:
  - service: xiaomi_miot.call_action
    data:
      entity_id: vacuum.roidmi_v66_2276_robot_cleaner
      siid: 14
      aiid: 1
      params:
        - 2
        - "{\"mapId\":1234567890,\"segmentId\":[1]}"
mode: single
```

But I cannot get it to work in the Card;

```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.roidmi_v66_2276_robot_cleaner
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_modes:
  - name: Room Selection
    icon: mdi:floor-plan
    tooltip: Start Rooms
    run_immediately: false
    coordinates_rounding: true
    selection_type: ROOM
    max_selections: 9
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: xiaomi_miot.call_action
    service_data:
      entity_id: '[[entity_id]]'
      siid: 14
      aiid: 1
      params:
        - 2
        - '{"mapId":1234567890,"segmentId":''[[selection]]''}'
      throw: true
      debug: true
    predefined_selections:
      ........
```

A quick toast notification message appears in HA console (not on logs) that displays "Failed to call service xiaomi_miot/call_action. required key not provided @ data['aiid']..."

I'm guessing it doesn't like my [[selection]] variable. The selection numbers are correct when I select in the Card Configuration but when I use the "Copy Servcie Call" it only dislays

{
  "domain": "xiaomi_miot",
  "service": "call_action"
}

Is there something obvious that I am missing.
Thanks

**Comment by PiotrMachowski** [comment, marked as answer]
> Is there something obvious that I am missing.

You need to add 2 spaces of indentation to whole `service_data` section :)
```yaml
    max_selections: 9
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: xiaomi_miot.call_action
      service_data:
        entity_id: '[[entity_id]]'
        siid: 14
        aiid: 1
        params:
          - 2
          - '{"mapId":1234567890,"segmentId":''[[selection]]''}'
        throw: true
        debug: true
```

**Reply by jask747** [reply]
Great! Thank you, it was obvious 🙄

I can confirm that it works well on the Roidmi Eva roidmi.vacuum.v66

Thanks for all your great work.

**Reply by jask747** [reply]
Code:

```yaml
  - name: Room Selection
    icon: mdi:floor-plan
    tooltip: Start Rooms
    run_immediately: false
    coordinates_rounding: true
    selection_type: ROOM
    max_selections: 9
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: xiaomi_miot.call_action
      service_data:
        entity_id: '[[entity_id]]'
        siid: 14
        aiid: 1
        params:
          - 2
          - '{"mapId":167125677,"segmentId":[[selection]]}'
```
