### DISCUSSION TITLE
Change position of lock

### DISCUSSION THREAD

**Discussion by humanBeer** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#528] [Q&A] [answered]
I tried everything i cant figure out the correct path to change the position of the lock.

has anyone got it working?

This is my latest attempt: 

```
            card_mod:              
              style:
                "xiaomi-vacuum-map-card:
                  "#map-zoomer-overlay:
                      "ha-icon":
                          $: | 
                            .standalone-icon-on-map {
                                background-color: red; 
                            }
```

background-color (icon color) only used to see if i found the correct path.

![image](https://user-images.githubusercontent.com/47748428/210833358-d04b1fbf-8a6c-4dee-b467-e635fb8c2182.png)

I want the lock on the left side

**Comment by PiotrMachowski** [comment, marked as answer]
```yaml
card_mod:
  style: |
    #map-zoomer-overlay > div:nth-child(1) {
      left: 0;
      right: unset;
    }
```
