### DISCUSSION TITLE
Set Multi zone cleaning

### DISCUSSION THREAD

**Discussion by mebitek** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#534] [Q&A] [answered]
Hi all,
I'm trying to set multi zone cleaning with my sensor.dreame_p2041o
here my card configuration:

```
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.dreame_p2041o_8819_robot_cleaner
vacuum_platform: al-one/hass-xiaomi-miot
map_locked: true
tiles:
  - tile_id: status
    entity: vacuum.dreame_p2041o_8819_robot_cleaner
    label: Status
    icon: mdi:robot-vacuum
  - tile_id: battery_level
    entity: vacuum.dreame_p2041o_8819_robot_cleaner
    label: Battery
    attribute: battery_level
    icon: mdi:battery-charging-100
    unit: '%'
  - tile_id: fan_speed
    entity: vacuum.dreame_p2041o_8819_robot_cleaner
    label: Fan speed
    attribute: fan_speed
    icon: mdi:fan
    translations:
      silent: Silent
      standard: Standard
      medium: Medium
      turbo: Turbo
      auto: Auto
      gentle: Gentle
  - tile_id: sensors_left
    entity: vacuum.dreame_p2041o_8819_robot_cleaner
    label: Sensors Left
    icon: mdi:eye
  - tile_id: filter_left
    entity: sensor.dreame_p2041o_8819_filter_left_time
    label: Filter Left
    icon: mdi:air-filter
    unit: h
  - tile_id: main_brush_left
    entity: sensor.dreame_p2041o_8819_brush_left_time
    label: Main brush Left
    icon: mdi:brush
    unit: h
  - tile_id: side_brush_left
    entity: sensor.dreame_p2041o_8819_brush_left_time_2
    label: Side brush Left
    icon: mdi:brush
    unit: h
  - tile_id: cleaning_count
    entity: vacuum.dreame_p2041o_8819_robot_cleaner
    label: Cleaning count
    icon: mdi:counter
    attribute: clean_logs.total_clean_times
icons:
  - icon: mdi:play
    conditions:
      - entity: vacuum.dreame_p2041o_8819_robot_cleaner
        value_not: cleaning
      - entity: vacuum.dreame_p2041o_8819_robot_cleaner
        value_not: error
      - entity: vacuum.dreame_p2041o_8819_robot_cleaner
        value_not: returning
    tooltip: Start
    tap_action:
      action: call-service
      service: vacuum.start
      service_data:
        entity_id: vacuum.dreame_p2041o_8819_robot_cleaner
  - icon: mdi:stop
    conditions:
      - entity: vacuum.dreame_p2041o_8819_robot_cleaner
        value_not: docked
      - entity: vacuum.dreame_p2041o_8819_robot_cleaner
        value_not: idle
      - entity: vacuum.dreame_p2041o_8819_robot_cleaner
        value_not: error
      - entity: vacuum.dreame_p2041o_8819_robot_cleaner
        value_not: paused
    tooltip: Stop
    tap_action:
      action: call-service
      service: vacuum.stop
      service_data:
        entity_id: vacuum.dreame_p2041o_8819_robot_cleaner
  - icon: mdi:home-map-marker
    conditions:
      - entity: vacuum.dreame_p2041o_8819_robot_cleaner
        value_not: docked
      - entity: vacuum.dreame_p2041o_8819_robot_cleaner
        value_not: returning
    tooltip: Return to base
    tap_action:
      action: call-service
      service: vacuum.return_to_base
      service_data:
        entity_id: vacuum.dreame_p2041o_8819_robot_cleaner
  - icon: mdi:map-marker
    tooltip: Locate
    tap_action:
      action: call-service
      service: vacuum.locate
      service_data:
        entity_id: vacuum.dreame_p2041o_8819_robot_cleaner
  - icon: mdi:fan-remove
    conditions:
      - entity: vacuum.dreame_p2041o_8819_robot_cleaner
        attribute: fan_speed
        value: Silent
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.dreame_p2041o_8819_robot_cleaner
        fan_speed: Basic
  - icon: mdi:fan-speed-1
    conditions:
      - entity: vacuum.dreame_p2041o_8819_robot_cleaner
        attribute: fan_speed
        value: Basic
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.dreame_p2041o_8819_robot_cleaner
        fan_speed: Strong
  - icon: mdi:fan-speed-2
    conditions:
      - entity: vacuum.dreame_p2041o_8819_robot_cleaner
        attribute: fan_speed
        value: Strong
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.dreame_p2041o_8819_robot_cleaner
        fan_speed: Full Speed
  - icon: mdi:fan-speed-3
    conditions:
      - entity: vacuum.dreame_p2041o_8819_robot_cleaner
        attribute: fan_speed
        value: Full Speed
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.dreame_p2041o_8819_robot_cleaner
        fan_speed: Silent
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.dreame_p2041o_8819_robot_cleaner
        attribute: fan_speed
        value_not: Silent
      - entity: vacuum.dreame_p2041o_8819_robot_cleaner
        attribute: fan_speed
        value_not: Basic
      - entity: vacuum.dreame_p2041o_8819_robot_cleaner
        attribute: fan_speed
        value_not: Strong
      - entity: vacuum.dreame_p2041o_8819_robot_cleaner
        attribute: fan_speed
        value_not: Full Speed
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.dreame_p2041o_8819_robot_cleaner
        fan_speed: Silent
  - icon: mdi:water
    conditions:
      - entity: vacuum.dreame_p2041o_8819_robot_cleaner
        attribute: vacuum_extend.waterbox_status
        value: 1
      - entity: vacuum.dreame_p2041o_8819_robot_cleaner
        attribute: vacuum_extend.mop_mode
        value: 1
    tap_action:
      action: call-service
      service: python_script.hass_entities
      service_data:
        action: set_attributes
        entity_id: vacuum.dreame_p2041o_8819_robot_cleaner
        attributes:
          - vacuum_extend.mop_mode: 2
      log_enabled: true
    tooltip: Change mop water mode
  - icon: mdi:water-plus
    conditions:
      - entity: vacuum.dreame_p2041o_8819_robot_cleaner
        attribute: vacuum_extend.waterbox_status
        value: 1
      - entity: vacuum.dreame_p2041o_8819_robot_cleaner
        attribute: vacuum_extend.mop_mode
        value: 2
    tap_action:
      action: call-service
      service: python_script.hass_entities
      service_data:
        action: set_attributes
        entity_id: vacuum.dreame_p2041o_8819_robot_cleaner
        attributes:
          - vacuum_extend.mop_mode: 3
        log_enabled: true
    tooltip: Change mop water mode
  - icon: mdi:water-alert
    conditions:
      - entity: vacuum.dreame_p2041o_8819_robot_cleaner
        attribute: vacuum_extend.waterbox_status
        value: 1
      - entity: vacuum.dreame_p2041o_8819_robot_cleaner
        attribute: vacuum_extend.mop_mode
        value: 3
    tap_action:
      action: call-service
      service: python_script.hass_entities
      service_data:
        action: set_attributes
        entity_id: vacuum.dreame_p2041o_8819_robot_cleaner
        attributes:
          - vacuum_extend.mop_mode: 1
        log_enabled: true
    tooltip: Change mop water mode
map_modes:
  - template: vacuum_clean_segment
    max_selections: 3
    selection_type: ROOM
    service_call_schema:
      service: xiaomi_miot.call_action
      service_data:
        entity_id: '[[entity_id]]'
        siid: 4
        aiid: 1
        params:
          - piid: 1
            value: 18
          - piid: 10
            value: '{"selects":[[[[selection_unwrapped]],[[repeats]],1,3,1]]}'
        force_params: true
    predefined_selections:
      - id: '1'
        icon:
          name: mdi:toilet
          x: -1942
          'y': 3500
        label:
          text: Bagno
          x: -1942
          'y': 3500
          offset_y: 35
        outline:
          - - -2508
            - 2496
          - - -1083
            - 2496
          - - -1083
            - 4112
          - - -2508
            - 4112
      - id: '2'
        icon:
          name: mdi:pot-mix
          x: -782
          'y': 900
        label:
          text: Cucina
          x: -782
          'y': 900
          offset_y: 35
        outline:
          - - -2682
            - -1279
          - - 786
            - -1279
          - - 786
            - 2506
          - - -2682
            - 2506
      - id: '3'
        icon:
          name: mdi:sofa
          x: -442
          'y': -2900
        label:
          text: Studio
          x: -442
          'y': -2900
          offset_y: 35
        outline:
          - - -1593
            - -4022
          - - 826
            - -4022
          - - 826
            - -1254
          - - -1593
            - -1254
  - name: Zone cleanup
    icon: mdi:select-drag
    run_immediately: false
    coordinates_rounding: true
    selection_type: MANUAL_RECTANGLE
    max_selections: 1
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: xiaomi_miot.call_action
      service_data:
        entity_id: '[[entity_id]]'
        siid: 4
        aiid: 1
        params:
          - piid: 1
            value: 19
          - piid: 10
            value: '{"areas":[[[[selection_unwrapped]],[[repeats]],1,1]]}'
        force_params: true
    predefined_selections: []
    variables: {}
  - name: Pin & Go
    icon: mdi:map-marker-plus
    run_immediately: false
    coordinates_rounding: true
    selection_type: MANUAL_POINT
    max_selections: 1
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: xiaomi_miot.call_action
      service_data:
        entity_id: '[[entity_id]]'
        siid: 4
        aiid: 1
        params:
          - piid: 1
            value: 20
          - piid: 10
            value: '{"points":[[[[selection_unwrapped]],[[repeats]],1,1]]}'
        force_params: true
    predefined_selections: []
    variables: {}
```

all is working in single mode but when I set more than one room it doesn't work
from xiaomi mod home app I get this logs for room cleaning:
 {"id":8512,"method":"action","params":{"did":"1022500216","siid":4,"aiid":1,"in":[{"piid":1,"value":18},{"piid":10,"value":"{\"selects\":[[1,1,1,3,1],[2,1,1,3,1],[3,1,1,3,1]]}"}]}}
so I think that the piid:10 value parameter is not exploded correctly
can someone helps me?

**Comment by PiotrMachowski** [comment, marked as answer]
Check this out: https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/251#issuecomment-1383273232

**Reply by PiotrMachowski** [reply]
```yaml
  - template: vacuum_clean_segment
    max_selections: 3
    selection_type: ROOM
    service_call_schema:
      evaluate_data_as_template: true
      service: xiaomi_miot.call_action
      service_data:
        entity_id: '[[entity_id]]'
        siid: 4
        aiid: 1
        params:
          - piid: 1
            value: 18
          - piid: 10
            value: |-
              {"selects":[{% for s in ('[[selection]]'|from_json) %}[{{s}},1,1,3,1]{% if not loop.last %},{% endif %}{% endfor %}]}
        force_params: true
```
