### DISCUSSION TITLE
How to enable multiple floors on Roborock

### DISCUSSION THREAD

**Discussion by PaulAntonDeen** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#551] [Q&A]
In the services tab on the developer tools in HA I can change my map by using the multi map loader:
<img width="538" alt="image" src="https://user-images.githubusercontent.com/25848961/221526091-6d4cd313-974f-4a3c-8c50-8d3183f37169.png">

When I try and move the same config into the vacuum card, nothing happens. Any suggestions how to change map?
```
- name: Begane
    icon: mdi:select-drag
    run_immediately: true
    coordinates_rounding: true
    selection_type: PREDEFINED_POINT
    max_selections: 999
    repeats_type: NONE
    max_repeats: 0
    service_call_schema:
      service: roborock.camera_load_multi_map
      service_data:
        map_flag: 0
      target:
        entity_id: '[[entity_id]]'
    predefined_selections: []
    variables: {}
  - name: Eerste
    icon: mdi:select-drag
    run_immediately: true
    coordinates_rounding: true
    selection_type: PREDEFINED_POINT
    max_selections: 999
    repeats_type: NONE
    max_repeats: 1
    service_call_schema:
      service: roborock.camera_load_multi_map
      service_data:
        map_flag: 1
      target:
        entity_id: '[[entity_id]]'
    predefined_selections: []
    variables: {}
```

As a follow-up: How do I extract the rooms from the new map so that I can do a full clean of the map?

**Comment by PiotrMachowski** [comment]
Check out discussion under this issue: https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/248
```yaml
append_icons: true
icons:
  - icon: mdi:numeric-0-box
    tooltip: Map 0
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.xiaomi_vacuum
        command: load_multi_map
        params: 0
  - icon: mdi:numeric-1-box
    tooltip: Map 1
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.xiaomi_vacuum
        command: load_multi_map
        params: 1
```

> How do I extract the rooms from the new map so that I can do a full clean of the map?

It depends on your final config, but the safest way would be to switch map to a desired one, create a new card, click "Generate rooms config" in its editor and then copy generated rooms to the original card.

**Reply by PaulAntonDeen** [reply]
Ok moving to the icons instead of the map modes is maybe easier. I did this:
```
append_icons: true
icons:
  - icon: mdi:numeric-0-box
    tooltip: Map 0
    tap_action:
      action: call-service
      service: roborock.camera_load_multi_map
      service_data:
        entity_id: vacuum.roborock_s7
        map_flag: 0
  - icon: mdi:numeric-1-box
    tooltip: Map 1
    tap_action:
      action: call-service
      service: roborock.camera_load_multi_map
      service_data:
        map_flag: 1
        entity_id: vacuum.roborock_s7
  - icon: mdi:numeric-2-box
    tooltip: Map 2
    tap_action:
      action: call-service
      service: roborock.camera_load_multi_map
      service_data:
        entity_id: vacuum.roborock_s7
        map_flag: 2
```

And I do get the icons for the different floors. But nothing happens when I click on them.
<img width="453" alt="image" src="https://user-images.githubusercontent.com/25848961/221543734-fc9fff41-4956-4d9b-9f38-4494de1bb7c4.png">

Am i translating the working service call incorrectly?
