### DISCUSSION TITLE
passing "[[selection]]" variable

### DISCUSSION THREAD

**Discussion by mikolajburkiewicz** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#560] [Q&A]
I have been trying to pass "[[selection]]" as a parameter in call service to a script which sends a notification. I was unable to get selection coordinates. My notification script displays "[[selection]]".  Any idea what is the right syntax?

**Comment by PiotrMachowski** [comment]
Have you used `[[selection]]` inside the script or in the card's config itself?

**Reply by mikolajburkiewicz** [reply]
I have not referred to "selection" in any other place my config is:
```yaml
tile_id: test
    label: Test
    tap_action:
      action: call-service
      service: script.test_script
      service_data:
        option: '[[selection]]'
    entity: script.test_script
```
