### DISCUSSION TITLE
Liczba powtorzen

### DISCUSSION THREAD

**Discussion by Ciutek2** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#561] [Q&A] [answered]
Czesc. Pisalem o swoim problemie z liczba reapeats w sprzataniu pokoi. Za kazdym razem sprzata tylko 1 raz.

Wklejam swoja konfiguracje karty. 
```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.roborock_s6_maxv
vacuum_platform: default
language: pl
map_modes:
  - name: Pokoje
    icon: mdi:floor-plan
    run_immediately: false
    coordinates_rounding: true
    selection_type: ROOM
    max_selections: 999
    repeats_type: REPEAT
    max_repeats: 3
    service_call_schema:
      service: xiaomi_miio.vacuum_clean_segment
      service_data:
        segments: '[[selection]]'
        entity_id: '[[entity_id]]'
    predefined_selections:
      - id: '16'
        icon:
          name: mdi:fridge
          x: 30525
          'y': 26775
        label:
          text: Kuchnia
          x: 30525
          'y': 25800
          offset_y: 35
        outline:
          - - 29300
            - 25200
          - - 31750
            - 25200
          - - 31750
            - 28350
          - - 29300
            - 28350
      - id: '17'
        icon:
          name: mdi:television-classic
          x: 27075
          'y': 27050
        label:
          text: Salon
          x: 27075
          'y': 25800
          offset_y: 35
        outline:
          - - 24800
            - 25200
          - - 29350
            - 25200
          - - 29350
            - 28900
          - - 24800
            - 28900
      - id: '18'
        icon:
          name: mdi:shoe-sneaker
          x: 34275
          'y': 25100
        label:
          text: Przedpokój
          x: 33675
          'y': 24400
          offset_y: 35
        outline:
          - - 31400
            - 23750
          - - 35950
            - 23750
          - - 35950
            - 26450
          - - 31400
            - 26450
      - id: '19'
        icon:
          name: mdi:bed
          x: 37475
          'y': 25100
        label:
          text: Sypialnia
          x: 37475
          'y': 24400
          offset_y: 35
        outline:
          - - 35950
            - 23700
          - - 39000
            - 23700
          - - 39000
            - 28900
          - - 35950
            - 28900
      - id: '20'
        icon:
          name: mdi:toilet
          x: 34725
          'y': 27675
        label:
          text: WC
          x: 34725
          'y': 30375
          offset_y: 35
        outline:
          - - 33600
            - 26450
          - - 35850
            - 26450
          - - 35850
            - 28900
          - - 33600
            - 28900
    variables: {}
  - name: Sprzątanie strefowe
    icon: mdi:select-drag
    run_immediately: false
    coordinates_rounding: true
    selection_type: MANUAL_RECTANGLE
    max_selections: 5
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: xiaomi_miio.vacuum_clean_zone
      service_data:
        zone: '[[selection]]'
        repeats: '[[repeats]]'
        entity_id: '[[entity_id]]'
    predefined_selections: []
    variables: {}
  - name: Idź do punktu
    icon: mdi:map-marker-plus
    run_immediately: false
    coordinates_rounding: true
    selection_type: MANUAL_POINT
    max_selections: 999
    repeats_type: NONE
    max_repeats: 1
    service_call_schema:
      service: xiaomi_miio.vacuum_goto
      service_data:
        x_coord: '[[point_x]]'
        y_coord: '[[point_y]]'
        entity_id: '[[entity_id]]'
    predefined_selections: []
    variables: {}
map_locked: true
tiles:
  - tile_id: status
    entity: vacuum.roborock_s6_maxv
    label: Status
    attribute: status
    icon: mdi:robot-vacuum
    translations:
      starting: Uruchamianie
      charger disconnected: Ładowarka odłączona
      idle: Nieaktywny
      remote control active: Zdalne sterowanie
      cleaning: Sprzątanie
      returning home: Powrót do stacji
      manual mode: Tryb manualny
      charging: Ładowanie
      charging problem: Problem z ładowaniem
      paused: Wstrzymany
      spot cleaning: Sprzątanie punktowe
      error: Błąd
      shutting down: Wyłączanie
      updating: Aktualizowanie
      docking: Dokowanie
      going to target: W drodze do celu
      zoned cleaning: Sprzątanie strefowe
      segment cleaning: Sprzątanie pokoju
      emptying the bin: Opróżnianie pojemnika
      charging complete: Ładowanie zakończone
      device offline: Offline
  - tile_id: battery_level
    entity: vacuum.roborock_s6_maxv
    label: Bateria
    attribute: battery_level
    icon: mdi:battery-charging-100
    unit: '%'
  - tile_id: fan_speed
    entity: vacuum.roborock_s6_maxv
    label: Wentylator
    attribute: fan_speed
    icon: mdi:fan
    translations:
      silent: Cichy
      standard: Normalny
      medium: Średni
      turbo: Turbo
      auto: Automatyczny
      gentle: Delikatny
  - tile_id: sensor_dirty_left
    label: Sensory
    unit: h
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: true
      service_data:
        command: reset_consumable
        params: sensor_dirty_time
        entity_id: vacuum.roborock_s6_maxv
    entity: sensor.roborock_s6_maxv_sensor_dirty_left
    icon: mdi:eye-outline
    precision: 0
    translations: {}
  - tile_id: filter_left
    label: Filtr
    unit: h
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: true
      service_data:
        command: reset_consumable
        params: filter_work_time
        entity_id: vacuum.roborock_s6_maxv
    entity: sensor.roborock_s6_maxv_filter_left
    icon: mdi:air-filter
    precision: 0
    translations: {}
  - tile_id: main_brush_left
    label: Główna szczotka
    unit: h
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: true
      service_data:
        command: reset_consumable
        params: main_brush_work_time
        entity_id: vacuum.roborock_s6_maxv
    entity: sensor.roborock_s6_maxv_main_brush_left
    icon: mdi:brush
    precision: 0
    translations: {}
  - tile_id: side_brush_left
    label: Boczna szczotka
    unit: h
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: true
      service_data:
        command: reset_consumable
        params: side_brush_work_time
        entity_id: vacuum.roborock_s6_maxv
    entity: sensor.roborock_s6_maxv_side_brush_left
    icon: mdi:brush
    precision: 0
    translations: {}
icons:
  - icon: mdi:play
    conditions:
      - entity: vacuum.roborock_s6_maxv
        value_not: cleaning
      - entity: vacuum.roborock_s6_maxv
        value_not: error
      - entity: vacuum.roborock_s6_maxv
        value_not: returning
    tooltip: Uruchom
    tap_action:
      action: call-service
      service: vacuum.start
      service_data:
        entity_id: vacuum.roborock_s6_maxv
  - icon: mdi:pause
    conditions:
      - entity: vacuum.roborock_s6_maxv
        value_not: docked
      - entity: vacuum.roborock_s6_maxv
        value_not: idle
      - entity: vacuum.roborock_s6_maxv
        value_not: error
      - entity: vacuum.roborock_s6_maxv
        value_not: paused
    tooltip: Wstrzymaj
    tap_action:
      action: call-service
      service: vacuum.pause
      service_data:
        entity_id: vacuum.roborock_s6_maxv
  - icon: mdi:stop
    conditions:
      - entity: vacuum.roborock_s6_maxv
        value_not: docked
      - entity: vacuum.roborock_s6_maxv
        value_not: idle
      - entity: vacuum.roborock_s6_maxv
        value_not: error
      - entity: vacuum.roborock_s6_maxv
        value_not: paused
    tooltip: Zatrzymaj
    tap_action:
      action: call-service
      service: vacuum.stop
      service_data:
        entity_id: vacuum.roborock_s6_maxv
  - icon: mdi:home-map-marker
    conditions:
      - entity: vacuum.roborock_s6_maxv
        value_not: docked
      - entity: vacuum.roborock_s6_maxv
        value_not: returning
    tooltip: Wróć do stacji dokującej
    tap_action:
      action: call-service
      service: vacuum.return_to_base
      service_data:
        entity_id: vacuum.roborock_s6_maxv
  - icon: mdi:target-variant
    conditions:
      - entity: vacuum.roborock_s6_maxv
        value_not: docked
      - entity: vacuum.roborock_s6_maxv
        value_not: error
      - entity: vacuum.roborock_s6_maxv
        value_not: cleaning
      - entity: vacuum.roborock_s6_maxv
        value_not: returning
    tooltip: Wyczyść miejsce
    tap_action:
      action: call-service
      service: vacuum.clean_spot
      service_data:
        entity_id: vacuum.roborock_s6_maxv
  - icon: mdi:map-marker
    tooltip: Zlokalizuj
    tap_action:
      action: call-service
      service: vacuum.locate
      service_data:
        entity_id: vacuum.roborock_s6_maxv
  - icon: mdi:fan-remove
    conditions:
      - entity: vacuum.roborock_s6_maxv
        attribute: fan_speed
        value: Silent
    tooltip: Zmień prędkość wentylatora
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_s6_maxv
        fan_speed: Standard
  - icon: mdi:fan-speed-1
    conditions:
      - entity: vacuum.roborock_s6_maxv
        attribute: fan_speed
        value: Standard
    tooltip: Zmień prędkość wentylatora
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_s6_maxv
        fan_speed: Medium
  - icon: mdi:fan-speed-2
    conditions:
      - entity: vacuum.roborock_s6_maxv
        attribute: fan_speed
        value: Medium
    tooltip: Zmień prędkość wentylatora
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_s6_maxv
        fan_speed: Turbo
  - icon: mdi:fan-speed-3
    conditions:
      - entity: vacuum.roborock_s6_maxv
        attribute: fan_speed
        value: Turbo
    tooltip: Zmień prędkość wentylatora
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_s6_maxv
        fan_speed: Gentle
  - icon: mdi:waves
    conditions:
      - entity: vacuum.roborock_s6_maxv
        attribute: fan_speed
        value: Gentle
    tooltip: Zmień prędkość wentylatora
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_s6_maxv
        fan_speed: Auto
  - icon: mdi:fan-auto
    conditions:
      - entity: vacuum.roborock_s6_maxv
        attribute: fan_speed
        value: Auto
    tooltip: Zmień prędkość wentylatora
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_s6_maxv
        fan_speed: Silent
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.roborock_s6_maxv
        attribute: fan_speed
        value_not: Silent
      - entity: vacuum.roborock_s6_maxv
        attribute: fan_speed
        value_not: Standard
      - entity: vacuum.roborock_s6_maxv
        attribute: fan_speed
        value_not: Medium
      - entity: vacuum.roborock_s6_maxv
        attribute: fan_speed
        value_not: Turbo
      - entity: vacuum.roborock_s6_maxv
        attribute: fan_speed
        value_not: Gentle
      - entity: vacuum.roborock_s6_maxv
        attribute: fan_speed
        value_not: Auto
    tooltip: Zmień prędkość wentylatora
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_s6_maxv
        fan_speed: Silent
```

**Comment by PiotrMachowski** [comment, marked as answer]
Issue #294 

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.roborock_s6_maxv
vacuum_platform: default
language: pl
map_modes:
  - template: vacuum_clean_segment
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: vacuum.send_command
      service_data:
        command: app_segment_clean
        entity_id: '[[entity_id]]'
        params:
          - segments: '[[selection]]'
            repeat: '[[repeats]]'
    predefined_selections:
      - id: 16
        icon:
          name: mdi:fridge
          x: 30525
          'y': 26775
        label:
          text: Kuchnia
          x: 30525
          'y': 25800
          offset_y: 35
        outline:
          - - 29300
            - 25200
          - - 31750
            - 25200
          - - 31750
            - 28350
          - - 29300
            - 28350
      - id: 17
        icon:
          name: mdi:television-classic
          x: 27075
          'y': 27050
        label:
          text: Salon
          x: 27075
          'y': 25800
          offset_y: 35
        outline:
          - - 24800
            - 25200
          - - 29350
            - 25200
          - - 29350
            - 28900
          - - 24800
            - 28900
      - id: 18
        icon:
          name: mdi:shoe-sneaker
          x: 34275
          'y': 25100
        label:
          text: Przedpokój
          x: 33675
          'y': 24400
          offset_y: 35
        outline:
          - - 31400
            - 23750
          - - 35950
            - 23750
          - - 35950
            - 26450
          - - 31400
            - 26450
      - id: 19
        icon:
          name: mdi:bed
          x: 37475
          'y': 25100
        label:
          text: Sypialnia
          x: 37475
          'y': 24400
          offset_y: 35
        outline:
          - - 35950
            - 23700
          - - 39000
            - 23700
          - - 39000
            - 28900
          - - 35950
            - 28900
      - id: 20
        icon:
          name: mdi:toilet
          x: 34725
          'y': 27675
        label:
          text: WC
          x: 34725
          'y': 30375
          offset_y: 35
        outline:
          - - 33600
            - 26450
          - - 35850
            - 26450
          - - 35850
            - 28900
          - - 33600
            - 28900
  - template: vacuum_clean_zone
  - template: vacuum_goto
map_locked: true
```

**Reply by Ciutek2** [reply]
Podmieniłem z zachowaniem dalszego fragmentu mojego configa po  map_locked: true ale nic się nie dzieje. Wyswietla sie "usluga wywolana" ale odkurzacz nic nie robi ;/

wklejam jeszcze fragment z configuration.yalm
```yaml
#roborock
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    map_transformation:
      scale: 1
      trim:
        top: 20
        bottom: 20
        left: 20
        right: 20
    auto_update: true
    scan_interval:
      seconds: 5 #10minutes  
    attributes:
      - calibration_points
      - rooms 
```
