### DISCUSSION TITLE
Failed to retreive device / Nieprawidlowa kalibracja sprawdz konfiguracje

### DISCUSSION THREAD

**Discussion by Ciutek2** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#564] [Q&A]
Czesc, to znowu ja ;) Ostatnio pisalem ze nie moge zmienic ilosci powtorzen przy sprzataniu pokoi. Problem zostal rozwiazany. W weekend nie mialem pradu przez jakis czas. Po powrocie zasilania przestala sie wyswietlac mapa. Kompletnie nie wiem co zrobic. Odkurzacz ma przypisane stale IP na routerze. Co moze powodowac takie objawy? Wklejam konfigi:

<a href="https://ibb.co/pPPS9hp"><img src="https://i.ibb.co/pPPS9hp/Screenshot-20230326-091635-Home-Assistant.jpg" alt="Screenshot-20230326-091635-Home-Assistant" border="0"></a>

configuration.yalm

```
#roborock
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    colors:
      color_map_outside: [28, 28, 28]
      color_path: [255, 255, 255]
      color_charger: [0, 0, 0,]
      color_charger_outline: [255, 255, 255,]
      color_robo: [0, 0, 0]
      color_robo_outline: [255, 255, 255]


    room_colors:
      16: [240, 178, 122]
      17: [89, 172, 255]
      18: [217, 136, 128]
      19: [128, 255, 0]
      20: [255, 255, 0]
    map_transformation:
      scale: 1
      trim:
        top: 20
        bottom: 20
        left: 20
        right: 20
    auto_update: true
    scan_interval:
      seconds: 5
    attributes:
      - calibration_points
      - rooms
```

Konfiguracja karty:

```
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.roborock_s6_maxv
vacuum_platform: default
language: pl
map_modes:
  - template: vacuum_clean_segment
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: vacuum.send_command
      service_data:
        command: app_segment_clean
        entity_id: '[[entity_id]]'
        params:
          - segments: '[[selection]]'
            repeat: '[[repeats]]'
    predefined_selections:
      - id: 16
        icon:
          name: mdi:fridge
          x: 30525
          'y': 26775
        label: null
        outline:
          - - 29300
            - 25200
          - - 31750
            - 25200
          - - 31750
            - 28350
          - - 29300
            - 28350
      - id: 17
        icon:
          name: mdi:television-classic
          x: 27075
          'y': 27050
        label: null
        outline:
          - - 24800
            - 25200
          - - 29350
            - 25200
          - - 29350
            - 28900
          - - 24800
            - 28900
      - id: 18
        icon:
          name: mdi:shoe-sneaker
          x: 34275
          'y': 25100
        label: null
        outline:
          - - 31400
            - 23750
          - - 35950
            - 23750
          - - 35950
            - 26450
          - - 31400
            - 26450
      - id: 19
        icon:
          name: mdi:bed
          x: 37475
          'y': 25100
        label: null
        outline:
          - - 35950
            - 23700
          - - 39000
            - 23700
          - - 39000
            - 28900
          - - 35950
            - 28900
      - id: 20
        icon:
          name: mdi:toilet
          x: 34725
          'y': 27675
        outline:
          - - 33600
            - 26450
          - - 35850
            - 26450
          - - 35850
            - 28900
          - - 33600
            - 28900
  - template: vacuum_clean_zone
  - template: vacuum_goto
map_locked: true

```
