### DISCUSSION TITLE
Failed to call service xiaomi_miio/vacuum_clean_zone. Service not found

### DISCUSSION THREAD

**Discussion by RedHomeA** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#584] [General]
New to HA, so likely me not doing something or missing a step.

I have the Vacuum card set up and trying to do zones.

![image](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/132276763/ed746ed9-4f4a-4ee7-9025-f778286382fc)

When I click the + it allows me to draw a zone on the map, but I get Failed to call service xiaomi_miio/vacuum_clean_zone. Service not found 

I assume I have to predefine zones or something called "vacuum_clean_zone"?

Also any ideas how to get the sensor info on the top card, all show unavailable all of the time

**Comment by PiotrMachowski** [comment]
Which integration do you use to control the vacuum?

**Reply by RedHomeA** [reply]
Hi, I am using Xiaomi MIoT

**Reply by PiotrMachowski** [reply]
Do you know model code of your vacuum (the one with dots, like `dreame.vacuum.p2009`)?

**Reply by RedHomeA** [reply]
This is from the Device Info
viomi.vacuum.v18
by Viomi
Firmware: 1.6.5_2254

**Reply by PiotrMachowski** [reply]
Xiaomi Miot integration is pretty hard to use, you need to find exact service call schema that needs to be used for your model.

You can start by trying [this config](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/406#discussioncomment-3694847)

**Reply by RedHomeA** [reply]
thanks which file do these get pasted into?

**Reply by PiotrMachowski** [reply]
The code has to be used in the `map_modes` section of the card's config:
```yaml
map_modes:
  - template: vacuum_clean_segment
    service_call_schema:
      service: xiaomi_miot.call_action
      max_selections: 7
      service_data:
        entity_id: '[[entity_id]]'
        siid: 4
        aiid: 13
        params:
          - piid: 36
            value: 0
          - piid: 37
            value: 1
          - piid: 38
            value: '[[selection_unwrapped]]'
        force_params: true
```

**Reply by RedHomeA** [reply]
Thanks I tried but I lose the zone thing off the bottom
![image](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/132276763/39760de6-5a5e-45ff-8fbf-71f7157d52d8)

**Reply by PiotrMachowski** [reply]
Please post your config as a text

**Reply by RedHomeA** [reply]
```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.v18_5c6bd716e393
vacuum_platform: default
map_locked: true
map_modes:
  - template: vacuum_clean_segment
    service_call_schema:
      service: xiaomi_miot.call_action
      max_selections: 7
      service_data:
        entity_id: vacuum.v18_5c6bd716e393
        siid: 4
        aiid: 13
        params:
          - piid: 36
            value: 0
          - piid: 37
            value: 1
          - piid: 38
            value: '[[selection_unwrapped]]'
        force_params: true
title: S9 Vacuum
```

**Reply by PiotrMachowski** [reply]
Ok, keep this config and [follow these instructions](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/317) to generate room config. Map mode selector is missing because you have only one map mode (Room cleaning), so it is unnecessary.

**Reply by RedHomeA** [reply]
It seems to break it on point 3 once I call the service after remving rooms from the configurations.yaml
![image](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/132276763/e72ed605-5f48-4329-90c4-0d0797de64ea)

**Reply by PiotrMachowski** [reply]
Can you paste yaml config here?

**Reply by RedHomeA** [reply]
```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
```

**Reply by PiotrMachowski** [reply]
Of the card, not map extractor

**Reply by RedHomeA** [reply]
```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: ''
calibration_source:
  camera: true
entity: vacuum.v18_5c6bd716e393
tiles:
  - tile_id: battery_level
    entity: vacuum.v18_5c6bd716e393
    label: Battery
    attribute: battery_level
    icon: mdi:battery-charging-100
    unit: '%'
  - tile_id: fan_speed
    entity: vacuum.v18_5c6bd716e393
    label: Fan speed
    attribute: fan_speed
    icon: mdi:fan
    translations:
      silent: Silent
      standard: Standard
      medium: Medium
      turbo: Turbo
      auto: Auto
      gentle: Gentle
icons:
  - icon: mdi:play
    conditions:
      - entity: vacuum.v18_5c6bd716e393
        value_not: cleaning
      - entity: vacuum.v18_5c6bd716e393
        value_not: error
      - entity: vacuum.v18_5c6bd716e393
        value_not: returning
    tooltip: Start
    tap_action:
      action: call-service
      service: vacuum.start
      service_data:
        entity_id: vacuum.v18_5c6bd716e393
  - icon: mdi:stop
    conditions:
      - entity: vacuum.v18_5c6bd716e393
        value_not: docked
      - entity: vacuum.v18_5c6bd716e393
        value_not: idle
      - entity: vacuum.v18_5c6bd716e393
        value_not: error
      - entity: vacuum.v18_5c6bd716e393
        value_not: paused
    tooltip: Stop
    tap_action:
      action: call-service
      service: vacuum.stop
      service_data:
        entity_id: vacuum.v18_5c6bd716e393
  - icon: mdi:map-marker
    tooltip: Locate
    tap_action:
      action: call-service
      service: vacuum.locate
      service_data:
        entity_id: vacuum.v18_5c6bd716e393
  - icon: mdi:fan-remove
    conditions:
      - entity: vacuum.v18_5c6bd716e393
        attribute: fan_speed
        value: Silent
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.v18_5c6bd716e393
        fan_speed: Basic
  - icon: mdi:fan-speed-1
    conditions:
      - entity: vacuum.v18_5c6bd716e393
        attribute: fan_speed
        value: Basic
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.v18_5c6bd716e393
        fan_speed: Medium
  - icon: mdi:fan-speed-2
    conditions:
      - entity: vacuum.v18_5c6bd716e393
        attribute: fan_speed
        value: Medium
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.v18_5c6bd716e393
        fan_speed: Strong
  - icon: mdi:fan-speed-2
    conditions:
      - entity: vacuum.v18_5c6bd716e393
        attribute: fan_speed
        value: Strong
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.v18_5c6bd716e393
        fan_speed: Silent
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.v18_5c6bd716e393
        attribute: fan_speed
        value_not: Silent
      - entity: vacuum.v18_5c6bd716e393
        attribute: fan_speed
        value_not: Basic
      - entity: vacuum.v18_5c6bd716e393
        attribute: fan_speed
        value_not: Medium
      - entity: vacuum.v18_5c6bd716e393
        attribute: fan_speed
        value_not: Strong
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.v18_5c6bd716e393
        fan_speed: Silent
map_modes:
  - name: Zone cleanup
    icon: mdi:select-drag
    run_immediately: false
    coordinates_rounding: true
    selection_type: MANUAL_RECTANGLE
    max_selections: 5
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: xiaomi_miio.vacuum_clean_zone
      service_data:
        zone: '[[selection]]'
        repeats: '[[repeats]]'
        entity_id: '[[entity_id]]'
    predefined_selections: []
    variables: {}
  - name: Pin & Go
    icon: mdi:map-marker-plus
    run_immediately: false
    coordinates_rounding: true
    selection_type: MANUAL_POINT
    max_selections: 999
    repeats_type: NONE
    max_repeats: 1
    service_call_schema:
      service: xiaomi_miio.vacuum_goto
      service_data:
        x_coord: '[[point_x]]'
        y_coord: '[[point_y]]'
        entity_id: '[[entity_id]]'
    predefined_selections: []
    variables: {}
```

**Reply by PiotrMachowski** [reply]
Does [this config](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/584#discussioncomment-5860239) work?

**Reply by RedHomeA** [reply]
no I get the failed to call service xiaomi_miio/vacuum_clean_zone. Service not found.

**Reply by PiotrMachowski** [reply]
But it shows the map, which is important now.
Create a new card, follow [these steps](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/317), except step 3 and paste the output code of the card here.

Do *not* click "Generate static config" button.

**Reply by RedHomeA** [reply]
```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.v18_5c6bd716e393
vacuum_platform: default
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_clean_segment
    predefined_selections:
      - id: '1'
        icon:
          name: mdi:broom
          x: -1324.999738484621
          'y': -4800.000907853246
        label:
          text: Room1
          x: -1324.999738484621
          'y': -4800.000907853246
          offset_y: 35
        outline:
          - - -4974.999792873859
            - -7325.000945478678
          - - 2325.0003159046173
            - -7325.000945478678
          - - 2325.0003159046173
            - -2275.0008702278133
          - - -4974.999792873859
            - -2275.0008702278133
      - id: '2'
        icon:
          name: mdi:broom
          x: -974.9997332692146
          'y': -500.00084377825226
        label:
          text: Room2
          x: -974.9997332692146
          'y': -500.00084377825226
          offset_y: 35
        outline:
          - - -4224.9997816979885
            - -2325.0008709728713
          - - 2275.0003151595592
            - -2325.0008709728713
          - - 2275.0003151595592
            - 1324.9991834163668
          - - -4224.9997816979885
            - 1324.9991834163668
      - id: '3'
        icon:
          name: mdi:broom
          x: -3974.999777972698
          'y': -5475.0009179115295
        label:
          text: Room3
          x: -3974.999777972698
          'y': -5475.0009179115295
          offset_y: 35
        outline:
          - - -5524.999801069498
            - -7275.00094473362
          - - -2424.9997548758984
            - -7275.00094473362
          - - -2424.9997548758984
            - -3675.000891089439
          - - -5524.999801069498
            - -3675.000891089439
```

**Reply by PiotrMachowski** [reply]
Ok, now try following config:
```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.v18_5c6bd716e393
vacuum_platform: default
map_locked: true
map_modes:
  - template: vacuum_clean_segment
    service_call_schema:
      service: xiaomi_miot.call_action
      max_selections: 7
      service_data:
        entity_id: vacuum.v18_5c6bd716e393
        siid: 4
        aiid: 13
        params:
          - piid: 36
            value: 0
          - piid: 37
            value: 1
          - piid: 38
            value: '[[selection_unwrapped]]'
        force_params: true
    predefined_selections:
      - id: '1'
        icon:
          name: mdi:broom
          x: -1324.999738484621
          'y': -4800.000907853246
        label:
          text: Room1
          x: -1324.999738484621
          'y': -4800.000907853246
          offset_y: 35
        outline:
          - - -4974.999792873859
            - -7325.000945478678
          - - 2325.0003159046173
            - -7325.000945478678
          - - 2325.0003159046173
            - -2275.0008702278133
          - - -4974.999792873859
            - -2275.0008702278133
      - id: '2'
        icon:
          name: mdi:broom
          x: -974.9997332692146
          'y': -500.00084377825226
        label:
          text: Room2
          x: -974.9997332692146
          'y': -500.00084377825226
          offset_y: 35
        outline:
          - - -4224.9997816979885
            - -2325.0008709728713
          - - 2275.0003151595592
            - -2325.0008709728713
          - - 2275.0003151595592
            - 1324.9991834163668
          - - -4224.9997816979885
            - 1324.9991834163668
      - id: '3'
        icon:
          name: mdi:broom
          x: -3974.999777972698
          'y': -5475.0009179115295
        label:
          text: Room3
          x: -3974.999777972698
          'y': -5475.0009179115295
          offset_y: 35
        outline:
          - - -5524.999801069498
            - -7275.00094473362
          - - -2424.9997548758984
            - -7275.00094473362
          - - -2424.9997548758984
            - -3675.000891089439
          - - -5524.999801069498
            - -3675.000891089439

title: S9 Vacuum

**Reply by RedHomeA** [reply]
Tried this and the zone icons disappear.  The rooms are there but when I press play I hear "clean all started" and the robot no longer shows position on the map.

**Reply by PiotrMachowski** [reply]
Have you used this play button?
![image](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/6118709/ff5f860f-922c-4bdd-8021-96b6b6723c44)

**Reply by RedHomeA** [reply]
when I press this one I get Failed to call service xiaomi_miot/call_action. Service not found.

**Reply by PiotrMachowski** [reply]
Which integration do you use?
https://github.com/al-one/hass-xiaomi-miot
or
https://github.com/ha0y/xiaomi_miot_raw

**Reply by RedHomeA** [reply]
I used the RAW one.

its no longer showing the map
![image](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/132276763/f64cc7c7-22f1-4123-9ae8-9fd3f8766b87)

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.v18_5c6bd716e393
vacuum_platform: default
map_locked: true
map_modes:
  - template: vacuum_clean_segment
    service_call_schema:
      service: xiaomi_miot.call_action
      max_selections: 7
      service_data:
        entity_id: vacuum.v18_5c6bd716e393
        siid: 4
        aiid: 13
        params:
          - piid: 36
            value: 0
          - piid: 37
            value: 1
          - piid: 38
            value: '[[selection_unwrapped]]'
        force_params: true
    predefined_selections:
      - id: '1'
        icon:
          name: mdi:broom
          x: -1324.999738484621
          'y': -4800.000907853246
        label:
          text: Room1
          x: -1324.999738484621
          'y': -4800.000907853246
          offset_y: 35
        outline:
          - - -4974.999792873859
            - -7325.000945478678
          - - 2325.0003159046173
            - -7325.000945478678
          - - 2325.0003159046173
            - -2275.0008702278133
          - - -4974.999792873859
            - -2275.0008702278133
      - id: '2'
        icon:
          name: mdi:broom
          x: -974.9997332692146
          'y': -500.00084377825226
        label:
          text: Room2
          x: -974.9997332692146
          'y': -500.00084377825226
          offset_y: 35
        outline:
          - - -4224.9997816979885
            - -2325.0008709728713
          - - 2275.0003151595592
            - -2325.0008709728713
          - - 2275.0003151595592
            - 1324.9991834163668
          - - -4224.9997816979885
            - 1324.9991834163668
      - id: '3'
        icon:
          name: mdi:broom
          x: -3974.999777972698
          'y': -5475.0009179115295
        label:
          text: Room3
          x: -3974.999777972698
          'y': -5475.0009179115295
          offset_y: 35
        outline:
          - - -5524.999801069498
            - -7275.00094473362
          - - -2424.9997548758984
            - -7275.00094473362
          - - -2424.9997548758984
            - -3675.000891089439
          - - -5524.999801069498
            - -3675.000891089439
title: S9 Vacuum
```


Config
```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
      - rooms
```

services.ya,o on xiaomi_moit_raw
speak_text:
  description: 让小爱播报指定文本
  fields:
    entity_id:
      description: 实体 ID
      example: "media_player.xiao_ai"
      required: true
      selector:
        entity:
          integration: xiaomi_miot_raw
          domain: media_player
    text:
      description: 要播报的文本
      example: "你好"
      required: true
      selector:
        object:
execute_text:
  description: 让小爱执行指定指令
  fields:
    entity_id:
      description: 实体 ID
      example: "media_player.xiao_ai"
      required: true
      selector:
        entity:
          integration: xiaomi_miot_raw
          domain: media_player
    text:
      description: 要执行的文本
      example: "播放轻音乐"
      required: true
      selector:
        object:
    silent:
      description: (可选，默认否)静默执行
      example: "true"
      required: false
      selector:
        boolean:
call_action:
  description: 执行 action(供高级用户使用)
  fields:
    entity_id:
      description: 实体 ID
      example: "media_player.xiao_ai"
      required: true
      selector:
        entity:
          integration: xiaomi_miot_raw
    siid:
      description: siid
      example: 3
      required: true
      selector:
        number:
          min: 1
          max: 256
          mode: box
    aiid:
      description: aiid
      example: 1
      required: true
      selector:
        number:
          min: 1
          max: 256
          mode: box
    inn:
      description: in 参数，列表形式
      example: ""
      required: false
      selector:
        object:
set_miot_property:
  description: Set property(供高级用户使用)
  fields:
    entity_id:
      description: 实体 ID
      example: "switch.212a01_abcd"
      required: true
      selector:
        entity:
          integration: xiaomi_miot_raw
    siid:
      description: siid
      example: 2
      required: true
      selector:
        number:
          min: 1
          max: 256
          mode: box
    piid:
      description: piid
      example: 1
      required: true
      selector:
        number:
          min: 1
          max: 256
          mode: box
    value:
      description: 值
      example: "true"
      required: true
      selector:
        object:
