### DISCUSSION TITLE
Using dropdown menu instead of switch

### DISCUSSION THREAD

**Discussion by znanywawa** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#588] [Ideas]
Hi,

Now You map card works great, but I think it would be way better where instead of switching vacuuming mod, there would be dropdown menu like it is for choosing vacuum target:
![image](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/62244838/433124b5-2ffc-4ecc-93d5-c11120b4452c)

Then from map card we can choose vacuuming power and (if it will be possible for You to implement) mopping settings (for Roborock).

Regards.

**Comment by PiotrMachowski** [comment]
It is something that I wanted to do for quite some time, but right now I have enough problems with already existing dropdown menu. I will try to add this feature after I fix the modes menu (reuse the same component).

**Reply by znanywawa** [reply]
Great news!
Thanks for that and keeping fingers crossed for quick resolution of current problems :)

**Reply by PiotrMachowski** [reply]
![image](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/6118709/16f17293-2787-49a1-9567-56cd8125c1ac)
😉

**Reply by PiotrMachowski** [reply]
Can you check [v2.2.0-beta.2](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/releases/tag/v2.2.0-beta.2) version?

**Reply by znanywawa** [reply]
Both menus works well now (vacuum power and zones/rooms) :)
Great job!

**Reply by PiotrMachowski** [reply]
You should get new 2 icons with made from select entities: water_box_mode and mop_mode as well. Have they appeared?

**Reply by znanywawa** [reply]
> You should get new 2 icons with made from select entities: water_box_mode and mop_mode as well. Have they appeared?

Nope, even if mop is attached.

**Reply by PiotrMachowski** [reply]
:( can you show your config?

**Reply by znanywawa** [reply]
Sure, whole page config below:
```yaml
cards:
  - cards:
      - entity: vacuum.roborock_s7
        image: /local/pictures/vacuum/vacuum.png
        name: Roborock S7
        type: custom:xiaomi-vacuum-card
        vendor: xiaomi
      - cards:
          - elements:
              - entity: sensor.roborock_s7_side_brush_remaining
                style:
                  background-color: rgba(0, 0, 0, 0.3)
                  bottom: 0px
                  color: orange
                  font-size: 30px
                  left: 0px
                  right: 0px
                  transform: translate(0%,0%)
                title: '% Remaining Until Side Brush Should Be Replaced'
                type: state-label
              - entity: sensor.roborock_s7_side_brush_hrs_remaining
                prefix: 'Remaining '
                style:
                  bottom: 0px
                  color: white
                  font-size: 16px
                  line-height: 16px
                  right: 0px
                  transform: translate(0%,0%)
                title: Hours Remaining Until Side Brush Should Be Replaced
                type: state-label
              - icon: mdi:restart
                style:
                  color: white
                  padding: 7px
                  right: 0px
                  top: 0px
                  transform: translate(0%,0%)
                tap_action:
                  action: call-service
                  confirmation:
                    text: >-
                      Are you sure you want to reset the hours remaining counter
                      for replacing the side brush?
                  service: vacuum.send_command
                  service_data:
                    command: reset_consumable
                    entity_id: vacuum.roborock_s7
                    params:
                      - side_brush_work_time
                title: Reset Hours
                type: icon
            image: /local/pictures/vacuum//side_brush.png
            type: picture-elements
          - elements:
              - entity: sensor.roborock_s7_sensors_remaining
                style:
                  background-color: rgba(0, 0, 0, 0.3)
                  bottom: 0px
                  color: orange
                  font-size: 30px
                  left: 0px
                  right: 0px
                  transform: translate(0%,0%)
                title: '% Remaining Until Sensors Should Be Cleaned'
                type: state-label
              - entity: sensor.roborock_s7_sensors_hrs_remaining
                prefix: 'Remaining '
                style:
                  bottom: 0px
                  color: white
                  font-size: 16px
                  line-height: 16px
                  right: 0px
                  transform: translate(0%,0%)
                title: Hours Remaining Until Sensors Should Be Cleaned
                type: state-label
              - icon: mdi:restart
                style:
                  color: white
                  padding: 7px
                  right: 0px
                  top: 0px
                  transform: translate(0%,0%)
                tap_action:
                  action: call-service
                  confirmation:
                    text: >-
                      Are you sure you want to reset the hours remaining counter
                      for cleaning the sensors?
                  service: vacuum.send_command
                  service_data:
                    command: reset_consumable
                    entity_id: vacuum.roborock_s7
                    params:
                      - sensor_dirty_time
                title: Reset Hours
                type: icon
            image: /local/pictures/vacuum/sensors.png
            type: picture-elements
        type: horizontal-stack
      - cards:
          - elements:
              - entity: sensor.roborock_s7_filter_remaining
                style:
                  background-color: rgba(0, 0, 0, 0.3)
                  bottom: 0px
                  color: orange
                  font-size: 30px
                  left: 0px
                  right: 0px
                  transform: translate(0%,0%)
                title: '% Remaining Until Filter Should Be Replaced'
                type: state-label
              - entity: sensor.roborock_s7_filter_hrs_remaining
                prefix: 'Remaining '
                style:
                  bottom: 0px
                  color: white
                  font-size: 16px
                  line-height: 16px
                  right: 0px
                  transform: translate(0%,0%)
                title: Hours Remaining Until Filter Should Be Replaced
                type: state-label
              - icon: mdi:restart
                style:
                  color: white
                  padding: 7px
                  right: 0px
                  top: 0px
                  transform: translate(0%,0%)
                tap_action:
                  action: call-service
                  confirmation:
                    text: >-
                      Are you sure you want to reset the hours remaining counter
                      for replacing the filter?
                  service: vacuum.send_command
                  service_data:
                    command: reset_consumable
                    entity_id: vacuum.roborock_s7
                    params:
                      - filter_work_time
                title: Reset Hours
                type: icon
            image: /local/pictures/vacuum/filter.png
            type: picture-elements
          - elements:
              - entity: sensor.roborock_s7_main_brush_remaining
                style:
                  background-color: rgba(0, 0, 0, 0.3)
                  bottom: 0px
                  color: orange
                  font-size: 30px
                  left: 0px
                  right: 0px
                  transform: translate(0%,0%)
                title: '% Remaining Until Main Brush Should Be Replaced'
                type: state-label
              - entity: sensor.roborock_s7_main_brush_hrs_remaining
                prefix: 'Remaining '
                style:
                  bottom: 0px
                  color: white
                  font-size: 16px
                  line-height: 16px
                  right: 0px
                  transform: translate(0%,0%)
                title: Hours Remaining Until Main Brush Should Be Replaced
                type: state-label
              - icon: mdi:restart
                style:
                  color: white
                  padding: 7px
                  right: 0px
                  top: 0px
                  transform: translate(0%,0%)
                tap_action:
                  action: call-service
                  confirmation:
                    text: >-
                      Are you sure you want to reset the hours remaining counter
                      for replacing the main brush?
                  service: vacuum.send_command
                  service_data:
                    command: reset_consumable
                    entity_id: vacuum.roborock_s7
                    params:
                      - main_brush_work_time
                title: Reset Hours
                type: icon
            image: /local/pictures/vacuum/main_brush.png
            type: picture-elements
        type: horizontal-stack
    type: vertical-stack
  - cards:
      - calibration_source:
          camera: true
        entity: vacuum.roborock_s7
        map_locked: true
        map_modes:
          - template: vacuum_clean_zone
          - template: vacuum_goto
          - predefined_selections:
              - icon:
                  name: mdi:television
                  x: 27400
                  'y': 26350
                id: 17
              - icon:
                  name: mdi:human-child
                  x: 30600
                  'y': 25975
                id: 18
              - icon:
                  name: mdi:shower-head
                  x: 25125
                  'y': 30300
                id: 19
              - icon:
                  name: mdi:bed
                  x: 26100
                  'y': 34500
                id: 20
              - icon:
                  name: mdi:broom
                  x: 27400
                  'y': 31175
                id: 16
              - icon:
                  name: mdi:bathtub
                  x: 25475
                  'y': 32325
                id: 21
            template: vacuum_clean_segment
        map_source:
          camera: camera.roborock_s7_map
          crop:
            bottom: 230
            left: 200
            right: 220
            top: 220
        type: custom:xiaomi-vacuum-map-card
        vacuum_platform: humbertogontijo/homeassistant-roborock
    type: vertical-stack
items_classes: col-lg-4 col-xs-12
type: custom:dwains-flexbox-card
```

You card is the bottom one.
