### DISCUSSION TITLE
using official roborock integration in home assistant but failed to get the map working

### DISCUSSION THREAD

**Discussion by mantaalex** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#599] [Q&A]
Hey,
i'm using official roborock integration in home assistant but failed to get the map working.
i think it has something to do with the 'camera' part.
i have seen in the documentation:
```
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
```
But this is for the xiaomi app what do i have to do for the official roborock integration of home assistant ?
Thanks on advance !
Grz alex
