### DISCUSSION TITLE
Deebot T8 AIVI -- Creating Rooms

### DISCUSSION THREAD

**Discussion by MDLefevere** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#608] [Q&A]
Hello Piotr, Community,

I really really like the new map card and it looks really clean.
For some reason i'm struggling to get myself a zone selector.

In the Ecovacs app i have mapped 3 rooms. Livingroom, Kitchen and Hallway. How do i create them within Map Card?.
My rooms are a little bit wonky so no straight lines.

So far i got this:

```
type: custom:xiaomi-vacuum-map-card
entity: vacuum.brum
vacuum_platform: DeebotUniverse/Deebot-4-Home-Assistant
map_source:
  camera: camera.brum_live_map
map_locked: false
tiles:
  - entity: vacuum.brum
    label: Status
  - entity: sensor.brum_life_span_brush
    label: Borstel
  - entity: sensor.brum_life_span_side_brush
    label: Zij-borstels
```

![image](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/47443715/3228cd56-3aae-4fb0-9001-3ea6a38f1204)

It also drops things underneath eachother.
![image](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/47443715/a7c7011f-1ef3-48a6-bd32-7146b6b91620)
