### DISCUSSION TITLE
Save zoomed map state

### DISCUSSION THREAD

**Discussion by AseKarlsson** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#609] [Ideas]
Feature request:
It would be nice to be able to Zoom in to the map an lock it, for some or all users.
Or if not possible Zoom and Lock by users them self and that would be remembered after a refresh or restart.

**Comment by PiotrMachowski** [comment]
Ok, this is a correct place to ask this question :)

It is already possible using `crop` functionality:

```yaml
map_source:
  camera: camera.vacuum
  crop:
    top: 100
    left: 50
    top: 70
    bottom: 80
```
all values are in pixels
