### DISCUSSION TITLE
Valetudo + ICBINV 'invalid configuration'

### DISCUSSION THREAD

**Discussion by pinda707** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#614] [Q&A]
First of all, thanks for the amazing extension that saves noobs like me a lot of headaches trying to control the robot vacuums!
I run Home Assistant supervised with your 'I can't believe it's not Valetudo' extension and figured out how to get the rendered camera to work. 
However I'm stuck on the calibration source that's supposed to go with this setup, currently it's displaying 'invalid calibration'. I'm sure it's something simple i'm missing but not a lot of people run this setup it seems so I don't have a lot of configs to look at.
This all the code I have currently:
```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.valetudo_ediblecreativedugong
vacuum_platform: Hypfer/Valetudo
map_source:
  camera: camera.ediblecreativedugong_rendered_map
calibration_source:
  camera: true
```

Edit: I didn't see the available templates that explain everything I struggled with very clearly, doh! Is there a way to delete this thread or should it be left up and closed? I'm not very familiar with Git..
Cheers!
