### DISCUSSION TITLE
Map resets on each cleanup - loose access to zones

### DISCUSSION THREAD

**Discussion by ngmartins** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#615] [Q&A] [answered]
Hello. 
First things first: kudos on the amazing job you're doing here :)

I'm experiencing something a bit weird and I didn't realize how to work around it yet.
I'm using the ` clean_zone_predefined` mode like the below:

```
map_modes:
            - template: vacuum_clean_zone_predefined
              predefined_selections:
                - zones: [[22360, 23896, 26037, 28450]]
                  icon:
                    name: mdi:desktop-classic
                    x: 24263
                    y: 25978
                - zones: [[15803, 23667, 22250, 28451]]
                  icon:
                    name: mdi:sofa
                    x: 24401
                    y: 26736
         (...)
```
The icons on the zones are displayed on the map as expected.
BUT when a new cleanup starts, the previous map disappears, and a new map start being extracted...
 
This means that when I perform a cleanup on a single zone, I got a limited map where some of the zones cannot be displayed.
In the very extreme scenario, When I clean the zone where the dock is installed, no more zones can be cleaned (just this zone on the map - it is impossible to select the other zones).

Any workaround for this?
I don't mind the map being updated, but I would like to always have access to the zones.
Is there any way of listing the zones somehow?

Thanks :)
