### DISCUSSION TITLE
Does anyone have a working Wyze Room configuration they can show me? Im having issues enabling any type of room selection based cleaning using this card.

### DISCUSSION THREAD

**Discussion by SpartanTech** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#616] [Q&A]
Does anyone have a working Wyze Room configuration they can show me? Im having issues enabling any type of room selection based cleaning using this card.

The card works by itself, but after generating coordinates by using the guide and drawing a zone over existing wyze rooms, I add them like the wiki says and it just shows up blank.

```yaml
type: custom:xiaomi-vacuum-map-card
title: Vacuum
entity: vacuum.romo_vacuum
vacuum_platform: romedtino/simple-wyze-vac
map_source:
  camera: camera.romo_vacuum_camera
map_locked: true
map_modes:
  - template: vacuum_clean_segment
    predefined_selections:
      - id: Kitchen
        outline: [[301, 812, 753, 1624]]
        label:
          text: "Kitchen"
          x: 400
          y: 850
          offset_y: 35
        icon:
          name: "mdi:bed"
          x: 400
          y: 750
      - id: Bathroom
        outline: [[342, 2258, 451, 2570]]
        label:
          text: "Bathroom"
          x: 322
          y: 2264
          offset_y: 35
        icon:
          name: "mdi:shower"
          x: 322
          y: 2264
```
