### DISCUSSION TITLE
If vacuum_platform = "Roomba" with template: vacuum_clean_segment, get "Each point of room outline must have 2 parameters"

### DISCUSSION THREAD

**Discussion by douginoz** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#619] [General]
I have a couple of problems:
1.  If vacuum_platform = "Setup integer', the Zone cleanup icon appears below the map and I get the ability to draw boxes on the map and find out the values.  For instance, if I draw a box on the map, it shows 

`Selection: [[629, 951, 1258, 1901]]`

However, for this to work I have to delete the entire map_modes section because 'template: vacuum_clean_segment' gives the error 
`
Invalid template: vacuum_clean_segment`

If I change vacuum_platform = Roomba, then I no longer see the Zone cleanup icon and I can't draw or click on anything on the map, but I can then include the 

```
map_modes:
  - template: vacuum_clean_segment
```

part of the YAML code.  

That means I can't use the Zone cleanup tool to determine map coordinates if I've already created all the map_modes configuration.  I can work around that by first having a small YAML that allows me to find out the coordinates, then change it later.

The second problem is that when I use the Zone cleanup tool and draw a box, it gives the values

`Selection: [[629, 951, 1258, 1901]]`

But if I try to use those in the YAML code like below, I get an error:

```
type: custom:xiaomi-vacuum-map-card
title: Roomba
entity: vacuum.roomba1
vacuum_platform: Roomba
map_source:
  image: /local/images/roombamap.png
map_locked: true
calibration_source:
  platform: Roomba
map_modes:
  - template: vacuum_clean_segment
    variables:
      pmap_id: w8fRUuYCTx-wBFdx3aTq9Q
    predefined_selections:
      - id: 1
        variables:
          type: rid
        outline: [[1076, 830, 1865, 1663]]
        label:
          text: "Living Room"
          x: 1313
          y: 1166
          offset_y: 35
        icon:
          name: "mdi:sofa-outline"
          x: 22932
          y: 30339
```
The error is:
! Each point of room outline must have 2 parameters

How do I convert the value I was given `Selection: [[629, 951, 1258, 1901]]` into the correct 'outline:' value in the YAML?
