### DISCUSSION TITLE
Is there a way to hide Map-related elements on a card?

### DISCUSSION THREAD

**Discussion by SeasonPhan** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#627] [Q&A]
I have 2 robot vacuum, one of which doesnt use map.

For consistency, i would like to have both card with a same style
For now i can hide the map by cropping an image,
but how can i hide this red section?

![image](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/61407079/0d64f107-ecd0-4532-ab0f-f05f0195f14b)

**Comment by PiotrMachowski** [comment]
This config should work:
```yaml
map_modes: []
```

**Reply by SeasonPhan** [reply]
This doesnt seem to work, the card looks the same
this is my config

```vacuum_platform: Setup integer
map_source:
  image: https://a.picture.com/image.png
  crop:
    top: 1000
    left: 0
    right: 0
    bottom: 0
calibration_source:
  identity: true
map_modes: []```

**Reply by PiotrMachowski** [reply]
Do you have the latest version of the card? Can you show your full config?

**Reply by SeasonPhan** [reply]
yes, im using the lastest 2.2.2
here is my full config
```
type: custom:xiaomi-vacuum-map-card
title: GOSEE Rotopus M
entity: vacuum.segoo
vacuum_platform: Setup integer
map_source:
  image: https://a.picture.com/image.png
  crop:
    top: 1000
    left: 0
    right: 0
    bottom: 0
calibration_source:
  identity: true
map_modes: []
icons:
  - icon: mdi:play
    conditions:
      - entity: vacuum.segoo
        value_not: cleaning
    tap_action:
      action: call-service
      service: localtuya.set_dp
      service_data:
        device_id: eb9d6460f2107dc606ais7
        dp: 101
        value: true
  - icon: mdi:pause
    conditions:
      - entity: vacuum.segoo
        value_not: docked
      - entity: vacuum.segoo
        value_not: returning
      - entity: vacuum.segoo
        value_not: paused
    tap_action:
      action: call-service
      service: localtuya.set_dp
      service_data:
        device_id: eb9d6460f2107dc606ais7
        dp: 102
        value: true
  - icon: mdi:pause
    conditions:
      - entity: vacuum.segoo
        value: returning
    tap_action:
      action: call-service
      service: localtuya.set_dp
      service_data:
        device_id: eb9d6460f2107dc606ais7
        dp: 103
        value: false
  - icon: mdi:fan-minus
    conditions:
      - entity: vacuum.segoo
        attribute: fan_speed
        value: quiet
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        fan_speed: auto
        entity_id: vacuum.segoo
  - icon: mdi:fan-auto
    conditions:
      - entity: vacuum.segoo
        attribute: fan_speed
        value: auto
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        fan_speed: strong
        entity_id: vacuum.segoo
  - icon: mdi:fan-plus
    conditions:
      - entity: vacuum.segoo
        attribute: fan_speed
        value: strong
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        fan_speed: quiet
        entity_id: vacuum.segoo
  - icon: mdi:map-marker-radius
    tap_action:
      action: call-service
      service: localtuya.set_dp
      service_data:
        device_id: eb9d6460f2107dc606ais7
        dp: 112
        value: true
  - icon: mdi:home-lightning-bolt
    tap_action:
      action: call-service
      service: localtuya.set_dp
      service_data:
        device_id: eb9d6460f2107dc606ais7
        dp: 103
        value: true
tiles:
  - tile_id: status
    entity: vacuum.segoo
    label: Status
    icon: mdi:robot-vacuum
  - tile_id: battery_level
    entity: vacuum.segoo
    attribute: battery_level
    icon_source: vacuum.segoo.attributes.battery_icon
    unit: '%'
  - tile_id: fan_speed
    entity: vacuum.segoo
    attribute: fan_speed
    icon: mdi:fan
    translations:
      quiet: Quiet
      auto: Auto
      strong: Loud
  - tile_id: Sound_segoo
    replace_config: true
    entity: switch.mute
    label: Sound - Tap to turn off
    icon: mdi:volume-high
    tap_action:
      action: call-service
      service: switch.turn_on
      service_data:
        entity_id: switch.mute
    conditions:
      - entity: switch.mute
        value: 'off'
    translations:
      'off': Normal
  - tile_id: Sound_segoo
    entity: switch.mute
    label: Sound - Tap to turn on
    icon: mdi:volume-variant-off
    tap_action:
      action: call-service
      service: switch.turn_off
      service_data:
        entity_id: switch.mute
    conditions:
      - entity: switch.mute
        value: 'on'
    translations:
      'on': Silent
```

**Reply by PiotrMachowski** [reply]
Try this one:
```yaml
type: custom:xiaomi-vacuum-map-card
title: GOSEE Rotopus M
entity: vacuum.segoo
vacuum_platform: Setup integer
map_source:
  image: https://a.picture.com/image.png
calibration_source:
  identity: true
map_modes: []
card_mod:
  style: |
    .map-wrapper {
      display: none;
    }
icons: ...
tiles: ...
```
