### DISCUSSION TITLE
Change map but also the rooms layout

### DISCUSSION THREAD

**Discussion by saschabrockel** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#633] [Q&A] [answered]
Hey there. I am experimenting for hours now to get the card working in a perfect way. It looks like this now:
![image](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/33376463/c857bdc7-e20a-4a42-9fd8-7e043d0db701)

With the icon_button on the right, I can switch between 3 maps. The map will change according to the sensor and Roborock app but it does not change on the card until I start a cleaning. Sometimes it does not even change the map. And the bad thing is that if I start the cleaning then, the layout of the rooms on my other map are still located and it looks very weird. How can I fix this? I have only generated the map for my main map and also defined the rooms. I can do it for them too but I guess the map will not know which rooms are according to the map right?
![image](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/33376463/d9fb9b29-2897-4158-b844-2f2b6cc815b6)
![image](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/33376463/b0dc431b-bdf2-42dc-abff-61ce5135c607)

I only made it now if I manually select the correct rooms.

**Comment by PiotrMachowski** [comment]
Do you have a sensor that tells which floor is now visible?

**Reply by saschabrockel** [reply]
Hey. Yes the one you can see on the pictures called map. It returns the name of the current map / floor.

**Reply by PiotrMachowski** [reply]
Please post your full config, I'll adjust it for you

**Reply by saschabrockel** [reply]
That's too kind. I will try to understand it then. Don't get shocked it's a huge config.

<details>
<summary>Code</summary>


```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.roborock_s7_2
vacuum_platform: humbertogontijo/homeassistant-roborock
translations: de
map_source:
  camera: camera.roborock_s7_map
  crop:
    top: 70
    left: 100
    right: 100
    bottom: 200
calibration_source:
  camera: true
map_modes:
  - name: Räume Sascha
    template: vacuum_clean_segment
    predefined_selections:
      - id: '16'
        icon:
          name: mdi:bed
          x: 23800
          'y': 27425
        label:
          text: Schlafzimmer
          x: 23800
          'y': 27425
          offset_x: 15
          offset_y: -40
        outline:
          - - 21700
            - 25300
          - - 25900
            - 25300
          - - 25900
            - 29550
          - - 21700
            - 29550
      - id: '17'
        icon:
          name: mdi:sofa
          x: 24000
          'y': 32675
        label:
          text: Wohnzimmer
          x: 24000
          'y': 32675
          offset_x: 8
          offset_y: 50
        outline:
          - - 22300
            - 29600
          - - 25700
            - 29600
          - - 25700
            - 35750
          - - 22300
            - 35750
      - id: '18'
        icon:
          name: mdi:floor-plan
          x: 20775
          'y': 30425
        label:
          text: Flur
          x: 20775
          'y': 30425
          offset_x: -35
          offset_y: 4
        outline:
          - - 18750
            - 29800
          - - 22800
            - 29800
          - - 22800
            - 31050
          - - 18750
            - 31050
      - id: '19'
        icon:
          name: mdi:fridge
          x: 21250
          'y': 32375
        label:
          text: Küche
          x: 21250
          'y': 32375
          offset_y: 30
          offset_x: 8
        outline:
          - - 20350
            - 31100
          - - 22150
            - 31100
          - - 22150
            - 33650
          - - 20350
            - 33650
      - id: '21'
        icon:
          name: mdi:bathtub
          x: 19250
          'y': 32175
        label:
          text: Bad
          x: 19250
          'y': 32175
          offset_y: 28
          offset_x: 2
        outline:
          - - 18650
            - 31100
          - - 19850
            - 31100
          - - 19850
            - 33250
          - - 18650
            - 33250
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_follow_path
  - name: Räume Papa
    template: vacuum_clean_segment
    predefined_selections:
      - id: '16'
        icon:
          name: mdi:broom
          x: 25875
          'y': 24850
        label:
          text: Room 16
          x: 25875
          'y': 24850
          offset_y: 35
        outline:
          - - 24200
            - 22700
          - - 27550
            - 22700
          - - 27550
            - 27000
          - - 24200
            - 27000
      - id: '17'
        icon:
          name: mdi:broom
          x: 22825
          'y': 26325
        label:
          text: Room 17
          x: 22825
          'y': 26325
          offset_y: 35
        outline:
          - - 21500
            - 25650
          - - 24150
            - 25650
          - - 24150
            - 27000
          - - 21500
            - 27000
      - id: '18'
        icon:
          name: mdi:broom
          x: 23275
          'y': 24550
        label:
          text: Room 18
          x: 23275
          'y': 24550
          offset_y: 35
        outline:
          - - 22550
            - 23500
          - - 24000
            - 23500
          - - 24000
            - 25600
          - - 22550
            - 25600
      - id: '19'
        icon:
          name: mdi:broom
          x: 20225
          'y': 24125
        label:
          text: Room 19
          x: 20225
          'y': 24125
          offset_y: 35
        outline:
          - - 18250
            - 21250
          - - 22200
            - 21250
          - - 22200
            - 27000
          - - 18250
            - 27000
      - id: '21'
        icon:
          name: mdi:broom
          x: 17025
          'y': 24750
        label:
          text: Room 21
          x: 17025
          'y': 24750
          offset_y: 35
        outline:
          - - 15850
            - 22550
          - - 18200
            - 22550
          - - 18200
            - 26950
          - - 15850
            - 26950
map_locked: true
tiles:
  - tile_id: status
    entity: vacuum.roborock_s7_2
    label: Status
    attribute: status
    icon: mdi:robot-vacuum
    translations:
      starting: Starte
      charger disconnected: Ladegerät getrennt
      idle: Untätig
      remote control active: Fernsteuerung aktiv
      cleaning: Reinigen
      returning home: Rückkehr
      manual mode: Manueller Modus
      charging: Aufladen
      charging problem: Aufladeproblem
      paused: Pausiert
      spot cleaning: Punktuelle Reinigung
      error: Fehler
      shutting down: Herunterfahren
      updating: Aktualisieren
      docking: Andocken
      going to target: Fahre zum Ziel
      zoned cleaning: Zonenreinigung
      segment cleaning: Segmentreinigung
      emptying the bin: Entleeren des Behälters
      charging complete: Aufladen abgeschlossen
      device offline: Gerät offline
  - tile_id: battery_level
    entity: vacuum.roborock_s7_2
    label: Akkustand
    attribute: battery_level
    icon_source: vacuum.roborock_s7_2.attributes.battery_icon
    unit: '%'
  - tile_id: fan_speed
    entity: vacuum.roborock_s7_2
    label: Saugleistung
    attribute: fan_speed
    icon: mdi:fan
    translations:
      'off': Aus
      silent: Leise
      quiet: Leise
      standard: Standard
      balanced: Normal
      medium: Medium
      turbo: Turbo
      auto: Auto
      gentle: Gentle
      custom: Indiv.
  - tile_id: cleaning_count
    label: Reinungsanzahl
    entity: sensor.roborock_s7_total_clean_count_2
    icon: mdi:counter
    precision: 0
    translations: {}
  - tile_id: sensor_dirty_left
    label: Sensoren übrig
    unit: h
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: {}
      service_data:
        command: reset_consumable
        params: sensor_dirty_time
        entity_id: vacuum.roborock_s7_2
    entity: sensor.roborock_s7_sensor_dirty_left_2
    icon: mdi:eye-outline
    precision: 0
    translations: {}
  - tile_id: filter_left
    label: Filter übrig
    unit: h
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: {}
      service_data:
        command: reset_consumable
        params: filter_work_time
        entity_id: vacuum.roborock_s7_2
    entity: sensor.roborock_s7_filter_left_2
    icon: mdi:air-filter
    precision: 0
    translations: {}
  - tile_id: cleaned_area
    label: Gereinigte Fläche
    unit: m²
    precision: 2
    entity: sensor.roborock_s7_current_clean_area_2
    icon: mdi:texture-box
    translations: {}
  - tile_id: cleaning_time
    label: Reinigungszeit
    unit: min
    multiplier: 0.016667
    entity: sensor.roborock_s7_current_clean_duration_2
    icon: mdi:timer-sand
    precision: 0
    translations: {}
  - tile_id: map
    entity: sensor.roborock_s7_current_map_selected
    label: Map
    icon: mdi:floor-plan
    translations: {}
  - tile_id: wischtuch
    entity: binary_sensor.roborock_s7_mop_attached_2
    label: Wischtuch
    translations:
      verbunden: Dran
  - tile_id: wassertank
    entity: binary_sensor.roborock_s7_water_box_attached_2
    label: Wassertank
    translations:
      verbunden: Dran
  - tile_id: wasserstand
    entity: binary_sensor.roborock_s7_water_shortage_2
    label: Wasserstand
    translations: {}
icons:
  - icon: mdi:play
    conditions:
      - entity: vacuum.roborock_s7_2
        value_not: cleaning
      - entity: vacuum.roborock_s7_2
        value_not: error
      - entity: vacuum.roborock_s7_2
        value_not: returning
    tooltip: Start
    tap_action:
      action: call-service
      service: vacuum.start
      service_data:
        entity_id: vacuum.roborock_s7_2
  - icon: mdi:pause
    conditions:
      - entity: vacuum.roborock_s7_2
        value_not: docked
      - entity: vacuum.roborock_s7_2
        value_not: idle
      - entity: vacuum.roborock_s7_2
        value_not: error
      - entity: vacuum.roborock_s7_2
        value_not: paused
    tooltip: Pause
    tap_action:
      action: call-service
      service: vacuum.pause
      service_data:
        entity_id: vacuum.roborock_s7_2
  - icon: mdi:stop
    conditions:
      - entity: vacuum.roborock_s7_2
        value_not: docked
      - entity: vacuum.roborock_s7_2
        value_not: idle
      - entity: vacuum.roborock_s7_2
        value_not: error
      - entity: vacuum.roborock_s7_2
        value_not: paused
    tooltip: Stop
    tap_action:
      action: call-service
      service: vacuum.stop
      service_data:
        entity_id: vacuum.roborock_s7_2
  - icon: mdi:home-map-marker
    conditions:
      - entity: vacuum.roborock_s7_2
        value_not: docked
      - entity: vacuum.roborock_s7_2
        value_not: returning
    tooltip: Rückkehr
    tap_action:
      action: call-service
      service: vacuum.return_to_base
      service_data:
        entity_id: vacuum.roborock_s7_2
  - icon: mdi:target-variant
    conditions:
      - entity: vacuum.roborock_s7_2
        value_not: docked
      - entity: vacuum.roborock_s7_2
        value_not: error
      - entity: vacuum.roborock_s7_2
        value_not: cleaning
      - entity: vacuum.roborock_s7_2
        value_not: returning
    tooltip: Clean spot
    tap_action:
      action: call-service
      service: vacuum.clean_spot
      service_data:
        entity_id: vacuum.roborock_s7_2
  - icon: mdi:map-marker
    tooltip: Locate
    tap_action:
      action: call-service
      service: vacuum.locate
      service_data:
        entity_id: vacuum.roborock_s7_2
  - menu_id: fan_speed
    icon: mdi:fan-alert
    label: Aus
    conditions:
      - entity: vacuum.roborock_s7_2
        attribute: fan_speed
        value: 'off'
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: '[[entity_id]]'
        fan_speed: 'off'
  - menu_id: fan_speed
    icon: mdi:fan-alert
    label: Leise
    conditions:
      - entity: vacuum.roborock_s7_2
        attribute: fan_speed
        value: quiet
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: '[[entity_id]]'
        fan_speed: quiet
  - menu_id: fan_speed
    icon: mdi:fan-alert
    label: Normal
    conditions:
      - entity: vacuum.roborock_s7_2
        attribute: fan_speed
        value: balanced
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: '[[entity_id]]'
        fan_speed: balanced
  - menu_id: fan_speed
    icon: mdi:fan-alert
    label: Turbo
    conditions:
      - entity: vacuum.roborock_s7_2
        attribute: fan_speed
        value: turbo
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: '[[entity_id]]'
        fan_speed: turbo
  - menu_id: fan_speed
    icon: mdi:fan-alert
    label: Max
    conditions:
      - entity: vacuum.roborock_s7_2
        attribute: fan_speed
        value: max
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: '[[entity_id]]'
        fan_speed: max
  - menu_id: fan_speed
    icon: mdi:fan-alert
    label: Indiv.
    conditions:
      - entity: vacuum.roborock_s7_2
        attribute: fan_speed
        value: custom
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: '[[entity_id]]'
        fan_speed: custom
  - icon: mdi:fan
    conditions:
      - entity: vacuum.roborock_s7_2
        attribute: fan_speed
        value_not: 'off'
      - entity: vacuum.roborock_s7_2
        attribute: fan_speed
        value_not: quiet
      - entity: vacuum.roborock_s7_2
        attribute: fan_speed
        value_not: balanced
      - entity: vacuum.roborock_s7_2
        attribute: fan_speed
        value_not: turbo
      - entity: vacuum.roborock_s7_2
        attribute: fan_speed
        value_not: max
      - entity: vacuum.roborock_s7_2
        attribute: fan_speed
        value_not: custom
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_s7_2
        fan_speed: 'off'
  - type: menu
    menu_id: water_box_mode
    icon_id: water_box_mode
    available_values_attribute: options
    value_translation_keys:
      'off': Aus
      mild: Sanft
      moderate: Mittel
      intense: Intensiv
      custom: Indiv.
    icon: mdi:water
    icon_mapping:
      'off': mdi:water-remove
      mild: mdi:water-minus
      moderate: mdi:water
      intense: mdi:water-plus
      custom: mdi:water-sync
    tap_action:
      action: call-service
      service: select.select_option
      service_data:
        option: '[[value]]'
        entity_id: '[[entity_id]]'
    entity: select.roborock_s7_mop_intensity
  - type: menu
    menu_id: mop_mode
    icon_id: mop_mode
    available_values_attribute: options
    value_translation_keys:
      deep: Gründlich
      deep+: Gründlich+
      custom: Indiv.
    icon: mdi:water
    icon_mapping:
      standard: mdi:standard-definition
      deep: mdi:high-definition
      deep_plus: mdi:ultra-high-definition
      custom: mdi:fit-to-screen-outline
    tap_action:
      action: call-service
      service: select.select_option
      service_data:
        option: '[[value]]'
        entity_id: '[[entity_id]]'
    entity: select.roborock_s7_mop_mode
  - menu_id: map_mode
    icon: mdi:home-switch
    label: Sascha
    conditions:
      - entity: vacuum.roborock_s7_2
        value_not: cleaning
      - entity: vacuum.roborock_s7_2
        value_not: error
      - entity: vacuum.roborock_s7_2
        value_not: returning
    tooltip: Map wechseln
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: '[[entity_id]]'
        command: load_multi_map
        params: 0
  - menu_id: map_mode
    icon: mdi:home-switch
    label: Mama
    conditions:
      - entity: vacuum.roborock_s7_2
        value_not: cleaning
      - entity: vacuum.roborock_s7_2
        value_not: error
      - entity: vacuum.roborock_s7_2
        value_not: returning
    tooltip: Map wechseln
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: '[[entity_id]]'
        command: load_multi_map
        params: 2
  - menu_id: map_mode
    icon: mdi:home-switch
    label: Papa
    conditions:
      - entity: vacuum.roborock_s7_2
        value_not: cleaning
      - entity: vacuum.roborock_s7_2
        value_not: error
      - entity: vacuum.roborock_s7_2
        value_not: returning
    tooltip: Map wechseln
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: '[[entity_id]]'
        command: load_multi_map
        params: 3
```


</details>

**Reply by PiotrMachowski** [reply, marked as answer]
Well, it's about to get even bigger:
<details>
<summary>Code</summary>


```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.roborock_s7_2
vacuum_platform: humbertogontijo/homeassistant-roborock
language: de
map_source: &map_source
  camera: camera.roborock_s7_map
  crop:
    top: 70
    left: 100
    right: 100
    bottom: 200
calibration_source:
  camera: true
preset_name: Sascha
map_locked: true
conditions:
  - entity: sensor.roborock_s7_current_map_selected
    value: sascha
map_modes:
  - name: Räume Sascha
    template: vacuum_clean_segment
    predefined_selections:
      - id: '16'
        icon:
          name: mdi:bed
          x: 23800
          'y': 27425
        label:
          text: Schlafzimmer
          x: 23800
          'y': 27425
          offset_x: 15
          offset_y: -40
        outline:
          - - 21700
            - 25300
          - - 25900
            - 25300
          - - 25900
            - 29550
          - - 21700
            - 29550
      - id: '17'
        icon:
          name: mdi:sofa
          x: 24000
          'y': 32675
        label:
          text: Wohnzimmer
          x: 24000
          'y': 32675
          offset_x: 8
          offset_y: 50
        outline:
          - - 22300
            - 29600
          - - 25700
            - 29600
          - - 25700
            - 35750
          - - 22300
            - 35750
      - id: '18'
        icon:
          name: mdi:floor-plan
          x: 20775
          'y': 30425
        label:
          text: Flur
          x: 20775
          'y': 30425
          offset_x: -35
          offset_y: 4
        outline:
          - - 18750
            - 29800
          - - 22800
            - 29800
          - - 22800
            - 31050
          - - 18750
            - 31050
      - id: '19'
        icon:
          name: mdi:fridge
          x: 21250
          'y': 32375
        label:
          text: Küche
          x: 21250
          'y': 32375
          offset_y: 30
          offset_x: 8
        outline:
          - - 20350
            - 31100
          - - 22150
            - 31100
          - - 22150
            - 33650
          - - 20350
            - 33650
      - id: '21'
        icon:
          name: mdi:bathtub
          x: 19250
          'y': 32175
        label:
          text: Bad
          x: 19250
          'y': 32175
          offset_y: 28
          offset_x: 2
        outline:
          - - 18650
            - 31100
          - - 19850
            - 31100
          - - 19850
            - 33250
          - - 18650
            - 33250
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_follow_path
tiles: &tiles
  - tile_id: status
    entity: vacuum.roborock_s7_2
    label: Status
    attribute: status
    icon: mdi:robot-vacuum
    translations:
      starting: Starte
      charger disconnected: Ladegerät getrennt
      idle: Untätig
      remote control active: Fernsteuerung aktiv
      cleaning: Reinigen
      returning home: Rückkehr
      manual mode: Manueller Modus
      charging: Aufladen
      charging problem: Aufladeproblem
      paused: Pausiert
      spot cleaning: Punktuelle Reinigung
      error: Fehler
      shutting down: Herunterfahren
      updating: Aktualisieren
      docking: Andocken
      going to target: Fahre zum Ziel
      zoned cleaning: Zonenreinigung
      segment cleaning: Segmentreinigung
      emptying the bin: Entleeren des Behälters
      charging complete: Aufladen abgeschlossen
      device offline: Gerät offline
  - tile_id: battery_level
    entity: vacuum.roborock_s7_2
    label: Akkustand
    attribute: battery_level
    icon_source: vacuum.roborock_s7_2.attributes.battery_icon
    unit: '%'
  - tile_id: fan_speed
    entity: vacuum.roborock_s7_2
    label: Saugleistung
    attribute: fan_speed
    icon: mdi:fan
    translations:
      'off': Aus
      silent: Leise
      quiet: Leise
      standard: Standard
      balanced: Normal
      medium: Medium
      turbo: Turbo
      auto: Auto
      gentle: Gentle
      custom: Indiv.
  - tile_id: cleaning_count
    label: Reinungsanzahl
    entity: sensor.roborock_s7_total_clean_count_2
    icon: mdi:counter
    precision: 0
    translations: {}
  - tile_id: sensor_dirty_left
    label: Sensoren übrig
    unit: h
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: {}
      service_data:
        command: reset_consumable
        params: sensor_dirty_time
        entity_id: vacuum.roborock_s7_2
    entity: sensor.roborock_s7_sensor_dirty_left_2
    icon: mdi:eye-outline
    precision: 0
    translations: {}
  - tile_id: filter_left
    label: Filter übrig
    unit: h
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: {}
      service_data:
        command: reset_consumable
        params: filter_work_time
        entity_id: vacuum.roborock_s7_2
    entity: sensor.roborock_s7_filter_left_2
    icon: mdi:air-filter
    precision: 0
    translations: {}
  - tile_id: cleaned_area
    label: Gereinigte Fläche
    unit: m²
    precision: 2
    entity: sensor.roborock_s7_current_clean_area_2
    icon: mdi:texture-box
    translations: {}
  - tile_id: cleaning_time
    label: Reinigungszeit
    unit: min
    multiplier: 0.016667
    entity: sensor.roborock_s7_current_clean_duration_2
    icon: mdi:timer-sand
    precision: 0
    translations: {}
  - tile_id: map
    entity: sensor.roborock_s7_current_map_selected
    label: Map
    icon: mdi:floor-plan
    translations: {}
  - tile_id: wischtuch
    entity: binary_sensor.roborock_s7_mop_attached_2
    label: Wischtuch
    translations:
      verbunden: Dran
  - tile_id: wassertank
    entity: binary_sensor.roborock_s7_water_box_attached_2
    label: Wassertank
    translations:
      verbunden: Dran
  - tile_id: wasserstand
    entity: binary_sensor.roborock_s7_water_shortage_2
    label: Wasserstand
    translations: {}
icons: &icons
  - icon: mdi:play
    conditions:
      - entity: vacuum.roborock_s7_2
        value_not: cleaning
      - entity: vacuum.roborock_s7_2
        value_not: error
      - entity: vacuum.roborock_s7_2
        value_not: returning
    tooltip: Start
    tap_action:
      action: call-service
      service: vacuum.start
      service_data:
        entity_id: vacuum.roborock_s7_2
  - icon: mdi:pause
    conditions:
      - entity: vacuum.roborock_s7_2
        value_not: docked
      - entity: vacuum.roborock_s7_2
        value_not: idle
      - entity: vacuum.roborock_s7_2
        value_not: error
      - entity: vacuum.roborock_s7_2
        value_not: paused
    tooltip: Pause
    tap_action:
      action: call-service
      service: vacuum.pause
      service_data:
        entity_id: vacuum.roborock_s7_2
  - icon: mdi:stop
    conditions:
      - entity: vacuum.roborock_s7_2
        value_not: docked
      - entity: vacuum.roborock_s7_2
        value_not: idle
      - entity: vacuum.roborock_s7_2
        value_not: error
      - entity: vacuum.roborock_s7_2
        value_not: paused
    tooltip: Stop
    tap_action:
      action: call-service
      service: vacuum.stop
      service_data:
        entity_id: vacuum.roborock_s7_2
  - icon: mdi:home-map-marker
    conditions:
      - entity: vacuum.roborock_s7_2
        value_not: docked
      - entity: vacuum.roborock_s7_2
        value_not: returning
    tooltip: Rückkehr
    tap_action:
      action: call-service
      service: vacuum.return_to_base
      service_data:
        entity_id: vacuum.roborock_s7_2
  - icon: mdi:target-variant
    conditions:
      - entity: vacuum.roborock_s7_2
        value_not: docked
      - entity: vacuum.roborock_s7_2
        value_not: error
      - entity: vacuum.roborock_s7_2
        value_not: cleaning
      - entity: vacuum.roborock_s7_2
        value_not: returning
    tooltip: Clean spot
    tap_action:
      action: call-service
      service: vacuum.clean_spot
      service_data:
        entity_id: vacuum.roborock_s7_2
  - icon: mdi:map-marker
    tooltip: Locate
    tap_action:
      action: call-service
      service: vacuum.locate
      service_data:
        entity_id: vacuum.roborock_s7_2
  - menu_id: fan_speed
    icon: mdi:fan-alert
    label: Aus
    conditions:
      - entity: vacuum.roborock_s7_2
        attribute: fan_speed
        value: 'off'
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: '[[entity_id]]'
        fan_speed: 'off'
  - menu_id: fan_speed
    icon: mdi:fan-alert
    label: Leise
    conditions:
      - entity: vacuum.roborock_s7_2
        attribute: fan_speed
        value: quiet
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: '[[entity_id]]'
        fan_speed: quiet
  - menu_id: fan_speed
    icon: mdi:fan-alert
    label: Normal
    conditions:
      - entity: vacuum.roborock_s7_2
        attribute: fan_speed
        value: balanced
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: '[[entity_id]]'
        fan_speed: balanced
  - menu_id: fan_speed
    icon: mdi:fan-alert
    label: Turbo
    conditions:
      - entity: vacuum.roborock_s7_2
        attribute: fan_speed
        value: turbo
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: '[[entity_id]]'
        fan_speed: turbo
  - menu_id: fan_speed
    icon: mdi:fan-alert
    label: Max
    conditions:
      - entity: vacuum.roborock_s7_2
        attribute: fan_speed
        value: max
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: '[[entity_id]]'
        fan_speed: max
  - menu_id: fan_speed
    icon: mdi:fan-alert
    label: Indiv.
    conditions:
      - entity: vacuum.roborock_s7_2
        attribute: fan_speed
        value: custom
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: '[[entity_id]]'
        fan_speed: custom
  - icon: mdi:fan
    conditions:
      - entity: vacuum.roborock_s7_2
        attribute: fan_speed
        value_not: 'off'
      - entity: vacuum.roborock_s7_2
        attribute: fan_speed
        value_not: quiet
      - entity: vacuum.roborock_s7_2
        attribute: fan_speed
        value_not: balanced
      - entity: vacuum.roborock_s7_2
        attribute: fan_speed
        value_not: turbo
      - entity: vacuum.roborock_s7_2
        attribute: fan_speed
        value_not: max
      - entity: vacuum.roborock_s7_2
        attribute: fan_speed
        value_not: custom
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_s7_2
        fan_speed: 'off'
  - type: menu
    menu_id: water_box_mode
    icon_id: water_box_mode
    available_values_attribute: options
    value_translation_keys:
      'off': Aus
      mild: Sanft
      moderate: Mittel
      intense: Intensiv
      custom: Indiv.
    icon: mdi:water
    icon_mapping:
      'off': mdi:water-remove
      mild: mdi:water-minus
      moderate: mdi:water
      intense: mdi:water-plus
      custom: mdi:water-sync
    tap_action:
      action: call-service
      service: select.select_option
      service_data:
        option: '[[value]]'
        entity_id: '[[entity_id]]'
    entity: select.roborock_s7_mop_intensity
  - type: menu
    menu_id: mop_mode
    icon_id: mop_mode
    available_values_attribute: options
    value_translation_keys:
      deep: Gründlich
      deep+: Gründlich+
      custom: Indiv.
    icon: mdi:water
    icon_mapping:
      standard: mdi:standard-definition
      deep: mdi:high-definition
      deep_plus: mdi:ultra-high-definition
      custom: mdi:fit-to-screen-outline
    tap_action:
      action: call-service
      service: select.select_option
      service_data:
        option: '[[value]]'
        entity_id: '[[entity_id]]'
    entity: select.roborock_s7_mop_mode
  - menu_id: map_mode
    icon: mdi:home-switch
    label: Sascha
    conditions:
      - entity: vacuum.roborock_s7_2
        value_not: cleaning
      - entity: vacuum.roborock_s7_2
        value_not: error
      - entity: vacuum.roborock_s7_2
        value_not: returning
    tooltip: Map wechseln
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: '[[entity_id]]'
        command: load_multi_map
        params: 0
  - menu_id: map_mode
    icon: mdi:home-switch
    label: Mama
    conditions:
      - entity: vacuum.roborock_s7_2
        value_not: cleaning
      - entity: vacuum.roborock_s7_2
        value_not: error
      - entity: vacuum.roborock_s7_2
        value_not: returning
    tooltip: Map wechseln
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: '[[entity_id]]'
        command: load_multi_map
        params: 2
  - menu_id: map_mode
    icon: mdi:home-switch
    label: Papa
    conditions:
      - entity: vacuum.roborock_s7_2
        value_not: cleaning
      - entity: vacuum.roborock_s7_2
        value_not: error
      - entity: vacuum.roborock_s7_2
        value_not: returning
    tooltip: Map wechseln
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: '[[entity_id]]'
        command: load_multi_map
        params: 3

additional_presets:
  - entity: vacuum.roborock_s7_2
    vacuum_platform: humbertogontijo/homeassistant-roborock
    map_source: *map_source
    calibration_source:
      camera: true
    preset_name: Papa
    map_locked: true
    conditions:
      - entity: sensor.roborock_s7_current_map_selected
        value: papa
    map_modes:
      - name: Räume Papa
        template: vacuum_clean_segment
        predefined_selections:
          - id: '16'
            icon:
              name: mdi:broom
              x: 25875
              'y': 24850
            label:
              text: Room 16
              x: 25875
              'y': 24850
              offset_y: 35
            outline:
              - - 24200
                - 22700
              - - 27550
                - 22700
              - - 27550
                - 27000
              - - 24200
                - 27000
          - id: '17'
            icon:
              name: mdi:broom
              x: 22825
              'y': 26325
            label:
              text: Room 17
              x: 22825
              'y': 26325
              offset_y: 35
            outline:
              - - 21500
                - 25650
              - - 24150
                - 25650
              - - 24150
                - 27000
              - - 21500
                - 27000
          - id: '18'
            icon:
              name: mdi:broom
              x: 23275
              'y': 24550
            label:
              text: Room 18
              x: 23275
              'y': 24550
              offset_y: 35
            outline:
              - - 22550
                - 23500
              - - 24000
                - 23500
              - - 24000
                - 25600
              - - 22550
                - 25600
          - id: '19'
            icon:
              name: mdi:broom
              x: 20225
              'y': 24125
            label:
              text: Room 19
              x: 20225
              'y': 24125
              offset_y: 35
            outline:
              - - 18250
                - 21250
              - - 22200
                - 21250
              - - 22200
                - 27000
              - - 18250
                - 27000
          - id: '21'
            icon:
              name: mdi:broom
              x: 17025
              'y': 24750
            label:
              text: Room 21
              x: 17025
              'y': 24750
              offset_y: 35
            outline:
              - - 15850
                - 22550
              - - 18200
                - 22550
              - - 18200
                - 26950
              - - 15850
                - 26950
      - template: vacuum_clean_zone
      - template: vacuum_goto
      - template: vacuum_follow_path
    icons: *icons
    tiles: *tiles
```


</details>

Explanation:

I have added a second preset for a second map (using `additional_presets` section). To automatically display data for every floor I have added conditions to both default and additional presets. I have also used [anchors and aliases](https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd) to minimize code duplication.
