### DISCUSSION TITLE
Problem with going to clean a room

### DISCUSSION THREAD

**Discussion by Maggus85** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#646] [Q&A] [answered]
Hi
I'm started using this integration. When I select zone to clean everything is working fine.

But when I select room, vacum is going from a dock and 10 second later is says "clean room completed" and it back to dock
I'm using below configuration. Did someone have simmilar problem?

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.s7_max_ultra_map
calibration_source:
  camera: true
entity: vacuum.s7_max_ultra
vacuum_platform: humbertogontijo/homeassistant-roborock
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_clean_segment
    predefined_selections:
      - id: '1'
        icon:
          name: mdi:broom
          x: 29100
          'y': 19875
        label:
          text: Salon
          x: 29100
          'y': 19875
          offset_y: 35
        outline:
          - - 27350
            - 17150
          - - 30850
            - 17150
          - - 30850
            - 22600
          - - 27350
            - 22600
      - id: '2'
        icon:
          name: mdi:broom
          x: 23475
          'y': 21075
        label:
          text: Kuchnia
          x: 23475
          'y': 21075
          offset_y: 35
        outline:
          - - 21950
            - 20100
          - - 25000
            - 20100
          - - 25000
            - 22050
          - - 21950
            - 22050
      - id: '3'
        icon:
          name: mdi:broom
          x: 26100
          'y': 23350
        label:
          text: Korytarz
          x: 26100
          'y': 23350
          offset_y: 35
        outline:
          - - 24900
            - 20150
          - - 27300
            - 20150
          - - 27300
            - 26550
          - - 24900
            - 26550
      - id: '4'
        icon:
          name: mdi:broom
          x: 28625
          'y': 24125
        label:
          text: Biuro
          x: 28625
          'y': 24125
          offset_y: 35
        outline:
          - - 26700
            - 22850
          - - 30550
            - 22850
          - - 30550
            - 25400
          - - 26700
            - 25400
      - id: '5'
        icon:
          name: mdi:broom
          x: 23475
          'y': 24225
        label:
          text: Łazienka
          x: 23475
          'y': 24225
          offset_y: 35
        outline:
          - - 21750
            - 23100
          - - 25200
            - 23100
          - - 25200
            - 25350
          - - 21750
            - 25350
      - id: '6'
        icon:
          name: mdi:broom
          x: 23175
          'y': 27050
        label:
          text: Sypialnia
          x: 23175
          'y': 27050
          offset_y: 35
        outline:
          - - 21300
            - 25400
          - - 25050
            - 25400
          - - 25050
            - 28700
          - - 21300
            - 28700
      - id: '7'
        icon:
          name: mdi:broom
          x: 28175
          'y': 27175
        label:
          text: Pokój dziecka
          x: 28175
          'y': 27175
          offset_y: 35
        outline:
          - - 26550
            - 25600
          - - 29800
            - 25600
          - - 29800
            - 28750
          - - 26550
            - 28750
```
