### DISCUSSION TITLE
When using Outline the Vacuum is starting an stopping after 10sec

### DISCUSSION THREAD

**Discussion by birgalive** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#651] [General]
Hei

Traing to use rooms and predefined_selections. The cleaner starts and moves away from the dock. but before moving to the are, its stopping and returning to the dock. 

i guess i am doing somthing wrong... this is a S5

```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.svigermor
vacuum_platform: default
//language: nb-NO
map_source:
  camera: camera.xiaomi_cloud_map_extractor
  crop:
    top: 100
    bottom: 100
calibration_source:
  camera: true
map_locked: true
two_finger_pan: false
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_zone_predefined
  - template: vacuum_clean_segment
    predefined_selections:
      - id: '1'
        outline:
          - - 16503
            - 21079
          - - 16441
            - 16857
          - - 12892
            - 16796
          - - 12831
            - 14471
          - - 20174
            - 14471
          - - 20113
            - 17592
          - - 17665
            - 17653
          - - 17543
            - 21079
          - - 16503
            - 21141
        label:
          text: Soverom
          x: 16380
          'y': 16368
        icon:
          name: mdi:bed
          x: 16380
          'y': 16368
      - id: '2'
        outline:
          - - 12709
            - 22365
          - - 20235
            - 22426
          - - 20235
            - 21385
          - - 12770
            - 21324
          - - 12709
            - 22365
        label: null
        icon:
          name: mdi:bed
          x: 16380
          'y': 16368
      - id: 3
        outline:
          - - 17604
            - 24751
          - - 17604
            - 22732
          - - 20664
            - 22732
          - - 20603
            - 24751
          - - 17726
            - 24751
        icon:
          name: mdi:bed
          x: 16380
          'y': 16368
      - id: 3
        outline:
          - - 15340
            - 26036
          - - 20297
            - 26097
          - - 20235
            - 24935
          - - 15462
            - 24751
          - - 15340
            - 25975
        label: null
        icon:
          name: mdi:bed
          x: 16380
          'y': 16368
      - id: 4
        outline:
          - - 16809
            - 31237
          - - 16441
            - 30809
          - - 16931
            - 30748
          - - 16992
            - 26709
          - - 18338
            - 26709
          - - 18338
            - 26097
          - - 19256
            - 26036
          - - 20174
            - 27076
          - - 20113
            - 29952
          - - 20052
            - 30626
          - - 19685
            - 31176
          - - 16809
            - 31299
        label: null
        icon:
          name: mdi:bed
          x: 16380
          'y': 16368
      - id: 5
        outline:
          - - 20786
            - 25363
          - - 21337
            - 25363
          - - 21337
            - 24751
          - - 20786
            - 24690
          - - 20786
            - 22732
          - - 23540
            - 22671
          - - 23540
            - 23160
          - - 25987
            - 23099
          - - 25926
            - 25853
          - - 24825
            - 25975
          - - 24764
            - 29463
          - - 20358
            - 29585
          - - 20235
            - 26954
          - - 19256
            - 25975
          - - 20297
            - 25424
          - - 20786
            - 25363
        label: null
        icon:
          name: mdi:bed
          x: 16380
          'y': 16368
      - id: 6
        outline:
          - - 12647
            - 18754
          - - 7263
            - 18754
          - - 7201
            - 23466
          - - 7813
            - 23527
          - - 10873
            - 23650
          - - 10934
            - 23527
          - - 12036
            - 23527
          - - 12097
            - 22487
          - - 12525
            - 22303
          - - 12647
            - 18754
        label: null
        icon:
          name: mdi:bed
          x: 16380
          'y': 16368
      - id: 7
        outline:
          - - 10506
            - 18632
          - - 10628
            - 14532
          - - 7263
            - 14593
          - - 7079
            - 18020
          - - 8915
            - 18020
          - - 8915
            - 18693
          - - 10506
            - 18632
        label: null
        icon:
          name: mdi:bed
          x: 16380
          'y': 16368
  - template: vacuum_clean_zone
tiles:
  - tile_id: status
    entity: vacuum.svigermor
    label: Status
    attribute: status
    icon: mdi:robot-vacuum
    translations:
      starting: Starting
      charger disconnected: Charger disconnected
      idle: Idle
      remote control active: Remote control active
      cleaning: Cleaning
      returning home: Returning home
      manual mode: Manual mode
      charging: Charging
      charging problem: Charging problem
      paused: Paused
      spot cleaning: Spot cleaning
      error: Error
      shutting down: Shutting down
      updating: Updating
      docking: Docking
      going to target: Going to target
      zoned cleaning: Zoned cleaning
      segment cleaning: Segment cleaning
      emptying the bin: Emptying the bin
      charging complete: Charging complete
      device offline: Device offline
  - tile_id: battery_level
    entity: vacuum.svigermor
    label: Battery
    attribute: battery_level
    icon: mdi:battery-charging-100
    unit: '%'
  - tile_id: fan_speed
    entity: vacuum.svigermor
    label: Fan speed
    attribute: fan_speed
    icon: mdi:fan
    translations:
      silent: Silent
      standard: Standard
      medium: Medium
      turbo: Turbo
      auto: Auto
      gentle: Gentle
  - tile_id: sensor_dirty_left
    label: Sensors left
    unit: h
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: true
      service_data:
        command: reset_consumable
        params: sensor_dirty_time
        entity_id: vacuum.svigermor
    entity: sensor.svigermor_sensor_dirty_left
    icon: mdi:eye-outline
    precision: 0
    translations: {}
  - tile_id: filter_left
    label: Filter left
    unit: h
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: true
      service_data:
        command: reset_consumable
        params: filter_work_time
        entity_id: vacuum.svigermor
    entity: sensor.svigermor_filter_left
    icon: mdi:air-filter
    precision: 0
    translations: {}
  - tile_id: main_brush_left
    label: Main brush left
    unit: h
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: true
      service_data:
        command: reset_consumable
        params: main_brush_work_time
        entity_id: vacuum.svigermor
    entity: sensor.svigermor_main_brush_left
    icon: mdi:brush
    precision: 0
    translations: {}
  - tile_id: side_brush_left
    label: Side brush left
    unit: h
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: true
      service_data:
        command: reset_consumable
        params: side_brush_work_time
        entity_id: vacuum.svigermor
    entity: sensor.svigermor_side_brush_left
    icon: mdi:brush
    precision: 0
    translations: {}
icons:
  - icon: mdi:play
    conditions:
      - entity: vacuum.svigermor
        value_not: cleaning
      - entity: vacuum.svigermor
        value_not: error
      - entity: vacuum.svigermor
        value_not: returning
    tooltip: Start
    tap_action:
      action: call-service
      service: vacuum.start
      service_data:
        entity_id: vacuum.svigermor
  - icon: mdi:pause
    conditions:
      - entity: vacuum.svigermor
        value_not: docked
      - entity: vacuum.svigermor
        value_not: idle
      - entity: vacuum.svigermor
        value_not: error
      - entity: vacuum.svigermor
        value_not: paused
    tooltip: Pause
    tap_action:
      action: call-service
      service: vacuum.pause
      service_data:
        entity_id: vacuum.svigermor
  - icon: mdi:stop
    conditions:
      - entity: vacuum.svigermor
        value_not: docked
      - entity: vacuum.svigermor
        value_not: idle
      - entity: vacuum.svigermor
        value_not: error
      - entity: vacuum.svigermor
        value_not: paused
    tooltip: Stop
    tap_action:
      action: call-service
      service: vacuum.stop
      service_data:
        entity_id: vacuum.svigermor
  - icon: mdi:home-map-marker
    conditions:
      - entity: vacuum.svigermor
        value_not: docked
      - entity: vacuum.svigermor
        value_not: returning
    tooltip: Return to base
    tap_action:
      action: call-service
      service: vacuum.return_to_base
      service_data:
        entity_id: vacuum.svigermor
  - icon: mdi:target-variant
    conditions:
      - entity: vacuum.svigermor
        value_not: docked
      - entity: vacuum.svigermor
        value_not: error
      - entity: vacuum.svigermor
        value_not: cleaning
      - entity: vacuum.svigermor
        value_not: returning
    tooltip: Clean spot
    tap_action:
      action: call-service
      service: vacuum.clean_spot
      service_data:
        entity_id: vacuum.svigermor
  - icon: mdi:map-marker
    tooltip: Locate
    tap_action:
      action: call-service
      service: vacuum.locate
      service_data:
        entity_id: vacuum.svigermor
  - icon: mdi:fan-remove
    conditions:
      - entity: vacuum.svigermor
        attribute: fan_speed
        value: Silent
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.svigermor
        fan_speed: Standard
  - icon: mdi:fan-speed-1
    conditions:
      - entity: vacuum.svigermor
        attribute: fan_speed
        value: Standard
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.svigermor
        fan_speed: Medium
  - icon: mdi:fan-speed-2
    conditions:
      - entity: vacuum.svigermor
        attribute: fan_speed
        value: Medium
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.svigermor
        fan_speed: Turbo
  - icon: mdi:fan-speed-3
    conditions:
      - entity: vacuum.svigermor
        attribute: fan_speed
        value: Turbo
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.svigermor
        fan_speed: Gentle
  - icon: mdi:waves
    conditions:
      - entity: vacuum.svigermor
        attribute: fan_speed
        value: Gentle
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.svigermor
        fan_speed: Auto
  - icon: mdi:fan-auto
    conditions:
      - entity: vacuum.svigermor
        attribute: fan_speed
        value: Auto
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.svigermor
        fan_speed: Silent
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.svigermor
        attribute: fan_speed
        value_not: Silent
      - entity: vacuum.svigermor
        attribute: fan_speed
        value_not: Standard
      - entity: vacuum.svigermor
        attribute: fan_speed
        value_not: Medium
      - entity: vacuum.svigermor
        attribute: fan_speed
        value_not: Turbo
      - entity: vacuum.svigermor
        attribute: fan_speed
        value_not: Gentle
      - entity: vacuum.svigermor
        attribute: fan_speed
        value_not: Auto
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.svigermor
        fan_speed: Silent
```

**Comment by birgalive** [comment]


**Reply by PiotrMachowski** [reply]
1. Have you used "Generate room config" button and then adjusted the config? You have to keep original room IDs.
2. You have unnecessarily clicked "Generate static config" button, use this config instead:
```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.svigermor
vacuum_platform: default
map_source:
  camera: camera.xiaomi_cloud_map_extractor
  crop:
    top: 100
    bottom: 100
calibration_source:
  camera: true
map_locked: true
two_finger_pan: false
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_zone_predefined
  - template: vacuum_clean_segment
    predefined_selections:
      - id: '1'
        outline:
          - - 16503
            - 21079
          - - 16441
            - 16857
          - - 12892
            - 16796
          - - 12831
            - 14471
          - - 20174
            - 14471
          - - 20113
            - 17592
          - - 17665
            - 17653
          - - 17543
            - 21079
          - - 16503
            - 21141
        label:
          text: Soverom
          x: 16380
          'y': 16368
        icon:
          name: mdi:bed
          x: 16380
          'y': 16368
      - id: '2'
        outline:
          - - 12709
            - 22365
          - - 20235
            - 22426
          - - 20235
            - 21385
          - - 12770
            - 21324
          - - 12709
            - 22365
        label: null
        icon:
          name: mdi:bed
          x: 16380
          'y': 16368
      - id: 3
        outline:
          - - 17604
            - 24751
          - - 17604
            - 22732
          - - 20664
            - 22732
          - - 20603
            - 24751
          - - 17726
            - 24751
        icon:
          name: mdi:bed
          x: 16380
          'y': 16368
      - id: 3
        outline:
          - - 15340
            - 26036
          - - 20297
            - 26097
          - - 20235
            - 24935
          - - 15462
            - 24751
          - - 15340
            - 25975
        label: null
        icon:
          name: mdi:bed
          x: 16380
          'y': 16368
      - id: 4
        outline:
          - - 16809
            - 31237
          - - 16441
            - 30809
          - - 16931
            - 30748
          - - 16992
            - 26709
          - - 18338
            - 26709
          - - 18338
            - 26097
          - - 19256
            - 26036
          - - 20174
            - 27076
          - - 20113
            - 29952
          - - 20052
            - 30626
          - - 19685
            - 31176
          - - 16809
            - 31299
        label: null
        icon:
          name: mdi:bed
          x: 16380
          'y': 16368
      - id: 5
        outline:
          - - 20786
            - 25363
          - - 21337
            - 25363
          - - 21337
            - 24751
          - - 20786
            - 24690
          - - 20786
            - 22732
          - - 23540
            - 22671
          - - 23540
            - 23160
          - - 25987
            - 23099
          - - 25926
            - 25853
          - - 24825
            - 25975
          - - 24764
            - 29463
          - - 20358
            - 29585
          - - 20235
            - 26954
          - - 19256
            - 25975
          - - 20297
            - 25424
          - - 20786
            - 25363
        label: null
        icon:
          name: mdi:bed
          x: 16380
          'y': 16368
      - id: 6
        outline:
          - - 12647
            - 18754
          - - 7263
            - 18754
          - - 7201
            - 23466
          - - 7813
            - 23527
          - - 10873
            - 23650
          - - 10934
            - 23527
          - - 12036
            - 23527
          - - 12097
            - 22487
          - - 12525
            - 22303
          - - 12647
            - 18754
        label: null
        icon:
          name: mdi:bed
          x: 16380
          'y': 16368
      - id: 7
        outline:
          - - 10506
            - 18632
          - - 10628
            - 14532
          - - 7263
            - 14593
          - - 7079
            - 18020
          - - 8915
            - 18020
          - - 8915
            - 18693
          - - 10506
            - 18632
        label: null
        icon:
          name: mdi:bed
          x: 16380
          'y': 16368
  - template: vacuum_clean_zone      
```
