### DISCUSSION TITLE
Room cleaning not working Xiaomi Miija 1C / dreame_mc1808

### DISCUSSION THREAD

**Discussion by KapriQ** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#654] [Q&A]
Hello guys, please i am coming here for a help from experienced users. I am trying to integrate ROOM / ZONE cleaning into my dashboard card.

I have following config, which works except room / zone cleaning. It shows the message “SUCCESS” but the cleaning doesn’t start.

Can you please help me how to debug this issue, due to i am a new at HA. Thanks,

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.dreame_mc1808_14a2_robot_cleaner_2
vacuum_platform: default
title: brenda v2
map_locked: true
two_finger_pan: true
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_clean_segment
    max_selections: 1
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: xiaomi_miot.call_action
      service_data:
        entity_id: '[[entity_id]]'
        siid: 18
        aiid: 1
        params:
          - piid: 1
            value: 19
          - piid: 21
            value: '{"selects":[[[[selection_unwrapped]],[[repeats]],3,3,1]]}'
        force_params: true
    predefined_selections:
      - id: '1'
        icon:
          name: mdi:broom
          x: 1925
          'y': 3425
        label:
          text: Detská
          x: 1925
          'y': 3425
          offset_y: 35
        outline:
          - - 650
            - 1800
          - - 3200
            - 1800
          - - 3200
            - 5050
          - - 650
            - 5050
      - id: '2'
        icon:
          name: mdi:broom
          x: 4750
          'y': 3275
        label:
          text: Spálňa
          x: 4750
          'y': 3275
          offset_y: 35
        outline:
          - - 3400
            - 250
          - - 6100
            - 250
          - - 6100
            - 6300
          - - 3400
            - 6300
      - id: '3'
        icon:
          name: mdi:broom
          x: 1925
          'y': 275
        label:
          text: Chodba
          x: 1925
          'y': 275
          offset_y: 35
        outline:
          - - 500
            - -1200
          - - 3350
            - -1200
          - - 3350
            - 1750
          - - 500
            - 1750
      - id: '4'
        icon:
          name: mdi:broom
          x: 2550
          'y': -1975
        label:
          text: Kúpeľňa
          x: 2550
          'y': -1975
          offset_y: 35
        outline:
          - - 1800
            - -2700
          - - 3300
            - -2700
          - - 3300
            - -1250
          - - 1800
            - -1250
      - id: '5'
        icon:
          name: mdi:broom
          x: -1150
          'y': 1000
        label:
          text: Obývačka
          x: -1150
          'y': 1000
          offset_y: 35
        outline:
          - - -2750
            - -2850
          - - 450
            - -2850
          - - 450
            - 4850
          - - -2750
            - 4850
```

**Comment by PiotrMachowski** [comment]
Have you changed room IDs after generating the config?

**Comment by KapriQ** [comment]
Sorry, maybe i just don't clearly undesrstand what are you asking exactly for. 

What i did:
1. ADD CARD -> Custom Xiaomi Vaccum card
2. entity (my vacuum cleaner) , platfom default, camera, tick MAP LOCKED, TICK TWO FINGER PAN, 
3. Then "Generate rooms config" . It shows "Config set..." .. This is config generated:
```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.dreame_mc1808_14a2_robot_cleaner_2
vacuum_platform: default
map_locked: true
two_finger_pan: true
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_clean_segment
    predefined_selections:
      - id: '1'
        icon:
          name: mdi:broom
          x: 1925
          'y': 3425
        label:
          text: Detská
          x: 1925
          'y': 3425
          offset_y: 35
        outline:
          - - 650
            - 1800
          - - 3200
            - 1800
          - - 3200
            - 5050
          - - 650
            - 5050
      - id: '2'
        icon:
          name: mdi:broom
          x: 4750
          'y': 3275
        label:
          text: Spálňa
          x: 4750
          'y': 3275
          offset_y: 35
        outline:
          - - 3400
            - 250
          - - 6100
            - 250
          - - 6100
            - 6300
          - - 3400
            - 6300
      - id: '3'
        icon:
          name: mdi:broom
          x: 1925
          'y': 275
        label:
          text: Chodba
          x: 1925
          'y': 275
          offset_y: 35
        outline:
          - - 500
            - -1200
          - - 3350
            - -1200
          - - 3350
            - 1750
          - - 500
            - 1750
      - id: '4'
        icon:
          name: mdi:broom
          x: 2550
          'y': -1975
        label:
          text: Kúpeľňa
          x: 2550
          'y': -1975
          offset_y: 35
        outline:
          - - 1800
            - -2700
          - - 3300
            - -2700
          - - 3300
            - -1250
          - - 1800
            - -1250
      - id: '5'
        icon:
          name: mdi:broom
          x: -1150
          'y': 1000
        label:
          text: Obývačka
          x: -1150
          'y': 1000
          offset_y: 35
        outline:
          - - -2750
            - -2850
          - - 450
            - -2850
          - - 450
            - 4850
          - - -2750
            - 4850
`


5. Then opened the YAML UI editor, and pasted this code above predefined selections: inside generated config, 
`
- template: vacuum_clean_segment
    max_selections: 1
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: xiaomi_miot.call_action
      service_data:
        entity_id: vacuum.dreame_mc1808_14a2_robot_cleaner_2
        siid: 18
        aiid: 1
        params:
          - piid: 1
            value: 19
          - piid: 21
            value: '{"selects":[[[[selection_unwrapped]],[[repeats]],3,3,1]]}'
        force_params: true
```
6. After this, if i click on ROOMS -> Select room -> It shows "SUCCESS" msg, but nothing happened.

Thank youu <3

**Reply by PiotrMachowski** [reply]
Have you changed values I marked with `# HERE`?
```yaml
  - template: vacuum_clean_segment
    predefined_selections:
      - id: '1'  # HERE
        icon:
          name: mdi:broom
          x: 1925
          'y': 3425
        label:
          text: Detská
          x: 1925
          'y': 3425
          offset_y: 35
        outline:
          - - 650
            - 1800
          - - 3200
            - 1800
          - - 3200
            - 5050
          - - 650
            - 5050
      - id: '2'  # HERE
        icon:
          name: mdi:broom
```

**Comment by KapriQ** [comment]
Nope, i didn't changed that.  there should be different ID? Where can i get that ?

**Reply by PiotrMachowski** [reply]
Please respond in the same thread. They should be in attributes of Map Extractor camera. If they are the same you might have to just try values from 1-32 range

**Reply by KapriQ** [reply]
I have tried to change your "# HERE" marked ID, from 1 - 32, but none of these works. If i understand you correctly,

Isn't something wrong in these code?

```yaml
- template: vacuum_clean_segment
    max_selections: 1
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: xiaomi_miot.call_action
      service_data:
        entity_id: vacuum.dreame_mc1808_14a2_robot_cleaner_2
        siid: 18
        aiid: 1
        params:
          - piid: 1
            value: 19
          - piid: 21
            value: '{"selects":[[[[selection_unwrapped]],[[repeats]],3,3,1]]}'
        force_params: true
```
