### DISCUSSION TITLE
Creating an icon with trash location

### DISCUSSION THREAD

**Discussion by ThimTT** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#660] [Q&A] [answered]
Hi,

I am trying to create an extra icon next to the play icon that navigates the vac to the trash location in my house - please help.
I took out the irrelevant sections.

```
icons:
  - icon: mdi:play
    conditions:
      - entity: vacuum.roborock_s7
        value_not: cleaning
      - entity: vacuum.roborock_s7
        value_not: error
      - entity: vacuum.roborock_s7
        value_not: returning
    tooltip: Start
    tap_action:
      action: call-service
      service: vacuum.start
      service_data:
        entity_id: vacuum.roborock_s7
  - icon: mdi:trash-can
    conditions:
      - entity: vacuum.roborock_s7
        value_not: cleaning
      - entity: vacuum.roborock_s7
        value_not: error
      - entity: vacuum.roborock_s7
        value_not: returning
    tooltip: Entleerung
    tap_action:
      action: call_service
      service: roborock.vacuum_goto
      service_data:
        x_coord: 27590
        y_coord: 25828
        entity_id: vacuum.roborock_s7
```
