### DISCUSSION TITLE
Actual map

### DISCUSSION THREAD

**Discussion by JacekJI** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#661] [Q&A]
Hello, 

I have few question about vacum map card.

1. Have floors- i use multifloors code from repository. It's working, but how show actual map on vacum map card? And actual position?

My code for multi maps:
```yaml
append_icons: true
icons:
  - icon: mdi:numeric-0-box
    tooltip: Map 0
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.roborock_s7_2
        command: load_multi_map
        params: 0
  - icon: mdi:numeric-1-box
    tooltip: Map 1
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.roborock_s7_2
        command: load_multi_map
        params: 1
map_locked: true
```
2. How zoom vacum map card prernamently on the dashboard?
3. Mopings setting-  how add mop options?
4. Refreshing podition of roboot- how more often refreshing position of robot?  On ha it's stuck...maybe because of automatisation for updateing map?

Thanks in advance!
