### DISCUSSION TITLE
Map custom colors

### DISCUSSION THREAD

**Discussion by hebval** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#666] [General]
Hi, thank you so much for your work !
I would love to have the same color pattern as you have here : 

https://raw.githubusercontent.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/master/images/map_no_rooms_custom_colors.png

Could you please give me the colors code please ? :)
Thanks!

**Comment by PiotrMachowski** [comment]
You have to do it in Map Extractor.
```yaml
colors:
    color_map_inside: [50, 50, 50]
    color_map_outside: [0, 0, 0, 128]
    color_map_wall: [255,255,255]
```
Config depends on the vacuum model, you probably also have to set room colors to `[50, 50, 50]`
