### DISCUSSION TITLE
Select rooms of Multiple Floors in one map

### DISCUSSION THREAD

**Discussion by Jack77777777** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#670] [Q&A] [answered]
Hi,

I have two floors. The selected one is always shown in my live map. Is there a way, with conditions for example, to show the rooms of the actual selected maps.
Floor one:
![image](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/64719909/f0e8dee7-eace-4044-9831-7439c474648d)

Floor two:
![image](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/64719909/462bbba3-b411-4ed5-8300-6a9ae799cbe4)

I would like to have this two in the live map, depending on which one is selected:
![image](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/64719909/e1c67d41-1196-407e-b8c9-b6583a76ad71)

**Comment by PiotrMachowski** [comment]
Are additional presets just images of a map? Do you have a way to check which map is currently active on a live map?

**Reply by Jack77777777** [reply]
Are additional presets just images of a map?
The additional presets are entities, no static images.

Do you have a way to check which map is currently active on a live map?
Yes, the live map shows always the actual selected map.

I am using https://github.com/Tasshack/dreame-vacuum to get the entities from my Dreame L20 Ultra:

**Reply by PiotrMachowski** [reply]
Can you post your config?

> Yes, the live map shows always the actual selected map.

Yeah, but is there an entity that tells the name/number of currently selected floor?

**Reply by Jack77777777** [reply]
Yes, there is an select entity:
![image](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/64719909/ccd72d8c-037f-4e7d-acbe-e31ebff9d896)

This is my config. My goal is to have the additional presets in the live map.
```
type: custom:xiaomi-vacuum-map-card
preset_name: Live
map_source:
  camera: camera.dreame_map
calibration_source:
  camera: true
entity: vacuum.dreame
language: de
vacuum_platform: Tasshack/dreame-vacuum
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_point
additional_presets:
  - preset_name: Erdgeschoss
    map_source:
      camera: camera.dreame_map_1
    calibration_source:
      camera: true
    entity: vacuum.dreame
    vacuum_platform: Tasshack/dreame-vacuum
    map_modes:
      - template: vacuum_clean_point
      - template: vacuum_clean_segment
        predefined_selections:
          - id: '1'
            icon:
              name: mdi:home-outline
              x: -1000
              'y': 3800
            label:
              text: 'Büro '
              x: -1000
              'y': 3800
              offset_y: 25
            outline:
              - - -2850
                - 2450
              - - -1250
                - 2450
              - - -1250
                - 950
              - - 750
                - 950
              - - 750
                - 5650
              - - -2850
                - 5650
          - id: '3'
            icon:
              name: mdi:home-outline
              x: 4250
              'y': 1250
            label:
              text: 'Wohnzimmer '
              x: 4250
              'y': 1250
              offset_y: 35
            outline:
              - - 1000
                - -3200
              - - 7050
                - -3200
              - - 7050
                - 5600
              - - 1000
                - 5600
          - id: '4'
            icon:
              name: mdi:home-outline
              x: 8750
              'y': 3550
            label:
              text: 'Esszimmer '
              x: 8750
              'y': 3550
              offset_y: 35
            outline:
              - - 7000
                - 2250
              - - 10500
                - 2250
              - - 10500
                - 4750
              - - 7000
                - 4750
          - id: '5'
            icon:
              name: mdi:home-outline
              x: -900
              'y': 0
            label:
              text: 'Flur '
              x: -900
              'y': 0
              offset_y: 35
            outline:
              - - -3200
                - -3000
              - - -1150
                - -3000
              - - -1150
                - -800
              - - 1050
                - -800
              - - 1050
                - 300
              - - 750
                - 300
              - - 750
                - 800
              - - -1400
                - 800
              - - -1400
                - 2400
              - - -3200
                - 2400
          - id: '7'
            icon:
              name: mdi:home-outline
              x: 10100
              'y': 750
            label:
              text: 'Küche '
              x: 10100
              'y': 750
              offset_y: 35
            outline:
              - - 6950
                - -900
              - - 10550
                - -900
              - - 10550
                - 2250
              - - 6950
                - 2250
  - preset_name: Obergeschoss
    map_source:
      camera: camera.dreame_map_2
    calibration_source:
      camera: true
    entity: vacuum.dreame
    vacuum_platform: Tasshack/dreame-vacuum
    map_modes:
      - template: vacuum_clean_point
      - template: vacuum_clean_segment
        predefined_selections:
          - id: '2'
            icon:
              name: mdi:home-outline
              x: -350
              'y': 1800
            label:
              text: Lucia
              x: -350
              'y': 1800
              offset_y: 35
            outline:
              - - -1700
                - -900
              - - 1450
                - -900
              - - 1450
                - 3850
              - - -1700
                - 3850
          - id: '3'
            icon:
              name: mdi:home-outline
              x: 3600
              'y': 1600
            label:
              text: Matteo
              x: 3600
              'y': 1600
              offset_y: 35
            outline:
              - - 1600
                - -950
              - - 4950
                - -950
              - - 4950
                - 3800
              - - 1600
                - 3800
          - id: '4'
            icon:
              name: mdi:home-outline
              x: -6600
              'y': -1850
            label:
              text: Badezimmer
              x: -6600
              'y': -1850
              offset_y: 35
            outline:
              - - -8450
                - -3650
              - - -4700
                - -3650
              - - -4700
                - -50
              - - -8450
                - -50
          - id: '7'
            icon:
              name: mdi:home-outline
              x: 2850
              'y': -2250
            label:
              text: Flur OG
              x: 2850
              'y': -2250
              offset_y: 35
            outline:
              - - -4700
                - -3600
              - - 4750
                - -3600
              - - 4750
                - -800
              - - -4700
                - -800
          - id: '9'
            icon:
              name: mdi:home-outline
              x: -5200
              'y': 2050
            label:
              text: Schlafzimmer
              x: -5200
              'y': 2050
              offset_y: 35
            outline:
              - - -8400
                - -800
              - - -2000
                - -800
              - - -2000
                - 3850
              - - -8400
                - 3850
append_icons: true
icons:
  - type: menu
    menu_id: dreame_cleaning_mode
    icon_id: dreame_cleaning_mode
    entity: select.dreame_cleaning_mode
    available_values_attribute: options
    icon_mapping:
      sweeping: mdi:broom
      mopping: mdi:cup-water
      sweeping_and_mopping: mdi:hydro-power
      mopping_after_sweeping: mdi:hydro-power
    tap_action:
      action: call-service
      service: select.select_option
      service_data:
        option: '[[value]]'
        entity_id: '[[entity_id]]'
  - type: menu
    menu_id: dreame_selected_map
    icon_id: dreame_selected_map
    entity: select.dreame_selected_map
    available_values_attribute: options
    icon_mapping:
      Erdgeschoss: phu:zones-areas-ground-floor
      Obergeschoss: phu:zones-areas-first-floor
    tap_action:
      action: call-service
      service: select.select_option
      service_data:
        option: '[[value]]'
        entity_id: '[[entity_id]]'

```

**Reply by PiotrMachowski** [reply]
Do `camera.dreame_map_1` always show the first floor and `camera.dreame_map_2` the second floor?

**Reply by Jack77777777** [reply]
Yes

**Reply by PiotrMachowski** [reply, marked as answer]
Try this config. It should automatically show a correct floor:
```yaml
type: custom:xiaomi-vacuum-map-card
language: de
preset_name: Erdgeschoss
map_source:
  camera: camera.dreame_map_1
calibration_source:
  camera: true
entity: vacuum.dreame
vacuum_platform: Tasshack/dreame-vacuum
map_modes:
  - template: vacuum_clean_point
  - template: vacuum_clean_segment
    predefined_selections:
      - id: '1'
        icon:
          name: mdi:home-outline
          x: -1000
          'y': 3800
        label:
          text: 'Büro '
          x: -1000
          'y': 3800
          offset_y: 25
        outline:
          - - -2850
            - 2450
          - - -1250
            - 2450
          - - -1250
            - 950
          - - 750
            - 950
          - - 750
            - 5650
          - - -2850
            - 5650
      - id: '3'
        icon:
          name: mdi:home-outline
          x: 4250
          'y': 1250
        label:
          text: 'Wohnzimmer '
          x: 4250
          'y': 1250
          offset_y: 35
        outline:
          - - 1000
            - -3200
          - - 7050
            - -3200
          - - 7050
            - 5600
          - - 1000
            - 5600
      - id: '4'
        icon:
          name: mdi:home-outline
          x: 8750
          'y': 3550
        label:
          text: 'Esszimmer '
          x: 8750
          'y': 3550
          offset_y: 35
        outline:
          - - 7000
            - 2250
          - - 10500
            - 2250
          - - 10500
            - 4750
          - - 7000
            - 4750
      - id: '5'
        icon:
          name: mdi:home-outline
          x: -900
          'y': 0
        label:
          text: 'Flur '
          x: -900
          'y': 0
          offset_y: 35
        outline:
          - - -3200
            - -3000
          - - -1150
            - -3000
          - - -1150
            - -800
          - - 1050
            - -800
          - - 1050
            - 300
          - - 750
            - 300
          - - 750
            - 800
          - - -1400
            - 800
          - - -1400
            - 2400
          - - -3200
            - 2400
      - id: '7'
        icon:
          name: mdi:home-outline
          x: 10100
          'y': 750
        label:
          text: 'Küche '
          x: 10100
          'y': 750
          offset_y: 35
        outline:
          - - 6950
            - -900
          - - 10550
            - -900
          - - 10550
            - 2250
          - - 6950
            - 2250
append_icons: true
icons:
  - type: menu
    menu_id: dreame_cleaning_mode
    icon_id: dreame_cleaning_mode
    entity: select.dreame_cleaning_mode
    available_values_attribute: options
    icon_mapping:
      sweeping: mdi:broom
      mopping: mdi:cup-water
      sweeping_and_mopping: mdi:hydro-power
      mopping_after_sweeping: mdi:hydro-power
    tap_action:
      action: call-service
      service: select.select_option
      service_data:
        option: '[[value]]'
        entity_id: '[[entity_id]]'
  - type: menu
    menu_id: dreame_selected_map
    icon_id: dreame_selected_map
    entity: select.dreame_selected_map
    available_values_attribute: options
    icon_mapping:
      Erdgeschoss: phu:zones-areas-ground-floor
      Obergeschoss: phu:zones-areas-first-floor
    tap_action:
      action: call-service
      service: select.select_option
      service_data:
        option: '[[value]]'
        entity_id: '[[entity_id]]'
conditions:
  - entity: select.dreame_selected_map
    value: Erdgeschoss
additional_presets:
  - preset_name: Obergeschoss
    map_source:
      camera: camera.dreame_map_2
    calibration_source:
      camera: true
    entity: vacuum.dreame
    vacuum_platform: Tasshack/dreame-vacuum
    map_modes:
      - template: vacuum_clean_point
      - template: vacuum_clean_segment
        predefined_selections:
          - id: '2'
            icon:
              name: mdi:home-outline
              x: -350
              'y': 1800
            label:
              text: Lucia
              x: -350
              'y': 1800
              offset_y: 35
            outline:
              - - -1700
                - -900
              - - 1450
                - -900
              - - 1450
                - 3850
              - - -1700
                - 3850
          - id: '3'
            icon:
              name: mdi:home-outline
              x: 3600
              'y': 1600
            label:
              text: Matteo
              x: 3600
              'y': 1600
              offset_y: 35
            outline:
              - - 1600
                - -950
              - - 4950
                - -950
              - - 4950
                - 3800
              - - 1600
                - 3800
          - id: '4'
            icon:
              name: mdi:home-outline
              x: -6600
              'y': -1850
            label:
              text: Badezimmer
              x: -6600
              'y': -1850
              offset_y: 35
            outline:
              - - -8450
                - -3650
              - - -4700
                - -3650
              - - -4700
                - -50
              - - -8450
                - -50
          - id: '7'
            icon:
              name: mdi:home-outline
              x: 2850
              'y': -2250
            label:
              text: Flur OG
              x: 2850
              'y': -2250
              offset_y: 35
            outline:
              - - -4700
                - -3600
              - - 4750
                - -3600
              - - 4750
                - -800
              - - -4700
                - -800
          - id: '9'
            icon:
              name: mdi:home-outline
              x: -5200
              'y': 2050
            label:
              text: Schlafzimmer
              x: -5200
              'y': 2050
              offset_y: 35
            outline:
              - - -8400
                - -800
              - - -2000
                - -800
              - - -2000
                - 3850
              - - -8400
                - 3850
    append_icons: true
    icons:
      - type: menu
        menu_id: dreame_cleaning_mode
        icon_id: dreame_cleaning_mode
        entity: select.dreame_cleaning_mode
        available_values_attribute: options
        icon_mapping:
          sweeping: mdi:broom
          mopping: mdi:cup-water
          sweeping_and_mopping: mdi:hydro-power
          mopping_after_sweeping: mdi:hydro-power
        tap_action:
          action: call-service
          service: select.select_option
          service_data:
            option: '[[value]]'
            entity_id: '[[entity_id]]'
      - type: menu
        menu_id: dreame_selected_map
        icon_id: dreame_selected_map
        entity: select.dreame_selected_map
        available_values_attribute: options
        icon_mapping:
          Erdgeschoss: phu:zones-areas-ground-floor
          Obergeschoss: phu:zones-areas-first-floor
        tap_action:
          action: call-service
          service: select.select_option
          service_data:
            option: '[[value]]'
            entity_id: '[[entity_id]]'
    conditions:
      - entity: select.dreame_selected_map
        value: Obergeschoss
```
