### DISCUSSION TITLE
Only two options - no option to clean room

### DISCUSSION THREAD

**Discussion by udouble** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#672] [Q&A] [answered]
HI,
I only have two options for starting my cleaner (Roborock s7 MaxV). Zone clean-up and Pin&Go. See screenshot.
The other options that are in your video don;t show up (Room,...). 
Probably I made a mistake when trying to reinstall. I remember seeing the options:-).
As you notice: new to HA. 
Herman - Belgium
![Scherm­afbeelding 2023-10-29 om 18 19 28](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/15670896/c6014e87-d507-4bbd-8a7e-67360a978cdb)

**Comment by PiotrMachowski** [comment]
You have to configure them. Wait for a full map to be visible, open card editor and click "generate rooms config" button

**Comment by udouble** [comment]
Thanks for replying. Very kind!
(Where is the card editor? I'll buy you a coffee.)

--
Herman Eerdekens
Steenovenstraat 5
2580 Putte

**Reply by PiotrMachowski** [reply]
You have to open dashboard in "Edit" mode and the appropriate button will appear below the card.

**Comment by udouble** [comment]
You mean this?

[image: Scherm­afbeelding 2023-10-30 om 11.11.43.png]


If I click that, I get the message (for two seconds and in Dutch): "Open
configuration-editor..." Then the message disappears.

Could you send me an example?


--
Herman Eerdekens
Steenovenstraat 5
2580 Putte

**Reply by PiotrMachowski** [reply]
Images do not work when replaying via email

**Reply by udouble** [reply]
![Scherm­afbeelding 2023-10-30 om 11 11 43](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/15670896/20bade83-94dc-48dc-9f34-83e71125eace)

**Reply by PiotrMachowski** [reply]
Yes, this button. The card's config should be automatically adjusted afterwards

**Reply by udouble** [reply]
Sorry, that didn't work.
I was able to adjust the parameters in the /config/dwains-dashboard/configs/cards/areas/keuken/custom:xiaomi-vacuum-map-card.yaml
Is there a way to have the Rooms-button as default? Instead of Zone Cleanup?

**Reply by PiotrMachowski** [reply, marked as answer]
> I was able to adjust the parameters in the /config/dwains-dashboard/configs/cards/areas/keuken/custom:xiaomi-vacuum-map-card.yaml

Does dwains dashboard use yaml config instead of UI editor?

> Is there a way to have the Rooms-button as default? Instead of Zone Cleanup?

Just change the order of entries in `map_modes` sections

**Comment by udouble** [comment]
Sorry, I have to come back regarding my first question: only two options in the roborock map: pin&go and zone cleanup. See screenshot:

![Scherm­afbeelding 2023-10-31 om 17 38 01](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/15670896/ef491e95-3252-475a-a1c1-75b7eb5bf997)

Using custom Roborock integration created by [@humbertogontijo](https://github.com/humbertogontijo).
Strange: in Dwains Dashboard I see three options (including Rooms), in a lovelace dashboard I can't get the three options. 

Cannot find the code I have to adjust. Could you tell me what yaml-document this section is in, and how it should look? Thanks.

**Reply by PiotrMachowski** [reply]
This list is populated by `map_modes` section of config. Can you post your config used in Dwains Dashboard?

**Comment by udouble** [comment]
The issue is not within Dwains D. It's within another dashboard I created.
This is the code:

```
calibration_source:
  camera: true
col_span: '2'
col_span_lg: '3'
col_span_xl: '4'
entity: vacuum.roborock_s7_maxv
map_locked: true
map_modes:
- template: vacuum_goto
- template: vacuum_clean_zone
- predefined_selections:
  - icon:
      name: mdi:broom
      x: 27500
      y: 29050
    id: '16'
    label:
      offset_y: 35
      text: Berging
      x: 27500
      y: 29050
    outline:
    - - 26600
      - 27550
    - - 28400
      - 27550
    - - 28400
      - 30550
    - - 26600
      - 30550
  - icon:
      name: mdi:broom
      x: 21450
      y: 27075
    id: '17'
    label:
      offset_y: 35
      text: Waskot
      x: 21450
      y: 27075
    outline:
    - - 20500
      - 24850
    - - 22400
      - 24850
    - - 22400
      - 29300
    - - 20500
      - 29300
  - icon:
      name: mdi:broom
      x: 30825
      y: 27800
    id: '18'
    label:
      offset_y: 35
      text: Eetkamer
      x: 30825
      y: 27800
    outline:
    - - 28600
      - 24500
    - - 33050
      - 24500
    - - 33050
      - 30500
    - - 28600
      - 30500
  - icon:
      name: mdi:broom
      x: 33600
      y: 28625
    id: '19'
    label:
      offset_y: 35
      text: TV-kamer
      x: 35000
      y: 28625
    outline:
    - - 33000
      - 25500
    - - 37400
      - 25500
    - - 37400
      - 34000
    - - 33000
      - 34000
  - icon:
      name: mdi:broom
      x: 24475
      y: 25625
    id: '21'
    label:
      offset_y: 35
      text: Keuken
      x: 26000
      y: 27500
    outline:
    - - 22400
      - 24500
    - - 28600
      - 24500
    - - 28600
      - 30000
    - - 22400
      - 30000
  template: vacuum_clean_segment
map_source:
  camera: camera.roborock_s7_maxv_map
position: top
row_span: '1'
row_span_lg: '1'
row_span_xl: '1'
title: Robotstofzuiger
type: custom:xiaomi-vacuum-map-card
vacuum_platform: humbertogontijo/homeassistant-roborock
```

**Reply by PiotrMachowski** [reply]
You can just copy this config to the card in another dashboard

**Comment by udouble** [comment]
I know what I did wrong: I didn't click the room-configuration link. 
Now I did it three times, so now I have three room-options:-). How do I delete the extra two? Sorry.

**Comment by udouble** [comment]
Hi Piotr. I'm making progress: i was able to adjust some things and to correct the unneccessary double click.
I also understand I'd better adress these issues within the HA Community. Thank you for your help.

**Comment by udouble** [comment]
I understand your card is stored as json and converted to yaml for editing. Json does not support comments? Only YAML mode supports comments.

**Reply by PiotrMachowski** [reply]
Yes, internally UI-editable dashboards are stored in JSON which doesn't support comments.

**Comment by pablosuarez999** [comment]
Hello,
I'm having a similar issue, I have tried the custom Roborock integration and the Xiaomi Miio, but It doesn't appear the "GET ROOMS CONFIG". I have seen some tutorials and with the Roborock integration it appears without doing anything extra, and with the Xiaomi miio integration, after getting the TOKEN API.
My configuration.yaml: 

```
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
      - rooms
      - room_numbers
```
I added the last two lines, and nothing happens, I have the two options like udouble, and It's imposible to get the "Selection: []" and the three blue options. I have reinstalled the xiaomi vacuum map card, the roborock integration, and also installed the xiaomi miio integration, reinstalled more than one time the xiaomi vacuum map card and nothing happens. I tried to search about this but it looks like I'm the only person with this issue hahaha. Any idea about this?
Regards.
