### DISCUSSION TITLE
Disabling/Hiding Map

### DISCUSSION THREAD

**Discussion by Jack77777777** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#673] [Q&A] [answered]
I would like to use this card in the sidebar view of home assistant (https://www.home-assistant.io/dashboards/sidebar/).
On the left, wide column the map with icons and on the right column the tiles.

I know could also use entities card or similar but i like the view and configuration options of tiles from this card.

My question is, is there a way to hide map and icons and just display tiles ?

**Comment by PiotrMachowski** [comment, marked as answer]
This should do the trick:
```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.xiaomi_vacuum
vacuum_platform: default
map_modes: []
icons: []
card_mod:
  style: |
    .map-wrapper {
      display: none;
    }
```

**Reply by linceaerian** [reply]
EDIT: Ignore that... Did not see it was a custom module to install via HACS

Hello, Does this work too when using dreame vacuum setting ? I tried:

```
type: custom:xiaomi-vacuum-map-card
entity: vacuum.dreamebot_l10s_ultra
map_source:
  camera: camera.dreamebot_l10s_ultra_map
calibration_source:
  camera: true
vacuum_platform: Tasshack/dreame-vacuum
card_mod:
  style: |
    .map-wrapper {
      display: none;
    }
map_modes: []
icons: []
tiles:
  - tile_id: status
    entity: vacuum.dreamebot_l10s_ultra
    label: Status
    attribute: status
    icon: mdi:robot-vacuum
```

But the map still shows to my disarray :)
(I would think that it does considering the css class is the same...)
