### DISCUSSION TITLE
Follow path Roborock S8

### DISCUSSION THREAD

**Discussion by poudenes** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#679] [General]
Hi All,

I added the script to make it possible to do follow path option.
Added my vacuum entity right in the script:

```
vacuum_follow_path:
  alias: "Roborock follow path"
  mode: single
  fields:
    path:
      name: Path
    entity_id:
      name: vacuum.roborock_s8

  sequence:
    - repeat:
        count: "{{ path | length }}"
        sequence:
          - choose:
              - conditions: "{{ mode == 'individual' }}"
                sequence:
                  - service: "{{ service }}"
                    data:
                      entity_id: "{{ entity_id }}"
                      x_coord: "{{ path[repeat.index-1][0] }}"
                      y_coord: "{{ path[repeat.index-1][1] }}"
                      
          - choose:
              - conditions: "{{ mode == 'send_command' }}"
                sequence:
                  - service: "{{ service }}"
                    data:
                      entity_id: "{{ entity_id }}"
                      command: app_goto_target
                      params: "{{ path[repeat.index-1] }}"

          - wait_template: "{{ is_state(entity_id, 'cleaning') }}"
            timeout: 00:00:30
            continue_on_timeout: false

          - delay: 00:00:01

          - wait_template: "{{ is_state(entity_id, 'idle') or is_state(entity_id, 'paused') }}"
            timeout: 00:05:00
            continue_on_timeout: false
```
And below (first part of the card):

```
      - type: custom:xiaomi-vacuum-map-card
        map_source:
          camera: camera.roborock_s8_map
          crop:
            top: 230
            right: 210
            left: 180
            bottom: 140
        calibration_source:
          camera: true
        entity: vacuum.roborock_s8
        vacuum_platform: humbertogontijo/homeassistant-roborock
        tiles: []
        icons: []
        map_modes:
          - template: vacuum_follow_path
          - name: Zone cleanup
            icon: mdi:select-drag
            run_immediately: false
            coordinates_rounding: true
            coordinates_to_meters_divider: 1000
            selection_type: MANUAL_RECTANGLE
            max_selections: 5
            repeats_type: EXTERNAL
            max_repeats: 3
            service_call_schema:
              service: roborock.vacuum_clean_zone
              service_data:
                zone: '[[selection]]'
                repeats: '[[repeats]]'
                entity_id: '[[entity_id]]'
            predefined_selections: []
            variables: {}
```

When I create a path the S8 goes to the first point and stop. 
It say: Going to target then target reached.

Is there something I do wrong?
