### DISCUSSION TITLE
Room over other room (segment)

### DISCUSSION THREAD

**Discussion by facutopa** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#680] [Q&A] [answered]
Hi guys, I have the next problem:
![image](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/7283431/1488cd18-f538-4471-aed1-4a6bde183c05)
I can't select the bathroom because the living room is over it.
This is my config:
```
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.dreame_mc1808_8280_robot_cleaner
vacuum_platform: al-one/hass-xiaomi-miot
map_locked: true
append_tiles: false
tiles:
  - label: Bateria
    entity: sensor.dreame_mc1808_8280_battery_level
    icon: mdi:battery-high
  - label: Status
    entity: sensor.dreame_mc1808_8280_charging_state
    icon: mdi:robot-vacuum
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_segment
    max_selections: 1
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: xiaomi_miot.call_action
      service_data:
        entity_id: '[[entity_id]]'
        siid: 18
        aiid: 1
        params:
          - piid: 1
            value: 18
          - piid: 21
            value: '{"selects":[[[[selection_unwrapped]],[[repeats]],3,3,1]]}'
        force_params: true
    predefined_selections:
      - id: '1'
        icon:
          name: mdi:shower
          x: -725
          'y': 2250
        label:
          text: Baño
          x: -725
          'y': 2250
          offset_y: 35
        outline:
          - - -1250
            - 1750
          - - -200
            - 1750
          - - -200
            - 2750
          - - -1250
            - 2750
      - id: '2'
        icon:
          name: mdi:bed-double-outline
          x: -850
          'y': -125
        label:
          text: Bedroom
          x: -850
          'y': -125
          offset_y: 35
        outline:
          - - -2200
            - -1800
          - - 500
            - -1800
          - - 500
            - 1550
          - - -2200
            - 1550
      - id: '3'
        icon:
          name: mdi:sofa-outline
          x: -925
          'y': 4400
        label:
          text: Living
          x: -925
          'y': 4400
          offset_y: 35
        outline:
          - - -2250
            - 1600
          - - 400
            - 1600
          - - 400
            - 6350
          - - -2250
            - 6350
      - id: '4'
        icon:
          name: mdi:fridge-outline
          x: -3000
          'y': 3800
        label:
          text: Cocina
          x: -3000
          'y': 3800
          offset_y: 35
        outline:
          - - -3700
            - 3000
          - - -2300
            - 3000
          - - -2300
            - 4600
          - - -3700
            - 4600
      - id: '6'
        icon:
          name: mdi:table-chair
          x: -2900
          'y': 5475
        label:
          text: Comedor
          x: -2900
          'y': 5475
          offset_y: 35
        outline:
          - - -4350
            - 4650
          - - -1450
            - 4650
          - - -1450
            - 6300
          - - -4350
            - 6300
title: Aspiradora

```
What can I do?
