### DISCUSSION TITLE
Second Vacuum help

### DISCUSSION THREAD

**Discussion by cesarthedj** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#682] [Q&A]
hi, i have two vacuum, and i have problem with configuration
First at configuration.yaml 
I have to do like this
```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret vacuum_host_s5
    token: !secret vacuum_token_s5
    username: !secret vacuum_username_s5
    password: !secret vacuum_password_s5
    name: "Roborock"
    draw: ["all"]
    attributes:
      - calibration_points
      - room_numbers
  - platform: xiaomi_cloud_map_extractor
    host: !secret vacuum_host_Roidmi
    token: !secret vacuum_token_Roidmi
    username: !secret vacuum_username_Roidmi
    password: !secret vacuum_password_Roidmi
    name: "Roidmi"
    draw: ["all"]
    attributes:
      - calibration_points
      - room_numbers
```

      but in host token username and password i have to do _(name of vacuum)?
      in name of vacuum i have to add name from xiaomi app?
      
      Second , in secret.yaml file how i have to do it?
      
      #Roidmi 
xiaomi_vacuum_host: ""
xiaomi_vacuum_token: ""
xiaomi_cloud_username: ""
xiaomi_cloud_password: ""

#Roborock
xiaomi_vacuum_host: ""
xiaomi_vacuum_token: ""
xiaomi_cloud_username: ""
xiaomi_cloud_password: "" 

?

Thanks for help

**Comment by PiotrMachowski** [comment]
https://www.home-assistant.io/docs/configuration/secrets

**Comment by cesarthedj** [comment]
ok now its working but i have another issue,
![368067472_734087525240735_8494368385814072270_n](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/46246640/dbddc4ec-9da6-4347-9d8b-fff52291a3a7)

Second vacuum works normally, i can send it to point, or clean zones(Robrock s50)
but in Roidmi eve plus i cant do anything

**Reply by PiotrMachowski** [reply]
Which integration do you use to control this vacuum?

**Comment by cesarthedj** [comment]
Xioami miot auto , cuz xiaomi miio doenst work with roidmi, there is no pattern for this vacuum

**Reply by PiotrMachowski** [reply]
https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/618

**Reply by cesarthedj** [reply]
```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.roidmi
calibration_source:
  camera: true
entity: vacuum.roidmi_v60_d19d_robot_cleaner
vacuum_platform: al-one/hass-xiaomi-miot
map_modes:
  - template: vacuum_clean_zone
    max_selections: 3
    repeats_type: NONE
    service_call_schema:
      service: xiaomi_miot.call_action
      evaluate_data_as_template: true
      service_data:
        entity_id: '[[entity_id]]'
        siid: 14
        aiid: 1
        params:
          - 2
          - >-
            {% set s_s = [[selection]] %}{"MapId":[[map_id]],"ExtraAreas":[{%for
            s in s_s %}{"name":"[[name]]", "id":[[id]], "tag":"[[tag]]",
            "vertexs":[[{{s[0]}},{{s[1]}}],[{{s[2]}},{{s[1]}}],[{{s[2]}},{{s[3]}}],[{{s[0]}},{{s[3]}}]],"active":"normal","mode":"area"}{%
            if not loop.last%},{% endif%}{%endfor%}]}
    variables:
      map_id: 123456
      name: 划区
      id: 300
      tag: 4
  - template: vacuum_clean_segment
    max_selections: 6
    repeats_type: NONE
    max_repeats: 2
    service_call_schema: null
    service: xiaomi_miot.call_action
    service_data: null
    entity_id: '[[entity_id]]'
    siid: 14
    aiid: 1
    params: null
    predefined_selections:
      - id: '1'
        icon:
          name: mdi:broom
          x: -5200.000075623393
          'y': 799.9997083097696
        label:
          text: Łazienka
          x: -5200.000075623393
          'y': 799.9997083097696
          offset_y: 35
        outline:
          - - -6025.000087916851
            - 274.9997004866601
          - - -4375.000063329935
            - 274.9997004866601
          - - -4375.000063329935
            - 1324.9997161328793
          - - -6025.000087916851
            - 1324.9997161328793
      - id: '2'
        icon:
          name: mdi:broom
          x: 1450.0000234693289
          'y': 524.9997042119503
        label:
          text: Salon
          x: 1450.0000234693289
          'y': 524.9997042119503
          offset_y: 35
        outline:
          - - -575.0000067055225
            - -1325.000323355198
          - - 3475.0000536441803
            - -1325.000323355198
          - - 3475.0000536441803
            - 2374.9997317790985
          - - -575.0000067055225
            - 2374.9997317790985
      - id: '3'
        icon:
          name: mdi:broom
          x: -3175.0000454485416
          'y': -675.0003136694431
        label:
          text: Przedpokój
          x: -3175.0000454485416
          'y': -675.0003136694431
          offset_y: 35
        outline:
          - - -5225.000075995922
            - -1475.000325590372
          - - -1125.0000149011612
            - -1475.000325590372
          - - -1125.0000149011612
            - 124.99969825148592
          - - -5225.000075995922
            - 124.99969825148592
      - id: '4'
        icon:
          name: mdi:broom
          x: 1250.0000204890966
          'y': 2749.999737367034
        label:
          text: Dywan
          x: 1250.0000204890966
          'y': 2749.999737367034
          offset_y: 35
        outline:
          - - 125.00000372529033
            - 1974.999725818634
          - - 2375.000037252903
            - 1974.999725818634
          - - 2375.000037252903
            - 3524.9997489154334
          - - 125.00000372529033
            - 3524.9997489154334
      - id: '5'
        icon:
          name: mdi:broom
          x: -4450.000064447522
          'y': 2674.999736249447
        label:
          text: Kuchnia
          x: -4450.000064447522
          'y': 2674.999736249447
          offset_y: 35
        outline:
          - - -5625.000081956387
            - 1724.9997220933437
          - - -3275.0000469386578
            - 1724.9997220933437
          - - -3275.0000469386578
            - 3624.9997504055495
          - - -5625.000081956387
            - 3624.9997504055495
      - id: '6'
        icon:
          name: mdi:broom
          x: -2525.000035762787
          'y': 2174.9997287988663
        label:
          text: Jadalnia
          x: -2525.000035762787
          'y': 2174.9997287988663
          offset_y: 35
        outline:
          - - -4425.000064074993
            - 74.99969750642786
          - - -625.0000074505806
            - 74.99969750642786
          - - -625.0000074505806
            - 4274.999760091305
          - - -4425.000064074993
            - 4274.999760091305
title: Roidmi
map_locked: true
```

And now when i do zone clean up its working

but when i try to do rooms error comes up 
"nie udalo sie wywolac uslugi xiaomi_miot/call_action required key not provided data aiid

could you please help me?
