### DISCUSSION TITLE
cant separate rooms in map

### DISCUSSION THREAD

**Discussion by pablosuarez999** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#690] [Q&A]
Hello,
I'm having a issue where I can't get the rooms in the Vacuum Map Card, I have tried the custom Roborock integration and the Xiaomi Miio, but It doesn't appear the "GET ROOMS CONFIG". I have seen some tutorials and with the Roborock integration it appears without doing anything extra, and with the Xiaomi miio integration, after getting the TOKEN API and doing the configuration correctly.

My configuration.yaml:
```
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
      - rooms
      - room_numbers
```

I added the last two lines, and nothing happens, I have the two options like udouble, and It's imposible to get the "Selection: []" and the three blue options. I have reinstalled the xiaomi vacuum map card, the roborock integration, and also installed the xiaomi miio integration, reinstalled more than one time the xiaomi vacuum map card and nothing happens. I tried to search about this but it looks like I'm the only person with this issue hahaha. Any idea about this?
Regards.
