### DISCUSSION TITLE
YAML configuration card losing the syntax

### DISCUSSION THREAD

**Discussion by elad1994** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#718] [General]
When copy the configuration from your video into my card, all the syntax get lost.
For example - 
```yaml
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_zone_predefined
    predefined_selections:
      - zones:
          - 21485
          - 28767
          - 24236
          - 32131
        label:
          text: Bedroom
          x: 22932
          'y': 30339
          offset_y: 35
```

**Comment by PiotrMachowski** [comment]
What is lost?

**Reply by elad1994** [reply]
This is your config - 
```yaml
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_zone_predefined
    predefined_selections:
      - zones: [[ 21485, 28767, 24236, 32131 ], [ 23217, 27379, 24216, 28737 ]]
        label:
          text: "Bedroom"
          x: 22932
          y: 30339
          offset_y: 35
        icon:
          name: "mdi:bed"
          x: 22932
          y: 30339
```

       
After copy your code and copy it in my card, this is the output - 
```yaml
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_zone_predefined
    predefined_selections:
      - zones:
          - 21485
          - 28767
          - 24236
          - 32131
        label:
          text: Bedroom
          x: 22932
          'y': 30339
          offset_y: 35
```
