### DISCUSSION TITLE
Make Roborock vacuum first then mop?

### DISCUSSION THREAD

**Discussion by ARK9975** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#721] [Q&A]
I am using [this roborock integration](https://github.com/humbertogontijo/homeassistant-roborock) and my card is working great. One of the things I really want to figure out though is if I can select rooms from the map as I do normally but then have the robot do a vacuum pass, return to the dock, then mop. I can kind of do this with routines in the roborock app but I want to be able to just select my rooms and press a button. Is there a way to do this?

**Comment by PiotrMachowski** [comment]
Sure, you can create a script in HA that will do it and start it from the card with an appropriate room passed as a field.

**Reply by ARK9975** [reply]
I know I can make a button for each room or a group of rooms but I want to select the rooms from the card then press a button. Only one button.

**Reply by PiotrMachowski** [reply]
Yes, yes. The card can do it. It can call a script with a list of rooms passed in the parameter. I can show you how to configure it in the card, but you have to create a script by yourself (I will adjust it if needed).

**Reply by ARK9975** [reply]
I made this script which is what I want to vacuum to do but with hard coded room ids. Could you tell me how I can pass the rooms through?

```yml
vacuum_upstairs_mop_vac:
  alias: Vacuum - Upstairs Mop & Vac
  sequence:
    - service: vacuum.send_command
      target:
        entity_id: vacuum.roborock_q_revo
      data:
        command: set_custom_mode
        params: 104
    - service: vacuum.send_command
      target:
        entity_id: vacuum.roborock_q_revo
      data:
        command: set_water_box_custom_mode
        params: 200
    - service: vacuum.send_command
      target:
        entity_id: vacuum.roborock_q_revo
      data:
        command: app_segment_clean
        params:
          - segments:
              - 18
              - 19
              - 16
              - 23
              - 24
              - 25
              - 17
              - 22
              - 20
              - 21
    - service: vacuum.send_command
      target:
        entity_id: vacuum.roborock_q_revo
      data:
        command: set_custom_mode
        params: 105
    - service: vacuum.send_command
      target:
        entity_id: vacuum.roborock_q_revo
      data:
        command: set_water_box_custom_mode
        params: 203
    - service: vacuum.send_command
      target:
        entity_id: vacuum.roborock_q_revo
      data:
        command: app_segment_clean
        params:
          - segments:
              - 18
              - 16
              - 17
              - 21
  mode: single
  icon: mdi:robot-vacuum
```
