### DISCUSSION TITLE
Cleaning spcifc zone

### DISCUSSION THREAD

**Discussion by elad1994** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#726] [Q&A] [answered]
Hi, 
no matter what, i cant clean specfic zone, when starting the cleaning after choose the zone, the vacuum start to clean all the area. 
this is my yml - 
```yaml
map_modes:
  - template: vacuum_clean_zone_predefined
    predefined_selections:
      - zones:
          - - 0
            - -1
            - 5
            - 3
        label:
          text: Bedroom
          x: 2
          'y': 2
          offset_y: 35
        icon:
          name: mdi:bed
          x: 2.2932
          'y': 3.0339
      - zones:
          - - 2
            - -5
            - 4
            - -2
        label:
          text: Kitchen
          x: 2.5
          'y': 0
          offset_y: 35
        icon:
          name: mdi:pot-mix
          x: 2.5
          'y': 0
```
