### DISCUSSION TITLE
Add custom icons

### DISCUSSION THREAD

**Discussion by Frassensh** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#729] [General]
Hey! So i have one layout of my home and one for the vacuum. i really want to combine these into one. Ive come halfway, all i need now is a way to add icons and tap actions to them in the vacuum map card. Is there any way i can do this?

![image](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/85584014/fca45bdb-622a-43e1-a314-e8c9263ff4e7)
this layer is a picture elements card that controls a lot of things like speakers and lights, like this:

```
type: picture-elements
image: /local/floorplan/off.png
elements:
  - type: icon
    icon: mdi:volume-minus
    tap_action:
      action: call-service
      service: script.volume_down
    style:
      top: 5%
      left: 75%
      opacity: 100%
```

my other layout, the vacuum map, looks like this:

![image](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/85584014/9f88e6b4-bfe1-448c-a7f1-12c8350d7db2)

its the vacuuum map card with css styling to get the background, so thats fine. But i want to be able to move all the icons over to the vacuum card. Is there any way I can do this?
