### DISCUSSION TITLE
Segment/room cleaning using Valetudo (and Roborock S5)

### DISCUSSION THREAD

**Discussion by NoBagels** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#732] [Q&A] [answered]
I'm running a Roborock S5 w/ the latest Valetudo, have installed Valetudo vacuum camera and followed the instructions (including "Card configuration") in https://github.com/sca075/valetudo_vacuum_camera/blob/main/docs/install.md.

It works fine selecting f. ex. zone cleanup using the card, and the Camera entity reports 6 rooms with correct names, but when selecting "Generate room config" nothing happens. 

(It also works fine sending the robot to different rooms/segments using the guide here: https://valetudo.cloud/pages/integrations/home-assistant-integration.html)

What step(s)/config have I missed?

BR
NoB

**Comment by PiotrMachowski** [comment]
Can you show card's yaml config?

**Comment by NoBagels** [comment]
Sure:
```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.valetudo_strictfaithfuloryx
vacuum_platform: Hypfer/Valetudo
map_source:
  camera: camera.valetudo_s5_strictfaithfuloryx_camera
map_locked: false
two_finger_pan: true
calibration_source:
  camera: true
internal_variables:
  topic: valetudo/StrictFaithfulOryx
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
```
