### DISCUSSION TITLE
Mi Robot Vaccum Mop (MC1808) - Failed to call service xiaomi_miot/call_action. required key not provided @ data['aiid']

### DISCUSSION THREAD

**Discussion by amit-nz** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#734] [Q&A] [answered]
Hello everyone

Anyway, I use the the hass-xiaomi-miot integration I can tell the robot to clean, stop, adjust fan speed etc but no area / zone control. (I can't use the built-in Home Assistant Xiaomi as it doesn't support my specific robot.)

So I installed `xiaomi-vacuum-map-card` and pulled the map, then generated the rooms config (all this works perfectly).

But, when I try to send the robot out to clean a specific room, I get

`Failed to call service xiaomi_miot/call_action. required key not provided @ data['aiid']` 

If I attempt to clean a specific zone, I get

`Failed to call service xiaomi_miot/call_action. required key not provided @ data['siid']` 

Would appreciate some guidance on what I'm doing wrong.

I have fully removed my robot (it was using cloud integration) and I have added my robot using "local" integration (IP address and Token) into the hass-xiaomi-miot integration.

`2024-05-24 14:36:26.710 DEBUG (MainThread) [custom_components.xiaomi_miot.vacuum] RoboVac(dreame.vacuum.mc1808): Got new state: {'vacuum.fault': 0, 'vacuum.status': 6, 'audio.volume': 53, 'audio.voice_packets': 'EN', 'clean.work_mode': 6, 'clean.area': '', 'clean.timer': '', 'clean.mode': 0, 'clean.water_box': 0, 'clean.total_clean_time': 39795, 'clean.total_clean_times': 866, 'clean.total_clean_area': 38047, 'clean.clean_log_start_time': 1627609784, 'clean.button_led': 0, 'clean.task_done': 1, 'brush_left_time-28-1': 37, 'brush_life_level-28-2': 18, 'filter.filter_life_level': 0, 'filter.filter_left_time': 0, 'brush_cleaner.brush_left_time': 137, 'brush_cleaner.brush_life_level': 45, 'battery_level': 99, 'battery.charging_state': 1, 'state_updater': 'lan'}`

My config for the card:

```
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.dreame_mc1808_dea3_robot_cleaner
vacuum_platform: al-one/hass-xiaomi-miot
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_segment
    predefined_selections:
      - id: '1'
        icon:
          name: mdi:broom
          x: 2550
          'y': 6825
        label:
          text: Bedroom
          x: 2550
          'y': 6825
          offset_y: 35
        outline:
          - - 500
            - 4900
          - - 4600
            - 4900
          - - 4600
            - 8750
          - - 500
            - 8750
      - id: '2'
        icon:
          name: mdi:broom
          x: 3050
          'y': 2900
        label:
          text: Laundry
          x: 3050
          'y': 2900
          offset_y: 35
        outline:
          - - 1850
            - 2450
          - - 4250
            - 2450
          - - 4250
            - 3350
          - - 1850
            - 3350
      - id: '3'
        icon:
          name: mdi:broom
          x: 1225
          'y': 3625
        label:
          text: Hallway
          x: 1225
          'y': 3625
          offset_y: 35
        outline:
          - - 650
            - 2400
          - - 1800
            - 2400
          - - 1800
            - 4850
          - - 650
            - 4850
      - id: '4'
        icon:
          name: mdi:broom
          x: 2750
          'y': -2375
        label:
          text: Office
          x: 2750
          'y': -2375
          offset_y: 35
        outline:
          - - 700
            - -4350
          - - 4800
            - -4350
          - - 4800
            - -400
          - - 700
            - -400
      - id: '5'
        icon:
          name: mdi:broom
          x: 3775
          'y': -5425
        label:
          text: Ensuite
          x: 3775
          'y': -5425
          offset_y: 35
        outline:
          - - 2850
            - -6300
          - - 4700
            - -6300
          - - 4700
            - -4550
          - - 2850
            - -4550
      - id: '6'
        icon:
          name: mdi:broom
          x: 1600
          'y': -5575
        label:
          text: Closet
          x: 1600
          'y': -5575
          offset_y: 35
        outline:
          - - 900
            - -6300
          - - 2300
            - -6300
          - - 2300
            - -4850
          - - 900
            - -4850
      - id: '7'
        icon:
          name: mdi:broom
          x: -2625
          'y': 5050
        label:
          text: Kitchen
          x: -2625
          'y': 5050
          offset_y: 35
        outline:
          - - -3600
            - 4000
          - - -1650
            - 4000
          - - -1650
            - 6100
          - - -3600
            - 6100
      - id: '8'
        icon:
          name: mdi:broom
          x: -2350
          'y': -9150
        label:
          text: Office 2
          x: -2350
          'y': -9150
          offset_y: 35
        outline:
          - - -4200
            - -10450
          - - -500
            - -10450
          - - -500
            - -7850
          - - -4200
            - -7850
      - id: '9'
        icon:
          name: mdi:broom
          x: 2975
          'y': -8625
        label:
          text: Bedroom 2
          x: 2975
          'y': -8625
          offset_y: 35
        outline:
          - - 800
            - -10900
          - - 5150
            - -10900
          - - 5150
            - -6350
          - - 800
            - -6350
      - id: '10'
        icon:
          name: mdi:broom
          x: -1825
          'y': 1650
        label:
          text: Dining
          x: -1825
          'y': 1650
          offset_y: 35
        outline:
          - - -4300
            - -1950
          - - 650
            - -1950
          - - 650
            - 5250
          - - -4300
            - 5250
      - id: '11'
        icon:
          name: mdi:broom
          x: 2600
          'y': 1100
        label:
          text: Bathroom
          x: 2600
          'y': 1100
          offset_y: 35
        outline:
          - - 800
            - -150
          - - 4400
            - -150
          - - 4400
            - 2350
          - - 800
            - 2350
      - id: '13'
        icon:
          name: mdi:broom
          x: -1750
          'y': -4900
        label:
          text: Living
          x: -1750
          'y': -4900
          offset_y: 35
        outline:
          - - -4250
            - -7800
          - - 750
            - -7800
          - - 750
            - -2000
          - - -4250
            - -2000
      - id: '16'
        icon:
          name: mdi:broom
          x: -1775
          'y': 275
        label:
          text: Dining Table
          x: -1775
          'y': 275
          offset_y: 35
        outline:
          - - -2950
            - -850
          - - -600
            - -850
          - - -600
            - 1400
          - - -2950
            - 1400
      - id: '18'
        icon:
          name: mdi:broom
          x: -1775
          'y': -4500
        label:
          text: Couch
          x: -1775
          'y': -4500
          offset_y: 35
        outline:
          - - -2950
            - -6350
          - - -600
            - -6350
          - - -600
            - -2650
          - - -2950
            - -2650

```

And the map extractor:
```

camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - charger
      - cleaned_rooms
      - goto
      - ignored_obstacles
      - map_name
      - no_go_areas
      - no_mopping_areas
      - vacuum_position
      - zones
      - calibration_points
      - rooms
    map_transformation:
      scale: 1
      rotate: 270
```
