### DISCUSSION TITLE
Multiple maps for 1 vacuum

### DISCUSSION THREAD

**Discussion by rungziggy** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#735] [Q&A] [answered]
Hi, sorry I'm a total noob to all this. I'm use 1 vacuum and move it between upstairs and downstairs. I cannot get the 2 maps to show up like many of you do. What am I doing wrong? Here's my config.

```yaml
type: custom:xiaomi-vacuum-map-card
preset_name: Upstairs
map_source:
  camera: camera.sucky_map_1
calibration_source:
  camera: true
entity: vacuum.sucky
vacuum_platform: default
map_locked: true
tiles: []
map_modes:
  - template: vacuum_clean_segment
    predefined_selections:
      - id: '1'
        icon:
          name: mdi:toilet
          x: -4650
          'y': 3750
        label:
          text: Bathroom
          x: -4650
          'y': 3750
          offset_y: 35
        outline:
          - - -6050
            - 2250
          - - -3250
            - 2250
          - - -3250
            - 4750
          - - -6050
            - 4750
      - id: '2'
        icon:
          name: mdi:bed-king-outline
          x: -5200
          'y': 200
        label:
          text: Primary Bedroom
          x: -5200
          'y': 200
          offset_y: 35
        outline:
          - - -7750
            - -3200
          - - -4100
            - -3200
          - - -4100
            - 2300
          - - -7750
            - 2300
      - id: '3'
        icon:
          name: mdi:sofa-outline
          x: -2150
          'y': -400
        label:
          text: Living Room
          x: -2150
          'y': -400
          offset_y: 35
        outline:
          - - -4850
            - -3150
          - - 500
            - -3150
          - - 500
            - 2250
          - - -4850
            - 2250
  - template: vacuum_clean_zone
  - template: vacuum_goto
additional_preset:
  - preset_name: Downstairs
    map_source:
      camera: camera.sucky_map_2
    calibration_source:
      camera: true
    entity: vacuum.sucky
    vacuum_platform: default
    map_locked: true
    tiles: []
    map_modes: null
  - template: vacuum_clean_segment
    predefined_selections:
      - id: '1'
        icon:
          name: mdi:bed-king-outline
          x: 4950
          'y': -2050
        label:
          text: Morgan Bedroom
          x: 4950
          'y': -2050
          offset_y: 35
        outline:
          - - 3200
            - -4200
          - - 6400
            - -4200
          - - 6400
            - -900
          - - 3200
            - -900
      - id: '2'
        icon:
          name: mdi:toilet
          x: 1450
          'y': -2950
        label:
          text: Bathroom
          x: 1450
          'y': -2950
          offset_y: 35
        outline:
          - - 350
            - -4250
          - - 2600
            - -4250
          - - 2600
            - -1600
          - - 350
            - -1600
      - id: '3'
        icon:
          name: mdi:chef-hat
          x: 3000
          'y': 2550
        label:
          text: Kitchen
          x: 3000
          'y': 2550
          offset_y: 35
        outline:
          - - 1650
            - 1700
          - - 4300
            - 1700
          - - 4300
            - 3250
          - - 1650
            - 3250
      - id: '4'
        icon:
          name: mdi:foot-print
          x: 3400
          'y': -500
        label:
          text: Corridor
          x: 3400
          'y': -500
          offset_y: 35
        outline:
          - - 1900
            - -1650
          - - 4850
            - -1650
          - - 4850
            - 850
          - - 1900
            - 850
      - id: '5'
        icon:
          name: mdi:room-service-outline
          x: -600
          'y': 2850
        label:
          text: Dining Hall
          x: -600
          'y': 2850
          offset_y: 35
        outline:
          - - -2900
            - 1900
          - - 1750
            - 1900
          - - 1750
            - 3650
          - - -2900
            - 3650
      - id: '6'
        icon:
          name: mdi:sofa-outline
          x: -550
          'y': -500
        label:
          text: Living Room
          x: -550
          'y': -500
          offset_y: 35
        outline:
          - - -3000
            - -4000
          - - 1900
            - -4000
          - - 1900
            - 1900
          - - -3000
            - 1900
  - template: vacuum_clean_zone
```

**Comment by PiotrMachowski** [comment]
Try this config:
```yaml
type: custom:xiaomi-vacuum-map-card
preset_name: Upstairs
map_source:
  camera: camera.sucky_map_1
calibration_source:
  camera: true
entity: vacuum.sucky
vacuum_platform: default
map_locked: true
tiles: []
map_modes:
  - template: vacuum_clean_segment
    predefined_selections:
      - id: '1'
        icon:
          name: mdi:toilet
          x: -4650
          'y': 3750
        label:
          text: Bathroom
          x: -4650
          'y': 3750
          offset_y: 35
        outline:
          - - -6050
            - 2250
          - - -3250
            - 2250
          - - -3250
            - 4750
          - - -6050
            - 4750
      - id: '2'
        icon:
          name: mdi:bed-king-outline
          x: -5200
          'y': 200
        label:
          text: Primary Bedroom
          x: -5200
          'y': 200
          offset_y: 35
        outline:
          - - -7750
            - -3200
          - - -4100
            - -3200
          - - -4100
            - 2300
          - - -7750
            - 2300
      - id: '3'
        icon:
          name: mdi:sofa-outline
          x: -2150
          'y': -400
        label:
          text: Living Room
          x: -2150
          'y': -400
          offset_y: 35
        outline:
          - - -4850
            - -3150
          - - 500
            - -3150
          - - 500
            - 2250
          - - -4850
            - 2250
  - template: vacuum_clean_zone
  - template: vacuum_goto
additional_preset:
  - preset_name: Downstairs
    map_source:
      camera: camera.sucky_map_2
    calibration_source:
      camera: true
    entity: vacuum.sucky
    vacuum_platform: default
    map_locked: true
    tiles: []
    map_modes:
      - template: vacuum_clean_segment
        predefined_selections:
          - id: '1'
            icon:
              name: mdi:bed-king-outline
              x: 4950
              'y': -2050
            label:
              text: Morgan Bedroom
              x: 4950
              'y': -2050
              offset_y: 35
            outline:
              - - 3200
                - -4200
              - - 6400
                - -4200
              - - 6400
                - -900
              - - 3200
                - -900
          - id: '2'
            icon:
              name: mdi:toilet
              x: 1450
              'y': -2950
            label:
              text: Bathroom
              x: 1450
              'y': -2950
              offset_y: 35
            outline:
              - - 350
                - -4250
              - - 2600
                - -4250
              - - 2600
                - -1600
              - - 350
                - -1600
          - id: '3'
            icon:
              name: mdi:chef-hat
              x: 3000
              'y': 2550
            label:
              text: Kitchen
              x: 3000
              'y': 2550
              offset_y: 35
            outline:
              - - 1650
                - 1700
              - - 4300
                - 1700
              - - 4300
                - 3250
              - - 1650
                - 3250
          - id: '4'
            icon:
              name: mdi:foot-print
              x: 3400
              'y': -500
            label:
              text: Corridor
              x: 3400
              'y': -500
              offset_y: 35
            outline:
              - - 1900
                - -1650
              - - 4850
                - -1650
              - - 4850
                - 850
              - - 1900
                - 850
          - id: '5'
            icon:
              name: mdi:room-service-outline
              x: -600
              'y': 2850
            label:
              text: Dining Hall
              x: -600
              'y': 2850
              offset_y: 35
            outline:
              - - -2900
                - 1900
              - - 1750
                - 1900
              - - 1750
                - 3650
              - - -2900
                - 3650
          - id: '6'
            icon:
              name: mdi:sofa-outline
              x: -550
              'y': -500
            label:
              text: Living Room
              x: -550
              'y': -500
              offset_y: 35
            outline:
              - - -3000
                - -4000
              - - 1900
                - -4000
              - - 1900
                - 1900
              - - -3000
                - 1900
      - template: vacuum_clean_zone
```

**Reply by rungziggy** [reply]
That didn't seem to work. Do I need to add the preset "live"?

**Reply by PiotrMachowski** [reply]
Wait a second... How have you made these 2 cameras?

**Reply by rungziggy** [reply]
Its created originally in the Mi app, then in HA I added the vacuum card and then I generated the room config.

**Reply by PiotrMachowski** [reply]
How have you added them to HA?

**Reply by rungziggy** [reply]
Via the Dreame Vacuum Integration. [https://github.com/Tasshack/dreame-vacuum]

**Reply by PiotrMachowski** [reply]
Ok, so what exactly is your problem?

**Comment by rungziggy** [comment]
<img width="459" alt="Screenshot 2024-05-29 at 4 56 04 PM" src="https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/170447049/6d0bbb99-7666-47f5-84f4-b4237f341841">

How do you get multiple maps for one vacuum? I thought when I have those presets in my config that I'd be able to set the current map and just move the vacuum from one floor to another like the Mi app

**Reply by PiotrMachowski** [reply]
Yes, you can do it. What happens in your current setup when you change presets?

**Reply by rungziggy** [reply]
It doesn’t give me the option to change between presets even though I call out two different ones in the config
![IMG_1100](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/170447049/0e998a17-f1b6-4814-9d54-6e44b6986c4f)

**Reply by PiotrMachowski** [reply]
Ok, I see it now. You have made a typo: `additional_preset` should be changed to `additional_presets`

**Reply by rungziggy** [reply]
That instantly gives me a error: Missing property: entity

Having 2 cards for separate floors works for now...

**Reply by PiotrMachowski** [reply, marked as answer]
Try this config:
```yaml
type: custom:xiaomi-vacuum-map-card
preset_name: Upstairs
map_source:
  camera: camera.sucky_map_1
calibration_source:
  camera: true
entity: vacuum.sucky
vacuum_platform: Tasshack/dreame-vacuum
map_locked: true
tiles: []
map_modes:
  - template: vacuum_clean_segment
    predefined_selections:
      - id: '1'
        icon:
          name: mdi:toilet
          x: -4650
          'y': 3750
        label:
          text: Bathroom
          x: -4650
          'y': 3750
          offset_y: 35
        outline:
          - - -6050
            - 2250
          - - -3250
            - 2250
          - - -3250
            - 4750
          - - -6050
            - 4750
      - id: '2'
        icon:
          name: mdi:bed-king-outline
          x: -5200
          'y': 200
        label:
          text: Primary Bedroom
          x: -5200
          'y': 200
          offset_y: 35
        outline:
          - - -7750
            - -3200
          - - -4100
            - -3200
          - - -4100
            - 2300
          - - -7750
            - 2300
      - id: '3'
        icon:
          name: mdi:sofa-outline
          x: -2150
          'y': -400
        label:
          text: Living Room
          x: -2150
          'y': -400
          offset_y: 35
        outline:
          - - -4850
            - -3150
          - - 500
            - -3150
          - - 500
            - 2250
          - - -4850
            - 2250
  - template: vacuum_clean_zone
  - template: vacuum_goto
additional_presets:
  - preset_name: Downstairs
    map_source:
      camera: camera.sucky_map_2
    calibration_source:
      camera: true
    entity: vacuum.sucky
    vacuum_platform: Tasshack/dreame-vacuum
    map_locked: true
    tiles: []
    map_modes:
      - template: vacuum_clean_segment
        predefined_selections:
          - id: '1'
            icon:
              name: mdi:bed-king-outline
              x: 4950
              'y': -2050
            label:
              text: Morgan Bedroom
              x: 4950
              'y': -2050
              offset_y: 35
            outline:
              - - 3200
                - -4200
              - - 6400
                - -4200
              - - 6400
                - -900
              - - 3200
                - -900
          - id: '2'
            icon:
              name: mdi:toilet
              x: 1450
              'y': -2950
            label:
              text: Bathroom
              x: 1450
              'y': -2950
              offset_y: 35
            outline:
              - - 350
                - -4250
              - - 2600
                - -4250
              - - 2600
                - -1600
              - - 350
                - -1600
          - id: '3'
            icon:
              name: mdi:chef-hat
              x: 3000
              'y': 2550
            label:
              text: Kitchen
              x: 3000
              'y': 2550
              offset_y: 35
            outline:
              - - 1650
                - 1700
              - - 4300
                - 1700
              - - 4300
                - 3250
              - - 1650
                - 3250
          - id: '4'
            icon:
              name: mdi:foot-print
              x: 3400
              'y': -500
            label:
              text: Corridor
              x: 3400
              'y': -500
              offset_y: 35
            outline:
              - - 1900
                - -1650
              - - 4850
                - -1650
              - - 4850
                - 850
              - - 1900
                - 850
          - id: '5'
            icon:
              name: mdi:room-service-outline
              x: -600
              'y': 2850
            label:
              text: Dining Hall
              x: -600
              'y': 2850
              offset_y: 35
            outline:
              - - -2900
                - 1900
              - - 1750
                - 1900
              - - 1750
                - 3650
              - - -2900
                - 3650
          - id: '6'
            icon:
              name: mdi:sofa-outline
              x: -550
              'y': -500
            label:
              text: Living Room
              x: -550
              'y': -500
              offset_y: 35
            outline:
              - - -3000
                - -4000
              - - 1900
                - -4000
              - - 1900
                - 1900
              - - -3000
                - 1900
      - template: vacuum_clean_zone
```
