### DISCUSSION TITLE
Dreame L20 Ultra Services how to find???

### DISCUSSION THREAD

**Discussion by pillemats** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#737] [Q&A] [answered]
Hey there,

I am searching für a list for the service command für the dreame l20 ultra.

I wand to configure the map card, but i dont have the correct service names

where i can fin these?

for example here ist my config:
i need the correct services for the tiles

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.l20_ultra_map
calibration_source:
  camera: true
entity: vacuum.l20_ultra
vacuum_platform: Tasshack/dreame-vacuum
card_mod:
  style: |
    ha-card {
     display: flex !important;
     align-items: stretch;
     flex-wrap: wrap;
     justify-content: space-evenly;
    }
    .map-wrapper {
     flex-grow: 3;
     width: 600px;
    }
    .controls-wrapper {
     flex-grow: 1;
     width: 300px;
    }
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_point
  - template: vacuum_clean_segment
    predefined_selections:
      - id: '1'
        icon:
          name: mdi:chef-hat
          x: -5600
          'y': 5050
        label:
          text: Kitchen
          x: -5600
          'y': 5050
          offset_y: 35
        outline:
          - - -6300
            - 3600
          - - -1500
            - 3600
          - - -1500
            - 6300
          - - -6300
            - 6300
      - id: '2'
        icon:
          name: mdi:foot-print
          x: -300
          'y': 4850
        label:
          text: Corridor
          x: -300
          'y': 4850
          offset_y: 35
        outline:
          - - -1500
            - 3200
          - - 1700
            - 3200
          - - 1700
            - 7450
          - - -1500
            - 7450
      - id: '3'
        icon:
          name: mdi:room-service-outline
          x: -10350
          'y': 5150
        label:
          text: Dining Hall
          x: -10350
          'y': 5150
          offset_y: 35
        outline:
          - - -16000
            - 2300
          - - -6300
            - 2300
          - - -6300
            - 7000
          - - -16000
            - 7000
      - id: '4'
        icon:
          name: mdi:monitor-shimmer
          x: 200
          'y': 1300
        label:
          text: Office
          x: 200
          'y': 1300
          offset_y: 35
        outline:
          - - -1650
            - -800
          - - 1700
            - -800
          - - 1700
            - 3200
          - - -1650
            - 3200
      - id: '5'
        icon:
          name: mdi:home-outline
          x: -4050
          'y': 1100
        label:
          text: Kinderzimmer
          x: -4050
          'y': 1100
          offset_y: 35
        outline:
          - - -6550
            - -800
          - - -1650
            - -800
          - - -1650
            - 2900
          - - -6550
            - 2900
      - id: '6'
        icon:
          name: mdi:sofa-outline
          x: -10100
          'y': -1400
        label:
          text: Living Room
          x: -10100
          'y': -1400
          offset_y: 35
        outline:
          - - -12750
            - -6300
          - - -6400
            - -6300
          - - -6400
            - 3250
          - - -12750
            - 3250
      - id: '7'
        icon:
          name: mdi:home-outline
          x: -1350
          'y': 8800
        label:
          text: Room 7
          x: -1350
          'y': 8800
          offset_y: 35
        outline:
          - - -2700
            - 7450
          - - 600
            - 7450
          - - 600
            - 11750
          - - -2700
            - 11750
  - template: vacuum_clean_segment
    predefined_selections:
      - id: '1'
        icon:
          name: mdi:chef-hat
          x: -5600
          'y': 5050
        label:
          text: Kitchen
          x: -5600
          'y': 5050
          offset_y: 35
        outline:
          - - -6300
            - 3600
          - - -1500
            - 3600
          - - -1500
            - 6400
          - - -6300
            - 6400
      - id: '2'
        icon:
          name: mdi:foot-print
          x: -300
          'y': 4850
        label:
          text: Corridor
          x: -300
          'y': 4850
          offset_y: 35
        outline:
          - - -1500
            - 3200
          - - 1750
            - 3200
          - - 1750
            - 7450
          - - -1500
            - 7450
      - id: '3'
        icon:
          name: mdi:room-service-outline
          x: -10350
          'y': 5150
        label:
          text: Dining Hall
          x: -10350
          'y': 5150
          offset_y: 35
        outline:
          - - -16000
            - 2300
          - - -6300
            - 2300
          - - -6300
            - 7100
          - - -16000
            - 7100
      - id: '4'
        icon:
          name: mdi:monitor-shimmer
          x: 200
          'y': 1300
        label:
          text: Office
          x: 200
          'y': 1300
          offset_y: 35
        outline:
          - - -1650
            - -850
          - - 1750
            - -850
          - - 1750
            - 3200
          - - -1650
            - 3200
      - id: '5'
        icon:
          name: mdi:home-outline
          x: -4050
          'y': 1100
        label:
          text: Kinderzimmer
          x: -4050
          'y': 1100
          offset_y: 35
        outline:
          - - -6550
            - -850
          - - -1650
            - -850
          - - -1650
            - 2950
          - - -6550
            - 2950
      - id: '6'
        icon:
          name: mdi:sofa-outline
          x: -10100
          'y': -1400
        label:
          text: Living Room
          x: -10100
          'y': -1400
          offset_y: 35
        outline:
          - - -12850
            - -6450
          - - -6350
            - -6450
          - - -6350
            - 3250
          - - -12850
            - 3250
      - id: '7'
        icon:
          name: mdi:home-outline
          x: -1350
          'y': 8800
        label:
          text: Room 7
          x: -1350
          'y': 8800
          offset_y: 35
        outline:
          - - -2700
            - 7450
          - - 600
            - 7450
          - - 600
            - 11800
          - - -2700
            - 11800
tiles:
  - tile_id: status
    entity: vacuum.l20_ultra
    label: Status
    attribute: status
    icon: mdi:robot-vacuum
    translations:
      starting: Starting
      charger disconnected: Charger disconnected
      idle: Idle
      remote control active: Remote control active
      cleaning: Cleaning
      returning home: Returning home
      manual mode: Manual mode
      charging: Charging
      charging problem: Charging problem
      paused: Paused
      spot cleaning: Spot cleaning
      error: Error
      shutting down: Shutting down
      updating: Updating
      docking: Docking
      going to target: Going to target
      zoned cleaning: Zoned cleaning
      segment cleaning: Segment cleaning
      emptying the bin: Emptying the bin
      charging complete: Charging complete
      device offline: Device offline
  - tile_id: battery_level
    entity: vacuum.l20_ultra
    label: Battery
    attribute: battery_level
    icon: mdi:battery-charging-100
    unit: '%'
  - tile_id: fan_speed
    entity: vacuum.l20_ultra
    label: Fan speed
    attribute: fan_speed
    icon: mdi:fan
    translations:
      silent: Silent
      standard: Standard
      medium: Medium
      turbo: Turbo
      auto: Auto
      gentle: Gentle
icons:
  - icon: mdi:play
    conditions:
      - entity: vacuum.l20_ultra
        value_not: cleaning
      - entity: vacuum.l20_ultra
        value_not: error
      - entity: vacuum.l20_ultra
        value_not: returning
    tooltip: Start
    tap_action:
      action: call-service
      service: vacuum.start
      service_data:
        entity_id: vacuum.l20_ultra
  - icon: mdi:pause
    conditions:
      - entity: vacuum.l20_ultra
        value_not: docked
      - entity: vacuum.l20_ultra
        value_not: idle
      - entity: vacuum.l20_ultra
        value_not: error
      - entity: vacuum.l20_ultra
        value_not: paused
    tooltip: Pause
    tap_action:
      action: call-service
      service: vacuum.pause
      service_data:
        entity_id: vacuum.l20_ultra
  - icon: mdi:stop
    conditions:
      - entity: vacuum.l20_ultra
        value_not: docked
      - entity: vacuum.l20_ultra
        value_not: idle
      - entity: vacuum.l20_ultra
        value_not: error
      - entity: vacuum.l20_ultra
        value_not: paused
    tooltip: Stop
    tap_action:
      action: call-service
      service: vacuum.stop
      service_data:
        entity_id: vacuum.l20_ultra
  - icon: mdi:home-map-marker
    conditions:
      - entity: vacuum.l20_ultra
        value_not: docked
      - entity: vacuum.l20_ultra
        value_not: returning
    tooltip: Return to base
    tap_action:
      action: call-service
      service: vacuum.return_to_base
      service_data:
        entity_id: vacuum.l20_ultra
  - icon: mdi:target-variant
    conditions:
      - entity: vacuum.l20_ultra
        value_not: docked
      - entity: vacuum.l20_ultra
        value_not: error
      - entity: vacuum.l20_ultra
        value_not: cleaning
      - entity: vacuum.l20_ultra
        value_not: returning
    tooltip: Clean spot
    tap_action:
      action: call-service
      service: vacuum.clean_spot
      service_data:
        entity_id: vacuum.l20_ultra
  - icon: mdi:map-marker
    tooltip: Locate
    tap_action:
      action: call-service
      service: vacuum.locate
      service_data:
        entity_id: vacuum.l20_ultra
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.l20_ultra
        attribute: fan_speed
        value: 'off'
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.l20_ultra
        fan_speed: silent
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.l20_ultra
        attribute: fan_speed
        value: silent
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.l20_ultra
        fan_speed: balanced
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.l20_ultra
        attribute: fan_speed
        value: balanced
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.l20_ultra
        fan_speed: turbo
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.l20_ultra
        attribute: fan_speed
        value: turbo
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.l20_ultra
        fan_speed: max
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.l20_ultra
        attribute: fan_speed
        value: max
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.l20_ultra
        fan_speed: max_plus
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.l20_ultra
        attribute: fan_speed
        value: max_plus
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.l20_ultra
        fan_speed: custom
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.l20_ultra
        attribute: fan_speed
        value: custom
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.l20_ultra
        fan_speed: 'off'
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.l20_ultra
        attribute: fan_speed
        value_not: 'off'
      - entity: vacuum.l20_ultra
        attribute: fan_speed
        value_not: silent
      - entity: vacuum.l20_ultra
        attribute: fan_speed
        value_not: balanced
      - entity: vacuum.l20_ultra
        attribute: fan_speed
        value_not: turbo
      - entity: vacuum.l20_ultra
        attribute: fan_speed
        value_not: max
      - entity: vacuum.l20_ultra
        attribute: fan_speed
        value_not: max_plus
      - entity: vacuum.l20_ultra
        attribute: fan_speed
        value_not: custom
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.l20_ultra
        fan_speed: 'off'
  - icon: mdi:wave
    conditions:
      - entity: vacuum.l20_ultra
        attribute: waterBoxMode
        value: 201
    tooltip: Change mop intensity
    tap_action:
      action: call-service
      service: dreame_vacuum.vacuum_set_custom_cleaning
      service_data:
        command: set_water_box_custom_mode
        params: 202
      target:
        entity_id: vacuum.l20_ultra
  - icon: mdi:waves-arrow-up
    conditions:
      - entity: vacuum.l20_ultra
        attribute: waterBoxMode
        value: 202
    tooltip: Change mop intensity
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        command: set_water_box_custom_mode
        params: 203
      target:
        entity_id: vacuum.l20_ultra
  - icon: mdi:waves
    conditions:
      - entity: vacuum.l20_ultra
        attribute: waterBoxMode
        value: 203
    tooltip: Change mop intensity
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        command: set_water_box_custom_mode
        params: 200
      target:
        entity_id: vacuum.l20_ultra
  - icon: mdi:waves
    conditions:
      - entity: vacuum.l20_ultra
        attribute: waterBoxMode
        value_not: 200
      - entity: vacuum.l20_ultra
        attribute: waterBoxMode
        value_not: 201
      - entity: vacuum.l20_ultra
        attribute: waterBoxMode
        value_not: 202
      - entity: vacuum.l20_ultra
        attribute: waterBoxMode
        value_not: 203
```

**Comment by PiotrMachowski** [comment]
Which services do you mean?

**Comment by pillemats** [comment]
for example: i want to use these buttons with the correct services

<img width="341" alt="Bildschirmfoto 2024-06-11 um 14 43 44" src="https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/26164977/8be55a85-db0b-4ad9-b24f-a6baaf98d2dc">

i copied the config below from an roborock tutorial, so the service, the action, service_data is not correct. maybe more, like value or others. the entity is correct. that my vacuum

```yaml
  - icon: mdi:wave
    conditions:
      - entity: vacuum.l20_ultra
        attribute: waterBoxMode
        value: 201
    tooltip: Change mop intensity
    tap_action:
      action: call-service
      service: dreame_vacuum.vacuum_set_custom_cleaning
      service_data:
        command: set_water_box_custom_mode
        params: 202
      target:
        entity_id: vacuum.l20_ultra
```

hopefully you understand what i mean. sorry for the bad english. i am from germany :-)

**Reply by PiotrMachowski** [reply]
You can't copy config for another platforms, every platform works differently. For `Tasshack/dreame-vacuum` platform everything should work out of the box. Can you remove `tiles` and `icons` sections and check if appropriate icons appear? If not, can you post a screenshot of the card?

By the way, please respond in the same thread

**Reply by pillemats** [reply]
now it works, but not without the mop button...
<img width="1259" alt="Bildschirmfoto 2024-06-12 um 22 44 50" src="https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/26164977/b927f96b-f186-4d7c-83c5-88e06260135a">

i want to change the vac mode
for example

- only vac
- only wipe
- wipe & vac
maybe the same function like the fan speed button

**Reply by PiotrMachowski** [reply]
Don't you have disabled entities that can provide this functionality? There should be a select entity

**Reply by pillemats** [reply]
there are definitely some, but I don't know how to use them to make it work

Do you have an config example for my case?

**Reply by PiotrMachowski** [reply]
You have to enable these select entities and then remove `icons` section from your config. Everything should work out of the box

**Reply by pillemats** [reply]
how to enable it?

do you have an config example?

**Reply by PiotrMachowski** [reply]
Please provide a screenshot of a vacuum page from [integrations](https://my.home-assistant.io/redirect/integrations/) dashboard

**Reply by pillemats** [reply]
do you mean this?

<img width="1157" alt="Bildschirmfoto 2024-06-13 um 13 49 09" src="https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/26164977/1bac46b8-4b32-4871-959a-39883e250b1f">

**Reply by PiotrMachowski** [reply]
No, one step further - when you open the device page of "L20 Ultra"

**Reply by pillemats** [reply]
ok here we go:

<img width="1140" alt="Bildschirmfoto 2024-06-13 um 13 56 27" src="https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/26164977/85eb714d-57b6-4c23-bf6e-5206f8bc9bac">

**Reply by PiotrMachowski** [reply]
You have to find a "Water Volume" entity and enable it

**Reply by pillemats** [reply]
it isnt there:

<img width="719" alt="Bildschirmfoto 2024-06-13 um 14 26 46" src="https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/26164977/f22a43d0-1484-4435-9e83-728f0eaf417f">

i can only find these

<img width="1097" alt="Bildschirmfoto 2024-06-13 um 14 33 05" src="https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/26164977/925c584f-3d80-4045-996d-9de65a654ea1">

**Reply by PiotrMachowski** [reply]
I think it should be there unless your vacuum doesn't support it. Maybe @Tasshack could help you with that

**Reply by Tasshack** [reply]
Its `mop_pad_humidity` for the vacuums that has a self wash base.

**Reply by PiotrMachowski** [reply]
thanks, @Tasshack! 

@pillemats do you have such entity?

**Reply by pillemats** [reply]
off course... i have some more :-)

<img width="792" alt="Bildschirmfoto 2024-06-13 um 15 06 51" src="https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/26164977/cba2ac05-cae7-4a92-8d6e-87f969110b9f">

**Reply by Tasshack** [reply]
Integration generates it for every room since water amount can be set to each room individiually when customized cleaning has been enabled.
You need to use the entity without the one with room id.

**Reply by PiotrMachowski** [reply]
> You need to use the entity without the one with room id.

Exactly

@pillemats you have to enable "L20 Ultra Mop Pad Humidity" entity and remove `icons` section from card's config.

**Reply by pillemats** [reply]
in my case this one....

sensor.120_ultra_mop_pad

i see it is already activated. @PiotrMachowski how to integrate it now in the vaccum card?

i want a button like this to choose vac, mop, or both

<img width="87" alt="Bildschirmfoto 2024-06-13 um 15 21 30" src="https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/26164977/faf7d680-c74a-409f-8033-986bf97c2ee9">


EDIT: it is already activated. 
<img width="596" alt="Bildschirmfoto 2024-06-13 um 15 23 40" src="https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/26164977/731015e5-0b8d-43ff-a518-ce5afd037816">


EDIT: i found out. i think i must put in the mop pad to the vac. at the moment the pads are not installed.... i will talk to you soon

**Reply by Tasshack** [reply]
> i want a button like this to choose vac, mop, or both

You need to use `cleaning_mode` entity for this like same as `mop_pad_humidity`.

**Reply by Tasshack** [reply]
By the way, I don't think it's a good idea to implement those entities like this because of unavailability rules of the entities.
@pillemats as you already figured out mop pad humidity is unavailable when mop pads are not installed and it's not the only case that it will be unavailable. Mop pad state also affects the options of the cleaning mode too so it won't be a viable option to add this on a card as a button.

**Reply by pillemats** [reply]
now it put in the mops and many select entities are active but not the mop 

<img width="324" alt="Bildschirmfoto 2024-06-13 um 19 07 22" src="https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/26164977/f1e1ab98-2a4e-4769-91b1-264f0866be78">

If I understood correctly, the button should appear automatically, but it doesn't:

<img width="415" alt="Bildschirmfoto 2024-06-13 um 19 06 49" src="https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/26164977/8346d20a-20c6-4f0b-9542-006e629abc70">

**Reply by PiotrMachowski** [reply]
icon should appear automatically when the entity will be available

**Reply by pillemats** [reply]
i think Cleaning mode is the right entity 

this isnt active....

<img width="316" alt="Bildschirmfoto 2024-06-14 um 14 23 01" src="https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/26164977/4d95a474-ecfc-478f-a292-cf9980757c1e">

@Tasshack maybe i must change anything in the IOS App to activate cleaning mode ?


@PiotrMachowski i changed something in the app and now cleaning mode is active 

<img width="332" alt="Bildschirmfoto 2024-06-14 um 14 28 26" src="https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/26164977/38bfc9df-90f8-4139-9506-ea83c2990ac6">


but not the button:

<img width="412" alt="Bildschirmfoto 2024-06-14 um 14 29 29" src="https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/26164977/da26bae0-991d-450b-9595-926306ebfb5b">

**Reply by Tasshack** [reply]
Cleaning mode can be set different to each room same as like the mop pad humidity when customized cleaning has been enabled.

**Reply by PiotrMachowski** [reply, marked as answer]
> @PiotrMachowski i changed something in the app and now cleaning mode is active
> <img alt="Bildschirmfoto 2024-06-14 um 14 28 26" width="332" src="https://private-user-images.githubusercontent.com/26164977/339764802-38bfc9df-90f8-4139-9506-ea83c2990ac6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzA1MDksIm5iZiI6MTcxODM3MDIwOSwicGF0aCI6Ii8yNjE2NDk3Ny8zMzk3NjQ4MDItMzhiZmM5ZGYtOTBmOC00MTM5LTk1MDYtZWE4M2MyOTkwYWM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDEzMDMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3ZDg0OWQ0NjY3MWM5ZmNkODUwOTNiN2E1NmQ1NzE2ZDYzZmIxYTRjZDQ1Mjk0OWNmYmNjMzMzNDFlMWE4MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ayrPYqxqOumF36SEhjTS_pABMSm1B-YwjeuCmlHqyYs">
>
> but not the button:
> 
> <img alt="Bildschirmfoto 2024-06-14 um 14 29 29" width="412" src="https://private-user-images.githubusercontent.com/26164977/339764966-da26bae0-991d-450b-9595-926306ebfb5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzA1MDksIm5iZiI6MTcxODM3MDIwOSwicGF0aCI6Ii8yNjE2NDk3Ny8zMzk3NjQ5NjYtZGEyNmJhZTAtOTkxZC00NTBiLTk1OTUtOTI2MzA2ZWJmYjViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDEzMDMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjNDEzZGVhNWQyNGU4ZTE0ZjY2ZDdlMTBjYmI2OGFiYmRmYzBlNGRiYTc0NDljMmEzMzJjZTg3YWRjZGI1MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5MlFIgC9DEAzRRjCqRUyHLJfLbir6P9hwJ37FdrBUXo">

Cleaning mode will not appear automatically, just "Mop Pad Humidity" or "Water Volume", so you have to add it manually:

```yaml
append_icons: true
icons:
  - type: "menu"
    menu_id: "cleaning_mode"
    icon_id: "cleaning_mode"
    entity: "select.l20_ultra_cleaning_mode"
    available_values_attribute: "options"
    icon: "mdi:water"
    icon_mapping:
      sweeping: "mdi:numeric-1"
      mopping: "mdi:numeric-2"
      sweeping_and_mopping: "mdi:numeric-3"
      mopping_after_sweeping: "mdi:numeric-4"
    tap_action:
      action: "call-service"
      service: "select.select_option"
      service_data:
        option: "[[value]]"
        entity_id: "[[entity_id]]"
```

**Reply by pillemats** [reply]
that is my solution!!! Thank you so much!!!


EDIT: one more question. how to lock the camera entity after zooming?

i can use the lock but after refresh its resettet

**Reply by PiotrMachowski** [reply]
You have to configure cropping

**Reply by pillemats** [reply]
ok thanks!

is this correct?
```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.l20_ultra_map
calibration_source:
  camera: true
crop:
  top: 20
  bottom: 20
  left: 20
  right: 20
entity: vacuum.l20_ultra
vacuum_platform: Tasshack/dreame-vacuum
card_mod:
```

**Reply by PiotrMachowski** [reply]
Nope, it should be under `map_source`:
```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.l20_ultra_map
  crop:
    top: 20
    bottom: 20
    left: 20
    right: 20
calibration_source:
  camera: true
entity: vacuum.l20_ultra
vacuum_platform: Tasshack/dreame-vacuum
card_mod:
```

**Reply by pillemats** [reply]
great! it works! Thank you so much!

Is it possible to integrate vaccum-card in your config?

<img width="997" alt="Bildschirmfoto 2024-06-18 um 11 09 30" src="https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/26164977/e00c313e-5c13-4cb7-ac5e-9172047c325c">


i want to integrate it here:

<img width="571" alt="Bildschirmfoto 2024-06-18 um 11 11 15" src="https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/26164977/07b1a52a-4214-4509-8ebf-c67946d5e0af">


here is the config from vacuum card:

```yaml
type: custom:vacuum-card
entity: vacuum.l20_ultra
compact_view: false
show_name: false
show_status: false
show_toolbar: false
```

and here from xiaomi card:

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.l20_ultra_map
  crop:
    top: 100
    bottom: 10
    left: 10
    right: 10
calibration_source:
  camera: true
entity: vacuum.l20_ultra
vacuum_platform: Tasshack/dreame-vacuum
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_point
  - template: vacuum_clean_segment
    predefined_selections:
      - id: '1'
        icon:
          name: mdi:chef-hat
          x: -5600
          'y': 5050
        label:
          text: Kitchen
          x: -5600
          'y': 5050
          offset_y: 35
        outline:
          - - -6300
            - 3600
          - - -1500
            - 3600
          - - -1500
            - 6300
          - - -6300
            - 6300
      - id: '2'
        icon:
          name: mdi:foot-print
          x: -300
          'y': 4850
        label:
          text: Corridor
          x: -300
          'y': 4850
          offset_y: 35
        outline:
          - - -1500
            - 3200
          - - 1700
            - 3200
          - - 1700
            - 7450
          - - -1500
            - 7450
      - id: '3'
        icon:
          name: mdi:room-service-outline
          x: -10350
          'y': 5150
        label:
          text: Dining Hall
          x: -10350
          'y': 5150
          offset_y: 35
        outline:
          - - -16000
            - 2300
          - - -6300
            - 2300
          - - -6300
            - 7000
          - - -16000
            - 7000
      - id: '4'
        icon:
          name: mdi:monitor-shimmer
          x: 200
          'y': 1300
        label:
          text: Office
          x: 200
          'y': 1300
          offset_y: 35
        outline:
          - - -1650
            - -800
          - - 1700
            - -800
          - - 1700
            - 3200
          - - -1650
            - 3200
      - id: '5'
        icon:
          name: mdi:home-outline
          x: -4050
          'y': 1100
        label:
          text: Kinderzimmer
          x: -4050
          'y': 1100
          offset_y: 35
        outline:
          - - -6550
            - -800
          - - -1650
            - -800
          - - -1650
            - 2900
          - - -6550
            - 2900
      - id: '6'
        icon:
          name: mdi:sofa-outline
          x: -10100
          'y': -1400
        label:
          text: Living Room
          x: -10100
          'y': -1400
          offset_y: 35
        outline:
          - - -12750
            - -6300
          - - -6400
            - -6300
          - - -6400
            - 3250
          - - -12750
            - 3250
      - id: '7'
        icon:
          name: mdi:home-outline
          x: -1350
          'y': 8800
        label:
          text: Room 7
          x: -1350
          'y': 8800
          offset_y: 35
        outline:
          - - -2700
            - 7450
          - - 600
            - 7450
          - - 600
            - 11750
          - - -2700
            - 11750
  - template: vacuum_clean_segment
    predefined_selections:
      - id: '1'
        icon:
          name: mdi:chef-hat
          x: -5600
          'y': 5050
        label:
          text: Kitchen
          x: -5600
          'y': 5050
          offset_y: 35
        outline:
          - - -6300
            - 3600
          - - -1500
            - 3600
          - - -1500
            - 6400
          - - -6300
            - 6400
      - id: '2'
        icon:
          name: mdi:foot-print
          x: -300
          'y': 4850
        label:
          text: Corridor
          x: -300
          'y': 4850
          offset_y: 35
        outline:
          - - -1500
            - 3200
          - - 1750
            - 3200
          - - 1750
            - 7450
          - - -1500
            - 7450
      - id: '3'
        icon:
          name: mdi:room-service-outline
          x: -10350
          'y': 5150
        label:
          text: Dining Hall
          x: -10350
          'y': 5150
          offset_y: 35
        outline:
          - - -16000
            - 2300
          - - -6300
            - 2300
          - - -6300
            - 7100
          - - -16000
            - 7100
      - id: '4'
        icon:
          name: mdi:monitor-shimmer
          x: 200
          'y': 1300
        label:
          text: Office
          x: 200
          'y': 1300
          offset_y: 35
        outline:
          - - -1650
            - -850
          - - 1750
            - -850
          - - 1750
            - 3200
          - - -1650
            - 3200
      - id: '5'
        icon:
          name: mdi:home-outline
          x: -4050
          'y': 1100
        label:
          text: Kinderzimmer
          x: -4050
          'y': 1100
          offset_y: 35
        outline:
          - - -6550
            - -850
          - - -1650
            - -850
          - - -1650
            - 2950
          - - -6550
            - 2950
      - id: '6'
        icon:
          name: mdi:sofa-outline
          x: -10100
          'y': -1400
        label:
          text: Living Room
          x: -10100
          'y': -1400
          offset_y: 35
        outline:
          - - -12850
            - -6450
          - - -6350
            - -6450
          - - -6350
            - 3250
          - - -12850
            - 3250
      - id: '7'
        icon:
          name: mdi:home-outline
          x: -1350
          'y': 8800
        label:
          text: Room 7
          x: -1350
          'y': 8800
          offset_y: 35
        outline:
          - - -2700
            - 7450
          - - 600
            - 7450
          - - 600
            - 11800
          - - -2700
            - 11800
append_icons: true
icons:
  - type: menu
    menu_id: cleaning_mode
    icon_id: cleaning_mode
    entity: select.l20_ultra_cleaning_mode
    available_values_attribute: options
    icon: mdi:water
    icon_mapping:
      sweeping: mdi:arrow-up-circle-outline
      mopping: mdi:waves
      sweeping_and_mopping: mdi:waves-arrow-up
    tap_action:
      action: call-service
      service: select.select_option
      service_data:
        option: '[[value]]'
        entity_id: '[[entity_id]]'
map_locked: true
card_mod:
  style: |
    ha-card {
     display: flex !important;
     align-items: stretch;
     flex-wrap: wrap;
     justify-content: space-evenly;
    }
    .map-wrapper {
     flex-grow: 3;
     width: 600px;
    }
    .controls-wrapper {
     flex-grow: 1;
     width: 300px;
    }
```
