### DISCUSSION TITLE
Configure rooms for viomi.vacuum.v7

### DISCUSSION THREAD

**Discussion by eerison** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#749] [Q&A]
Hello guys

any of you could configure rooms for model `viomi.vacuum.v7`?

I tried to define zones But `Sections` doesn't show any value to be copied :/

<img width="993" alt="Screenshot 2024-07-11 at 17 56 18" src="https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/6358755/3db1a0a9-37f4-4ebc-b7e7-5d170e21e998">
<img width="1003" alt="Screenshot 2024-07-11 at 17 56 58" src="https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/6358755/7a588b08-d965-482e-b664-728081f0384f">

**Comment by PiotrMachowski** [comment]
https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/747

**Comment by eerison** [comment]
now the rooms are generated :)

But when I draw a zone (Zone Cleanup) it works, But when I execute a room, nothing happen :/

Note: I am using `send_command`

**Reply by PiotrMachowski** [reply]
I assume you use Xiaomi Miot integration?

**Reply by eerison** [reply]
Yep this one: https://github.com/al-one/hass-xiaomi-miot

**Reply by PiotrMachowski** [reply]
Xiaomi Miot integration doesn't work out of the box, you have to adjust it manually. [This config](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/406#discussioncomment-3694847) might work for you

**Reply by eerison** [reply]
It might help me :)

One last question, do you have any idea why when I execute the roboot to cleanup a zone via ui it works, But calling the service direct, it doesn't?

e.g

```yaml
service: xiaomi_miot.send_command
data:
  entity_id: vacuum.viomi_v7_xxx_robot_cleaner
  method: app_zoned_clean
  params:
    - - -1
      - 0
      - 0
      - 1
      - 1
```

**Reply by PiotrMachowski** [reply]
> I execute the roboot to cleanup a zone via ui it works

What is your config?

**Reply by eerison** [reply]
<img width="1357" alt="Screenshot 2024-07-12 at 13 12 40" src="https://github.com/user-attachments/assets/c915d84f-daba-4ae3-be16-275289c38196">

I am trying to execute directly via home assistant service page

**Reply by PiotrMachowski** [reply]
Yes, but I meant the one that works

**Reply by eerison** [reply]
it is my card


```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.viomi_v7_xxx_robot_cleaner
vacuum_platform: send_command
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_clean_segment
    predefined_selections:
      - id: '10'
        icon:
          name: mdi:broom
          x: -3.375
          'y': -1.725
        label:
          text: kitchen
          x: -3.375
          'y': -1.725
          offset_y: 35
        outline:
          - - -5.5
            - -2.8
          - - -1.25
            - -2.8
          - - -1.25
            - -0.65
          - - -5.5
            - -0.65
      - id: '11'
        icon:
          name: mdi:broom
          x: -2.5
          'y': 2.025
        label:
          text: Living room
          x: -2.5
          'y': 2.025
          offset_y: 35
        outline:
          - - -5.5
            - 0.4
          - - 0.5
            - 0.4
          - - 0.5
            - 3.65
          - - -5.5
            - 3.65
      - id: '12'
        icon:
          name: mdi:broom
          x: -0.875
          'y': -1.1999999999999997
        label:
          text: Hall
          x: -0.875
          'y': -1.1999999999999997
          offset_y: 35
        outline:
          - - -2.35
            - -2.8
          - - 0.6
            - -2.8
          - - 0.6
            - 0.4
          - - -2.35
            - 0.4
      - id: '13'
        icon:
          name: mdi:broom
          x: -2.6500000000000004
          'y': -4.6499999999999995
        label:
          text: Bedroom
          x: -2.6500000000000004
          'y': -4.6499999999999995
          offset_y: 35
        outline:
          - - -5.65
            - -6.6
          - - 0.35
            - -6.6
          - - 0.35
            - -2.7
          - - -5.65
            - -2.7
```

and I draw it one the ui, like this

<img width="531" alt="Screenshot 2024-07-12 at 13 19 39" src="https://github.com/user-attachments/assets/7331ddbf-fe42-4419-bee9-57193b39812b">
