### DISCUSSION TITLE
Help to set menu for changing vacuum mode

### DISCUSSION THREAD

**Discussion by Melaxx19** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#758] [Q&A]
Hello, I can't really get going this kind of menu for mode selection. I guess the service call is wrong but I can't really figure out the right one.

I use viomi.v8 vacuum integrated via al-one/hass-xiaomi-miot

This is part of configuration I use for this: 
```yaml
  - menu_id: vacuum_mode
    icon: mdi:robot-vacuum
    label: Vacuum
    tooltip: Vyberte režim vysávania
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.viomi_v8_8233_robot_cleaner
        command: set_mode
        params:
          mode: 0
  - menu_id: vacuum_mode
    icon: mdi:robot-vacuum-variant
    label: Vacuum and Mop
    tooltip: Vyberte režim vysávania
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.viomi_v8_8233_robot_cleaner
        command: set_mode
        params:
          mode: 1
  - menu_id: vacuum_mode
    icon: mdi:water
    label: Mop
    tooltip: Vyberte režim vysávania
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.viomi_v8_8233_robot_cleaner
        command: set_mode
        params:
          mode: 2
 ```

Whole config is in attachments
[xiaomi-vacuum-map-card.txt](https://github.com/user-attachments/files/16824891/xiaomi-vacuum-map-card.txt)
       
![map_card](https://github.com/user-attachments/assets/1c20b30d-1900-446f-99da-331c6cb26406)
