### DISCUSSION TITLE
clean segment is not working

### DISCUSSION THREAD

**Discussion by panic-Patrick** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#779] [General]
Hey, I have the following problem and a question: I have defined clean segments, but the robot always starts in the bedroom, even though that room isn't selected. What could be causing this? Additionally, is it possible to rename the clean segments?

Attached is my code for the vacuum card.

```
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.l10sultra_map
calibration_source:
  camera: true
entity: vacuum.l10sultra
vacuum_platform: Tasshack/dreame-vacuum
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_point
  - template: vacuum_clean_segment
    predefined_selections:
      - id: "8"
        icon:
          name: mdi:bed-king-outline
          x: -4000
          "y": -2850
        label:
          text: Primary Bedroom
          x: -4000
          "y": -2850
          offset_y: 35
        outline:
          - - -7050
            - -4900
          - - -2650
            - -4900
          - - -2650
            - -800
          - - -7050
            - -800
      - id: "4"
        icon:
          name: mdi:toilet
          x: -850
          "y": -2850
        label:
          text: Bathroom
          x: -850
          "y": -2850
          offset_y: 35
        outline:
          - - -2700
            - -4900
          - - 250
            - -4900
          - - 250
            - -800
          - - -2700
            - -800
      - id: "3"
        icon:
          name: mdi:foot-print
          x: -1650
          "y": 1350
        label:
          text: Corridor
          x: -1650
          "y": 1350
          offset_y: 35
        outline:
          - - -5400
            - -800
          - - 550
            - -800
          - - 550
            - 3450
          - - -5400
            - 3450
      - id: "2"
        icon:
          name: mdi:toilet
          x: -6200
          "y": -250
        label:
          text: Bathroom 2
          x: -6200
          "y": -250
          offset_y: 35
        outline:
          - - -7000
            - -750
          - - -5400
            - -750
          - - -5400
            - 950
          - - -7000
            - 950
  - template: vacuum_clean_segment
    predefined_selections:
      - id: "7"
        icon:
          name: mdi:sofa-outline
          x: 3250
          "y": -2100
        label:
          text: Living Room
          x: 3250
          "y": -2100
          offset_y: 35
        outline:
          - - 550
            - -5150
          - - 5450
            - -5150
          - - 5450
            - 950
          - - 550
            - 950
      - id: "5"
        icon:
          name: mdi:room-service-outline
          x: 3900
          "y": 3050
        label:
          text: Dining Hall
          x: 3900
          "y": 3050
          offset_y: 35
        outline:
          - - 2550
            - 650
          - - 5550
            - 650
          - - 5550
            - 5200
          - - 2550
            - 5200
      - id: "1"
        icon:
          name: mdi:chef-hat
          x: 650
          "y": 3050
        label:
          text: Kitchen
          x: 650
          "y": 3050
          offset_y: 35
        outline:
          - - -850
            - 1300
          - - 2550
            - 1300
          - - 2550
            - 5250
          - - -850
            - 5250
  - template: vacuum_clean_segment
    predefined_selections:
      - id: "2"
        icon:
          name: mdi:toilet
          x: -6200
          "y": -250
        label:
          text: Bathroom 2
          x: -6200
          "y": -250
          offset_y: 35
        outline:
          - - -7000
            - -750
          - - -5400
            - -750
          - - -5400
            - 950
          - - -7000
            - 950
append_icons: true
icons:
  - type: menu
    menu_id: cleaning_mode
    icon_id: cleaning_mode
    entity: select.l10sultra_cleaning_mode
    available_values_attribute: options
    icon: mdi:water
    icon_mapping:
      sweeping: mdi:numeric-1
      mopping: mdi:numeric-2
      sweeping_and_mopping: mdi:numeric-3
      mopping_after_sweeping: mdi:numeric-4
    tap_action:
      action: call-service
      service: select.select_option
      service_data:
        option: "[[value]]"
        entity_id: "[[entity_id]]"
 
```
