### DISCUSSION TITLE
I ask for help in advanced configuration of config for imilab v1

### DISCUSSION THREAD

**Discussion by arsenal3008** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#786] [Q&A]
Hello, I don't know any programming languages, but I want to use all the possibilities of home assistant.
I can't do:
1. Drop-down list with a choice of actions for dust reset
2. Make my own map from a drawing (I can't make it transparent so that the path is visible)
3. Make a notification when the water in the tank runs out
4. I'm trying to adjust the brush speed block, I can't, the selection list doesn't drop out.
![2024-12-25_14-52-06](https://github.com/user-attachments/assets/dc0a1e7a-4602-485d-88d6-14f966355fad)
```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
vacuum_platform: DeebotUniverse/Deebot-4-Home-Assistant
map_locked: true
map_source:
  image: /local/custom_lovelace/xiaomi_vacuum_map_card/map_5.png
  crop:
    top: 15
    bottom: 20
icons:
  - icon: mdi:play
    conditions:
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        value_not: cleaning
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        value_not: error
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        value_not: returning
    tooltip: Старт
    tap_action:
      action: call-service
      service: vacuum.start
      service_data:
        entity_id: vacuum.chuangmi_hmi707_9f51_robot_cleaner
  - icon: mdi:pause
    conditions:
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        value_not: docked
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        value_not: idle
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        value_not: error
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        value_not: paused
    tooltip: Пауза
    tap_action:
      action: call-service
      service: vacuum.pause
      service_data:
        entity_id: vacuum.chuangmi_hmi707_9f51_robot_cleaner
  - icon: mdi:stop
    conditions:
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        value_not: docked
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        value_not: idle
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        value_not: error
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        value_not: paused
    tooltip: Стоп
    tap_action:
      action: call-service
      service: vacuum.stop
      service_data:
        entity_id: vacuum.chuangmi_hmi707_9f51_robot_cleaner
  - icon: mdi:home-map-marker
    conditions:
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        value_not: docked
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        value_not: returning
    tooltip: На базу
    tap_action:
      action: call-service
      service: vacuum.return_to_base
      service_data:
        entity_id: vacuum.chuangmi_hmi707_9f51_robot_cleaner
  - icon: mdi:land-plots-marker
    tooltip: Поиск пылесоса
    tap_action:
      action: call-service
      service: xiaomi_miot.call_action
      service_data:
        entity_id: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        siid: 7
        aiid: 1
  - type: menu
    menu_id: clean_mode
    icon_id: clean_mode
    entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
    available_values_attribute: options
    icon: mdi:vacuum
    icon_mapping:
      Vacuum: mdi:broom
      Vacuum & Mop: mdi:vacuum
      Mop: mdi:waves
    conditions:
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        value_not: cleaning
    tooltip: Смена типа уборки
    tap_action:
      action: call-service
      service: select.select_option
      service_data:
        option: "[[value]]"
        entity_id: "[[entity_id]]"
  - menu_id: fan_speed
    icon: mdi:fan
    label: Silent
    conditions:
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: fan_speed
        value: "1"
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: fan_speed
    tooltip: Смена типа уборки
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        siid: 2
        piid: 4
        value: 1
  - menu_id: fan_speed
    icon: mdi:fan-speed-1
    label: Basic
    conditions:
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: fan_speed
        value: "2"
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: fan_speed
    tooltip: Смена типа уборки
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        siid: 2
        piid: 4
        value: 2
  - menu_id: fan_speed
    icon: mdi:fan-speed-2
    label: Strong
    conditions:
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: fan_speed
        value: "3"
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: fan_speed
    tooltip: Смена типа уборки
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        siid: 2
        piid: 4
        value: 3
  - menu_id: fan_speed
    icon: mdi:fan-speed-3
    label: Full Speed
    conditions:
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: fan_speed
        value: "4"
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: fan_speed
    tooltip: Смена типа уборки
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        siid: 2
        piid: 4
        value: 4
  - menu_id: fan_speed
    icon: mdi:fan-speed-3
    label: Mop
    conditions:
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: fan_speed
        value: "0"
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: fan_speed
    tooltip: Смена типа уборки
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        siid: 2
        piid: 4
        value: 0
  - icon: mdi:fan
    conditions:
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: fan_speed
        value_not: "1"
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: fan_speed
        value_not: "2"
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: fan_speed
        value_not: "3"
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: fan_speed
        value_not: "4"
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: fan_speed
        value_not: "0"
  - type: menu
    menu_id: mop_style
    icon_id: mop_style
    entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
    available_values_attribute: options
    icon: mdi:water
    icon_mapping:
      弓字形: mdi:alpha-s-circle
      Y字形: mdi:alpha-y-circle
    value_translation_keys:
      弓字形: S-style
      Y字形: Y-style
    conditions:
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        value_not: Vacuum
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        value_not: cleaning
    tooltip: Change mop style
    tap_action:
      action: call-service
      service: select.select_option
      service_data:
        option: "[[value]]"
        entity_id: "[[entity_id]]"
  - menu_id: water_level
    icon: mdi:water-off
    label: Без воды
    conditions:
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: custom.water_level
        value: "0"
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: custom.mop
        value_not: "0"
    tooltip: Расход воды
    tap_action:
      action: call-service
      service: xiaomi_miot.set_miot_property
      service_data:
        entity_id: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        siid: 7
        piid: 8
        value: 0
  - menu_id: water_level
    icon: mdi:water-opacity
    label: Мало
    conditions:
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: custom.water_level
        value: "1"
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: custom.mop
        value_not: "0"
    tooltip: Расход воды
    tap_action:
      action: call-service
      service: xiaomi_miot.set_miot_property
      service_data:
        entity_id: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        siid: 7
        piid: 8
        value: 1
  - menu_id: water_level
    icon: mdi:water
    label: Норма
    conditions:
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: custom.water_level
        value: "2"
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: custom.mop
        value_not: "0"
    tooltip: Расход воды
    tap_action:
      action: call-service
      service: xiaomi_miot.set_miot_property
      service_data:
        entity_id: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        siid: 7
        piid: 8
        value: 2
  - menu_id: water_level
    icon: mdi:water-plus
    label: Много
    conditions:
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: custom.water_level
        value: "3"
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: custom.mop
        value_not: "0"
    tooltip: Расход воды
    tap_action:
      action: call-service
      service: xiaomi_miot.set_miot_property
      service_data:
        entity_id: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        siid: 7
        piid: 8
        value: 3
  - icon: mdi:water-off
    conditions:
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: custom.mop
        value_not: "0"
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: custom.water_level
        value_not: "1"
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: custom.water_level
        value_not: "2"
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: custom.water_level
        value_not: "3"
  - icon: mdi:numeric-2-box-multiple-outline
    tooltip: Двойная уборка вкл.
    conditions:
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: custom.double_clean
        value: true
    tap_action:
      action: call-service
      service: xiaomi_miot.set_miot_property
      service_data:
        entity_id: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        siid: 7
        piid: 13
        value: false
  - icon: mdi:numeric-1-box-outline
    tooltip: Двойная уборка выкл.
    conditions:
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: custom.double_clean
        value_not: true
    tap_action:
      action: call-service
      service: xiaomi_miot.set_miot_property
      service_data:
        entity_id: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        siid: 7
        piid: 13
        value: true
  - icon: mdi:axis-y-arrow
    tooltip: Y Уборка вкл.
    conditions:
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: custom.mop
        value: "1"
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: map.path_type
        value: "1"
    tap_action:
      action: call-service
      service: xiaomi_miot.set_miot_property
      service_data:
        entity_id: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        siid: 13
        piid: 7
        value: 0
  - icon: mdi:heating-coil
    tooltip: Y Уборка выкл.
    conditions:
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: custom.mop
        value: "1"
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: map.path_type
        value_not: "1"
    tap_action:
      action: call-service
      service: xiaomi_miot.set_miot_property
      service_data:
        entity_id: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        siid: 13
        piid: 7
        value: 1
tiles:
  - tile_id: status
    entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
    label: Статус
    attribute: vacuum.status
    translations:
      "1": Dromant
      "2": Бездействие
      "3": Пауза
      "4": Уборка
      "5": Еду на зарядку
      "6": На зарядке
      "7": Ошибка
      "8": Remote
      "9": Заряжен
      "10": Shut-down
      "11": Back-Chagrge-Pause
    icon: mdi:robot-vacuum
  - tile_id: status
    entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
    label: Тип уборки
    attribute: vacuum.sweep_type
    icon: mdi:broom
    translations:
      "0": Пылесос
      "1": Швабра
      "2": Влажная
  - tile_id: battery_level
    entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
    label: Батарея
    attribute: battery_level
    icon_source: vacuum.chuangmi_hmi707_9f51_robot_cleaner.attributes.battery_icon
    unit: "%"
  - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
    label: Mop style
    icon: mdi:gesture
    icon_mapping:
      弓字形: mdi:alpha-s-circle
      Y字形: mdi:alpha-y-circle
    conditions:
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        value: mopping
    translations:
      弓字形: S-style
      Y字形: Y-style
  - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
    label: Error state
    conditions:
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        value: error
  - tile_id: total.clean_time
    entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
    attribute: custom.total_clean_time
    multiplier: 0.01666666666
    precision: 0
    icon: mdi:timer
    label: Всего (м.)
  - tile_id: total_clean_areas
    entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
    attribute: custom.total_clean_areas
    icon: mdi:square-opacity
    label: Всего (м²)
  - tile_id: clean_counts
    entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
    attribute: custom.clean_area
    icon: mdi:square-opacity
    label: Сегодня (м²)
  - tile_id: clean_time
    entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
    attribute: custom.clean_time
    multiplier: 0.01666666666
    precision: 0
    icon: mdi:timer
    label: Сегодня (м.)
  - tile_id: main_brush_level
    entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
    attribute: brush_cleaner.brush_life_level
    unit: "%"
    label: Турбо щетка
    icon: mdi:spirit-level
    tap_action:
      action: call-service
      confirmation:
        text: Сбросить значения турбо щетки?
      service: xiaomi_miot.call_action
      service_data:
        entity_id: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        siid: 11
        aiid: 1
  - tile_id: side_brush_level
    entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
    attribute: brush_life_level-11-2
    unit: "%"
    label: Боковая щетка
    icon: mdi:ceiling-fan
    tap_action:
      action: call-service
      confirmation:
        text: Сбросить значения боковой щетки?
      service: xiaomi_miot.call_action
      service_data:
        entity_id: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        siid: 12
        aiid: 1
  - tile_id: filter_level
    entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
    attribute: filter.filter_life_level
    unit: "%"
    label: Фильтр
    icon: mdi:air-filter
    tap_action:
      action: call-service
      confirmation:
        text: Сбросить значения фильтра?
      service: xiaomi_miot.call_action
      service_data:
        entity_id: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        siid: 10
        aiid: 1
  - tile_id: fault
    entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
    label: Ошибки
    attribute: vacuum.fault
    icon: mdi:alert-circle
    translations:
      "0": Без ошибок
      "1": Low Power
      "2": Low Power And Shut Down
      "3": Wheel Error
      "4": Collision Error
      "5": Tile Do Task
      "6": Lidar Point Error
      "7": Front Wall Error
      "8": Psd Dirty
      "9": Middle BRush Error
      "10": Sid Brush Error
      "11": Fan Speed Error
      "12": Lidar Cover Error
      "13": Grabage Box Full
      "14": Grabage Box Out
      "15": Grabage Box Full Out
      "16": Physical Plan
      "17": Pick Up Do Task
      "18": No Water Do Task
      "19": Бак для воды пуст
      "20": Cannot Arrive
      "21": Start Form Forbid Area
      "22": Drop
      "23": Kit Water Pump
      "24": Find Charge Fail
      "25": Kit Water Error
      "26": No Mop Do Task
      "27": Lidar Speed Error
      "28": Move Obst Charge
      "29": Не удалил мусор
map_modes:
  - name: Уборка зоны
    icon: mdi:select-drag
    selection_type: MANUAL_RECTANGLE
    variables:
      map_id: 1661655224
    max_selections: 5
    repeats: NONE
    max_repeats: 5
    service_call_schema:
      evaluate_data_as_template: true
      service: xiaomi_miot.call_action
      service_data:
        entity_id: "[[entity_id]]"
        siid: 14
        aiid: 1
        params:
          - 4
          - >-
            {"MapId":[[map_id]],
            "ExtraAreas":{"name":"定点","id":301,"tag":"5","vertexs":[[{{[[selection]][0][0]}},
            {{[[selection]][0][3]}}],[{{[[selection]][0][2]}},
            {{[[selection]][0][3]}}],[{{[[selection]][0][2]}},
            {{[[selection]][0][1]}}],[{{[[selection]][0][0]}},
            {{[[selection]][0][1]}}]],"active":"normal","mode":"point"}}
  - template: vacuum_clean_segment
    name: Уборка сегмента
    variables:
      map_id: 1661655224
    max_selections: 5
    repeats_type: NONE
    service_call_schema:
      service: xiaomi_miot.call_action
      service_data:
        entity_id: "[[entity_id]]"
        siid: 14
        aiid: 1
        params:
          - 2
          - "{\"mapId\":[[map_id]],\"segmentId\":[[[selection_unwrapped]]]}"
    predefined_selections:
      - id: 3
        label:
          text: Диван
          x: 925.0004142522812
          "y": -2975.00055283308
          offset_y: 35
        icon:
          name: mdi:broom
          x: 925.0004142522812
          "y": -2975.00055283308
      - id: 2
        label:
          text: Центр
          x: 925.0004142522812
          "y": -1475.000530481338
          offset_y: 35
        icon:
          name: mdi:broom
          x: 925.0004142522812
          "y": -1475.000530481338
      - id: 1
        label:
          text: Компьютер
          x: 925.0004142522812
          "y": 74.99949261546158
          offset_y: 35
        icon:
          name: mdi:broom
          x: 925.0004142522812
          "y": 74.99949261546158
additional_presets: []
```

**Comment by arsenal3008** [comment]
Will these settings work to display the robot vacuum and path on top of the map image?
card_mod:
  style: |
    ha-card {
      --map-card-room-label-color: white;
      --map-card-room-icon-background-color: white;
      --map-card-room-label-font-size: 18px;
      --map-card-primary-color: red;
      --map-card-zoomer-background: rgba(155, 130, 131, 0.7);      
    }
    svg text {
      stroke: white;
      font-weight: bold;
    } 
If so, what parameters and where should I write them so that it works?
Is it possible to make the drop-down list not close until the command is completed?
![2024-12-26_16-18-42](https://github.com/user-attachments/assets/504aa081-ef2f-4152-ac63-2f3756d0dbfa)

**Reply by sca075** [reply]
It isn't clear what you are trying to accomplish to be honest it looks like you got a vacuum and somehow you want to display the map (that as you don't retrieve from the vacuum) drawer by you.
You want to see the path of the vacuum overlapping the drawing is that correct? 

The phat data anyhow comes from the vacuum and if you aren't using any of the integrations (for the vacuum) listed in the setup of the card it could be a little complicated (to don't say impossible).

**Reply by arsenal3008** [reply]
I understand, thank you, and what about the other two questions?

**Reply by sca075** [reply]
Well I guess the imilab v1 is a xaiomi instead of images done by you are you sure you are using the right integration for it?

**Reply by arsenal3008** [reply]
I'm more interested in
1. Is it possible to make the drop-down list not close until the command is completed?
2. Drop-down list with a choice of actions for dust reset
3. Make a notification when the water in the tank runs out
4. I'm trying to adjust the brush speed block, I can't, the selection list doesn't drop out.
I have an image, I wanted a picture
disabling the camera doesn't work as I imagined, the map is constantly changing, that's why I wanted a picture

**Reply by PiotrMachowski** [reply]
The first step to achieve anything is to use appropriate integration. Please provide more info about your setup

**Reply by arsenal3008** [reply]
Is that what you meant?
https://home.miot-spec.com/spec/chuangmi.vacuum.hmi707

**Reply by PiotrMachowski** [reply]
No, not really. I meant which integration do you use to add the vacuum to HA. Is it [this one](https://github.com/al-one/hass-xiaomi-miot)?

**Reply by arsenal3008** [reply]
yes

**Reply by arsenal3008** [reply]
Will my questions be answered?

**Reply by PiotrMachowski** [reply]
> 1. Drop-down list with a choice of actions for dust reset

Do you want to use icons below the map to do that? In my approach I used long press on specific tile to reset the consumable.

> 2. Make my own map from a drawing (I can't make it transparent so that the path is visible)

You can't use map drawing and make a path visible at this moment.

> 3. Make a notification when the water in the tank runs out

What kind of notification do you want? Most probably it should be an automation, not a card config.

> 4. I'm trying to adjust the brush speed block, I can't, the selection list doesn't drop out.

Please provide more info about your vacuum entity (data from dev tools)

**Reply by arsenal3008** [reply]
Do you mean this?
```yaml
info: IMILAB V1 Vacuuming Robot
model: chuangmi.vacuum.hmi707
did: 448787133
mac: 60:7e:a4:2a:9f:51
lan_ip: 192.168.1.130
app_link: mihome://device?uid=4151969947&did=448787133
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:chuangmi-hmi707:2
available: true
home_room: 4151969947 Дом
icon: mdi:information
updater: cloud
updated_at: 2025-01-07 14:03:59.755131+03:00
battery.charging_state: 1
vacuum.status: 9
vacuum.mode: 2
vacuum.sweep_type: 2
sweep.sweep_mode: 0
map.map_memory: true
map.use_auto_area: false
map.path_type: 0
custom.mop: true
custom.work_station_frep: 1
custom.timing: {"time":[],"tz":3,"tzs":10800}
custom.clean_area: 0
custom.uid: LHMI707A020000001606
custom.auto_boost: true
custom.forbid_time: {"time":[],"tz":3,"tzs":10800}
custom.water_level: 1
custom.total_clean_time: 233548
custom.total_clean_areas: 3277
custom.clean_counts: 280
custom.clean_time: 0
custom.double_clean: false
custom.edge_sweep: false
custom.led_switch: true
custom.lidar_collision: true
custom.station_key: false
custom.station_key_led: false
custom.current_audio: girl_ru
custom.audio_progress: {
	"code" : 1,
	"fileName" : "girl_ru",
	"process" : 100,
	"state" : "downloaded"
}

custom.station_type: 102
custom.voice_config: file not exist !!!
brush_left_time-12-1: 21
brush_life_level-12-2: 70
brush_left_time-11-1: 135
brush_life_level-11-2: 67
brush_cleaner.brush_left_time: 235
brush_cleaner.brush_life_level: 78
filter.filter_life_level: 90
filter.filter_left_time: 135
speaker.volume: 31
speaker.mute: false
battery_level: 100
vacuum.fault: 0
vacuum.on: true
state_updater: cloud
vacuum.status_desc: Заряжен
converters: button.info, sensor.filter.filter_life_level, sensor.filter.filter_left_time, sensor.brush_cleaner.brush_life_level, sensor.brush_cleaner.brush_left_time, sensor.brush_life_level-11-2, sensor.brush_left_time-11-1, sensor.brush_life_level-12-2, sensor.brush_left_time-12-1, sensor.battery_level, sensor.battery.charging_state, sensor.vacuum.status, number.speaker.volume, select.vacuum.mode, select.vacuum.sweep_type, button.vacuum.start_sweep, button.vacuum.stop_sweeping, button.battery.start_charge, button.filter.reset_filter_life, button.brush_cleaner.reset_brush_life, button.custom.continue_sweep, button.sweep.start_sweep
customizes: 
binary_sensor_properties: mop_status
sensor_properties: >-
  status,cleaning_area,cleaning_time,mop_life_level,brush_life_level,filter_life_level,dust_bag_life_level
select_properties: mode,sweep_mop_type,sweep_type,clean_times
number_properties: volume
button_actions: >-
  start_sweep,stop_sweeping,stop_and_gocharge,start_only_sweep,start_mop,start_sweep_mop,pause_sweeping,continue_sweep,start_dust_arrest,start_mop_wash,start_dry,start_eject,stop_mop_wash,stop_dry,back_mop_wash,start_charge,identify,reset_mop_life,reset_brush_life,reset_filter_life,reset_dust_bag_life
configuration_entities: reset_mop_life,reset_brush_life,reset_filter_life,reset_dust_bag_life
chunk_coordinators:
  - interval: 10
    props: status,cleaning_area,cleaning_time,charging_state
    notify: true
  - interval: 15
    props: mode,sweep_mop_type,sweep_type,clean_times

device_class: update
friendly_name: IMILAB V1 Vacuuming Robot Info
```

**Reply by PiotrMachowski** [reply]
Can you also show a screenshot from HA? Also, I have asked several other questions

**Comment by arsenal3008** [comment]
Drop-down list with a choice of actions for dust reset (yes, I want to)
I used long press on specific tile to reset the consumable. (It works for me)
Make my own map from a drawing (I can't make it transparent so that the path is visible) (you can survive without it :))
Make a notification when the water in the tank runs out
What kind of notification do you want? Most probably it should be an automation, not a card config. (I thought it was just a flag, is there or not)
![2025-01-07_18-46-36](https://github.com/user-attachments/assets/6beafdd5-2849-433b-86ed-106adb4039f6)

**Reply by PiotrMachowski** [reply]
I still need more info about your entities related to the vacuum. Xiaomi Miot integration is very hard to work with. Follow [these steps](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/594) to get more detailed info about entities

**Reply by arsenal3008** [reply]
On which page should I open the console?
http://192.168.1.67:8123/lovelace/3

**Reply by PiotrMachowski** [reply]
This should be ok

**Reply by arsenal3008** [reply]
That's how it should be, are there any mistakes?

**Reply by PiotrMachowski** [reply]
You have to provide a correct entity id

**Reply by arsenal3008** [reply]
Yes, of course, I didn’t think about it right away, I sent it by email

**Reply by arsenal3008** [reply]
How to make a fixed switch so that this parameter is enabled?
```yaml
 - icon: mdi:numeric-2-box-multiple-outline
    tooltip: Двойная уборка вкл.
    conditions:
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: custom.double_clean
        value: true
    tap_action:
      action: call-service
      service: xiaomi_miot.set_miot_property
      service_data:
        entity_id: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        siid: 7
        piid: 13
        value: false
```

**Reply by PiotrMachowski** [reply]
Do you mean something like this?
```yaml
 - icon: mdi:numeric-2-box-multiple-outline
    tooltip: Двойная уборка вкл.
    conditions:
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: custom.double_clean
        value: true
    tap_action:
      action: call-service
      service: xiaomi_miot.set_miot_property
      service_data:
        entity_id: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        siid: 7
        piid: 13
        value: false
 - icon: mdi:numeric-2-box-multiple
    tooltip: Двойная уборка вкл.
    conditions:
      - entity: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        attribute: custom.double_clean
        value: false
    tap_action:
      action: call-service
      service: xiaomi_miot.set_miot_property
      service_data:
        entity_id: vacuum.chuangmi_hmi707_9f51_robot_cleaner
        siid: 7
        piid: 13
        value: true
```
