### DISCUSSION TITLE
Mop intensity support in the card

### DISCUSSION THREAD

**Discussion by jarekgrzabel** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#789] [Q&A]
Hi!

I have Roborock S7 MaxV and I'm trying to add the supported vacuum and mopping intensity to the card so I can manipulate the settings and for example set to mop only, intensity or hoover only depending on the need. Currently that isn't directly supported and I can get that setting change through the Xiaomi app.

I'm using Xiaomi Protocol documentation from this link: https://github.com/marcelrv/XiaomiRobotVacuumProtocol/blob/master/water_box_custom_mode.md

Based on the fan speed settings I decided to modify the card code to contain this:
```yaml
  - icon: mdi:circle-off-outline
    conditions:
      - entity: vacuum.roborock_s7_maxv
        attribute: get_water_box_custom_mode
        value: "water_box_mode: 200"
    tooltip: Change mop intensity
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.roborock_s7_maxv
        command: set_water_box_custom_mode
        params:
          - 200
  - icon: mdi:circle-slice-3
    conditions:
      - entity: vacuum.roborock_s7_maxv
        attribute: get_water_box_custom_mode
        value: 201
    tooltip: Change mop intensity
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.roborock_s7_maxv
        command: set_water_box_custom_mode
        params:
          - 201
  - icon: mdi:circle-slice-5
    conditions:
      - entity: vacuum.roborock_s7_maxv
        attribute: get_water_box_custom_mode
        value: 202
    tooltip: Change mop intensity
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.roborock_s7_maxv
        command: set_water_box_custom_mode
        params:
          - 202
  - icon: mdi:circle-slice-8
    conditions:
      - entity: vacuum.roborock_s7_maxv
        attribute: get_water_box_custom_mode
        value: 203
    tooltip: Change mop intensity
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.roborock_s7_maxv
        command: set_water_box_custom_mode
        params:
          - 203
  - icon: mdi:circle-slice-8
    conditions:
      - entity: vacuum.roborock_s7_maxv
        attribute: get_water_box_custom_mode
        value: 203
    tooltip: Change mop intensity
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.roborock_s7_maxv
        command: set_water_box_custom_mode
        params:
          - 200
  - icon: mdi:circle-slice-8
    conditions:
      - entity: vacuum.roborock_s7_maxv
        attribute: get_water_box_custom_mode
        value_not: 200
      - entity: vacuum.roborock_s7_maxv
        attribute: get_water_box_custom_mode
        value_not: 201
      - entity: vacuum.roborock_s7_maxv
        attribute: get_water_box_custom_mode
        value_not: 202
      - entity: vacuum.roborock_s7_maxv
        attribute: get_water_box_custom_mode
        value_not: 203
    tooltip: Change mop intensity
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.roborock_s7_maxv
        command: set_water_box_custom_mode
        params:
          - 200
```

The problem is, that the mop intensity mode is not exposed directly as any entity and requires a service call to get the current mode... and this is where I got stuck and I don't know how to get the current mode. I've run a debug and when I call the service like this:
```yaml
action: vacuum.send_command
target:
  device_id: xxx
data:
  command: get_water_box_custom_mode
```

The result is as follows:
`{'id': 581, 'result': {'water_box_mode': 200}, 'exe_time': 11}`

I have no idea how to get this result back to the card.

I'd appreciate any hint on how to solve this problem.

Thank you!
