### DISCUSSION TITLE
Can't generate room config

### DISCUSSION THREAD

**Discussion by panic-Patrick** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#793] [Q&A] [answered]
I have an Ecovacs Deebot T30 Pro Omni integrated with Home Assistant, and I want to create a room configuration. However, the button for this feature is disabled, and I cannot proceed. What could be the cause, and how can I resolve this issue?

**Comment by PiotrMachowski** [comment]
Unfortunately data required for automatic configuration of rooms is not provided by the Ecovacs integration. Which features of the card do you want to use? (Mainly - do you want to use custom zone cleaning or just room cleaning?)

**Reply by panic-Patrick** [reply]
I just want to select one or multiple rooms

**Reply by PiotrMachowski** [reply]
Please post your config here, I will try to prepare some guide for you

**Reply by panic-Patrick** [reply]
That's the config if the vacuum card.
 ```
type: custom:xiaomi-vacuum-map-card
entity: vacuum.dirt_vader
vacuum_platform: DeebotUniverse/Deebot-4-Home-Assistant
map_source:
  camera: image.dirt_vader_karte
map_modes: null
```

**Reply by PiotrMachowski** [reply, marked as answer]
1. Create a second card with this config:
   ```yaml
    type: custom:xiaomi-vacuum-map-card
    entity: vacuum.dirt_vader
    vacuum_platform: Setup integer
    map_source:
      camera: image.dirt_vader_karte
    calibration_source:
      identity: true
    ```
2. Keep the card in edit mode and use map mode "Path" to create outlines for every room on the map (click on the map to create an outline, click "copy selection" when you are done for this room and move on to the next one)
3. Use the outlines in the main config to mark every room:
    ```yaml
    type: custom:xiaomi-vacuum-map-card
    entity: vacuum.dirt_vader
    vacuum_platform: DeebotUniverse/Deebot-4-Home-Assistant
    map_source:
      camera: image.dirt_vader_karte
    calibration_source:
      identity: true
    map_modes:
      - template: vacuum_clean_segment
        predefined_selections:
          - id: 14
            outline: [[ 214, 321 ], [ 242, 321 ], [ 241, 274 ], [ 231, 274 ]]
            label:
              text: "Bedroom"
              x: 229
              y: 303
              offset_y: 35
            icon:
              name: "mdi:bed"
              x: 229
              y: 303
          - id: 19
            outline: [[ 214, 272 ], [ 230, 272 ], [ 230, 256 ], [ 214, 256 ]]
            label:
              text: "Bathroom"
              x: 222
              y: 264
              offset_y: 35
            icon:
              name: "mdi:shower"
              x: 22282
              y: 26496
    ```
4. Remember to provide correct IDs of every room (they have to match ones generated by the vacuum)
