### DISCUSSION TITLE
Icon mapping in tiles

### DISCUSSION THREAD

**Discussion by panic-Patrick** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#797] [Q&A] [answered]
I have the problem that the icon mapping in the tiles is not working. What could be the reason for this?
``` 
tiles:
  - tile_id: wasserdurchfluss
    entity: select.dirt_vader_wasserdurchfluss
    label: Feuchtigkeit
    icon_mapping: 
      low: "mdi:water-minus"
      medium: "mdi:water"
      high: "mdi:water-plus"
      ultrahigh: "mdi:water-alert"
    icon: mdi:water

**Comment by PiotrMachowski** [comment]
There is no icon mapping functionality for tiles, just for icons

**Reply by panic-Patrick** [reply]
Is there another way to implement this?

**Reply by PiotrMachowski** [reply, marked as answer]
This one should work:
```yaml
tiles:
  - tile_id: wasserdurchfluss_low
    entity: select.dirt_vader_wasserdurchfluss
    label: Feuchtigkeit
    conditions:
      - entity: select.dirt_vader_wasserdurchfluss
        value: low
    icon: mdi:water-minus
  - tile_id: wasserdurchfluss_medium
    entity: select.dirt_vader_wasserdurchfluss
    label: Feuchtigkeit
    conditions:
      - entity: select.dirt_vader_wasserdurchfluss
        value: medium
    icon: mdi:water
  - tile_id: wasserdurchfluss_high
    entity: select.dirt_vader_wasserdurchfluss
    label: Feuchtigkeit
    conditions:
      - entity: select.dirt_vader_wasserdurchfluss
        value: high
    icon: mdi:water-plus
  - tile_id: wasserdurchfluss_ultrahigh
    entity: select.dirt_vader_wasserdurchfluss
    label: Feuchtigkeit
    conditions:
      - entity: select.dirt_vader_wasserdurchfluss
        value: ultrahigh
    icon: mdi:water-alert
```
