### DISCUSSION TITLE
HA 2025.3.0 core Roborock integration and Xiaomi vacuum map card

### DISCUSSION THREAD

**Discussion by poudenes** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#804] [Q&A] [answered]
Hi All,

I was using the custom integration for Roborock vacuum. But with HA 2025.3.0 this is not working. On Github of the integration it's also saying that you have to use the core integration.

Ok... removed it, reboot, add the core integration and now the vacuum map is broken.... Because they integration is using an image instead of a camera.

Now you can use vacuum map extractor to get a camera entity.... now I have a issue.

My roborock S8 is within a Roborock account in a Roborock iOS app.
I don't use Xiaomi Home app..

How can I solve this issue so I can happily use Vacuum Map Card again?

Thanks
Peter

**Comment by PiotrMachowski** [comment, marked as answer]
You can just put the image entity instead of camera entity in yaml.

Related issues: https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/691, https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/754#issuecomment-2394958982

**Comment by poudenes** [comment]
How to solve the error with calibration points?

<img width="508" alt="Screenshot 2025-03-06 at 18 31 18" src="https://github.com/user-attachments/assets/c0d2bee9-f3e7-4a33-873f-16145256286f" />



```
type: vertical-stack
cards:
  - type: vertical-stack
    title: Cleaning map
    cards:
      - type: custom:xiaomi-vacuum-map-card
        map_source:
          camera: image.roborock_s8_map_0
          crop:
            top: 200
            bottom: 140
            left: 185
            right: 215
        calibration_source:
          camera: true
        entity: vacuum.roborock_s8
        identity: true
        platform: humbertogontijo/homeassistant-roborock
        tiles: []
        icons: []
        map_modes:
          - name: Path
            icon: mdi:map-marker-path
            run_immediately: false
            coordinates_rounding: true
            coordinates_to_meters_divider: 1000
            selection_type: MANUAL_PATH
            max_selections: 999
            repeats_type: NONE
            max_repeats: 1
            service_call_schema:
              service: script.vacuum_follow_path
              service_data:
                service: roborock.vacuum_goto
                mode: individual
                path: "[[selection]]"
                entity_id: "[[entity_id]]"
            predefined_selections: []
            variables: {}
          - name: Zone cleanup
            icon: mdi:select-drag
            run_immediately: false
            coordinates_rounding: true
            coordinates_to_meters_divider: 1000
            selection_type: MANUAL_RECTANGLE
            max_selections: 5
            repeats_type: EXTERNAL
            max_repeats: 3
            service_call_schema:
              service: roborock.vacuum_clean_zone
              service_data:
                zone: "[[selection]]"
                repeats: "[[repeats]]"
                entity_id: "[[entity_id]]"
            predefined_selections: []
            variables: {}
          - name: Pin & Go
            icon: mdi:map-marker-plus
            run_immediately: false
            coordinates_rounding: true
            coordinates_to_meters_divider: 1000
            selection_type: MANUAL_POINT
            max_selections: 999
            repeats_type: NONE
            max_repeats: 1
            service_call_schema:
              service: roborock.vacuum_goto
              service_data:
                x_coord: "[[point_x]]"
                y_coord: "[[point_y]]"
                entity_id: "[[entity_id]]"
            predefined_selections: []
            variables: {}
          - name: Rooms
            icon: mdi:floor-plan
            run_immediately: false
            coordinates_rounding: true
            coordinates_to_meters_divider: 1000
            selection_type: ROOM
            max_selections: 999
            repeats_type: EXTERNAL
            max_repeats: 3
            service_call_schema:
              service: roborock.vacuum_clean_segment
              service_data:
                segments: "[[selection]]"
                entity_id: "[[entity_id]]"
                repeats: "[[repeats]]"
            predefined_selections:
              - id: "16"
                icon:
                  name: mdi:broom
                  x: 20750
                  "y": 21500
                label:
                  text: Room 16
                  x: 20750
                  "y": 21500
                  offset_y: 35
                outline:
                  - - 19200
                    - 20500
                  - - 22300
                    - 20500
                  - - 22300
                    - 22500
                  - - 19200
                    - 22500
              - id: "17"
                icon:
                  name: mdi:broom
                  x: 19875
                  "y": 19125
                label:
                  text: Room 17
                  x: 19875
                  "y": 19125
                  offset_y: 35
                outline:
                  - - 19200
                    - 17750
                  - - 20550
                    - 17750
                  - - 20550
                    - 20500
                  - - 19200
                    - 20500
              - id: "18"
                icon:
                  name: mdi:broom
                  x: 20350
                  "y": 26400
                label:
                  text: Room 18
                  x: 20350
                  "y": 26400
                  offset_y: 35
                outline:
                  - - 18400
                    - 25700
                  - - 22300
                    - 25700
                  - - 22300
                    - 27100
                  - - 18400
                    - 27100
              - id: "19"
                icon:
                  name: mdi:broom
                  x: 24150
                  "y": 24075
                label:
                  text: Room 19
                  x: 24150
                  "y": 24075
                  offset_y: 35
                outline:
                  - - 22300
                    - 21450
                  - - 26000
                    - 21450
                  - - 26000
                    - 26700
                  - - 22300
                    - 26700
              - id: "20"
                icon:
                  name: mdi:broom
                  x: 20175
                  "y": 24025
                label:
                  text: Room 20
                  x: 20175
                  "y": 24025
                  offset_y: 35
                outline:
                  - - 18000
                    - 22450
                  - - 22350
                    - 22450
                  - - 22350
                    - 25600
                  - - 18000
                    - 25600
              - id: "21"
                icon:
                  name: mdi:broom
                  x: 23600
                  "y": 19600
                label:
                  text: Room 21
                  x: 23600
                  "y": 19600
                  offset_y: 35
                outline:
                  - - 21200
                    - 17000
                  - - 26000
                    - 17000
                  - - 26000
                    - 22200
                  - - 21200
                    - 22200
              - id: "22"
                icon:
                  name: mdi:broom
                  x: 18675
                  "y": 22075
                label:
                  text: Room 22
                  x: 18675
                  "y": 22075
                  offset_y: 35
                outline:
                  - - 18250
                    - 21700
                  - - 19100
                    - 21700
                  - - 19100
                    - 22450
                  - - 18250
                    - 22450
            variables: {}
        two_finger_pan: true
        map_locked: true
        additional_presets: []
        vacuum_platform: humbertogontijo/homeassistant-roborock
      - type: vertical-stack
        title: Roborock and motion detection
        cards:
          - type: entities
            entities:
              - entity: vacuum.roborock_s8
              - entity: sensor.roborock_s8_current_room
```
