### DISCUSSION TITLE
Create a snapshot of the image entity

### DISCUSSION THREAD

**Discussion by poudenes** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#805] [General]
Hi All,

Wit custom roborock integration I used this:

```
  actions:
    - action: camera.snapshot
      target:
        entity_id: camera.roborock_s8_map
      data:
        filename: "/config/www/snapshot/vacuum.jpg"
```
When there is a error it send a image to my mobile so I can see where the issue is.

Now with the core integration its a image but this is not work:

```
  actions:
    - action: image.snapshot
      target:
        entity_id: image.roborock_s8_map
      data:
        filename: "/config/www/snapshot/vacuum.jpg"
```
