### DISCUSSION TITLE
How to set zones for Deebot

### DISCUSSION THREAD

**Discussion by dllfpp** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#808] [Q&A]
### Checklist

- [x] I have updated the card to the latest version available
- [x] I have cleared the cache of my browser
- [x] I have checked if the problem is already reported

### The problem

Hello, this is more of a distress call than an issue report, sorry.
I have this as my setup:

![Image](https://github.com/user-attachments/assets/634382b7-2cdb-4d17-ac63-ef632300c4aa)

![Image](https://github.com/user-attachments/assets/6e831392-00ad-4ce5-b8d2-3e84fcfa743e)

How can I link these attributes, which reflect my zones in the app, in the card so that if I chose the zone it automatically binds the corresponding area?

![Image](https://github.com/user-attachments/assets/f1950c7f-5dcb-4de1-a404-d05cfb5d82c1)
I know already which room is which zone in my house so it's not a problem matching them accordingly.

### What version of a card has described problem?

2.2.4

### What vacuum model do you have problems with?

DEEBOT N8 PRO+ (ifbw08)

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/ecovacs

### What browser (browsers/apps) does have this problem?

Edge/iOS app/Firefox

### What version of Home Assistant do you use?

core-2025.3.1

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
language: it
entity: vacuum.cenerentola
vacuum_platform: DeebotUniverse/Deebot-4-Home-Assistant
map_source:
  camera: image.cenerentola_map
map_locked: true
two_finger_pan: true
map_modes:
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 0
        icon:
          name: mdi:door
          label: Ingresso/Corridoio
          x: -8500
          "y": -11500
      - id: 1
        icon:
          name: mdi:knife
          label: Cucina
          x: -1000
          "y": -15000
      - id: 2
        icon:
          name: mdi:sofa
          label: Salotto
          x: -2900
          "y": -3000
      - id: 3
        icon:
          name: mdi:table-chair
          label: Sala da pranzo
          x: -2900
          "y": -9000
      - id: 4
        icon:
          name: mdi:bed
          label: Camera
          x: -15200
          "y": 0
      - id: 5
        icon:
          name: mdi:bed
          label: Cameretta
          x: -15200
          "y": -9000
      - id: 6
        icon:
          name: mdi:toilet
          label: Bagno Padronale
          x: -9000
          "y": 2200
      - id: 6
        icon:
          name: mdi:toilet
          label: Bagno Ospiti
          x: -17000
          "y": -14700
  - template: vacuum_clean_zone
  - template: vacuum_clean_zone_predefined
    predefined_selections:
      - zones:
          - - 239
            - 184
            - 1336
            - 665
        icon:
          name: mdi:rectangle
          x: -8500
          "y": -11500
```

### Javascript errors shown in the browser's console (if applicable)

```shell

```

**Comment by PiotrMachowski** [comment]
So what does happen when you start a room cleaning?

**Reply by dllfpp** [reply]
What do you exactly mean by this?
Do you mean if I select one of the rooms identified in 
```yaml
map_modes:
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 0
        icon:
          name: mdi:door
          label: Ingresso/Corridoio
          x: -8500
          "y": -11500
```

etcc?

Like these two, for example?
![immagine](https://github.com/user-attachments/assets/4699b89e-afd4-49a5-8854-3926676c42bc)

**Reply by PiotrMachowski** [reply]
Yes, you select two rooms and click the yellow "play" button

**Comment by dllfpp** [comment]
On top of this, this happens when I click on the + button for Zone cleanup:
![immagine](https://github.com/user-attachments/assets/53c93f23-b573-4a10-8b5f-a42845fca3b8)

**Reply by PiotrMachowski** [reply]
To be honest it seems that there's something generally wrong with your config... Also, the vacuum platform you have selected has been made for [this custom integration](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant), not the built-in one, so not all features might work correctly.

**Reply by dllfpp** [reply]
Can you help here maybe a little?
Also, in custom integration has been deprecated in favor of the official one, wouldn’t be it an opportunity to adapt the platform to be chosen so it’s compatible with the core integration from HA?
Thanks.🙏

**Reply by PiotrMachowski** [reply]
Sure, but in order to add support for this integration I need some data. First of all, have you succeeded to start room cleaning from HA?

**Reply by dllfpp** [reply]
Sure, when clicking on the kitchen icon (top right knife icon), robot went cleaning the whole dining area:
![image](https://github.com/user-attachments/assets/60bb438a-96a5-473a-8f32-088a4896d5fc)

**Reply by PiotrMachowski** [reply]
Ok, so the room cleaning with the card works correctly, but you have used incorrect IDs - they shouldn't be just consecutive numbers, they should be the same as the ones used by the vacuum:
![image](https://github.com/user-attachments/assets/8d864273-cef5-4c13-a3f0-bab5444dbb4b)

**Reply by dllfpp** [reply]
This now works!

**Reply by PiotrMachowski** [reply]
Ok, so what does not work at this moment?

**Reply by dllfpp** [reply]
Hello, sorry for the delay.
What is not working is the GUI.
On iPhone I can create the manual area (but not on computer), on the other hands, room icons are positioned correctly on computer but completely messed up on iPhone.

**Reply by PiotrMachowski** [reply]
Can you show the full current card's config and all attributes of this entity `image.cenerentola_map` (from dev tools)?

**Comment by dllfpp** [comment]
Sure!

Card:
```yaml
type: custom:xiaomi-vacuum-map-card
language: en
entity: vacuum.cenerentola
vacuum_platform: DeebotUniverse/Deebot-4-Home-Assistant
map_source:
  camera: image.cenerentola_map
map_locked: true
two_finger_pan: true
map_modes:
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 2
        icon:
          name: mdi:door
          label: Ingresso/Corridoio
          x: -8500
          "y": -11500
      - id: 0
        icon:
          name: mdi:knife
          label: Cucina
          x: -1000
          "y": -15000
      - id: 1
        icon:
          name: mdi:sofa
          label: Salotto
          x: -2900
          "y": -5000
      - id: 7
        icon:
          name: mdi:bed
          label: Camera
          x: -15200
          "y": 0
      - id: 5
        icon:
          name: mdi:bed
          label: Cameretta
          x: -15200
          "y": -9000
      - id: 8
        icon:
          name: mdi:toilet
          label: Bagno Padronale
          x: -9000
          "y": 2200
      - id: 3
        icon:
          name: mdi:toilet
          label: Bagno Ospiti
          x: -17000
          "y": -14700
  - template: vacuum_clean_zone
  - template: vacuum_clean_zone_predefined
    predefined_selections:
      - zones:
          - - 239
            - 184
            - 1336
            - 665
        icon:
          name: mdi:rectangle
          x: -8500
          "y": -11500
```

Attributes:
![immagine](https://github.com/user-attachments/assets/483640a5-e759-4606-ac37-e2d3b33b8ec5)

**Reply by PiotrMachowski** [reply]
Can you try adding this to your config?
```yaml
calibration_source:
  calibration_points:
    - vacuum:
        x: 0
        "y": 0
      map:
        x: 400
        "y": 400
    - vacuum:
        x: 6400
        "y": 0
      map:
        x: 528
        "y": 400
    - vacuum:
        x: 0
        "y": 6400
      map:
        x: 400
        "y": 528
```
