### DISCUSSION TITLE
Map zoom status is not saved

### DISCUSSION THREAD

**Discussion by z-master42** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#824] [Q&A] [answered]
Hello,

you can zoom in and move the map and then lock the map against further changes.

Unfortunately, these settings are only saved as long as the page is not reloaded in a browser, for example. Even in the Companion app, the settings are gone at the latest when you reopen the app.

Is that how it is intended? Is there a way to save these settings permanently?

**Comment by PiotrMachowski** [comment, marked as answer]
Yes, the map zoom level is not saved at this moment. You can configure cropping instead, but it also doesn't work perfectly:

```yaml
map_source:
  camera: camera.xiaomi_cloud_map_extractor
  crop:
    top: 30
    right: 50
    bottom: 314
    left: 101
```
