### DISCUSSION TITLE
(Roborock) Changing the "play" start button to a list that has the standard service call, but all has a list of presets

### DISCUSSION THREAD

**Discussion by bobloadmire** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#826] [Q&A] [answered]
The roborock integration exposes all of my presets, e.g. "Clean Kitchen and Living Room Only" and it exposes these presets via a button. so while the standard config is the play button to start regular cleaning, i'd like to change that button to be like the Fan Speed list, but expose a list like "1. Clean. 2. Preset One 3. Preset Two" etc. I looked how the fan speed list was setup, but i'm pretty confused on how you call the list popup when tapped, and then how to make the list to call service or press the button (for the preset buttons). I tried:

```yaml
tap_action:
      action: perform-action
      perform_action: button.press
      target:
        entity_id: button.roborock_s8_pro_ultra_kitchen-livingroom
```

and this doesn't work in this card. I tried it with the standard home assistant entity card and it works fine.

**Comment by PiotrMachowski** [comment, marked as answer]
This card uses the old yaml naming, so it has to look the following way:
```yaml 
    tap_action:
      action: call-service
      service: button.press
      service_data:
        entity_id: button.roborock_s8_pro_ultra_kitchen-livingroom
```

The config that does what you want looks like this:
```yaml
icons:
  - menu_id: cleaning_menu
    icon: mdi:play
    label: Start cleaning
    tap_action:
      action: call-service
      service: vacuum.start
      service_data:
        entity_id: vacuum.alfred
  - menu_id: cleaning_menu
    icon: mdi:pot-mix
    label: Clean Kitchen
    tap_action:
      action: call-service
      service: button.press
      service_data:
        entity_id: button.roborock_s8_pro_ultra_kitchen
  - menu_id: cleaning_menu
    icon: mdi:bathtub
    label: Clean Bathroom
    tap_action:
      action: call-service
      service: button.press
      service_data:
        entity_id: button.roborock_s8_pro_ultra_bathroom
  - menu_id: cleaning_menu
    icon: mdi:bed
    label: Clean Bedroom
    tap_action:
      action: call-service
      service: button.press
      service_data:
        entity_id: button.roborock_s8_pro_ultra_bedroom
```
There might be some bugs in colors though
