### DISCUSSION TITLE
Pre select multiple rooms

### DISCUSSION THREAD

**Discussion by Dazzler583** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#829] [Q&A] [answered]
I am using  a Roborock Q5 Pro with your card and it works well but I would like t be able to  have a "whole house" option. Is I possible to pre-select muliple rooms so that all the user has to do is press the play button?
my code is:
```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: image.q5_pro_map_0_custom
calibration_source:
  camera: true
entity: vacuum.q5_pro
vacuum_platform: Roborock
map_modes:
  - name: Pick a Room
    icon: mdi:floor-plan
    run_immediately: false
    coordinates_rounding: true
    coordinates_to_meters_divider: 1000
    selection_type: ROOM
    id_type: number
    max_selections: 999
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: vacuum.send_command
      service_data:
        command: app_segment_clean
        params:
          - segments: "[[selection]]"
            repeats: "[[repeats]]"
        entity_id: "[[entity_id]]"
    predefined_selections:
      - id: "16"
        icon:
          name: mdi:broom
          x: 27750
          "y": 28350
        label:
          text: Living room
          x: 27750
          "y": 28350
          offset_y: 35
        outline:
          - - 20150
            - 22200
          - - 35350
            - 22200
          - - 35350
            - 34500
          - - 20150
            - 34500
      - id: "17"
        icon:
          name: mdi:broom
          x: 25275
          "y": 21000
        label:
          text: Bedroom
          x: 25275
          "y": 21000
          offset_y: 35
        outline:
          - - 21350
            - 18950
          - - 29200
            - 18950
          - - 29200
            - 23050
          - - 21350
            - 23050
      - id: "18"
        icon:
          name: mdi:broom
          x: 19575
          "y": 19925
        label:
          text: Master bedroom
          x: 19575
          "y": 19925
          offset_y: 35
        outline:
          - - 17450
            - 16550
          - - 21700
            - 16550
          - - 21700
            - 23300
          - - 17450
            - 23300
      - id: "19"
        icon:
          name: mdi:broom
          x: 19200
          "y": 24225
        label:
          text: Bathroom
          x: 19200
          "y": 24225
          offset_y: 35
        outline:
          - - 17450
            - 23200
          - - 20950
            - 23200
          - - 20950
            - 25250
          - - 17450
            - 25250
    variables: {}
  - name: Whole House
    icon: mdi:floor-plan
    run_immediately: false
    coordinates_rounding: true
    coordinates_to_meters_divider: 1000
    selection_type: ROOM
    id_type: number
    max_selections: 999
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: vacuum.send_command
      service_data:
        command: app_segment_clean
        params:
          - segments: "-16 -17 -18 -19"
            repeats: "[[repeats]]"
        entity_id: "[[entity_id]]"
    predefined_selections:
      - id: "16"
        icon:
          name: mdi:broom
          x: 27750
          "y": 28350
        label:
          text: Living room
          x: 27750
          "y": 28350
          offset_y: 35
        outline:
          - - 20150
            - 22200
          - - 35350
            - 22200
          - - 35350
            - 34500
          - - 20150
            - 34500
      - id: "17"
        icon:
          name: mdi:broom
          x: 25275
          "y": 21000
        label:
          text: Bedroom
          x: 25275
          "y": 21000
          offset_y: 35
        outline:
          - - 21350
            - 18950
          - - 29200
            - 18950
          - - 29200
            - 23050
          - - 21350
            - 23050
      - id: "18"
        icon:
          name: mdi:broom
          x: 19575
          "y": 19925
        label:
          text: Master bedroom
          x: 19575
          "y": 19925
          offset_y: 35
        outline:
          - - 17450
            - 16550
          - - 21700
            - 16550
          - - 21700
            - 23300
          - - 17450
            - 23300
      - id: "19"
        icon:
          name: mdi:broom
          x: 19200
          "y": 24225
        label:
          text: Bathroom
          x: 19200
          "y": 24225
          offset_y: 35
        outline:
          - - 17450
            - 23200
          - - 20950
            - 23200
          - - 20950
            - 25250
          - - 17450
            - 25250
    variables: {}
  - name: Clean a Spot
    icon: mdi:map-marker-plus
    run_immediately: false
    coordinates_rounding: true
    coordinates_to_meters_divider: 1000
    selection_type: MANUAL_POINT
    max_selections: 999
    repeats_type: NONE
    max_repeats: 1
    service_call_schema:
      service: roborock.set_vacuum_goto_position
      service_data:
        x: "[[point_x]]"
        "y": "[[point_y]]"
        entity_id: "[[entity_id]]"
    predefined_selections: []
    variables: {}
```

**Comment by PiotrMachowski** [comment, marked as answer]
Generally normal "full cleaning" is available using this button:
![image](https://github.com/user-attachments/assets/e3fb5215-9828-4220-98c5-efdf882ace46)

If you want to do it using room cleaning and the map view then you can use `default_state` property:
```yaml
    predefined_selections:
      - id: "16"
        default_state: selected
        icon:
          name: mdi:broom
          x: 27750
          "y": 28350
        label:
          text: Living room
          x: 27750
          "y": 28350
          offset_y: 35
        outline:
          - - 20150
            - 22200
          - - 35350
            - 22200
          - - 35350
            - 34500
          - - 20150
            - 34500
      - id: "17"
        default_state: selected
        icon:
          name: mdi:broom
          x: 25275
          "y": 21000
        label:
          text: Bedroom
        ...
```
