### ISSUE TITLE
Robot does not actually vacuum when using this card

### ISSUE THREAD

**Issue by auanasgheps** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#110]
Hello,
I have a Xiaomi Mi Robot 1S. I've done the full integration (and I've also added zones. Everything looks good.

However, when I issue the command to clean a zone, the robot goes there, cover the zone **but does not vacuum**. If I open the mobile app and switch fan speed, it will start the vacuum engine, but just for the session.

I haven't found an option to specify the fan speed, I guess it should use whatever is set (medium in my case).

Am I missing something? Not sure if it's even related to this card or to the Miio Integration.

![image](https://user-images.githubusercontent.com/20586878/121692936-e8076200-cac8-11eb-8596-12ba13863456.png)

```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.totor_o_spazzator
map_camera: camera.xiaomi_cloud_map_extractor
camera_calibration: true
default_mode: predefined_zones
zones:
  - - - 24250
      - 21800
      - 28550
      - 26400
  - - - 28550
      - 22600
      - 30100
      - 26000
  - - - 30100
      - 21700
      - 35350
      - 26300
```
