### ISSUE TITLE
Feature request: Zoom

### ISSUE THREAD

**Issue by mihalski** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#123]
I am using the automatic cloud map extractor and the map it returns has a border around it making it rather small.

![image](https://user-images.githubusercontent.com/3755059/127078905-84f00066-ec9d-4336-8898-07ccaa221d4d.png)

Some way to autosize to the lovelace view or specify a zoom would be helpful.

Thank you for your awesome work.

Regards,
Michal

EDIT: Discovered I could solve it at the map extractor end by adding the folowing to my config:
```yaml
    map_transformation:
      trim:
        top: 25
        bottom: 25
        left: 15
        right: 15
```
Now it looks like this:
![image](https://user-images.githubusercontent.com/3755059/127080508-6c276b44-7f62-4032-9fda-838ceb294299.png)

Hope this helps someone else.
