### ISSUE TITLE
Empty values in debug mode. roidmi.vacuum.v60

### ISSUE THREAD

**Issue by oembsod** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#128]
Hi.
Problem with roidmi.vacuum.v60 (rockrobo.vacuum.v1 worked fine)

Configuring xiaomi_cloud_map_extractor
```
- platform: xiaomi_cloud_map_extractor
   host:! secret roidmi_vacuum_host
   token:! secret roidmi_vacuum_token
   username:! secret mi_login
   password:! secret mi_password
   name: vacuum_cam_roidmi
   country: ru
   draw: ["all"]
   scan_interval:
     seconds: 10
   auto_update: true
   store_map_raw: true
   store_map_image: false
   store_map_path: "/tmp"
   force_api: roidmi
   attributes:
     - calibration_points
```

Configuring xiaomi-vacuum-map-card
```
type: custom: xiaomi-vacuum-map-card
entity: vacuum.roidmi_v60_04f1_robot_cleaner
map_camera: camera.vacuum_cam_roidmi
camera_calibration: true
debug: true
service: script.vacuum_send_command_multiple_zones
```

When I try to get any data in debug mode, I get null values.
![image](https://user-images.githubusercontent.com/16118481/138671114-576fe4c6-2a98-483d-bca4-f059bafafdd4.png)

Does the vacuum cleaner not respond when the debugger is disabled, coordinate error in the logs
**2021-10-25 12:27:18 ERROR (SyncWorker_9) [homeassistant.components.python_script.vacuum_send_command.py] Error executing script: invalid literal for int () with base 10: 'None'**
