### ISSUE TITLE
Problem in v2.0.0+ in Firefox, Safari and iOS companion app

### ISSUE THREAD

**Issue by HepoH3** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#130]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Hello, thank you for still working on this card.
Apparantly there is a problem with picking up the point / moving / resizing custom zone area in firefox browsers. In Chrome and Edge browsers that's working just fine.

Chrome:
![](https://puu.sh/IplAx/f3b6337f7e.png)
Firefox (can't set point):
![](https://puu.sh/IplBn/a2a61fac71.png)

### What version of a card has described problem?

v2.0.0

### What vacuum model do you have problems with?

STYJ02YM 

### What version of Home Assistant do you use?

2021.11.3

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
- type: custom:xiaomi-vacuum-map-card
    entity: vacuum.kraken
    map_source:
      camera: camera.vacuum_extractor_camera
    calibration_source:
      camera: true
    map_modes:
      - template: vacuum_clean_zone
      - template: vacuum_goto
    vacuum_platform: KrzysztofHajdamowicz/miio2
```

### Javascript errors shown in the browser's console (if applicable)

```shell
Uncaught ReferenceError: TouchEvent is not defined
    _drag http://homeassistant.local:8123/hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js:181
    render http://homeassistant.local:8123/hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js:150
    handleEvent http://homeassistant.local:8123/hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js:31
```

**Comment by nickdos** [comment]
Seeing similar issues on Safari and Mac OS Companion app (v.2.0.1).

I can't change move or the size of manually added zones. I can't remove a zone via the `x` either. When the map is "unlocked" and I add a manual zone, when I try to move the newly created zone, the entire map moves and not the zone. If I lock  the map then nothing happens when trying to move the zone. Click and dragging does nothing.

Similarly on the iOS companion app I can't move, resize or remove a zone added via "Zone cleanup".

**Comment by Lyr3x** [comment]
Besides that I can also confirm that the bug exists in safari and the iOS/iPadOS I just want to state that the ROOM listing is also not working. In Chrome everything runs fine

**Comment by PiotrMachowski** [comment]
There are major improvements in `v2.0.2`, most of functionalities should work.

Remaining problem: selections are not mapped correctly when map is zoomed-in

**Comment by nickdos** [comment]
Just tested v2.0.2 and Safari is working now. 

However both the iOS and Mac OS companion apps still donot show the zones. I've forced the apps to reload a few times and still not zones showing. I even edited the config to change the card display a little and the changes appeared but still no zones.

**Comment by PiotrMachowski** [comment]
@nickdos can you check if any of new feature works on iOS/Mac to make yourself sure that they use the latest release? The easiest way to do it is to add `language` to config:
```yaml
type: custom:xiaomi-vacuum-map-card
language: it
...
```
