### ISSUE TITLE
Rooms (segments) not appearing

### ISSUE THREAD

**Issue by aneisch** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#145]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

I cannot get the card to display my rooms (segments) for selection for use with `- template: vacuum_clean_segment`

### What version of a card has described problem?

2.0.1

### What vacuum model do you have problems with?

roborock_s4

### What version of Home Assistant do you use?

2011.11.4

### What type of installation are you running?

Home Assistant Container

### Card's configuration

```yaml
- type: custom:xiaomi-vacuum-map-card
    entity: vacuum.roborock_s4
    map_source:
      camera: camera.xiaomi_cloud_map_extractor
    calibration_source:
      camera: true
    map_modes:
      - template: vacuum_clean_zone
      - template: vacuum_clean_segment
      - template: vacuum_goto
```

### Additional information

Camera:
```
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 10.0.0.10
    token: !secret roborock_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
      - charger
      - cleaned_rooms
      - country
      - goto_path
      - goto_predicted_path
      - goto
      - ignored_obstacles_with_photo
      - ignored_obstacles
      - image
      - is_empty
      - map_name
      - no_go_areas
      - no_mopping_areas
      - obstacles_with_photo
      - obstacles
      - path
      - room_numbers
      - rooms
      - vacuum_position
      - vacuum_room_name
      - vacuum_room
      - walls
      - zones
    colors:
      color_path: [255, 255, 255]
```

Rooms do appear as an attribute to my camera:
```
rooms: 
'16':
  x0: 21850
  y0: 18500
  x1: 23700
  y1: 25100
'17':
  x0: 9150
  y0: 12600
  x1: 11100
  y1: 16650
'18':
  x0: 21950
  y0: 14150
  x1: 27400
  y1: 18950
... etc
```
