### ISSUE TITLE
Similar to a closed issue, missing tiles.

### ISSUE THREAD

**Issue by xac1d** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#146]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Similar to this [issue](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/135) I am only getting the Status, Battery and Fan Speed tiles. 

### What version of a card has described problem?

v2.0.1

### What vacuum model do you have problems with?

Roborock S4

### What version of Home Assistant do you use?

core-2021.11.4

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.roborock_vacuum
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_clean_zone_predefined
vacuum_platform: KrzysztofHajdamowicz/miio2
title: Roborock S4
```

### Additional information

If I select the platform as default, I lose all buttons and tiles, so I'm using miio2 which at least gives me some of the buttons and data. I have all entities enabled in HA.

![image](https://user-images.githubusercontent.com/7860722/141940549-12cdba60-9b9c-414c-92df-9b7f8a804536.png)
![image](https://user-images.githubusercontent.com/7860722/141940720-6c96bc34-20c7-4935-9996-d60d4848a79c.png)

**Comment by PiotrMachowski** [comment]
You shouldn't use `vacuum_platform: KrzysztofHajdamowicz/miio2` with built-in miio integration, they use incompatible service call schemas.

Did you have all these entities turned on before?

**Comment by xac1d** [comment]
@PiotrMachowski unfortunately, I probably buggered something up. I updated OS and core and hacs and installed the card like all in 1 shot so I'm not surprised that it's acting weird.

For a time, I had the old card and the new card side by side and the old card was showing the sensor information, but the new card wasn't. I'm sure i had the entities enabled before, but after seeing the other issue I found them disabled and i had to reenable them.

**Comment by xac1d** [comment]
was able to add the tiles manually. not sure if my math is right but seems close enough..

```
type: custom:xiaomi-vacuum-map-card
entity: vacuum.roborock_vacuum
map_source:
  camera: camera.xiaomi_cloud_map_extractor
  crop:
    top: 150
    bottom: 150
    left: 100
    right: 150
calibration_source:
  camera: true
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_follow_path
  - template: vacuum_goto
  - template: vacuum_clean_zone_predefined
vacuum_platform: default
title: Roborock S4
tiles:
  - label: Status
    entity: vacuum.roborock_vacuum
    attribute: status
    icon: mdi:robot-vacuum
  - label: Battery
    entity: vacuum.roborock_vacuum
    attribute: battery_level
    icon: mdi:battery-charging-100
    unit: '%'
  - label: Fan Speed
    icon: mdi:fan
    entity: vacuum.roborock_vacuum
    attribute: fan_speed
  - label: Sensors left
    icon: mdi:leak
    entity: sensor.roborock_vacuum_sensor_dirty_left
    multiplier: 0.00069
    precision: 0
    unit: h
  - label: Filter left
    icon: mdi:air-filter
    entity: sensor.roborock_vacuum_filter_left
    multiplier: 0.00069
    precision: 0
    unit: h
  - label: Main brush left
    icon: mdi:brush
    entity: sensor.roborock_vacuum_main_brush_left
    multiplier: 0.00069
    precision: 0
    unit: h
  - label: Side brush left
    icon: mdi:brush
    entity: sensor.roborock_vacuum_side_brush_left
    multiplier: 0.00069
    precision: 0
    unit: h
  - label: Cleaning count
    icon: mdi:counter
    entity: sensor.roborock_vacuum_total_clean_count

```
