### ISSUE TITLE
Invalid calibration

### ISSUE THREAD

**Issue by kaphwor** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#153]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

As described in title. It pops a messsage saying "Invalid calibration, please check your configuration". It was working pre v2.0.

The only log i've is "Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds".
There is no "old configuration" in the yaml file as I've removed it long ago, and it seems that this log (1 occurrence) was only a hickup as it's running every 10minutes.

I've also attempted to remove style, map_modes from my card configuration and the output is the same.

### What version of a card has described problem?

v2.0.1

### What vacuum model do you have problems with?

Roborock.vacuum.s5e

### What version of Home Assistant do you use?

core-2021.11.3

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
title: Jaqueline
preset_name: Live Map
entity: vacuum.xiaomi_vacuum_cleaner
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_follow_path
vacuum_platform: default
style: |
  ha-card {
    border-radius: 20px;
    background-color: var(--primary-background-color);
    }
```

**Comment by PiotrMachowski** [comment]
@kaphwor can you provide config of `camera.xiaomi_cloud_map_extractor`?

**Comment by kaphwor** [comment]
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_ip
    token: !secret xiaomi_token
    username: !secret xiaomi_user
    password: !secret xiaomi_pass
    colors:
      color_path: [255, 255, 255]
    draw: ['all']
    map_transformation:
      scale: 1
      trim:
        top: 20
        bottom: 20
        left: 20
        right: 20
    auto_update: true
    scan_interval:
      seconds: 600 #10minutes

**Comment by PiotrMachowski** [comment]
This one should solve the problem:
```
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_url
    token: !secret xiaomi_token
    username: !secret xiaomi_user
    password: !secret xiaomi_pass
    colors:
      color_path: [255, 255, 255]
    draw: ['all']
    map_transformation:
      scale: 1
      trim:
        top: 20
        bottom: 20
        left: 20
        right: 20
    auto_update: true
    scan_interval:
      seconds: 600 #10minutes

**Comment by kaphwor** [comment]
Yup! That solved it!!

tyvm!! :D

**Comment by TheGabeMan** [comment]
For others that stumble upon this, there is a little typo in "attibutes", the r has falen off. Took me 15min of troubleshooting to see it. I need glasses :-) :-) :-) 

>     attibutes:
>       - calibration_points
> ```

**Comment by PiotrMachowski** [comment]
@TheGabeMan whoops :D

**Comment by michalzadkowski** [comment]
Weird. I'm getting the "Invalid calibration, please check your configuration" error despite attributes: calibration_points in my camera config. Reload of the xiaomi_cloud_map_extractor in server controls section of the GUI seems to solve the problem for a brief second, then it comes back.

**Comment by PiotrMachowski** [comment]
@michalzadkowski have you checked what was the camera image even it happened?

**Comment by pannal** [comment]
> Weird. I'm getting the "Invalid calibration, please check your configuration" error despite attributes: calibration_points in my camera config. Reload of the xiaomi_cloud_map_extractor in server controls section of the GUI seems to solve the problem for a brief second, then it comes back.

Same issue over here.

**Comment by NiapApa** [comment]
Hi,

Thanks for this awesome integration! 👍 

I am able to use everything except "Rooms" when I do try i get "Invalid calibration, please check your configuration" and the Roborock.vacuum.s5e goes out for 5 sec and says "room cleaning complete" and returns to dock. I also notice my dockstation is missing on the map now?

I have tried to restart my roborock_vacuum_s5e, done a proper mapping, everything updated what I can see.. Any tips? 

camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    auto_update: true
    scan_interval:
      seconds: 10
    attributes:
      - calibration_points

https://user-images.githubusercontent.com/76902176/222988091-5d5ff9b0-3b9d-4e19-a3c2-d0e6ae3dbb5f.mp4



Thanks for any support!

**Comment by PiotrMachowski** [comment]
@NiapApa well, you have copied *my* rooms, so obviously it won't work with your map. Do not copy my config, follow [these steps](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/317) instead

**Comment by NiapApa** [comment]
@PiotrMachowski Ahh thanks - Sorry I was just testing out different configs and trying the integration out! Cheers!

**Comment by PiotrMachowski** [comment]
@NiapApa no problem, good luck :)

**Comment by Knellius** [comment]
Hi! I have same problem (

My card's configuration:

```
type: custom:xiaomi-vacuum-map-card
entity: vacuum.roborock_s7
vacuum_platform: humbertogontijo/homeassistant-roborock
title: Roborock S7
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
```

Config of camera.xiaomi_cloud_map_extractor:

```
platform: xiaomi_cloud_map_extractor
host: !secret xiaomi_vacuum_host
token: !secret xiaomi_vacuum_token
username: !secret xiaomi_cloud_username
password: !secret xiaomi_cloud_password
country: "ru"
draw: ['all']
scan_interval:
  seconds: 14400
attributes:
  - calibration_points
```

I can't figure out where I went wrong?

**Comment by PiotrMachowski** [comment]
@Knellius Is the map shown?

**Comment by PiotrMachowski** [comment]
@Knellius #422

**Comment by PiotrMachowski** [comment]
@Knellius https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues/422

**Comment by Knellius** [comment]
@PiotrMachowski 
I followed these advices, but still no luck (

**Comment by peyopeev0206** [comment]
i have the same issue. I have roborock s5, but why i try to load the map inside the Apple Mi Home app it's still not loading
Card configuration:
```
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.robot_vacuum
vacuum_platform: default
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_clean_segment
    predefined_selections:
      - id: '1'
        icon:
          name: mdi:broom
          x: 26675
          'y': 16750
        label:
          text: Bedroom
          x: 26675
          'y': 16750
          offset_y: 35
        outline:
          - - 25100
            - 14250
          - - 28250
            - 14250
          - - 28250
            - 19250
          - - 25100
            - 19250
      - id: '2'
        icon:
          name: mdi:broom
          x: 29499
          'y': 21945
        label:
          text: Hallway
          x: 29499
          'y': 21945
          offset_y: 35
        outline:
          - - 31350
            - 23408
          - - 31350
            - 19276
          - - 26917
            - 19276
          - - 26917
            - 23408
      - id: '3'
        icon:
          name: mdi:broom
          x: 28208
          'y': 27497
        label:
          text: Living Room
          x: 28208
          'y': 27497
          offset_y: 35
        outline:
          - - 31307
            - 31328
          - - 31307
            - 23408
          - - 24980
            - 23408
          - - 24980
            - 31371
map_locked: true

```

and inside the configuration.yaml

```
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ["all"]
    colors:
      color_path: [255, 255, 255]
    map_transformation:
      scale: 1
      trim:
        top: 20
        bottom: 20
        left: 20
        right: 20
    auto_update: true
    scan_interval:
      seconds: 600 #10minutes
    attributes:
      - calibration_points
      - rooms

```
