### ISSUE TITLE
Version 2 not working

### ISSUE THREAD

**Issue by TheFes** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#156]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

When upgrading to the new version, I get this error:
![image](https://user-images.githubusercontent.com/28803438/141999963-3d042999-a041-4e0c-bcdb-3a0ce5649607.png)

Which seems to be related to v1, as v2 doesn't have this setting anymore.

I've cleared all site data relating to my HA url, removed the card in HACS (and resources in lovelace settings) rebooted, and installed it again, but no luck

### What version of a card has described problem?

2.0.1

### What was the last working version card?

1.2.3

### What vacuum model do you have problems with?

roborock.vacuum.v1

### What version of Home Assistant do you use?

2021.11.3

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
- type: custom:xiaomi-vacuum-map-card
    entity: vacuum.rockrobo_vacuum_v1
    map_source:
      camera: camera.xiaomi_cloud_map_extractor
    calibration_source:
      camera: true
    map_modes:
      - template: vacuum_clean_zone
      - template: vacuum_goto
      - template: vacuum_clean_zone_predefined
        predefined_selections:
          - zones: [[24145, 22380, 28925, 25965, 1]]
          - zones: [[28906, 22304, 32795, 25946, 1]]
          - zones: [[30196, 20180, 32814, 22304, 1]]
          - zones: [[27104, 20217, 30234, 22380, 1]]
          - zones: [[24012, 20199, 27161, 22418, 1]]
```

### Javascript errors shown in the browser's console (if applicable)

```shell
card custom:xiaomi-vacuum-map-card Error: Missing configuration: map_image or map_camera
    at HTMLElement.setConfig (xiaomi-vacuum-map-card.js:77)
    at s (ha-logbook.ts:28)
    at ha-logbook.ts:28
    at d (ha-logbook.ts:28)
    at c (ha-logbook.ts:28)
    at b (ha-logbook.ts:28)
    at HTMLElement.value (hui-masonry-view.ts:44)
    at hui-masonry-view.ts:44
    at Array.map (<anonymous>)
    at HTMLElement.value (hui-masonry-view.ts:44)
```

**Comment by mdrobny** [comment]
@TheFes 
are you sure about indentations in the yaml file? `type`, `entity`, `map_source` etc should be at the same level:

```yaml
- type: custom:xiaomi-vacuum-map-card
  entity: vacuum.rockrobo_vacuum_v1
  map_source:
    camera: camera.xiaomi_cloud_map_extractor
  calibration_source:
    camera: true
  map_modes:
    - template: vacuum_clean_zone
    - template: vacuum_goto
    - template: vacuum_clean_zone_predefined
      predefined_selections:
        - zones: [[24145, 22380, 28925, 25965, 1]]
        - zones: [[28906, 22304, 32795, 25946, 1]]
        - zones: [[30196, 20180, 32814, 22304, 1]]
        - zones: [[27104, 20217, 30234, 22380, 1]]
        - zones: [[24012, 20199, 27161, 22418, 1]]

```

v2 works for me
