### ISSUE TITLE
"Internal" repeats type doesn't work

### ISSUE THREAD

**Issue by Enzokot** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#161]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

"Internal" repeats type doesn't work
![image](https://user-images.githubusercontent.com/43236573/142048426-c8c52f3c-6a48-4ef6-b8e4-650a66f1bcd4.png)

### What version of a card has described problem?

2.0.1

### What vacuum model do you have problems with?

roborock.vacuum.s5

### What version of Home Assistant do you use?

core-2021.11.4

### What type of installation are you running?

Home Assistant Supervised

### Card's configuration

```yaml
- name: Rooms
  icon: mdi:floor-plan
  selection_type: ROOM
  max_selections: 8
  repeats_type: INTERNAL
  max_repeats: 3
  service_call_schema:
    service: script.vacuum_follow_path #create notification for debug
    service_data:
      path: "[[selection]]"
      entity_id: "[[entity_id]]"
```

**Comment by PiotrMachowski** [comment]
Actually it works, just not with `selection_type: ROOM`. I thought it will be useless, so I have skipped it. Anyway, I will add it in the next version 👍

**Comment by Enzokot** [comment]
As a suggestion. May be repeat count for each room?

**Comment by PiotrMachowski** [comment]
Separate repeat counter for each room is a tricky thing to do, maybe someday 🙂 Right now I can add a common counter for all rooms

**Comment by PiotrMachowski** [comment]
Resolved in v2.0.2

**Comment by Enzokot** [comment]
Thanks!

**Comment by Mr-Groch** [comment]
I think it still doesn't work...

My conf:
```
map_modes:
  - template: vacuum_clean_segment
    repeats_type: INTERNAL
    max_repeats: 3
    predefined_selections:
```

When I select room and set repeat >1 it stills clean that room once...
