### ISSUE TITLE
Map rotate causes issues with zone cleaning

### ISSUE THREAD

**Issue by PiotrMachowski** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#173]
### Discussed in https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/172

<div type='discussions-op-text'>

<sup>Originally posted by **geezer54** November 17, 2021</sup>
First, I wanted to say how impressed I am with your new card.  Its quite a significant upgrade from your previous release!

When the map is rotated 90% via [Xiaomi-Cloud-Map-Extractor config](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#map-transformation-configuration), the selection box in zone cleaning does not work correctly. Mouse movement up causes selection box lower edge to move down and vice versa.  Also, the x,y coordinates appear to be exchanged.  FYI:  I'm using chrome browser on Windows 10.

https://user-images.githubusercontent.com/67194877/142241761-f3f7a701-3cb2-4473-9518-eeae0528dba3.mp4
</div>

**Comment by Heisenberg2980** [comment]
Following. Same issue here with map rotated 180 degrees

**Comment by jacekpaszkowski** [comment]
I have same issue but with my camera map - images generated from ValetudoRE

![2021-11-21_15h26_50](https://user-images.githubusercontent.com/4264991/142772067-cd01d48a-73b8-43cf-88bf-ba1e23d2a409.gif)
E

**Comment by PiotrMachowski** [comment]
I already have a solution, it will be included in the next release.

@jacekpaszkowski what is your setup to make card work with valetudo?

**Comment by jacekpaszkowski** [comment]
My vacuum is connected via standard HA integration and also via Valetudo RE MQTT. I'm also able to read predefined zones from sensor using `custom:config-template-card`
Have to use both because of problems eg. with fan speed :(

Still work in progress, but most of all works okey

```yaml
type: custom:config-template-card
    variables:
      zones: >-
        states['sensor.rockrobo_valetudo_zones_processed'].attributes['predefined_selections']
    entities:
      - sensor.rockrobo_valetudo_zones_processed
      - vacuum.xiaomi_vacuum_cleaner
      - camera.rockrobo_map
      - vacuum.rockrobo
    card:
      type: custom:xiaomi-vacuum-map-card
      entity: vacuum.xiaomi_vacuum_cleaner
      map_source:
        camera: camera.rockrobo_map
      language: pl
      vacuum_platform: send_command
      calibration_source:
        calibration_points:
          - vacuum:
              x: 25210
              'y': 19057
            map:
              x: 35
              'y': 20
          - vacuum:
              x: 25210
              'y': 27625
            map:
              x: 35
              'y': 1035
          - vacuum:
              x: 35388
              'y': 27625
            map:
              x: 1255
              'y': 1035
      map_modes:
        - name: Pokoje
          icon: mdi:floor-plan
          selection_type: PREDEFINED_RECTANGLE
          max_selections: 5
          coordinates_rounding: true
          repeats_type: EXTERNAL
          max_repeats: 3
          service_call_schema:
            service: pyscript.rockrobo_start_predefined_zone_cleaning
            service_data:
              coordinates: '[[selection]]'
              repeats: '[[repeats]]'
              vacuum: vacuum.rockrobo
          predefined_selections: ${zones}
        - name: Idź do punktu
          icon: mdi:crosshairs-gps
          selection_type: MANUAL_POINT
          coordinates_rounding: true
          service_call_schema:
            service: pyscript.rockrobo_goto
            service_data:
              coordinates: '[[selection]]'
              vacuum: '[[entity_id]]'
        - template: vacuum_clean_zone
      append_icons: true
      icons:
        - icon: mdi:home
          tooltip: Sprzątanie całego mieszkania
          tap_action:
            service: input_select.select_option
            service_data:
              entity_id: input_select.vacuum_room
              option: Wszystkie
        - icon: mdi:delete-empty
          tooltip: Podjedź do kosza
          service: script.roborock_go_to_empty_bin
      append_tiles: true
      tiles:
        - entity: vacuum.rockrobo
          label: Filtr
          attribute: filter
          icon: mdi:air-filter
          unit: h
        - entity: vacuum.rockrobo
          label: Sensor
          attribute: sensor
          icon: mdi:eye
          unit: h
        - entity: vacuum.rockrobo
          label: Główna
          attribute: mainBrush
          icon: mdi:brush-variant
          unit: h
        - entity: vacuum.rockrobo
          label: Boczna
          attribute: mainBrush
          icon: mdi:brush
          unit: h
        - entity: sensor.vacuum_hours_from_last_bin_out_time
          label: Opróżnianie
          icon: mdi:delete-empty
          unit: h
        - entity: sensor.vacuum_cleaned_area
          label: Powierzchnia
          unit: m²
        - entity: sensor.vacuum_cleaning_time
          label: Trwało
          unit: m
        - entity: sensor.vacuum_time_from_last_cleanup
          label: Minęło
        - entity: sensor.vacuum_time_to_next_automatic_cleanup
          label: Następne
        - entity: sensor.vacuum_area_cleaned_since_last_bin_emptying
          label: Opróżniano
          unit: m²
        - entity: vacuum.rockrobo
          label: Liczba sprzątań
          attribute: cleanCount
          icon: mdi:counter
```

**Comment by PiotrMachowski** [comment]
@jacekpaszkowski I have to add Valetudo to supported platforms, can you show me what services does it use?

**Comment by PiotrMachowski** [comment]
This issue should be fixed in v2.0.3
@geezer54 @Heisenberg2980 @jacekpaszkowski can you confirm it's working?

**Comment by jacekpaszkowski** [comment]
For me ok.

I use Valetudo**RE** not original Valetudo. In HA it works as Mqtt Vacuum, here you can find list of serwices, and custom ``send_comand`` commands.
Unfortuantelly Mqtt it doesn't support "goto" and "zoned_cleanup" to given coordintes, only to named zones and spots defined in Valetudo settings.

So for "goto" and "zoned_cleanup" with coordinates from your map i have to use xiaomi_miio entity with "translated" coordinates

**Comment by wowgamr** [comment]
Hello!
Is it the same problem? My map rotated by 180 degrees and i can't select zone.
![image](https://user-images.githubusercontent.com/4518407/142863084-092ee485-b13a-4df4-85f5-81233c54b81d.png)

**Comment by Heisenberg2980** [comment]
> This issue should be fixed in v2.0.3 @geezer54 @Heisenberg2980 @jacekpaszkowski can you confirm it's working?

Updated to v2.0.3 and it is working now, thanks!!

**Comment by PiotrMachowski** [comment]
@wowgamr I am pretty sure you have an old version of the card, update to v2.0.3 should fix it

**Comment by wowgamr** [comment]
Same issue on v2.0.3 :(
There is an error in console:
![image](https://user-images.githubusercontent.com/4518407/142866386-24177182-b995-472f-8b28-3e5f4117aeca.png)

**Comment by NikiHard** [comment]
I have no calibration points
`camera:
  - platform: xiaomi_cloud_map_extractor
    host: host
    token: token
    username: username
    password: password
    country: "ru"
    draw: ['all']
    attributes:
      - calibration_points 
    map_transformation:
      rotate: 180
      trim:
        top: 25
        bottom: 20
        left: 15
        right: 20
    colors:
      color_map_inside: [28, 28, 28, 0]
      color_map_outside: [28, 28, 28, 0]
      color_path: [28, 28, 28]
      color_robo: [28, 28, 28]`

**Comment by PiotrMachowski** [comment]
@NikiHard they are available in attributes of camera in devtools 
[![Open your Home Assistant instance and show your state developer tools.](https://my.home-assistant.io/badges/developer_states.svg)](https://my.home-assistant.io/redirect/developer_states/)

**Comment by NikiHard** [comment]
> @NikiHard they are available in attributes of camera in devtools [![Open your Home Assistant instance and show your state developer tools.](https://camo.githubusercontent.com/73bd22e94f35bf8dc96867eb43c77c9f188d621057adab857e6fa5c3a0d7c16a/68747470733a2f2f6d792e686f6d652d617373697374616e742e696f2f6261646765732f646576656c6f7065725f7374617465732e737667)](https://my.home-assistant.io/redirect/developer_states/)

```
- vacuum:
    x: 25500
    'y': 25500
  map:
    x: 85
    'y': 111
- vacuum:
    x: 26500
    'y': 25500
  map:
    x: 65
    'y': 111
- vacuum:
    x: 25500
    'y': 26500
  map:
    x: 85
    'y': 131
```
