### ISSUE TITLE
Add send_command platform

### ISSUE THREAD

**Issue by jay448** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#175]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

After upgrading to the latest version (which looks amazing!) I am not able to tell the vacuum to do a Zone Cleanup or Pin & Go. This feature worked in the previous version (1.X) of the card just fine. I'm using this HACS Component (https://github.com/al-one/hass-xiaomi-miot) to link my viomi.vacuum.v7 to Home Assistant. I was able to get the Zone Cleanup & Pin & Go working using the component. 

The device is telling me the service was not found.

![Screenshot (10)](https://user-images.githubusercontent.com/1663401/142274210-1722afd5-e123-40f2-81cd-732374d2ce28.jpg)

![Screenshot (8)](https://user-images.githubusercontent.com/1663401/142274379-4724b971-b981-4b78-ae41-616588cfd77b.jpg)

And the following card configuration:

```
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.viomi_v7_da55_robot_cleaner
vacuum_platform: KrzysztofHajdamowicz/miio2
map_locked: false
```
There has got to be something I'm doing wrong here. I was loving the old card and the functionality and love the look of the new one. I'd really like to get it working but I need some help I think.

Thanks!

### What version of a card has described problem?

v2.0.1

### What was the last working version card?

v1.2.3

### What vacuum model do you have problems with?

viomi.vacuum.v7

### What version of Home Assistant do you use?

2021.11.0

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.viomi_v7_da55_robot_cleaner
vacuum_platform: KrzysztofHajdamowicz/miio2
map_locked: false
```
