### ISSUE TITLE
Can't draw a zone for zoned cleanup

### ISSUE THREAD

**Issue by kimme1024** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#189]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

I can't draw a selection for zoned cleanup.
I also can't select any segments.

### What version of a card has described problem?

v2.0.2

### What was the last working version card?

v1.x

### What vacuum model do you have problems with?

Roborock S5 & S7

### What version of Home Assistant do you use?

2021.11.4

### What type of installation are you running?

Home Assistant Core

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.roborock_s7
vacuum_platform: default
title: ''
map_source:
  camera: camera.roborock_s7
calibration_source:
  camera: true
map_locked: true
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_segment
  - template: vacuum_goto
```
