### ISSUE TITLE
Feature request: default map zoom

### ISSUE THREAD

**Issue by relains** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#194]
### Description

I have some mirrors and balcony windows in my house and the vacuum when scans it "thinks" that behind there is other part of the room. I put virtual walls so it won't try to get there, but the default map scale shows those areas.

![image](https://user-images.githubusercontent.com/19413434/142754721-25437dab-d1be-40f0-87b9-29be7a8815e4.png)

### Solution

Adding a variable with default zoom scale factor or specifying coordinates for default view would solve this issue.

**Comment by PiotrMachowski** [comment]
It is already possible: [documentation](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card#cropping-options)

```yaml
map_source:
  camera: camera.xiaomi
  crop:
    left: 100
    right: 20
    top: 25
    bottom: 15
```
