### ISSUE TITLE
Card inside vertical-stack makes other vertical-stack cards act weird

### ISSUE THREAD

**Issue by mortenmoulder** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#219]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

I recently updated this card and had to migrate the card. So far, so good, and everything went fine, except it is no longer next to my other cards.

I have a very, very simple view with just 2 columns. The 2 columns are placed as 2 vertical-stack cards, which used to work before the update (important - this used to work until I just updated). Here's an YAML example:

```
- title: Vacuum
  path: vacuum
  badges: []
  cards:
    - type: vertical-stack
      cards:
        - type: custom:xiaomi-vacuum-map-card
          map_source:
            camera: camera.xiaomi_cloud_map_extractor
          calibration_source:
            camera: true
          entity: vacuum.vacuum
          vacuum_platform: default
    - type: vertical-stack
      cards:
        - type: entities
          entities:
            - switch.some_entity
```

If I remove this card and replace it with something like weather, it works perfectly. No matter what I do, I cannot get my `type: vertical-stack` card with entities (and other things) to show up next to this vacuum map card. It worked perfectly before the update, though. No clue how or why the update can break parent "containers", but apparently it can.

The behavior also happens if I add a 3rd vertical-stack card, which I have on all my other views (I just have 3 vertical-stack filled with cards on all my other views, and they work perfectly).

Any clue why this is happening?

### What version of a card has described problem?

v2.0.6

### What was the last working version card?

v1.x.x

### What vacuum model do you have problems with?

Roborock S5

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Chrome (but others as well)

### What version of Home Assistant do you use?

core-2021.11.0

### What type of installation are you running?

Home Assistant Core
