### ISSUE TITLE
Room cleaning does not cleanin the correct zone

### ISSUE THREAD

**Issue by Lyr3x** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#228]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Zoned cleanup is working without any issues but room cleaning (zones defined by a path) does not results in cleaning the defined zone but the vacuum starts to clean around its base. 

![image](https://user-images.githubusercontent.com/6078365/143770030-afc25263-402d-4a72-b008-7a8f5dc2eedc.png)

You see the starting point of the path in the left area but the vacuum should start cleaning the right area. 

### What version of a card has described problem?

v2.0.7

### What vacuum model do you have problems with?

Roborock S7

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

All of them

### What version of Home Assistant do you use?

 2021.11.5

### What type of installation are you running?

Home Assistant Container

### Card's configuration

```yaml
 - type: custom:xiaomi-vacuum-map-card
    entity: vacuum.roborock_vacuum_a15
    map_source:
      camera: camera.xiaomi_cloud_map_extractor
    calibration_source:
      camera: true
    map_modes:
      - template: vacuum_clean_segment
        selection_type: ROOM
        name: Room List
        icon: mdi:floor-plan
        predefined_selections:
          - id: 2
            outline:
              - - 30015
                - 24311
              - - 31851
                - 24346
              - - 31851
                - 23711
              - - 34640
                - 23675
              - - 34605
                - 25829
              - - 31851
                - 25935
              - - 31887
                - 25441
              - - 30757
                - 25441
              - - 30757
                - 25864
              - - 30439
                - 25864
              - - 30439
                - 25229
              - - 29980
                - 25194
              - - 30015
                - 24311
            label:
              text: Büro
              x: 32567
              y: 24727
              offset_x: 35
            icon:
              name: mdi:desk-lamp
              x: 32567
              y: 24727
```
