### ISSUE TITLE
Outlines offset in map on android app

### ISSUE THREAD

**Issue by jonathanelmgren** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#232]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

The outlines in mobile version is not working properly when opening the app. It works after adding a zone to it. See the video for more context

https://user-images.githubusercontent.com/81702447/144248732-ad6e1acf-be5a-4c82-ad73-642170ae100d.mp4

### What version of a card has described problem?

Latest

### What vacuum model do you have problems with?

Xiaomi S6

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Android App

### What version of Home Assistant do you use?

core-2021.11.3

### What type of installation are you running?

Home Assistant Core

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.uffe
vacuum_platform: KrzysztofHajdamowicz/miio2
map_locked: true
two_finger_pan: true
map_modes:
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 1
        outline:
          - - 17977.884615384617
            - 33014.42307692308
          - - 21569.23076923077
            - 33014.42307692308
          - - 21649.03846153846
            - 29981.73076923077
          - - 20372.115384615383
            - 29981.73076923077
          - - 20292.30769230769
            - 28784.615384615383
          - - 17977.884615384617
            - 28704.80769230769
          - - 17977.884615384617
            - 33014.42307692308
      - id: 2
        outline:
          - - 18057.69230769231
            - 28704.80769230769
          - - 18137.5
            - 25033.653846153844
          - - 21728.846153846152
            - 25033.653846153844
          - - 21569.23076923077
            - 28625
          - - 18057.69230769231
            - 28625
      - id: 3
        outline:
          - - 23963.46153846154
            - 33094.230769230766
          - - 24043.26923076923
            - 29901.923076923078
          - - 22447.115384615383
            - 29981.73076923077
          - - 22287.5
            - 33174.03846153846
          - - 23963.46153846154
            - 33094.230769230766
      - id: 4
        outline:
          - - 27075.96153846154
            - 33094.230769230766
          - - 27075.96153846154
            - 29183.653846153848
          - - 24442.30769230769
            - 29103.846153846156
          - - 24442.30769230769
            - 31418.26923076923
          - - 25400
            - 31498.076923076922
          - - 25479.80769230769
            - 33014.42307692308
          - - 26996.153846153844
            - 33014.42307692308
      - id: 5
        outline:
          - - 27395.192307692305
            - 25113.46153846154
          - - 27395.192307692305
            - 29103.846153846156
          - - 24043.26923076923
            - 29103.846153846156
          - - 23644.23076923077
            - 29742.30769230769
          - - 23404.80769230769
            - 29981.73076923077
          - - 20611.53846153846
            - 29901.923076923078
          - - 20531.73076923077
            - 28864.423076923078
          - - 22207.69230769231
            - 28704.80769230769
          - - 22526.923076923078
            - 25273.076923076922
          - - 27075.96153846154
            - 25113.46153846154
          - - 27235.576923076922
            - 25113.46153846154
      - id: 6
        outline:
          - - 32103.846153846152
            - 28864.423076923078
          - - 32183.653846153844
            - 30061.53846153846
          - - 31625
            - 30061.53846153846
          - - 31545.192307692305
            - 32296.153846153848
          - - 31146.153846153844
            - 32535.576923076922
          - - 31066.346153846156
            - 32934.61538461538
          - - 27235.576923076922
            - 33094.230769230766
          - - 27155.769230769227
            - 29662.5
          - - 30427.884615384617
            - 29423.076923076922
          - - 30507.692307692305
            - 28864.423076923078
          - - 32024.03846153846
            - 28864.423076923078
      - id: 7
        outline:
          - - 27315.384615384617
            - 28704.80769230769
          - - 27315.384615384617
            - 25033.653846153844
          - - 32103.846153846152
            - 25193.269230769234
          - - 32103.846153846152
            - 28784.615384615383
          - - 27315.384615384617
            - 28625
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_follow_path
```
