### ISSUE TITLE
Add support for automatic switching map used by vacuum

### ISSUE THREAD

**Issue by jambuu** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#248]
### Description

I have a robot (roborock s5 max) which supports multiple floors (up to 4). I would like to request the possibility of choosing which map to use.

This is supported by the library used to communicate with the robot (i.e. python miio):

![Screenshot_20211208_102119](https://user-images.githubusercontent.com/20259378/145183228-1989f76e-0a75-422f-bb7f-02f4f1093cad.jpg)
O

This project is amazing and I am able to do everything I need with this card except switching the map. Then I need o explicitly use the mi home app and manually switch the map. 

### Solution

My wish would be that we could add an option in the menu (called floors) which would list the floors saved for this robot and set the wished map as active

**Comment by PiotrMachowski** [comment]
Clarification:

Right now card supports multiple floors by using `additional_presets`. You can use this feature to add multiple maps/vacuums configs.

---

Question:

Is it possible to choose map from HA by using `vacuum.send_command` service?
```yaml
service: vacuum.send_command
data:
  command: use_backup_map
  params:
    id: 314
```

**Comment by jambuu** [comment]
Hi @PiotrMachowski,

Thanks for taking a look at this! Your idea works, nevertheless with a slight different command. I was able to change the map with this command:

![image](https://user-images.githubusercontent.com/20259378/145833907-92873144-f31d-49ed-96b2-4a0054b01e0e.png)

I will take a look at your `additional_presets` to figure out how make the buttons call this `service`. In my case, I was able to change maps with parameters `0` and `1`

**Comment by PiotrMachowski** [comment]
You can add following config to your card (it will create 2 icons that will switch maps):
```yaml
append_icons: true
icons:
  - icon: mdi:numeric-0-box
    tooltip: Map 0
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.xiaomi_vacuum
        command: load_multi_map
        params: 0
  - icon: mdi:numeric-1-box
    tooltip: Map 1
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.xiaomi_vacuum
        command: load_multi_map
        params: 1
```

**Comment by jambuu** [comment]
Hi @PiotrMachowski,

Thank you very much! That worked flawlessly!

I will close this request as solved!

Thanks!

**Comment by jambuu** [comment]
Hi @PiotrMachowski,

One last question on this topic.

By using the icons, I can't add rooms to my map since the map dynamically changes and it wouldn't fit the second map.

If I instead I want to make it appear here:

![image](https://user-images.githubusercontent.com/20259378/145838897-1f73900a-aed9-4392-9ca5-b19db8987ea0.png)

I would need to create a new template for the map_mode to allow switching between presets (i.e. maps and rooms)?

**Comment by PiotrMachowski** [comment]
Can you post your config here? I have an idea for a temporary solution.

**Comment by jambuu** [comment]
Absolutely! Thank you very much for all the help.

It is very simple at the moment but I want to add rooms next:

```
  - badges: []
    title: Roboter
    path: roboter
    icon: "mdi:robot-vacuum"
    type: "custom:horizontal-layout"
    cards:
      - type: custom:xiaomi-vacuum-map-card
        preset_name: Haus
        entity: vacuum.roborock_vacuum_s5e
        map_source:
          camera: camera.xiaomi_cloud_map_extractor
        calibration_source:
          camera: true
        append_icons: true
        icons:
          - icon: mdi:home-floor-0
            tooltip: Erdgechoss
            tap_action:
              action: call-service
              service: vacuum.send_command
              service_data:
                entity_id: vacuum.roborock_vacuum_s5e
                command: load_multi_map
                params: 1
          - icon: mdi:home-floor-1
            tooltip: Obergeschoss
            tap_action:
              action: call-service
              service: vacuum.send_command
              service_data:
                entity_id: vacuum.roborock_vacuum_s5e
                command: load_multi_map
                params: 0
```

**Comment by PiotrMachowski** [comment]
I have added an additional preset for your first floor, you have to switch preset and then click "0" or "1" button. 
```yaml
  - badges: []
    title: Roboter
    path: roboter
    icon: "mdi:robot-vacuum"
    type: "custom:horizontal-layout"
    cards:
      - type: custom:xiaomi-vacuum-map-card
        preset_name: Erdgechoss
        entity: vacuum.roborock_vacuum_s5e
        map_source:
          camera: camera.xiaomi_cloud_map_extractor
        calibration_source:
          camera: true
        append_icons: true
        icons:
          - icon: mdi:home-floor-0
            tooltip: Erdgechoss
            tap_action:
              action: call-service
              service: vacuum.send_command
              service_data:
                entity_id: vacuum.roborock_vacuum_s5e
                command: load_multi_map
                params: 1
        map_modes:
          - template: vacuum_clean_zone
          - template: vacuum_clean_zone_predefined
            predefined_selections:
              - zones: [[25500, 25500, 26500, 26500]]
          - template: vacuum_goto
        additional_presets:
          - preset_name: Obergeschoss
            entity: vacuum.roborock_vacuum_s5e
            map_source:
              camera: camera.xiaomi_cloud_map_extractor
            calibration_source:
              camera: true
            append_icons: true
            icons:
              - icon: mdi:home-floor-1
                tooltip: Obergeschoss
                tap_action:
                  action: call-service
                  service: vacuum.send_command
                  service_data:
                    entity_id: vacuum.roborock_vacuum_s5e
                    command: load_multi_map
                    params: 0
            map_modes:
              - template: vacuum_clean_zone
              - template: vacuum_clean_zone_predefined
                predefined_selections:
                  - zones: [[27500, 27500, 28500, 28500]]
              - template: vacuum_goto
```

**Comment by jambuu** [comment]
Hi @PiotrMachowski,

Thank you for your incredible help and responsiveness! I really like your idea of switching the view which changes the presets.

What would really it perfect would be to override the action of chevron buttons (or to allow calling another callback on clicking event) so they trigger the map switching in the background:

![image](https://user-images.githubusercontent.com/20259378/145960035-dedb1580-af32-44eb-91cc-a49c539c78b6.png)

I looked briefly through the code and it seems those buttons are controlled by this code:
```html
<div
    class="preset-selector-icon-wrapper"
    @click="${(): void => this._setPresetIndex(this.presetIndex + 1, true)}">
    <ha-icon
        icon="mdi:chevron-right"
        class="preset-selector-icon ${this.presetIndex ===
        this.config.additional_presets?.length
            ? "disabled"
            : ""}">
    </ha-icon>
</div>
```

in this callback which sets the `presetIndex`, I would need to somehow inject another callback which can configure from home assistant, firing whatever service which we need. 

Would that be something doable or will it cause the ui to freeze assuming that the service is a blocking call? My javascript knowledge is very limited since I am a c++ guy, so I am raising more questions than answers :D

For the usability, that would be really perfect since the user wouldn't even notice that something is happening :trophy:

**Comment by PiotrMachowski** [comment]
I think it is doable, my idea is following:
 * add possibility to execute service call when preset is selected
 * add possibility to automatically select preset using a condition

I will reopen this issue as a feature request, but I do promise I will implement it anytime soon

**Comment by lwsrbrts** [comment]
I've achieved something similar to this using conditional cards.

In a nutshell, the set up relies on the calibration points from Xiaomi Cloud Map Extractor (camera) and uses one calibration point from that. I set a binary sensor to "on" if the calibration point matches and use that to decide which of two map cards to display using conditional cards - each map card having their own room outlines.

So, when the ground floor map is loaded, this is the state:

```
access_token: x
calibration_points:
  - vacuum:
      x: 25500
      'y': 25500
    map:
      x: 214
      'y': 230
  - vacuum:
      x: 26500
      'y': 25500
    map:
      x: 254
      'y': 230
  - vacuum:
      x: 25500
      'y': 26500
    map:
      x: 214
      'y': 190
room_numbers:
  '16': null
  '17': null
  '18': null
  '19': null
  '20': null
  '21': null
  '22': null
  '23': null
model: roborock.vacuum.a15
used_api: xiaomi
entity_picture: >-
  /api/camera_proxy/camera.roborock_s7_camera?token=x
friendly_name: Roborock S7 Camera
supported_features: 1
```

However when the first floor map is loaded, this is the camera state:

```
access_token: x
calibration_points:
  - vacuum:
      x: 25500
      'y': 25500
    map:
      x: 172
      'y': 242
  - vacuum:
      x: 26500
      'y': 25500
    map:
      x: 212
      'y': 242
  - vacuum:
      x: 25500
      'y': 26500
    map:
      x: 172
      'y': 202
room_numbers:
  '16': null
  '17': null
  '18': null
  '19': null
  '20': null
  '21': null
  '22': null
model: roborock.vacuum.a15
used_api: xiaomi
entity_picture: >-
  /api/camera_proxy/camera.roborock_s7_camera?token=x
friendly_name: Roborock S7 Camera
supported_features: 1
```

I configure a binary sensor template to be "on" when the first "map > x" calibration point is equal to 214 (see the ground floor state above). I am of course assuming this will remain fairly static.

```yaml
binary_sensor:
  - platform: template
    sensors:
      roborock_downstairs:
        friendly_name: Vacuum downstairs
        value_template: >
          {{ (state_attr('camera.roborock_s7_camera', 'calibration_points')[0].map.x) == 214 }}
```

I have two cards configured, one with outlines for rooms defined downstairs and one for rooms defined upstairs. I use a grid card, then have two conditional cards within that grid. One shows when binary.roborock_downstairs is "on", the other shows when it's "off" (not on).

I've pilfered the icons configuration from this discussion and added them also to allow switching. Once clicked, it does take a number of seconds for the other card to show up, but it works.

```yaml
type: grid
cards:
  - type: conditional
    conditions:
      - entity: binary_sensor.roborock_downstairs
        state: 'on'
    card:
      type: custom:xiaomi-vacuum-map-card
      entity: vacuum.roborock_s7
      camera: camera.roborock_s7_camera
      title: Roborock S7 Downstairs
      map_source:
        camera: camera.roborock_s7_camera
      calibration_source:
        camera: true
      append_icons: true
      icons:
        - icon: mdi:home-floor-0
          tooltip: Downstairs
          tap_action:
            action: call-service
            service: vacuum.send_command
            service_data:
              entity_id: vacuum.roborock_s7
              command: load_multi_map
              params: 0
        - icon: mdi:home-floor-1
          tooltip: Upstairs
          tap_action:
            action: call-service
            service: vacuum.send_command
            service_data:
              entity_id: vacuum.roborock_s7
              command: load_multi_map
              params: 1
      vacuum_platform: default
      map_locked: true
      map_modes:
        - template: vacuum_clean_segment
          repeats_type: EXTERNAL
          max_repeats: 3
          service_call_schema:
            service: vacuum.send_command
            service_data:
              command: app_segment_clean
              entity_id: '[[entity_id]]'
              params:
                - segments: '[[selection]]'
                  repeat: '[[repeats]]'
          predefined_selections:
            - id: 19
              outline:
                - - 26040
                  - 23119
                - - 25165
                  - 23076
                - - 25165
                  - 23226
                - - 22626
                  - 23247
              label:
                text: Dining Room
                x: 24482
                'y': 24634
                offset_y: 25
              icon:
                name: mdi:table-chair
                x: 24482
                'y': 24634
        - template: vacuum_clean_zone
        - template: vacuum_follow_path
  - type: conditional
    conditions:
      - entity: binary_sensor.roborock_downstairs
        state: 'off'
    card:
      type: custom:xiaomi-vacuum-map-card
      entity: vacuum.roborock_s7
      camera: camera.roborock_s7_camera
      title: Roborock S7 Upstairs
      map_source:
        camera: camera.roborock_s7_camera
      calibration_source:
        camera: true
      append_icons: true
      icons:
        - icon: mdi:home-floor-0
          tooltip: Downstairs
          tap_action:
            action: call-service
            service: vacuum.send_command
            service_data:
              entity_id: vacuum.roborock_s7
              command: load_multi_map
              params: 0
        - icon: mdi:home-floor-1
          tooltip: Upstairs
          tap_action:
            action: call-service
            service: vacuum.send_command
            service_data:
              entity_id: vacuum.roborock_s7
              command: load_multi_map
              params: 1
      vacuum_platform: default
      map_locked: true
      map_modes:
        - template: vacuum_clean_segment
          repeats_type: EXTERNAL
          max_repeats: 3
          service_call_schema:
            service: vacuum.send_command
            service_data:
              command: app_segment_clean
              entity_id: '[[entity_id]]'
              params:
                - segments: '[[selection]]'
                  repeat: '[[repeats]]'
          predefined_selections:
            - id: 18
              outline:
                - - 23493
                  - 27132
                - - 27700
                  - 27195
                - - 27721
                  - 28226
                - - 28205
                  - 28205
              label:
                text: Bedroom
                x: 25513
                'y': 29804
                offset_y: 25
              icon:
                name: mdi:bed-king
                x: 25513
                'y': 29804
        - template: vacuum_clean_zone
        - template: vacuum_follow_path
columns: 1
square: false

```

I've removed most of the rooms and outline points to minimise the information posted here. I think I could/should probably remove the icon for the current floor as it's fairly pointless but that's what I have at the moment.

Elegant? Not really, but it works.

**Comment by PiotrMachowski** [comment]
@lwsrbrts nice approach, buuuuuuuuuuut I have already implemented this feature, it should be published really soon (maybe even today)

**Comment by PiotrMachowski** [comment]
@lwsrbrts ok, you made me do it 😃 

v2.0.10 added `conditions` to preset's config

**Comment by AdrinkBeer** [comment]
Hello,

first of all, thanks again for your amazing work. 

I was exciting about this feature and I'm currently testing it.

I have two floors and I use the new activate service, it works great but I'm not sure about the following : is it possible to have the card opened on the right preset when it is rendered ? 
At first, I thought that conditions would do the job.

Thanks for your help !

**Comment by PiotrMachowski** [comment]
I didn't want to call a service every time the card is shown. Currently you can trigger the action for active preset by clicking on preset name (so you don't have go back and forth through presets). You can also add a condition, but a preset will disappear from chooser when condition is not met.

**Comment by AdrinkBeer** [comment]
I was not thinking about calling the service every time the card is shown, but more about something like 
`active_preset : 1` where 1 is the index of the second card and could be js template. Something that is used when the card is created, only to know which preset to display.

In my situation, when I change preset now, it change also the map, which is good, but when I exit the app and open it again, first preset is selected with the map of the second present.

**Comment by PiotrMachowski** [comment]
@AdrinkBeer I thiiiiink I can add an option to enable executing service every time the card is shown.

Right now if preset and map become desynchronized you can click in marked area, it will execute service for currently shown preset
![image](https://user-images.githubusercontent.com/6118709/149515330-69a60292-30f2-478d-94ad-a3837f1cf4fd.png)

**Comment by jambuu** [comment]
I totally agree with @AdrinkBeer.

If the robot is running on the second floor and I open home assistant, it should be able to open that preset (i.e. programmatically).

Is that what you mean @PiotrMachowski by executing the service whenever the card is shown or do you mean that we should always change the map of the robot we see the card? That would cause break the whole functionality since it would set map to first preset although robot might be elsewhere.

**Comment by PiotrMachowski** [comment]
@jambuu are you able to create a "current floor" sensor?

**Comment by jambuu** [comment]
Hi @PiotrMachowski, 

my idea was to use that other project of yours to save the state of a variable. As long as someone only changes the map with your card, it should work fine, i.e. whenever we change a preset, we can store the current floor as a sensor and solely rely on that. This would work cross users. 

This would break if people are changing the map via mihome app otherwise sounds like a simple solution to me.

**Comment by PiotrMachowski** [comment]
@jambuu I think it would be better to use input_select instead of saver ;)

By the way, probably the best solution would be the one proposed by @lwsrbrts: create a template sensor that will show current floor. Is it doable in your case?

**Comment by AdrinkBeer** [comment]
@PiotrMachowski,

I think we can easily create this kind of sensor,  like @lwsrbrts did, but in my case I used instead the **map_name** attribute of the **camera.xiaomi_cloud_map_extractor** entity to handle it.

**Comment by PiotrMachowski** [comment]
@AdrinkBeer ok, sooo, my idea is following: 
- add a condition to both presets to show only the current map
- add icons to switch floors from map card (because preset selector will be hidden)

**Comment by AdrinkBeer** [comment]
> @PiotrMachowski,
> 
> I think we can easily create this kind of sensor, like @lwsrbrts did, but in my case I used instead the **map_name** attribute of the **camera.xiaomi_cloud_map_extractor** entity to handle it.

My bad, for those reading this, it is not the name of the floor, so it cannot be used like this.

**Comment by PiotrMachowski** [comment]
@AdrinkBeer you should be able to distinguish floors by using other properties from map extractor, maybe using something from  `image` or `calibration_points`

**Comment by nvvasilev** [comment]
Hello, I have a similar request to be able to pick a preset on a certain condition, however the command "load_multi_map" does not seem to work. 
I would like to be able to switch maps depending on the open/close state of 2 sliding doors covered with glass on the front. The idea is that when the doors are closed I would like to use a map with an invisible wall in front of the closed doors so that the vacuum does not bump into them. And when they are open, the invisible wall splits into 2 like in the pictures below.
![image](https://user-images.githubusercontent.com/12248943/149938544-3a893003-0da3-47bc-8d30-8be3558dcf79.png)
![image](https://user-images.githubusercontent.com/12248943/149938587-9f1028c4-8168-4778-bf20-eb7dbe7d8244.png)
That way the vacuum does not bump into the opened doors, but is able to go into the walk-in closet and clean inside it :)

I have the Roborock S5 vacuum. Could that be the problem that it does not support that command?

**Comment by jambuu** [comment]
Hi @nvvasilev, I have roborock s5 max and the command works for me. Are you sure everything is enabled? (i.e. Multimap via Mi app)

**Comment by jambuu** [comment]
Hi @nvvasilev, that's what I mean, by default it is disabled, you need to activate and create multiple maps, etc.

**Comment by nvvasilev** [comment]
@jambuu I have enabled that option a long time ago. The only thing I don't know how to do is create multiple maps.. Currently I have 2 Backup maps and one Current map in the Map Settings. But there is no way to rename or set and Id to the backed up maps.

**Comment by ICookiee** [comment]
I am trying to implement the map switching feature, but it doesn't work. Switching floors with buttons works, switching presets with < and > works also. But it doesn't change the map automatically. Have I implemented it wrong?

` - type: custom:xiaomi-vacuum-map-card
        preset_name: Erdgeschoss
        activate_on_switch: true
        activate:
          service: vacuum.send_command
          service_data:
            entity_id: vacuum.roborock_s5_max
            command: load_multi_map
            params: 1
        view_layout:
          grid-area: map
        card_mod:
          class: header
        language: de
        entity: vacuum.roborock_s5_max
        map_source:
          camera: camera.roborock_s5_max
        calibration_source:
          camera: true
        map_locked: true
        map_modes:
          - template: vacuum_goto
          - template: vacuum_clean_zone
          - template: vacuum_clean_segment
            predefined_selections:
        additional_presets:`

(I deleted the rooms and the additional preset to minimize the code)

**Comment by Mansiongrewweheiser** [comment]
> I have added an additional preset for your first floor, you have to switch preset and then click "0" or "1" button.
> 
> ```yaml
>   - badges: []
>     title: Roboter
>     path: roboter
>     icon: "mdi:robot-vacuum"
>     type: "custom:horizontal-layout"
>     cards:
>       - type: custom:xiaomi-vacuum-map-card
>         preset_name: Erdgechoss
>         entity: vacuum.roborock_vacuum_s5e
>         map_source:
>           camera: camera.xiaomi_cloud_map_extractor
>         calibration_source:
>           camera: true
>         append_icons: true
>         icons:
>           - icon: mdi:home-floor-0
>             tooltip: Erdgechoss
>             tap_action:
>               action: call-service
>               service: vacuum.send_command
>               service_data:
>                 entity_id: vacuum.roborock_vacuum_s5e
>                 command: load_multi_map
>                 params: 1
>         map_modes:
>           - template: vacuum_clean_zone
>           - template: vacuum_clean_zone_predefined
>             predefined_selections:
>               - zones: [[25500, 25500, 26500, 26500]]
>           - template: vacuum_goto
>         additional_presets:
>           - preset_name: Obergeschoss
>             entity: vacuum.roborock_vacuum_s5e
>             map_source:
>               camera: camera.xiaomi_cloud_map_extractor
>             calibration_source:
>               camera: true
>             append_icons: true
>             icons:
>               - icon: mdi:home-floor-1
>                 tooltip: Obergeschoss
>                 tap_action:
>                   action: call-service
>                   service: vacuum.send_command
>                   service_data:
>                     entity_id: vacuum.roborock_vacuum_s5e
>                     command: load_multi_map
>                     params: 0
>             map_modes:
>               - template: vacuum_clean_zone
>               - template: vacuum_clean_zone_predefined
>                 predefined_selections:
>                   - zones: [[27500, 27500, 28500, 28500]]
>               - template: vacuum_goto
> ```

Hello everyone, I also used this code for showing me 2 maps. I have 4 floors, but adding more presets didnt work for me. Can you help me?
Also where do I find which param is which map?
 I tried changing numbers and got the params for 3 of my 4 maps. But I cannot figure out the Last one.

Thank you so much in advance.

**Comment by yoda98mnt** [comment]
`type: custom:xiaomi-vacuum-map-card
preset_name: Erdgeschoss
activate_on_switch: true
activate:
  service: vacuum.send_command
  service_data:
    entity_id: vacuum.roborock_s6_maxv
    command: load_multi_map
    params: 1
  view_layout:
    grid-area: map
    card_mod: null
  class: header
  language: de
  entity: vacuum.roborock_s6_maxv
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.roborock_s6_maxv
map_locked: true
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_zone_predefined
    name: Zone EG
    predefined_selections:
      - zones:
          - - 21921
            - 28584
            - 23954
            - 30333
        label:
          text: Badezimmer
          x: 22932
          'y': 29539
          offset_y: 35
        icon:
          name: mdi:bathtub
          x: 22932
          'y': 29539
      - zones:
          - - 23957
            - 24963
            - 26034
            - 30657
        label:
          text: Flur
          x: 24975
          'y': 27591
          offset_y: 35
        icon:
          name: mdi:floor-lamp-torchiere
          x: 24975
          'y': 27591
  - template: vacuum_goto
append_icons: true
icons:
  - icon: mdi:home-floor-0
    tooltip: Erdgechoss
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.roborock_s6_maxv
        command: load_multi_map
        params: 0
  - icon: mdi:home-floor-1
    tooltip: Obergeschoss
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.roborock_s6_maxv
        command: load_multi_map
        params: 1
`
![Map](https://user-images.githubusercontent.com/116071224/196393535-b6e2a33b-6956-4de3-91ce-088bf366ba5e.PNG)

I have uploaded all my code here. In the hope that someone can help me. When I click on the buttons with the floors, the map change works. But when I select zone EG, it does not change to the correct map. What am I doing wrong?

**Comment by PiotrMachowski** [comment]
@yoda98mnt changing mode doesn't change the map, `activate` service call is used only when you have multiple presets

**Comment by yoda98mnt** [comment]
> @yoda98mnt changing mode doesn't change the map, `activate` service call is used only when you have multiple presets

Sorry, I don't understand, do you have an example of what I have to do?

**Comment by PiotrMachowski** [comment]
@yoda98mnt sure, it is here:
https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/248#issuecomment-992617765

You have to add this section to additional preset:
```yaml
activate_on_switch: true
activate:
  service: vacuum.send_command
  service_data:
    entity_id: vacuum.roborock_s6_maxv
    command: load_multi_map
    params: 1
```
