### ISSUE TITLE
Calibration failed, check configuration

### ISSUE THREAD

**Issue by Burbacottero** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#253]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

When I start cleaning zones it tells calibration not valid check configuration.

![image](https://user-images.githubusercontent.com/82754488/145584718-ccec3740-9810-49e3-8afc-1551d4ec6de6.png)

I'm using the configuration from demo, with xiaomi cloud map extractor, configured like this>
```
camera:
  - platform: xiaomi_cloud_map_extractor
    scan_interval: 1
    host: 192.168.1.47
    token: !secret token
    username: !secret username
    password: !secret xiaomi_cloud_password
    draw: ["all"]
    colors:
      color_map_outside: [0, 0, 0]
      color_path: [255, 255, 255]
    map_transformation:
      rotate: 180
      trim:
        left: 25
        right: 4
        top: 25
        bottom: 22
    attributes:
      - calibration_points
```

### What version of a card has described problem?

v2.0.8

### What vacuum model do you have problems with?

roborock.vacuum.s5e

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Chrome

### What version of Home Assistant do you use?

core-2021.11.5

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
title: ''
preset_name: Live map
entity: vacuum.chang
language: it
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 1
        outline:
          - - 25362
            - 29989
          - - 25362
            - 30370
          - - 25421
            - 30370
          - - 25421
            - 33476
          - - 25333
            - 33476
          - - 25333
            - 33534
          - - 25274
            - 33534
          - - 25274
            - 33739
          - - 24073
            - 33710
          - - 24073
            - 33622
          - - 22520
            - 33622
          - - 22520
            - 33388
          - - 21963
            - 33388
          - - 21963
            - 33329
          - - 21875
            - 33329
          - - 21875
            - 33270
          - - 21641
            - 33270
          - - 21641
            - 33183
          - - 21524
            - 33183
          - - 21524
            - 33124
          - - 21465
            - 33124
          - - 21465
            - 32772
          - - 21670
            - 32772
          - - 21670
            - 31220
          - - 21524
            - 31220
          - - 21524
            - 30663
          - - 24278
            - 30663
          - - 24278
            - 29989
          - - 25362
            - 29989
        label:
          text: Bedroom
          x: 22800
          'y': 31000
          offset_y: 35
        icon:
          name: mdi:bed
          x: 22800
          'y': 31250
  - template: vacuum_goto
  - template: vacuum_follow_path
map_locked: false
two_finger_pan: true
vacuum_platform: default
```

### Javascript errors shown in the browser's console (if applicable)

```shell
Nothing
```
