### ISSUE TITLE
Uncaught Error: Invalid argument not valid semver '2022.1.0.dev20211210'

### ISSUE THREAD

**Issue by sgueniot** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#254]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

The code that checks Home-Assistant version does not expect a dev version at the end and hence fails for example on version '2022.1.0.dev20211210'.

i use image from docker hub homeassistant/raspberrypi4-homeassistant:latest

Log : 
```
https://.../hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js?hacstag=193372044208:53:74396
Uncaught Error: Invalid argument not valid semver ('2022.1.0.dev20211210' received)
```

### What version of a card has described problem?

v2.0.8

### What vacuum model do you have problems with?

roborock.vacuum.s6

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

All

### What version of Home Assistant do you use?

core-2022.1.0.dev20211210

### What type of installation are you running?

Home Assistant Container

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.nestor
vacuum_platform: default
title: Test
```

### Additional information

If i had the card on lovelace, all the interface disapear
