### ISSUE TITLE
Custom battery tile icon template

### ISSUE THREAD

**Issue by kmlucy** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#255]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

I am attempting to replace the auto-generated tiles. The status and fan tiles are easy, but I'm not able to keep the dynamic battery icon from the battery tile. I tried the tile block below, but that just results in a missing icon.

### What version of a card has described problem?

v2.0.8

### What vacuum model do you have problems with?

roborock.vacuum.a15

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Chrome, Android App

### What version of Home Assistant do you use?

2021.11.5

### What type of installation are you running?

Home Assistant Container

### Card's configuration

```yaml
- entity: vacuum.roborock_s7
  label: Battery
  attribute: battery_level
  icon: '{{ states.vacuum.roborock_s7.attributes.battery_icon }}'
  unit: "%"
```

### Javascript errors shown in the browser's console (if applicable)

```shell
None
```

**Comment by PiotrMachowski** [comment]
Currently you can achieve it by adding multiple tiles with different icons and conditions that will make only one of them visible.

I will try to make icon temptable in the future versions

**Comment by kmlucy** [comment]
That's a good idea for now. For anyone else who is looking for this, here is what I came up with:
```
- entity: vacuum.roborock_s7
  label: Battery
  attribute: battery_level
  icon: mdi:battery-unknown
  unit: "%"
  tap_action: none
  conditions:
    - entity: vacuum.roborock_s7
      attribute: battery_icon
      value: "mdi:battery-unknown"
- entity: vacuum.roborock_s7
  label: Battery
  attribute: battery_level
  icon: mdi:battery-outline
  unit: "%"
  tap_action: none
  conditions:
    - entity: vacuum.roborock_s7
      attribute: battery_icon
      value: "mdi:battery-outline"
- entity: vacuum.roborock_s7
  label: Battery
  attribute: battery_level
  icon: mdi:battery-alert
  unit: "%"
  tap_action: none
  conditions:
    - entity: vacuum.roborock_s7
      attribute: battery_icon
      value: "mdi:battery-alert"
- entity: vacuum.roborock_s7
  label: Battery
  attribute: battery_level
  icon: mdi:battery
  unit: "%"
  tap_action: none
  conditions:
    - entity: vacuum.roborock_s7
      attribute: battery_icon
      value: "mdi:battery"
- entity: vacuum.roborock_s7
  label: Battery
  attribute: battery_level
  icon: mdi:battery-charging-10
  unit: "%"
  tap_action: none
  conditions:
    - entity: vacuum.roborock_s7
      attribute: battery_icon
      value: "mdi:battery-charging-10"
- entity: vacuum.roborock_s7
  label: Battery
  attribute: battery_level
  icon: mdi:battery-charging-20
  unit: "%"
  tap_action: none
  conditions:
    - entity: vacuum.roborock_s7
      attribute: battery_icon
      value: "mdi:battery-charging-20"
- entity: vacuum.roborock_s7
  label: Battery
  attribute: battery_level
  icon: mdi:battery-charging-30
  unit: "%"
  tap_action: none
  conditions:
    - entity: vacuum.roborock_s7
      attribute: battery_icon
      value: "mdi:battery-charging-30"
- entity: vacuum.roborock_s7
  label: Battery
  attribute: battery_level
  icon: mdi:battery-charging-40
  unit: "%"
  tap_action: none
  conditions:
    - entity: vacuum.roborock_s7
      attribute: battery_icon
      value: "mdi:battery-charging-40"
- entity: vacuum.roborock_s7
  label: Battery
  attribute: battery_level
  icon: mdi:battery-charging-50
  unit: "%"
  tap_action: none
  conditions:
    - entity: vacuum.roborock_s7
      attribute: battery_icon
      value: "mdi:battery-charging-50"
- entity: vacuum.roborock_s7
  label: Battery
  attribute: battery_level
  icon: mdi:battery-charging-60
  unit: "%"
  tap_action: none
  conditions:
    - entity: vacuum.roborock_s7
      attribute: battery_icon
      value: "mdi:battery-charging-60"
- entity: vacuum.roborock_s7
  label: Battery
  attribute: battery_level
  icon: mdi:battery-charging-70
  unit: "%"
  tap_action: none
  conditions:
    - entity: vacuum.roborock_s7
      attribute: battery_icon
      value: "mdi:battery-charging-70"
- entity: vacuum.roborock_s7
  label: Battery
  attribute: battery_level
  icon: mdi:battery-charging-80
  unit: "%"
  tap_action: none
  conditions:
    - entity: vacuum.roborock_s7
      attribute: battery_icon
      value: "mdi:battery-charging-80"
- entity: vacuum.roborock_s7
  label: Battery
  attribute: battery_level
  icon: mdi:battery-charging-90
  unit: "%"
  tap_action: none
  conditions:
    - entity: vacuum.roborock_s7
      attribute: battery_icon
      value: "mdi:battery-charging-90"
- entity: vacuum.roborock_s7
  label: Battery
  attribute: battery_level
  icon: mdi:battery-charging-100
  unit: "%"
  tap_action: none
  conditions:
    - entity: vacuum.roborock_s7
      attribute: battery_icon
      value: "mdi:battery-charging-100"
- entity: vacuum.roborock_s7
  label: Battery
  attribute: battery_level
  icon: mdi:battery-10
  unit: "%"
  tap_action: none
  conditions:
    - entity: vacuum.roborock_s7
      attribute: battery_icon
      value: "mdi:battery-10"
- entity: vacuum.roborock_s7
  label: Battery
  attribute: battery_level
  icon: mdi:battery-20
  unit: "%"
  tap_action: none
  conditions:
    - entity: vacuum.roborock_s7
      attribute: battery_icon
      value: "mdi:battery-20"
- entity: vacuum.roborock_s7
  label: Battery
  attribute: battery_level
  icon: mdi:battery-30
  unit: "%"
  tap_action: none
  conditions:
    - entity: vacuum.roborock_s7
      attribute: battery_icon
      value: "mdi:battery-30"
- entity: vacuum.roborock_s7
  label: Battery
  attribute: battery_level
  icon: mdi:battery-40
  unit: "%"
  tap_action: none
  conditions:
    - entity: vacuum.roborock_s7
      attribute: battery_icon
      value: "mdi:battery-40"
- entity: vacuum.roborock_s7
  label: Battery
  attribute: battery_level
  icon: mdi:battery-50
  unit: "%"
  tap_action: none
  conditions:
    - entity: vacuum.roborock_s7
      attribute: battery_icon
      value: "mdi:battery-50"
- entity: vacuum.roborock_s7
  label: Battery
  attribute: battery_level
  icon: mdi:battery-60
  unit: "%"
  tap_action: none
  conditions:
    - entity: vacuum.roborock_s7
      attribute: battery_icon
      value: "mdi:battery-60"
- entity: vacuum.roborock_s7
  label: Battery
  attribute: battery_level
  icon: mdi:battery-70
  unit: "%"
  tap_action: none
  conditions:
    - entity: vacuum.roborock_s7
      attribute: battery_icon
      value: "mdi:battery-70"
- entity: vacuum.roborock_s7
  label: Battery
  attribute: battery_level
  icon: mdi:battery-80
  unit: "%"
  tap_action: none
  conditions:
    - entity: vacuum.roborock_s7
      attribute: battery_icon
      value: "mdi:battery-80"
- entity: vacuum.roborock_s7
  label: Battery
  attribute: battery_level
  icon: mdi:battery-90
  unit: "%"
  tap_action: none
  conditions:
    - entity: vacuum.roborock_s7
      attribute: battery_icon
      value: "mdi:battery-90"
```

**Comment by PiotrMachowski** [comment]
Done in [v2.2.0](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/releases/tag/v2.2.0)

**Comment by CurtisTD** [comment]
@PiotrMachowski what is the appropriate way to render the icon based on the battery level now? Is there an icon template we can leverage? 

```
append_tiles: true
tiles:
  - entity: sensor.q5_max_battery
    icon: mdi:battery // <-- I want to render the various battery level icons depending on the entity value
```
