### ISSUE TITLE
Error for default vacuum platform with Neato bots

### ISSUE THREAD

**Issue by rsteckler** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#259]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

This line:
https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/blob/f5e13cc0e2c26a2d0f52093cc03ac3955e37ca6d/src/model/generators/icon-list-generator.ts#L166

... assumes that there's a fan_speed_list attribute on the vacuum, which is optional in the vacuum device type for HA.  Neato botvacs, in particular, don't have said attribute.  Seems like checking for null and omitting the fan speed icon would be the safe thing here.

### What version of a card has described problem?

2.0.8

### What vacuum model do you have problems with?

Neato Botvac D7

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/neato/

### What browser (browsers/apps) does have this problem?

All

### What version of Home Assistant do you use?

2021.12.1

### What type of installation are you running?

Home Assistant Container

### Javascript errors shown in the browser's console (if applicable)

```shell
xiaomi-vacuum-map-card.js?hacstag=193372044208:557 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at Function.generate (xiaomi-vacuum-map-card.js?hacstag=193372044208:557)
    at HTMLElement._setPresetIndex (xiaomi-vacuum-map-card.js?hacstag=193372044208:836)
    at HTMLElement._firstHass (xiaomi-vacuum-map-card.js?hacstag=193372044208:836)
    at HTMLElement.set hass [as hass] (xiaomi-vacuum-map-card.js?hacstag=193372044208:836)
    at HTMLElement.value (hui-masonry-view.ts:44)
    at hui-masonry-view.ts:44
    at Array.map (<anonymous>)
    at HTMLElement.value (hui-masonry-view.ts:44)
    at HTMLElement.value (hui-masonry-view.ts:44)
    at HTMLElement.value (hui-masonry-view.ts:44)
```

**Comment by PiotrMachowski** [comment]
Thanks! You can also disable this part of code by providing `icons: []` in your config

**Comment by PiotrMachowski** [comment]
By the way, I would love to add support for Neato vacuums, please share your config if/when you will get it to work

**Comment by rsteckler** [comment]
Noticed that I could override this generator by specifying icons.  I also "fixed" it by customizing the entity and adding the fan_speed_list attribute with a fake "Auto" value to satiate the generator.

Once that was done, it worked to the point that the card loaded (with a faked calibration).  Here's the current config:
```
type: custom:xiaomi-vacuum-map-card
platform: default
title: Dusty (downstairs)
entity: vacuum.dusty
preset_name: Live Map
map_source:
  camera: camera.dusty_cleaning_map
calibration_source:
  calibration_points:
    - vacuum:
        x: 1
        'y': 1
      map:
        x: 1
        'y': 1
    - vacuum:
        x: 1562
        'y': 1916
      map:
        x: 1562
        'y': 1916
    - vacuum:
        x: 1
        'y': 1916
      map:
        x: 1
        'y': 1916
```
I just pulled the image size from the neato camera and created three fake points to get it to load the image.  None of that calibration is useful for the neato integration as neither it, nor the neato API, supports sending the device to a location or cleaning a zone that isn't pre-defined.

I haven't tested beyond that yet, but I'll go through the functions later today and verify what works and what doesn't.  I'll also share my "clean" config for those who want to use it, eliminating things like fan speed, go to point, etc.

I'll also document some differences between the integrations for you in case you want to add real support for Neato.  I for one would appreciate it;  your card is awesome!

To start, here's the vacuum entity:
```
battery_level: 97
battery_icon: mdi:battery-charging-100
status: Docked
clean_start: 2021-12-15T05:19:30Z
clean_stop: 2021-12-15T07:18:00Z
clean_area: 106.5472
clean_suspension_count: 0
clean_suspension_time: 0
clean_pause_time: 0
clean_error_time: 0
battery_level_at_clean_start: 97
battery_level_at_clean_end: 11
launched_from: app
icon: mdi:robot-vacuum-variant
friendly_name: Dusty
supported_features: 15964
fan_speed_list: Auto
```
(Note the fan_speed_list is hacked in by me)

Some differences I've already noted:
1. No move to point
2. Zone cleaning requires predefined zones and are specified by name
3. The "fan speed" is specified as eco vs. turbo.
All of the changes required are probably covered in the ```neato.custom_cleaning``` service call spec outlined here:  https://www.home-assistant.io/integrations/neato/#platform-services


Will add some more comments later.

**Comment by PiotrMachowski** [comment]
> neither it, nor the neato API, supports sending the device to a location or cleaning a zone that isn't pre-defined

Sooo is it possible to send vacuum to predefined locations/zones?

**Comment by rsteckler** [comment]
> Sooo is it possible to send vacuum to predefined locations/zones?

Only by specifying a "zone name" that was setup in the app previously.  For example, in the Neato app, I created a room called "bedroom".  Now I can specify "bedroom" as the zone to clean in the neato.custom_cleaning service call, which will cause the robot to navigate to the bedroom, clean it, then return to base.

You can't specify coordinates and start a cleaning session.  In fact, the idea of robot corrdinates don't even exist in the neato API.

**Comment by PiotrMachowski** [comment]
Ok, so it seems that it will be possible to use map with predefined rooms using `neato.custom_cleaning` service 👍

**Comment by rsteckler** [comment]
Yep - working on that now.

**Comment by PiotrMachowski** [comment]
There might be a small problem in current version: IDs in room cleaning are passed in an array, I'm not sure if it is ok with neato.

It probably will look like this:
```yaml
service: neato.custom_cleaning
data:
  entity_id: vacuum.neato
  zone: ["bathroom"]
```

**Comment by rsteckler** [comment]
I think I can template it to make it work.  

One question.  The hints indicate an easy way to get/create coordinates from the card:
```
Getting room/point coordinates

To get coordinates switch to a specific mode, create a selection and hold "Play" button. A popup with full service call details will be shown. This feature replaces debug option from previous versions of the card. Config will also be written in browser's console to make it easier to copy.
```

I'm creating a box with zone cleanup, then holding the play button, but I don't get a popup or anything in the javascript console.  I can do it by hand in photoshop, but want to see if I'm missing something obvious, because drawing here and getting a list of coordinates would definitely be easier.

**Comment by PiotrMachowski** [comment]
It seems that there might be some issues with hold detection on some OSes/browsers... What browser do you use?

**Comment by rsteckler** [comment]
Using Chrome.  I'll just create some simple shapes using PS to get it working.

**Comment by rsteckler** [comment]
Here's an example of a working config on Neato:
```
type: custom:xiaomi-vacuum-map-card
platform: default
title: Dusty (downstairs)
entity: vacuum.dusty
preset_name: Live Map
map_source:
  camera: camera.dusty_cleaning_map
calibration_source:
  calibration_points:
    - vacuum:
        x: 1
        'y': 1
      map:
        x: 1
        'y': 1
    - vacuum:
        x: 1562
        'y': 1916
      map:
        x: 1562
        'y': 1916
    - vacuum:
        x: 1
        'y': 1916
      map:
        x: 1
        'y': 1916
icons:
  - icon: mdi:play
    tap_action:
      action: call-service
      service: vacuum.start
      service_data:
        entity_id: vacuum.dusty
  - icon: mdi:pause
    tap_action:
      action: call-service
      service: vacuum.pause
      service_data:
        entity_id: vacuum.dusty
  - icon: mdi:stop
    tap_action:
      action: call-service
      service: vacuum.stop
      service_data:
        entity_id: vacuum.dusty
  - icon: mdi:home
    tap_action:
      action: call-service
      service: vacuum.return_to_base
      service_data:
        entity_id: vacuum.dusty
  - icon: mdi:map-marker
    tap_action:
      action: call-service
      service: vacuum.locate
      service_data:
        entity_id: vacuum.dusty
tiles:
  - label: Battery
    icon: mdi:battery
    entity: vacuum.dusty
    attribute: battery_level
    unit: '%'
  - label: Status
    icon: mdi:robot-vacuum-variant
    entity: vacuum.dusty
    attribute: status
  - label: Area Cleaned
    icon: mdi:view-grid-outline
    entity: vacuum.dusty
    attribute: clean_area
    precision: 0
    unit: ' sqft'
map_modes:
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 1
        outline:
          - - 921
            - 1066
          - - 250
            - 1066
          - - 250
            - 750
          - - 921
            - 750
          - - 921
            - 1066
        label:
          text: Kitchen
          x: 580
          'y': 900
          offset_y: 30
        icon:
          name: mdi:fridge
          x: 580
          'y': 900
      - id: 2
        outline:
          - - 921
            - 1068
          - - 250
            - 1068
          - - 250
            - 1631
          - - 921
            - 1631
          - - 921
            - 1068
        label:
          text: Dining
          x: 580
          'y': 1300
          offset_y: 30
        icon:
          name: mdi:food
          x: 580
          'y': 1300
```

Here's the result:
![image](https://user-images.githubusercontent.com/1714230/146276573-97c39ff0-7338-40d6-80ca-39159162ebcb.png)

**Comment by PiotrMachowski** [comment]
Is this attribute always in square feet or does it depend on configuration?
```yaml
    entity: vacuum.dusty
    attribute: clean_area
```

**Comment by rsteckler** [comment]
> Is this attribute always in square feet or does it depend on configuration?
> 
> ```yaml
>     entity: vacuum.dusty
>     attribute: clean_area
> ```

Oops!  It's actually [always] square meters.

**Comment by PiotrMachowski** [comment]
Fixed in v2.0.9

@rsteckler have you managed to make a final version of config for Neato vacuums?

**Comment by rsteckler** [comment]
Here's what I've been using successfully:

```
type: custom:xiaomi-vacuum-map-card
platform: default
title: Dusty (downstairs)
entity: vacuum.dusty
preset_name: Live Map
map_source:
  camera: camera.dusty_cleaning_map
calibration_source:
  calibration_points:
    - vacuum:
        x: 1
        'y': 1
      map:
        x: 1
        'y': 1
    - vacuum:
        x: 1562
        'y': 1916
      map:
        x: 1562
        'y': 1916
    - vacuum:
        x: 1
        'y': 1916
      map:
        x: 1
        'y': 1916
icons:
  - icon: mdi:play
    tap_action:
      action: call-service
      service: vacuum.start
      service_data:
        entity_id: vacuum.dusty
  - icon: mdi:pause
    tap_action:
      action: call-service
      service: vacuum.pause
      service_data:
        entity_id: vacuum.dusty
  - icon: mdi:stop
    tap_action:
      action: call-service
      service: vacuum.stop
      service_data:
        entity_id: vacuum.dusty
  - icon: mdi:home
    tap_action:
      action: call-service
      service: vacuum.return_to_base
      service_data:
        entity_id: vacuum.dusty
  - icon: mdi:map-marker
    tap_action:
      action: call-service
      service: vacuum.locate
      service_data:
        entity_id: vacuum.dusty
tiles:
  - label: Battery
    icon: mdi:battery
    entity: vacuum.dusty
    attribute: battery_level
    unit: '%'
  - label: Status
    icon: mdi:robot-vacuum-variant
    entity: vacuum.dusty
    attribute: status
  - label: Area Cleaned
    icon: mdi:view-grid-outline
    entity: vacuum.dusty
    attribute: clean_area
    precision: 0
    multiplier: 10.75
    unit: ' sqft'
map_modes:
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 1
        outline:
          - - 921
            - 1066
          - - 250
            - 1066
          - - 250
            - 750
          - - 921
            - 750
          - - 921
            - 1066
        label:
          text: Kitchen
          x: 580
          'y': 900
          offset_y: 30
        icon:
          name: mdi:fridge
          x: 580
          'y': 900
      - id: 2
        outline:
          - - 921
            - 1068
          - - 250
            - 1068
          - - 250
            - 1631
          - - 921
            - 1631
          - - 921
            - 1068
        label:
          text: Dining
          x: 580
          'y': 1300
          offset_y: 30
        icon:
          name: mdi:food
          x: 580
          'y': 1300
```

**Comment by PiotrMachowski** [comment]
So segment cleaning still waits? :)

**Comment by rsteckler** [comment]
It does, unfortunately.  It's not something I would ever really use and I'm inundated with projects right now, so getting this piece working is a low priority for me.

**Comment by PiotrMachowski** [comment]
Absolutely understandable :) 

I have taken a look, can you check out this config? You have to provide correct zone id
```yaml
type: custom:xiaomi-vacuum-map-card
platform: default
title: Dusty (downstairs)
entity: vacuum.dusty
preset_name: Live Map
map_source:
  camera: camera.dusty_cleaning_map
calibration_source:
  calibration_points:
    - vacuum:
        x: 1
        'y': 1
      map:
        x: 1
        'y': 1
    - vacuum:
        x: 1562
        'y': 1916
      map:
        x: 1562
        'y': 1916
    - vacuum:
        x: 1
        'y': 1916
      map:
        x: 1
        'y': 1916
icons:
  - icon: mdi:play
    tap_action:
      action: call-service
      service: vacuum.start
      service_data:
        entity_id: vacuum.dusty
  - icon: mdi:pause
    tap_action:
      action: call-service
      service: vacuum.pause
      service_data:
        entity_id: vacuum.dusty
  - icon: mdi:stop
    tap_action:
      action: call-service
      service: vacuum.stop
      service_data:
        entity_id: vacuum.dusty
  - icon: mdi:home
    tap_action:
      action: call-service
      service: vacuum.return_to_base
      service_data:
        entity_id: vacuum.dusty
  - icon: mdi:map-marker
    tap_action:
      action: call-service
      service: vacuum.locate
      service_data:
        entity_id: vacuum.dusty
tiles:
  - label: Battery
    icon: mdi:battery
    entity: vacuum.dusty
    attribute: battery_level
    unit: '%'
  - label: Status
    icon: mdi:robot-vacuum-variant
    entity: vacuum.dusty
    attribute: status
  - label: Area Cleaned
    icon: mdi:view-grid-outline
    entity: vacuum.dusty
    attribute: clean_area
    precision: 0
    multiplier: 10.75
    unit: ' sqft'
map_modes:
  - template: vacuum_clean_segment
    service_call_schema:
      service: neato.custom_cleaning
      service_data:
        zone: '[[selection_unwrapped]]'
    predefined_selections:
      - id: Kitchen_zone
        outline:
          - - 921
            - 1066
          - - 250
            - 1066
          - - 250
            - 750
          - - 921
            - 750
          - - 921
            - 1066
        label:
          text: Kitchen
          x: 580
          'y': 900
          offset_y: 30
        icon:
          name: mdi:fridge
          x: 580
          'y': 900
      - id: Dining_zone
        outline:
          - - 921
            - 1068
          - - 250
            - 1068
          - - 250
            - 1631
          - - 921
            - 1631
          - - 921
            - 1068
        label:
          text: Dining
          x: 580
          'y': 1300
          offset_y: 30
        icon:
          name: mdi:food
          x: 580
          'y': 1300
```

**Comment by PiotrMachowski** [comment]
Ok, it won't work

**Comment by PiotrMachowski** [comment]
It might work with this (slightly adjusted) version:
[xiaomi-vacuum-map-card.zip](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/files/7811674/xiaomi-vacuum-map-card.zip)
Right now only alphanumeric zone ids are supported

**Comment by rsteckler** [comment]
Nice - will take a look in the morning!

**Comment by rsteckler** [comment]
Ok a couple of things:
1)  The underscore in the IDs doesn't work.  Says it's invalid.  No big deal.  I just created some without underscores.
2)  I created zones in the neato app with names that matched the zone IDs in the yaml above (e.g. diningroom)
3)  I selected the zone and hit play and get the following:  "Failed to call service neato/custom_cleaning. must contain at least one of entity_id, device_id, area_id."

You know FAR more about home assistant than me, but the only thing that looks weird in the yaml to me is the square brackets instead of curly braces for templating?  Changing them to braces didn't make a difference though - same error.

**Comment by PiotrMachowski** [comment]
1. I think I can change underscores to a valid symbol
2. Good idea 👍
3. Right, I have forgotten to add entity id. Please check out updated version

Square brackets are intentional - this is not HA built-in template, but a custom one for this card.

**Comment by rsteckler** [comment]
So close!  I'm getting this in the logs:  
```2022-01-05 19:06:42 ERROR (SyncWorker_4) [homeassistant.components.neato.vacuum] Zone '[[selection_unwrapped]]' was not found for the robot 'vacuum.dusty'```

It sounds like the zone is being passed across, but the square brackets aren't being replaced with the actual name of the zone and it's just passing the string literal.

Here's the current config:
```
...
map_modes:
  - template: vacuum_clean_segment
    service_call_schema:
      service: neato.custom_cleaning
      service_data:
        zone: '[[selection_unwrapped]]'
        entity_id: '[[entity_id]]'
    predefined_selections:
      - id: kitchen
...
```

**Comment by PiotrMachowski** [comment]
Have you installed js file included in the comment above?

**Comment by rsteckler** [comment]
I did yah, but it looks like it was serving up the old version.  Restarted HA and hard refreshed the browser and it looks like it loaded the new one.  
Even closer :)
```
2022-01-05 19:27:47 ERROR (SyncWorker_4) [homeassistant.components.neato.vacuum] Zone '"diningroom"' was not found for the robot 'vacuum.dusty'
```

It looks like there are some double quotes making their way into the expansion.

**Comment by PiotrMachowski** [comment]
Ok, now it seems to be the latest version, but it doesn't seem to contain fix for Neato... Please check out this one:
[xiaomi-vacuum-map-card.zip](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/files/7817436/xiaomi-vacuum-map-card.zip)
You can try opening HA in incognito mode, it should prevent caching.
This version should display following message in browser's console:
![image](https://user-images.githubusercontent.com/6118709/148280262-a73edfe4-a6ac-4960-a180-8d1ad1bdf305.png)

**Comment by rsteckler** [comment]
My bad.  Apparently you can't just replace the file when it was installed with HACS.  I had to delete the matching .gz file that HACS creates (and serves) when it installs a frontend component.  Once I deleted the .gz, it started serving the .js file.

....aaaaaand....
IT WORKS!

![image](https://user-images.githubusercontent.com/1714230/148281946-4ed7e4c7-69ff-425c-a293-818ecd325bd9.png)

**Comment by PiotrMachowski** [comment]
Great! It looks like I will have to remove "Xiaomi" part from the card's name 😀

**Comment by PiotrMachowski** [comment]
@rsteckler can you check out if this version works with your vacuum?

[xiaomi-vacuum-map-card.zip](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/files/7842646/xiaomi-vacuum-map-card.zip)

config:
```yaml
type: custom:xiaomi-vacuum-map-card
platform: default
title: Dusty (downstairs)
entity: vacuum.dusty
preset_name: Live Map
map_source:
  camera: camera.dusty_cleaning_map
calibration_source:
  identity: true
map_modes:
  - template: vacuum_clean_zone
    predefined_selections:
      - id: Kitchen_zone
        outline:
          - - 921
            - 1066
          - - 250
            - 1066
          - - 250
            - 750
          - - 921
            - 750
          - - 921
            - 1066
        label:
          text: Kitchen
          x: 580
          'y': 900
          offset_y: 30
        icon:
          name: mdi:fridge
          x: 580
          'y': 900
      - id: Dining_zone
        outline:
          - - 921
            - 1068
          - - 250
            - 1068
          - - 250
            - 1631
          - - 921
            - 1631
          - - 921
            - 1068
        label:
          text: Dining
          x: 580
          'y': 1300
          offset_y: 30
        icon:
          name: mdi:food
          x: 580
          'y': 1300
```

**Comment by PiotrMachowski** [comment]
By the way, it should now work with spaces in room id

**Comment by PiotrMachowski** [comment]
@rsteckler Can you check out v2.0.10?

config:
```yaml
type: custom:xiaomi-vacuum-map-card
platform: default
title: Dusty (downstairs)
entity: vacuum.dusty
preset_name: Live Map
map_source:
  camera: camera.dusty_cleaning_map
calibration_source:
  identity: true
map_modes:
  - template: vacuum_clean_zone
    predefined_selections:
      - id: Kitchen_zone
        outline:
          - - 921
            - 1066
          - - 250
            - 1066
          - - 250
            - 750
          - - 921
            - 750
          - - 921
            - 1066
        label:
          text: Kitchen
          x: 580
          'y': 900
          offset_y: 30
        icon:
          name: mdi:fridge
          x: 580
          'y': 900
      - id: Dining_zone
        outline:
          - - 921
            - 1068
          - - 250
            - 1068
          - - 250
            - 1631
          - - 921
            - 1631
          - - 921
            - 1068
        label:
          text: Dining
          x: 580
          'y': 1300
          offset_y: 30
        icon:
          name: mdi:food
          x: 580
          'y': 1300
```
