### ISSUE TITLE
Unnecessary value in parameter for app_segment_clean

### ISSUE THREAD

**Issue by Enzokot** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#268]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

When I start clean for one room, the card send command to the vacuum with additional unnecessary value. The vacuum go to the two rooms.
![image](https://user-images.githubusercontent.com/43236573/147138385-637205c9-0505-476a-8c6f-39d4ad6f492f.png)
![image](https://user-images.githubusercontent.com/43236573/147138391-08ae6e12-9472-4c2a-8ae8-c2b0a927d62d.png)

### What version of a card has described problem?

 v2.0.8

### What vacuum model do you have problems with?

roborock.vacuum.s5

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Chrome

### What version of Home Assistant do you use?

core-2021.11.5

### What type of installation are you running?

Home Assistant Supervised

### Card's configuration

```yaml
......
predefined_selections:
  - id: 1
    outline: [[19697, 23978], [22693, 23978], [22682, 23147], [22441, 23147], [22462, 19658], [19645, 19668]]
    label:
      text: "Спальня"
      x: 20953
      y: 21654
      offset_y: 35
    icon:
      name: "mdi:bed-king"
      x: 20953
      y: 21654
  - id: 16
    outline: [[19727, 24250], [22427, 24266], [22427, 28415], [19661, 28415]]
    label:
      text: "Детская"
      x: 20953
      y: 26835
      offset_y: 35
    icon:
      name: "mdi:bed-queen"
      x: 20953
      y: 26835
......
```
