### ISSUE TITLE
Can't draw an area on the map

### ISSUE THREAD

**Issue by r3pek** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#276]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Whenever i try to add a "square" to draw an area, it just adds a circle (i think) on the top left (0,0) of the map and can't be moved or resized.

### What version of a card has described problem?

v2.0.8

### What vacuum model do you have problems with?

Viomi S9

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Tried on Brave Version 1.33.106 Chromium: 96.0.4664.110 and Firefox 95.0.2

### What version of Home Assistant do you use?

2021.12.7

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
preset_name: Live map
entity: vacuum.viomi_s9
map_locked: true
map_source:
  camera: camera.viomi_s9_map
calibration_source:
  camera: true
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 1
        outline:
          - - 11458
            - 22131
          - - 14235
            - 22152
          - - 14194
            - 27409
          - - 13181
            - 27409
        label:
          text: Bedroom
          x: 12932
          'y': 20339
          offset_y: 35
        icon:
          name: mdi:bed
          x: 12932
          'y': 20339
  - template: vacuum_goto
  - template: vacuum_goto_predefined
    predefined_selections:
      - position:
          - 28006
          - 28036
        label:
          text: Emptying
          x: 28006
          'y': 28036
          offset_y: 35
        icon:
          name: mdi:broom
          x: 28006
          'y': 28036
      - position:
          - 32143
          - 26284
        label:
          text: Sofa
          x: 32143
          'y': 26284
          offset_y: 35
        icon:
          name: mdi:sofa
          x: 32143
          'y': 26284
vacuum_platform: default
```

### Javascript errors shown in the browser's console (if applicable)

```shell
xiaomi-vacuum-map-card.js?hacstag=193372044208:31 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
I @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
v @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
_ @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
I @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
g @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
I @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
v @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
_ @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
I @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
v @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
_ @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
I @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
v @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
_ @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
I @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
v @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
_ @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
I @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
(anonymous) @ xiaomi-vacuum-map-card.js?hacstag=193372044208:37
update @ xiaomi-vacuum-map-card.js?hacstag=193372044208:37
performUpdate @ xiaomi-vacuum-map-card.js?hacstag=193372044208:25
Πq @ xiaomi-vacuum-map-card.js?hacstag=193372044208:25
xiaomi-vacuum-map-card.js?hacstag=193372044208:31 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
I @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
v @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
_ @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
I @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
g @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
I @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
v @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
_ @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
I @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
v @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
_ @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
I @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
v @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
_ @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
I @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
v @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
_ @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
I @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
(anonymous) @ xiaomi-vacuum-map-card.js?hacstag=193372044208:37
update @ xiaomi-vacuum-map-card.js?hacstag=193372044208:37
performUpdate @ xiaomi-vacuum-map-card.js?hacstag=193372044208:25
Πq @ xiaomi-vacuum-map-card.js?hacstag=193372044208:25
xiaomi-vacuum-map-card.js?hacstag=193372044208:31 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
I @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
v @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
_ @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
I @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
g @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
I @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
v @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
_ @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
I @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
v @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
_ @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
I @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
v @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
_ @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
I @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
v @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
_ @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
I @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
(anonymous) @ xiaomi-vacuum-map-card.js?hacstag=193372044208:37
update @ xiaomi-vacuum-map-card.js?hacstag=193372044208:37
performUpdate @ xiaomi-vacuum-map-card.js?hacstag=193372044208:25
Πq @ xiaomi-vacuum-map-card.js?hacstag=193372044208:25
xiaomi-vacuum-map-card.js?hacstag=193372044208:31 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
I @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
v @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
_ @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
I @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
g @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
I @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
v @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
_ @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
I @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
v @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
_ @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
I @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
v @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
_ @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
I @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
v @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
_ @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
I @ xiaomi-vacuum-map-card.js?hacstag=193372044208:31
(anonymous) @ xiaomi-vacuum-map-card.js?hacstag=193372044208:37
update @ xiaomi-vacuum-map-card.js?hacstag=193372044208:37
performUpdate @ xiaomi-vacuum-map-card.js?hacstag=193372044208:25
Πq @ xiaomi-vacuum-map-card.js?hacstag=193372044208:25
```

### Additional information

I was just starting to try to setup some zones (started with the demo config) and noticed that it didn't work as expected.

**Comment by PiotrMachowski** [comment]
Can you show how it looks like? Does it start to work after switching to a different mode and back?

**Comment by r3pek** [comment]
damn... sorry, i even recorded a video of it and forgot to attach ti :facepalm: 

https://user-images.githubusercontent.com/3050556/147797223-67ca0c32-54ec-4173-8f18-7d0938b59b2b.mp4

**Comment by PiotrMachowski** [comment]
Can you try changing to a different mode and back to check if it starts to work?

Also could you paste attributes of `camera.viomi_s9_map` entity as well?

**Comment by r3pek** [comment]
Changing back and forth doesn't make it behave differently.


```
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 10.0.1.100
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ["all"]
    country: de
    name: "Viomi S9 Map"
    colors:
      color_map_inside: [32, 115, 185]
      color_map_outside: [19, 87, 148]
      color_map_wall: [100, 196, 254]
      color_map_wall_v2: [93, 109, 126]
      color_grey_wall: [93, 109, 126]
      color_ignored_obstacle: [0, 0, 0, 127]
      color_ignored_obstacle_with_photo: [0, 0, 0, 127]
      color_obstacle: [0, 0, 0, 127]
      color_obstacle_with_photo: [0, 0, 0, 127]
      color_path: [147, 194, 238]
      color_goto_path: [0, 255, 0]
      color_predicted_path: [255, 255, 0, 0]
      color_cleaned_area: [127, 127, 127, 127]
      color_zones: [0xAD, 0xD8, 0xFF, 0x8F]
      color_zones_outline: [0xAD, 0xD8, 0xFF]
      color_virtual_walls: [255, 0, 0]
      color_new_discovered_area: [64, 64, 64]
      color_no_go_zones: [255, 33, 55, 127]
      color_no_go_zones_outline: [255, 0, 0]
      color_no_mop_zones: [163, 130, 211, 127]
      color_no_mop_zones_outline: [163, 130, 211]
      color_charger: [0x66, 0xfe, 0xda, 0x7f]
      color_robo: [75, 235, 149]
      color_room_names: [0, 0, 0, 0]
      color_unknown: [0, 0, 0]
      color_scan: [0xDF, 0xDF, 0xDF]
    room_colors:
      1: [240, 178, 122]
      2: [133, 193, 233]
      3: [217, 136, 128]
      4: [52, 152, 219]
      5: [205, 97, 85]
      6: [243, 156, 18]
      7: [88, 214, 141]
      8: [245, 176, 65]
      9: [252, 212, 81]
      10: [72, 201, 176]
      11: [84, 153, 199]
      12: [133, 193, 233]
      13: [245, 176, 65]
      14: [82, 190, 128]
      15: [72, 201, 176]
      16: [165, 105, 18]
    # texts:
    #   - text: "Room 1"
    #     x: 25
    #     y: 25
    #     color: [125, 20, 213]
    #   - text: "Room 2"
    #     x: 25
    #     y: 75
    #     color: [125, 20, 213, 127]
    #     font: "FreeSans.ttf"
    #     font_size: 25
    map_transformation:
      scale: 1
      rotate: 0
      trim:
        top: 0
        bottom: 0
        left: 0
        right: 0
    sizes:
      charger_radius: 4
      vacuum_radius: 6.5
      obstacle_radius: 3
      ignored_obstacle_radius: 3
      obstacle_with_photo_radius: 3
      ignored_obstacle_with_photo_radius: 3
    attributes:
      - calibration_points
      - charger
      - cleaned_rooms
      - country
      - goto
      - goto_path
      - goto_predicted_path
      - image
      - is_empty
      - map_name
      - no_go_areas
      - no_mopping_areas
      - obstacles
      - ignored_obstacles
      - obstacles_with_photo
      - ignored_obstacles_with_photo
      - path
      - room_numbers
      - rooms
      - vacuum_position
      - vacuum_room
      - vacuum_room_name
      - walls
      - zones
    scan_interval:
      seconds: 5
    auto_update: true
    store_map_raw: false
    store_map_image: true
    store_map_path: "/tmp"
    force_api: roidmi
```

**Comment by PiotrMachowski** [comment]
There should be `calibration_points` entry in attributes, is it missing?

**Comment by r3pek** [comment]
Yeah sorry.... miss clipped it:

```
calibration_points: 
- vacuum:
    x: 0
    'y': 0
  map:
    x: 75
    'y': 120
- vacuum:
    x: 1
    'y': 0
  map:
    x: 75
    'y': 120
- vacuum:
    x: 0
    'y': 1
  map:
    x: 75
    'y': 120

charger: 
x: 712
'y': 485

cleaned_rooms: null
country: de
goto: null
goto_path: null
goto_predicted_path: null
ignored_obstacles: null
ignored_obstacles_with_photo: null
image: 
size: 73170
offset_y: 0
```

This is the missing part right before the `offset_x`
