### ISSUE TITLE
Unable to mark point in Pin&Go or Path mode

### ISSUE THREAD

**Issue by jerrywcy** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#277]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Everything else goes well, but when I tried to mark a point in Pin & Go mode or a series of points in Path mode, nothing happened.  No point showed up, and when I clicked the play button, it showed "No selection provided"
HOWEVER, when I tried to mark points on the iPad App with my fingers, nothing happened. BUT then I tried to mark with my Apple Pencil and it worked! I still wonder what happened.

### What version of a card has described problem?

v2.0.8

### What vacuum model do you have problems with?

roborock.vacuum.a29

### Which integration do you use to control your vacuum (link)?

https://github.com/ha0y/xiaomi_miot_raw

### What browser (browsers/apps) does have this problem?

Microsoft Edge

### What version of Home Assistant do you use?

core-2021.12.7

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
title: Xiaomi Vacuum Map Card
preset_name: Live map
entity: vacuum.roborock_a29_f6ee_robot_cleaner
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
vacuum_platform: default
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_follow_path
```

### Javascript errors shown in the browser's console (if applicable)

```shell
Error handling response: TypeError: Cannot read properties of undefined (reading 'code')
    at o (chrome-extension://clgdhlhfiocphghdkdbgdlmfaafccfmc/bundle/common.js:3:21134)
    at chrome-extension://clgdhlhfiocphghdkdbgdlmfaafccfmc/bundle/common.js:3:23431
default_view:1 
        
Error handling response: TypeError: Cannot read properties of undefined (reading 'code')
    at o (chrome-extension://clgdhlhfiocphghdkdbgdlmfaafccfmc/bundle/common.js:3:21134)
    at chrome-extension://clgdhlhfiocphghdkdbgdlmfaafccfmc/bundle/common.js:3:23431
default_view:1 
        
Unchecked runtime.lastError: The message port closed before a response was received.

DevTools failed to load source map: Could not load content for chrome-extension://fgckcfkpckemdnnejbbfkkchanedbeje/lib/browser-polyfill.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

DevTools failed to load source map: Could not load content for chrome-extension://lggdbpblkekjjbobadliahffoaobaknh/static/js/content.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

DevTools failed to load source map: Could not load content for chrome-extension://odfonlkabodgbolnmmkdijkaeggofoop/pages/content/purify.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```
