### ISSUE TITLE
Ungültige Kalibrierung, bitte überprüfen Sie ihre Konfigration

### ISSUE THREAD

**Issue by Crash343** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#278]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Hi,

Since a few hours I cannot use the Card in my Homeassistant anymore. It is showing an error (sorry I have installed it in German... "Ungültige Kalibrierung, bitte überprüfen Sie ihre Konfiguration".
![image](https://user-images.githubusercontent.com/52348814/147875975-65196821-e085-4760-bc9c-d940209fe800.png)
I tested some things like reverting the Homeassistant Versio, Card Version, ... not working at all.

After I searched about the error and I found some errors with the Login to Xiaomi with other devices and plugins:
https://github.com/Pittini/iobroker-nodemihome/issues/56

I think this could also be the problem for this?

Thanks for fixing, have a good start in 2022 and best regards,
Crash343

### What version of a card has described problem?

v2.0.8

### What vacuum model do you have problems with?

roborock.vacuum.s5

### Which integration do you use to control your vacuum (link)?

https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card

### What browser (browsers/apps) does have this problem?

Chrome/Android App

### What version of Home Assistant do you use?

core-2021.12.7

### What type of installation are you running?

Home Assistant Supervised

**Comment by koles142** [comment]
Mam to samo ale możliwe, że problemem jest xiaomi miio bo też sieje błędami.

W przypadku Twojej karty w logu jest błąd:
"Logger: custom_components.xiaomi_cloud_map_extractor.camera
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:288
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 1 stycznia 2022, 12:16:01 (505 occurrences)
Last logged: 17:42:19

Failed to retrieve model"

**Comment by PiotrMachowski** [comment]
This was a problem with map extractor, update it to the latest version to fix map

**Comment by spider7611** [comment]
Have the same problem. Reinstall many times the map extractor but nothing changed.

**Comment by PiotrMachowski** [comment]
@spider7611 Do you have this version of map extractor installed?
https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/releases/tag/v2.1.3

**Comment by spider7611** [comment]
Yes, always download the latest one.

**Comment by spider7611** [comment]
When I use this I see the map:
`calibration_source:
  calibration_points:
    - map:
        x: 676
        'y': 138
      vacuum:
        x: 25457
        'y': 28069
    - map:
        x: 1247
        'y': 108
      vacuum:
        x: 37405
        'y': 28501
    - map:
        x: 526
        'y': 200
      vacuum:
        x: 22410
        'y': 26566`

**Comment by spider7611** [comment]
When I use this I see the map:
```
calibration_source:
  calibration_points:
    - map:
        x: 676
        'y': 138
      vacuum:
        x: 25457
        'y': 28069
    - map:
        x: 1247
        'y': 108
      vacuum:
        x: 37405
        'y': 28501
    - map:
        x: 526
        'y': 200
      vacuum:
        x: 22410
        'y': 26566
```

**Comment by PiotrMachowski** [comment]
What does camera image show?

**Comment by spider7611** [comment]
Show my rooms and I see the vacuum where it was when cleaning live.

**Comment by PiotrMachowski** [comment]
Can you show your camera config here?

**Comment by spider7611** [comment]
Of course: 
```
- platform: xiaomi_cloud_map_extractor
    host: 192.168.1.178
    token: !secret xi_token
    username: email@email.com
    password: xxxxxxxx
    country: "de"
    colors:
      color_map_inside: [32, 115, 185]
      color_map_outside: [19, 87, 148]
      color_map_wall: [100, 196, 254]
      color_map_wall_v2: [93, 109, 126]
      color_grey_wall: [93, 109, 126]
      color_path: [255, 0, 0]
      color_goto_path: [0, 255, 0]
      color_predicted_path: [255, 255, 0, 0]
      color_zones_outline: [0xAD, 0xD8, 0xFF]
      color_virtual_walls: [255, 0, 0]
      color_no_go_zones: [255, 33, 55, 127]
      color_no_go_zones_outline: [255, 0, 0]
      color_no_mop_zones: [163, 130, 211, 127]
      color_no_mop_zones_outline: [163, 130, 211]
      color_charger: [0x66, 0xfe, 0xda, 0x7f]
      color_robo: [75, 235, 149]
      color_unknown: [0, 0, 0]
      color_scan: [0xDF, 0xDF, 0xDF]
    room_colors:
      1: [240, 178, 122]
      2: [133, 193, 233]
      3: [217, 136, 128]
      4: [52, 152, 219]
      5: [205, 97, 85]
      6: [243, 156, 18]
      7: [88, 214, 141]
      8: [245, 176, 65]
      9: [252, 212, 81]
      10: [72, 201, 176]
      11: [84, 153, 199]
      12: [133, 193, 233]
      13: [245, 176, 65]
      14: [82, 190, 128]
      15: [72, 201, 176]
      16: [165, 105, 18]
    draw:
      - charger
      - path
      - goto_path
      - predicted_path
      - no_go_zones
      - no_mopping_zones
      - vacuum_position
      - virtual_walls
    map_transformation:
      scale: 3
      trim:
        top: 15
        bottom: 10
        left: 0
        right: 15
    attributes:
      - charger
      - goto
      - goto_path
      - goto_predicted_path
      - image
      - no_go_areas
      - no_mopping_areas
      - obstacles
      - path
      - vacuum_position
      - walls
    auto_update: true
    force_api: xiaomi
```

**Comment by PiotrMachowski** [comment]
You have to add `calibration_points` to `attributes` section to make card work. Also I suggest to remove all unnecessary values, as they increase DB/CPU/memory usage

**Comment by spider7611** [comment]
Ok, will try it. Waht you think what must to remove? Any suggestion?

**Comment by spider7611** [comment]
Now I see the map, but can't select rooms.
```
calibration_source:
  camera: true
entity: vacuum.roborock_s5
map_source:
  camera: camera.xiaomi_cloud_map_extractor
type: custom:xiaomi-vacuum-map-card
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_segment
  - template: vacuum_goto
vacuum_platform: default
```

**Comment by PiotrMachowski** [comment]
You have to configure them manually in card's config

**Comment by spider7611** [comment]
Don't know how to do that.  This is not enough? - template: vacuum_clean_segment

**Comment by PiotrMachowski** [comment]
No, you have to add `predefined_selections` section, like [here](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/blob/master/docs/demo_config.yaml#L33). `id` = room number

**Comment by spider7611** [comment]
Ok, thank your help! Perfect job!

**Comment by spider7611** [comment]
Sorry but have a problem with the room selection cleaning. Have this code and see the rooms and can select it. But if I start the room cleaning the robot go about 2 meter and go back to dock, sometimes after start just go reverse 20cm and go back to dock. What you think what is the problem? (the predefined zone cleaning working good, only the room cleaning do something wierd) You see the red line on the picture when i do room cleaning.
![roomclean](https://user-images.githubusercontent.com/45290475/148086931-dd8939b5-15b6-4fe0-a897-4b9d9c3ebd72.jpg)


```
calibration_source:
  camera: true
entity: vacuum.roborock_s5
map_source:
  camera: camera.xiaomi_cloud_map_extractor
type: custom:xiaomi-vacuum-map-card
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_follow_path
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 1
        outline:
          - - 26150
            - 27618
          - - 26091
            - 25255
          - - 26505
            - 25255
          - - 26505
            - 25373
          - - 28041
            - 25432
          - - 28041
            - 24782
          - - 29400
            - 24782
          - - 29400
            - 25668
          - - 29223
            - 25727
          - - 29164
            - 27677
          - - 26150
            - 27677
        label:
          text: Nappali
          x: 27745
          'y': 26082
          offset_y: 35
        icon:
          name: mdi:television
          x: 27745
          'y': 26082
      - id: 2
        outline:
          - - 22132
            - 27914
          - - 22132
            - 26377
          - - 23786
            - 26318
          - - 23786
            - 24782
          - - 24377
            - 24841
          - - 24318
            - 26318
          - - 25323
            - 26318
          - - 25323
            - 24782
          - - 26150
            - 24841
          - - 26150
            - 28032
          - - 24732
            - 28091
          - - 24732
            - 28800
          - - 23255
            - 28800
          - - 23195
            - 27914
          - - 22132
            - 27914
        label:
          text: Előszoba
          x: 23885
          'y': 27954
          offset_y: 35
        icon:
          name: mdi:exit-run
          x: 23885
          'y': 27954
```
