### ISSUE TITLE
After adding this card, panel is always empty

### ISSUE THREAD

**Issue by lweberru** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#279]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

I using the simple vacuum card and also the camera addon from this repo. Both work fine. But as soon I add this map card, the selected panel is empty. Its even no longer possible to edit anything within the selected panel. No error message visible.

### What version of a card has described problem?

V.2.08

### What vacuum model do you have problems with?

roborock_vacuum_a15

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

IOS App

### What version of Home Assistant do you use?

core-2022.2.0.dev20211230

### What type of installation are you running?

Home Assistant Container

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.robbi
calibration_source:
  camera: true
entity: vacuum.roborock_vacuum_a15
vacuum_platform: default
title: Robbi
```

### Additional information

Used a manual default installation with passing in the token and ip of the cleaner, because eu cloud not working with auto mode
