### ISSUE TITLE
Invalid calibration, please check your configuration

### ISSUE THREAD

**Issue by thumDer** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#285]
### Checklist

- [x] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

I've just installed the card via HACS but it seems I can't make it work. My card shows `Invalid calibration, please check your configuration` instead of the map. The other controls are working just fine. The map extractor itself works just fine.
![image](https://user-images.githubusercontent.com/54556708/148115130-4075f1da-0627-4ed7-b033-3df53d220c88.png)
If I try to set it up via the UI the Camera Entity selector is not working, I can't even type in anything.
![image](https://user-images.githubusercontent.com/54556708/148115702-e7e459bc-4d18-401d-8a7a-ea0c62ae001b.png)

### What version of a card has described problem?

v2.0.8

### What vacuum model do you have problems with?

Viomi SE

### Which integration do you use to control your vacuum (link)?

ttps://github.com/marotoweb/home-assistant-vacuum-viomise

### What browser (browsers/apps) does have this problem?

Firefox

### What version of Home Assistant do you use?

2021.10.2

### What type of installation are you running?

Home Assistant Supervised

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
title: Viomi Vacuum Map Card
preset_name: Live Map
entity: vacuum.viomi_se
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
vacuum_platform: marotoweb/viomise
```

### Javascript errors shown in the browser's console (if applicable)

```shell
Uncaught DOMException: CustomElementRegistry.define: 'xiaomi-vacuum-map-card-editor' has already been defined as a custom element xiaomi-vacuum-map-card.js:43
    re http://192.168.0.5:8123/local/custom_lovelace/xiaomi-vacuum-map-card.js:43
    re http://192.168.0.5:8123/local/custom_lovelace/xiaomi-vacuum-map-card.js:43
    e http://192.168.0.5:8123/local/custom_lovelace/xiaomi-vacuum-map-card.js:15
    <anonymous> http://192.168.0.5:8123/local/custom_lovelace/xiaomi-vacuum-map-card.js:126
    InnerModuleEvaluation self-hosted:2374
    evaluation self-hosted:2335
```

**Comment by PiotrMachowski** [comment]
Can you show config of map extractor?

**Comment by thumDer** [comment]
Sure, here it is:

```
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret viomi_se_host
    token: !secret viomi_se_token
    username: !secret mihome_user
    password: !secret mihome_pass
    draw: ["all"]
    map_transformation:
      scale: 3
      trim:
        top: 45
        left: 40
        right: 40
        bottom: 30
```

**Comment by PiotrMachowski** [comment]
You have to add `calibration_points` to make it work:
```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret viomi_se_host
    token: !secret viomi_se_token
    username: !secret mihome_user
    password: !secret mihome_pass
    draw: ["all"]
    map_transformation:
      scale: 3
      trim:
        top: 45
        left: 40
        right: 40
        bottom: 30
    attributes:
      - calibration_points
```
