### ISSUE TITLE
Room cleaning ignores repeat count

### ISSUE THREAD

**Issue by mateuszmalek** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#294]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

It seems that room cleaning function is ignoring the repeat counter which was added in v2.0.9 (I believe within #256).
Setting 2 or 3 has the same result - vacuum cleans the room only once and returns to dock.

### What version of a card has described problem?

v2.0.9

### What vacuum model do you have problems with?

roborock.vacuum.s5e

### Which integration do you use to control your vacuum (link)?

default

### What browser (browsers/apps) does have this problem?

Chrome 97.0.4692.71

### What version of Home Assistant do you use?

2021.12.8

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
  crop:
    top: 175
    left: 175
    right: 175
    bottom: 175
calibration_source:
  camera: true
entity: vacuum.roborock_vacuum_s5e
vacuum_platform: default
title: ''
map_locked: true
two_finger_pan: true
map_modes:
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 16
        outline:
          - - 25146
            - 26101
          - - 28049
            - 26101
          - - 28007
            - 22651
          - - 25146
            - 22651
        icon:
          label: Bedroom
          name: mdi:bed
          x: 26534
          'y': 24671
      - id: 17
        outline:
          - - 28160
            - 28463
          - - 29579
            - 28463
          - - 29579
            - 26128
          - - 28160
            - 26128
        icon:
          name: mdi:shoe-sneaker
          x: 28801
          'y': 27181
      - id: 18
        outline:
          - - 30266
            - 25990
          - - 35258
            - 25990
          - - 35258
            - 22510
          - - 30266
            - 22510
        icon:
          x: 32785
          'y': 24296
          name: mdi:television
      - id: 19
        outline:
          - - 28114
            - 24479
          - - 29625
            - 24479
          - - 29625
            - 23242
          - - 28114
            - 23242
        icon:
          x: 28801
          'y': 23975
          name: mdi:shower
      - id: 20
        outline:
          - - 25091
            - 28005
          - - 28068
            - 28005
          - - 28068
            - 26860
          - - 25091
            - 26860
        icon:
          x: 26603
          'y': 27410
          name: mdi:countertop
      - id: 21
        outline:
          - - 28114
            - 26082
          - - 30146
            - 26082
          - - 30146
            - 24571
          - - 28114
            - 24571
        icon:
          x: 29030
          'y': 25212
          name: mdi:book-open-page-variant
  - template: vacuum_clean_zone
  - template: vacuum_goto
```

**Comment by mateuszmalek** [comment]
I've tried to fix it myself but I believe it's an issue with integration instead: https://github.com/home-assistant/core/issues/59110 

Manually triggering command results in the same behavior.

```yaml
service: xiaomi_miio.vacuum_clean_segment
data:
  segments:
    - 21
    - 21
target:
  entity_id: vacuum.roborock_vacuum_s5e
```

**Comment by PiotrMachowski** [comment]
Well, I can't do much in this case

**Comment by mateuszmalek** [comment]
After some troubleshooting got it to work but still - I believe that's an upstream issue: https://github.com/home-assistant/core/issues/59110#issuecomment-1007558447 with `xiaomi_miio.vacuum_clean_segment`

**Comment by PiotrMachowski** [comment]
@mateuszmalek I think that it depends on vacuum model

**Comment by mateuszmalek** [comment]
You're right probably :)

I was successfully able to make it work for my S5 Max by overriding default template:
```yaml
  - template: vacuum_clean_segment
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: vacuum.send_command
      service_data:
        command: app_segment_clean
        entity_id: '[[entity_id]]'
        params:
          - segments: '[[selection]]'
            repeat: '[[repeats]]'
    predefined_selections:
    (...)
```

Dzięki :)
