### ISSUE TITLE
vacuum_clean_segment repeat count is -1

### ISSUE THREAD

**Issue by Mr-Groch** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#295]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

When I wanted to use new default repeat in 'room mode' (`template: vacuum_clean_segment`) I noticed that when I choose repeat 1 or 2 and one room it will clean only once. When I choose repeat 2 and 2 rooms, it will clean first room twice but second only once. When I choose repeat 3 and one room - it will clean twice that room... And so on... So it looks that last segment id in lgenerated list is missing...

### What version of a card has described problem?

2.0.9

### What vacuum model do you have problems with?

roborock.vacuum.s5e

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Chrome

### What version of Home Assistant do you use?

core-2021.12.8

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.roborock_s5_max
language: pl
map_source:
  camera: camera.roborock_s5_max_map
  crop:
    top: 150
    bottom: 150
    left: 170
    right: 170
calibration_source:
  camera: true
map_locked: true
append_tiles: true
tiles:
  - label: Mopowanie
    entity: binary_sensor.roborock_s5_max_mop_attached
    icon: mdi:waves
map_modes:
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 20
        outline:
          - - 25002
            - 23271
          - - 29847
            - 23271
          - - 29847
            - 25850
          - - 30044
            - 25850
          - - 30044
            - 26889
          - - 29803
            - 26889
          - - 29803
            - 27191
          - - 28637
            - 28422
          - - 25002
            - 28422
        label:
          text: Sypialnia
          x: 27513
          'y': 26014
          offset_y: 30
        icon:
          name: mdi:bed-empty
          x: 27513
          'y': 26014
      - id: 17
        outline:
          - - 30044
            - 25559
          - - 34775
            - 25559
          - - 34775
            - 29196
          - - 30044
            - 29196
        label:
          text: Salon
          x: 32364
          'y': 27468
          offset_y: 30
        icon:
          name: mdi:sofa
          x: 32364
          'y': 27468
      - id: 16
        outline:
          - - 30044
            - 25559
          - - 34775
            - 25559
          - - 34775
            - 23401
          - - 30044
            - 23401
        label:
          text: Pokój dzieci
          x: 32364
          'y': 24741
          offset_y: 30
        icon:
          name: mdi:toy-brick-outline
          x: 32364
          'y': 24741
      - id: 18
        outline:
          - - 29615
            - 31920
          - - 34446
            - 31920
          - - 34446
            - 35702
          - - 29615
            - 35702
        label:
          text: Kuchnia
          x: 32275
          'y': 33898
          offset_y: 30
        icon:
          name: mdi:silverware-fork-knife
          x: 32275
          'y': 33898
      - id: 21
        outline:
          - - 29615
            - 35702
          - - 34446
            - 35702
          - - 34446
            - 37526
          - - 29615
            - 37526
        label:
          text: Łazienka
          x: 32275
          'y': 36779
          offset_y: 30
        icon:
          name: mdi:shower
          x: 32275
          'y': 36779
  - template: vacuum_clean_zone
  - template: vacuum_goto
```

**Comment by PiotrMachowski** [comment]
It seems to be a problem with HA integration, not card: #294

**Comment by PiotrMachowski** [comment]
@mateuszmalek can you check if your vacuum behaves the same?

**Comment by mateuszmalek** [comment]
Can't confirm it is able to clean more than once with original template.

My card config: https://gist.github.com/mateuszmalek/1dacccf8900a18ccb21b7370903121c6
I've used the "Original template" mode.

`I noticed that when I choose repeat 1 or 2 and one room it will clean only once.` - that's true but that's the current broken behavior
`When I choose repeat 3 and one room - it will clean twice that room` - cleaned only once

Debug data:
```json
{
  "domain": "xiaomi_miio",
  "service": "vacuum_clean_segment",
  "serviceData": {
    "segments": [
      21,
      21,
      21
    ],
    "entity_id": "vacuum.roborock_vacuum_s5e"
  }
}
```

`When I choose repeat 2 and 2 rooms, it will clean first room twice but second only once.` - cleaned both rooms only once (21 and then 17).

Debug data:
```json
{
  "domain": "xiaomi_miio",
  "service": "vacuum_clean_segment",
  "serviceData": {
    "segments": [
      21,
      17,
      21,
      17
    ],
    "entity_id": "vacuum.roborock_vacuum_s5e"
  }
}
```

The only way to get it working exactly the same as with Xiaomi Home application is to override default template as I've posted here: https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/294#issuecomment-1007755199
Also see this: https://github.com/home-assistant/core/issues/59110#issuecomment-1007558447

Firmware version on my Roborock is: 3.5.8_1566 (from 20.12.2021).

**Comment by PiotrMachowski** [comment]
@bearpawmaxim can you show your config?

**Comment by bearpawmaxim** [comment]
@PiotrMachowski, ofc! Here Is it:
`
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.roborock_s7_map
calibration_source:
  camera: true
entity: vacuum.rosha
vacuum_platform: default
map_modes:
  - name: Уборка зоны
    icon: mdi:select-drag
    run_immediately: false
    coordinates_rounding: true
    selection_type: MANUAL_RECTANGLE
    max_selections: 5
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: xiaomi_miio.vacuum_clean_zone
      service_data:
        zone: '[[selection]]'
        repeats: '[[repeats]]'
        entity_id: '[[entity_id]]'
    predefined_selections: []
    variables: {}
  - name: Точка назначения
    icon: mdi:map-marker-plus
    run_immediately: false
    coordinates_rounding: true
    selection_type: MANUAL_POINT
    max_selections: 999
    repeats_type: NONE
    max_repeats: 1
    service_call_schema:
      service: xiaomi_miio.vacuum_goto
      service_data:
        x_coord: '[[point_x]]'
        y_coord: '[[point_y]]'
        entity_id: '[[entity_id]]'
    predefined_selections: []
    variables: {}
  - name: Комнаты
    icon: mdi:floor-plan
    run_immediately: false
    coordinates_rounding: true
    selection_type: ROOM
    max_selections: 999
    repeats_type: REPEAT
    max_repeats: 3
    service_call_schema:
      service: xiaomi_miio.vacuum_clean_segment
      service_data:
        segments: '[[selection]]'
        entity_id: '[[entity_id]]'
    predefined_selections:
      - id: '16'
        icon:
          name: mdi:broom
          x: 30300
          'y': 30400
        label:
          text: Room 16
          x: 30300
          'y': 30400
          offset_y: 35
        outline:
          - - 28200
            - 28950
          - - 32400
            - 28950
          - - 32400
            - 31850
          - - 28200
            - 31850
      - id: '17'
        icon:
          name: mdi:broom
          x: 29525
          'y': 26975
        label:
          text: Room 17
          x: 29525
          'y': 26975
          offset_y: 35
        outline:
          - - 27000
            - 25200
          - - 32050
            - 25200
          - - 32050
            - 28750
          - - 27000
            - 28750
      - id: '18'
        icon:
          name: mdi:broom
          x: 24275
          'y': 27225
        label:
          text: Room 18
          x: 24275
          'y': 27225
          offset_y: 35
        outline:
          - - 23400
            - 25100
          - - 25150
            - 25100
          - - 25150
            - 29350
          - - 23400
            - 29350
      - id: '19'
        icon:
          name: mdi:broom
          x: 23700
          'y': 31350
        label:
          text: Room 19
          x: 23700
          'y': 31350
          offset_y: 35
        outline:
          - - 23200
            - 30850
          - - 24200
            - 30850
          - - 24200
            - 31850
          - - 23200
            - 31850
      - id: '20'
        icon:
          name: mdi:broom
          x: 24900
          'y': 30975
        label:
          text: Room 20
          x: 24900
          'y': 30975
          offset_y: 35
        outline:
          - - 24200
            - 30150
          - - 25600
            - 30150
          - - 25600
            - 31800
          - - 24200
            - 31800
      - id: '21'
        icon:
          name: mdi:broom
          x: 27175
          'y': 30975
        label:
          text: Room 21
          x: 27175
          'y': 30975
          offset_y: 35
        outline:
          - - 26300
            - 30150
          - - 28050
            - 30150
          - - 28050
            - 31800
          - - 26300
            - 31800
      - id: '22'
        icon:
          name: mdi:broom
          x: 26100
          'y': 26925
        label:
          text: Room 22
          x: 26100
          'y': 26925
          offset_y: 35
        outline:
          - - 25200
            - 25150
          - - 27000
            - 25150
          - - 27000
            - 28700
          - - 25200
            - 28700
      - id: '23'
        icon:
          name: mdi:broom
          x: 26225
          'y': 29425
        label:
          text: Room 23
          x: 26225
          'y': 29425
          offset_y: 35
        outline:
          - - 24250
            - 28750
          - - 28200
            - 28750
          - - 28200
            - 30100
          - - 24250
            - 30100
    variables: {}
tiles:
  - tile_id: status
    entity: vacuum.rosha
    label: Статус
    attribute: status
    icon: mdi:robot-vacuum
    translations:
      starting: Начало уборки
      charger disconnected: Зарядное устройство отключено
      idle: Ожидание
      remote control active: Включено управление через пульт
      cleaning: Уборка
      returning home: Возвращение на базу
      manual mode: Ручной режим
      charging: Зарядка
      charging problem: Проблема с зарядкой
      paused: Пауза
      spot cleaning: Уборка точки
      error: Ошибка
      shutting down: Выключение
      updating: Обновление
      docking: Остановка у базы
      going to target: Направление до точки
      zoned cleaning: Уборка зоны
      segment cleaning: Уборка
      emptying the bin: Очистка бака
      charging complete: Зарядка завершена
      device offline: Устройство не в сети
  - tile_id: battery_level
    entity: vacuum.rosha
    label: Уровень заряда
    attribute: battery_level
    icon: mdi:battery-charging-100
    unit: '%'
  - tile_id: fan_speed
    entity: vacuum.rosha
    label: Мощность всасывания
    attribute: fan_speed
    icon: mdi:fan
    translations:
      silent: Тихий
      standard: Стандарт
      medium: Средний
      turbo: Турбо
      auto: Авто
      gentle: Слабый
  - tile_id: sensor_dirty_left
    label: Уровень загрязнения датчиков
    unit: ч
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: true
      service_data:
        command: reset_consumable
        params: sensor_dirty_time
        entity_id: vacuum.rosha
    entity: sensor.roborock_vacuum_a15_sensor_dirty_left
    icon: mdi:eye-outline
    precision: 0
    translations: {}
  - tile_id: filter_left
    label: Ресурс фильтра
    unit: ч
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: true
      service_data:
        command: reset_consumable
        params: filter_work_time
        entity_id: vacuum.rosha
    entity: sensor.roborock_vacuum_a15_filter_left
    icon: mdi:air-filter
    precision: 0
    translations: {}
  - tile_id: main_brush_left
    label: Ресурс основной щётки
    unit: ч
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: true
      service_data:
        command: reset_consumable
        params: main_brush_work_time
        entity_id: vacuum.rosha
    entity: sensor.roborock_vacuum_a15_main_brush_left
    icon: mdi:brush
    precision: 0
    translations: {}
  - tile_id: side_brush_left
    label: Ресурс боковой щётки
    unit: ч
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: true
      service_data:
        command: reset_consumable
        params: side_brush_work_time
        entity_id: vacuum.rosha
    entity: sensor.roborock_vacuum_a15_side_brush_left
    icon: mdi:brush
    precision: 0
    translations: {}
  - tile_id: cleaning_count
    label: Число уборок
    entity: sensor.roborock_vacuum_a15_total_clean_count
    icon: mdi:counter
    precision: 0
    translations: {}
icons:
  - icon: mdi:play
    conditions:
      - entity: vacuum.rosha
        value_not: cleaning
      - entity: vacuum.rosha
        value_not: error
      - entity: vacuum.rosha
        value_not: returning
    tooltip: Старт
    tap_action:
      action: call-service
      service: vacuum.start
      service_data:
        entity_id: vacuum.rosha
  - icon: mdi:pause
    conditions:
      - entity: vacuum.rosha
        value_not: docked
      - entity: vacuum.rosha
        value_not: idle
      - entity: vacuum.rosha
        value_not: error
      - entity: vacuum.rosha
        value_not: paused
    tooltip: Пауза
    tap_action:
      action: call-service
      service: vacuum.pause
      service_data:
        entity_id: vacuum.rosha
  - icon: mdi:stop
    conditions:
      - entity: vacuum.rosha
        value_not: docked
      - entity: vacuum.rosha
        value_not: idle
      - entity: vacuum.rosha
        value_not: error
      - entity: vacuum.rosha
        value_not: paused
    tooltip: Стоп
    tap_action:
      action: call-service
      service: vacuum.stop
      service_data:
        entity_id: vacuum.rosha
  - icon: mdi:home-map-marker
    conditions:
      - entity: vacuum.rosha
        value_not: docked
      - entity: vacuum.rosha
        value_not: returning
    tooltip: Вернуть к базе
    tap_action:
      action: call-service
      service: vacuum.return_to_base
      service_data:
        entity_id: vacuum.rosha
  - icon: mdi:target-variant
    conditions:
      - entity: vacuum.rosha
        value_not: docked
      - entity: vacuum.rosha
        value_not: error
      - entity: vacuum.rosha
        value_not: cleaning
      - entity: vacuum.rosha
        value_not: returning
    tooltip: Убрать точку
    tap_action:
      action: call-service
      service: vacuum.clean_spot
      service_data:
        entity_id: vacuum.rosha
  - icon: mdi:map-marker
    tooltip: Обнаружить
    tap_action:
      action: call-service
      service: vacuum.locate
      service_data:
        entity_id: vacuum.rosha
  - icon: mdi:fan-remove
    conditions:
      - entity: vacuum.rosha
        attribute: fan_speed
        value: Silent
    tooltip: Изменить мощность всасывания
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.rosha
        fan_speed: Standard
  - icon: mdi:fan-speed-1
    conditions:
      - entity: vacuum.rosha
        attribute: fan_speed
        value: Standard
    tooltip: Изменить мощность всасывания
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.rosha
        fan_speed: Medium
  - icon: mdi:fan-speed-2
    conditions:
      - entity: vacuum.rosha
        attribute: fan_speed
        value: Medium
    tooltip: Изменить мощность всасывания
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.rosha
        fan_speed: Turbo
  - icon: mdi:fan-speed-3
    conditions:
      - entity: vacuum.rosha
        attribute: fan_speed
        value: Turbo
    tooltip: Изменить мощность всасывания
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.rosha
        fan_speed: Silent
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.rosha
        attribute: fan_speed
        value_not: Silent
      - entity: vacuum.rosha
        attribute: fan_speed
        value_not: Standard
      - entity: vacuum.rosha
        attribute: fan_speed
        value_not: Medium
      - entity: vacuum.rosha
        attribute: fan_speed
        value_not: Turbo
    tooltip: Изменить мощность всасывания
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.rosha
        fan_speed: Silent
`

The issue is the same: when I select room cleaning and set repeat count to 2 or 3, the vacuum cleans the room only once.

**Comment by PiotrMachowski** [comment]
@bearpawmaxim well, your config doesn't contain the fix. Also it seems that you have unnecessarily clicked "generate static config" button. You can use following config:
```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.roborock_s7_map
calibration_source:
  camera: true
entity: vacuum.rosha
vacuum_platform: default
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_clean_segment
  - template: vacuum_clean_segment
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: vacuum.send_command
      service_data:
        command: app_segment_clean
        entity_id: '[[entity_id]]'
        params:
          - segments: '[[selection]]'
            repeat: '[[repeats]]'
    predefined_selections:
      - id: '16'
        icon:
          name: mdi:broom
          x: 30300
          'y': 30400
        label:
          text: Room 16
          x: 30300
          'y': 30400
          offset_y: 35
        outline:
          - - 28200
            - 28950
          - - 32400
            - 28950
          - - 32400
            - 31850
          - - 28200
            - 31850
      - id: '17'
        icon:
          name: mdi:broom
          x: 29525
          'y': 26975
        label:
          text: Room 17
          x: 29525
          'y': 26975
          offset_y: 35
        outline:
          - - 27000
            - 25200
          - - 32050
            - 25200
          - - 32050
            - 28750
          - - 27000
            - 28750
      - id: '18'
        icon:
          name: mdi:broom
          x: 24275
          'y': 27225
        label:
          text: Room 18
          x: 24275
          'y': 27225
          offset_y: 35
        outline:
          - - 23400
            - 25100
          - - 25150
            - 25100
          - - 25150
            - 29350
          - - 23400
            - 29350
      - id: '19'
        icon:
          name: mdi:broom
          x: 23700
          'y': 31350
        label:
          text: Room 19
          x: 23700
          'y': 31350
          offset_y: 35
        outline:
          - - 23200
            - 30850
          - - 24200
            - 30850
          - - 24200
            - 31850
          - - 23200
            - 31850
      - id: '20'
        icon:
          name: mdi:broom
          x: 24900
          'y': 30975
        label:
          text: Room 20
          x: 24900
          'y': 30975
          offset_y: 35
        outline:
          - - 24200
            - 30150
          - - 25600
            - 30150
          - - 25600
            - 31800
          - - 24200
            - 31800
      - id: '21'
        icon:
          name: mdi:broom
          x: 27175
          'y': 30975
        label:
          text: Room 21
          x: 27175
          'y': 30975
          offset_y: 35
        outline:
          - - 26300
            - 30150
          - - 28050
            - 30150
          - - 28050
            - 31800
          - - 26300
            - 31800
      - id: '22'
        icon:
          name: mdi:broom
          x: 26100
          'y': 26925
        label:
          text: Room 22
          x: 26100
          'y': 26925
          offset_y: 35
        outline:
          - - 25200
            - 25150
          - - 27000
            - 25150
          - - 27000
            - 28700
          - - 25200
            - 28700
      - id: '23'
        icon:
          name: mdi:broom
          x: 26225
          'y': 29425
        label:
          text: Room 23
          x: 26225
          'y': 29425
          offset_y: 35
        outline:
          - - 24250
            - 28750
          - - 28200
            - 28750
          - - 28200
            - 30100
          - - 24250
            - 30100
```
