### ISSUE TITLE
marotoweb/viomise vacuum_clean_zone_predefined

### ISSUE THREAD

**Issue by thumDer** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#322]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Since the latest updates some functions for my Viomi SE stopped working. Previously it was working fine with the `default` platform using non-template map modes, with `PREDEFINED_RECTANGLE` and `PREDEFINED_POINT` `selection_type`s. Since these modes are not working anymore (it throws the following error on the UI: `Failed to call service 'vacuum/do_zones'. Service not found.`) I've changed the platform to `marotoweb/viomise` and while `vacuum_clean_point_predefined` is working as expected `vacuum_clean_zone_predefined` does nothing, only the Success notification flashes up on the card, and no reaction from the vacuum, only the following line in the log:
```
2022-01-17 21:38:23 ERROR (MainThread) [custom_components.viomise.vacuum] Unable to clean zone: {'code': -9998, 'message': 'user ack invalid'}
```

It might be related to [this](https://github.com/marotoweb/home-assistant-vacuum-viomise/issues/15) and [this](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/215)

### What version of a card has described problem?

v2.0.10

### What was the last working version card?

v2.0.8

### What vacuum model do you have problems with?

Viomi SE

### Which integration do you use to control your vacuum (link)?

https://github.com/marotoweb/home-assistant-vacuum-viomise

### What browser (browsers/apps) does have this problem?

Firefox

### What version of Home Assistant do you use?

core-2021.10.2

### What type of installation are you running?

Home Assistant Supervised

### Card's configuration

Current:
```yaml
type: custom:xiaomi-vacuum-map-card
title: Viomi Vacuum Map Card
entity: vacuum.viomi_se
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
vacuum_platform: marotoweb/viomise
map_modes:
  - template: vacuum_clean_zone_predefined
    predefined_selections:
      - zones:
          - - 1
            - 0.2
            - 2.2
            - -3.4
        label:
          text: Kitchen
          x: 1.5
          'y': -1.5
          offset_y: 35
        icon:
          name: mdi:pot-mix
          x: 1.5
          'y': -1.5
      - zones:
          - - -3
            - -3.4
            - 1
            - 0.2
        label:
          text: Living Room
          x: -1.5
          'y': -1.5
          offset_y: 35
        icon:
          name: mdi:television
          x: -1.5
          'y': -1.5
      - zones:
          - - 0.5
            - -4.9
            - 2.2
            - -3.4
        label:
          text: Hall
          x: 1.5
          'y': -3.9
          offset_y: 35
        icon:
          name: mdi:shoe-sneaker
          x: 1.5
          'y': -3.9
      - zones:
          - - 0.5
            - -7
            - 2.2
            - -4.9
        label:
          text: Bathroom
          x: 1.5
          'y': -5.5
          offset_y: 35
        icon:
          name: mdi:bathtub
          x: 1.5
          'y': -5.5
      - zones:
          - - -3
            - -7
            - 0.5
            - -3.4
        label:
          text: Bedroom
          x: -1.5
          'y': -5.5
          offset_y: 35
        icon:
          name: mdi:bed
          x: -1.5
          'y': -5.5
  - template: vacuum_clean_point_predefined
    predefined_selections:
      - position:
          - -1
          - -1
        label:
          text: Sofa
          x: -1
          'y': -1
          offset_y: 35
        icon:
          name: mdi:sofa
          x: -1
          'y': -1
two_finger_pan: true
map_locked: true
```

Previous:
```yaml
type: custom:xiaomi-vacuum-map-card
title: Viomi Vacuum Map Card
entity: vacuum.viomi_se
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
vacuum_platform: default
map_modes: 
  - name: Predefined zones
    icon: mdi:texture-box
    selection_type: PREDEFINED_RECTANGLE
    max_selections: 5
    repeats_type: INTERNAL
    max_repeats: 3
    service_call_schema:
      service: vacuum.do_zones
      service_data:
        zones: '[[selection]]'
        repeats: '[[repeats]]'
        predefined: 'true'
      target:
        entity_id: '[[entity_id]]'
    predefined_selections:
      - zones:
          - - 1
            - 0.2
            - 2.2
            - -3.4
        label:
          text: Kitchen
          x: 1.5
          'y': -1.5
          offset_y: 35
        icon:
          name: mdi:pot-mix
          x: 1.5
          'y': -1.5
      - zones:
          - - -3
            - -3.4
            - 1
            - 0.2
        label:
          text: Living Room
          x: -1.5
          'y': -1.5
          offset_y: 35
        icon:
          name: mdi:television
          x: -1.5
          'y': -1.5
      - zones:
          - - 0.5
            - -4.9
            - 2.2
            - -3.4
        label:
          text: Hall
          x: 1.5
          'y': -3.9
          offset_y: 35
        icon:
          name: mdi:shoe-sneaker
          x: 1.5
          'y': -3.9
      - zones:
          - - 0.5
            - -7
            - 2.2
            - -4.9
        label:
          text: Bathroom
          x: 1.5
          'y': -5.5
          offset_y: 35
        icon:
          name: mdi:bathtub
          x: 1.5
          'y': -5.5
      - zones:
          - - -3
            - -7
            - 0.5
            - -3.4
        label:
          text: Bedroom
          x: -1.5
          'y': -5.5
          offset_y: 35
        icon:
          name: mdi:bed
          x: -1.5
          'y': -5.5
  - name: Predefined Point
    icon: mdi:map-marker
    selection_type: PREDEFINED_POINT
    max_selections: 5
    repeats_type: NONE
    max_repeats: 3
    service_call_schema:
      service: vacuum.do_point
      service_data:
        point: '[[selection]]'
        repeats: '[[repeats]]'
        point_x: '[[point_x]]'
        point_y: '[[point_y]]'
        predefined: 'true'
      target:
        entity_id: '[[entity_id]]'
    predefined_selections:
      - position:
          - -1
          - -1
        label:
          text: Sofa
          x: -1
          'y': -1
          offset_y: 35
        icon:
          name: mdi:sofa
          x: -1
          'y': -1
  - template: vacuum_follow_path
  - template: vacuum_goto
two_finger_pan: true
map_locked: true
```
