### ISSUE TITLE
Frontend issue - Swipe action doesn't work on Map Card

### ISSUE THREAD

**Issue by sstefanowski** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#325]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

When Swipe is configured in the HA Frontend then it doesn't work on Android Companion Map.
It works well on any other card.

**Scenario:**
1. Add Xiaomi Map card to the one of the Tabs (of many tabs) placing the card on as the first one in the Tab
2. Edit the frontend config by adding the following lines in the Fronexd YAML editor
```
swipe_nav:
  wrap: true
  animate: swipe
  prevent_default: false
  swipe_amount: 15
```
3. Go to the Android Companion App, reload, try to swipe to the Tab with Map Card.
4. When Map Card is reached you cannot swipe to the Tabs on left to right anymore. The swipe gesture is probably hijacked by Map Card.

### What version of a card has described problem?

v2.0.10

### What vacuum model do you have problems with?

Roborock

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Android App

### What version of Home Assistant do you use?

core-2021.12.9

### What type of installation are you running?

Home Assistant OS

**Comment by PiotrMachowski** [comment]
Can add your cards config?

**Comment by sstefanowski** [comment]
Sure, here it is...
Note: I use nothing fancy. I cut-out the outline data from config below to reduce the length of the config.

```
type: custom:xiaomi-vacuum-map-card
card_mod:
  style: |
    ha-card .controls-wrapper {
      --map-card-internal-secondary-text-color: #55BBFF;
      --map-card-internal-primary-color: #55BBFF;
    }
    ha-card .map-wrapper {
      --map-card-internal-secondary-text-color: #55BBFF;
      --map-card-internal-primary-color: #55BBFF;
    }
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.roborock_vacuum_s5e
vacuum_platform: default
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 16
        outline:
      ...
        label:
          text: Bedroom
          x: 19930
          'y': 29100
          offset_y: 35
        icon:
          name: mdi:bed
          x: 19930
          'y': 29100
      - id: 17
        outline:
       ...
        label:
          text: Hall
          x: 22930
          'y': 24200
          offset_x: 35
        icon:
          name: mdi:none
          x: 22930
          'y': 24200
      - id: 18
        outline:
  ...
        label:
          text: Living Room
          x: 24400
          'y': 28000
          offset_x: 60
        icon:
          name: mdi:television
          x: 24400
          'y': 28000
      - id: 19
        outline:
    ....
        label:
          text: Tom's Bedroom
          x: 18930
          'y': 24500
          offset_y: 35
        icon:
          name: mdi:bed
          x: 18930
          'y': 24500
      - id: 20
        outline:
      ...
        label:
          text: Marta's Bedroom
          x: 18000
          'y': 21600
          offset_y: 35
        icon:
          name: mdi:bed
          x: 18000
          'y': 21600
      - id: 21
        outline:
    ...
        label:
          text: Bathroom
          x: 20700
          'y': 20700
          offset_x: 50
        icon:
          name: mdi:bathtub
          x: 20700
          'y': 20700
      - id: 22
        outline:
 ...
        label:
          text: Shower
          x: 27930
          'y': 24540
          offset_x: 45
        icon:
          name: mdi:shower-head
          x: 27930
          'y': 24540
  - template: vacuum_clean_zone_predefined
    predefined_selections:
      - zones:
    ...
        label:
          text: Kitchen
          x: 24500
          'y': 28000
          offset_y: 35
        icon:
          name: mdi:pot-mix
          x: 24500
          'y': 28000
      - zones:
  ...
        label:
          text: Table
          x: 24500
          'y': 30700
          offset_y: 35
        icon:
          name: mdi:kitchen
          x: 24500
          'y': 30700
  - template: vacuum_goto
  - template: vacuum_goto_predefined
  - template: vacuum_follow_path
```
