### ISSUE TITLE
Irobot Support

### ISSUE THREAD

**Issue by johnrobledo** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#328]
### Description

I would like support for Irobot Roomba vacuums.

### Solution

Roomba support

**Comment by johnrobledo** [comment]
- Yes
   - I dont think so
   - I dont think so
   - I dont think so

**Comment by PiotrMachowski** [comment]
Can you show all attributes of vacuum entity from dev tools?

**Comment by PiotrMachowski** [comment]
@johnrobledo ping

**Comment by sebPomme** [comment]
> Can you show all attributes of vacuum-related entities from dev tools?

This ?
```yaml
battery_level: 100
battery_icon: mdi:battery-charging-100
software_version: versionversionversion
status: Charging
bin_present: true
bin_full: false
friendly_name: roombastrid
supported_features: 13276
```

**Comment by PiotrMachowski** [comment]
@sebPomme yup, thank you. Can you confirm answers provided by @johnrobledo [in this comment](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/328#issuecomment-1018802467)?

**Comment by sebPomme** [comment]
- yes
- i don't think
- i don't think
- not embed on ha but yes
With something like this
```
type: button
tap_action:
  action: call-service
  service: vacuum.send_command
  service_data:
    entity_id: vacuum.roomba_n
    command: start
    params:
      pmap_id: <pmap_id>
      regions:
        - region_id: '<region_id>'
          type: <zid or rid>
```

**Comment by PiotrMachowski** [comment]
Thank you! I will try to add it to the card

**Comment by PiotrMachowski** [comment]
@sebPomme You can to use latest dev version of the card, it should support Roomba vacuums: [download](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/suites/7620744954/artifacts/316436698), [documentation](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/blob/dev/docs/templates/roomba.md)

**Comment by sebPomme** [comment]
@PiotrMachowski thanks I will try soon

**Comment by sebPomme** [comment]
I have some troubles with my vacuum and homeassistant this is why it's take so much time

**Comment by PiotrMachowski** [comment]
Here you have a newer build: https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/suites/7744115847/artifacts/324967747

**Comment by PiotrMachowski** [comment]
@sebPomme any progress on this topic?

**Comment by sebPomme** [comment]
Hi, 

I have some new now, I just put all works together.  
I m blocked with `Missing property: map_source`, I seem linked to this: 

![camera](https://user-images.githubusercontent.com/4944971/188322512-8c127e4f-7c56-4e22-9a23-e7d647d68f66.png)
Home assistant can't access to the roomba camera. 

By the way what are this numbers ? `outline: [[ 21458, 32131 ], [ 24235, 32152 ], [ 24194, 27409 ], [ 23181, 27409 ]]` ? that defined the room limits ? I'm not sure where I can find the equivalent for my roomba

**Comment by PiotrMachowski** [comment]
Do you have a camera with map in your HA and card can't access it?

These numbers are coordinates of corners of an outline - poligon that is displayed on the map to show boundaries of a room. They are used just for presentation purposes and are not sent to the vacuum. To get them for a specific room you have to:
 - open card editor 
 - change preset to "Setup Xiaomi"/"Setup Integer" in card's config 
 - change mode to "Path"
 - mark an outline of a room on the map
 - copy selection using a button in the editor 

https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/blob/dev/docs/templates/setup.md

**Comment by PiotrMachowski** [comment]
I think I will create a release today/tomorrow and fix possible problems in the future.

**Comment by sebPomme** [comment]
Hi, `Do you have a camera with map in your HA and card can't access it?` => I don't think I have roomba camera available from HA at all.
The camera seem be for roomba internal use only.

**Comment by PiotrMachowski** [comment]
@sebPomme actually I'm not asking about real camera, but "HA" camera, which is just a HA representation of a live image. Aaaand it is available for Roomba as well: https://github.com/jeremywillans/ha-rest980-roomba

**Comment by sebPomme** [comment]
Aaaah ok I see.  
This kind of map isn't available by default for roomba.

I already take a look at this https://github.com/jeremywillans/ha-rest980-roomba and the goal isn't reachable with the default HA roomba integration. To fill a map like this, we must add a new service(/server) [dorita](https://github.com/koalazak/dorita980) that communicate with the robot + add a php service to generate and manage the map for HA etc etc etc.  

Unfortunately I dont want to manage this kind of heavy setups just for the map.

**Comment by sebPomme** [comment]
IDK if someone else already have the setup to test it.
On my side I will not dig anymore.

**Comment by PiotrMachowski** [comment]
@sebPomme actually you don't need camera with live view, you can just use an image of the map, like here:
```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.roomba
map_source:
  image: '/local/images/roomba_map.png'
calibration_source:
  identity: true
vacuum_platform: Roomba
map_modes:
  - template: vacuum_clean_segment
    variables:
      pmap_id: abc123def456
    predefined_selections:
      - id: Bedroom
        variables:
          type: rid
        outline: [[ 21458, 32131 ], [ 24235, 32152 ], [ 24194, 27409 ], [ 23181, 27409 ]]
        label:
          text: "Bedroom"
          x: 22932
          y: 30339
          offset_y: 35
        icon:
          name: "mdi:bed"
          x: 22932
          y: 30339
      - id: Bathroom
        variables:
          type: zid
        outline: [[ 21478, 27237 ], [ 23048, 27250 ], [ 23061, 25655 ], [ 21478, 25680 ]]
        label:
          text: "Bathroom"
          x: 22282
          y: 26496
          offset_y: 35
        icon:
          name: "mdi:shower"
          x: 22282
          y: 26496
```
