### ISSUE TITLE
Pan/zoom affect all presets

### ISSUE THREAD

**Issue by rospogrigio** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#347]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

I am using 2 presets: one displaying a static image, and one using the camera from cloud map extractor. Now, if I unlock and pan/zoom the image from the camera, the other image gets panned/zoomed as well.
Moreover, the camera image displayed is differently cropped in the android app, compared to the web browser (should open another issue probably).

### What version of a card has described problem?

v2.0.10

### What vacuum model do you have problems with?

roborock.vacuum.s5

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Chrome, Android app

### What version of Home Assistant do you use?

2021.12.5

### What type of installation are you running?

Home Assistant Supervised

### Card's configuration

```yaml
preset_name: Static Map
calibration_source:
  calibration_points:
    - map:
        x: 148
        'y': 384
      vacuum:
        x: 25500
        'y': 25500
    - map:
        x: 195
        'y': 338
      vacuum:
        x: 26500
        'y': 26500
    - map:
        x: 148
        'y': 338
      vacuum:
        x: 25500
        'y': 26500
debug: false
default_mode: predefined_zones
entity: vacuum.xiaomi_vacuum_cleaner
map_source:
  image: /local/mappa_casa.png
tiles:
  - label: Status
    entity: vacuum.xiaomi_vacuum_cleaner
    attribute: status
    icon: mdi:robot-vacuum
  - label: Battery
    entity: vacuum.xiaomi_vacuum_cleaner
    attribute: battery_level
    icon: mdi:battery-charging-100
    unit: '%'
  - label: Fan Speed
    icon: mdi:fan
    entity: vacuum.xiaomi_vacuum_cleaner
    attribute: fan_speed
  - label: Sensors left
    icon: mdi:leak
    entity: sensor.roborock_sensor_dirty_left
    multiplier: 0.000011574
    precision: 1
    unit: ' days'
  - label: Filter left
    icon: mdi:air-filter
    entity: sensor.roborock_filter_left
    multiplier: 0.000011574
    precision: 1
    unit: ' days'
  - label: Main brush left
    icon: mdi:eslint
    entity: sensor.roborock_main_brush_left
    multiplier: 0.000011574
    precision: 1
    unit: ' days'
  - label: Side brush left
    icon: mdi:axis
    entity: sensor.roborock_side_brush_left
    multiplier: 0.000011574
    precision: 1
    unit: ' days'
  - label: Last Cleaned area
    icon: mdi:texture-box
    entity: sensor.roborock_last_clean_area
    unit: ' m²'
type: custom:xiaomi-vacuum-map-card
map_modes:
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 17
        outline:
          - - 23450
            - 27700
          - - 23450
            - 33320
          - - 28100
            - 33320
          - - 29550
            - 31800
          - - 29550
            - 27700
        label:
          text: Soggiorno
          x: 26550
          'y': 31300
          offset_y: 30
        icon:
          name: mdi:sofa
          x: 26550
          'y': 31300
      - id: 18
        outline:
          - - 29550
            - 29000
          - - 29550
            - 31800
          - - 30800
            - 33050
          - - 33700
            - 33050
          - - 33700
            - 29000
        label:
          text: Cucina
          x: 31800
          'y': 31300
          offset_y: 30
        icon:
          name: mdi:food-variant
          x: 31800
          'y': 31300
      - id: 19
        outline:
          - - 26950
            - 27700
          - - 29550
            - 27700
          - - 29550
            - 26450
          - - 28300
            - 26450
          - - 28300
            - 24600
          - - 28000
            - 24600
          - - 28000
            - 23950
          - - 26700
            - 23950
          - - 26700
            - 25150
          - - 26950
            - 25150
        label:
          text: Corridoio
          x: 28200
          'y': 28050
          offset_y: 30
  - template: vacuum_clean_zone_predefined
    predefined_selections:
      - zones:
          - - 29500
            - 29340
            - 32100
            - 32500
  - template: vacuum_clean_zone
  - template: vacuum_goto
map_locked: true
two_finger_pan: true
additional_presets:
  - preset_name: Live map
    entity: vacuum.xiaomi_vacuum_cleaner
    map_source:
      camera: camera.roborock_live_map
      crop:
        top: 230
        bottom: 220
        left: 50
        right: 20
    calibration_source:
      camera: true
    map_locked: true
    two_finger_pan: false
    tiles:
      - label: Status
        entity: vacuum.xiaomi_vacuum_cleaner
        attribute: status
        icon: mdi:robot-vacuum
      - label: Battery
        entity: vacuum.xiaomi_vacuum_cleaner
        attribute: battery_level
        icon: mdi:battery-charging-100
        unit: '%'
      - label: Fan Speed
        icon: mdi:fan
        entity: vacuum.xiaomi_vacuum_cleaner
        attribute: fan_speed
      - label: Sensors left
        icon: mdi:leak
        entity: sensor.roborock_sensor_dirty_left
        multiplier: 0.000011574
        precision: 1
        unit: ' days'
      - label: Filter left
        icon: mdi:air-filter
        entity: sensor.roborock_filter_left
        multiplier: 0.000011574
        precision: 1
        unit: ' days'
      - label: Main brush left
        icon: mdi:eslint
        entity: sensor.roborock_main_brush_left
        multiplier: 0.000011574
        precision: 1
        unit: ' days'
      - label: Side brush left
        icon: mdi:axis
        entity: sensor.roborock_side_brush_left
        multiplier: 0.000011574
        precision: 1
        unit: ' days'
      - label: Last Cleaned area
        icon: mdi:texture-box
        entity: sensor.roborock_last_clean_area
        unit: ' m²'
    map_modes:
      - template: vacuum_clean_segment
        predefined_selections:
          - id: 17
            outline:
              - - 23450
                - 27500
              - - 23450
                - 33320
              - - 28100
                - 33320
              - - 29550
                - 31800
              - - 29550
                - 27500
            label:
              text: Soggiorno
              x: 26550
              'y': 31000
              offset_y: 30
            icon:
              name: mdi:television
              x: 26550
              'y': 31000
          - id: 18
            outline:
              - - 29550
                - 29000
              - - 29550
                - 31800
              - - 30800
                - 33050
              - - 33700
                - 33050
              - - 33700
                - 29000
            label:
              text: Cucina
              x: 31800
              'y': 31000
              offset_y: 30
            icon:
              name: mdi:food-variant
              x: 31800
              'y': 31000
          - id: 19
            outline:
              - - 27020
                - 27500
              - - 29580
                - 27500
              - - 29580
                - 26450
              - - 28300
                - 26450
              - - 28300
                - 24600
              - - 28000
                - 24600
              - - 28000
                - 24080
              - - 26750
                - 24080
              - - 26750
                - 25150
              - - 27020
                - 25150
            label:
              text: Corridoio
              x: 28200
              'y': 27650
              offset_y: 30
      - template: vacuum_clean_zone_predefined
        predefined_selections:
          - zones:
              - - 29500
                - 29340
                - 32100
                - 32500
      - template: vacuum_clean_zone
      - template: vacuum_goto
```
