### ISSUE TITLE
Button to rotate the map

### ISSUE THREAD

**Issue by mat4444** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#354]
### Description

Hello,
It would be great to have a button to rotate the map in the card. Every time I restart a full clean-up, my vacuum generates a map with a random orientation (0 or 90°). It then messes up with the predefined zones that are not aligned anymore.

There is a button on the map that looks like a rotation button but it's frustrating to see it actually re-center the map. I would suggest to replace this icon with mdi:image-filter-center-focus for instance
![Untitled](https://user-images.githubusercontent.com/53400792/153234305-6e35d42a-3f93-4816-8093-9e0b30f9167e.png).

Hope you can consider this in a future release !

### Solution

- Consider adding a map rotation feature
- Change the re-center map icon

**Comment by PiotrMachowski** [comment]
This is not just a simple image rotation, rotated image requires a different calibration, so it can't be done in this card.

**Comment by mat4444** [comment]
Hello,
I am just wondering if you could consider changing the icone I circled in red ? IMHO, it's confusing and looks like a rotation button. 
![](https://user-images.githubusercontent.com/53400792/153234305-6e35d42a-3f93-4816-8093-9e0b30f9167e.png)
Since its purpose is to re-center the map, I can suggest to use an icon such as this one  : (mdi:image-filter-center-focus)
![image](https://user-images.githubusercontent.com/53400792/158392324-60cde8b5-0282-4345-aeb0-a6e462db7f44.png)
Thanks for reading me :) !

**Comment by cataseven** [comment]
card_mod:
  style: I
    #map-image {
       transform: rotate(270deg);
     }

**Comment by cataseven** [comment]
@mat4444 

Opened PR https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/pull/949

for quick install to test here is the js file: 

[xiaomi-vacuum-map-card.js](https://github.com/user-attachments/files/30677783/xiaomi-vacuum-map-card.js)

```
type: custom:xiaomi-vacuum-map-card
entity: vacuum.roborock
preset_name: Ground floor
map_source:
  camera: camera.roborock_ground_floor
calibration_source:
  camera: true
vacuum_platform: Roborock
map_rotation: 90
additional_presets:
  - preset_name: First floor
    entity: vacuum.roborock
    map_source:
      camera: camera.roborock_first_floor
    calibration_source:
      camera: true
    vacuum_platform: Roborock
map_view_storage_key: vacuum-overview 
```
