### ISSUE TITLE
Continous IP bans caused by the card on Home Assistant App

### ISSUE THREAD

**Issue by LC7894** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#357]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Hi there,

since the last major update of the card, I have problems when using the Home Assistant Companion App. 

When I am opening the HA Companion app and the last shown lovelace tab was the tab that includes the vacuum card, I always get an IP ban (I have set up HA to ban IPs after 3 tries). It looks like the card is refreshing in a very high frequency and then I get banned instantly. The problem occurs on both, IOS and Android phones.

My current workaround is to head to a Lovelace tab that doesn't include the vacuum card every time before I close the HA companion app. But, obviously this is not very user friendly. That's why I'm reporting the issue. 

### What version of a card has described problem?

v2.0.10

### What was the last working version card?

v1.2.3

### What vacuum model do you have problems with?

roborock.vacuum.s5e

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

iOS/Android

### What version of Home Assistant do you use?

2022.2.6

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.roborock
vacuum_platform: default
map_modes:
  - template: vacuum_clean_segment
    predefined_selections:
      - id: xx
        outline:
          - xx
        label:
          text: Room X
          x: xx
          'y': xx
          offset_x: xx
		  offset_y: xx
        icon:
          name: mdi:xx
          x: xx
          'y': xx
  - template: vacuum_goto_predefined
    predefined_selections:
      - position:
          - xx
          - xx
        label:
          text: xx
          x: xx
          'y': xx
          offset_y: xx
        icon:
          name: mdi:xx
          x: xx
          'y': xx
  - template: vacuum_clean_zone
  - template: vacuum_goto
map_locked: true
two_finger_pan: false
```

**Comment by LC7894** [comment]
Good to know that you also have this problem. I hope there is a way to solve it. The issue most probably arises while retrieving the image as the image flickers when opening the app (until one gets kicked because of the IP ban) 👍

**Comment by Pete1979** [comment]
I also have this problem. Tried different solutions, but ended up removing the card for now. Hoping this can be fixed soon.

**Comment by PiotrMachowski** [comment]
@Pete1979 my temporary solution is to have 2 presets: default one with map image (not from map_extractor) and live one, connected to map_extractor

**Comment by Pete1979** [comment]
@PiotrMachowski Thanks, not entierly sure how to set that up.
Would it be enough to add this part?
```
additional_presets:
  - preset_name: Static image
    entity: vacuum.xiaomi_vacuum
    map_source:
      image: "/local/map_image.png"
```

Or do i need to add the entire config for it?

**Comment by PiotrMachowski** [comment]
Actually this setup would add second preset with map image, you have to move your config to additional_presets instead:
```yaml
type: custom:xiaomi-vacuum-map-card
preset_name: Static image
entity: vacuum.xiaomi_vacuum
map_source:
  image: '/local/map_image.png'
calibration_source:
  identity: true # if you don't want to calibrate image
additional_presets:
  - entity: vacuum.xiaomi_vacuum
    preset_name: Live map
    map_source:
      camera: camera.xiaomi_cloud_map_extractor
    calibration_source:
      camera: true
    map_modes:
      - template: vacuum_clean_zone
      - template: vacuum_goto
      - template: vacuum_clean_zone_predefined
        predefined_selections:
          - zones: [[25500, 25500, 26500, 26500]]
          - zones: [[24245, 25190, 27495, 27940], [27492, 26789, 28942, 27889]]
```

**Comment by Pete1979** [comment]
Thanks, got it working i a sense, but on the live map, my predefined selections, zones and labels doesn't show.

**Comment by PiotrMachowski** [comment]
@Pete1979 Paste your config here

**Comment by Pete1979** [comment]
```
type: custom:xiaomi-vacuum-map-card
preset_name: Static image
entity: vacuum.roborock_vacuum_s6
map_source:
  image: /local/map_image.png
calibration_source:
  identity: true
additional_presets:
  - entity: vacuum.roborock_vacuum_s6
    preset_name: Live map
    map_source:
      camera: camera.xiaomi_cloud_map_extractor
    calibration_source:
      camera: true
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_goto_predefined
    predefined_selections:
      - position:
          - 23232
          - 22419
        icon:
          name: mdi:vacuum
          x: 23232
          'y': 22419
  - template: vacuum_clean_zone_predefined
    predefined_selections:
      - zones:
          - - 18539
            - 26234
            - 22337
            - 32477
        label:
          text: Vardagsrum
          x: 20536
          'y': 30996
      - zones:
          - - 22355
            - 28184
            - 25664
            - 32506
        label:
          text: Kök
          x: 24014
          'y': 31274
      - zones:
          - - 22392
            - 25120
            - 26345
            - 28253
        label:
          text: Hall1
          x: 24339
          'y': 26821
      - zones:
          - - 22380
            - 22196
            - 23957
            - 25435
        label:
          text: Hall2
          x: 23272
          'y': 24084
      - zones:
          - - 18659
            - 19638
            - 22306
            - 23417
        label:
          text: Sovrum1
          x: 20396
          'y': 21255
      - zones:
          - - 18648
            - 23480
            - 22230
            - 26222
        label:
          text: Sovrum2
          x: 20489
          'y': 25012
      - zones:
          - - 24042
            - 22282
            - 26157
            - 25007
        label:
          text: Badrum
          x: 25081
          'y': 23574

```

**Comment by PiotrMachowski** [comment]
Map modes have to be in additional preset as well:
```yaml
type: custom:xiaomi-vacuum-map-card
preset_name: Static image
entity: vacuum.roborock_vacuum_s6
map_source:
  image: /local/map_image.png
calibration_source:
  identity: true
additional_presets:
  - entity: vacuum.roborock_vacuum_s6
    preset_name: Live map
    map_source:
      camera: camera.xiaomi_cloud_map_extractor
    calibration_source:
      camera: true
    map_modes:
      - template: vacuum_clean_zone
      - template: vacuum_goto
      - template: vacuum_goto_predefined
        predefined_selections:
          - position:
              - 23232
              - 22419
            icon:
              name: mdi:vacuum
              x: 23232
              'y': 22419
      - template: vacuum_clean_zone_predefined
        predefined_selections:
          - zones:
              - - 18539
                - 26234
                - 22337
                - 32477
            label:
              text: Vardagsrum
              x: 20536
              'y': 30996
          - zones:
              - - 22355
                - 28184
                - 25664
                - 32506
            label:
              text: Kök
              x: 24014
              'y': 31274
          - zones:
              - - 22392
                - 25120
                - 26345
                - 28253
            label:
              text: Hall1
              x: 24339
              'y': 26821
          - zones:
              - - 22380
                - 22196
                - 23957
                - 25435
            label:
              text: Hall2
              x: 23272
              'y': 24084
          - zones:
              - - 18659
                - 19638
                - 22306
                - 23417
            label:
              text: Sovrum1
              x: 20396
              'y': 21255
          - zones:
              - - 18648
                - 23480
                - 22230
                - 26222
            label:
              text: Sovrum2
              x: 20489
              'y': 25012
          - zones:
              - - 24042
                - 22282
                - 26157
                - 25007
            label:
              text: Badrum
              x: 25081
              'y': 23574
    
```

**Comment by Pete1979** [comment]
Think i solved it, swappen the order for Live and static map
```
type: custom:xiaomi-vacuum-map-card
preset_name: Live Map
entity: vacuum.roborock_vacuum_s6
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
additional_presets:
  - entity: vacuum.roborock_vacuum_s6
    preset_name: Static Map
    map_source:
      image: /local/map_image.png
    calibration_source:
      identity: true
```
