### ISSUE TITLE
Support multi selection with xiaomi_miot.call_action

### ISSUE THREAD

**Issue by mced76** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#370]
### Description

xiaomi_miot.call_action works fine with my dreame D9 vacuum.
But with multiselection, value: '{"selects":[[[[selection_unwrapped]],[[repeats]],0,2,1]]}' is not correct.

The exact generated scipt with rooms should be 2 arrays
"{\"selects\":[[6,1,0,2,1],[8,1,0,2,2]]}"}]}}
First number (6, 8) in this sample is the room ID.
The last number is a simple order increment.

Please add this new feature in Vacuum Map Card to use the multi selection mode with rooms.

Thanks

### Solution

The exact generated scipt with rooms should be 2 arrays
"{\"selects\":[[6,1,0,2,1],[8,1,0,2,2]]}"}]}}
First number (6, 8) in this sample is the room ID.
The last number is a simple order increment.

**Comment by PiotrMachowski** [comment]
I don't think that I will implement it anytime soon... It doesn't really match current implementation and you can achieve it using a script

**Comment by mced76** [comment]
Hmm, the selection_unwrapped seems to send [6,8] when 2 rooms are selected
if I add the end of string, I will have "{"selects":[[[6,8], 1,0,2,1]}"}]}} and it doesn't match with the vaccum json string.
I dont see how I could have the correct string in Yaml without change the "selection_unwrapped" code... 
thx

**Comment by PiotrMachowski** [comment]
You can't do it using just card's config. You can create a script that will consume selections and repeats (in a normal way) and call xiaomi_miot.call_action service

**Comment by mced76** [comment]
Sorry, but I don't understand your solution.
What type of script ? Is it an Home assistant script ? The problem is the same. How transform params into arrays in Yaml ?
I need xiaomi_miot.call_action. If I use it in another script how can I transform selection into a array into the first Yaml HA script ?
Do you have you an example ? Thanks

For information, my template for multi selection areas. I can use selection but my problem is always here.

 - template: vacuum_clean_segment
    max_selections: 5
    repeats_type: EXTERNAL
    max_repeats: 5
    service_call_schema:
      service: xiaomi_miot.call_action
      service_data:
        entity_id: '[[entity_id]]'
        siid: 4
        aiid: 1
        params:
          - piid: 1
            value: 18
          - piid: 10
            value: '{"selects":[[[[selection_unwrapped]],[[repeats]],0,2,1]]}'
        force_params: true
...

**Comment by PiotrMachowski** [comment]
Yes, I'm talking about HA script. You can use templates to manipulate arrays and convert them to an appropriate format

**Comment by mced76** [comment]
Yes indeed, I will try this. Thx

**Comment by mced76** [comment]
It works !
Il write this script. I Think it coul be better. I didn't found how to avoid the json automatic translate without add a ' before the result value ;-(

Here is the script for the dreame D9 vacuum

alias: vacuum_clean_rooms
sequence:
  - service: xiaomi_miot.call_action
    data:
      entity_id: '{{entity_id}}'
      siid: 4
      aiid: 1
      params:
        - piid: 1
          value: 18
        - piid: 10
          value: >
            {% set ns = namespace(str_rooms='{"selects":[') %}  {%- for x in
            rooms -%}
              {% set ns.str_rooms = ns.str_rooms ~ '[' ~ x ~ ',' ~ repeats ~ ',0,2,' ~ loop.index ~ ']' %}
              {%- if not loop.last %}
               {%  set ns.str_rooms = ns.str_rooms ~ ',' %}
              {%- endif %}
            {%- endfor -%}  {% set ns.str_rooms = ns.str_rooms ~ ']}' %}   
            '{{ns.str_rooms}} 
      force_params: true
fields:
  rooms:
    description: Array of rooms ID
  repeats:
    description: Repeat zone
  entity_id:
    description: Id
mode: single
icon: mdi:vacuum-outline


and to call this into the Map template UI
  - template: vacuum_clean_segment
    max_selections: 7
    repeats_type: EXTERNAL
    max_repeats: 5
    service_call_schema:
      service: script.vacuum_rooms
      service_data:
        rooms: '[[selection]]'
        repeats: '[[repeats]]'
        entity_id: '[[entity_id]]'
    predefined_selections:
...

**Comment by foxx99** [comment]
Could You please help me, I'm trying to put my dreame D9 to work with HA. I've got maps from cloud map extractor, I've integrated D9 using Xiaomi miot (I've only got few attributes, if I use HACS dreame D9 integration I've got more like filter time left, brush time left). I've created this script in HA script menu:
```
alias: vacuum_clean_rooms
sequence:
  - service: xiaomi_miot.call_action
    data:
      entity_id: '{{entity_id}}'
      siid: 4
      aiid: 1
      params:
        - piid: 1
          value: 18
        - piid: 10
          value: >
            {% set ns = namespace(str_rooms='{"selects":[') %}  {%- for x in
            rooms -%}
              {% set ns.str_rooms = ns.str_rooms ~ '[' ~ x ~ ',' ~ repeats ~ ',0,2,' ~ loop.index ~ ']' %}
              {%- if not loop.last %}
               {%  set ns.str_rooms = ns.str_rooms ~ ',' %}
              {%- endif %}
            {%- endfor -%}  {% set ns.str_rooms = ns.str_rooms ~ ']}' %}   
            '{{ns.str_rooms}} 
      force_params: true
fields:
  rooms:
    description: Array of rooms ID
  repeats:
    description: Repeat zone
  entity_id:
    description: Id
mode: single
icon: mdi:vacuum-outline
```
and this is my UI card
```
type: custom:xiaomi-vacuum-map-card
entity: vacuum.p2009_d4d2d6f9d6cd
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_modes:
  - template: vacuum_goto
  - template: vacuum_clean_zone
    max_selections: 1
    repeats_type: EXTERNAL
    max_repeats: 5
    service_call_schema: null
    service: xiaomi_miot.call_action
    service_data:
      entity_id: '[[entity_id]]'
      siid: 4
      aiid: 1
      params:
        - piid: 1
          value: 19
        - piid: 10
          value: '{"areas":[[[[selection_unwrapped]],[[repeats]],1,1]]}'
      force_params: true
  - template: vacuum_clean_segment
    max_selections: 1
    repeats_type: EXTERNAL
    max_repeats: 5
    service_call_schema:
    service: xiaomi_miot.call_action
    service_data:
      entity_id: '[[entity_id]]'
      siid: 4
      aiid: 1
      params:
        - piid: 1
          value: 18
        - piid: 10
          value: '{"selects":[[[[selection_unwrapped]],[[repeats]],3,3,1]]}'
      force_params: true
    predefined_selections:
      - id: 4
        label:
          text: Room 4
          x: 300
          'y': 2925
          offset_y: 35
        icon:
          name: mdi:broom
          x: 300
          'y': 2925
      - id: 5
        label:
          text: Room 5
          x: -3975
          'y': 1950
          offset_y: 35
        icon:
          name: mdi:broom
          x: -3975
          'y': 1950
      - id: 1
        label:
          text: Room 1
          x: 950
          'y': 3050
          offset_y: 35
        icon:
          name: mdi:broom
          x: 950
          'y': 3050
      - id: 6
        label:
          text: Room 6
          x: 1350
          'y': 5075
          offset_y: 35
        icon:
          name: mdi:broom
          x: 1350
          'y': 5075
      - id: 3
        label:
          text: Room 3
          x: -3575
          'y': 7050
          offset_y: 35
        icon:
          name: mdi:broom
          x: -3575
          'y': 7050
      - id: 2
        label:
          text: Room 2
          x: 650
          'y': 7775
          offset_y: 35
        icon:
          name: mdi:broom
          x: 650
          'y': 7775
vacuum_platform: send_command
```
this show after holding start button:
![image](https://user-images.githubusercontent.com/97547613/174325645-28e04116-703d-4418-8a57-fae445c8515a.png)
and this is log:
Logger: homeassistant.components.websocket_api.http.connection
Source: components/vacuum/__init__.py:292
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 16:35:20 (4 occurrences)
Last logged: 17:07:26

[140114656299904]
[140114396363024]
[140114487001872]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1704, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1741, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py", line 301, in async_send_command
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py", line 292, in send_command
    raise NotImplementedError()
NotImplementedError

what am I doing wrong?
