### ISSUE TITLE
La mappa scompare dopo aggiornamento a Home Assistant OS 2022.4.X

### ISSUE THREAD

**Issue by amastrogiacomo1968** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#378]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

The map disappears (camera_image message appears) after updating to version 2022.4.X of Home Assistant OS, up to version 2022.3.8 it works regularly

### What version of a card has described problem?

2.0.10

### What was the last working version card?

2.0.10

### What vacuum model do you have problems with?

Roborock S5 Max

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Chrome

### What version of Home Assistant do you use?

2022.4.X

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
- cards:
  - type: 'custom:xiaomi-vacuum-map-card'
    entity: vacuum.roborock_vacuum_s5e
    map_source:
      camera: camera.ambrogio
    language: it
    calibration_source:
      camera: true
```
