### ISSUE TITLE
Issue with displaying icons and labels

### ISSUE THREAD

**Issue by inviz-ize** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#379]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Hello! I'm not sure if it is a bug or I'm doing something wrong. I followed [this instruction](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/317#discussioncomment-2558884) and successfully got x & y coordinates, but icons and labels are displaying at the top left corner. browser log is saying that coordinates are NaN. What can be the reason?

![Screenshot 2022-04-13 at 13 16 02](https://user-images.githubusercontent.com/9848808/163169519-e8e6506c-cb8a-4765-b0e5-376c26c189be.png)
![Screenshot 2022-04-13 at 13 28 32](https://user-images.githubusercontent.com/9848808/163169538-3e947246-7ece-4f69-b9d0-c60477cebea6.png)
![Screenshot 2022-04-13 at 13 23 52](https://user-images.githubusercontent.com/9848808/163169556-5fc6a794-9781-422d-9d69-05c034b5204b.png)

### What version of a card has described problem?

v2.0.10

### What vacuum model do you have problems with?

dreame.vacuum.mb1808

### Which integration do you use to control your vacuum (link)?

https://github.com/al-one/hass-xiaomi-miot

### What browser (browsers/apps) does have this problem?

Chrome/Safari

### What version of Home Assistant do you use?

core-2022.4.3

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.vacuum_map
calibration_source:
  camera: true
entity: vacuum.ksiushka
vacuum_platform: default
map_modes:
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 5
        label:
          text: "Room 5"
          x: 1175
          y: -2000
          offset_y: 35
        icon:
          name: "mdi:teddy-bear"
          x: 1175
          y: -2000
      - id: 3
        label:
          text: "Room 3"
          x: -6725
          y: -2025
          offset_y: 35
        icon:
          name: "mdi:bed"
          x: -6725
          y: -2025
      - id: 6
        label:
          text: "Room 6"
          x: -2475
          y: -1600
          offset_y: 35
        icon:
          name: "mdi:broom"
          x: -2475
          y: -1600
      - id: 4
        label:
          text: "Room 4"
          x: -2550
          y: 550
          offset_y: 35
        icon:
          name: "mdi:broom"
          x: -2550
          y: 550
      - id: 2
        label:
          text: "Room 2"
          x: 1500
          y: 600
          offset_y: 35
        icon:
          name: "mdi:broom"
          x: 1500
          y: 600
      - id: 1
        label:
          text: "Room 1"
          x: -6975
          y: 1125
          offset_y: 35
        icon:
          name: "mdi:broom"
          x: -6975
          y: 1125
```
