### ISSUE TITLE
Map Mode selector broke the layout

### ISSUE THREAD

**Issue by MisterTdog** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#381]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Since recent update of Home Assistant, the card looks ugly :(
The Map Mode selector remains opened and break the layout.
![2022-04-14_11h47_13](https://user-images.githubusercontent.com/80855488/163359987-9d161a16-04b6-4bb0-a313-afbe5463d8b8.png)

### What version of a card has described problem?

v2.0.10

### What vacuum model do you have problems with?

xiaomi v1

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Edge/Chrome/Brave

### What version of Home Assistant do you use?

core-2022.4.3

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
title: Robot Aspirateur
preset_name: Live view
entity: vacuum.robot_aspirateur
map_source:
  camera: camera.aspirateur
  crop:
    top: 140
    bottom: 130
    left: 140
    right: 80
map_locked: true
calibration_source:
  camera: true
append_icons: true
icons:
  - icon: mdi:delete-empty
    tooltip: Vider le bac à poussière
    tap_action:
      action: call-service
      service: XIAOMI_MIIO.VACUUM_GOTO
      service_data:
        entity_id: vacuum.robot_aspirateur
        x_coord: 23150
        y_coord: 13750
  - icon: mdi:countertop
    tooltip: Nettoyer la cuisine
    tap_action:
      action: call-service
      service: XIAOMI_MIIO.vacuum_clean_zone
      service_data:
        entity_id: vacuum.robot_aspirateur
        zone:
          - - 22257
            - 13030
            - 25344
            - 16408
append_tiles: false
language: fr
map_modes:
  - template: vacuum_clean_zone_predefined
    predefined_selections:
      - zones:
          - - 23263
            - 23049
            - 27667
            - 25929
        label:
          text: Chambre
          x: 25465
          'y': 24489
          offset_y: 35
        icon:
          name: mdi:bed
          x: 25465
          'y': 24489
      - zones:
          - - 25335
            - 19700
            - 27967
            - 23135
        label:
          text: WC - SdB
          x: 26651
          'y': 21417.5
          offset_y: 35
        icon:
          name: mdi:shower
          x: 26651
          'y': 21417.5
      - zones:
          - - 20812
            - 19187
            - 25268
            - 22793
        label:
          text: Salon
          x: 23040
          'y': 20990
          offset_y: 35
        icon:
          name: mdi:sofa
          x: 23040
          'y': 20990
      - zones:
          - - 18494
            - 15652
            - 25268
            - 19258
        label:
          text: Salle à manger
          x: 21881
          'y': 17455
          offset_y: 35
        icon:
          name: mdi:table-chair
          x: 21881
          'y': 17455
      - zones:
          - - 25184
            - 15690
            - 27093
            - 19524
        label:
          text: Entrée
          x: 26138.5
          'y': 17607
          offset_y: 35
        icon:
          name: mdi:door
          x: 26138.5
          'y': 17607
      - zones:
          - - 22257
            - 13030
            - 25344
            - 16408
        label:
          text: Cuisine
          x: 23800.5
          'y': 14719
          offset_y: 35
        icon:
          name: mdi:countertop
          x: 23800.5
          'y': 14719
  - template: vacuum_clean_zone
  - template: vacuum_goto
tiles:
  - entity: vacuum.robot_aspirateur
    label: Statut
    attribute: status
    icon: mdi:robot-vacuum
    translations:
      Starting: Démarrage...
      Charger disconnected: Chargeur déconnecté
      Idle: Inactif
      Remote control active: Télécommande active
      Cleaning: Nettoyage
      Returning home: Retour à la station
      Manual mode: Mode manuel
      Charging: En charge
      Charging problem: Problème de chargement
      Paused: En pause
      Spot cleaning: Nettoyage ciblé
      Error: Erreur
      Shutting down: Arrêt en cours...
      Updating: Mise à jour
      Docking: Retour à la station
      Going to target: En route vers la cible
      Zoned cleaning: Nettoyage de zone
      Segment cleaning: Nettoyage de pièce
      Emptying the bin: Vidage du réservoir
      Charging complete: Chargement terminé
      Device offline: Hors ligne
  - entity: vacuum.robot_aspirateur
    label: Batterie
    attribute: battery_level
    icon: mdi:battery-charging-100
    unit: '%'
  - entity: vacuum.robot_aspirateur
    label: Puissance
    attribute: fan_speed
    icon: mdi:fan
    translations:
      Silent: Silencieux
      Standard: Standard
      Medium: Moyen
      Turbo: Turbo
      Auto: Auto
      Gentle: Calme
  - entity: sensor.robot_aspirateur_sensor_dirty_left
    label: Sensors left
    icon: mdi:eye-outline
    multiplier: 0.0002777777777777778
    precision: 1
    unit: h
    hold_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        command: reset_consumable
        params:
          - sensor_dirty_time
      target:
        entity_id: vacuum.robot_aspirateur
      confirmation:
        text: Les capteurs sont bien nettoyés ?
  - entity: sensor.robot_aspirateur_filter_left
    label: Filtre
    icon: mdi:air-filter
    multiplier: 0.0002777777777777778
    precision: 1
    unit: h
    hold_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        command: reset_consumable
        params:
          - filter_work_time
      target:
        entity_id: vacuum.robot_aspirateur
      confirmation:
        text: Le filtre est bien nettoyé ?
  - entity: sensor.robot_aspirateur_main_brush_left
    label: Brosse principale
    icon: mdi:brush
    multiplier: 0.0002777777777777778
    precision: 1
    unit: h
    hold_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        command: reset_consumable
        params:
          - main_brush_work_time
      target:
        entity_id: vacuum.robot_aspirateur
      confirmation:
        text: La brosse principale est bien nettoyée ?
  - entity: sensor.robot_aspirateur_side_brush_left
    label: Brosse latérale
    icon: mdi:brush
    multiplier: 0.0002777777777777778
    precision: 1
    unit: h
    hold_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        command: reset_consumable
        params:
          - side_brush_work_time
      target:
        entity_id: vacuum.robot_aspirateur
      confirmation:
        text: La brosse latérale est bien nettoyée ?
  - entity: sensor.robot_aspirateur_total_clean_count
    label: Nombre de nettoyages
    icon: mdi:counter
additional_presets:
  - preset_name: Static image
    entity: vacuum.robot_aspirateur
    map_locked: true
    map_source:
      image: /local/custom_lovelace/xiaomi_vacuum_map_card/carte.png
    calibration_source:
      calibration_points:
        - vacuum:
            x: 25450
            'y': 23150
          map:
            x: 370
            'y': 173
        - vacuum:
            x: 18550
            'y': 19250
          map:
            x: 34
            'y': 370
        - vacuum:
            x: 25150
            'y': 13150
          map:
            x: 357
            'y': 676
    map_modes:
      - template: vacuum_clean_zone_predefined
        predefined_selections:
          - zones:
              - - 23263
                - 23049
                - 27667
                - 25929
            label:
              text: Chambre
              x: 25465
              'y': 24489
              offset_y: 35
            icon:
              name: mdi:bed
              x: 25465
              'y': 24489
          - zones:
              - - 25335
                - 19700
                - 27967
                - 23135
            label:
              text: WC - SdB
              x: 26651
              'y': 21417.5
              offset_y: 35
            icon:
              name: mdi:shower
              x: 26651
              'y': 21417.5
          - zones:
              - - 20812
                - 19187
                - 25268
                - 22793
            label:
              text: Salon
              x: 23040
              'y': 20990
              offset_y: 35
            icon:
              name: mdi:sofa
              x: 23040
              'y': 20990
          - zones:
              - - 18494
                - 15652
                - 25268
                - 19258
            label:
              text: Salle à manger
              x: 21881
              'y': 17455
              offset_y: 35
            icon:
              name: mdi:table-chair
              x: 21881
              'y': 17455
          - zones:
              - - 25184
                - 15690
                - 27093
                - 19524
            label:
              text: Entrée
              color: red
              x: 26138.5
              'y': 17607
              offset_y: 35
            icon:
              name: mdi:door
              x: 26138.5
              'y': 17607
          - zones:
              - - 22257
                - 13030
                - 25344
                - 16408
            label:
              text: Cuisine
              x: 23800.5
              'y': 14719
              offset_y: 35
            icon:
              name: mdi:countertop
              x: 23800.5
              'y': 14719
      - template: vacuum_clean_zone
      - template: vacuum_goto
style: |
  .predefined-rectangle-wrapper  {
    --map-card-internal-predefined-rectangle-label-color: white;
    --map-card-internal-predefined-rectangle-label-color-selected: var(--map-card-internal-predefined-rectangle-icon-background-color-selected);
  }
  {% if (states("sensor.robot_aspirateur_sensor_dirty_left")) | float(0) < 0 %}
    :host 
      .tile-wrapper:nth-child(4) {
        border: 3px solid red;
      }
      .tile-wrapper:nth-child(4) > * > .tile-value {
        color: red;
        font-weight: bold;
      }
  {% endif %}
  {% if (states("sensor.robot_aspirateur_filter_left")) | float(0) < 0 %}
    :host 
      .tile-wrapper:nth-child(5) {
        border: 3px solid red;
      }
      .tile-wrapper:nth-child(5) > * > .tile-value {
        color: red;
        font-weight: bold;
      }
  {% endif %}
  {% if (states("sensor.robot_aspirateur_main_brush_left")) | float(0) < 0 %}
    :host 
      .tile-wrapper:nth-child(6) {
        border: 3px solid red;
      }
      .tile-wrapper:nth-child(6) > * > .tile-value {
        color: red;
        font-weight: bold;
      }
  {% endif %}
  {% if (states("sensor.robot_aspirateur_side_brush_left")) | float(0) < 0 %}
    :host 
      .tile-wrapper:nth-child(7) {
        border: 3px solid red;
      }
      .tile-wrapper:nth-child(7) > * > .tile-value {
        color: red;
        font-weight: bold;
      }
  {% endif %}
```
