### ISSUE TITLE
Rooms don't update when switching between presets

### ISSUE THREAD

**Issue by bigbangus** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#385]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

When switching between presets for my downstair and upstairs, the rooms won't automatically update.

![image](https://user-images.githubusercontent.com/91270101/164499765-2802369b-4628-4dcc-bea0-b6a7ada60848.png)
![image](https://user-images.githubusercontent.com/91270101/164499853-617a9135-579c-45a3-89a6-b32501f3a8b9.png)

My fix is to toggle between map modes. Is there another way?

### What version of a card has described problem?

v2.0.10

### What vacuum model do you have problems with?

roborock.vacuum.a15

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Chrome

### What version of Home Assistant do you use?

ghcr.io/linuxserver/homeassistant:2022.4.3-ls70

### What type of installation are you running?

Home Assistant Core

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
preset_name: Downstairs
title: Xiaomi Vacuum Map Card
entity: vacuum.roborock_vacuum_a15
activate_on_switch: true
activate:
  service: vacuum.send_command
  service_data:
    entity_id: vacuum.roborock_vacuum_a15
    command: load_multi_map
    params: 0
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
append_icons: true
icons:
  - icon: mdi:sync
    tooltip: Downstairs
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.roborock_vacuum_a15
        command: load_multi_map
        params: 0
map_modes:
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 16
        label:
          text: Bedroom
          x: 35050
          'y': 14125
          offset_y: 35
        icon:
          name: mdi:bed
          x: 35050
          'y': 14125
      - id: 27
        label:
          text: Living Room
          x: 30425
          'y': 15700
          offset_y: 35
        icon:
          name: mdi:television
          x: 30425
          'y': 15700
      - id: 25
        label:
          text: Dining
          x: 26575
          'y': 14675
          offset_y: 35
        icon:
          name: mdi:table-picnic
          x: 26575
          'y': 14675
      - id: 21
        label:
          text: Kitchen
          x: 27275
          'y': 19500
          offset_y: 35
        icon:
          name: mdi:chef-hat
          x: 27275
          'y': 19500
      - id: 17
        label:
          text: Master Bath
          x: 35925
          'y': 18900
          offset_y: 35
        icon:
          name: mdi:shower
          x: 35925
          'y': 18900
      - id: 26
        icon:
          name: mdi:broom
          x: 30025
          'y': 21375
      - id: 18
        label:
          text: Master Closet
          x: 32750
          'y': 20425
          offset_y: 35
        icon:
          name: mdi:hanger
          x: 32750
          'y': 20425
      - id: 22
        icon:
          name: mdi:washing-machine
          x: 25800
          'y': 22875
      - id: 19
        icon:
          name: mdi:broom
          x: 27875
          'y': 22125
      - id: 23
        icon:
          name: mdi:toilet
          x: 27900
          'y': 23700
      - id: 20
        label:
          text: Music Room
          x: 27775
          'y': 27250
          offset_y: 35
        icon:
          name: mdi:music-clef-treble
          x: 27775
          'y': 27250
  - template: vacuum_goto
  - template: vacuum_follow_path
additional_presets:
  - preset_name: Upstairs
    entity: vacuum.roborock_vacuum_a15
    activate_on_switch: true
    activate:
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.roborock_vacuum_a15
        command: load_multi_map
        params: 1
    map_source:
      camera: camera.xiaomi_cloud_map_extractor
    calibration_source:
      camera: true
    append_icons: true
    icons:
      - icon: mdi:sync
        tooltip: Upstairs
        tap_action:
          action: call-service
          service: vacuum.send_command
          service_data:
            entity_id: vacuum.roborock_vacuum_a15
            command: load_multi_map
            params: 1
    map_modes:
      - template: vacuum_clean_segment
        predefined_selections:
          - id: 2
            label:
              text: Office
              x: 24000
              'y': 23675
              offset_y: 35
            icon:
              name: mdi:monitor
              x: 24000
              'y': 23675
          - id: 1
            label:
              text: Kodi
              x: 31775
              'y': 23550
              offset_y: 35
            icon:
              name: mdi:broom
              x: 31775
              'y': 23550
          - id: 3
            label:
              text: Bathroom
              x: 27600
              'y': 23625
              offset_y: 35
            icon:
              name: mdi:toilet
              x: 27600
              'y': 23625
          - id: 4
            label:
              text: Loft
              x: 24225
              'y': 27350
              offset_y: 35
            icon:
              name: mdi:broom
              x: 24225
              'y': 27350
          - id: 5
            label:
              text: Georgie
              x: 31825
              'y': 27250
              offset_y: 35
            icon:
              name: mdi:broom
              x: 31825
              'y': 27250
          - id: 6
            label:
              text: Closet
              x: 27625
              'y': 27200
              offset_y: 35
            icon:
              name: mdi:broom
              x: 27625
              'y': 27200
      - template: vacuum_goto
      - template: vacuum_follow_path
```
