### ISSUE TITLE
Home Assistant support for Viomi Vacuum V8 (STYJ02YM)

### ISSUE THREAD

**Issue by jsantosdias** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#390]
### Integration repository

https://github.com/tykarol/home-assistant-viomi-vacuum-v8

### Supported features

- [X] Zone cleaning (using 4 coordinates)
- [X] Room cleaning (using room id/number)
- [X] Going to point (using 2 coordinates)
- [X] Cleaning a point (using 2 coordinates)
- [ ] Others

### Vacuum entity/entities

```yaml
Viomi Vacuum V8 --> vacuum.viomi_vacuum_v8
```

### Service calls

```yaml
clean_zone:
  description: Start the cleaning operation in the selected areas for the number of repeats indicated.
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.my_viomi_vacuum_v8"
    zone:
      description: Array of zones. Each zone is an array of 4 float values. The values are in meters, where (0, 0) is the robot attached to the docking station.
      example: "[[-1,-1,2,2]]"
    repeats:
      description: Number of cleaning repeats for each zone between 1 and 3.
      example: "1"

clean_area:
  description: Start the cleaning operation in the selected areas for the number of repeats indicated.
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.my_viomi_vacuum_v8"
    area:
      description: Array of areas. Each area is an array of 8 float values (4 points). The values are in meters, where (0, 0) is the robot attached to the docking station.
      example: "[[-2.75,-1.3,-2.75,-5.5,4.3,-5.5,0,-1.3]]"
    repeats:
      description: Number of cleaning repeats for each area between 1 and 3.
      example: "1"

clean_point:
  description: Start cleaning around the specified coordinate (spot cleaning).
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.my_viomi_vacuum_v8"
    point:
      description: Point.
      example: "[-2.75,-1.3]"

clean_segment:
  description: Start cleaning of the specified segment(s).
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.my_viomi_vacuum_v8"
    segments:
      description: Segments.
      example: "[10,11]"

xiaomi_clean_zone:
  description: Obsoleted, see vacuum_clean_zone.
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.my_viomi_vacuum_v8"
    zone:
      description: Array of zones. Each zone is an array of 4 float values. The values are in meters, where (0, 0) is the robot attached to the docking station.
      example: "[[-1,-1,2,2]]"
    repeats:
      description: Number of cleaning repeats for each zone between 1 and 3.
      example: "1"

xiaomi_clean_point:
  description: Obsoleted, see vacuum_goto.
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.my_viomi_vacuum_v8"
    point:
      description: An array specifying a coordinate pair.
      example: "[-1,2]"
```

**Comment by PiotrMachowski** [comment]
> ### Vacuum entity/entities
> ```yaml
> Viomi Vacuum V8 --> vacuum.viomi_vacuum_v8
> ```
I think I haven't described it good enough. Can you provide state and attributes of vacuum entity from HA dev tools?

**Comment by jsantosdias** [comment]
Sorry, newbie here!

 

 

Entity

vacuum.viomi_vacuum_v8

Viomi Vacuum V8

 

State

Docked

(In History it has been: returning to base, cleaning, waiting).

 

 

Attributes

fan_speed_list: Silent, Standard, Medium, Turbo

battery_level: 100

battery_icon: mdi:battery-charging-100

fan_speed: Standard

run_state: 5

mode: 0

err_state: 2105

battary_life: 100

box_type: 1

mop_type: 0

s_time: 0

s_area: 0

suction_grade: 1

water_grade: 12

remember_map: 1

has_map: 1

is_mop: 0

has_newmap: 0

hw_info: 1.0.3

sw_info: 3.5.3_0017

start_time: 0

order_time: 0

v_state: 10

zone_data: 0

repeat_state: 0

light_state: 1

is_charge: 0

is_work: 1

cleaned_area: 0

cleaning_time: 0

status: docked

friendly_name: Viomi Vacuum V8

supported_features: 13180

 

De: Piotr Machowski ***@***.***> 
Enviada: 26 de abril de 2022 20:19
Para: PiotrMachowski/lovelace-xiaomi-vacuum-map-card ***@***.***>
Cc: jsantosdias ***@***.***>; Author ***@***.***>
Assunto: Re: [PiotrMachowski/lovelace-xiaomi-vacuum-map-card] Home Assistant support for Viomi Vacuum V8 (STYJ02YM) (Issue #390)

 


Vacuum entity/entities

Viomi Vacuum V8 --> vacuum.viomi_vacuum_v8

I think I haven't described it good enough. Can you provide state and attributes of vacuum entity from HA dev tools?

**Comment by PiotrMachowski** [comment]
For now you can configure it manually:
```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.viomi_vacuum_v8
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
vacuum_platform: KrzysztofHajdamowicz/miio2
map_modes:
  - template: vacuum_clean_segment
    service_call_schema:
      service: viomi_vacuum_v8.clean_segment
      service_data:
        segments: '[[selection]]'
        entity_id: '[[entity_id]]'
  - template: vacuum_clean_zone
    service_call_schema:
      service: viomi_vacuum_v8.clean_zone
      service_data:
        zone: '[[selection]]'
        repeats: '[[repeats]]'
        entity_id: '[[entity_id]]'
  - template: vacuum_clean_zone_predefined
    service_call_schema:
      service: viomi_vacuum_v8.clean_zone
      service_data:
        zone: '[[selection]]'
        repeats: '[[repeats]]'
        entity_id: '[[entity_id]]'
  - template: vacuum_goto
    name: Spot cleaning
    service_call_schema:
      service: viomi_vacuum_v8.clean_point
      service_data:
        x_coord: '[[point_x]]'
        y_coord: '[[point_y]]'
        entity_id: '[[entity_id]]'
  - template: vacuum_goto_predefined
    name: Saved spots
    service_call_schema:
      service: viomi_vacuum_v8.clean_point
      service_data:
        x_coord: '[[point_x]]'
        y_coord: '[[point_y]]'
        entity_id: '[[entity_id]]'
```
