### ISSUE TITLE
Problem with map modes options

### ISSUE THREAD

**Issue by carlos-48** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#391]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Problem when visualizing map modes buttons/icons. That area seems to be taller than it should be, and probably it's not collapsed. See attached screenshots

![vacuum map card - pingo](https://user-images.githubusercontent.com/63410909/166823376-ad924d24-c515-4539-9cd4-a44be37d5340.png)

![vacuum map card - zone](https://user-images.githubusercontent.com/63410909/166823380-3fd5ba21-fcdc-4c34-9c60-555b731ade88.png)
s

### What version of a card has described problem?

v2.0.10

### What vacuum model do you have problems with?

roborock.vacuum.a38

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Chrome/Android app

### What version of Home Assistant do you use?

core-2022.5.0

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.aspiradora
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_locked: true
two_finger_pan: true
```

### Additional information

It's my first time with this card, I don't know if it's my blame or a bad configuration, or maybe just a bug.

Also I dont see other map modes but I believe it's because of my model (Roborock Q7 Max)
