### ISSUE TITLE
Menu is cut by the card border when expanding down

### ISSUE THREAD

**Issue by jrlacharnay** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#397]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Hi,

In my config I disabled the icons & tiles :

```
icons: []
tiles: []
```

Since the version 2.0.11 (using HA 2022.5.3), the menu is sometimes expanding down and is then "cut" by the card :

![image](https://user-images.githubusercontent.com/20613054/167619432-8d87787d-f710-4090-b647-9704b8e304b8.png)

It works well when it expands up. It depends its position on the screen.

Before 2.0.11 (and with HA 2022.2), it was always expanding up.

Note that I'm using Firefox. With the Android companion app, when it expand down, the card is expanded as well.

Thank you!

### What version of a card has described problem?

v2.0.11

### What was the last working version card?

v2.0.10

### What vacuum model do you have problems with?

rockrobo.vacuum.v1

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Firefox

### What version of Home Assistant do you use?

2022.5.3

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.robot_aspirateur
vacuum_platform: default
title: Vue aspirateur
map_locked: true
two_finger_pan: false
icons: []
tiles: []
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_follow_path
```
