### ISSUE TITLE
Popup containing card is closing when cleaning mode is changed

### ISSUE THREAD

**Issue by yaruslavm** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#398]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

![image](https://user-images.githubusercontent.com/19183721/167905145-8e7660a7-25ec-4d71-851f-a8a99081666a.png)

the issues is when you select any non "default" or "first" item in the list. 
if you do that the entire card just close

![image](https://user-images.githubusercontent.com/19183721/167905366-a772e9db-1a8b-4538-b1f2-e01bcd834491.png)

### What version of a card has described problem?

 v2.0.11

### What was the last working version card?

v2.0.10

### What vacuum model do you have problems with?

Roborock S7

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Firefox/Chrome

### What version of Home Assistant do you use?

2022.5.1

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
card:
    type: custom:xiaomi-vacuum-map-card
    entity: vacuum.roborock_s7
    preset_name: Live map
    debug: false
    style: |
      ha-card {
      --map-card-manual-rectangle-line-color-selected: red;
      --map-card-manual-rectangle-fill-color: rgba(255, 140, 0, 0.5);
      --map-card-manual-rectangle-fill-color-selected: rgba(255, 140, 0, 0.5);
      --map-card-room-outline-line-color-selected: red;
      --map-card-room-outline-fill-color-selected: rgba(255, 140, 0, 0.5);

      }
      :host {
        --ha-card-border-radius: 0px;
      }
    map_source:
      camera: camera.my_vacuum_camera
      crop:
        top: 455
        bottom: 225
        left: 190
        right: 190
    calibration_source:
      camera: true
    map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_follow_path
```

### Javascript errors shown in the browser's console (if applicable)

```shell
none
```
