### ISSUE TITLE
Problem with browser_mod

### ISSUE THREAD

**Issue by LukaszP2** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#405]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

I use  [service: browser_mod.popup ](https://github.com/thomasloven/hass-browser_mod). 
When Xiaomi Vacuum Map card is open in popup and I change template the popup go closed.

### What version of a card has described problem?

2.0.11

### What vacuum model do you have problems with?

dreame.vacuum.p2029 (Dreame L10 Pro)

### Which integration do you use to control your vacuum (link)?

https://github.com/al-one/hass-xiaomi-miot

### What browser (browsers/apps) does have this problem?

Chrome

### What version of Home Assistant do you use?

2022.6.0b0

### What type of installation are you running?

Home Assistant Supervised

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
title: ''
language: pl
preset_name: Mapa pokoi
entity: vacuum.odkurzacz
map_source:
  camera: camera.odkurzacz_kamera
calibration_source:
  camera: true
map_modes:
  - template: vacuum_clean_segment
    max_selections: 1
    repeats_type: EXTERNAL
    max_repeats: 5
    service_call_schema:
      service: xiaomi_miot.call_action
      service_data:
        entity_id: '[[entity_id]]'
        siid: 4
        aiid: 1
        params:
          - piid: 1
            value: 18
          - piid: 10
            value: '{"selects":[[[[selection_unwrapped]],[[repeats]],3,3,1]]}'
        force_params: true
    predefined_selections:
      - id: 3
        outline:
          - - -658
            - -2500
          - - -658
            - 1150
          - - 1892
            - 1150
          - - 1892
            - -2500
        label:
          text: Kuchnia
          x: 0
          'y': 0
          offset_y: 35
      - id: 2
        outline:
          - - 5000
            - -2500
          - - 5000
            - 1150
          - - 1892
            - 1150
          - - 1892
            - -2500
        label:
          text: Przedpokój
          x: 2050
          'y': 350
          offset_y: 35
      - id: 1
        outline:
          - - 5000
            - 4900
          - - 5000
            - 1150
          - - 2292
            - 1150
          - - 2292
            - 4900
        label:
          text: Salon
          x: 3000
          'y': 3000
          offset_y: 35
      - id: 4
        outline:
          - - -658
            - 1150
          - - -658
            - 4900
          - - 2292
            - 4900
          - - 2292
            - 1150
        label:
          text: Jadalnia
          x: 0
          'y': 3000
          offset_y: 35
  - template: vacuum_clean_zone
    max_selections: 1
    repeats_type: EXTERNAL
    max_repeats: 5
    service_call_schema:
      service: xiaomi_miot.call_action
      service_data:
        entity_id: '[[entity_id]]'
        siid: 4
        aiid: 1
        params:
          - piid: 1
            value: 19
          - piid: 10
            value: '{"areas":[[[[selection_unwrapped]],[[repeats]],1,1]]}'
        force_params: true
vacuum_platform: default
map_locked: true
two_finger_pan: true
tiles:
  - label: Status
    entity: vacuum.odkurzacz
    icon: mdi:robot-vacuum
  - label: Bateria
    entity: sensor.odkurzacz_battery_level
    icon: mdi:battery
    unit: '%'
  - label: Prędkość
    entity: vacuum.odkurzacz
    icon: mdi:fan
    attribute: fan_speed
```
