### ISSUE TITLE
Missing tiles for my vacuum

### ISSUE THREAD

**Issue by dogmatic69** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#409]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Tiles are not rendered for the vacuum on the left, but they are rendered from the one on the right.... 

![image](https://user-images.githubusercontent.com/94674/172068094-10cb6313-dd0e-4911-be2a-5a0fa950bf2c.png)

The weird thing is that the device in developer tools on the left has attributes for these tiles but are not shown, where as the device on the right has no attributes but magically are showing? 😕 

![image](https://user-images.githubusercontent.com/94674/172068171-76f93896-a4fe-4877-9d15-99e0c7cbee73.png)

Left is `viomi.vacuum.v8` and using [this](https://github.com/nergal/homeassistant-vacuum-viomi) integration
Right is `rockrobo.vacuum.v1` and uses the built in HA integration

### What version of a card has described problem?

2.0.11

### What vacuum model do you have problems with?

viomi.vacuum.v8

### Which integration do you use to control your vacuum (link)?

https://github.com/nergal/homeassistant-vacuum-viomi

### What browser (browsers/apps) does have this problem?

chrome

### What version of Home Assistant do you use?

2022.6.2

### What type of installation are you running?

Home Assistant Supervised

### Card's configuration

Left: 
```yaml
      - type: custom:xiaomi-vacuum-map-card
        entity: vacuum.waffle
        map_source:
          camera: camera.waffle
        calibration_source:
          camera: true
        map_modes:
          - template: vacuum_clean_zone
          - template: vacuum_goto
          - template: vacuum_clean_zone_predefined
            predefined_selections:
              - zones: [[15500, 25500, 26500, 26500]]
              - zones: [[25500, 25500, 26500, 26500]]
```

Right:
```yaml
      - type: custom:xiaomi-vacuum-map-card
        entity: vacuum.pancake
        map_source:
          camera: camera.pancake
        calibration_source:
          camera: true
        map_modes:
          - template: vacuum_clean_zone
          - template: vacuum_goto
          - template: vacuum_clean_zone_predefined
            predefined_selections:
              - zones: [[15500, 25500, 26500, 26500]]
              - zones: [[25500, 25500, 26500, 26500]]
```

**Comment by dogmatic69** [comment]
Manually added tiles and now looks similar. 
![image](https://user-images.githubusercontent.com/94674/172069149-f8c090a5-8664-4d63-9173-8b5eb70b67c5.png)

updated config. question is why can it not do this automatically? 
```

      - type: custom:xiaomi-vacuum-map-card
        entity: vacuum.waffle
        map_source:
          camera: camera.waffle
        calibration_source:
          camera: true
        map_modes:
          - template: vacuum_clean_zone
          - template: vacuum_goto
          - template: vacuum_clean_zone_predefined
            predefined_selections:
              - zones: [[15500, 25500, 26500, 26500]]
              - zones: [[25500, 25500, 26500, 26500]]
        tiles:
          - label: Status
            entity: vacuum.waffle
            icon: mdi:robot-vacuum
            attribute: status
          - label: Battery
            entity: vacuum.waffle
            icon: mdi:battery-charging-100
            attribute: battery_level
          - label: Fan Speed
            entity: vacuum.waffle
            icon: mdi:fan
            attribute: fan_speed
          - label: Sensors left
            entity: vacuum.waffle
            icon: mdi:eye
            attribute: sensors_left
            unit: h
            precision: 1
          - label: Filter left
            entity: vacuum.waffle
            icon: mdi:air-filter
            attribute: filter_left
            unit: h
            precision: 1
          - label: Main brush left
            entity: vacuum.waffle
            icon: mdi:broom
            attribute: main_brush_left
            unit: h
            precision: 1
          - label: Side brush left
            entity: vacuum.waffle
            icon: mdi:broom
            attribute: side_brush_left
            unit: h
            precision: 1
```

**Comment by PiotrMachowski** [comment]
Tiles appear automatically when you use an [integration that is supported out of the box](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card#supported-vacuum-platforms). When you don't provide `platform` in your config card assumes that you use built-in Xiaomi Miio integration and tries to search for separate sensors instead of attributes. Your integration is not supported out of the box, sou you have to configure everything manually or try a different platforms to find one that works for your vacuum.

**Comment by dogmatic69** [comment]
Using the built in viomi integration is not much better. 

![image](https://user-images.githubusercontent.com/94674/172071334-e35ae39d-cb56-40ec-9d37-11ffed2bf6ba.png)

```
      - type: custom:xiaomi-vacuum-map-card
        entity: vacuum.test
        map_source:
          camera: camera.test
        calibration_source:
          camera: true
        map_modes:
          - template: vacuum_clean_zone
          - template: vacuum_goto
          - template: vacuum_clean_zone_predefined
            predefined_selections:
              - zones: [[15500, 25500, 26500, 26500]]
              - zones: [[25500, 25500, 26500, 26500]]
```
