### ISSUE TITLE
Cannot read properties of undefined (reading 'unique_id')

### ISSUE THREAD

**Issue by RoboMagus** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#412]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Whilst looking at the browser logs for other (unrelated) issues, I came across the following error:
```
xiaomi-vacuum-map-card.js:555 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'unique_id') at kr.addTilesFromSensors (xiaomi-vacuum-map-card.js:555:7474)
addTilesFromSensors @ xiaomi-vacuum-map-card.js:555
```

This must have been in my logging for quite a while now already, but just never noticed it.
It seems that vacuum entities without `unique_id` cause this error.

Not sure if I'd be missing out on functionality now, but it seems like non existing `unique_id`s should be handled better such that no errors occur.

### What version of a card has described problem?

v2.0.11

### What vacuum model do you have problems with?

Dreame Bot L10 Pro

### Which integration do you use to control your vacuum (link)?

https://github.com/pooyashahidi/xiaomi_vacuum

### What browser (browsers/apps) does have this problem?

Chrome

### What version of Home Assistant do you use?

2022.6.3

### What type of installation are you running?

Home Assistant Container

### Card's configuration

```yaml
- type: 'custom:xiaomi-vacuum-map-card'
    title: Xiaomi Vacuum Map Card
    preset_name: Live map
    entity: vacuum.dusty
    map_locked: true
    map_source:
      camera: camera.dusty_vacuum_map
    calibration_source:
      camera: true
    map_modes:
      - template: vacuum_clean_zone      
      - name: Zones
        icon: mdi:select-drag
        selection_type: MANUAL_RECTANGLE
        max_selections: 5
        repeats_type: INTERNAL
        max_repeats: 5
        service_call_schema:
          service: vacuum.do_zones
          service_data:
            zones: "[[selection]]"
            repeats: "[[repeats]]"
            predefined: "false"
          target:
            entity_id: "[[entity_id]]"
    card_mod:
      style: |
        #map-zoomer-overlay {
          display: none;
        }
```

### Javascript errors shown in the browser's console (if applicable)

```shell
xiaomi-vacuum-map-card.js:555 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'unique_id') at kr.addTilesFromSensors (xiaomi-vacuum-map-card.js:555:7474)
addTilesFromSensors @ xiaomi-vacuum-map-card.js:555
```

### Additional information

Yeah, the vacuum integration that I'm using recently became archived. But there's still better features in there than in the HA built in Xiaomi miio integration.
