### ISSUE TITLE
Find segment

### ISSUE THREAD

**Issue by mellowism** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#413]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Hi, I have had issues since an update, finding the correct segment ID. I can't find a way to find this? I think I saw it under hints last time I set this up, but that seems to have been removed. How can I find the correct segment id now?

### What version of a card has described problem?

v2.0.11

### What vacuum model do you have problems with?

Roborock s6 Pure

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Chrome

### What version of Home Assistant do you use?

2022.6.2

### What type of installation are you running?

Home Assistant Core

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
title: Første etasje
entity: vacuum.roborock_s6_pure
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_locked: true
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 17
        outline:
          - - 19847
            - 34058
          - - 20110
            - 34058
          - - 20110
            - 33401
          - - 22741
            - 33401
          - - 22741
            - 32085
          - - 20110
            - 32085
          - - 20110
            - 31493
          - - 19847
            - 31493
        label:
          text: Kjøkken
          x: 21300
          'y': 32750
          offset_y: 30
        icon:
          name: mdi:countertop-outline
          x: 21300
          'y': 32750
      - id: 18
        outline:
          - - 19847
            - 34058
          - - 15600
            - 34058
          - - 15600
            - 27700
          - - 22850
            - 27700
          - - 22850
            - 31298
          - - 19847
            - 31265
        label:
          text: Stue
          x: 18500
          'y': 31000
          offset_y: 30
        icon:
          name: mdi:sofa-outline
          x: 18500
          'y': 31000
      - id: 16
        outline:
          - - 22850
            - 31298
          - - 22850
            - 24400
          - - 24550
            - 24400
          - - 24550
            - 25880
          - - 25584
            - 25880
          - - 25584
            - 31331
        label:
          text: Gang
          x: 24500
          'y': 28000
          offset_y: 30
        icon:
          name: mdi:bag-personal-outline
          x: 24500
          'y': 28000
      - id: 21
        outline:
          - - 25849
            - 29212
          - - 25849
            - 25934
          - - 28432
            - 25934
          - - 28432
            - 29113
        label:
          text: Hovedsoverom
          x: 27500
          'y': 27500
          offset_y: 30
        icon:
          name: mdi:bed-king-outline
          x: 27500
          'y': 27500
      - id: 22
        outline:
          - - 28506
            - 29305
          - - 25881
            - 29338
          - - 25881
            - 32586
          - - 28572
            - 32619
        label:
          text: Garderob
          x: 27500
          'y': 30800
          offset_y: 30
        icon:
          name: mdi:wardrobe-outline
          x: 27500
          'y': 30800
      - id: 19
        outline:
          - - 23730
            - 31430
          - - 23664
            - 33980
          - - 26611
            - 34013
          - - 26578
            - 32920
          - - 25584
            - 32953
          - - 25518
            - 31430
        label:
          text: Baderom
          x: 25000
          'y': 32700
          offset_y: 30
        icon:
          name: mdi:shower
          x: 25000
          'y': 32700
      - id: 20
        outline:
          - - 24657
            - 25868
          - - 26214
            - 25901
          - - 26247
            - 25173
          - - 27703
            - 25140
          - - 27670
            - 23484
          - - 24691
            - 23451
        label:
          text: Vaskerom
          x: 26500
          'y': 24300
          offset_y: 30
        icon:
          name: mdi:washing-machine
          x: 26500
          'y': 24300
  - template: vacuum_clean_zone_predefined
    predefined_selections:
      - zones:
          - - 15814
            - 31033
            - 19805
            - 33980
        label:
          text: Spisebord
          x: 18000
          'y': 32500
          offset_y: 30
        icon:
          name: mdi:table-furniture
          x: 18000
          'y': 32500
  - template: vacuum_goto
  - template: vacuum_goto_predefined
    predefined_selections:
      - position:
          - 23399
          - 30305
        label:
          text: 2e etasje
          x: 23399
          'y': 30345
          offset_y: 30
        icon:
          name: mdi:bed
          x: 23399
          'y': 30345
      - position:
          - 24757
          - 28252
        label:
          text: Kjeller
          x: 24757
          'y': 28252
          offset_y: 30
        icon:
          name: mdi:sofa
          x: 24757
          'y': 28252
      - position:
          - 21611
          - 33086
        label:
          text: Empty
          x: 21611
          'y': 33086
          offset_y: 30
        icon:
          name: mdi:delete
          x: 21611
          'y': 33086
  - template: vacuum_follow_path
```
