### ISSUE TITLE
Disappearing card

### ISSUE THREAD

**Issue by darkkatarsis** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#414]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

If the tab is displayed in a popup after changing the cleaning mode, it disappears. I'm not sure when it stopped working but there were no problems before. The tab that I use to display the modal is browser_mod.

### What version of a card has described problem?

v2.0.11

### What vacuum model do you have problems with?

roborock.vacuum.s5

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Chrome, ios, Safari

### What version of Home Assistant do you use?

core-2022.6.4

### What type of installation are you running?

Home Assistant Supervised

### Card's configuration

```yaml
#-- Vacuum cleaner --#

  popup_vacuum:
    alias: Show popup for vacuum cleaner
    sequence:
      - service: browser_mod.popup
        data:
          deviceID: "{{ deviceID }}"
          title: Floor plan
          card:
            entities:
              - type: custom:xiaomi-vacuum-map-card
                entity: vacuum.xiaomi_vacuum_cleaner
                map_source:
                  camera: camera.vacuum_cleaner_map
                calibration_source:
                  camera: true
                map_modes:
                  - template: vacuum_clean_zone
                  - template: vacuum_goto
                  - template: vacuum_clean_zone_predefined
                    predefined_selections:
                      - zones: [[23000,29750,26050,32650]] # Bedroom [3]
                      - zones: [[20500,33200,21850,34600]] # Bathroom [16]
                      - zones: [[20600,24400,26100,29450]] # Living room [17]
                      - zones: [[22000,33250,26000,35700]] # Office [18]
                      - zones: [[20300,29500,23000,33200]] # Hallway [19]
                card_mod:
                  style: |
                    #map-zoomer-content {
                      min-height: 400px;
                    }
                    #xiaomiCard {
                      background: #222222;
                      box-shadow: none;
                    }
            type: entities
            card_mod:
              style: |
                ha-card {
                  background: #222222;
                  box-shadow: none;
                }
          style: |
            ha-card {
              background: #222222;
            }
            ha-icon, .mdc-icon-button {
              display: flex;
            }
```

### Javascript errors shown in the browser's console (if applicable)

```shell
no errors
```

### Additional information
![ezgif-3-eeb5207eb3](https://user-images.githubusercontent.com/24244919/173024377-bed228b6-3969-4c08-8d46-276a08f8a3fc.gif)

If you need more information or help with testing a possible fix we can catch up on the Home Assistant Poland group
