### ISSUE TITLE
Unable to get zone data

### ISSUE THREAD

**Issue by dogmatic69** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#415]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Followed the [docs](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/318) to workout zone coordinates but seem to get bad data (number much lower than examples).

Additionally when using these numbers the zone does not show up in any way.

![image](https://user-images.githubusercontent.com/94674/173548648-03ea49d3-71de-4a22-abd7-6dee84fd9fa5.png)

```
{
  "domain": "xiaomi_miio",
  "service": "vacuum_clean_zone",
  "serviceData": {
    "zone": [
      [
        2,
        -1,
        4,
        1
      ]
    ],
    "repeats": 1,
    "entity_id": "vacuum.waffle"
  }
}
```

I'm currently using [this integration](https://github.com/nergal/homeassistant-vacuum-viomi) for the vacuum and [your other one](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor) for the camera 

I believe the vacuum is a `STYJ02YM` aka `viomi.vacuum.v8`.

### What version of a card has described problem?

v2.0.11

### What vacuum model do you have problems with?

viomi.vacuum.v8

### Which integration do you use to control your vacuum (link)?

https://github.com/nergal/homeassistant-vacuum-viomi

### What browser (browsers/apps) does have this problem?

chrome on windows

### What version of Home Assistant do you use?

2022.6.5

### What type of installation are you running?

Home Assistant Supervised

### Card's configuration

```yaml
- type: custom:xiaomi-vacuum-map-card
        entity: vacuum.waffle
        map_source:
          camera: camera.waffle
          crop:
            top: 300
            bottom: 300
            left: 250
            right: 250
        calibration_source:
          camera: true
        map_modes:
          - template: vacuum_clean_zone
          - template: vacuum_goto
          - template: vacuum_clean_zone_predefined
            predefined_selections:
              - zones: [[2, -1, 4, 1]]
        tiles:
          - label: Status
            entity: vacuum.waffle
            icon: mdi:robot-vacuum
            attribute: status
          - label: Battery
            entity: vacuum.waffle
            icon: mdi:battery-charging-100
            attribute: battery_level
          - label: Fan Speed
            entity: vacuum.waffle
            icon: mdi:fan
            attribute: fan_speed
          - label: Sensors left
            entity: vacuum.waffle
            icon: mdi:eye
            attribute: sensors_left
            unit: h
            precision: 1
          - label: Filter left
            entity: vacuum.waffle
            icon: mdi:air-filter
            attribute: filter_left
            unit: h
            precision: 1
          - label: Main brush left
            entity: vacuum.waffle
            icon: mdi:broom
            attribute: main_brush_left
            unit: h
            precision: 1
          - label: Side brush left
            entity: vacuum.waffle
            icon: mdi:broom
            attribute: side_brush_left
            unit: h
            precision: 1
```
```


### Javascript errors shown in the browser's console (if applicable)

```shell
none
```
