### ISSUE TITLE
Spanish translations are wrong

### ISSUE THREAD

**Issue by adocampo** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#416]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Spanish translations are wrong, they seem to be translated using a translation engine, not by a human, so they have wrong translations
![imagen](https://user-images.githubusercontent.com/2266612/174106826-9da41ee2-c3cb-43b9-b46e-5ea72b1b027a.png)

In the card, the word “left” is used as “remaining”, but it has been translated into Spanish as “left” with the meaning of the opposite of right. In english "left" has those two meanings, but in Spanish they have a completely different words.

So, "Sensors left" should be translated as "sensores restantes", or even better, just "Sensores", and *never* as "Sensores izquierda". The same applies for "Filter left", "Main brush left", and "Side brush left". I would translate them into "Filtro", "Escobilla central" (or just "Escobilla" or "Cepillo"), and "Escobilla lateral" (or Cepillo lateral) respectively, omitting the word "restante" (left) so the 4 minicards, would fit into the same row, and now as shown on the screenshot which the later one needs to fit a whole row

### What version of a card has described problem?

v2.0.11

### What vacuum model do you have problems with?

roborock.vacuum.s5e

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Not applicable

### What version of Home Assistant do you use?

core-2022.5.5

### What type of installation are you running?

Home Assistant Core

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
title: Xiaomi Vacuum Map Card
language: es
preset_name: Live map
entity: vacuum.ruky
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
```
```


### Javascript errors shown in the browser's console (if applicable)

_No response_

### Additional information

_No response_
