### ISSUE TITLE
Dropdowns are cut off on 2K screens in Firefox

### ISSUE THREAD

**Issue by adocampo** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#418]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

I've noticed the dropdowns are show bad in my 2K screen as show below
![imagen](https://user-images.githubusercontent.com/2266612/174191226-ef7020f4-88fc-407c-bfad-dfc64c5f4a21.png)

Moving my firefox window to my secondary screen, which only supports FullHD, the same dropdown shows just as expected.
![imagen](https://user-images.githubusercontent.com/2266612/174191187-db9d0f24-3c69-472f-8e7f-c8cd56cbeb11.png)

I've tried with chromed-based browsers and they are show properly, only happens with firefox.

### What version of a card has described problem?

v2.0.11

### What vacuum model do you have problems with?

roborock.vacuum.s5e

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Firefox

### What version of Home Assistant do you use?

core-2022.5.5

### What type of installation are you running?

Home Assistant Core

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
title: Xiaomi Vacuum Map Card
language: es
preset_name: Live map
entity: vacuum.ruky
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
```
```


### Javascript errors shown in the browser's console (if applicable)

_No response_

### Additional information

_No response_
