### ISSUE TITLE
vacuum doesn't start

### ISSUE THREAD

**Issue by jlo88** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#42]
Hi, first of all, amazing card! Looks really cool! 

I've been trying to use it but I'm unable to start the vacuum cleaner. My card settings: 

```
calibration_points:
  - map:
      x: 466
      'y': 1889
    vacuum:
      x: 25500
      'y': 25500
  - map:
      x: 730
      'y': 1625
    vacuum:
      x: 26500
      'y': 26500
  - map:
      x: 466
      'y': 1625
    vacuum:
      x: 25500
      'y': 26500
debug: true
entity: vacuum.xiaomi_vacuum_cleaner
map_camera: camera.rockrobo_map
service: vacuum.start
type: 'custom:xiaomi-vacuum-map-card'

```

When I use the developer tools like this I can start the vacuum: 

![image](https://user-images.githubusercontent.com/10574850/75091887-86895000-5572-11ea-8551-b2d195084ccf.png)

The card does display the map. 

I've read https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/7 but I wasn't sure if it was solved now.

**Comment by PiotrMachowski** [comment]
Vacuum doesn't start if debug mode is enabled, have you tried without it?

**Comment by jlo88** [comment]
Just changed the card to: 

```
calibration_points:
  - map:
      x: 466
      'y': 1889
    vacuum:
      x: 25500
      'y': 25500
  - map:
      x: 730
      'y': 1625
    vacuum:
      x: 26500
      'y': 26500
  - map:
      x: 466
      'y': 1625
    vacuum:
      x: 25500
      'y': 26500
entity: vacuum.xiaomi_vacuum_cleaner
map_camera: camera.rockrobo_map
service: vacuum.start
type: 'custom:xiaomi-vacuum-map-card'
```

but still nothing. The logs also show nothing.
