### ISSUE TITLE
Unable to scroll window with finger touching map even though it is "locked"

### ISSUE THREAD

**Issue by ps1x** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#421]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Thanks for great addon!

I am unable to scroll lovelace UI, touching map even though map is "locked". It is much annoying because map is long and can take almost entire screen, so if it is scrolled to fit screen then you have hard time trying to escape it.

### What version of a card has described problem?

v2.0.11

### What vacuum model do you have problems with?

roborock.vacuum.s5max

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Mobile Home Assistant companion app for Android

### What version of Home Assistant do you use?

Home Assistant Core 2022.5.5

### What type of installation are you running?

Home Assistant Container

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.xiaomi_vacuum_cleaner
map_source:
  camera: camera.xiaomi_cloud_map_extractor
  crop:
    bottom: 200
    top: 200
    left: 200
    right: 200
calibration_source:
  camera: true
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_clean_zone_predefined
    predefined_selections:
      - zones:
          - - 25500
            - 25500
            - 26500
            - 26500
title: ''
vacuum_platform: default
map_locked: true
```
