### ISSUE TITLE
Mop settings in pop-up card and in the icon for vacuum Dreame D9

### ISSUE THREAD

**Issue by TimpP-Spb** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#422]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Dear Piotr,

I found some problem, it is not possible cahnge mop settings for vacuum Dreame D9
![image](https://user-images.githubusercontent.com/64695580/175277647-744576d7-79b7-4248-b314-896217f8b300.png)

### What version of a card has described problem?

 v2.0.11

### What vacuum model do you have problems with?

dreame.vacuum.p2009

### Which integration do you use to control your vacuum (link)?

https://github.com/al-one/hass-xiaomi-miot

### What browser (browsers/apps) does have this problem?

Chrome

### What version of Home Assistant do you use?

core-2022.4.6

### What type of installation are you running?

Home Assistant Supervised

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.dreame_p2009_14bf_robot_cleaner
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_locked: false
two_finger_pan: false
vacuum_platform: default
appened_tiles: true
tiles:
  - entity: sensor.dreame_p2009_14bf_filter_left_time
    label: Filter left
    icon: mdi:air-filter
    unit: ' h'
  - entity: sensor.dreame_p2009_14bf_brush_left_time
    label: Main brush left
    icon: mdi:brush
    unit: ' h'
  - entity: sensor.dreame_p2009_14bf_brush_left_time_2
    label: Side brush left
    icon: mdi:brush
    unit: ' h'
  - entity: sensor.dreame_p2009_14bf_status
    label: Status
    icon: mdi:state-machine
  - entity: sensor.dreame_p2009_14bf_battery_level
    label: Battery
    icon: mdi:battery
    unit: '%'
  - entity: vacuum.dreame_p2009_14bf_robot_cleaner
    label: Fan Speed
    attribute: vacuum_extend.cleaning_mode
    icon: mdi:fan
    tap_action:
      action: more-info
```
