### ISSUE TITLE
Room cleaning issue roborock.vacuum.m1s

### ISSUE THREAD

**Issue by Snizh-Fize** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#423]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

I'm trying to get room cleaning working to no avail. Updated to the latest versions, newest stable HA (container), newest vacuum-map-card and cloud extractor with my roborock.vacuum.m1s.

I've gotten the right room IDs from the FAQ entry using the developer tools and adapted them into the map config.

The issue is that the vacuum, no matter which room I select, starts cleaning right around its dock, then says it's done and returns to its home point.

My configuration.yaml looks like this:
```
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
      - rooms
      - room_numbers
```

### What version of a card has described problem?

v2.0.1.1

### What vacuum model do you have problems with?

roborock.vacuum.m1s

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Chrome

### What version of Home Assistant do you use?

2022.6.7

### What type of installation are you running?

Home Assistant Container

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.hugo
vacuum_platform: default
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_segment
    predefined_selections:
      - id: '17'
        outline:
          - - 24050
            - 22200
          - - 24050
            - 30950
          - - 31650
            - 30950
          - - 31650
            - 22200
        label:
          text: Room 17
          x: 27850
          'y': 26575
          offset_y: 35
        icon:
          name: mdi:broom
          x: 27850
          'y': 26575
      - id: '18'
        outline:
          - - 30350
            - 26750
          - - 30350
            - 28950
          - - 32400
            - 28950
          - - 32400
            - 26750
        label:
          text: Room 18
          x: 31375
          'y': 27850
          offset_y: 35
        icon:
          name: mdi:broom
          x: 31375
          'y': 27850
      - id: '1'
        outline:
          - - 31650
            - 28300
          - - 31650
            - 33100
          - - 36050
            - 33100
          - - 36050
            - 28300
        label:
          text: Room 1
          x: 33850
          'y': 30700
          offset_y: 35
        icon:
          name: mdi:broom
          x: 33850
          'y': 30700
      - id: '19'
        outline:
          - - 27950
            - 30250
          - - 27950
            - 33150
          - - 31350
            - 33150
          - - 31350
            - 30250
        label:
          text: Room 19
          x: 29650
          'y': 31700
          offset_y: 35
        icon:
          name: mdi:broom
          x: 29650
          'y': 31700
      - id: '16'
        outline:
          - - 24550
            - 31000
          - - 24550
            - 33150
          - - 27850
            - 33150
          - - 27850
            - 31000
        label:
          text: Room 16
          x: 26200
          'y': 32075
          offset_y: 35
        icon:
          name: mdi:broom
          x: 26200
          'y': 32075
  - template: vacuum_goto
  - template: vacuum_follow_path
  - template: vacuum_clean_zone_predefined
map_locked: true
```

### Additional information

I've used the room ID/config values returned by following [this](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/317).

YAML returned:
```
type: custom:xiaomi-vacuum-map-card
entity: vacuum.hugo
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_modes:
  - template: vacuum_goto
  - template: vacuum_clean_zone
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 17
        outline:
          - - 24050
            - 22200
          - - 24050
            - 30950
          - - 31650
            - 30950
          - - 31650
            - 22200
        label:
          text: Room 17
          x: 27850
          y: 26575
          offset_y: 35
        icon:
          name: "mdi:broom"
          x: 27850
          y: 26575
      - id: 18
        outline:
          - - 30350
            - 26750
          - - 30350
            - 28950
          - - 32400
            - 28950
          - - 32400
            - 26750
        label:
          text: Room 18
          x: 31375
          y: 27850
          offset_y: 35
        icon:
          name: "mdi:broom"
          x: 31375
          y: 27850
      - id: 1
        outline:
          - - 30700
            - 28300
          - - 30700
            - 33100
          - - 36050
            - 33100
          - - 36050
            - 28300
        label:
          text: Room 1
          x: 33375
          y: 30700
          offset_y: 35
        icon:
          name: "mdi:broom"
          x: 33375
          y: 30700
      - id: 19
        outline:
          - - 27950
            - 30250
          - - 27950
            - 33150
          - - 31350
            - 33150
          - - 31350
            - 30250
        label:
          text: Room 19
          x: 29650
          y: 31700
          offset_y: 35
        icon:
          name: "mdi:broom"
          x: 29650
          y: 31700
      - id: 16
        outline:
          - - 24550
            - 31000
          - - 24550
            - 33150
          - - 27850
            - 33150
          - - 27850
            - 31000
        label:
          text: Room 16
          x: 26200
          y: 32075
          offset_y: 35
        icon:
          name: "mdi:broom"
          x: 26200
          y: 32075
```
