### ISSUE TITLE
Support of dreame.vacuum.p2114o

### ISSUE THREAD

**Issue by wlli2021** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#427]
### Integration repository

https://github.com/al-one/hass-xiaomi-miot

### Supported features

- [X] Zone cleaning (using 4 coordinates)
- [X] Room cleaning (using room id/number)
- [X] Going to point (using 2 coordinates)
- [X] Cleaning a point (using 2 coordinates)
- [ ] Others

### Vacuum entity/entities

```yaml
fan_speed_list:
  - Silent
  - Basic
  - Strong
  - Full Speed
friendly_name: Robot Robot Cleaner
supported_features: 13048
battery_level: 90
battery_icon: mdi:battery-90
fan_speed: Full Speed
model: dreame.vacuum.p2114o
lan_ip: XXX.xxx.xxx.xxx
mac_address: B8:4D:43:xx:xx:xx
entity_class: MiotVacuumEntity
exclude_miot_services:
  - consumable
  - annoy
  - remote
  - time
exclude_miot_properties:
  - delete_timer
  - clean_info
  - map_view
  - frame_info
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:dreame-p2114o:1
vacuum.status: 12
vacuum.fault: 0
vacuum.mode: 3
mop.mop_life_level: 91
mop.mop_left_time: 73
clean_logs.first_clean_time: 1655729778
clean_logs.total_clean_time: 402
clean_logs.total_clean_times: 27
clean_logs.total_clean_area: 350
audio.volume: 100
audio.voice_packet_id: EN
audio.voice_change_state: '{\"id\":\"\",\"state\":\"idle\",\"progress\":0}'
audio.set_voice.error: '-1'
map.mult_map_info: >-
  {"object_name":"278044470/1033606377/9","md5":"b6dec12731ab153f2023e61a39f833ee"}
do_not_disturb.enable: true
do_not_disturb.start_time: '22:00'
do_not_disturb.end_time: '08:00'
vacuum_extend.work_mode: 18
vacuum_extend.cleaning_time: 12
vacuum_extend.cleaning_area: 15
vacuum_extend.cleaning_mode: 3
vacuum_extend.mop_mode: 3
vacuum_extend.waterbox_status: 1
vacuum_extend.task_status: 3
vacuum_extend.clean_extend_data.error: '-1'
break_point_restart-4-11: 1
vacuum_extend.carpet_press: 1
vacuum_extend.serial_number: P21142427CN01698ZM
vacuum_extend.remote_state.error: '-1'
vacuum_extend.clean_rags_tip: 0
vacuum_extend.keep_sweeper_time: 0
vacuum_extend.faults: ''
vacuum_extend.nation_matched: unknown
vacuum_extend.relocation_status: 0
vacuum_extend.laser_switch: 1
filter.filter_life_level: 95
filter.filter_left_time: 143
brush_left_time-10-1: 193
brush_life_level-10-2: 96
brush_cleaner.brush_left_time: 293
brush_cleaner.brush_life_level: 97
battery.charging_state: 2
state_updater: lan
vacuum.status_desc: Sweeping and Mopping
sub_entities:
  - vacuum-2.status-1
  - filter-11.filter_life_level-1
  - filter-11.filter_left_time-2
  - battery-3.battery_level-1
  - battery-3.charging_state-2
  - brush_cleaner-9.brush_left_time-1
  - brush_cleaner-9.brush_life_level-2
  - brush_cleaner-10.brush_left_time-1
  - brush_cleaner-10.brush_life_level-2
```

### Service calls

```yaml
Turn on/off, return to base, set fan speed, locate, start/pause, stop, send command, return to base, toggle, clean spot
```
