### ISSUE TITLE
Object.fromEntries is not a function

### ISSUE THREAD

**Issue by Wombosvideo** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#429]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Whenever I add the configured card to the UI, on my **wall tablet** it only shows the error "Object.fromEntries is not a function" and the card's configuration.

### What version of a card has described problem?

v2.0.11

### What was the last working version card?

v2.0.0

### What vacuum model do you have problems with?

roborock.vacuum.s5e

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Chrome/Android App

### What version of Home Assistant do you use?

core-2022.7.3

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_locked: true
entity: vacuum.roborock_vacuum_s5e
map_source:
  camera: camera.roborock_s5_max_map
  crop:
    top: 100
    right: 100
    bottom: 100
    left: 100
calibration_source:
  camera: true
map_modes:
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 1
        label:
          text: Rooms Deducted
          x: 23456
          y: 23456
          offset_y: 35
        icon:
          name: "mdi:broom"
          x: 23456
          y: 23456
  - template: vacuum_goto
  - template: vacuum_clean_zone
```

### Additional information

Javascript error exists only on my wall tablet and debugging is hardly possible there. I assume an outdated Webview version but I can't update it because it only ships with the OS, which hasn't gotten any updates in a while now. But I'd like to keep using the tablet as long as possible and the main reason for this is because I use the tablet mostly for the vacuum card only. I also assume the problem can easily be fixed with a polyfill: https://vanillajstoolkit.com/polyfills/objectfromentries/
