### ISSUE TITLE
edit button dims the page and doesnt open the card config.

### ISSUE THREAD

**Issue by ctrl50** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#43]
Almost everytime i click 'edit' the card just dims out and i have to refresh in order to click anywhere, sometimes it works, however most of the time it doesnt.  see screenshot of it dim:

![carddim](https://user-images.githubusercontent.com/51256504/76286468-81f5b480-625f-11ea-8923-5d6796955dcf.png)

when im able to view/edit the card the yaml is all messed up and out of order. none of my other 26 pages full of cards do this. i have 18 other plugins/cards installed. Also, its eating ram real fast. and refreshing the picture every few seconds, something weird is going on and i cant pin point it. 

the card works, but its unusable in this condition that i cant edit it, and when its open its leaking memory. 
any ideas what i might have done wrong? 
![cardconfig](https://user-images.githubusercontent.com/51256504/76286472-84580e80-625f-11ea-85e4-56d5ba7d6499.png)

**Comment by ctrl50** [comment]
I should note that removing the card/or the config and everything else is normal..

when i add this config to any other pages with other cards, THOSE cards also do the edit/dim issue.

removing it, and everything is fine again

**Comment by ctrl50** [comment]
couple more screenshots, when i use the example config i get no card type found:
![exampleconfig](https://user-images.githubusercontent.com/51256504/76287329-71ded480-6261-11ea-84a6-ea3b39676d8b.png)

when i set it up how i usually do, removing the first - 
and type:card at the bottom, like 99% of the configs i have, i get missing entity?
![normalconfig](https://user-images.githubusercontent.com/51256504/76287376-95098400-6261-11ea-829f-83306c0e5ce8.png)

im lost here

**Comment by PiotrMachowski** [comment]
It seems that you have placed this card inside of `entities` card, why? Is it for card mod? Does it work when used by itself?

**Comment by ctrl50** [comment]
see other comments ^ it does work, as in the vac will do what it should. but the card is unusable becuase it just dims it...placing in entities is the only config that i can even get to not error.. see other screenshots.

**Comment by PiotrMachowski** [comment]
It seems that you have copied too much from example (it includes configuration of a view). Please use the following one:
```
type: custom:xiaomi-vacuum-map-card
entity: vacuum.xiaomi_vacuum
map_image: '/local/custom_lovelace/xiaomi_vacuum_map_card/map.png'
calibration_points:
  - vacuum:
      x: 25500
      y: 25500
    map:
      x: 466
      y: 1889
  - vacuum:
      x: 26500
      y: 26500
    map:
      x: 730
      y: 1625
  - vacuum:
      x: 25500
      y: 26500
    map:
      x: 466
      y: 1625
zones:
  - [[25500, 25500, 26500, 26500]]
  - [[24215, 28125, 29465, 32175]]
  - [[24245, 25190, 27495, 27940], [27492, 26789, 28942, 27889]]
  - [[28972, 26715, 31072, 27915], [29457, 27903, 31107, 29203], [30198, 29215, 31498, 31215], [29461, 31228, 31511, 32478]]
```
