### ISSUE TITLE
Roborock S6 Pure seems to expose more attributes than the S6 MaxV

### ISSUE THREAD

**Issue by mihalski** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#431]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Please ignore the lack of a map and the error regarding calibration. This is simply due to me disabling the map update when the vacuum is not in use.
![image](https://user-images.githubusercontent.com/3755059/178869210-142e6fb3-29d7-43bb-8b17-346c1c73cfca.png)

To be fair I don't know if this is a problem with the map or the integration so I thought it best to start here.

Is the S6 MaxV only supposed to show the status, battery and fan speed while the S6 Pure shows additional information? I would think not as they both show this information in the Mi Home app and they are very similar vacuums. This appears to be a bug.

### What version of a card has described problem?

v2.0.11

### What vacuum model do you have problems with?

roborock.vacuum.a10

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Chrome/Safari/iOS App

### What version of Home Assistant do you use?

core-2022.7.3

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.roborock_s6_maxv_cloud_map
calibration_source:
  camera: true
entity: vacuum.roborock_s6_maxv
vacuum_platform: default
title: Roborock S6 MaxV
```

### Additional information

I do not know if this additional information ever showed up in the past as I had previously used a card that did not contain this information for both vacuums.
