### ISSUE TITLE
Zoom out not working in chrome/brave

### ISSUE THREAD

**Issue by idogrf** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#438]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

This is a really minor issue

Zooming out of the map using the mouse scroll wheel doesn't work.
I've tried using chrome and brave, both on latest version and it doesn't zoom out.
Zoom in does work... weird

Tried the same on edge browser and it does work.

### What version of a card has described problem?

v2.0.11

### What vacuum model do you have problems with?

xiaomi mi robot (1st gen)

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio

### What browser (browsers/apps) does have this problem?

Chrome/Brave

### What version of Home Assistant do you use?

docker

### What type of installation are you running?

Home Assistant Container

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.xiaomi_vacuum_cleaner
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_modes:
  - template: vacuum_clean_zone_predefined
    predefined_selections:
      - zones: input_text.zone_kitchen
      - zones: input_text.zone_dinning_room
      - zones: input_text.zone_living_room
      - zones: input_text.zone_office
      - zones: input_text.zone_bedroom
      - zones: input_text.zone_hall
      - zones: input_text.zone_toilet
  - template: vacuum_clean_zone
  - template: vacuum_goto
```

**Comment by idogrf** [comment]
no, it's not wrapped, it's directly on the dashboard - 

```  
  - title: Vacuum
    path: vacuum
    icon: mdi:broom
    badges: []
    cards:
      - type: custom:xiaomi-vacuum-map-card
        entity: vacuum.xiaomi_vacuum_cleaner
        map_source:
          camera: camera.xiaomi_cloud_map_extractor
        calibration_source:
          camera: true
        map_modes:
          - template: vacuum_clean_zone_predefined
            predefined_selections:
              - zones: input_text.zone_kitchen
              - zones: input_text.zone_dinning_room
              - zones: input_text.zone_living_room
              - zones: input_text.zone_office
              - zones: input_text.zone_bedroom
              - zones: input_text.zone_hall
              - zones: input_text.zone_toilet
          - template: vacuum_clean_zone
          - template: vacuum_goto
      - type: entities
        entities:
          - entity: input_boolean.vacuum_full
          - entity: input_number.vacuum_days_since_full_clean
            name: Days since full clean
          - entity: input_number.vacuum_days_since_office_clean
            name: Days since office clean
      - type: grid
        cards:
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: call-service
              service: pyscript.vacuum_map_house
              service_data: {}
              target: {}
            icon: mdi:warehouse
            show_state: false
            name: Map House
```

chrome version - 103.0.5060.114
