### ISSUE TITLE
Zones not updating after press 'Run" during cleaning

### ISSUE THREAD

**Issue by Abbadon89** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#44]
Hi, thanks for a big effort of this custom card.

When i start Xiaomi vacuum gen 1 to predeffined zone cleanup robot starts. After a while i want to add next zone, after i press run nothing happens, zones are not updating. I have to manualy pause robot and press Run again to update zones. I tried to modify .js script and add additional pause service but this seems to be not working.
If its possible, to check if robot is claening, and if so, pause it and updates zones to be cleaned?

```
        if (config.service && config.service.split(".").length === 2) {
            this.service_domain = config.service.split(".")[0];
            this.service_method = config.service.split(".")[1];
	    this.service_stop = "stop";
        } else {
            this.service_domain = "vacuum";
            this.service_method = "send_command";
	    this.service_stop = "stop";
        }
...
    vacuumStartZonedCleanup(debug) {
        const zone = [];
        for (const rect of this.rectangles) {
            zone.push(this.convertMapToVacuumRect(rect, this.vacuumZonedCleanupRepeats));
        }
        if (debug && this._config.debug) {
            alert(JSON.stringify(zone));
        } else {
           this._hass.callService(this.service_domain, this.service_stop, {
	   entity_id: this._config.entity,
	}).then(() => this.showToast());		
            this._hass.callService(this.service_domain, this.service_method, {
            entity_id: this._config.entity,
            command: "app_zoned_clean",
            params: zone
            }).then(() => this.showToast());
        }
    }
```

**Comment by PiotrMachowski** [comment]
It is better to do it by using a script and defining a service in a [cards configuration](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card#defining-service). To make it run you have to set up [this](https://raw.githubusercontent.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/master/examples/vacuum_send_command.py) python script.

Scripts:
```
vacuum_send_command:
  sequence:
    - service: script.vacuum_stop_if_not_docked
      data_template:
        entity_id: "{{ entity_id }}"
    - service: python_script.vacuum_send_command
      data_template:
        entity_id: "{{ entity_id }}"
        command: "{{ command }}"
        params: "{{ params }}"

vacuum_stop_if_not_docked:
  sequence:
    - condition: template
      value_template: "{{ not is_state(entity_id, "docked") }}"
    - service: vacuum.stop
      data_template:
        entity_id: "{{ entity_id }}"
```
cards configuration:
```
type: custom:xiaomi-vacuum-map-card
service: script.vacuum_send_command
...
```
