### ISSUE TITLE
Remove support for integration KrzysztofHajdamowicz/miio2

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#454]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

I am abandoning STYTJ02YM integration, new maintainer is needed. For now, no further commits from my side are expected.

### What version of a card has described problem?

2.0.11

### What was the last working version card?

v6.6.6

### What vacuum model do you have problems with?

STYTJ02YM

### Which integration do you use to control your vacuum (link)?

https://github.com/KrzysztofHajdamowicz/home-assistant-vacuum-styj02ym

### What browser (browsers/apps) does have this problem?

All of them

### What version of Home Assistant do you use?

2022.8.1

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.vacuum
vacuum_platform: KrzysztofHajdamowicz/miio2
map_locked: true
append_icons: true
icons:
  - icon: mdi:water-outline
    conditions:
      - entity: vacuum.vacuum
        attribute: is_mop
        value: 1
      - entity: vacuum.vacuum
        attribute: water_grade
        value: 11
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.vacuum
        command: set_suction
        params: 12
  - icon: mdi:water-opacity
    conditions:
      - entity: vacuum.vacuum
        attribute: is_mop
        value: 1
      - entity: vacuum.vacuum
        attribute: water_grade
        value: 12
    tap_action:
      action: call-service
      service: vacuum.vacuum
      service_data:
        entity_id: vacuum.vacuum
        command: set_suction
        params: 13
  - icon: mdi:water
    conditions:
      - entity: vacuum.vacuum
        attribute: is_mop
        value: 1
      - entity: vacuum.vacuum
        attribute: water_grade
        value: 13
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.vacuum
        command: set_suction
        params: 11
```
