### ISSUE TITLE
Cannot draw Zones or add points in Card /  TypeError: Cannot read properties of null (reading 'toString')

### ISSUE THREAD

**Issue by devhopsde** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#457]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Cannot draw Zones or add points in Xiaomi Vacuum Map Card. My Card is shown, No go and no Mop Areas are shown too. But when in cliock on the "+" Button, i get an "Uncaught (in promise) TypeError: Cannot read properties of null (reading 'toString')" Error and nothing happens. 

i can control my Dreame F9 within Home Assistant. 

### What version of a card has described problem?

v2.0.11

### What vacuum model do you have problems with?

vacuum.dreame.p2008

### Which integration do you use to control your vacuum (link)?

https://github.com/al-one/hass-xiaomi-miot

### What browser (browsers/apps) does have this problem?

Chrome, Brave, Android Firefox

### What version of Home Assistant do you use?

2022.8.2

### What type of installation are you running?

Home Assistant Container

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.dreame_p2008_a819_robot_cleaner
title: karte
language: de
debug: true
calibration_source:
  camera: true
map_locked: false
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_follow_path
map_source:
  camera: camera.xiaomi_cloud_map_extractor
vacuum_platform: default
```

### Javascript errors shown in the browser's console (if applicable)

```shell
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'toString')
    at xr.render (xiaomi-vacuum-map-card.js?hacstag=1933720442011:555:11018)
    at xiaomi-vacuum-map-card.js?hacstag=1933720442011:940:92
    at Array.map (<anonymous>)
    at xiaomi-vacuum-map-card.js?hacstag=1933720442011:940:81
    at Bn (xiaomi-vacuum-map-card.js?hacstag=1933720442011:123:12332)
    at Vr.render (xiaomi-vacuum-map-card.js?hacstag=1933720442011:938:23)
    at Vr.update (xiaomi-vacuum-map-card.js?hacstag=1933720442011:23:405)
    at Vr.performUpdate (xiaomi-vacuum-map-card.js?hacstag=1933720442011:11:5057)
    at Vr.scheduleUpdate (xiaomi-vacuum-map-card.js?hacstag=1933720442011:11:4704)
    at Vr._$E_ (xiaomi-vacuum-map-card.js?hacstag=1933720442011:11:4612)
```

### Additional information

I always get "Uncaught (in promise) TypeError: Cannot read properties of null (reading 'toString')
    at xr.render" Errors... 
   

My Camera Config in configuration.yaml:
```
camera:
  - platform: xiaomi_cloud_map_extractor
    force_api: dreame
    host: !secret vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    country: "de"
    draw: ['all']
    attributes:
      - calibration_points
    auto_update: true
    scan_interval: 10

```
