### ISSUE TITLE
Typo on English card

### ISSUE THREAD

**Issue by adocampo** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#468]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

It says "unavailableh" instead of "unavailable".
![imagen](https://user-images.githubusercontent.com/2266612/188562214-58832b8f-2279-4ac2-aa24-659cbe207208.png)

### What version of a card has described problem?

v2.0.11

### What vacuum model do you have problems with?

roborock.vacuum.s5e

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

All

### What version of Home Assistant do you use?

core-2022.5.5

### What type of installation are you running?

Home Assistant Core

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
title: Ruky
preset_name: Live map
entity: vacuum.ruky
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_modes:
  - template: vacuum_goto
  - template: vacuum_clean_zone
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 17
        outline:
          - - 26875
            - 25085
          - - 30646
            - 25038
          - - 29435
            - 29274
          - - 27434
            - 28483
          - - 27946
            - 27040
          - - 27806
            - 26993
          - - 27760
            - 26761
          - - 27341
            - 26574
          - - 27341
            - 26202
          - - 26968
            - 26155
          - - 26922
            - 26435
          - - 26829
            - 26435
          - - 26875
            - 25085
        label:
          text: Despacho
          x: 28600
          'y': 27100
          offset_y: 35
        icon:
          name: mdi:chair-rolling
          x: 28600
          'y': 27100
      - id: 22
        outline:
          - - 17473
            - 30158
          - - 19242
            - 24992
          - - 24874
            - 25178
          - - 25060
            - 26155
          - - 24595
            - 26155
          - - 23943
            - 28203
          - - 24269
            - 28483
          - - 24036
            - 29274
          - - 22267
            - 28669
          - - 21150
            - 31462
          - - 17473
            - 30205
        label:
          text: Comedor
          x: 21025
          'y': 27825
          offset_y: 35
        icon:
          name: mdi:sofa
          x: 21025
          'y': 27825
      - id: 23
        outline:
          - - 24921
            - 25132
          - - 26782
            - 25132
          - - 26829
            - 25411
          - - 26782
            - 26388
          - - 25060
            - 26202
          - - 24921
            - 25132
        label:
          text: Recibidor
          x: 25425
          'y': 26300
          offset_y: 35
        icon:
          name: mdi:door-open
          x: 25425
          'y': 26300
      - id: 20
        outline:
          - - 24083
            - 29321
          - - 24362
            - 28297
          - - 26270
            - 28995
          - - 25991
            - 30112
          - - 28877
            - 31136
          - - 28132
            - 33789
          - - 27294
            - 33510
          - - 27899
            - 31648
          - - 24967
            - 30670
          - - 25246
            - 29646
          - - 24036
            - 29321
        label:
          text: Pasillo
          color: white
          x: 28272
          'y': 32253
          offset_y: 35
        icon:
          name: mdi:walk
          x: 28365
          'y': 31601
      - id: 24
        outline:
          - - 28179
            - 30903
          - - 28179
            - 30810
          - - 27620
            - 30577
          - - 27620
            - 30438
          - - 27387
            - 30345
          - - 27574
            - 29739
          - - 27946
            - 29739
          - - 27992
            - 29879
          - - 28318
            - 29739
          - - 28411
            - 29553
          - - 29156
            - 29786
          - - 29016
            - 30624
          - - 28830
            - 31089
          - - 28179
            - 30903
        label:
          text: Baño
          x: 28250
          'y': 30150
          offset_y: 35
        icon:
          name: mdi:toilet
          x: 28250
          'y': 30150
      - id: 19
        outline:
          - - 26038
            - 30112
          - - 26363
            - 29274
          - - 27527
            - 29739
          - - 27201
            - 30531
          - - 26038
            - 30112
        label:
          text: Lavadero
          x: 26700
          'y': 29925
          offset_y: 35
        icon:
          name: mdi:washing-machine
          x: 26700
          'y': 29925
      - id: 16
        outline:
          - - 22686
            - 32160
          - - 21755
            - 34394
          - - 16589
            - 32392
          - - 17520
            - 30112
          - - 21709
            - 31648
          - - 22686
            - 32160
        label:
          text: Dormitorio
          x: 19125
          'y': 33150
          offset_y: 35
        icon:
          name: mdi:bunk-bed
          x: 19125
          'y': 33150
      - id: 18
        outline:
          - - 25572
            - 30857
          - - 26177
            - 31089
          - - 26131
            - 31275
          - - 27341
            - 31694
          - - 26875
            - 32672
          - - 25060
            - 32067
          - - 25386
            - 31043
          - - 25572
            - 30857
        label:
          text: Cocina
          x: 26000
          'y': 31725
          offset_y: 35
        icon:
          name: mdi:fridge
          x: 26000
          'y': 31725
      - id: 25
        outline:
          - - 24455
            - 35371
          - - 21895
            - 34487
          - - 22686
            - 32067
          - - 25665
            - 33091
          - - 25339
            - 33835
          - - 24502
            - 35371
        label:
          text: Habitación
          x: 24100
          'y': 33700
          offset_y: 35
        icon:
          name: mdi:bed
          x: 24100
          'y': 33700
      - id: 26
        outline:
          - - 27434
            - 33510
          - - 28179
            - 33510
          - - 27992
            - 34394
          - - 27341
            - 34301
          - - 27201
            - 35604
          - - 26875
            - 35604
          - - 26689
            - 35232
          - - 25851
            - 34952
          - - 26038
            - 34254
          - - 25339
            - 33835
          - - 25572
            - 33091
          - - 25898
            - 33044
          - - 27434
            - 33510
        label:
          text: Vestidor
          x: 26625
          'y': 34200
          offset_y: 35
        icon:
          name: mdi:wardrobe
          x: 26625
          'y': 34200
  - template: vacuum_goto
  - template: vacuum_goto_predefined
    predefined_selections:
      - position:
          - 28006
          - 28036
        label:
          text: Emptying
          x: 28006
          'y': 28036
          offset_y: 35
        icon:
          name: mdi:broom
          x: 28006
          'y': 28036
      - position:
          - 32143
          - 26284
        label:
          text: Sofa
          x: 32143
          'y': 26284
          offset_y: 35
        icon:
          name: mdi:sofa
          x: 32143
          'y': 26284
  - template: vacuum_follow_path
vacuum_platform: default
two_finger_pan: true
map_locked: false
```
