### ISSUE TITLE
Request: Use get_room_mapping Numbers

### ISSUE THREAD

**Issue by majorsl** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#47]
I used miio to retrieve all of my rooms via get_room_mapping.  I do not need to use zone coordinates to define my rooms.

Can this card be updated to make use of these for room numbers in addition?

**Comment by PiotrMachowski** [comment]
I plan to implement it, but it requires whole card to be rewritten

**Comment by r3dsouza** [comment]
+1. Would be great to have an additional setting to include room numbers. It would make this really good card even greater!!

**Comment by Maximus97** [comment]
+1 Would be great if this card used the preconfigured rooms in the app

**Comment by pznamenskii** [comment]
would love to see this feature - opens up so many possibilities! like asking your VA to clean the kitchen when you drop something with your hands full.

**Comment by LucasBednarek** [comment]
Hey @PiotrMachowski! I have just created a feature of adding room:

![image](https://user-images.githubusercontent.com/37834008/103659084-50777380-4f6c-11eb-8bfa-db953e5b9d6b.png)
![image](https://user-images.githubusercontent.com/37834008/103659472-b7952800-4f6c-11eb-9bf9-da781b037017.png)
![image](https://user-images.githubusercontent.com/37834008/103659741-1064c080-4f6d-11eb-90af-2f19b14a997f.png)
![image](https://user-images.githubusercontent.com/37834008/103659828-283c4480-4f6d-11eb-85b0-8df51f53e77d.png)

It's a very first version, and I need to clean up code and change some variables names as I used segment nomenclature according to app_segment_clean command, but I want to use names referencing to rooms cleanup. It has multiple rooms selection option, but it causes that card size changing. I am not sure if it's acceptable. I also have a previous version with a list where you may choose only one room at the time.

The code could be not perfect as I am not a programmer anymore, and I have never written in JS. I could send you this initial version, and maybe you would like to review it, share comments and check if it's worth to put additional work on that and commit it in the future? Then I will refactor it and make a pull request.

**Comment by PiotrMachowski** [comment]
@LucasBednarek it looks nice, but there is a small problem from my side: I try to avoid adding new features to this version of a card, because I want to have it completely rewritten in version 2.0.0

**Comment by LucasBednarek** [comment]
@PiotrMachowski Great to hear there is a new version on the horizon. Have you already planned any release date?

I am sharing my dirty version here. Maybe it helps someone during the time waiting for a new 2.0.0 version. For languages other than English, the text.js file needs to be aligned accordingly.

Based on v1.2.1: [xiaomi_vacuum_map_card.zip](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/files/5771107/xiaomi_vacuum_map_card.zip)

**Comment by PiotrMachowski** [comment]
@LucasBednarek no, I have been postponing it for a quite some time now...

**Comment by markrennie71** [comment]
> @PiotrMachowski Great to hear there is a new version on the horizon. Have you already planned any release date?
> 
> I am sharing my dirty version here. Maybe it helps someone during the time waiting for a new 2.0.0 version. For languages other than English, the text.js file needs to be aligned accordingly.
> 
> Based on v1.2.1: [xiaomi_vacuum_map_card.zip](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/files/5771107/xiaomi_vacuum_map_card.zip)

works a treat, thank you. Would be nice to select several rooms at once, but does me for now :)

**Comment by LucasBednarek** [comment]
@markrennie71 it should be possible to select several rooms at once. Chosen rooms will be bolded. May you check that again?

**Comment by markrennie71** [comment]
> @markrennie71 it should be possible to select several rooms at once. Chosen rooms will be bolded. May you check that again?

You are right.. I hadn't noticed it was bold. Brilliant. Thanks again. Now only if I cod get th damn S50 to clean edges....

**Comment by silentgecko** [comment]
@PiotrMachowski any update on this?
I would love the feature! Personally i don't like zones, and if i can just select rooms, like in the xiaomi app, that would be great!

**Comment by roopesh** [comment]
@LucasBednarek I really want to try the card you created.  However, my segments don't show up.  Is there any trick to this?  I am using Xiaomi Map Extractor for the camera & calibration.
```yaml
type: 'custom:xiaomi-vacuum-map-card'
entity: vacuum.s5max_upstairs
map_camera: camera.s5max
camera_calibration: true
segments:
  - name: Master_Bathroom
    segment: 16
  - name: Upstairs_Hallway
    segment: 17
  - name: Master_Bedroom
    segment: 18
  - name: Office_Bathroom
    segment: 19
  - name: Office_Closet
    segment: 20
  - name: Loft
    segment: 21
  - name: Office
    segment: 22
  - name: Laundry_Room
    segment: 23
  - name: Rohans_Room
    segment: 24
  - name: Rohans_Closet
    segment: 25
  - name: Ashas_Room
    segment: 26
  - name: Rohans_Bathroom
    segment: 27
  - name: Ashas_Bathroom
    segment: 28
  - name: Ashas_Closet
    segment: 29
  - name: Closet
    segment: 30
```
