### ISSUE TITLE
TITLE_MY

### ISSUE THREAD

**Issue by gena053** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#474]
### Integration repository

https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/releases/tag/v2.1.0

### Supported features

- [X] Zone cleaning (using 4 coordinates)
- [X] Room cleaning (using room id/number)
- [X] Going to point (using 2 coordinates)
- [X] Cleaning a point (using 2 coordinates)
- [ ] Others

### Vacuum entity/entities

```yaml
vacuum.dreame_p2140a_ccf0_robot_cleaner
```

### Service calls

```yaml
fan_speed_list: Silent, Basic, Strong, Full Speed
battery_level: 100
battery_icon: mdi:battery
fan_speed: Silent
model: dreame.vacuum.p2140a
lan_ip: 192.168.1.110
mac_address: 24:18:C6:E9:CC:F0
entity_class: MiotVacuumEntity
exclude_miot_services: consumable, annoy, remote, time
exclude_miot_properties: delete_timer, clean_info, map_view, frame_info
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:dreame-p2140a:1
vacuum.status: 2
vacuum.fault: 68
vacuum.mode: 0
vslam_extend.save_map_status: 1
clean_logs.first_clean_time: 1656931794
clean_logs.total_clean_time: 2671
clean_logs.total_clean_times: 238
clean_logs.total_clean_area: 2129
audio.volume: 43
audio.voice_packet_id: EN
audio.voice_change_state: {\"id\":\"\",\"state\":\"idle\",\"progress\":0}
audio.set_voice.error: -1
do_not_disturb.enable: true
do_not_disturb.start_time: 22:00
do_not_disturb.end_time: 08:00
vacuum_extend.work_mode: 14
vacuum_extend.cleaning_time: 4
vacuum_extend.cleaning_area: 2
vacuum_extend.cleaning_mode: 0
vacuum_extend.mop_mode: 3
vacuum_extend.waterbox_status: 1
vacuum_extend.task_status: 0
vacuum_extend.clean_extend_data.error: -1
break_point_restart-4-11: 1
vacuum_extend.carpet_press: 0
vacuum_extend.serial_number: 33239/BFACX12Q201626
vacuum_extend.remote_state.error: -1
vacuum_extend.keep_sweeper_time: 0
vacuum_extend.faults: 68
filter.filter_life_level: 70
filter.filter_left_time: 105
brush_left_time-10-1: 155
brush_life_level-10-2: 77
brush_cleaner.brush_left_time: 255
brush_cleaner.brush_life_level: 85
battery.charging_state: 1
state_updater: lan
vacuum.status_desc: Idle
friendly_name: Mi Robot Vacuum-Mop 2C Robot Cleaner
supported_features: 13048
sub_entities: vacuum-2.status-1, filter-11.filter_life_level-1, filter-11.filter_left_time-2, battery-3.battery_level-1, battery-3.charging_state-2, brush_cleaner-9.brush_left_time-1, brush_cleaner-9.brush_life_level-2, brush_cleaner-10.brush_left_time-1, brush_cleaner-10.brush_life_level-2
```
