### ISSUE TITLE
Select mode bug for web browser

### ISSUE THREAD

**Issue by cataseven** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#481]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Doesnt matter chrome or firefox mode selection list cannot be seen if the card is located in a Grid. I tried to create a new stand alone card on different page then it is working but the list appear on the right side.

I also saw that, the popup list is shown behind the other cards when I tried from my mobile phone.

![2022-09-18 16_25_08-Overview – Home Assistant](https://user-images.githubusercontent.com/52464808/190904518-2e257298-0a09-4688-b288-2de5794fcc5a.png)
![2022-09-18 16_25_24-Overview – Home Assistant](https://user-images.githubusercontent.com/52464808/190904522-74b0f6f3-2454-4379-a61e-0f34db321afb.png)
![IMG_20220918_162803](https://user-images.githubusercontent.com/52464808/190904616-cb508fc2-b1a8-4458-98de-9d657e4c6031.jpg)

### What version of a card has described problem?

v2.1.2

### What was the last working version card?

v2.1.0

### What vacuum model do you have problems with?

vioami v13

### Which integration do you use to control your vacuum (link)?

marotoweb/viomi SE

### What browser (browsers/apps) does have this problem?

All

### What version of Home Assistant do you use?

2022.9

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml

          - type: custom:state-switch
            entity: input_boolean.show_hide_map
            states:
              'on':
                type: custom:state-switch
                entity: input_select.map
                transition: flip-x
                states:
                  Downstairs:
                    type: custom:xiaomi-vacuum-map-card
                    entity: vacuum.viomi_se
                    preset_name: Downstairs
                    map_source:
                      camera: camera.xiaomi_cloud_map_extractor
                      crop:
                        top: 900
                        bottom: 275
                        left: 575
                        right: 850
                    calibration_source:
                      camera: true
                    clean_selection_on_start: true
                    map_locked: true
                    two_finger_pan: true
                    icons: []
                    tiles: []
                    map_modes:
                      - template: vacuum_clean_segment
                        max_selections: 4
                        repeats_type: NONE
                        selection_type: ROOM
                        predefined_selections:
                          - id: 10
                            label:
                              text: Staircase
                              x: -5.2
                              'y': -8.4
                            icon:
                              name: mdi:water-plus
                              x: -5.2
                              'y': -8.7
                          - id: 11
                            label:
                              text: Kitchen
                              x: -0.9
                              'y': -9.85
                            icon:
                              name: mdi:water-plus
                              x: -0.9
                              'y': -10.15
                          - id: 12
                            label:
                              text: Guest Room
                              x: -5.8
                              'y': -12.1
                            icon:
                              name: mdi:water-plus
                              x: -5.8
                              'y': -12.4
                          - id: 13
                            label:
                              text: Hallway
                              x: -3.7
                              'y': -9.8
                            icon:
                              name: mdi:water-plus
                              x: -3.7
                              'y': -10.1
                          - id: 15
                            label:
                              text: Living Room
                              x: -2.2
                              'y': -3.5
                            icon:
                              name: mdi:water-plus
                              x: -2.2
                              'y': -3.8
                      - template: vacuum_clean_zone
                      - template: vacuum_clean_point
                    vacuum_platform: marotoweb/viomise
                    style: |
                      ha-card {
                        --map-card-room-label-color: rgb(255, 255, 255);
                        --map-card-room-label-color-selected: rgb(255, 255, 255);
                        --map-card-room-icon-wrapper-size: 18px;
                        --map-card-room-icon-size: 14px;
                      }
```
