### ISSUE TITLE
I try everything. Still doesn't work

### ISSUE THREAD

**Issue by Netwalkerul** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#486]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Failed to retrieve map from vacuum.
Invalid calibration, please check your configuration.
Sensors left: unaivalableh (same to filter and brushes

I try everything I get on these subjects. Nothing works. Please help me.
![Screenshot_1](https://user-images.githubusercontent.com/115063124/193993400-0d2dfc36-7278-435e-976d-1d0b3788dd49.png)

### What version of a card has described problem?

v2.2.0

### What vacuum model do you have problems with?

Roborock S6 Pure

### Which integration do you use to control your vacuum (link)?

Xiaomi Cloud Map Extractor

### What browser (browsers/apps) does have this problem?

Chrome

### What version of Home Assistant do you use?

2022.9.7

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.roborock_s6_pure
vacuum_platform: default
map_locked: true
two_finger_pan: true
```

### Additional information

In configuration.yaml

`camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret mihost
    token: !secret mitoken
    username: !secret miusername
    password: !secret mipassword
    draw: ["all"]
    attributes:
      - calibration_points`
