### ISSUE TITLE
Room Cleaning Queue

### ISSUE THREAD

**Issue by cataseven** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#487]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

If I select more than 1 room, It cleans the first room and then returns to dock.

### What version of a card has described problem?

v2.1.2

### What was the last working version card?

v2.1.1

### What vacuum model do you have problems with?

viomi v13

### Which integration do you use to control your vacuum (link)?

https://github.com/marotoweb/home-assistant-vacuum-viomise

### What browser (browsers/apps) does have this problem?

All

### What version of Home Assistant do you use?

2022.10

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.viomi_se
preset_name: Upstairs
map_source:
  camera: camera.xiaomi_cloud_map_extractor
  crop:
    top: 500
    bottom: 475
    left: 450
    right: 300
calibration_source:
  camera: true
clean_selection_on_start: true
map_locked: true
two_finger_pan: true
icons: []
tiles: []
map_modes:
  - template: vacuum_clean_segment
    max_selections: 4
    repeats_type: NONE
    selection_type: ROOM
    predefined_selections:
      - id: 10
        label:
          text: Bathroom
          x: 3.25
          'y': -2.75
        icon:
          name: mdi:water-plus
          x: 3.25
          'y': -3.25
      - id: 11
        label:
          text: Bedroom
          x: -1.75
          'y': -1
        icon:
          name: mdi:water-plus
          x: -1.75
          'y': -1.5
      - id: 14
        label:
          text: Work Room
          x: 6
          'y': 1.25
        icon:
          name: mdi:water-plus
          x: 6
          'y': 0.75
      - id: 15
        label:
          text: Hallway
          x: 1.75
          'y': 0.75
        icon:
          name: mdi:water-plus
          x: 1.75
          'y': 0.25
      - id: 16
        label:
          text: Kids Room
          x: 7.25
          'y': -2.1
        icon:
          name: mdi:water-plus
          x: 7.25
          'y': -2.6
  - template: vacuum_clean_zone
  - template: vacuum_clean_point
vacuum_platform: marotoweb/viomise
style: |
  ha-card {
    --map-card-room-label-color: rgb(255, 255, 255);
    --map-card-room-label-color-selected: rgb(255, 255, 255);
    --map-card-room-icon-wrapper-size: 18px;
    --map-card-room-icon-size: 14px;
  }
```

**Comment by PiotrMachowski** [comment]
Well, there is a reason why it is only possible to select one room when using this platform - Its current config allows only for one room to be cleaned.

You can check out config from [this comment](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/187#discussioncomment-2524524) and tell me if it works for you. If it works then I might add it to viomise platform

**Comment by cataseven** [comment]
yes, this worked! You are great!

```
map_modes:
  - name: Room Cleaning
    icon: mdi:floor-plan
    selection_type: ROOM
    predefined_selections:
      - id: 10
        label:
          text: Bathroom
          x: 3.25
          'y': -2.75
        icon:
          name: mdi:water-plus
          x: 3.25
          'y': -3.25
      - id: 11
        label:
          text: Bedroom
          x: -1.75
          'y': -1
        icon:
          name: mdi:water-plus
          x: -1.75
          'y': -1.5
      - id: 14
        label:
          text: Work Room
          x: 6
          'y': 1.25
        icon:
          name: mdi:water-plus
          x: 6
          'y': 0.75
      - id: 15
        label:
          text: Hallway
          x: 1.75
          'y': 0.75
        icon:
          name: mdi:water-plus
          x: 1.75
          'y': 0.25
      - id: 16
        label:
          text: Kids Room
          x: 7.25
          'y': -2.1
        icon:
          name: mdi:water-plus
          x: 7.25
          'y': -2.6
    max_selections: 4
    repeats_type: EXTERNAL
    max_repeats: 1
    service_call_schema:
      service: vacuum.send_command
      service_data:
        entity_id: '[[entity_id]]'
        command: set_mode_withroom
        params: >-
          [ "{{state_attr(\"[[entity_id]]\", \"is_mop\")}}", [[repeats]],
          [[selection_size]], [[selection_unwrapped]] ]|[[jsonify]]
```
