### ISSUE TITLE
Default Zoom Level

### ISSUE THREAD

**Issue by cataseven** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#488]
### Description

Is it possible to set default zoom level? I would like to see the map at first all zoom out. It will also help to cropping options to fit more easily on the screen

### Solution

A zoom level from 0-10

**Comment by PiotrMachowski** [comment]
It is already possible using [map cropping](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card#cropping-options)

```yaml
map_source:
  camera: camera.xiaomi_cloud_map_extractor
  crop:
    top: 10
    bottom: 20
    left: 30
    right: 40
```
