### ISSUE TITLE
the drop-down menu overlaps the interface

### ISSUE THREAD

**Issue by Zver5** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#491]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

The menu of the drop-down window moves to different places
<img width="589" alt="Screenshot_1" src="https://user-images.githubusercontent.com/25123525/196036866-869e6cf5-c9e2-4fdf-b610-a669ba2a96c9.png">

### What version of a card has described problem?

v2.1.2

### What vacuum model do you have problems with?

rockrobo.vacuum.v1

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Chrome

### What version of Home Assistant do you use?

Home Assistant 2022.10.4

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
title: Дюша Метёлкин
language: ru
map_locked: true
debug: true
vacuum_platform: default
preset_name: Карта онлайн
entity: vacuum.mi_robot_vacuum
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_modes:
  - name: Зона
    icon: mdi:select-drag
    run_immediately: false
    coordinates_rounding: true
    selection_type: MANUAL_RECTANGLE
    max_selections: 5
    repeats_type: EXTERNAL
    max_repeats: 1
    service_call_schema:
      service: xiaomi_miio.vacuum_clean_zone
      service_data:
        zone: '[[selection]]'
        repeats: '[[repeats]]'
    predefined: 'false'
    target:
      entity_id: '[[entity_id]]'
  - name: Выбранные зоны
    icon: mdi:floor-plan
    run_immediately: false
    coordinates_rounding: true
    selection_type: PREDEFINED_RECTANGLE
    max_selections: 5
    repeats_type: EXTERNAL
    max_repeats: 1
    service_call_schema:
      service: xiaomi_miio.vacuum_clean_zone
      service_data:
        zone: '[[selection]]'
        repeats: '[[repeats]]'
        entity_id: '[[entity_id]]'
    predefined_selections:
      - zones:
          - - 25304
            - 22406
            - 28888
            - 25901
          - - 28888
            - 24955
            - 32379
            - 25648
          - - 25304
            - 19983
            - 28888
            - 22406
          - - 28888
            - 21333
            - 32643
            - 23192
      - zones:
          - - 25304
            - 22406
            - 28888
            - 25901
        label:
          text: Гостинная
          x: 26716
          'y': 24372
          offset_y: 25
        icon:
          name: mdi:bed
          x: 26716
          'y': 24372
      - zones:
          - - 28888
            - 24955
            - 32379
            - 25648
        label:
          text: Гардероб
          x: 30488
          'y': 25190
          offset_y: 25
        icon:
          name: mdi:wardrobe
          x: 30488
          'y': 25190
      - zones:
          - - 25304
            - 19983
            - 28888
            - 22406
        label:
          text: Кухня
          x: 26716
          'y': 21500
          offset_y: 25
        icon:
          name: mdi:pot-mix
          x: 26716
          'y': 21500
      - zones:
          - - 28888
            - 21333
            - 32643
            - 23192
        label:
          text: Коридор
          x: 30488
          'y': 22330
          offset_y: 25
        icon:
          name: mdi:door-open
          x: 30488
          'y': 22330
      - zones:
          - - 19763
            - 18965
            - 21346
            - 20365
        label:
          text: Ванна
          x: 31287
          'y': 19682
          offset_y: 25
        icon:
          name: mdi:shower
          x: 31287
          'y': 19682
  - name: Комната
    icon: mdi:floor-plan
    run_immediately: false
    coordinates_rounding: true
    selection_type: ROOM
    max_selections: 999
    repeats_type: REPEAT
    max_repeats: 1
    service_call_schema:
      service: xiaomi_miio.vacuum_clean_segment
      service_data:
        segments: '[[selection]]'
        entity_id: '[[entity_id]]'
    predefined_selections: []
    variables: {}
  - name: Выбрать & Go
    icon: mdi:map-marker-plus
    run_immediately: false
    coordinates_rounding: true
    selection_type: MANUAL_POINT
    max_selections: 999
    repeats_type: NONE
    max_repeats: 1
    service_call_schema:
      service: xiaomi_miio.vacuum_goto
      service_data:
        x_coord: '[[point_x]]'
        y_coord: '[[point_y]]'
        entity_id: '[[entity_id]]'
    predefined_selections: []
    variables: {}
  - name: Точка на карте
    icon: mdi:map-marker
    run_immediately: false
    coordinates_rounding: true
    selection_type: PREDEFINED_POINT
    max_selections: 999
    repeats_type: NONE
    max_repeats: 1
    service_call_schema:
      service: xiaomi_miio.vacuum_goto
      service_data:
        x_coord: '[[point_x]]'
        y_coord: '[[point_y]]'
        entity_id: '[[entity_id]]'
    predefined_selections:
      - position:
          - 20850
          - 23387
        label:
          text: Корзина
          x: 28652
          'y': 20049
          offset_y: 35
        icon:
          name: mdi:delete-empty
          x: 28652
          'y': 20049
    variables: {}
  - name: Путь
    icon: mdi:map-marker-path
    run_immediately: false
    coordinates_rounding: true
    selection_type: MANUAL_PATH
    max_selections: 999
    repeats_type: NONE
    max_repeats: 1
    service_call_schema:
      service: script.vacuum_follow_path
      service_data:
        service: xiaomi_miio.vacuum_goto
        mode: individual
        path: '[[selection]]'
        entity_id: '[[entity_id]]'
    predefined_selections: []
    variables: {}
additional_presets:
  - preset_name: 3D
    entity: vacuum.mi_robot_vacuum
    map_source:
      image: /local/ZverNewbok1.png
    calibration_source:
      calibration_points:
        - vacuum:
            x: 19000
            'y': 31000
          map:
            x: 400
            'y': 1400
        - vacuum:
            x: 19000
            'y': 24000
          map:
            x: 400
            'y': 300
        - vacuum:
            x: 31000
            'y': 24000
          map:
            x: 1400
            'y': 300
    map_modes:
      - name: Зона уборки 3D
        icon: mdi:select-drag
        selection_type: MANUAL_RECTANGLE
        max_selections: 5
        repeats_type: INTERNAL
        max_repeats: 5
        service_call_schema:
          service: vacuum.do_zones
          service_data:
            zones: '[[selection]]'
            repeats: '[[repeats]]'
            predefined: 'false'
          target:
            entity_id: '[[entity_id]]'
      - name: Выбранные зоны
        icon: mdi:texture-box
        selection_type: PREDEFINED_RECTANGLE
        max_selections: 5
        repeats_type: INTERNAL
        max_repeats: 5
        service_call_schema:
          service: vacuum.do_zones
          service_data:
            zones: '[[selection]]'
            repeats: '[[repeats]]'
            predefined: 'true'
          target:
            entity_id: '[[entity_id]]'
        predefined_selections:
          - zones:
              - - 19000
                - 32000
                - 28000
                - 24500
            label:
              text: Гостинная
              x: 22413
              'y': 25500
              offset_y: 25
            icon:
              name: mdi:bed
              x: 22413
              'y': 25500
      - name: Manual Point
        icon: mdi:map-marker-plus
        selection_type: MANUAL_POINT
        max_selections: 5
        repeats_type: NONE
        max_repeats: 5
        service_call_schema:
          service: vacuum.do_point
          service_data:
            point: '[[selection]]'
            point_x: '[[point_x]]'
            point_y: '[[point_y]]'
            repeats: '[[repeats]]'
            predefined: 'false'
          target:
            entity_id: '[[entity_id]]'
      - name: Predefined Point
        icon: mdi:map-marker
        selection_type: PREDEFINED_POINT
        max_selections: 5
        repeats_type: NONE
        max_repeats: 5
        service_call_schema:
          service: vacuum.do_point
          service_data:
            point: '[[selection]]'
            repeats: '[[repeats]]'
            point_x: '[[point_x]]'
            point_y: '[[point_y]]'
            predefined: 'true'
          target:
            entity_id: '[[entity_id]]'
        predefined_selections:
          - position:
              - 28006
              - 28036
            label:
              text: Emptying
              x: 28006
              'y': 28036
              offset_y: 35
            icon:
              name: mdi:broom
              x: 28006
              'y': 28036
          - position:
              - 32143
              - 26284
            label:
              text: Sofa
              x: 32143
              'y': 26284
              offset_y: 35
            icon:
              name: mdi:sofa
              x: 350
              'y': 350
```
