### ISSUE TITLE
Vacuum map card not working as a conditional card

### ISSUE THREAD

**Issue by asetGem** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#495]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

When I create a standalone vacuum map card, everything works perfectly. 
Now, I wanted to show this card only when I hit a button. So I put this same card inside a conditional card.
The card shows up and is hidden as expected when I hit the corresponding button. However, even if it shows up, it does not control the vacuum anymore.
I checked on the interface, and I can see that on the standalone card, when I select something, it appears in the "selection" field. With the card inside a conditional, the "selection" field remains empty whatever I select (in any mode, room, zone...). So I guess it is sending to my vacuum to clean...nothing and that is why it is not working.

Here is the card "alone":
![vacuum-working-room](https://user-images.githubusercontent.com/15121352/200111435-594f4ea9-4ec3-4fd7-99f4-950484ebe2d3.png)
![vacuum-working](https://user-images.githubusercontent.com/15121352/200111440-a785c7fb-b116-41ca-bc16-3a563f9c5c6a.png)

And here is the same card (exactly same code) but inside a conditional:

![vacuum-conditonal-room](https://user-images.githubusercontent.com/15121352/200111472-d8a5131b-793e-4d98-8f68-aa9363d74317.png)
![vacuum-conditonal-zone](https://user-images.githubusercontent.com/15121352/200111478-74373672-b7b2-48aa-be6f-ea05fe36f50f.png)

### What version of a card has described problem?

v2.1.2

### What vacuum model do you have problems with?

dreame_d9

### Which integration do you use to control your vacuum (link)?

https://github.com/al-one/hass-xiaomi-miot

### What browser (browsers/apps) does have this problem?

chrome/firefox/android app

### What version of Home Assistant do you use?

2022.11.1

### What type of installation are you running?

Home Assistant Supervised

### Card's configuration

```yaml
type: conditional
conditions:
  - entity: input_boolean.map_mode_enabled
    state: 'on'
card:
  type: custom:xiaomi-vacuum-map-card
  icons: []
  tiles: []
  preset_name: Plan de l'appart
  map_source:
        camera: camera.vacuum
  calibration_source:
        camera: true
  entity: vacuum.dreame
  vacuum_platform: default
  map_modes:
    - template: vacuum_clean_segment
      name: Nettoyer une piece
      service_call_schema:
        [...]
      predefined_selections:
         [...]
    - template: vacuum_clean_zone
      name: Nettoyer une zone
      service_call_schema:
          [...]
    - template: vacuum_goto_predefined
      predefined_selections:
         [...]
  map_locked: false
  two_finger_pan: true
```
```


### Javascript errors shown in the browser's console (if applicable)

_No response_

### Additional information

_No response_
