### ISSUE TITLE
Example config gets corrupted when added via 'Configure UI'

### ISSUE THREAD

**Issue by nickdos** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#5]
I'm using the UI editing option for LoveLace (not `lovelace.yml`). When I paste the example config into my `Raw config editor` via the UI, the YML code looks fine. But when I save and exit and then go back into the editor, the YML has been sanitised to look like:

```
      - base_position:
          x: 399
          'y': 370
        entity: vacuum.xiaomi_vacuum
        map_image: /local/custom_lovelace/xiaomi_vacuum_map_card/map.png
        reference_point:
          x: 459
          'y': 308
        type: 'custom:xiaomi-vacuum-map-card'
        zones:
          - - - 20000
              - 28600
              - 26400
              - 27800
```

Which explains why my card is corrupted and doesn't work.
