### ISSUE TITLE
Support Wyze Robot Vacuum

### ISSUE THREAD

**Issue by dnestico** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#506]
### Integration repository

https://github.com/romedtino/simple-wyze-vac

### Supported features

- [ ] Zone cleaning (using 4 coordinates)
- [X] Room cleaning (using room id/number)
- [ ] Going to point (using 2 coordinates)
- [ ] Cleaning a point (using 2 coordinates)
- [X] Others

### Vacuum entity/entities

```yaml
fan_speed_list:
  - Quiet
  - Standard
  - Strong
battery_level: 100
battery_icon: mdi:battery-charging-100
fan_speed: Strong
filter: 146
main_brush: 296
side_brush: 196
rooms: []
friendly_name: Nestico Robot Vacuum
supported_features: 11256
```

### Service calls

```yaml
- simple_wyze_vac.sweep_rooms
- vacuum.send_command

command examples:
- sweep_auto
- sweep_rooms
- vacuum.set_fan_speed
- update
- refresh_token
```

### Other info

**Supported Features:** (copied from GitHub)

- TOTP (Note: This is NOT the same thing as the 6 digit code you get from your Authenticator app. Please see [TOTP](https://github.com/romedtino/simple-wyze-vac#totp) section)
- Start
- Stop / Pause
- Return to Base
- Filter lifespan information (Main filter, main brush and side brush)
- Camera entity to show last vacuum map
- Room names as toggleable switches (For area cleaning)
- Room names as vacuum attributes
- Optional [Polling](https://github.com/romedtino/simple-wyze-vac#polling)
- Sweep Rooms as a service using simple_wyze_vac.sweep_rooms or vacuum.send_command with command sweep_auto
- Using built-in service and choosing the switch entities/rooms you want to do a sweep
