### ISSUE TITLE
Platform: custom Roborock integration (not via Miio)

### ISSUE THREAD

**Issue by Xyaren** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#518]
### Integration repository

https://github.com/humbertogontijo/homeassistant-roborock

### Supported features

- [X] Zone cleaning (using 4 coordinates)
- [X] Room cleaning (using room id/number)
- [X] Going to point (using 2 coordinates)
- [X] Cleaning a point (using 2 coordinates)
- [ ] Others

### Vacuum entity/entities

```yaml
vaccuum.name:
  fan_speed_list:
    - Silent
    - Balanced
    - Turbo
    - Max
  battery_level: 100
  battery_icon: mdi:battery
  fan_speed: Turbo
  icon: mdi:robot-vacuum
  friendly_name: Fussel
  supported_features: 16383
```
```yaml
camera.name:
  access_token: dfe6XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  entity_picture: >-
    /api/camera_proxy/camera.fussel?token=dfe6XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  icon: mdi:map-outline
  friendly_name: Fussel
  supported_features: 1
  calibration_points:
    - vacuum:
        x: 25500
        'y': 25500
      map:
        x: 191
        'y': 144
    - vacuum:
        x: 26500
        'y': 25500
      map:
        x: 211
        'y': 144
    - vacuum:
        x: 25500
        'y': 26500
      map:
        x: 191
        'y': 124
  charger:
    x: 26026
    'y': 25743
    a: -179
  image:
    size: 202960
    offset_y: 225
    offset_x: 319
    height: 430
    scale: 1
    rotation: 0
    width: 472
  is_empty: false
  no_go_areas: []
  no_mopping_areas:
    - x0: 21307
      y0: 22010
      x1: 22401
      y1: 22010
      x2: 22401
      y2: 20375
      x3: 21307
      y3: 20375
    - x0: 21396
      y0: 18858
      x1: 22385
      y1: 18858
      x2: 22385
      y2: 17184
      x3: 21396
      y3: 17184
  path:
    point_length: 0
    point_size: 4
    angle: 0
    path:
      - []
  room_numbers:
    '16': null
    '17': null
    '18': null
    '19': null
  rooms:
    '16':
      x0: 24150
      y0: 16650
      x1: 26050
      y1: 20400
    '17':
      x0: 20900
      y0: 16650
      x1: 24100
      y1: 22050
    '18':
      x0: 24050
      y0: 20450
      x1: 26050
      y1: 23950
    '19':
      x0: 20950
      y0: 22250
      x1: 26050
      y1: 26800
  vacuum_position:
    x: 25847
    'y': 25738
    a: 1
  vacuum_room: 19
  walls:
    - x0: 25222
      y0: 23066
      x1: 25223
      y1: 20478
```

### Service calls
Resetting consumables
```yaml
service: vacuum.send_command
data:
  command: reset_consumable
  params: sensor_dirty_time
target:
  entity_id: vacuum.fussel
```

Goto
```yaml
service: vacuum.send_command
data:
  command: app_goto_target
  params:
    - 23141
    - 24926
target:
  entity_id: vacuum.fussel
```

Clean Room
```yaml
service: vacuum.send_command
data:
  command: app_segment_clean
  params:
    - 19
target:
  entity_id: vacuum.fussel
```
Spot Clean
```yaml
service: vacuum.clean_spot
data: {}
target:
  entity_id: vacuum.fussel
```

Locate (Robot announces "I am here" via Speakers)
```yaml
service: vacuum.locate
data: {}
target:
  entity_id: vacuum.fussel
```

Stop
```yaml
service: vacuum.stop
data: {}
target:
  entity_id: vacuum.fussel
````
There is also 
 - start_pause
 - stop
 - pause
 - toggle
 - turn_off
 - turn_on

RTB
```yaml
service: vacuum.return_to_base
data: {}
target:
  entity_id: vacuum.fussel

```

Untested:
```yaml
service: vacuum.set_fan_speed
data:
  fan_speed: unknown
target:
  entity_id: vacuum.fussel
```

### Other info

The integration is in a very early stage but being worked on.
Attributes on vaccuum are currently still missing. https://github.com/humbertogontijo/homeassistant-roborock/issues/16

All in all very similar to xiaomiMiio.

**Rooms use numerical Ids instead of strings!**

**Comment by Xyaren** [comment]
Further information in this discussion: https://github.com/humbertogontijo/homeassistant-roborock/discussions/40

**Comment by PiotrMachowski** [comment]
@Xyaren @Matte8519
Could you provide me some info about entities created by Roborock integration?

1. Open your main dashboard
2. Open browser's dev tools (with `F12` button)
3. Open console
4. Paste following code in the console:
    ```js
    getDeviceData = async (entity) => {
        const hass = document.querySelector("home-assistant").hass;
        const vacuumDeviceId = (
            await hass.callWS({
                type: "config/entity_registry/get",
                entity_id: entity,
            })
        )["device_id"];
        const vacuumSensors = (
            await hass.callWS({
                type: "config/entity_registry/list",
            })
        ).filter(e => e.device_id === vacuumDeviceId);
        Promise.all(
            vacuumSensors.map(vs =>
                hass.callWS({
                    type: "config/entity_registry/get",
                    entity_id: vs.entity_id,
                }),
            ),
        ).then(v => console.log(v));
    }
    ```
5. Retrieve entities related to the vacuum entity using following command:
    ```js
    getDeviceData("vacuum.your_vacuum");
    ```
6. Two entries should be printed, please copy content of the second one (click with right mouse button on it and choose "Copy object" option)
7. Send me copied values to `piotr.machowski.dev [at] gmail.com`

**Comment by PiotrMachowski** [comment]
@Xyaren great, thank you!

**Comment by PiotrMachowski** [comment]
Can you check out this version?

[v2.1.3-beta.1](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/releases/tag/v2.1.3-beta.1)

**Comment by Xyaren** [comment]
![Uploading image.png…]()
The default looks better than the actual homeassistant-roborock template ?

**Comment by PiotrMachowski** [comment]
That's weird, it should generate more tiles than default (Miio) platform... Are there any errors in browser's console? Can you show card's config?

**Comment by Xyaren** [comment]
![image](https://user-images.githubusercontent.com/5864045/223546013-ea714e77-62fe-4f42-b936-5eaadf4f57e4.png)

**Comment by PiotrMachowski** [comment]
It looks good 👍 I have not added all tiles that you have configured manually because it seems to be a bit too much. Buuuuut I might add them and create an instruction that will explain how to disable a specific tile instead

**Comment by Xyaren** [comment]
I think the "Status" is quite useful to have the other ones are probably not that useful.

**Comment by PiotrMachowski** [comment]
Status tile should work, can you show attributes of your vacuum entity?

**Comment by Xyaren** [comment]
```yaml
fan_speed_list:
  - 'off'
  - silent
  - balanced
  - turbo
  - max
  - max_plus
  - custom
mop_mode_list:
  - standard
  - deep
  - deep_plus
  - custom
mop_intensity_list:
  - 'off'
  - mild
  - moderate
  - intense
  - custom
msg_ver: 2
msg_seq: 1937
state: docked
battery: 100
clean_time: 50
clean_area: 382500
error_code: 0
map_present: 1
in_cleaning: 0
in_returning: 0
in_fresh_state: 1
lab_status: 3
water_box_status: 0
fan_power: 102
dnd_enabled: 0
map_status: 3
is_locating: 0
lock_status: 0
water_box_mode: 202
water_box_carriage_status: 0
mop_forbidden_enable: 0
adbumper_status:
  - 0
  - 0
  - 0
water_shortage_status: 0
dock_type: 0
dust_collection_status: 0
auto_dust_collection: 1
mop_mode: standard
debug_mode: 0
dock_error_status: 0
unsave_map_reason: 4
unsave_map_flag: 0
battery_level: 100
battery_icon: mdi:battery-charging-100
fan_speed: balanced
vacuum_status: charging
mop_intensity: moderate
error: Keine
icon: mdi:robot-vacuum
friendly_name: Fussel
supported_features: 16383

````
