### ISSUE TITLE
Roborock E5 (roborock.vacuum.a01) Invalid calibration, check your configuration

### ISSUE THREAD

**Issue by Arakon** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#522]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

![image](https://user-images.githubusercontent.com/12016360/209962182-7acaa6c5-169a-4b9c-92e2-25e93ba00155.png)
configuration.yaml:
```
camera:
    platform: xiaomi_cloud_map_extractor
    host: 192.168.0.*
    token: 9def21*
    username: -
    password: -
    draw: ['all']
    attributes:
      - calibration_points
```

I believe it's set up correctly, but I can not get any map data. I can see the map in the app.
Everything else (controls, status) works just fine, so it's not a connection issue, I believe.

Any ideas?

### What version of a card has described problem?

v2.1.2

### What vacuum model do you have problems with?

roborock.vacuum.a01

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Any

### What version of Home Assistant do you use?

core-2022.11.5

### What type of installation are you running?

Home Assistant Supervised

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.robot_vacuum
vacuum_platform: default
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
```
