### ISSUE TITLE
Map not updating on Home Assistant

### ISSUE THREAD

**Issue by xtraorange** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#531]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Last night I connected my Roborock s4 to Home Assistant.  I then ran the vacuum, divided the rooms, and reran the vacuum to fix one area (mirror).

For some reason, the map on Home Assistant hasn't been updated.  It has about half of the rooms divided and nothing past that point.  Oddly, if I load a new "floor" and start vacuuming, it immediately updates what I'm seeing on home assistant according to what the vacuum is seeing.

It's as though a map is stuck in cache and just won't update.  If I run the vacuum, it shows its movement around the map though.

Anything I can try?

### What version of a card has described problem?

v2.1.2

### What vacuum model do you have problems with?

roborock.vacuum.a19

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Chrome

### What version of Home Assistant do you use?

2023.1.4

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.roborock_vacuum_a19
vacuum_platform: default
```

### Javascript errors shown in the browser's console (if applicable)

```shell
No errors
```
