### ISSUE TITLE
Failed to call service vacuum/vacuum_clean_segment. Service not found

### ISSUE THREAD

**Issue by kmanan** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#532]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

I am trying to clean a specific room but when I select the room and press "play", I get the error Service not found. Error image: https://ibb.co/xqkk9vx

### What version of a card has described problem?

v2.1.2

### What was the last working version card?

N/A

### What vacuum model do you have problems with?

S6 MaxV

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Edge Chromium and iOS HA app

### What version of Home Assistant do you use?

2023.1.7

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.roborock_s6_maxv
vacuum_platform: KrzysztofHajdamowicz/miio2
map_modes:
  - template: vacuum_clean_segment
    predefined_selections:
      - id: '16'
        icon:
          name: mdi:broom
          x: 23250
          'y': 23550
        label:
          text: Guest Room
          x: 23250
          'y': 23550
          offset_y: 35
        outline:
          - - 19000
            - 21850
          - - 27500
            - 21850
          - - 27500
            - 25250
          - - 19000
            - 25250
      - id: '17'
        icon:
          name: mdi:broom
          x: 31125
          'y': 26825
        label:
          text: Kitchen
          x: 31125
          'y': 26825
          offset_y: 35
        outline:
          - - 29450
            - 24550
          - - 32800
            - 24550
          - - 32800
            - 29100
          - - 29450
            - 29100
      - id: '18'
        icon:
          name: mdi:broom
          x: 28525
          'y': 23875
        label:
          text: Guest Bathroom
          x: 28525
          'y': 23875
          offset_y: 35
        outline:
          - - 27550
            - 22700
          - - 29500
            - 22700
          - - 29500
            - 25050
          - - 27550
            - 25050
      - id: '19'
        icon:
          name: mdi:broom
          x: 34450
          'y': 28825
        label:
          text: master Bedroom
          x: 34450
          'y': 28825
          offset_y: 35
        outline:
          - - 32150
            - 24150
          - - 36750
            - 24150
          - - 36750
            - 33500
          - - 32150
            - 33500
      - id: '20'
        icon:
          name: mdi:broom
          x: 35125
          'y': 25725
        label:
          text: Master Bathroom
          x: 35125
          'y': 25725
          offset_y: 35
        outline:
          - - 34000
            - 24250
          - - 36250
            - 24250
          - - 36250
            - 27200
          - - 34000
            - 27200
      - id: '21'
        icon:
          name: mdi:broom
          x: 24875
          'y': 29700
        label:
          text: Living Room
          x: 24875
          'y': 29700
          offset_y: 35
        outline:
          - - 19500
            - 24550
          - - 30250
            - 24550
          - - 30250
            - 34850
          - - 19500
            - 34850
      - id: '22'
        icon:
          name: mdi:broom
          x: 30250
          'y': 32475
        label:
          text: Dining Room
          x: 30250
          'y': 32475
          offset_y: 35
        outline:
          - - 27450
            - 29100
          - - 33050
            - 29100
          - - 33050
            - 35850
          - - 27450
            - 35850
      - id: '23'
        icon:
          name: mdi:broom
          x: 30075
          'y': 24450
        label:
          text: Office
          x: 30075
          'y': 24450
          offset_y: 35
        outline:
          - - 29900
            - 24400
          - - 30250
            - 24400
          - - 30250
            - 24500
          - - 29900
            - 24500
      - id: '24'
        icon:
          name: mdi:broom
          x: 33475
          'y': 22900
        label:
          text: Entrance
          x: 33475
          'y': 22900
          offset_y: 35
        outline:
          - - 31600
            - 21700
          - - 35350
            - 21700
          - - 35350
            - 24100
          - - 31600
            - 24100
      - id: '25'
        icon:
          name: mdi:broom
          x: 31125
          'y': 23500
        label:
          text: Office
          x: 31125
          'y': 23500
          offset_y: 35
        outline:
          - - 29450
            - 21850
          - - 32800
            - 21850
          - - 32800
            - 25150
          - - 29450
            - 25150
  - template: vacuum_clean_zone
  - template: vacuum_goto
```
