### ISSUE TITLE
Ecovacs Deebot 

### ISSUE THREAD

**Issue by kotana** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#535]
### Integration repository

https://github.com/DeebotUniverse/Deebot-4-Home-Assistant

### Supported features

- [X] Zone cleaning (using 4 coordinates)
- [X] Room cleaning (using room id/number)
- [X] Going to point (using 2 coordinates)
- [X] Cleaning a point (using 2 coordinates)
- [X] Others

### Vacuum entity/entities

```yaml
vacuum.t8

fan_speed_list:
  - quiet
  - normal
  - max
  - max+
battery_level: 100
battery_icon: mdi:battery-charging-100
fan_speed: normal
rooms:
  corridor: 0
  living_room: 4
  dining_room: 7
  bathroom: 2
  kitchen: 8
  storeroom: 9
last_error: 'NoError: Robot is operational (0)'
icon: phu:roborock
friendly_name: T8
supported_features: 15228
```

### Service calls

```yaml
service: vacuum.send_command
target:
  entity_id: vacuum.YOUR_ROBOT_NAME
data:
  command: getLifeSpan
  params:
    - sideBrush
    - brush
    - heap
```
