### ISSUE TITLE
Problem with the amount of room cleaning

### ISSUE THREAD

**Issue by witold-gren** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#538]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

When I set the number how many time mo room should be cleaned, it always clean room only one time. 
<img width="526" alt="Screenshot 2023-01-30 at 13 51 11" src="https://user-images.githubusercontent.com/2304938/215522057-4e8cf28b-ec81-44c1-8c2d-8657d555fead.png">

### What version of a card has described problem?

v2.2.0

### What vacuum model do you have problems with?

roborock.vacuum.s5e

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Chrome/Safari/iOS App

### What version of Home Assistant do you use?

2023.1.7

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.vacuum_map
calibration_source:
  camera: true
entity: vacuum.roborock_s5_max
vacuum_platform: default
```
