### ISSUE TITLE
Xiaomi Vacuum-Mop 2 Pro (ijai.vacuum.v3)

### ISSUE THREAD

**Issue by Vandiliz3r** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#539]
### Integration repository

https://www.home-assistant.io/integrations/xiaomi_miio/

### Supported features

- [X] Zone cleaning (using 4 coordinates)
- [X] Room cleaning (using room id/number)
- [X] Going to point (using 2 coordinates)
- [X] Cleaning a point (using 2 coordinates)
- [ ] Others

### Vacuum entity/entities

```yaml
fan_speed_list: 关, 节能, 标准, 强劲
battery_level: 53
battery_icon: mdi:battery-50
fan_speed: 关
model: ijai.vacuum.v3
lan_ip: 192.168.1.72
mac_address: 50:ec:50:45:d7:f5
entity_class: MiotVacuumEntity
home_room: Du Plessis Lair Kitchen
exclude_miot_services: order
exclude_miot_properties: zone_points, restrict_points, target_point
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:ijai-v3:1
vacuum.status: 2
vacuum.fault: 514
vacuum.mode: 0
vacuum.sweep_type: 0
vacuum.on: [1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1]
disturb.dnd_enable: 0
disturb.dnd_start_hour: 23
disturb.dnd_start_minute: 0
disturb.dnd_end_hour: 9
disturb.dnd_end_minute: 0
disturb.multi_prop_dnd: [0,23,0,9,0]
map.remember_state: 1
map.cur_map_id: 1675071972
map.map_num: 1
map.cur_cleaning_path: null
map.build_map: 0
map.has_new_map: 0
map.map_uploads.error: -4001 Property is not readable
sweep.repeat_state: 0
sweep.door_state: 3
sweep.cloth_state: 1
sweep.suction_state: 0
sweep.water_state: 0
sweep.mop_route: 0
sweep.side_brush_life: 98
sweep.side_brush_hours: 178
sweep.main_brush_life: 99
sweep.main_brush_hours: 358
sweep.hypa_life: 98
sweep.hypa_hours: 178
sweep.mop_life: 98
sweep.mop_hours: 178
sweep.direction.error: -4001 Property is not readable
sweep.time_zone: -7200
sweep.cur_lang: en_US
sweep.cleaning_time: 0
sweep.cleaning_area: 0
sweep.multi_prop_vacuum: [0,3,1,0,0,0,-7200,0,0.0,1,"en_US","334702602110A36057","en_US",6,-1,4,0,1,2]
sweep.tank_shake: 1
sweep.shake_shift: 2
alarm: 1
alarm.volume: 10
state_updater: lan
vacuum.status_desc: Paused
friendly_name: Mi Robot Vacuum-Mop 2 Pro Robot Cleaner
supported_features: 12539
sub_entities: vacuum-2.status-1, sweep-7.side_brush_life-8, sweep-7.main_brush_life-10, sweep-7.hypa_life-12, sweep-7.mop_life-14, alarm-4.alarm-1, sweep-7.repeat_state-1, vacuum-2.mode-4, vacuum-2.sweep_type-8, sweep-7.water_state-6, battery-3.battery_level-1
```

### Service calls

```yaml
Not sure
```
