### ISSUE TITLE
Translate tiles value using default translation or your custom templates

### ISSUE THREAD

**Issue by humbertogontijo** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#543]
### Description

The tiles are getting the raw value of the entity as of right now

### Solution

Add the translated value if translations map is not defined or add the ability to use https://github.com/PiotrMachowski/Home-Assistant-custom-components-Custom-Templates instead

**Comment by PiotrMachowski** [comment]
At this moment it is possible to use card's built-in translation mechanism:
```yaml
tiles:
  - entity: vacuum.alfred
    label: Status
    attribute: status
    icon: mdi:robot-vacuum
    translations:
      starting: Uruchamianie
      charger disconnected: Ładowarka odłączona
      idle: Nieaktywny
      remote control active: Zdalne sterowanie
      cleaning: Sprzątanie
```
Buuut not all languages contain appropriate translations: [source](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/tree/master/src/localize/languages)

Additionally, a lot of integrations use attributes that are not translated
