### ISSUE TITLE
Incorrect calibration

### ISSUE THREAD

**Issue by shurakenas** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#547]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Некорректная калибровка, проверьте вашу конфигурацию

### What version of a card has described problem?

v2.1.2

### What vacuum model do you have problems with?

dreame.vacuum.p2140o

### Which integration do you use to control your vacuum (link)?

https://github.com/ha0y/xiaomi_miot_raw

### What browser (browsers/apps) does have this problem?

Chrome

### What version of Home Assistant do you use?

core-2022.3.5

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
title: Xiaomi Vacuum Map Card
preset_name: Live map
entity: vacuum.p2140o
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_zone_predefined
vacuum_platform: default
```
