### ISSUE TITLE
Empty map_modes / Option to disable autogeneration of map_modes

### ISSUE THREAD

**Issue by rkorn86** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#548]
### Description

I would like a add live map preset without any map mode, just for following the vaccum position. Therefore it would be nice to set `map_modes: []`.

### Solution

Do not autogenerate map_modes if explicitly set to an empty array.

**Comment by PiotrMachowski** [comment]
Right now you can use following config:
```yaml
map_modes:
  - template: vacuum_clean_segment
    run_immediately: true
    repeats_type: NONE
```
