### ISSUE TITLE
Ecovacs Deebot

### ISSUE THREAD

**Issue by luigistrauss** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#552]
### Integration repository

https://github.com/DeebotUniverse/Deebot-4-Home-Assistant

### Supported features

- [X] Zone cleaning (using 4 coordinates)
- [X] Room cleaning (using room id/number)
- [ ] Going to point (using 2 coordinates)
- [ ] Cleaning a point (using 2 coordinates)
- [X] Others

### Vacuum entity/entities

```yaml
Entity:
vacuum.sid

States:
Docked, Returning to dock, Cleaning

Attributes:
fan_speed_list: quiet, normal, max, max+
battery_level: 100
battery_icon: mdi:battery-charging-100
fan_speed: quiet
rooms: 
kitchen: 0
lounge: 1
corridor: 2
living_room: 3
study: 6
bathroom: 7
laundry: 5

last_error: NoError: Robot is operational (0)
friendly_name: Sid
supported_features: 15228


Others: https://deebot.readthedocs.io/integrations/home-assistant/entities/
```

### Service calls

```yaml
service: vacuum.send_command
target:
  entity_id: vacuum.YOUR_ROBOT_NAME
data:
  command: relocate

service: vacuum.send_command
target:
  entity_id: vacuum.YOUR_ROBOT_NAME
data:
  command: spot_area
  params:
    rooms: 10,14
    cleanings: 1


service: vacuum.send_command
target:
  entity_id: vacuum.YOUR_ROBOT_NAME
data:
  command: custom_area
  params:
    coordinates: -1339,-1511,296,-2587
```

### Other info

Full documentation: https://deebot.readthedocs.io/integrations/home-assistant/
