### ISSUE TITLE
humbertogontijo Roborock integration 

### ISSUE THREAD

**Issue by Matte8519** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#556]
### Integration repository

https://github.com/humbertogontijo/homeassistant-roborock

### Supported features

- [X] Zone cleaning (using 4 coordinates)
- [X] Room cleaning (using room id/number)
- [X] Going to point (using 2 coordinates)
- [X] Cleaning a point (using 2 coordinates)
- [ ] Others

### Vacuum entity/entities

```yaml
vacuum.dust_eater

docked	

fan_speed_list: off, silent, balanced, turbo, max, max_plus, custom
mop_mode_list: standard, deep, deep_plus, custom
mop_intensity_list: off, mild, moderate, intense, custom
msg_ver: 2
msg_seq: 1979
state: docked
battery: 88
clean_time: 4289
clean_area: 62195000
error_code: 0
map_present: 1
in_cleaning: 0
in_returning: 0
in_fresh_state: 1
lab_status: 3
water_box_status: 1
back_type: -1
wash_phase: 0
wash_ready: 0
fan_power: 102
dnd_enabled: 0
map_status: 3
is_locating: 0
lock_status: 0
water_box_mode: 202
water_box_carriage_status: 1
mop_forbidden_enable: 1
camera_status: 3495
is_exploring: 0
home_sec_status: 0
home_sec_enable_password: 1
adbumper_status: 0, 0, 0
water_shortage_status: 0
dock_type: 1
dust_collection_status: 0
auto_dust_collection: 1
avoid_count: 200
mop_mode: standard
debug_mode: 0
collision_avoid_status: 1
switch_map_mode: 0
dock_error_status: 0
charge_status: 1
unsave_map_reason: 0
unsave_map_flag: 0
battery_level: 88
battery_icon: mdi:battery-charging-80
fan_speed: balanced
vacuum_status: charging
mop_intensity: moderate
error: None
icon: cil:roborock-vacuum
friendly_name: Dust eater
supported_features: 16383
```

### Service calls

```yaml
service: roborock.vacuum_clean_segment
data:
  segments: 2
target:
  entity_id: vacuum.dust_eater

service: roborock.vacuum_clean_zone
data:
  zone: 1
  repeats: 1
target:
  entity_id: vacuum.dust_eater


service: roborock.vacuum_goto
data:
  x_coord: "1234"
  y_coord: "4321"
target:
  entity_id: vacuum.dust_eater

service: roborock.vacuum_remote_control_move
data:
  duration: 1
  rotation: 10
  velocity: 0.01
target:
  entity_id: vacuum.dust_eater

service: roborock.vacuum_remote_control_start
data: {}
target:
  entity_id: vacuum.dust_eater

service: roborock.vacuum_remote_control_stop
data: {}
target:
  entity_id: vacuum.dust_eater

service: roborock.vacuum_reset_consumables
data: {}
target:
  entity_id: vacuum.dust_eater

service: roborock.vacuum_set_fan_speed
data:
  fan_speed: balanced
target:
  entity_id: vacuum.dust_eater

service: roborock.vacuum_set_mop_intensity
data:
  mop_intensity: moderate
target:
  entity_id: vacuum.dust_eater

service: roborock.vacuum_set_mop_mode
data:
  mop_mode: deep
target:
  entity_id: vacuum.dust_eater
```
