### ISSUE TITLE
xiaomi_miio Service not found

### ISSUE THREAD

**Issue by Phil1988** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#559]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Hello,

I can not get my Roborock S7 and Dreame D9 to work with that lovely nice card (great work by the way!).

First off, I am using HomeAssistant OS.

I installed ["Xiaomi Miot Auto"](https://github.com/al-one/hass-xiaomi-miot) from HACS and included my devices via the Mi Account. I have seen that this was initially done for HASS, but no idea if thats a problem.
After that I installed the ["Xiaomi Cloud Map Extractor"](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor) v2.2.0

Then I installed this ["Xiaomi Vacuum Map Card"](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card) and created a card.

I always get the errors, that the "xiaomi_miio service was not found.
Zone cleaning:
"xiaomi_miio/vacuum_clean_zone. Service not found"
Room cleaning:
"xiaomi_miio/vacuum_clean_segment. Service not found"
Pin& Go:
"xiaomi_miio/vacuum_goto. Service not found"
Path:
"xiaomi_miio/vacuum_follow_path. Service not found"

I have seen multiple tutorials and have done everything twice, but the issue persists.

I hope you can hint me to the right direction if this is not a bug in that project.

### What version of a card has described problem?

v2.1.2

### What vacuum model do you have problems with?

vacuum.roborock_a15_501b_robot_cleaner

### Which integration do you use to control your vacuum (link)?

https://github.com/al-one/hass-xiaomi-miot

### What browser (browsers/apps) does have this problem?

Chrome/Edge/FireFox/Brave/Opera

### What version of Home Assistant do you use?

Home Assistant 2023.3.5

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
language: de
title: Roborock S7
map_source:
  camera: camera.roborocks7_map
calibration_source:
  camera: true
entity: vacuum.roborock_a15_501b_robot_cleaner
vacuum_platform: default
two_finger_pan: true
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_zone_predefined
    predefined_selections:
      - zones:
          - - 25765
            - 21669
            - 27180
            - 23432
        label:
          text: Bad
          x: 26444
          'y': 23240
          offset_y: 35
        icon:
          name: mdi:shower
          x: 26444
          'y': 23040
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 1
        outline:
          - - 25752
            - 23428
          - - 25752
            - 22573
          - - 25347
            - 22573
          - - 25347
            - 22393
          - - 25797
            - 22393
          - - 26156
            - 21989
          - - 26201
            - 21674
          - - 27191
            - 21674
          - - 27191
            - 23428
          - - 25752
            - 23428
        label:
          text: Bad
          x: 26444
          'y': 23040
          offset_y: 35
        icon:
          name: mdi:shower
          x: 26444
          'y': 23040
  - template: vacuum_goto
  - template: vacuum_goto_predefined
    predefined_selections:
      - position:
          - 25842
          - 26665
        label:
          text: Leeren
          x: 25842
          'y': 26665
          offset_y: 35
        icon:
          name: mdi:broom
          x: 25842
          'y': 26665
  - template: vacuum_follow_path
```

### Additional information

My configuration.yaml looks like this:

```
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret roborockS7_ip_adress
    token: !secret roborockS7_token
    username: !secret xiaomi_account_username
    password: !secret xiaomi_account_password
    name: roborockS7_map
    country: de
    draw: ['all']
    attributes:
      - calibration_points
```
