### ISSUE TITLE
Invalid calibration, please check your configuration after HA v2023.3.6

### ISSUE THREAD

**Issue by FancyNerd92** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#562]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Invalid calibration, please check your configuration
![Screenshot 2023-03-24 220804](https://user-images.githubusercontent.com/76796004/227628664-56f451ae-8736-46e1-9f00-9eb44e21d054.png)

### What version of a card has described problem?

v.2.2.0

### What was the last working version card?

v.2.2.0

### What vacuum model do you have problems with?

vacuum.roborock_a15

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

none

### What version of Home Assistant do you use?

v2023.3.6

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
#Xiaomi Cloud Map Extractor
camera:
  - platform: xiaomi_cloud_map_extractor
    host: *************
    token: *************
    username:  *************
    password: *************
    country: de
    scan_interval: 120
    draw: ['all']
    attributes:
      - calibration_points
```
