### ISSUE TITLE
Please add Roborock integration for HomeAsssistant

### ISSUE THREAD

**Issue by jwnnd93** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#567]
### Integration repository

https://github.com/humbertogontijo/homeassistant-roborock

### Supported features

- [x] Zone cleaning (using 4 coordinates)
- [ ] Room cleaning (using room id/number)
- [X] Going to point (using 2 coordinates)
- [X] Cleaning a point (using 2 coordinates)
- [ ] Others

### Vacuum entity/entities

```yaml
fan_speed_list:
  - 'off'
  - silent
  - balanced
  - turbo
  - max
  - max_plus
  - custom
mop_mode_list:
  - standard
  - deep
  - deep_plus
  - custom
mop_intensity_list:
  - 'off'
  - mild
  - moderate
  - intense
  - custom
battery_level: 100
battery_icon: mdi:battery-charging-100
fan_speed: balanced
msg_ver: 2
msg_seq: 511
state: docked
battery: 100
clean_time: 13
clean_area: 140000
error_code: 0
map_present: 1
in_cleaning: 0
in_returning: 0
in_fresh_state: 1
lab_status: 1
water_box_status: 1
fan_power: 102
dnd_enabled: 0
map_status: 3
is_locating: 0
lock_status: 0
water_box_mode: 202
water_box_carriage_status: 1
mop_forbidden_enable: 1
camera_status: 385
is_exploring: 0
adbumper_status:
  - 0
  - 0
  - 0
water_shortage_status: 0
dock_type: 0
dust_collection_status: 0
auto_dust_collection: 1
avoid_count: 1
mop_mode: standard
debug_mode: 0
collision_avoid_status: 1
switch_map_mode: 0
dock_error_status: 0
charge_status: 1
unsave_map_reason: 4
unsave_map_flag: 0
clean_percent: 1
rss: 2
dss: 0
status: charging
mop_intensity: moderate
error: Keine
icon: mdi:robot-vacuum
friendly_name: Herbert
supported_features: 16383
```

### Service calls

```yaml
roborock.vacuum_clean_zone
roborock.camera_load_multi_map
roborock.vacuum_clean_segment
roborock.vacuum_goto
roborock.vacuum_remote_control_move
roborock.vacuum_remote_control_move_step
roborock.vacuum_remote_control_start
roborock.vacuum_remote_control_stop
roborock.vacuum_reset_consumables
roborock.vacuum_set_fan_speed
roborock.vacuum_set_mop_intensity
roborock.vacuum_set_mop_mode
```
