### ISSUE TITLE
Log Error: Failed to execute 'define' on 'CustomElementRegistry': the name "xiaomi-vacuum-map-card-editor" has already been used with this registry

### ISSUE THREAD

**Issue by ziptbm** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#572]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

I'm seeing this error regularly in my logs coming from this card, but I'm not quite sure how to fix it.  I've attempted already to uninstall and reinstall it (with reboots between), but it continues to persist regular.   Any known workarounds or did I fail to do something right?

```
Logger: frontend.js.latest.202304111
Source: components/system_log/__init__.py:257
First occurred: 20:51:45 (1 occurrences)
Last logged: 20:51:45

http://10.0.0.161:8123/frontend_latest/app-BWfprBTJFp0.js:2:215408 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "xiaomi-vacuum-map-card-editor" has already been used with this registry
```

### What version of a card has described problem?

2.1.2

### What vacuum model do you have problems with?

roborock.s4max

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

All

### What version of Home Assistant do you use?

2023.4.4

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
preset_name: Main Floor
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.buzz
vacuum_platform: default
two_finger_pan: true
append_icons: true
icons:
  - icon: mdi:home-floor-1
    tooltip: Main Floor
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.buzz
        command: load_multi_map
        params: 0
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_zone_predefined
    predefined_selections:
      - zones:
          - - 25500
            - 25500
            - 26500
            - 26500
  - template: vacuum_goto
additional_presets:
  - preset_name: 2nd Floor
    entity: vacuum.buzz
    map_source:
      camera: camera.xiaomi_cloud_map_extractor
    calibration_source:
      camera: true
    append_icons: true
    icons:
      - icon: mdi:home-floor-2
        tooltip: 2nd Floor
        tap_action:
          action: call-service
          service: vacuum.send_command
          service_data:
            entity_id: vacuum.buzz
            command: load_multi_map
            params: 1
    map_modes:
      - template: vacuum_clean_zone
      - template: vacuum_clean_zone_predefined
        predefined_selections:
          - zones:
              - - 27500
                - 27500
                - 28500
                - 28500
      - template: vacuum_goto
```
