### ISSUE TITLE
Unable to setup zone cleanup and perform pin&go directly in the card

### ISSUE THREAD

**Issue by pawko2000** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#575]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Hi,
I've flashed my roborock v.1 with valetudo re, tried to configure with xiaomi vacuum map card. I'm able to see the map, sensors and basic buttons but unable to create zones for cleanup and perform go to action.

Previously I was using the card with xiaomi map integration with no issues. I have followed the instructions with no luck.
While clicking + to add new zone i'm getting no reaction on the map, in edit mode I can see that it gets "null,null..." coordinations. It's the same story with go to action.
 
![image](https://user-images.githubusercontent.com/73130544/233346489-bd1e3ff9-0ef2-47fd-bdff-a623e8de2863.png)

### What version of a card has described problem?

v.2.0.0

### What vacuum model do you have problems with?

roborock.v1

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Chrome

### What version of Home Assistant do you use?

2023.4.4

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.rockrobofinal_map
calibration_source:
  entity: sensor.rockrobo_calibration
entity: vacuum.rockrobofinal
vacuum_platform: rand256/ValetudoRE
internal_variables:
  topic: valetudore/rockrobofinal
map_locked: true
```

### Additional information

config.yalm:

mqtt:
  sensor:
    - state_topic: valetudore/rockrobofinal/map_calibration_points
      name: rockrobo_calibration
