### ISSUE TITLE
Predefined room selections limit to 8

### ISSUE THREAD

**Issue by Saxophtrion** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#578]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Hi,

I used the xiaomi vacuum card integration on my home assistant for months now. It is flawless except one little thing 👍 
In the configs, I set the param max_selections to 9 to test but when i select 9 zones, the vaccum stops after 8 zones.

It seems to clean zone in order but i don't understand why it stops after 8. I tried to activate debug mode to check coordinates and everything seems to be ok. But after all my attemps, i can only clean 8 zones max with the predefined selection.

Does someone else encountered this issue ?

Thx in advance

### What version of a card has described problem?

v2.1.2

### What vacuum model do you have problems with?

vacuum.roborock_s5_max

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio

### What browser (browsers/apps) does have this problem?

Chrome

### What version of Home Assistant do you use?

2023.4.6

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
cards:
      - type: custom:xiaomi-vacuum-map-card
        map_source:
          camera: camera.aspirateur
          crop:
            top: 230
            bottom: 210
            right: 100
            left: 100
        calibration_source:
          camera: true
        entity: vacuum.roborock_s5_max
        vacuum_platform: default
        map_locked: true
        map_modes:
          - template: vacuum_clean_zone
          - template: vacuum_goto
          - template: vacuum_clean_zone_predefined
            max_selections: 9
            predefined_selections:
              - zones:
                  - - 20050
                    - 25996
                    - 22184
                    - 28079
                label:
                  text: Salle de bain
                  x: 21150
                  'y': 26700
              - zones:
                  - - 23388
                    - 25107
                    - 27712
                    - 28134
                label:
                  text: Chambre
                  x: 26150
                  'y': 26200
              - zones:
                  - - 22176
                    - 27129
                    - 23279
                    - 31747
                label:
                  text: Couloir
                  x: 22700
                  'y': 30000
              - zones:
                  - - 20515
                    - 28280
                    - 22129
                    - 29584
                label:
                  text: Toilettes
                  x: 21150
                  'y': 28900
              - zones:
                  - - 20023
                    - 29785
                    - 22076
                    - 31691
                label:
                  text: Entrée
                  x: 21150
                  'y': 30500
              - zones:
                  - - 20877
                    - 31772
                    - 23261
                    - 35345
                label:
                  text: Cuisine
                  x: 22150
                  'y': 33500
              - zones:
                  - - 23292
                    - 31188
                    - 27494
                    - 35325
                label:
                  text: Salon
                  x: 25150
                  'y': 34500
              - zones:
                  - - 23292
                    - 28306
                    - 27525
                    - 31164
                label:
                  text: Bureau
                  x: 25150
                  'y': 29500
          - template: vacuum_follow_path
```
