### ISSUE TITLE
Cannot expand menu to pick rooms mode - Home Assistant app

### ISSUE THREAD

**Issue by znanywawa** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#582]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

At newest Home Assistant Supervised and Home Assistant Android App (beta-9972-8b32f9bf-full) You cannot expand menu to pick rooms, only creation of ZONES is allowed. Issue is applicable to Mobile App as well as web browser (tested at Android Chrome web browser) while using mobile version of instance, but when I switch Android Chrome app to Desktop mode - it works with no issues through web browser.

### What version of a card has described problem?

v2.2.0-beta.1

### What vacuum model do you have problems with?

roborock.vacuum.a15

### Which integration do you use to control your vacuum (link)?

https://github.com/humbertogontijo/homeassistant-roborock

### What browser (browsers/apps) does have this problem?

Android HA App, Android Chrome (in mobile mode)

### What version of Home Assistant do you use?

2023.5.2

### What type of installation are you running?

Home Assistant Supervised

### Card's configuration

```yaml
type: vertical-stack
cards:
  - type: custom:xiaomi-vacuum-map-card
    entity: vacuum.roborock_s7
    map_source:
      camera: camera.roborock_s7_map
    calibration_source:
      camera: true
    map_modes:
      - template: vacuum_clean_zone
      - template: vacuum_goto
      - template: vacuum_clean_segment
        predefined_selections:
          - icon:
              name: mdi:television
              x: 27400
              'y': 26350
            id: 17
          - icon:
              name: mdi:human-child
              x: 30600
              'y': 25975
            id: 18
          - icon:
              name: mdi:shower-head
              x: 25125
              'y': 30300
            id: 19
          - icon:
              name: mdi:bed
              x: 26100
              'y': 34500
            id: 20
          - icon:
              name: mdi:broom
              x: 27400
              'y': 31175
            id: 16
          - icon:
              name: mdi:bathtub
              x: 25475
              'y': 32325
            id: 21
    vacuum_platform: humbertogontijo/homeassistant-roborock
```
