### ISSUE TITLE
Selection shows no coordinates

### ISSUE THREAD

**Issue by stibe881** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#589]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Selection doesn't show coordinates when I do a Zone Cleanup.
I tried it with the existing card and since it didn't work there, I created a new card.

I have now updated the map to the latest beta version. I have the same problem with this card too.

![Screenshot 2023-05-16 111844](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/24219649/2d53aa77-7bd8-4465-88c8-4e792afb3257)

### What version of a card has described problem?

v2.1.2

### What vacuum model do you have problems with?

roborock.vacuum.s5e

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/roborock/

### What browser (browsers/apps) does have this problem?

Chrome/Edge/iOS

### What version of Home Assistant do you use?

2023.5.3

### What type of installation are you running?

Home Assistant Supervised

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
language: de
map_source:
  camera: camera.olga_map
calibration_source:
  camera: true
entity: vacuum.olga
vacuum_platform: send_command
tiles:
  - tile_id: battery_level
    entity: vacuum.olga
    label: Battery
    attribute: battery_level
    icon: mdi:battery-charging-100
    unit: '%'
icons:
  - icon: mdi:play
    conditions:
      - entity: vacuum.olga
        value_not: cleaning
      - entity: vacuum.olga
        value_not: error
      - entity: vacuum.olga
        value_not: returning
    tooltip: Start
    tap_action:
      action: call-service
      service: vacuum.start
      service_data:
        entity_id: vacuum.olga
  - icon: mdi:stop
    conditions:
      - entity: vacuum.olga
        value_not: docked
      - entity: vacuum.olga
        value_not: idle
      - entity: vacuum.olga
        value_not: error
      - entity: vacuum.olga
        value_not: paused
    tooltip: Stop
    tap_action:
      action: call-service
      service: vacuum.stop
      service_data:
        entity_id: vacuum.olga
  - icon: mdi:home-map-marker
    conditions:
      - entity: vacuum.olga
        value_not: docked
      - entity: vacuum.olga
        value_not: returning
    tooltip: Return to base
    tap_action:
      action: call-service
      service: vacuum.return_to_base
      service_data:
        entity_id: vacuum.olga
map_modes:
  - template: vacuum_goto_predefined
    predefined_selections:
      - position:
          - 32969
          - 26797
        label:
          text: Küche
          x: 32969
          'y': 26797
          offset_y: 35
        icon:
          name: mdi:fridge
          x: 32969
          'y': 26797
      - position:
          - 27543
          - 20112
        label:
          text: Badezimmer
          x: 27543
          'y': 20112
          offset_y: 35
        icon:
          name: mdi:faucet
          x: 27543
          'y': 20112
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 21
        label:
          text: Schlafzimmer
          x: 29700
          'y': 16000
          offset_y: 35
        icon:
          name: mdi:bed
          x: 29700
          'y': 16000
      - id: 22
        label:
          text: Kinderzimmer
          x: 26150
          'y': 16025
          offset_y: 35
        icon:
          name: mdi:teddy-bear
          x: 26150
          'y': 16025
      - id: 19
        label:
          text: Wohnzimmer
          x: 32600
          'y': 19700
          offset_y: 35
        icon:
          name: mdi:sofa-outline
          x: 32600
          'y': 19700
      - id: 20
        label:
          text: Gang
          x: 30200
          'y': 21925
          offset_y: 35
        icon:
          name: mdi:hanger
          x: 30200
          'y': 21925
      - id: 23
        label:
          text: Badezimmer
          x: 27125
          'y': 19350
          offset_y: 35
        icon:
          name: mdi:bathtub-outline
          x: 27125
          'y': 19350
      - id: 17
        label:
          text: Küche
          x: 34075
          'y': 25700
          offset_y: 35
        icon:
          name: mdi:fridge-outline
          x: 34075
          'y': 25700
      - id: 16
        label:
          text: Büro
          x: 27050
          'y': 28000
          offset_y: 35
        icon:
          name: mdi:laptop
          x: 27050
          'y': 28000
      - id: 18
        label:
          text: Kleiderzimmer
          x: 29850
          'y': 27000
          offset_y: 35
        icon:
          name: mdi:tshirt-crew-outline
          x: 29850
          'y': 27000
  - template: vacuum_clean_zone_predefined
    predefined_selections:
      - zones:
          - - 31151
            - 16393
            - 32406
            - 19140
        label:
          text: Mäuse
          x: 31843
          'y': 18042
          offset_y: 35
        icon:
          name: mdi:rodent
          x: 31843
          'y': 18042
      - zones:
          - - 29488
            - 19413
            - 31219
            - 21655
        label:
          text: Eingang
          x: 29971
          'y': 20494
          offset_y: 35
        icon:
          name: mdi:door
          x: 29971
          'y': 20494
      - zones:
          - - 32327
            - 20451
            - 33610
            - 22141
        label:
          text: Tisch
          x: 32974
          'y': 21281
          offset_y: 35
        icon:
          name: mdi:table-furniture
          x: 32974
          'y': 21281
      - zones:
          - - 32993
            - 20163
            - 35086
            - 23443
        label:
          text: Sofa
          x: 34152
          'y': 22487
          offset_y: 35
        icon:
          name: mdi:sofa
          x: 34152
          'y': 22487
      - zones:
          - - 34115
            - 25353
            - 35675
            - 27623
        label:
          text: Tisch
          x: 34938
          'y': 26611
          offset_y: 35
        icon:
          name: mdi:table
          x: 34938
          'y': 26611
  - name: Zone cleanup
    icon: mdi:select-drag
    run_immediately: false
    coordinates_rounding: true
    selection_type: MANUAL_RECTANGLE
    max_selections: 5
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: roborock.vacuum_clean_zone
      service_data:
        zone: '[[selection]]'
        repeats: '[[repeats]]'
        entity_id: '[[entity_id]]'
    predefined_selections: []
    variables: {}
  - name: Pin & Go
    icon: mdi:map-marker-plus
    run_immediately: false
    coordinates_rounding: true
    selection_type: MANUAL_POINT
    max_selections: 999
    repeats_type: NONE
    max_repeats: 1
    service_call_schema:
      service: roborock.vacuum_goto
      service_data:
        x_coord: '[[point_x]]'
        y_coord: '[[point_y]]'
        entity_id: '[[entity_id]]'
    predefined_selections: []
    variables: {}
  - name: Path
    icon: mdi:map-marker-path
    run_immediately: false
    coordinates_rounding: true
    selection_type: MANUAL_PATH
    max_selections: 999
    repeats_type: NONE
    max_repeats: 1
    service_call_schema:
      service: script.vacuum_follow_path
      service_data:
        service: vacuum.send_command
        mode: send_command
        path: '[[selection]]'
        entity_id: '[[entity_id]]'
    predefined_selections: []
    variables: {}
map_locked: true
title: Olga
```
