### ISSUE TITLE
Integration humbertogontijo / homeassistant-roborock clean_segment repeats not working

### ISSUE THREAD

**Issue by Trilis29** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#604]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Seems template for [humbertogontijo/homeassistant-roborock](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/blob/master/docs/templates/humbertogontijoHomeassistantRoborock.md) integration Room cleaning (vacuum_clean_segment) does not add repeats to service call. Attaching picture. 
service call: 
{
  "domain": "roborock",
  "service": "vacuum_clean_segment",
  "serviceData": {
    "segments": [
      27,
      27,
      27
    ],
    "entity_id": "vacuum.roborock_s5_max_2"
  }
}

![image](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/51697921/8df61b4e-6662-4e05-9f8a-4a490d239322)

### What version of a card has described problem?

v2.2.0

### What vacuum model do you have problems with?

roborock_s5_max

### Which integration do you use to control your vacuum (link)?

https://github.com/humbertogontijo/homeassistant-roborock

### What browser (browsers/apps) does have this problem?

All

### What version of Home Assistant do you use?

Home Assistant 2023.5.4

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.roborock_s5_max_map
calibration_source:
  camera: true
entity: vacuum.roborock_s5_max_2
vacuum_platform: humbertogontijo/homeassistant-roborock
two_finger_pan: true
map_locked: false
debug: false
map_modes:
  - template: vacuum_goto
  - template: vacuum_goto_predefined
  - template: vacuum_clean_zone
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 16
        label:
          text: Living room
          x: 21600
          'y': 24550
          offset_y: 35
        icon:
          name: mdi:broom
          x: 21600
          'y': 24550
      - id: 21
        label:
          text: Room 21
          x: 27500
          'y': 22875
          offset_y: 35
        icon:
          name: mdi:broom
          x: 27500
          'y': 22875
      - id: 27
        label:
          text: Kitchen
          x: 19500
          'y': 22925
          offset_y: 35
        icon:
          name: mdi:broom
          x: 19500
          'y': 22925
      - id: 29
        label:
          text: Room 29
          x: 26800
          'y': 26675
          offset_y: 35
        icon:
          name: mdi:broom
          x: 26800
          'y': 26675
      - id: 17
        label:
          text: Room 17
          x: 13950
          'y': 28450
          offset_y: 35
        icon:
          name: mdi:broom
          x: 13950
          'y': 28450
      - id: 26
        label:
          text: Room 26
          x: 22550
          'y': 31900
          offset_y: 35
        icon:
          name: mdi:broom
          x: 22550
          'y': 31900
      - id: 19
        label:
          text: Room 19
          x: 25550
          'y': 29650
          offset_y: 35
        icon:
          name: mdi:broom
          x: 25550
          'y': 29650
      - id: 20
        label:
          text: Room 20
          x: 19250
          'y': 29325
          offset_y: 35
        icon:
          name: mdi:broom
          x: 19250
          'y': 29325
      - id: 22
        label:
          text: Room 22
          x: 17050
          'y': 32725
          offset_y: 35
        icon:
          name: mdi:broom
          x: 17050
          'y': 32725
      - id: 18
        label:
          text: Room 18
          x: 14375
          'y': 33350
          offset_y: 35
        icon:
          name: mdi:broom
          x: 14375
          'y': 33350
      - id: 23
        label:
          text: Room 23
          x: 12175
          'y': 33650
          offset_y: 35
        icon:
          name: mdi:broom
          x: 12175
          'y': 33650
```
