### ISSUE TITLE
Cannot select homeassistant-roborock as vacuum platform

### ISSUE THREAD

**Issue by bigbangus** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#606]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

I recently migrated to using the Roborock iOS map and the humbertogontijo/homeassistant-roborock custom component to add my vacuum and create the map.

However, I noticed that features of my map card didn't work anymore. So I tried to select the new platform in the card editor in homeassistant but the choice was not there.
![image](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/91270101/bb03a0ce-02c4-4427-89e9-3b1eca6cdc62)

Then if I manually add it to the bottom of the vacuum card code, it goes blank.

What's going on? Is my card configuration not compatible with humbertogontijo/homeassistant-roborock?

### What version of a card has described problem?

v2.1.2

### What vacuum model do you have problems with?

roborock.vacuum.a15 (s7)

### Which integration do you use to control your vacuum (link)?

https://github.com/humbertogontijo/homeassistant-roborock

### What browser (browsers/apps) does have this problem?

Chrome

### What version of Home Assistant do you use?

2023.5.4

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
preset_name: Downstairs
title: Vacuum Map Card
entity: vacuum.roborock_s7
activate_on_switch: true
activate:
  service: vacuum.send_command
  service_data:
    entity_id: vacuum.roborock_s7
    command: load_multi_map
    params: 0
map_source:
  camera: camera.roborock_s7_map
calibration_source:
  camera: true
append_icons: true
icons:
  - icon: mdi:sync
    tooltip: Downstairs
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.roborock_s7
        command: load_multi_map
        params: 0
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 16
        label:
          text: Bedroom
          x: 35050
          'y': 14125
          offset_y: 35
        icon:
          name: mdi:bed
          x: 35050
          'y': 14125
      - id: 27
        label:
          text: Living Room
          x: 30425
          'y': 15700
          offset_y: 35
        icon:
          name: mdi:television
          x: 30425
          'y': 15700
      - id: 25
        label:
          text: Dining
          x: 26575
          'y': 14675
          offset_y: 35
        icon:
          name: mdi:table-picnic
          x: 26575
          'y': 14675
      - id: 21
        label:
          text: Kitchen
          x: 27275
          'y': 19500
          offset_y: 35
        icon:
          name: mdi:chef-hat
          x: 27275
          'y': 19500
      - id: 17
        label:
          text: Master Bath
          x: 35925
          'y': 18900
          offset_y: 35
        icon:
          name: mdi:shower
          x: 35925
          'y': 18900
      - id: 24
        icon:
          name: mdi:broom
          x: 30025
          'y': 21375
      - id: 18
        label:
          text: Master Closet
          x: 32750
          'y': 20425
          offset_y: 35
        icon:
          name: mdi:hanger
          x: 32750
          'y': 20425
      - id: 22
        icon:
          name: mdi:washing-machine
          x: 25800
          'y': 22875
      - id: 19
        icon:
          name: mdi:broom
          x: 27875
          'y': 22125
      - id: 23
        icon:
          name: mdi:toilet
          x: 27900
          'y': 23700
      - id: 20
        label:
          text: Music Room
          x: 27775
          'y': 27250
          offset_y: 35
        icon:
          name: mdi:music-clef-treble
          x: 27775
          'y': 27250
  - template: vacuum_goto
  - template: vacuum_follow_path
additional_presets:
  - preset_name: Upstairs
    entity: vacuum.roborock_s7
    activate_on_switch: true
    activate:
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.roborock_s7
        command: load_multi_map
        params: 1
    map_source:
      camera: camera.roborock_s7_map
    calibration_source:
      camera: true
    append_icons: true
    icons:
      - icon: mdi:sync
        tooltip: Upstairs
        tap_action:
          action: call-service
          service: vacuum.send_command
          service_data:
            entity_id: vacuum.roborock_s7
            command: load_multi_map
            params: 1
    map_modes:
      - template: vacuum_clean_zone
      - template: vacuum_clean_segment
        predefined_selections:
          - id: 16
            label:
              text: Office
              x: 24000
              'y': 23675
              offset_y: 35
            icon:
              name: mdi:monitor
              x: 24000
              'y': 23675
          - id: 17
            label:
              text: Kodi
              x: 31775
              'y': 23550
              offset_y: 35
            icon:
              name: mdi:broom
              x: 31775
              'y': 23550
          - id: 18
            label:
              text: Bathroom
              x: 27600
              'y': 23625
              offset_y: 35
            icon:
              name: mdi:toilet
              x: 27600
              'y': 23625
          - id: 19
            label:
              text: Loft
              x: 24225
              'y': 27350
              offset_y: 35
            icon:
              name: mdi:broom
              x: 24225
              'y': 27350
          - id: 20
            label:
              text: Georgie
              x: 31825
              'y': 27250
              offset_y: 35
            icon:
              name: mdi:broom
              x: 31825
              'y': 27250
          - id: 21
            label:
              text: Closet
              x: 27625
              'y': 27200
              offset_y: 35
            icon:
              name: mdi:broom
              x: 27625
              'y': 27200
      - template: vacuum_goto
      - template: vacuum_follow_path
vacuum_platform: humbertogontijo/homeassistant-roborock
```

### Javascript errors shown in the browser's console (if applicable)

```shell
Invalid vacuum platform: humbertogontijo/homeassistant-roborock
```
