### ISSUE TITLE
Different map sources for each map modes

### ISSUE THREAD

**Issue by DeDelner** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#621]
### Description

For instance, my wife didn't like the the map that is generated by the robot. So I created a neat 3D floorplan of our home and used this as a map source for room cleaning. 

Now the floorplan becomes inaccurate when you want to use zone cleanup or pin & go. 

### Solution

The idea would be to provide `map_source` and `calibration_source` per `mod_mode` as optional parameters, which can overwrite the "default" ones.

Something like this:
```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.sweepie
map_source:
  camera: camera.sweepie
calibration_source:
  camera: true
...
map_modes:
  - template: vacuum_clean_segment
    # Overwriting the parameters from above
    map_source:
      image: /local/floorplan.png
    calibration_source:
      calibration_points:
         ...
    predefined_selections:
       ...

```
