### ISSUE TITLE
"Could not reach a specified room"

### ISSUE THREAD

**Issue by krzych-s** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#626]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

I was searching but found nothing, and I do not know where the issue might be, so I am reporting here as most probable - after setting up a room map, I have 6 rooms, which of 5 works perfectly. Just the kitchen is "buggy" and always when I choose kitchen, my Roborock S5 says "Could not reach a specified room" and goes back to the dock. Even with multiple rooms, it cleans all but the kitchen. And when I use Xiaomi Home, it works flawlessly with the kithen also. Fun fact - when I define a zone identical to the Kitchen (with graphical editor, so may be not precise to the point), vacuum goes there and cleans it flawlessly. I even tried to shrint the kitchen to be smaller than the tested zone, still nothing. Is there any way to define a "start point" for a room?

### What version of a card has described problem?

v2.2.2

### What vacuum model do you have problems with?

roborock.vacuum.s5

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

firefox

### What version of Home Assistant do you use?

container-20230503.3

### What type of installation are you running?

Home Assistant Container

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.rrs5
vacuum_platform: default
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_locked: true
attributes:
  - calibration_points
  - rooms
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_clean_segment
    predefined_selections:
      - id: '15'
        icon:
          name: mdi:glass-cocktail
          x: 33625
          'y': 26650
        label:
          text: Kitchen
          x: 33625
          'y': 26650
          offset_y: 35
        outline:
          - - 31800
            - 25600
          - - 35450
            - 25600
          - - 35450
            - 27500
          - - 31800
            - 27500
      - id: '16'
        icon:
          name: mdi:television
          x: 32200
          'y': 22875
        label:
          text: Saloon
          x: 32200
          'y': 22875
          offset_y: 35
        outline:
          - - 30100
            - 20250
          - - 34300
            - 20250
          - - 34300
            - 25500
          - - 30100
            - 25500
      - id: '17'
        icon:
          name: mdi:bed
          x: 28650
          'y': 22325
        label:
          text: Bedroom
          x: 28650
          'y': 22325
          offset_y: 35
        outline:
          - - 27250
            - 20600
          - - 30050
            - 20600
          - - 30050
            - 24050
          - - 27250
            - 24050
      - id: '18'
        icon:
          name: mdi:shower
          x: 26575
          'y': 25925
        label:
          text: Bathroom
          x: 26575
          'y': 25925
          offset_y: 35
        outline:
          - - 25250
            - 25150
          - - 27900
            - 25150
          - - 27900
            - 26700
          - - 25250
            - 26700
      - id: '19'
        icon:
          name: mdi:tshirt-v
          x: 29975
          'y': 26550
        label:
          text: Lobby
          x: 29975
          'y': 26550
          offset_y: 35
        outline:
          - - 27950
            - 25150
          - - 32000
            - 25150
          - - 32000
            - 26650
          - - 27950
            - 26650
      - id: '20'
        icon:
          name: mdi:shoe-formal
          x: 27975
          'y': 27350
        label:
          text: Entrance
          x: 27975
          'y': 27350
          offset_y: 35
        outline:
          - - 26300
            - 26600
          - - 29650
            - 26600
          - - 29650
            - 28100
          - - 26300
            - 28100
```
