### ISSUE TITLE
s5 max does not repeat

### ISSUE THREAD

**Issue by dingausmwald** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#628]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Command is sent, but it only cleans once

### What version of a card has described problem?

2.2.2

### What vacuum model do you have problems with?

s5max

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

chrome

### What version of Home Assistant do you use?

2023.7.2

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.roborock_vacuum_s5e
vacuum_platform: default
map_modes:
  - name: Zone cleanup
    icon: mdi:select-drag
    run_immediately: false
    coordinates_rounding: true
    selection_type: MANUAL_RECTANGLE
    max_selections: 5
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: xiaomi_miio.vacuum_clean_zone
      service_data:
        zone: '[[selection]]'
        repeats: '[[repeats]]'
        entity_id: '[[entity_id]]'
    predefined_selections: []
    variables: {}
  - name: Pin & Go
    icon: mdi:map-marker-plus
    run_immediately: false
    coordinates_rounding: true
    selection_type: MANUAL_POINT
    max_selections: 999
    repeats_type: NONE
    max_repeats: 1
    service_call_schema:
      service: xiaomi_miio.vacuum_goto
      service_data:
        x_coord: '[[point_x]]'
        y_coord: '[[point_y]]'
        entity_id: '[[entity_id]]'
    predefined_selections: []
    variables: {}
  - name: Rooms
    icon: mdi:floor-plan
    run_immediately: false
    coordinates_rounding: true
    selection_type: ROOM
    max_selections: 999
    repeats_type: REPEAT
    max_repeats: 3
    service_call_schema:
      service: xiaomi_miio.vacuum_clean_segment
      service_data:
        segments: '[[selection]]'
        entity_id: '[[entity_id]]'
    predefined_selections:
      - id: '1'
        icon:
          name: mdi:broom
          x: 28025
          'y': 21900
        outline:
          - - 26900
            - 20650
          - - 29150
            - 20650
          - - 29150
            - 23150
          - - 26900
            - 23150
      - id: '16'
        icon:
          name: mdi:broom
          x: 27550
          'y': 26000
        label:
          text: Flur 1
          x: 27550
          'y': 26000
          offset_y: 35
        outline:
          - - 26300
            - 23050
          - - 28800
            - 23050
          - - 28800
            - 28950
          - - 26300
            - 28950
      - id: '17'
        icon:
          name: mdi:broom
          x: 30250
          'y': 27875
        label:
          text: Flur 2
          x: 30250
          'y': 27875
          offset_y: 35
        outline:
          - - 28250
            - 26950
          - - 32250
            - 26950
          - - 32250
            - 28800
          - - 28250
            - 28800
      - id: '18'
        icon:
          name: mdi:broom
          x: 22975
          'y': 22925
        label:
          text: Büro
          x: 22975
          'y': 22925
          offset_y: 35
        outline:
          - - 19750
            - 20800
          - - 26200
            - 20800
          - - 26200
            - 25050
          - - 19750
            - 25050
      - id: '19'
        icon:
          name: mdi:broom
          x: 23975
          'y': 28850
        label:
          text: Wohnzimmer
          x: 23975
          'y': 28850
          offset_y: 35
        outline:
          - - 21250
            - 25050
          - - 26700
            - 25050
          - - 26700
            - 32650
          - - 21250
            - 32650
      - id: '20'
        icon:
          name: mdi:broom
          x: 28400
          'y': 30775
        label:
          text: Küche
          x: 28400
          'y': 30775
          offset_y: 35
        outline:
          - - 26700
            - 28950
          - - 30100
            - 28950
          - - 30100
            - 32600
          - - 26700
            - 32600
      - id: '21'
        icon:
          name: mdi:broom
          x: 30825
          'y': 25100
        label:
          text: Schlafzimmer
          x: 30825
          'y': 25100
          offset_y: 35
        outline:
          - - 28250
            - 23200
          - - 33400
            - 23200
          - - 33400
            - 27000
          - - 28250
            - 27000
      - id: '22'
        icon:
          name: mdi:broom
          x: 32825
          'y': 27850
        label:
          text: Toilette
          x: 32825
          'y': 27850
          offset_y: 35
        outline:
          - - 32250
            - 27000
          - - 33400
            - 27000
          - - 33400
            - 28700
          - - 32250
            - 28700
      - id: '23'
        icon:
          name: mdi:broom
          x: 32150
          'y': 30650
        label:
          text: Badezimmer
          x: 32150
          'y': 30650
          offset_y: 35
        outline:
          - - 30900
            - 28900
          - - 33400
            - 28900
          - - 33400
            - 32400
          - - 30900
            - 32400
    variables: {}
tiles:
  - tile_id: status
    entity: vacuum.roborock_vacuum_s5e
    label: Status
    attribute: status
    icon: mdi:robot-vacuum
    translations:
      starting: Starting
      charger disconnected: Charger disconnected
      idle: Idle
      remote control active: Remote control active
      cleaning: Cleaning
      returning home: Returning home
      manual mode: Manual mode
      charging: Charging
      charging problem: Charging problem
      paused: Paused
      spot cleaning: Spot cleaning
      error: Error
      shutting down: Shutting down
      updating: Updating
      docking: Docking
      going to target: Going to target
      zoned cleaning: Zoned cleaning
      segment cleaning: Segment cleaning
      emptying the bin: Emptying the bin
      charging complete: Charging complete
      device offline: Device offline
  - tile_id: battery_level
    entity: vacuum.roborock_vacuum_s5e
    label: Battery
    attribute: battery_level
    icon: mdi:battery-charging-100
    unit: '%'
  - tile_id: fan_speed
    entity: vacuum.roborock_vacuum_s5e
    label: Fan speed
    attribute: fan_speed
    icon: mdi:fan
    translations:
      silent: Silent
      standard: Standard
      medium: Medium
      turbo: Turbo
      auto: Auto
      gentle: Gentle
  - tile_id: sensor_dirty_left
    label: Sensors left
    unit: h
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: true
      service_data:
        command: reset_consumable
        params: sensor_dirty_time
        entity_id: vacuum.roborock_vacuum_s5e
    entity: sensor.roborock_vacuum_s5e_sensor_dirty_left
    icon: mdi:eye-outline
    precision: 0
    translations: {}
  - tile_id: filter_left
    label: Filter left
    unit: h
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: true
      service_data:
        command: reset_consumable
        params: filter_work_time
        entity_id: vacuum.roborock_vacuum_s5e
    entity: sensor.roborock_vacuum_s5e_filter_left
    icon: mdi:air-filter
    precision: 0
    translations: {}
  - tile_id: main_brush_left
    label: Main brush left
    unit: h
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: true
      service_data:
        command: reset_consumable
        params: main_brush_work_time
        entity_id: vacuum.roborock_vacuum_s5e
    entity: sensor.roborock_vacuum_s5e_main_brush_left
    icon: mdi:brush
    precision: 0
    translations: {}
  - tile_id: side_brush_left
    label: Side brush left
    unit: h
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: true
      service_data:
        command: reset_consumable
        params: side_brush_work_time
        entity_id: vacuum.roborock_vacuum_s5e
    entity: sensor.roborock_vacuum_s5e_side_brush_left
    icon: mdi:brush
    precision: 0
    translations: {}
  - tile_id: cleaning_count
    label: Cleaning count
    entity: sensor.roborock_vacuum_s5e_total_clean_count
    icon: mdi:counter
    precision: 0
    translations: {}
icons:
  - icon: mdi:play
    conditions:
      - entity: vacuum.roborock_vacuum_s5e
        value_not: cleaning
      - entity: vacuum.roborock_vacuum_s5e
        value_not: error
      - entity: vacuum.roborock_vacuum_s5e
        value_not: returning
    tooltip: Start
    tap_action:
      action: call-service
      service: vacuum.start
      service_data:
        entity_id: vacuum.roborock_vacuum_s5e
  - icon: mdi:pause
    conditions:
      - entity: vacuum.roborock_vacuum_s5e
        value_not: docked
      - entity: vacuum.roborock_vacuum_s5e
        value_not: idle
      - entity: vacuum.roborock_vacuum_s5e
        value_not: error
      - entity: vacuum.roborock_vacuum_s5e
        value_not: paused
    tooltip: Pause
    tap_action:
      action: call-service
      service: vacuum.pause
      service_data:
        entity_id: vacuum.roborock_vacuum_s5e
  - icon: mdi:stop
    conditions:
      - entity: vacuum.roborock_vacuum_s5e
        value_not: docked
      - entity: vacuum.roborock_vacuum_s5e
        value_not: idle
      - entity: vacuum.roborock_vacuum_s5e
        value_not: error
      - entity: vacuum.roborock_vacuum_s5e
        value_not: paused
    tooltip: Stop
    tap_action:
      action: call-service
      service: vacuum.stop
      service_data:
        entity_id: vacuum.roborock_vacuum_s5e
  - icon: mdi:home-map-marker
    conditions:
      - entity: vacuum.roborock_vacuum_s5e
        value_not: docked
      - entity: vacuum.roborock_vacuum_s5e
        value_not: returning
    tooltip: Return to base
    tap_action:
      action: call-service
      service: vacuum.return_to_base
      service_data:
        entity_id: vacuum.roborock_vacuum_s5e
  - icon: mdi:target-variant
    conditions:
      - entity: vacuum.roborock_vacuum_s5e
        value_not: docked
      - entity: vacuum.roborock_vacuum_s5e
        value_not: error
      - entity: vacuum.roborock_vacuum_s5e
        value_not: cleaning
      - entity: vacuum.roborock_vacuum_s5e
        value_not: returning
    tooltip: Clean spot
    tap_action:
      action: call-service
      service: vacuum.clean_spot
      service_data:
        entity_id: vacuum.roborock_vacuum_s5e
  - icon: mdi:map-marker
    tooltip: Locate
    tap_action:
      action: call-service
      service: vacuum.locate
      service_data:
        entity_id: vacuum.roborock_vacuum_s5e
  - icon: mdi:fan-remove
    conditions:
      - entity: vacuum.roborock_vacuum_s5e
        attribute: fan_speed
        value: Silent
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_vacuum_s5e
        fan_speed: Standard
  - icon: mdi:fan-speed-1
    conditions:
      - entity: vacuum.roborock_vacuum_s5e
        attribute: fan_speed
        value: Standard
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_vacuum_s5e
        fan_speed: Medium
  - icon: mdi:fan-speed-2
    conditions:
      - entity: vacuum.roborock_vacuum_s5e
        attribute: fan_speed
        value: Medium
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_vacuum_s5e
        fan_speed: Turbo
  - icon: mdi:fan-speed-3
    conditions:
      - entity: vacuum.roborock_vacuum_s5e
        attribute: fan_speed
        value: Turbo
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_vacuum_s5e
        fan_speed: Gentle
  - icon: mdi:waves
    conditions:
      - entity: vacuum.roborock_vacuum_s5e
        attribute: fan_speed
        value: Gentle
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_vacuum_s5e
        fan_speed: Auto
  - icon: mdi:fan-auto
    conditions:
      - entity: vacuum.roborock_vacuum_s5e
        attribute: fan_speed
        value: Auto
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_vacuum_s5e
        fan_speed: Silent
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.roborock_vacuum_s5e
        attribute: fan_speed
        value_not: Silent
      - entity: vacuum.roborock_vacuum_s5e
        attribute: fan_speed
        value_not: Standard
      - entity: vacuum.roborock_vacuum_s5e
        attribute: fan_speed
        value_not: Medium
      - entity: vacuum.roborock_vacuum_s5e
        attribute: fan_speed
        value_not: Turbo
      - entity: vacuum.roborock_vacuum_s5e
        attribute: fan_speed
        value_not: Gentle
      - entity: vacuum.roborock_vacuum_s5e
        attribute: fan_speed
        value_not: Auto
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_vacuum_s5e
        fan_speed: Silent
```

**Comment by PiotrMachowski** [comment]
```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.roborock_vacuum_s5e
vacuum_platform: default
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_clean_segment
    predefined_selections:
      - id: '1'
        icon:
          name: mdi:broom
          x: 28025
          'y': 21900
        outline:
          - - 26900
            - 20650
          - - 29150
            - 20650
          - - 29150
            - 23150
          - - 26900
            - 23150
      - id: '16'
        icon:
          name: mdi:broom
          x: 27550
          'y': 26000
        label:
          text: Flur 1
          x: 27550
          'y': 26000
          offset_y: 35
        outline:
          - - 26300
            - 23050
          - - 28800
            - 23050
          - - 28800
            - 28950
          - - 26300
            - 28950
      - id: '17'
        icon:
          name: mdi:broom
          x: 30250
          'y': 27875
        label:
          text: Flur 2
          x: 30250
          'y': 27875
          offset_y: 35
        outline:
          - - 28250
            - 26950
          - - 32250
            - 26950
          - - 32250
            - 28800
          - - 28250
            - 28800
      - id: '18'
        icon:
          name: mdi:broom
          x: 22975
          'y': 22925
        label:
          text: Büro
          x: 22975
          'y': 22925
          offset_y: 35
        outline:
          - - 19750
            - 20800
          - - 26200
            - 20800
          - - 26200
            - 25050
          - - 19750
            - 25050
      - id: '19'
        icon:
          name: mdi:broom
          x: 23975
          'y': 28850
        label:
          text: Wohnzimmer
          x: 23975
          'y': 28850
          offset_y: 35
        outline:
          - - 21250
            - 25050
          - - 26700
            - 25050
          - - 26700
            - 32650
          - - 21250
            - 32650
      - id: '20'
        icon:
          name: mdi:broom
          x: 28400
          'y': 30775
        label:
          text: Küche
          x: 28400
          'y': 30775
          offset_y: 35
        outline:
          - - 26700
            - 28950
          - - 30100
            - 28950
          - - 30100
            - 32600
          - - 26700
            - 32600
      - id: '21'
        icon:
          name: mdi:broom
          x: 30825
          'y': 25100
        label:
          text: Schlafzimmer
          x: 30825
          'y': 25100
          offset_y: 35
        outline:
          - - 28250
            - 23200
          - - 33400
            - 23200
          - - 33400
            - 27000
          - - 28250
            - 27000
      - id: '22'
        icon:
          name: mdi:broom
          x: 32825
          'y': 27850
        label:
          text: Toilette
          x: 32825
          'y': 27850
          offset_y: 35
        outline:
          - - 32250
            - 27000
          - - 33400
            - 27000
          - - 33400
            - 28700
          - - 32250
            - 28700
      - id: '23'
        icon:
          name: mdi:broom
          x: 32150
          'y': 30650
        label:
          text: Badezimmer
          x: 32150
          'y': 30650
          offset_y: 35
        outline:
          - - 30900
            - 28900
          - - 33400
            - 28900
          - - 33400
            - 32400
          - - 30900
            - 32400
```
