### ISSUE TITLE
Generated room config incorrect

### ISSUE THREAD

**Issue by lunatik98** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#632]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Thanks for adding room config generation! Unfortunatly one of my rooms is not correct and I am not sure how to fix it. It is overlapping my other room. Probably because the room isnt a square?

![image](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/83845172/a5babcfe-5ced-48fa-ae5e-656d02b2e6af)

### What version of a card has described problem?

2.2.2

### What was the last working version card?

2.1.2

### What vacuum model do you have problems with?

Mi Robot Vacuum 1s

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Chrome and App

### What version of Home Assistant do you use?

2023.7.2

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
language: de
map_source:
  camera: camera.xiaomi_cloud_map_extractor
  crop:
    top: 150
    bottom: 150
    left: 150
    right: 170
calibration_source:
  camera: true
entity: vacuum.mi_robot_vacuum_1s
vacuum_platform: default
map_locked: true
two_finger_pan: true
map_modes:
  - template: vacuum_clean_segment
    predefined_selections:
      - id: '1'
        icon:
          name: phu:rooms-front-door
          x: 14850
          'y': 27300
        outline:
          - - 13800
            - 25250
          - - 15900
            - 25250
          - - 15900
            - 28150
          - - 13800
            - 28150
      - id: '16'
        icon:
          name: phu:rooms-hallway
          x: 18573
          'y': 27600
        outline:
          - - 15850
            - 25300
          - - 21400
            - 25300
          - - 21400
            - 28250
          - - 15850
            - 28250
      - id: '17'
        icon:
          name: phu:rooms-kitchen
          x: 15850
          'y': 29775
        outline:
          - - 13750
            - 28300
          - - 17750
            - 28300
          - - 17750
            - 31250
          - - 13750
            - 31250
      - id: '18'
        icon:
          name: phu:rooms-living
          x: 22312
          'y': 29406
        outline:
          - - 17800
            - 25350
          - - 26050
            - 25350
          - - 26050
            - 31450
          - - 17800
            - 31450
```
