### ISSUE TITLE
Request: Room Naming & Logging

### ISSUE THREAD

**Issue by murraykessell** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#64]
Hi, This is a great card and I've been using it for about 6 months now. Thanks.
Just wondering if you could add the ability to name a zone (room) and fire off an entry to the Logbook when it is cleaned. That way we would be able to tell when a room was last vacuumed.

**Comment by PiotrMachowski** [comment]
Hi,
I don't think that it is a feature that should be done using lovelace card. The best way to accomplish it would be in an automation that will listen to `call_service` event. Example one below:
```
automation:
  - alias: vacuum_log
    trigger:
      platform: event
      event_type: call_service
      event_data:
        domain: vacuum
        service: send_command
        service_data:
          command: app_zoned_clean
          entity_id: vacuum.xiaomi_vacuum
    action:
      - choose:
          - conditions: '{{ "25500,25500,26500,26500" in (trigger.event.data.service_data.params|string|replace(" ","")) }}'
            sequence:
              - service: logbook.log
                data:
                  name: 'Vacuum'
                  message: 'Cleaning kitchen'
          - conditions: '{{ "35500,25500,36500,26500" in (trigger.event.data.service_data.params|string|replace(" ","")) }}'
            sequence:
              - service: logbook.log
                data:
                  name: 'Vacuum'
                  message: 'Cleaning bedroom'
             ...
```
