### ISSUE TITLE
Roidmi EVA - required key not provided 

### ISSUE THREAD

**Issue by paqpaqpaq** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#647]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

After many many tries I finally got the Roidmi EVA responding in HA and is operable from its integration. Now for the card with rooms itself I run into this issue stating 'the required key is not provided @ data ['aiid']'.
It doesn't specify what key however so not sure what it is I am looking for here?

### What version of a card has described problem?

v2.2.2

### What vacuum model do you have problems with?

roidmi_v66_0849_robot_cleaner

### Which integration do you use to control your vacuum (link)?

https://github.com/al-one/hass-xiaomi-miot

### What browser (browsers/apps) does have this problem?

Safari

### What version of Home Assistant do you use?

2023.8.1

### What type of installation are you running?

Home Assistant Supervised

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
title: kantoor2
entity: vacuum.roidmi_v66_0849_robot_cleaner_3
vacuum_platform: al-one/hass-xiaomi-miot
map_source:
  camera: camera.xiaomi_cloud_map_extractor
map_locked: false
calibration_source:
  camera: true
map_modes:
  - template: vacuum_clean_segment
    predefined_selections:
      - id: '1'
        icon:
          name: mdi:broom
          x: 975.0000387430191
          'y': -1100.0000294297934
        label:
          text: Room1
          x: 975.0000387430191
          'y': -1100.0000294297934
          offset_y: 35
        outline:
          - - -874.9999888241291
            - -4975.000087171793
          - - 2825.0000663101673
            - -4975.000087171793
          - - 2825.0000663101673
            - 2775.0000283122063
          - - -874.9999888241291
            - 2775.0000283122063
      - id: '2'
        icon:
          name: mdi:broom
          x: 1000.0000391155481
          'y': 6100.000077858567
        label:
          text: Room2
          x: 1000.0000391155481
          'y': 6100.000077858567
          offset_y: 35
        outline:
          - - -1074.9999918043613
            - 2775.0000283122063
          - - 3075.0000700354576
            - 2775.0000283122063
          - - 3075.0000700354576
            - 9425.000127404928
          - - -1074.9999918043613
            - 9425.000127404928
      - id: '3'
        icon:
          name: mdi:broom
          x: 4225.000087171793
          'y': 6825.000088661909
        label:
          text: Room3
          x: 4225.000087171793
          'y': 6825.000088661909
          offset_y: 35
        outline:
          - - 2425.000060349703
            - 4225.00004991889
          - - 6025.000113993883
            - 4225.00004991889
          - - 6025.000113993883
            - 9425.000127404928
          - - 2425.000060349703
            - 9425.000127404928
```
