### ISSUE TITLE
Zone/Room cleaning don't work -> dreame_mc1808_14a2_robot_cleaner_2 | 

### ISSUE THREAD

**Issue by KapriQ** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#652]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

I would like to ask for help from experienced users here...

 My zone / room cleaning isn't working on my vacuum dreame_mc1808. Details bellow

Thanks, i appreciate any help :).

### What version of a card has described problem?

v2.2.2

### What vacuum model do you have problems with?

dreame_mc1808_14a2_robot_cleaner_2

### Which integration do you use to control your vacuum (link)?

https://github.com/al-one/hass-xiaomi-miot

### What browser (browsers/apps) does have this problem?

Opera/Chrome/Firefox/Iceraven

### What version of Home Assistant do you use?

2023.7.3

### What type of installation are you running?

Home Assistant Core

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.dreame_mc1808_14a2_robot_cleaner_2
vacuum_platform: default
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_clean_segment
    predefined_selections:
      - id: '1'
        icon:
          name: mdi:broom
          x: 1925
          'y': 3425
        label:
          text: Detská
          x: 1925
          'y': 3425
          offset_y: 35
        outline:
          - - 650
            - 1800
          - - 3200
            - 1800
          - - 3200
            - 5050
          - - 650
            - 5050
      - id: '2'
        icon:
          name: mdi:broom
          x: 4750
          'y': 3275
        label:
          text: Spálňa
          x: 4750
          'y': 3275
          offset_y: 35
        outline:
          - - 3400
            - 250
          - - 6100
            - 250
          - - 6100
            - 6300
          - - 3400
            - 6300
      - id: '3'
        icon:
          name: mdi:broom
          x: 1925
          'y': 275
        label:
          text: Chodba
          x: 1925
          'y': 275
          offset_y: 35
        outline:
          - - 500
            - -1200
          - - 3350
            - -1200
          - - 3350
            - 1750
          - - 500
            - 1750
      - id: '4'
        icon:
          name: mdi:broom
          x: 2550
          'y': -1975
        label:
          text: Kúpeľňa
          x: 2550
          'y': -1975
          offset_y: 35
        outline:
          - - 1800
            - -2700
          - - 3300
            - -2700
          - - 3300
            - -1250
          - - 1800
            - -1250
      - id: '5'
        icon:
          name: mdi:broom
          x: -1150
          'y': 1000
        label:
          text: Obývačka
          x: -1150
          'y': 1000
          offset_y: 35
        outline:
          - - -2750
            - -2850
          - - 450
            - -2850
          - - 450
            - 4850
          - - -2750
            - 4850
map_locked: true
two_finger_pan: true
title: brenda v2
```

### Javascript errors shown in the browser's console (if applicable)

```shell
at bottom it shows: (Vaccum plaftom in the (... )
Failed to call service vacuum/send_command. unknown error (KrzysztofHajdamowicz/miio2)
Failed to call service vacuum/vacuum_clean_segment. connection lost (default)

On the map it show the popup "Failed to call service. Service not found"
```

### Additional information

![Screenshot from 2023-09-08 15-51-04](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/31235411/05c36405-9e44-4afd-9c7f-4b1c11de4e14)
![Screenshot from 2023-09-08 15-50-56](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/31235411/b0f1faae-ff3b-42b4-9123-0be82e0bbb5b)
