### ISSUE TITLE
Failed to call service. Service not found. 

### ISSUE THREAD

**Issue by Derksie** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#658]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

When i try to pin & go or zone cleanup i get the message:
Failed to call service xiaomi_miio/vacuum_goto. Service not found.

This message occurs when i selected a point or created a zone and press start.

### What version of a card has described problem?

v2.2.2

### What vacuum model do you have problems with?

Viomi v3 max

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Firefox, also tried edge

### What version of Home Assistant do you use?

2023.9.2

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.viomi_v23_bdea_robot_cleaner
vacuum_platform: default


And this is the config in configuration.yaml:
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    force_api: roidmi
    attributes:
      - calibration_points
```
