### ISSUE TITLE
Failed to call service xiaomi_miot/call_action. required key not provided @ data['aiid']

### ISSUE THREAD

**Issue by Derksie** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#659]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

When i try to start a predefined zone I get this error message:
Failed to call service xiaomi_miot/call_action. required key not provided @ data['aiid']

### What version of a card has described problem?

v2.2.2

### What vacuum model do you have problems with?

Viomi v3 max

### Which integration do you use to control your vacuum (link)?

https://github.com/al-one/hass-xiaomi-miot

### What browser (browsers/apps) does have this problem?

Firefox

### What version of Home Assistant do you use?

2023.9.2

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
entity: vacuum.viomi_v23_bdea_robot_cleaner
vacuum_platform: al-one/hass-xiaomi-miot
map_modes:
  - template: vacuum_clean_zone_predefined
    predefined_selections:
      - zones:
          - - -2732
            - -538
            - -490
            - 542
        label:
          text: Bedroom
          x: -1600
          'y': 20
          offset_y: 35
        icon:
          name: mdi:bed
          x: -1600
          'y': 20
calibration_source:
  camera: true



Or when creating zone on the spot:

type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
entity: vacuum.viomi_v23_bdea_robot_cleaner
vacuum_platform: al-one/hass-xiaomi-miot
map_modes:
  - template: vacuum_clean_zone
calibration_source:
  camera: true
```
