### ISSUE TITLE
Dropdown menu problem with State-switch

### ISSUE THREAD

**Issue by NanouMu** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#665]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Hi, 
I use the Vacuum Map Card inside a [state-switch](https://github.com/thomasloven/lovelace-state-switch) card from thomasloven
Inside a state-switch card, all dropdown menus of the map card are offset. (no problem without state-switch)
![screenshot](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/81906281/93bf8880-6412-4c2b-a648-909cc49f0fc6)
The offset is proportional to viewport. (larger is the viewport, bigger is the offset)

Thank you for this great card

### What version of a card has described problem?

v2.2.2

### What vacuum model do you have problems with?

vacuum.roborock_s8_pro_ultra

### Which integration do you use to control your vacuum (link)?

https://github.com/humbertogontijo/homeassistant-roborock

### What browser (browsers/apps) does have this problem?

Chrome

### What version of Home Assistant do you use?

2023.10.1

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:state-switch
entity: hash
default: vacuum
transition: slide-left
transition_time: 300
states:
  vacuum:
    type: custom:xiaomi-vacuum-map-card
    map_source:
      camera: camera.roborock_s8_pro_ultra_map
    calibration_source:
      camera: true
    entity: vacuum.roborock_s8_pro_ultra
    vacuum_platform: default
```
