### ISSUE TITLE
Button Zone Cleanup dissapear

### ISSUE THREAD

**Issue by facutopa** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#675]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Can you help me? The button of Zone Cleanup dissapear and I don't know how to make it back.
![image](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/7283431/05f13160-999b-43a2-bec8-f582634650a8)

### What version of a card has described problem?

v2.2.2

### What vacuum model do you have problems with?

dreame.vacuum.mc1808

### Which integration do you use to control your vacuum (link)?

https://github.com/al-one/hass-xiaomi-miot

### What browser (browsers/apps) does have this problem?

Chrome

### What version of Home Assistant do you use?

2023.11.0

### What type of installation are you running?

Home Assistant Supervised

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.dreame_mc1808_8280_robot_cleaner
vacuum_platform: al-one/hass-xiaomi-miot
map_locked: false
map_modes:
  - template: vacuum_clean_segment
    max_selections: 1
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: xiaomi_miot.call_action
      service_data:
        entity_id: '[[entity_id]]'
        siid: 18
        aiid: 1
        params:
          - piid: 1
            value: 18
          - piid: 21
            value: '{"selects":[[[[selection_unwrapped]],[[repeats]],3,3,1]]}'
        force_params: true
        predefined_selections:
          - id: '1'
            icon:
              name: mdi:broom
              x: -750
              'y': 2450
            label:
              text: Baño
              x: -750
              'y': 2450
              offset_y: 35
            outline:
              - - -1350
                - 1950
              - - -150
                - 1950
              - - -150
                - 2950
              - - -1350
                - 2950
          - id: '2'
            icon:
              name: mdi:broom
              x: -825
              'y': -275
            label:
              text: Bedroom
              x: -825
              'y': -275
              offset_y: 35
            outline:
              - - -2100
                - -1550
              - - 450
                - -1550
              - - 450
                - 1000
              - - -2100
                - 1000
          - id: '3'
            icon:
              name: mdi:broom
              x: -2925
              'y': 4000
            label:
              text: Cocina
              x: -2925
              'y': 4000
              offset_y: 35
            outline:
              - - -3650
                - 3200
              - - -2200
                - 3200
              - - -2200
                - 4800
              - - -3650
                - 4800
          - id: '4'
            icon:
              name: mdi:broom
              x: -1850
              'y': 3800
            label:
              text: '4'
              x: -1850
              'y': 3800
              offset_y: 35
            outline:
              - - -4250
                - 1000
              - - 550
                - 1000
              - - 550
                - 6600
              - - -4250
                - 6600
    predefined_selections:
      - id: '1'
        icon:
          name: mdi:broom
          x: -600
          'y': 2100
        label:
          text: Baño
          x: -600
          'y': 2100
          offset_y: 35
        outline:
          - - -1150
            - 1650
          - - -50
            - 1650
          - - -50
            - 2550
          - - -1150
            - 2550
      - id: '2'
        icon:
          name: mdi:broom
          x: -800
          'y': -175
        label:
          text: Bedroom
          x: -800
          'y': -175
          offset_y: 35
        outline:
          - - -2150
            - -1850
          - - 550
            - -1850
          - - 550
            - 1500
          - - -2150
            - 1500
      - id: '3'
        icon:
          name: mdi:broom
          x: -2575
          'y': 5650
        label:
          text: Comedor
          x: -2575
          'y': 5650
          offset_y: 35
        outline:
          - - -4000
            - 4850
          - - -1150
            - 4850
          - - -1150
            - 6450
          - - -4000
            - 6450
      - id: '4'
        icon:
          name: mdi:broom
          x: -700
          'y': 3950
        label:
          text: Living
          x: -700
          'y': 3950
          offset_y: 35
        outline:
          - - -2150
            - 1550
          - - 750
            - 1550
          - - 750
            - 6350
          - - -2150
            - 6350
      - id: '5'
        icon:
          name: mdi:broom
          x: -2825
          'y': 3950
        label:
          text: Cocina
          x: -2825
          'y': 3950
          offset_y: 35
        outline:
          - - -3500
            - 3000
          - - -2150
            - 3000
          - - -2150
            - 4900
          - - -3500
            - 4900
```
