### ISSUE TITLE
EziClean x850 (Tuya/Smart Life installed)

### ISSUE THREAD

**Issue by atillabayrambas** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#683]
### Integration repository

https://www.home-assistant.io/integrations/xiaomi_miio/

### Supported features

- [X] Zone cleaning (using 4 coordinates)
- [X] Room cleaning (using room id/number)
- [X] Going to point (using 2 coordinates)
- [X] Cleaning a point (using 2 coordinates)
- [X] Others

### Checklist

- [X] I have sent info about entities to `piotr.machowski.dev [at] gmail.com` ([Retrieving entities info](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/594); please provide your GitHub username in the email)

### Vacuum entity/entities

```yaml
SENDED WITH MAIL


Entiteit	Status	Attributen
button.fatima_reset_map	2023-10-28T15:57:54.287976+00:00	icon: mdi:map-marker-remove friendly_name: Fatima Resetten kaart
number.fatima_volume	58.0	min: 0 max: 100 step: 1 mode: auto icon: mdi:volume-high friendly_name: Fatima Volume
select.fatima_mode	chargego	options: smart, zone, pose, part, chargego icon: mdi:layers-outline friendly_name: Fatima Mode
select.fatima_water_tank_adjustment	middle	options: low, middle, high icon: mdi:water-opacity friendly_name: Fatima Watertank aanpassing
sensor.fatima_cleaning_area	39.0	state_class: measurement unit_of_measurement: ㎡ icon: mdi:texture-box friendly_name: Fatima Schoonmaakgebied
sensor.fatima_cleaning_time	41.0	state_class: measurement unit_of_measurement: min icon: mdi:progress-clock friendly_name: Fatima Schoonmaaktijd
switch.fatima_do_not_disturb	on	icon: mdi:minus-circle friendly_name: Fatima Niet storen
vacuum.fatima	docked	fan_speed_list: gentle, normal, strong battery_level: 61 battery_icon: mdi:battery-charging-60 fan_speed: strong friendly_name: Fatima supported_features: 13180
```

### Service calls

```yaml
service: vacuum.clean_spot
service: vacuum.locate
service: vacuum.pause
service: vacuum.return_to_base
service: vacuum.send_command
service: vacuum.set_fan_speed
service: vacuum.start
service: vacuum.start_pause
service: vacuum.stop
service: vacuum.toggle
service: vacuum.turn_off
service: vacuum.turn_on
```

### Other info

https://eziclean.nl/products/beste-robotstofzuiger-eziclean-aqua-connect-x850
