### ISSUE TITLE
Add Roborock Core as a platform

### ISSUE THREAD

**Issue by Lash-L** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#691]
### Integration repository

https://www.home-assistant.io/integrations/roborock/

### Supported features

- [X] Zone cleaning (using 4 coordinates)
- [X] Room cleaning (using room id/number)
- [X] Going to point (using 2 coordinates)
- [X] Cleaning a point (using 2 coordinates)
- [ ] Others

### Checklist

- [ ] I have sent info about entities to `piotr.machowski.dev [at] gmail.com` ([Retrieving entities info](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/594); please provide your GitHub username in the email)

### Vacuum entity/entities

```yaml
n/a
```

### Service calls

```yaml
n/a
```

### Other info

Creating this issue here to keep track of my work and ask questions. I plan to do the incorporation myself so I have left service calls and entities blank.

Roborock core holds the map in a image entity instead of a camera entity, so I got the calibration points from the map parser .calibration() and set up the following:

```
type: custom:xiaomi-vacuum-map-card
entity: vacuum.s7_roborock
map_source:
  image: image.s7_roborock_downstairs
calibration_source:
  calibration_points:
    - vacuum:
        x: 25500
        'y': 25500
      map:
        x: 240
        'y': 184
    - vacuum:
        x: 35500
        'y': 25500
      map:
        x: 440
        'y': 184
    - vacuum:
        x: 25500
        'y': 35500
      map:
        x: 240
        'y': -16

vacuum_platform: humbertogontijo/homeassistant-roborock
```

However, the image does not show up 
<img width="380" alt="Screenshot 2023-12-08 at 5 54 49 PM" src="https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/20257911/3c01df37-999d-4e7b-94ab-5e0ff7fae0ff">

Before I went any further I wanted to check with you that images are supported by the card.
