### ISSUE TITLE
Vacuum doesn't start

### ISSUE THREAD

**Issue by Anisse4** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#7]
Hi 3_14,

Congrats for this developpment, and thanks for sharing it.

I have installed your module following you HowTo.

Creating directories 

> /home/homeassistant/.homeassistant/www/custom_lovelace/xiaomi_vacuum_map_card

With homeassistant rights 

> drwxr-xr-x 2 homeassistant homeassistant 4.0K Aug 26 14:18 xiaomi_vacuum_map_card

Download the 3 files inside directory adding same homeassistant rights

> -rw-r--r-- 1 homeassistant homeassistant 1.1K Aug 26 09:03 style.js
> -rw-r--r-- 1 homeassistant homeassistant  442 Aug 26 09:03 texts.js
> -rw-r--r-- 1 homeassistant homeassistant  18K Aug 26 09:02 `xiaomi-vacuum-map-card.js

Added your the ressource in top of my ui-lovelace.yaml
```
resources:
  - url: /local/my-custom-card.js
    type: js
  - url: /local/my-webfont.css
    type: css
  - url: /local/custom_lovelace/xiaomi_vacuum_map_card/xiaomi-vacuum-map-card.js
    type: module
```

And added in ui_lovelace.yaml the configuration

```
  - icon: mdi:robot-vacuum
    # Title of the view. Will be used as the tooltip for tab icon
    title: Interactive map
    cards:
      - type: custom:xiaomi-vacuum-map-card
        entity: vacuum.xiaomi_vacuum
        map_image: '/local/custom_lovelace/xiaomi_vacuum_map_card/map4.png'
        base_position:
          x: 201
          y: 283
        reference_point:
          x: 161
          y: 247
        zones:
          - [[25500, 25500, 26500, 26500]]

```

I am able to check that my coordinates are correct, as when I display the cleaning zone [[25500, 25500, 26500, 26500]], I can see the square at the right place in the map. Cf screenshot under:

Don't pay attention for the play/pause... buttons, they are only screenshot:

![Screenshot](https://user-images.githubusercontent.com/54260659/63695559-42aecb80-c819-11e9-9474-2330baeca936.png)

But When I click on start nothing happens. Same when I specify GoTo zone or new zoned cleanup.

Could you give any help please ?
Thanks in advance
