### ISSUE TITLE
Using deprecated supported features values which will be removed in HA Core 2025.1.

### ISSUE THREAD

**Issue by WolfgangFuchs** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#706]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

2024-02-04 12:58:15.390 WARNING (MainThread) [homeassistant.helpers.entity] Entity camera.xiaomi_cloud_map_extractor (<class 'custom_components.xiaomi_cloud_map_extractor.camera.VacuumCamera'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <CameraEntityFeature.ON_OFF: 1>, please create a bug report at https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

### What version of a card has described problem?

v2.2.1

### What vacuum model do you have problems with?

s7

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Chrome

### What version of Home Assistant do you use?

2024.1.6

### What type of installation are you running?

Home Assistant Core

### Card's configuration

```yaml
type: vertical-stack
cards:
  - type: entities
    entities:
      - entity: vacuum.roborock_s7
      - entity: sensor.roborock_s7_current_clean_area
        name: Gereinigte Fläche
      - entity: sensor.roborock_s7_current_clean_duration
        name: Reinigungsdauer
      - entity: update.xiaomi_vacuum_map_card_update
        name: Karte
    show_header_toggle: false
    state_color: true
    title: Roborock S7
  - camera_view: live
    type: picture-glance
    title: Roborock S7
    image: https://demo.home-assistant.io/stub_config/kitchen.png
    entities:
      - sensor.time
      - sensor.date
      - sensor.roborock_s7_current_clean_area
      - sensor.roborock_s7_current_clean_duration
    theme: waves
    camera_image: camera.xiaomi_cloud_map_extractor
    entity: vacuum.roborock_s7
  - type: custom:xiaomi-vacuum-map-card
    title: Roborock S7
    preset_name: Live map
    entity: vacuum.roborock_s7
    language: de
    map_source:
      camera: camera.xiaomi_cloud_map_extractor
    calibration_source:
      camera: false
    vacuum_platform: default
    map_locked: false
    two_finger_pan: true
```
