### ISSUE TITLE
rooms display mistake in iphone (homeassistant app or ios safari)

### ISSUE THREAD

**Issue by sunfang1cn** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#710]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

My config , It works well on windows desktop chrome and android web browsers:
![686a7fb355c051f6ee2feb469f11450](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/926867/2ec02c2f-dbb6-4cf4-9cd8-4a70497de998)

But in iphone IOS 17.2.1, both safari and homeassistant app:
![88f25c29fe5621a65654797c5893c28](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/926867/9ee08463-e628-4c2e-945e-1d0c5c9875a9)

### What version of a card has described problem?

2.2.2

### What vacuum model do you have problems with?

Deebot

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/ecovacs

### What browser (browsers/apps) does have this problem?

IOS Safari/IOS app

### What version of Home Assistant do you use?

Core 2024.2.1;  frontend 20240207.1

### What type of installation are you running?

Home Assistant Container

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.18658109175
map_source:
  camera: image.18658109175_map
vacuum_platform: DeebotUniverse/Deebot-4-Home-Assistant
map_locked: true
two_finger_pan: false
title: 科沃斯扫地机器人
language: zh
card_mod:
  style: |
    ha-card {
      --map-card-room-label-color: black;
      --map-card-room-icon-background-color: lightgreen;
      --map-card-room-label-font-size: 14px;
      --map-card-manual-rectangle-line-color: blue;
      --map-card-room-outline-line-color: green;
      --map-card-room-outline-line-color-selected: green;
      --map-card-room-outline-fill-color-selected: rgba(0,255,0,0.3);;
      --map-card-manual-rectangle-fill-color: rgba(0,0,255,0.2);

    }
calibration_source:
  image: true
map_modes:
  - template: vacuum_clean_segment
    selection_type: ROOM
    predefined_selections:
      - id: 6
        outline:
          - - -19907
            - -19907
          - - -19981
            - -17900
          - - -17232
            - -17566
          - - -15652
            - -17269
          - - -15355
            - -18030
          - - -16321
            - -18068
          - - -16507
            - -19015
          - - -17046
            - -19870
          - - -19889
            - -19926
        label:
          text: 主卧
          x: -18848
          'y': -18681
          offset_y: 30
        icon:
          name: mdi:bed
          x: -18848
          'y': -18681
      - id: 7
        outline:
          - - -16042
            - -19108
          - - -16042
            - -18068
          - - -14835
            - -18012
          - - -14723
            - -19127
          - - -16024
            - -19127
        label:
          text: 主卫
          x: -15392
          'y': -18811
          offset_y: 30
        icon:
          name: mdi:toilet
          x: -15392
          'y': -18811
      - id: 0
        outline:
          - - -15466
            - -14965
          - - -14519
            - -15002
          - - -14500
            - -12828
          - - -15522
            - -12847
          - - -15485
            - -14853
        label:
          text: 储藏间
          x: -14872
          'y': -13999
          offset_y: 30
        icon:
          name: mdi:toolbox
          x: -14872
          'y': -13999
      - id: 8
        outline:
          - - -14426
            - -14816
          - - -14444
            - -12624
          - - -12568
            - -12586
          - - -12438
            - -14742
          - - -14389
            - -14816
        label:
          text: 多功能房
          x: -13385
          'y': -13608
          offset_y: 30
        icon:
          name: mdi:desktop-classic
          x: -13385
          'y': -13608
      - id: 9
        outline:
          - - -12456
            - -13999
          - - -12624
            - -12624
          - - -11862
            - -12549
          - - -11769
            - -13980
          - - -12494
            - -14036
        label:
          text: 阳台
          x: -12215
          'y': -13367
          offset_y: 30
        icon:
          name: mdi:washing-machine
          x: -12215
          'y': -13367
      - id: 1
        outline:
          - - -15355
            - -17083
          - - -15355
            - -14928
          - - -13014
            - -15132
          - - -13032
            - -17157
          - - -15355
            - -17083
        label:
          text: 餐厅
          x: -14352
          'y': -16080
          offset_y: 30
        icon:
          name: mdi:table-chair
          x: -14352
          'y': -16080
      - id: 10
        outline:
          - - -12828
            - -16860
          - - -12865
            - -15912
          - - -11156
            - -15857
          - - -11174
            - -16916
          - - -12865
            - -16860
        label:
          text: 厨房
          x: -12048
          'y': -16451
          offset_y: 30
        icon:
          name: mdi:pot-mix
          x: -12048
          'y': -16451
      - id: 11
        outline:
          - - -12531
            - -15782
          - - -12549
            - -14835
          - - -11267
            - -14797
          - - -11230
            - -15708
          - - -12512
            - -15857
        label:
          text: 客卫
          x: -11825
          'y': -15448
          offset_y: 30
        icon:
          name: mdi:toilet
          x: -11825
          'y': -15448
      - id: 4
        outline:
          - - -18384
            - -15411
          - - -15541
            - -15392
          - - -15541
            - -12884
          - - -18476
            - -12921
          - - -18365
            - -15466
        label:
          text: 儿童房
          x: -17083
          'y': -14519
          offset_y: 30
        icon:
          name: mdi:baby
          x: -17083
          'y': -14519
      - id: 12
        outline:
          - - -19257
            - -17715
          - - -19220
            - -15466
          - - -15429
            - -15392
          - - -15318
            - -17064
          - - -16098
            - -17436
          - - -17194
            - -17343
          - - -18105
            - -17603
          - - -19294
            - -17752
        label:
          text: 客厅
          x: -17343
          'y': -16414
          offset_y: 30
        icon:
          name: mdi:sofa
          x: -17343
          'y': -16414
  - template: vacuum_clean_zone
```
