### ISSUE TITLE
Valetudo segment cleaning doesn't work

### ISSUE THREAD

**Issue by carefulcomputer** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#713]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

I am using this card with Valetudo/dreame d9 max. When I select a segment on map , it selects the segment, and click on 'play' button on right side (next to repeat count), I get a toast saying 'success' but nothing happens. The robot doesn't start. I don't see any error in browser console or in home assistant.
However if I press the main clean button (whole house) it works fine.

### What version of a card has described problem?

v2.2.2

### What vacuum model do you have problems with?

dreame d9 max/valetudo

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Chrome

### What version of Home Assistant do you use?

2024.2.2

### What type of installation are you running?

Home Assistant Core

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.rosievaccumrobot_camera
calibration_source:
  camera: true
entity: vacuum.valetudo_rosietherobot
vacuum_platform: Hypfer/Valetudo
two_finger_pan: true
map_locked: true
map_modes:
  - template: vacuum_clean_segment
    predefined_selections:
      - id: '2'
        icon:
          name: mdi:broom
          x: 3142
          'y': 3520
        label:
          text: Family Room
          x: 3142
          'y': 3520
          offset_y: 35
        outline:
          - - 2990
            - 3345
          - - 3295
            - 3345
          - - 3295
            - 3695
          - - 2990
            - 3695
      - id: '3'
        icon:
          name: mdi:broom
          x: 3010
          'y': 3310
        label:
          text: Lobby
          x: 3010
          'y': 3310
          offset_y: 35
        outline:
          - - 2695
            - 2990
          - - 3325
            - 2990
          - - 3325
            - 3430
          - - 2695
            - 3430
      - id: '4'
        icon:
          name: mdi:broom
          x: 2487
          'y': 3222
        label:
          text: Kitchen
          x: 2487
          'y': 3222
          offset_y: 35
        outline:
          - - 2350
            - 3095
          - - 2625
            - 3095
          - - 2625
            - 3350
          - - 2350
            - 3350
      - id: '5'
        icon:
          name: mdi:broom
          x: 2530
          'y': 3525
        label:
          text: Dining Room
          x: 2530
          'y': 3525
          offset_y: 35
        outline:
          - - 2370
            - 3355
          - - 2690
            - 3355
          - - 2690
            - 3695
          - - 2370
            - 3695
      - id: '7'
        icon:
          name: mdi:broom
          x: 2545
          'y': 2927
        label:
          text: Kitchen Extension
          x: 2545
          'y': 2927
          offset_y: 35
        outline:
          - - 2375
            - 2765
          - - 2715
            - 2765
          - - 2715
            - 3090
          - - 2375
            - 3090
  - template: vacuum_clean_zone
  - template: vacuum_goto
```

### Javascript errors shown in the browser's console (if applicable)

```shell
None
```

### Additional information

For maps I am using Valetudo Vacuum's Camera and map shows up fine.

**Comment by sca075** [comment]
@carefulcomputer if you use Valetudo you need to specify the topic in your card configuration an example is in this:
```
internal_variables: 
  topic: valetudo/your_topic 
```
this should solve the problem you are facing right now.. that by the way is under work, there is a PR for that.
you might have interest also on this https://github.com/sca075/valetudo_vacuum_camera  if you want to experience cloud free.

**Comment by carefulcomputer** [comment]
thank you will give it a try. and thanks again for pointing out valetudo camera. I am using that right now and it is awesome. Do not need additional docker or any other cloud.

**Comment by carefulcomputer** [comment]
unfortunately.. it didn't work.  i tried both with a trailing slash and without but nothing happened. i don't see any error. there is no error generated in browser console and there is no rest call made.

**Comment by sca075** [comment]
@carefulcomputer if you go on the main page of Valetudo Vacuum Camera (and please start the project if you like it) on the read me there is the full explanation of how to put the lines I show you. Be careful that actually you use the correct topic the one it was up was just an example.. basically in the camera attributes the same topic must be in the card.

Thanks for trying again.

**Comment by carefulcomputer** [comment]
I just starred the repo. :)
i double checked the topic and looks okey. still it did not work. Here is my card config.. What else can I do to debug the issue ?

```
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.rosievaccumrobot_camera
calibration_source:
  camera: true
entity: vacuum.valetudo_rosietherobot
vacuum_platform: Hypfer/Valetudo
two_finger_pan: true
map_locked: true
internal_variables:
  topic: homeassistant/myVaccumRobot
map_modes:
  - template: vacuum_clean_segment
    predefined_selections:
      - id: '2'
        icon:
          name: mdi:broom
          x: 3142
          'y': 3520
        label:
          text: Family Room
          x: 3142
          'y': 3520
          offset_y: 35
        outline:
          - - 2990
            - 3345
          - - 3295
            - 3345
          - - 3295
            - 3695
          - - 2990
            - 3695
      - id: '3'
        icon:
          name: mdi:broom
          x: 3010
          'y': 3310
        label:
          text: Lobby
          x: 3010
          'y': 3310
          offset_y: 35
        outline:
          - - 2695
            - 2990
          - - 3325
            - 2990
          - - 3325
            - 3430
          - - 2695
            - 3430
      - id: '4'
        icon:
          name: mdi:broom
          x: 2487
          'y': 3222
        label:
          text: Kitchen
          x: 2487
          'y': 3222
          offset_y: 35
        outline:
          - - 2350
            - 3095
          - - 2625
            - 3095
          - - 2625
            - 3350
          - - 2350
            - 3350
      - id: '5'
        icon:
          name: mdi:broom
          x: 2530
          'y': 3525
        label:
          text: Dining Room
          x: 2530
          'y': 3525
          offset_y: 35
        outline:
          - - 2370
            - 3355
          - - 2690
            - 3355
          - - 2690
            - 3695
          - - 2370
            - 3695
      - id: '7'
        icon:
          name: mdi:broom
          x: 2545
          'y': 2927
        label:
          text: Kitchen Extension
          x: 2545
          'y': 2927
          offset_y: 35
        outline:
          - - 2375
            - 2765
          - - 2715
            - 2765
          - - 2715
            - 3090
          - - 2375
            - 3090
  - template: vacuum_clean_zone
  - template: vacuum_goto

```

**Comment by PiotrMachowski** [comment]
Try this config:
```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.rosievaccumrobot_camera
calibration_source:
  camera: true
entity: vacuum.valetudo_rosietherobot
vacuum_platform: Hypfer/Valetudo
two_finger_pan: true
map_locked: true
internal_variables:
  topic: homeassistant/myVaccumRobot
map_modes:
  - template: vacuum_clean_segment
    id_type: number
    predefined_selections:
      - id: '2'
        icon:
          name: mdi:broom
          x: 3142
          'y': 3520
        label:
          text: Family Room
          x: 3142
          'y': 3520
          offset_y: 35
        outline:
          - - 2990
            - 3345
          - - 3295
            - 3345
          - - 3295
            - 3695
          - - 2990
            - 3695
      - id: '3'
        icon:
          name: mdi:broom
          x: 3010
          'y': 3310
        label:
          text: Lobby
          x: 3010
          'y': 3310
          offset_y: 35
        outline:
          - - 2695
            - 2990
          - - 3325
            - 2990
          - - 3325
            - 3430
          - - 2695
            - 3430
      - id: '4'
        icon:
          name: mdi:broom
          x: 2487
          'y': 3222
        label:
          text: Kitchen
          x: 2487
          'y': 3222
          offset_y: 35
        outline:
          - - 2350
            - 3095
          - - 2625
            - 3095
          - - 2625
            - 3350
          - - 2350
            - 3350
      - id: '5'
        icon:
          name: mdi:broom
          x: 2530
          'y': 3525
        label:
          text: Dining Room
          x: 2530
          'y': 3525
          offset_y: 35
        outline:
          - - 2370
            - 3355
          - - 2690
            - 3355
          - - 2690
            - 3695
          - - 2370
            - 3695
      - id: '7'
        icon:
          name: mdi:broom
          x: 2545
          'y': 2927
        label:
          text: Kitchen Extension
          x: 2545
          'y': 2927
          offset_y: 35
        outline:
          - - 2375
            - 2765
          - - 2715
            - 2765
          - - 2715
            - 3090
          - - 2375
            - 3090
  - template: vacuum_clean_zone
  - template: vacuum_goto
```
