### ISSUE TITLE
Map-based controls do not work

### ISSUE THREAD

**Issue by kazooie13** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#719]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

I have a problem with the map based controls. None of them seem to work. 

I get the room configuration and can select zones and/or a go to point on the map. After I send the command I only get a "success" pop up, but the command does not reach the robot. It cannot be found in the MQTT logs either.

Everything else works and non-map-based commands are received by the robot.

Map based controls via valentudo webinterface are possible.

### What version of a card has described problem?

v2.2.2

### What vacuum model do you have problems with?

Roborock S5 / Valentudo 2024.02.0

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/mqtt/

### What browser (browsers/apps) does have this problem?

all of them

### What version of Home Assistant do you use?

core-2024.2.5

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.valetudo_s5_XXXX_camera
calibration_source:
  camera: true
entity: vacuum.valetudo_XXXX
vacuum_platform: Hypfer/Valetudo
map_locked: false
two_finger_pan: true
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_clean_segment
    predefined_selections:
      - id: '16'
        icon:
          name: mdi:broom
          x: 2735
          'y': 2360
        label:
          text: room1
          x: 2735
          'y': 2360
          offset_y: 35
        outline:
          - - 2625
            - 2220
          - - 2845
            - 2220
          - - 2845
            - 2500
          - - 2625
            - 2500
      - id: '17'
        icon:
          name: mdi:broom
          x: 2315
          'y': 2760
        label:
          text: room2
          x: 2315
          'y': 2760
          offset_y: 35
        outline:
          - - 2070
            - 2615
          - - 2560
            - 2615
          - - 2560
            - 2905
          - - 2070
            - 2905
      - id: '18'
        icon:
          name: mdi:broom
          x: 2342
          'y': 2360
        label:
          text: room3
          x: 2342
          'y': 2360
          offset_y: 35
        outline:
          - - 2065
            - 2110
          - - 2620
            - 2110
          - - 2620
            - 2610
          - - 2065
            - 2610
      - id: '19'
        icon:
          name: mdi:broom
          x: 2845
          'y': 2575
        label:
          text: room4
          x: 2845
          'y': 2575
          offset_y: 35
        outline:
          - - 2700
            - 2505
          - - 2990
            - 2505
          - - 2990
            - 2645
          - - 2700
            - 2645
      - id: '20'
        icon:
          name: mdi:broom
          x: 2905
          'y': 2420
        label:
          text: room5
          x: 2905
          'y': 2420
          offset_y: 35
        outline:
          - - 2820
            - 2345
          - - 2990
            - 2345
          - - 2990
            - 2495
          - - 2820
            - 2495
  - template: vacuum_clean_segment
    predefined_selections:
      - id: '16'
        icon:
          name: mdi:broom
          x: 2735
          'y': 2360
        label:
          text: room1
          x: 2735
          'y': 2360
          offset_y: 35
        outline:
          - - 2625
            - 2220
          - - 2845
            - 2220
          - - 2845
            - 2500
          - - 2625
            - 2500
      - id: '17'
        icon:
          name: mdi:broom
          x: 2315
          'y': 2760
        label:
          text: room2
          x: 2315
          'y': 2760
          offset_y: 35
        outline:
          - - 2070
            - 2615
          - - 2560
            - 2615
          - - 2560
            - 2905
          - - 2070
            - 2905
      - id: '18'
        icon:
          name: mdi:broom
          x: 2342
          'y': 2360
        label:
          text: room3
          x: 2342
          'y': 2360
          offset_y: 35
        outline:
          - - 2065
            - 2110
          - - 2620
            - 2110
          - - 2620
            - 2610
          - - 2065
            - 2610
      - id: '19'
        icon:
          name: mdi:broom
          x: 2845
          'y': 2575
        label:
          text: room4
          x: 2845
          'y': 2575
          offset_y: 35
        outline:
          - - 2700
            - 2505
          - - 2990
            - 2505
          - - 2990
            - 2645
          - - 2700
            - 2645
      - id: '20'
        icon:
          name: mdi:broom
          x: 2905
          'y': 2420
        label:
          text: room5
          x: 2905
          'y': 2420
          offset_y: 35
        outline:
          - - 2820
            - 2345
          - - 2990
            - 2345
          - - 2990
            - 2495
          - - 2820
            - 2495
```
