### ISSUE TITLE
`attribute` not working correctly

### ISSUE THREAD

**Issue by veniplex** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#751]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

The `attribute` option in the config is not functioning.

For example, this config:
```yaml
...
tiles:
  - label: Main Brush
    icon: mdi:brush-variant
    attribute: props.main_brush_work_time # This is not working
...
```

results in:
![image](https://github.com/user-attachments/assets/c81de331-d256-411c-88a4-458d86d553bb)

### What version of a card has described problem?

v2.2.4

### What vacuum model do you have problems with?

roborock.vacuum.s5

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Chrome

### What version of Home Assistant do you use?

core-2024.7.3

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.roborock_kamera
calibration_source:
  camera: true
entity: vacuum.roborock_s5
vacuum_platform: default
title: ''
two_finger_pan: true
map_locked: false
tiles:
  - label: Main Brush
    icon: mdi:brush-variant
    entity: vacuum.roborock_s5
    attribute: props.main_brush_work_time
    tooltip: Runned time
    unit: seconds
    multiplier: 1
    precision: 1
    order: 1
```

**Comment by PiotrMachowski** [comment]
Does it work when you provide entity id?
```yaml
...
tiles:
  - label: Main Brush
    icon: mdi:brush-variant
    entity: vacuum.roborock_s5
    attribute: props.main_brush_work_time
...
```

**Comment by veniplex** [comment]
> Does it work when you provide entity id?
> 
> ```yaml
> ...
> tiles:
>   - label: Main Brush
>     icon: mdi:brush-variant
>     entity: vacuum.roborock_s5
>     attribute: props.main_brush_work_time
> ...
> ```

No, then the status is just "unknown" :(.
![image](https://github.com/user-attachments/assets/e557f7d8-8dcc-468d-a55e-b8dffa001b1f)

**Comment by PiotrMachowski** [comment]
The tile appears, so it definitely works better.

What are attributes of `vacuum.roborock_s5` entity? You can check them here:
[![Open your Home Assistant instance and show your state developer tools.](https://my.home-assistant.io/badges/developer_states.svg)](https://my.home-assistant.io/redirect/developer_states/)

**Comment by veniplex** [comment]
@PiotrMachowski here is the full list of attributes for `vacuum.roborock_s5`:

```yaml
fan_speed_list:
  - Silent
  - Basic
  - Strong
  - Full Speed
battery_level: 100
battery_icon: mdi:battery-charging-100
fan_speed: Full Speed
model: roborock.vacuum.s5
lan_ip: 192.168.178.34
mac_address: 78:11:DC:EC:F5:FD
entity_class: MiotRoborockVacuumEntity
home_room: Home Wohnzimmer
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:roborock-s5:1
vacuum.status: 3
vacuum.mode: 104
battery.charging_state: 1
state_updater: lan
vacuum.status_desc: Charging
props:
  msg_ver: 3
  msg_seq: 851
  state: 8
  battery: 100
  clean_time: 0
  clean_area: 0
  error_code: 0
  map_present: 1
  in_cleaning: 0
  in_returning: 0
  in_fresh_state: 1
  lab_status: 1
  water_box_status: 0
  fan_power: 104
  dnd_enabled: 0
  map_status: 3
  lock_status: 0
  main_brush_work_time: 68769
  side_brush_work_time: 68769
  filter_work_time: 68769
  filter_element_work_time: 0
  sensor_dirty_time: 68765
  fan_mode: 104
clean_area: 0
clean_time: 0
sub_entities:
  - props:clean_area
  - props:clean_time
  - vacuum-2.status-1
  - battery-3.battery_level-1
  - battery-3.charging_state-2
friendly_name: Roborock
supported_features: 13308
```
