### ISSUE TITLE
Error while trying to generate rooms configuration - TypeError: can't define array index property past the end of an array with non-writable length

### ISSUE THREAD

**Issue by andrzej-devops** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#760]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Hi,

I have installed the latest version of Xiaomi Vacuum Map card and managed to configure custom card. I can see map, I'm able to control robot but I cannot generate a configuration for rooms. When I click on "Generate rooms config" I got this error in the log:

`TypeError: Cannot add property 2, object is not extensible
Hs._handleRoomConfig (/hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js:262:969)
zc._handleRoomsConfigGet (/hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js:1223:5485)
Hs._generateRoomsConfig (/hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js:164:1144)
Hs.<anonymous> (/hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js:251:42)
te.handleEvent (/hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js:18:7389)`

### What version of a card has described problem?

v2.2.4

### What vacuum model do you have problems with?

rockrobo.vacuum.v1

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Brave, Chrome, Firefox

### What version of Home Assistant do you use?

core-2024.9.2

### What type of installation are you running?

Home Assistant Core

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
title: Xiaomi
entity: vacuum.paulinka
vacuum_platform: default
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
icons:
  - icon: mdi:play
    conditions:
      - entity: vacuum.paulinka
        value_not: cleaning
      - entity: vacuum.paulinka
        value_not: error
      - entity: vacuum.paulinka
        value_not: returning
    tooltip: Uruchom
    tap_action:
      action: call-service
      service: vacuum.start
      service_data:
        entity_id: vacuum.paulinka
  - icon: mdi:pause
    conditions:
      - entity: vacuum.paulinka
        value_not: docked
      - entity: vacuum.paulinka
        value_not: idle
      - entity: vacuum.paulinka
        value_not: error
      - entity: vacuum.paulinka
        value_not: paused
    tooltip: Wstrzymaj
    tap_action:
      action: call-service
      service: vacuum.pause
      service_data:
        entity_id: vacuum.paulinka
  - icon: mdi:stop
    conditions:
      - entity: vacuum.paulinka
        value_not: docked
      - entity: vacuum.paulinka
        value_not: idle
      - entity: vacuum.paulinka
        value_not: error
      - entity: vacuum.paulinka
        value_not: paused
    tooltip: Zatrzymaj
    tap_action:
      action: call-service
      service: vacuum.stop
      service_data:
        entity_id: vacuum.paulinka
  - icon: mdi:home-map-marker
    conditions:
      - entity: vacuum.paulinka
        value_not: docked
      - entity: vacuum.paulinka
        value_not: returning
    tooltip: Wróć do stacji dokującej
    tap_action:
      action: call-service
      service: vacuum.return_to_base
      service_data:
        entity_id: vacuum.paulinka
  - icon: mdi:target-variant
    conditions:
      - entity: vacuum.paulinka
        value_not: docked
      - entity: vacuum.paulinka
        value_not: error
      - entity: vacuum.paulinka
        value_not: cleaning
      - entity: vacuum.paulinka
        value_not: returning
    tooltip: Wyczyść miejsce
    tap_action:
      action: call-service
      service: vacuum.clean_spot
      service_data:
        entity_id: vacuum.paulinka
  - icon: mdi:map-marker
    tooltip: Zlokalizuj
    tap_action:
      action: call-service
      service: vacuum.locate
      service_data:
        entity_id: vacuum.paulinka
  - menu_id: fan_speed
    icon: mdi:fan-remove
    label: Cichy
    conditions:
      - entity: vacuum.paulinka
        attribute: fan_speed
        value: Silent
    tooltip: Zmień prędkość wentylatora
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.paulinka
        fan_speed: Silent
  - menu_id: fan_speed
    icon: mdi:fan-speed-1
    label: Normalny
    conditions:
      - entity: vacuum.paulinka
        attribute: fan_speed
        value: Standard
    tooltip: Zmień prędkość wentylatora
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.paulinka
        fan_speed: Standard
  - menu_id: fan_speed
    icon: mdi:fan-speed-2
    label: Średni
    conditions:
      - entity: vacuum.paulinka
        attribute: fan_speed
        value: Medium
    tooltip: Zmień prędkość wentylatora
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.paulinka
        fan_speed: Medium
  - menu_id: fan_speed
    icon: mdi:fan-speed-3
    label: Turbo
    conditions:
      - entity: vacuum.paulinka
        attribute: fan_speed
        value: Turbo
    tooltip: Zmień prędkość wentylatora
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.paulinka
        fan_speed: Turbo
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.paulinka
        attribute: fan_speed
        value_not: Silent
      - entity: vacuum.paulinka
        attribute: fan_speed
        value_not: Standard
      - entity: vacuum.paulinka
        attribute: fan_speed
        value_not: Medium
      - entity: vacuum.paulinka
        attribute: fan_speed
        value_not: Turbo
    tooltip: Zmień prędkość wentylatora
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.paulinka
        fan_speed: Silent
tiles:
  - tile_id: status
    entity: vacuum.paulinka
    label: Status
    attribute: status
    icon: mdi:robot-vacuum
    translations:
      starting: Uruchamianie
      charger disconnected: Ładowarka odłączona
      idle: Nieaktywny
      remote control active: Zdalne sterowanie
      cleaning: Sprzątanie
      returning home: Powrót do stacji
      manual mode: Tryb manualny
      charging: Ładowanie
      charging problem: Problem z ładowaniem
      paused: Wstrzymany
      spot cleaning: Sprzątanie punktowe
      error: Błąd
      shutting down: Wyłączanie
      updating: Aktualizowanie
      docking: Dokowanie
      going to target: W drodze do celu
      zoned cleaning: Sprzątanie strefowe
      segment cleaning: Sprzątanie pokoju
      emptying the bin: Opróżnianie pojemnika
      charging complete: Ładowanie zakończone
      device offline: Offline
  - tile_id: battery_level
    entity: vacuum.paulinka
    label: Bateria
    attribute: battery_level
    icon_source: vacuum.paulinka.attributes.battery_icon
    unit: '%'
  - tile_id: fan_speed
    entity: vacuum.paulinka
    label: Wentylator
    attribute: fan_speed
    icon: mdi:fan
    translations:
      silent: Cichy
      standard: Normalny
      medium: Średni
      turbo: Turbo
      auto: Automatyczny
      gentle: Delikatny
  - tile_id: sensor_dirty_left
    label: Sensory
    unit: h
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: {}
      service_data:
        command: reset_consumable
        params: sensor_dirty_time
        entity_id: vacuum.paulinka
    entity: sensor.paulinka_sensor_dirty_left
    icon: mdi:eye-outline
    precision: 0
    translations: {}
  - tile_id: filter_left
    label: Filtr
    unit: h
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: {}
      service_data:
        command: reset_consumable
        params: filter_work_time
        entity_id: vacuum.paulinka
    entity: sensor.paulinka_filter_left
    icon: mdi:air-filter
    precision: 0
    translations: {}
  - tile_id: main_brush_left
    label: Główna szczotka
    unit: h
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: {}
      service_data:
        command: reset_consumable
        params: main_brush_work_time
        entity_id: vacuum.paulinka
    entity: sensor.paulinka_main_brush_left
    icon: mdi:brush
    precision: 0
    translations: {}
  - tile_id: side_brush_left
    label: Boczna szczotka
    unit: h
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: {}
      service_data:
        command: reset_consumable
        params: side_brush_work_time
        entity_id: vacuum.paulinka
    entity: sensor.paulinka_side_brush_left
    icon: mdi:brush
    precision: 0
    translations: {}
map_modes:
  - name: Sprzątanie strefowe
    icon: mdi:select-drag
    run_immediately: false
    coordinates_rounding: true
    coordinates_to_meters_divider: 1000
    selection_type: MANUAL_RECTANGLE
    max_selections: 5
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: xiaomi_miio.vacuum_clean_zone
      service_data:
        zone: '[[selection]]'
        repeats: '[[repeats]]'
        entity_id: '[[entity_id]]'
    predefined_selections: []
    variables: {}
  - name: Idź do punktu
    icon: mdi:map-marker-plus
    run_immediately: false
    coordinates_rounding: true
    coordinates_to_meters_divider: 1000
    selection_type: MANUAL_POINT
    max_selections: 999
    repeats_type: NONE
    max_repeats: 1
    service_call_schema:
      service: xiaomi_miio.vacuum_goto
      service_data:
        x_coord: '[[point_x]]'
        y_coord: '[[point_y]]'
        entity_id: '[[entity_id]]'
    predefined_selections: []
    variables: {}
additional_presets: []
```

**Comment by PiotrMachowski** [comment]
Can you change card's config to the following one and try again:
```yaml
type: custom:xiaomi-vacuum-map-card
title: Xiaomi
entity: vacuum.paulinka
vacuum_platform: default
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
```
