### ISSUE TITLE
Dreame vacuum cleaning by room does not work using the map

### ISSUE THREAD

**Issue by mgidding** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#764]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Hello, when I select a room to clean in the vacuum map my Dreame vacuum cleaner instead cleans the entire floor. When I run the following action via developer tools, cleaning a single room does work:

```
action: dreame_vacuum.vacuum_clean_segment
target:
  entity_id: vacuum.stoffel
data:
  segments: [
  1
  ]
  repeats: 1
```
I have previously changed the room ids from string ("1") to int (1) but that did not help. The generated service call is:

```
{
  "domain": "dreame_vacuum",
  "service": "vacuum_clean_segment",
  "serviceData": {
    "segments": [
      1
    ],
    "repeats": 1,
    "entity_id": "vacuum.stoffel"
  }
}
```

### What version of a card has described problem?

v2.2.4

### What vacuum model do you have problems with?

dreame.vacuum.r2228o

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Safari

### What version of Home Assistant do you use?

2024.10.2

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.stoffel
map_source:
  camera: camera.stoffel_map
calibration_source:
  camera: true
vacuum_platform: Tasshack/dreame-vacuum
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_point
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 1
        icon:
          name: mdi:chef-hat
          x: 4500
          "y": 5700
        label:
          text: Kitchen
          x: 4500
          "y": 5700
          offset_y: 35
        outline:
          - - 3100
            - 3750
          - - 5650
            - 3750
          - - 5650
            - 7600
          - - 3100
            - 7600
      - id: 2
        icon:
          name: mdi:toilet
          x: 4300
          "y": 2100
        label:
          text: Bathroom
          x: 4300
          "y": 2100
          offset_y: 35
        outline:
          - - 2850
            - 1050
          - - 5700
            - 1050
          - - 5700
            - 3100
          - - 2850
            - 3100
      - id: 3
        icon:
          name: mdi:bed-king-outline
          x: -2650
          "y": -1100
        label:
          text: Primary Bedroom
          x: -2650
          "y": -1100
          offset_y: 35
        outline:
          - - -7250
            - -3450
          - - 1300
            - -3450
          - - 1300
            - 900
          - - -7250
            - 900
      - id: 4
        icon:
          name: mdi:bed-single-outline
          x: -1050
          "y": 1650
        label:
          text: Secondary Bedroom
          x: -1050
          "y": 1650
          offset_y: 35
        outline:
          - - -3250
            - 1050
          - - 1300
            - 1050
          - - 1300
            - 3200
          - - -3250
            - 3200
      - id: 5
        icon:
          name: mdi:sofa-outline
          x: -1700
          "y": 7450
        label:
          text: Living Room
          x: -1700
          "y": 7450
          offset_y: 35
        outline:
          - - -3550
            - 3000
          - - 5850
            - 3000
          - - 5850
            - 12550
          - - -3550
            - 12550
      - id: 6
        icon:
          name: mdi:archive-outline
          x: 3150
          "y": -1450
        label:
          text: Utility Room
          x: 3150
          "y": -1450
          offset_y: 35
        outline:
          - - 2800
            - -2050
          - - 3450
            - -2050
          - - 3450
            - -850
          - - 2800
            - -850
      - id: 7
        icon:
          name: mdi:home-outline
          x: 3450
          "y": -200
        label:
          text: Toilet
          x: 3450
          "y": -200
          offset_y: 35
        outline:
          - - 2850
            - -700
          - - 4050
            - -700
          - - 4050
            - 150
          - - 2850
            - 150
      - id: 8
        icon:
          name: mdi:foot-print
          x: 2050
          "y": -250
        label:
          text: Corridor
          x: 2050
          "y": -250
          offset_y: 35
        outline:
          - - 1250
            - -3800
          - - 4200
            - -3800
          - - 4200
            - 3150
          - - 1250
            - 3150
```

### Additional information

I am using dreame vacuum v2.0.0b16
