### ISSUE TITLE
Multiple "rooms" mode

### ISSUE THREAD

**Issue by JDrillz** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#765]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Hello, I'm having a little problem with this card.
I had to generate a new rooms configuration because of a mistake with the map, and now I see multiple "rooms" mode buttons on my card.
How can I fix it?
I already try to uninstall/reinstall everything about my Roborock.

Thanks!
![Screenshot 2024-10-12 at 18-16-53 Casa – Home Assistant](https://github.com/user-attachments/assets/09678d93-a7bb-48ec-b98c-f2568a4b4dde)

### What version of a card has described problem?

v2.2.4

### What vacuum model do you have problems with?

Roborock S8

### Which integration do you use to control your vacuum (link)?

https://github.com/humbertogontijo/homeassistant-roborock

### What browser (browsers/apps) does have this problem?

Firefox

### What version of Home Assistant do you use?

2024.10.2

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.roborock_s8_map
calibration_source:
  camera: true
entity: vacuum.roborock_s8
vacuum_platform: humbertogontijo/homeassistant-roborock
two_finger_pan: true
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_clean_segment
    predefined_selections:
      - id: "16"
        icon:
          name: mdi:broom
          x: 23750
          "y": 24150
        label:
          text: Room 16
          x: 23750
          "y": 24150
          offset_y: 35
        outline:
          - - 21400
            - 22250
          - - 26100
            - 22250
          - - 26100
            - 26050
          - - 21400
            - 26050
      - id: "17"
        icon:
          name: mdi:broom
          x: 29425
          "y": 20100
        label:
          text: Room 17
          x: 29425
          "y": 20100
          offset_y: 35
        outline:
          - - 27600
            - 18100
          - - 31250
            - 18100
          - - 31250
            - 22100
          - - 27600
            - 22100
      - id: "18"
        icon:
          name: mdi:broom
          x: 33275
          "y": 19275
        label:
          text: Room 18
          x: 33275
          "y": 19275
          offset_y: 35
        outline:
          - - 31250
            - 18250
          - - 35300
            - 18250
          - - 35300
            - 20300
          - - 31250
            - 20300
      - id: "19"
        icon:
          name: mdi:broom
          x: 20500
          "y": 18000
        label:
          text: Room 19
          x: 20500
          "y": 18000
          offset_y: 35
        outline:
          - - 19850
            - 16400
          - - 21150
            - 16400
          - - 21150
            - 19600
          - - 19850
            - 19600
      - id: "20"
        icon:
          name: mdi:broom
          x: 28550
          "y": 24025
        label:
          text: Room 20
          x: 28550
          "y": 24025
          offset_y: 35
        outline:
          - - 26150
            - 22250
          - - 30950
            - 22250
          - - 30950
            - 25800
          - - 26150
            - 25800
      - id: "21"
        icon:
          name: mdi:broom
          x: 28025
          "y": 17050
        label:
          text: Room 21
          x: 28025
          "y": 17050
          offset_y: 35
        outline:
          - - 26100
            - 16050
          - - 29950
            - 16050
          - - 29950
            - 18050
          - - 26100
            - 18050
      - id: "22"
        icon:
          name: mdi:broom
          x: 26200
          "y": 20125
        label:
          text: Room 22
          x: 26200
          "y": 20125
          offset_y: 35
        outline:
          - - 24900
            - 18050
          - - 27500
            - 18050
          - - 27500
            - 22200
          - - 24900
            - 22200
      - id: "23"
        icon:
          name: mdi:broom
          x: 23075
          "y": 21300
        label:
          text: Room 23
          x: 23075
          "y": 21300
          offset_y: 35
        outline:
          - - 21300
            - 20550
          - - 24850
            - 20550
          - - 24850
            - 22050
          - - 21300
            - 22050
      - id: "24"
        icon:
          name: mdi:broom
          x: 25675
          "y": 19200
        label:
          text: Room 24
          x: 25675
          "y": 19200
          offset_y: 35
        outline:
          - - 25200
            - 17650
          - - 26150
            - 17650
          - - 26150
            - 20750
          - - 25200
            - 20750
      - id: "25"
        icon:
          name: mdi:broom
          x: 33450
          "y": 21275
        label:
          text: Room 25
          x: 33450
          "y": 21275
          offset_y: 35
        outline:
          - - 31550
            - 20350
          - - 35350
            - 20350
          - - 35350
            - 22200
          - - 31550
            - 22200
      - id: "26"
        icon:
          name: mdi:broom
          x: 23575
          "y": 18175
        label:
          text: Room 26
          x: 23575
          "y": 18175
          offset_y: 35
        outline:
          - - 21100
            - 16000
          - - 26050
            - 16000
          - - 26050
            - 20350
          - - 21100
            - 20350
      - id: "27"
        icon:
          name: mdi:broom
          x: 29575
          "y": 26550
        label:
          text: Room 27
          x: 29575
          "y": 26550
          offset_y: 35
        outline:
          - - 29000
            - 25900
          - - 30150
            - 25900
          - - 30150
            - 27200
          - - 29000
            - 27200
  - template: vacuum_clean_segment
    predefined_selections:
      - id: "16"
        icon:
          name: mdi:broom
          x: 23750
          "y": 24150
        label:
          text: Room 16
          x: 23750
          "y": 24150
          offset_y: 35
        outline:
          - - 21400
            - 22250
          - - 26100
            - 22250
          - - 26100
            - 26050
          - - 21400
            - 26050
      - id: "17"
        icon:
          name: mdi:broom
          x: 29425
          "y": 20100
        label:
          text: Room 17
          x: 29425
          "y": 20100
          offset_y: 35
        outline:
          - - 27600
            - 18100
          - - 31250
            - 18100
          - - 31250
            - 22100
          - - 27600
            - 22100
      - id: "18"
        icon:
          name: mdi:broom
          x: 33275
          "y": 19275
        label:
          text: Room 18
          x: 33275
          "y": 19275
          offset_y: 35
        outline:
          - - 31250
            - 18250
          - - 35300
            - 18250
          - - 35300
            - 20300
          - - 31250
            - 20300
      - id: "19"
        icon:
          name: mdi:broom
          x: 20500
          "y": 18000
        label:
          text: Room 19
          x: 20500
          "y": 18000
          offset_y: 35
        outline:
          - - 19850
            - 16400
          - - 21150
            - 16400
          - - 21150
            - 19600
          - - 19850
            - 19600
      - id: "20"
        icon:
          name: mdi:broom
          x: 28550
          "y": 24025
        label:
          text: Room 20
          x: 28550
          "y": 24025
          offset_y: 35
        outline:
          - - 26150
            - 22250
          - - 30950
            - 22250
          - - 30950
            - 25800
          - - 26150
            - 25800
      - id: "21"
        icon:
          name: mdi:broom
          x: 28025
          "y": 17050
        label:
          text: Room 21
          x: 28025
          "y": 17050
          offset_y: 35
        outline:
          - - 26100
            - 16050
          - - 29950
            - 16050
          - - 29950
            - 18050
          - - 26100
            - 18050
      - id: "22"
        icon:
          name: mdi:broom
          x: 26200
          "y": 20125
        label:
          text: Room 22
          x: 26200
          "y": 20125
          offset_y: 35
        outline:
          - - 24900
            - 18050
          - - 27500
            - 18050
          - - 27500
            - 22200
          - - 24900
            - 22200
      - id: "23"
        icon:
          name: mdi:broom
          x: 23075
          "y": 21300
        label:
          text: Room 23
          x: 23075
          "y": 21300
          offset_y: 35
        outline:
          - - 21300
            - 20550
          - - 24850
            - 20550
          - - 24850
            - 22050
          - - 21300
            - 22050
      - id: "24"
        icon:
          name: mdi:broom
          x: 25675
          "y": 19200
        label:
          text: Room 24
          x: 25675
          "y": 19200
          offset_y: 35
        outline:
          - - 25200
            - 17650
          - - 26150
            - 17650
          - - 26150
            - 20750
          - - 25200
            - 20750
      - id: "25"
        icon:
          name: mdi:broom
          x: 33450
          "y": 21275
        label:
          text: Room 25
          x: 33450
          "y": 21275
          offset_y: 35
        outline:
          - - 31550
            - 20350
          - - 35350
            - 20350
          - - 35350
            - 22200
          - - 31550
            - 22200
      - id: "26"
        icon:
          name: mdi:broom
          x: 23575
          "y": 18175
        label:
          text: Room 26
          x: 23575
          "y": 18175
          offset_y: 35
        outline:
          - - 21100
            - 16000
          - - 26050
            - 16000
          - - 26050
            - 20350
          - - 21100
            - 20350
      - id: "27"
        icon:
          name: mdi:broom
          x: 29575
          "y": 26550
        label:
          text: Room 27
          x: 29575
          "y": 26550
          offset_y: 35
        outline:
          - - 29000
            - 25900
          - - 30150
            - 25900
          - - 30150
            - 27200
          - - 29000
            - 27200
  - template: vacuum_clean_segment
    predefined_selections:
      - id: "16"
        icon:
          name: mdi:broom
          x: 23750
          "y": 24150
        label:
          text: Room 16
          x: 23750
          "y": 24150
          offset_y: 35
        outline:
          - - 21400
            - 22250
          - - 26100
            - 22250
          - - 26100
            - 26050
          - - 21400
            - 26050
      - id: "17"
        icon:
          name: mdi:broom
          x: 29425
          "y": 20100
        label:
          text: Room 17
          x: 29425
          "y": 20100
          offset_y: 35
        outline:
          - - 27600
            - 18100
          - - 31250
            - 18100
          - - 31250
            - 22100
          - - 27600
            - 22100
      - id: "18"
        icon:
          name: mdi:broom
          x: 33275
          "y": 19275
        label:
          text: Room 18
          x: 33275
          "y": 19275
          offset_y: 35
        outline:
          - - 31250
            - 18250
          - - 35300
            - 18250
          - - 35300
            - 20300
          - - 31250
            - 20300
      - id: "19"
        icon:
          name: mdi:broom
          x: 20500
          "y": 18000
        label:
          text: Room 19
          x: 20500
          "y": 18000
          offset_y: 35
        outline:
          - - 19850
            - 16400
          - - 21150
            - 16400
          - - 21150
            - 19600
          - - 19850
            - 19600
      - id: "20"
        icon:
          name: mdi:broom
          x: 28550
          "y": 24025
        label:
          text: Room 20
          x: 28550
          "y": 24025
          offset_y: 35
        outline:
          - - 26150
            - 22250
          - - 30950
            - 22250
          - - 30950
            - 25800
          - - 26150
            - 25800
      - id: "21"
        icon:
          name: mdi:broom
          x: 28025
          "y": 17050
        label:
          text: Room 21
          x: 28025
          "y": 17050
          offset_y: 35
        outline:
          - - 26100
            - 16050
          - - 29950
            - 16050
          - - 29950
            - 18050
          - - 26100
            - 18050
      - id: "22"
        icon:
          name: mdi:broom
          x: 26200
          "y": 20125
        label:
          text: Room 22
          x: 26200
          "y": 20125
          offset_y: 35
        outline:
          - - 24900
            - 18050
          - - 27500
            - 18050
          - - 27500
            - 22200
          - - 24900
            - 22200
      - id: "23"
        icon:
          name: mdi:broom
          x: 23075
          "y": 21300
        label:
          text: Room 23
          x: 23075
          "y": 21300
          offset_y: 35
        outline:
          - - 21300
            - 20550
          - - 24850
            - 20550
          - - 24850
            - 22050
          - - 21300
            - 22050
      - id: "24"
        icon:
          name: mdi:broom
          x: 25675
          "y": 19200
        label:
          text: Room 24
          x: 25675
          "y": 19200
          offset_y: 35
        outline:
          - - 25200
            - 17650
          - - 26150
            - 17650
          - - 26150
            - 20750
          - - 25200
            - 20750
      - id: "25"
        icon:
          name: mdi:broom
          x: 33450
          "y": 21275
        label:
          text: Room 25
          x: 33450
          "y": 21275
          offset_y: 35
        outline:
          - - 31550
            - 20350
          - - 35350
            - 20350
          - - 35350
            - 22200
          - - 31550
            - 22200
      - id: "26"
        icon:
          name: mdi:broom
          x: 23575
          "y": 18175
        label:
          text: Room 26
          x: 23575
          "y": 18175
          offset_y: 35
        outline:
          - - 21100
            - 16000
          - - 26050
            - 16000
          - - 26050
            - 20350
          - - 21100
            - 20350
      - id: "27"
        icon:
          name: mdi:broom
          x: 29575
          "y": 26550
        label:
          text: Room 27
          x: 29575
          "y": 26550
          offset_y: 35
        outline:
          - - 29000
            - 25900
          - - 30150
            - 25900
          - - 30150
            - 27200
          - - 29000
            - 27200
  - template: vacuum_clean_segment
    predefined_selections:
      - id: "16"
        icon:
          name: mdi:broom
          x: 23750
          "y": 24150
        label:
          text: Room 16
          x: 23750
          "y": 24150
          offset_y: 35
        outline:
          - - 21400
            - 22250
          - - 26100
            - 22250
          - - 26100
            - 26050
          - - 21400
            - 26050
      - id: "17"
        icon:
          name: mdi:broom
          x: 29425
          "y": 20100
        label:
          text: Room 17
          x: 29425
          "y": 20100
          offset_y: 35
        outline:
          - - 27600
            - 18100
          - - 31250
            - 18100
          - - 31250
            - 22100
          - - 27600
            - 22100
      - id: "18"
        icon:
          name: mdi:broom
          x: 33275
          "y": 19275
        label:
          text: Room 18
          x: 33275
          "y": 19275
          offset_y: 35
        outline:
          - - 31250
            - 18250
          - - 35300
            - 18250
          - - 35300
            - 20300
          - - 31250
            - 20300
      - id: "19"
        icon:
          name: mdi:broom
          x: 20500
          "y": 18000
        label:
          text: Room 19
          x: 20500
          "y": 18000
          offset_y: 35
        outline:
          - - 19850
            - 16400
          - - 21150
            - 16400
          - - 21150
            - 19600
          - - 19850
            - 19600
      - id: "20"
        icon:
          name: mdi:broom
          x: 28550
          "y": 24025
        label:
          text: Room 20
          x: 28550
          "y": 24025
          offset_y: 35
        outline:
          - - 26150
            - 22250
          - - 30950
            - 22250
          - - 30950
            - 25800
          - - 26150
            - 25800
      - id: "21"
        icon:
          name: mdi:broom
          x: 28025
          "y": 17050
        label:
          text: Room 21
          x: 28025
          "y": 17050
          offset_y: 35
        outline:
          - - 26100
            - 16050
          - - 29950
            - 16050
          - - 29950
            - 18050
          - - 26100
            - 18050
      - id: "22"
        icon:
          name: mdi:broom
          x: 26200
          "y": 20125
        label:
          text: Room 22
          x: 26200
          "y": 20125
          offset_y: 35
        outline:
          - - 24900
            - 18050
          - - 27500
            - 18050
          - - 27500
            - 22200
          - - 24900
            - 22200
      - id: "23"
        icon:
          name: mdi:broom
          x: 23075
          "y": 21300
        label:
          text: Room 23
          x: 23075
          "y": 21300
          offset_y: 35
        outline:
          - - 21300
            - 20550
          - - 24850
            - 20550
          - - 24850
            - 22050
          - - 21300
            - 22050
      - id: "24"
        icon:
          name: mdi:broom
          x: 25675
          "y": 19200
        label:
          text: Room 24
          x: 25675
          "y": 19200
          offset_y: 35
        outline:
          - - 25200
            - 17650
          - - 26150
            - 17650
          - - 26150
            - 20750
          - - 25200
            - 20750
      - id: "25"
        icon:
          name: mdi:broom
          x: 33450
          "y": 21275
        label:
          text: Room 25
          x: 33450
          "y": 21275
          offset_y: 35
        outline:
          - - 31550
            - 20350
          - - 35350
            - 20350
          - - 35350
            - 22200
          - - 31550
            - 22200
      - id: "26"
        icon:
          name: mdi:broom
          x: 23575
          "y": 18175
        label:
          text: Room 26
          x: 23575
          "y": 18175
          offset_y: 35
        outline:
          - - 21100
            - 16000
          - - 26050
            - 16000
          - - 26050
            - 20350
          - - 21100
            - 20350
      - id: "27"
        icon:
          name: mdi:broom
          x: 29575
          "y": 26550
        label:
          text: Room 27
          x: 29575
          "y": 26550
          offset_y: 35
        outline:
          - - 29000
            - 25900
          - - 30150
            - 25900
          - - 30150
            - 27200
          - - 29000
            - 27200
```

**Comment by PiotrMachowski** [comment]
```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.roborock_s8_map
calibration_source:
  camera: true
entity: vacuum.roborock_s8
vacuum_platform: humbertogontijo/homeassistant-roborock
two_finger_pan: true
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_clean_segment
    predefined_selections:
      - id: "16"
        icon:
          name: mdi:broom
          x: 23750
          "y": 24150
        label:
          text: Room 16
          x: 23750
          "y": 24150
          offset_y: 35
        outline:
          - - 21400
            - 22250
          - - 26100
            - 22250
          - - 26100
            - 26050
          - - 21400
            - 26050
      - id: "17"
        icon:
          name: mdi:broom
          x: 29425
          "y": 20100
        label:
          text: Room 17
          x: 29425
          "y": 20100
          offset_y: 35
        outline:
          - - 27600
            - 18100
          - - 31250
            - 18100
          - - 31250
            - 22100
          - - 27600
            - 22100
      - id: "18"
        icon:
          name: mdi:broom
          x: 33275
          "y": 19275
        label:
          text: Room 18
          x: 33275
          "y": 19275
          offset_y: 35
        outline:
          - - 31250
            - 18250
          - - 35300
            - 18250
          - - 35300
            - 20300
          - - 31250
            - 20300
      - id: "19"
        icon:
          name: mdi:broom
          x: 20500
          "y": 18000
        label:
          text: Room 19
          x: 20500
          "y": 18000
          offset_y: 35
        outline:
          - - 19850
            - 16400
          - - 21150
            - 16400
          - - 21150
            - 19600
          - - 19850
            - 19600
      - id: "20"
        icon:
          name: mdi:broom
          x: 28550
          "y": 24025
        label:
          text: Room 20
          x: 28550
          "y": 24025
          offset_y: 35
        outline:
          - - 26150
            - 22250
          - - 30950
            - 22250
          - - 30950
            - 25800
          - - 26150
            - 25800
      - id: "21"
        icon:
          name: mdi:broom
          x: 28025
          "y": 17050
        label:
          text: Room 21
          x: 28025
          "y": 17050
          offset_y: 35
        outline:
          - - 26100
            - 16050
          - - 29950
            - 16050
          - - 29950
            - 18050
          - - 26100
            - 18050
      - id: "22"
        icon:
          name: mdi:broom
          x: 26200
          "y": 20125
        label:
          text: Room 22
          x: 26200
          "y": 20125
          offset_y: 35
        outline:
          - - 24900
            - 18050
          - - 27500
            - 18050
          - - 27500
            - 22200
          - - 24900
            - 22200
      - id: "23"
        icon:
          name: mdi:broom
          x: 23075
          "y": 21300
        label:
          text: Room 23
          x: 23075
          "y": 21300
          offset_y: 35
        outline:
          - - 21300
            - 20550
          - - 24850
            - 20550
          - - 24850
            - 22050
          - - 21300
            - 22050
      - id: "24"
        icon:
          name: mdi:broom
          x: 25675
          "y": 19200
        label:
          text: Room 24
          x: 25675
          "y": 19200
          offset_y: 35
        outline:
          - - 25200
            - 17650
          - - 26150
            - 17650
          - - 26150
            - 20750
          - - 25200
            - 20750
      - id: "25"
        icon:
          name: mdi:broom
          x: 33450
          "y": 21275
        label:
          text: Room 25
          x: 33450
          "y": 21275
          offset_y: 35
        outline:
          - - 31550
            - 20350
          - - 35350
            - 20350
          - - 35350
            - 22200
          - - 31550
            - 22200
      - id: "26"
        icon:
          name: mdi:broom
          x: 23575
          "y": 18175
        label:
          text: Room 26
          x: 23575
          "y": 18175
          offset_y: 35
        outline:
          - - 21100
            - 16000
          - - 26050
            - 16000
          - - 26050
            - 20350
          - - 21100
            - 20350
      - id: "27"
        icon:
          name: mdi:broom
          x: 29575
          "y": 26550
        label:
          text: Room 27
          x: 29575
          "y": 26550
          offset_y: 35
        outline:
          - - 29000
            - 25900
          - - 30150
            - 25900
          - - 30150
            - 27200
          - - 29000
            - 27200
```
