### ISSUE TITLE
repeadatly generated room config attaches to another

### ISSUE THREAD

**Issue by Xyz00777** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#771]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

I found out that if I generate a room configuration and then do it again in another card, the generated room configuration becomes twice as long each time, and it keeps stacking further and further. The last room configuration I had generated turned an 8-line config into a repeating 8000-line config...
It looks for me like some kind of a browser cache bug, because when i strg + F5 the tab its looking normal again

### What version of a card has described problem?

2.2.4

### What vacuum model do you have problems with?

ViomiV6ValetudoRobot with valetudo

### Which integration do you use to control your vacuum (link)?

MQTT?

### What browser (browsers/apps) does have this problem?

firefox

### What version of Home Assistant do you use?

2024.10.4

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.valetudo_v6_bustlingflickeringgoose_camera
calibration_source:
  camera: true
entity: vacuum.valetudo_bustlingflickeringgoose
vacuum_platform: Hypfer/Valetudo
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_clean_segment
    predefined_selections:
      - id: "10"
        icon:
          name: mdi:broom
          x: 1792
          "y": 2110
        label:
          text: Küche
          x: 1792
          "y": 2110
          offset_y: 35
        outline:
          - - 1535
            - 1965
          - - 2050
            - 1965
          - - 2050
            - 2255
          - - 1535
            - 2255
      - id: "11"
        icon:
          name: mdi:broom
          x: 1282
          "y": 2197
        label:
          text: Bad
          x: 1282
          "y": 2197
          offset_y: 35
        outline:
          - - 1145
            - 2120
          - - 1420
            - 2120
          - - 1420
            - 2275
          - - 1145
            - 2275
      - id: "12"
        icon:
          name: mdi:broom
          x: 1800
          "y": 2425
        label:
          text: Schlafzimmer
          x: 1800
          "y": 2425
          offset_y: 35
        outline:
          - - 1565
            - 2255
          - - 2035
            - 2255
          - - 2035
            - 2595
          - - 1565
            - 2595
      - id: "13"
        icon:
          name: mdi:broom
          x: 1357
          "y": 2435
        label:
          text: Wohnzimmer
          x: 1357
          "y": 2435
          offset_y: 35
        outline:
          - - 1150
            - 2265
          - - 1565
            - 2265
          - - 1565
            - 2605
          - - 1150
            - 2605
      - id: "16"
        icon:
          name: mdi:broom
          x: 1480
          "y": 2195
        label:
          text: Flur
          x: 1480
          "y": 2195
          offset_y: 35
        outline:
          - - 1420
            - 2105
          - - 1540
            - 2105
          - - 1540
            - 2285
          - - 1420
            - 2285
  - template: vacuum_clean_segment
    predefined_selections:
      - id: "10"
        icon:
          name: mdi:broom
          x: 1792
          "y": 2110
        label:
          text: Küche
          x: 1792
          "y": 2110
          offset_y: 35
        outline:
          - - 1535
            - 1965
          - - 2050
            - 1965
          - - 2050
            - 2255
          - - 1535
            - 2255
      - id: "11"
        icon:
          name: mdi:broom
          x: 1282
          "y": 2197
        label:
          text: Bad
          x: 1282
          "y": 2197
          offset_y: 35
        outline:
          - - 1145
            - 2120
          - - 1420
            - 2120
          - - 1420
            - 2275
          - - 1145
            - 2275
      - id: "12"
        icon:
          name: mdi:broom
          x: 1800
          "y": 2425
        label:
          text: Schlafzimmer
          x: 1800
          "y": 2425
          offset_y: 35
        outline:
          - - 1565
            - 2255
          - - 2035
            - 2255
          - - 2035
            - 2595
          - - 1565
            - 2595
      - id: "13"
        icon:
          name: mdi:broom
          x: 1357
          "y": 2435
        label:
          text: Wohnzimmer
          x: 1357
          "y": 2435
          offset_y: 35
        outline:
          - - 1150
            - 2265
          - - 1565
            - 2265
          - - 1565
            - 2605
          - - 1150
            - 2605
      - id: "16"
        icon:
          name: mdi:broom
          x: 1480
          "y": 2195
        label:
          text: Flur
          x: 1480
          "y": 2195
          offset_y: 35
        outline:
          - - 1420
            - 2105
          - - 1540
            - 2105
          - - 1540
            - 2285
          - - 1420
            - 2285
  - template: vacuum_clean_segment
    predefined_selections:
      - id: "10"
        icon:
          name: mdi:broom
          x: 1792
          "y": 2110
        label:
          text: Küche
          x: 1792
          "y": 2110
          offset_y: 35
        outline:
          - - 1535
            - 1965
          - - 2050
            - 1965
          - - 2050
            - 2255
          - - 1535
            - 2255
      - id: "11"
        icon:
          name: mdi:broom
          x: 1282
          "y": 2197
        label:
          text: Bad
          x: 1282
          "y": 2197
          offset_y: 35
        outline:
          - - 1145
            - 2120
          - - 1420
            - 2120
          - - 1420
            - 2275
          - - 1145
            - 2275
      - id: "12"
        icon:
          name: mdi:broom
          x: 1800
          "y": 2425
        label:
          text: Schlafzimmer
          x: 1800
          "y": 2425
          offset_y: 35
        outline:
          - - 1565
            - 2255
          - - 2035
            - 2255
          - - 2035
            - 2595
          - - 1565
            - 2595
      - id: "13"
        icon:
          name: mdi:broom
          x: 1357
          "y": 2435
        label:
          text: Wohnzimmer
          x: 1357
          "y": 2435
          offset_y: 35
        outline:
          - - 1150
            - 2265
          - - 1565
            - 2265
          - - 1565
            - 2605
          - - 1150
            - 2605
      - id: "16"
        icon:
          name: mdi:broom
          x: 1480
          "y": 2195
        label:
          text: Flur
          x: 1480
          "y": 2195
          offset_y: 35
        outline:
          - - 1420
            - 2105
          - - 1540
            - 2105
          - - 1540
            - 2285
          - - 1420
            - 2285
  - template: vacuum_clean_segment
    predefined_selections:
      - id: "10"
        icon:
          name: mdi:broom
          x: 1792
          "y": 2110
        label:
          text: Küche
          x: 1792
          "y": 2110
          offset_y: 35
        outline:
          - - 1535
            - 1965
          - - 2050
            - 1965
          - - 2050
            - 2255
          - - 1535
            - 2255
      - id: "11"
        icon:
          name: mdi:broom
          x: 1282
          "y": 2197
        label:
          text: Bad
          x: 1282
          "y": 2197
          offset_y: 35
        outline:
          - - 1145
            - 2120
          - - 1420
            - 2120
          - - 1420
            - 2275
          - - 1145
            - 2275
      - id: "12"
        icon:
          name: mdi:broom
          x: 1800
          "y": 2425
        label:
          text: Schlafzimmer
          x: 1800
          "y": 2425
          offset_y: 35
        outline:
          - - 1565
            - 2255
          - - 2035
            - 2255
          - - 2035
            - 2595
          - - 1565
            - 2595
      - id: "13"
        icon:
          name: mdi:broom
          x: 1357
          "y": 2435
        label:
          text: Wohnzimmer
          x: 1357
          "y": 2435
          offset_y: 35
        outline:
          - - 1150
            - 2265
          - - 1565
            - 2265
          - - 1565
            - 2605
          - - 1150
            - 2605
      - id: "16"
        icon:
          name: mdi:broom
          x: 1480
          "y": 2195
        label:
          text: Flur
          x: 1480
          "y": 2195
          offset_y: 35
        outline:
          - - 1420
            - 2105
          - - 1540
            - 2105
          - - 1540
            - 2285
          - - 1420
            - 2285
  - template: vacuum_clean_segment
    predefined_selections:
      - id: "10"
        icon:
          name: mdi:broom
          x: 1792
          "y": 2110
        label:
          text: Küche
          x: 1792
          "y": 2110
          offset_y: 35
        outline:
          - - 1535
            - 1965
          - - 2050
            - 1965
          - - 2050
            - 2255
          - - 1535
            - 2255
      - id: "11"
        icon:
          name: mdi:broom
          x: 1282
          "y": 2197
        label:
          text: Bad
          x: 1282
          "y": 2197
          offset_y: 35
        outline:
          - - 1145
            - 2120
          - - 1420
            - 2120
          - - 1420
            - 2275
          - - 1145
            - 2275
      - id: "12"
        icon:
          name: mdi:broom
          x: 1800
          "y": 2425
        label:
          text: Schlafzimmer
          x: 1800
          "y": 2425
          offset_y: 35
        outline:
          - - 1565
            - 2255
          - - 2035
            - 2255
          - - 2035
            - 2595
          - - 1565
            - 2595
      - id: "13"
        icon:
          name: mdi:broom
          x: 1357
          "y": 2435
        label:
          text: Wohnzimmer
          x: 1357
          "y": 2435
          offset_y: 35
        outline:
          - - 1150
            - 2265
          - - 1565
            - 2265
          - - 1565
            - 2605
          - - 1150
            - 2605
      - id: "16"
        icon:
          name: mdi:broom
          x: 1480
          "y": 2195
        label:
          text: Flur
          x: 1480
          "y": 2195
          offset_y: 35
        outline:
          - - 1420
            - 2105
          - - 1540
            - 2105
          - - 1540
            - 2285
          - - 1420
            - 2285
  - template: vacuum_clean_segment
    predefined_selections:
      - id: "10"
        icon:
          name: mdi:broom
          x: 1792
          "y": 2110
        label:
          text: Küche
          x: 1792
          "y": 2110
          offset_y: 35
        outline:
          - - 1535
            - 1965
          - - 2050
            - 1965
          - - 2050
            - 2255
          - - 1535
            - 2255
      - id: "11"
        icon:
          name: mdi:broom
          x: 1282
          "y": 2197
        label:
          text: Bad
          x: 1282
          "y": 2197
          offset_y: 35
        outline:
          - - 1145
            - 2120
          - - 1420
            - 2120
          - - 1420
            - 2275
          - - 1145
            - 2275
      - id: "12"
        icon:
          name: mdi:broom
          x: 1800
          "y": 2425
        label:
          text: Schlafzimmer
          x: 1800
          "y": 2425
          offset_y: 35
        outline:
          - - 1565
            - 2255
          - - 2035
            - 2255
          - - 2035
            - 2595
          - - 1565
            - 2595
      - id: "13"
        icon:
          name: mdi:broom
          x: 1357
          "y": 2435
        label:
          text: Wohnzimmer
          x: 1357
          "y": 2435
          offset_y: 35
        outline:
          - - 1150
            - 2265
          - - 1565
            - 2265
          - - 1565
            - 2605
          - - 1150
            - 2605
      - id: "16"
        icon:
          name: mdi:broom
          x: 1480
          "y": 2195
        label:
          text: Flur
          x: 1480
          "y": 2195
          offset_y: 35
        outline:
          - - 1420
            - 2105
          - - 1540
            - 2105
          - - 1540
            - 2285
          - - 1420
            - 2285
  - template: vacuum_clean_segment
    predefined_selections:
      - id: "10"
        icon:
          name: mdi:broom
          x: 1792
          "y": 2110
        label:
          text: Küche
          x: 1792
          "y": 2110
          offset_y: 35
        outline:
          - - 1535
            - 1965
          - - 2050
            - 1965
          - - 2050
            - 2255
          - - 1535
            - 2255
      - id: "11"
        icon:
          name: mdi:broom
          x: 1282
          "y": 2197
        label:
          text: Bad
          x: 1282
          "y": 2197
          offset_y: 35
        outline:
          - - 1145
            - 2120
          - - 1420
            - 2120
          - - 1420
            - 2275
          - - 1145
            - 2275
      - id: "12"
        icon:
          name: mdi:broom
          x: 1800
          "y": 2425
        label:
          text: Schlafzimmer
          x: 1800
          "y": 2425
          offset_y: 35
        outline:
          - - 1565
            - 2255
          - - 2035
            - 2255
          - - 2035
            - 2595
          - - 1565
            - 2595
      - id: "13"
        icon:
          name: mdi:broom
          x: 1357
          "y": 2435
        label:
          text: Wohnzimmer
          x: 1357
          "y": 2435
          offset_y: 35
        outline:
          - - 1150
            - 2265
          - - 1565
            - 2265
          - - 1565
            - 2605
          - - 1150
            - 2605
      - id: "16"
        icon:
          name: mdi:broom
          x: 1480
          "y": 2195
        label:
          text: Flur
          x: 1480
          "y": 2195
          offset_y: 35
        outline:
          - - 1420
            - 2105
          - - 1540
            - 2105
          - - 1540
            - 2285
          - - 1420
            - 2285
  - template: vacuum_clean_segment
    predefined_selections:
      - id: "10"
        icon:
          name: mdi:broom
          x: 1792
          "y": 2110
        label:
          text: Küche
          x: 1792
          "y": 2110
          offset_y: 35
        outline:
          - - 1535
            - 1965
          - - 2050
            - 1965
          - - 2050
            - 2255
          - - 1535
            - 2255
      - id: "11"
        icon:
          name: mdi:broom
          x: 1282
          "y": 2197
        label:
          text: Bad
          x: 1282
          "y": 2197
          offset_y: 35
        outline:
          - - 1145
            - 2120
          - - 1420
            - 2120
          - - 1420
            - 2275
          - - 1145
            - 2275
      - id: "12"
        icon:
          name: mdi:broom
          x: 1800
          "y": 2425
        label:
          text: Schlafzimmer
          x: 1800
          "y": 2425
          offset_y: 35
        outline:
          - - 1565
            - 2255
          - - 2035
            - 2255
          - - 2035
            - 2595
          - - 1565
            - 2595
      - id: "13"
        icon:
          name: mdi:broom
          x: 1357
          "y": 2435
        label:
          text: Wohnzimmer
          x: 1357
          "y": 2435
          offset_y: 35
        outline:
          - - 1150
            - 2265
          - - 1565
            - 2265
          - - 1565
            - 2605
          - - 1150
            - 2605
      - id: "16"
        icon:
          name: mdi:broom
          x: 1480
          "y": 2195
        label:
          text: Flur
          x: 1480
          "y": 2195
          offset_y: 35
        outline:
          - - 1420
            - 2105
          - - 1540
            - 2105
          - - 1540
            - 2285
          - - 1420
            - 2285
```
