### ISSUE TITLE
Valetudo not working for rooms/zones?

### ISSUE THREAD

**Issue by borgqueenx** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#778]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

I am using the map card, selected valetudo as platform and the device and camera (mqtt vacuum camera), then click on create room configuration and save.
However, i cant start cleaning a zone or room with the play/ button next to it. the robot wont do any work or confirm anything.
If i click the normal start button (that changes to pause when clicked) the robot starts working, but that command is for a full house cleaning, i think? The map also works fine, i see the robot moving.

The device i flashed valetudo on is a dreame x40 ultra and is added as a MQTT device in home assistant.

Perhaps and hopefully this is solvable by changing something, but maybe the auto-configuration maker needs some editting to solve this bug. (if it is a bug, i think so)

### What version of a card has described problem?

v2.2.4

### What vacuum model do you have problems with?

valetudo dreame x40

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/mqtt/

### What browser (browsers/apps) does have this problem?

all

### What version of Home Assistant do you use?

2024.11.3

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.valetudo_x40_ultra_occasionalmurkyguanaco_camera
calibration_source:
  camera: true
entity: vacuum.valetudo_occasionalmurkyguanaco
vacuum_platform: Hypfer/Valetudo
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_clean_segment
    predefined_selections:
      - id: "1"
        icon:
          name: mdi:broom
          x: 3200
          "y": 1952
        label:
          text: Naelis Room
          x: 3200
          "y": 1952
          offset_y: 35
        outline:
          - - 3035
            - 1755
          - - 3365
            - 1755
          - - 3365
            - 2150
          - - 3035
            - 2150
      - id: "2"
        icon:
          name: mdi:broom
          x: 3157
          "y": 2230
        label:
          text: Hallway Bathroom
          x: 3157
          "y": 2230
          offset_y: 35
        outline:
          - - 3050
            - 2160
          - - 3265
            - 2160
          - - 3265
            - 2300
          - - 3050
            - 2300
      - id: "3"
        icon:
          name: mdi:broom
          x: 3330
          "y": 2345
        label:
          text: Hallway
          x: 3330
          "y": 2345
          offset_y: 35
        outline:
          - - 3040
            - 2130
          - - 3620
            - 2130
          - - 3620
            - 2560
          - - 3040
            - 2560
      - id: "4"
        icon:
          name: mdi:broom
          x: 3737
          "y": 2340
        label:
          text: Entrance
          x: 3737
          "y": 2340
          offset_y: 35
        outline:
          - - 3620
            - 2135
          - - 3855
            - 2135
          - - 3855
            - 2545
          - - 3620
            - 2545
      - id: "6"
        icon:
          name: mdi:broom
          x: 3662
          "y": 2715
        label:
          text: Billiard Room
          x: 3662
          "y": 2715
          offset_y: 35
        outline:
          - - 3455
            - 2540
          - - 3870
            - 2540
          - - 3870
            - 2890
          - - 3455
            - 2890
      - id: "7"
        icon:
          name: mdi:broom
          x: 2662
          "y": 3060
        label:
          text: Master Bathroom
          x: 2662
          "y": 3060
          offset_y: 35
        outline:
          - - 2595
            - 2930
          - - 2730
            - 2930
          - - 2730
            - 3190
          - - 2595
            - 3190
      - id: "8"
        icon:
          name: mdi:broom
          x: 3677
          "y": 3042
        label:
          text: Kitchen
          x: 3677
          "y": 3042
          offset_y: 35
        outline:
          - - 3490
            - 2870
          - - 3865
            - 2870
          - - 3865
            - 3215
          - - 3490
            - 3215
      - id: "9"
        icon:
          name: mdi:broom
          x: 2417
          "y": 3147
        label:
          text: Bedroom
          x: 2417
          "y": 3147
          offset_y: 35
        outline:
          - - 2085
            - 2930
          - - 2750
            - 2930
          - - 2750
            - 3365
          - - 2085
            - 3365
      - id: "10"
        icon:
          name: mdi:broom
          x: 2892
          "y": 3140
        label:
          text: PC Corner
          x: 2892
          "y": 3140
          offset_y: 35
        outline:
          - - 2745
            - 2915
          - - 3040
            - 2915
          - - 3040
            - 3365
          - - 2745
            - 3365
      - id: "12"
        icon:
          name: mdi:broom
          x: 3240
          "y": 2955
        label:
          text: Living Room
          x: 3240
          "y": 2955
          offset_y: 35
        outline:
          - - 3030
            - 2535
          - - 3450
            - 2535
          - - 3450
            - 3375
          - - 3030
            - 3375
      - id: "13"
        icon:
          name: mdi:broom
          x: 3690
          "y": 3292
        label:
          text: Kitchen Side
          x: 3690
          "y": 3292
          offset_y: 35
        outline:
          - - 3515
            - 3195
          - - 3865
            - 3195
          - - 3865
            - 3390
          - - 3515
            - 3390
```
