### ISSUE TITLE
Multi Floor Support

### ISSUE THREAD

**Issue by Tmatz27** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#780]
### Description

The current system does well handling when i switch the floor that the vacuum is on. The issue is i have to use a different card to switch the floor or use the vacuum app. Additionally is there a way to generate rooms for a multi-floor? 

### Solution

It would be amazing to have this integrated with a simple button or like a floor number (1,2,3) on the side of the card to change the floor to clean.

Adding the ability to generate rooms for a multi floor config.

**Comment by PiotrMachowski** [comment]
Have you checked out `additional_presets` config?

**Comment by Tmatz27** [comment]
I did! but this doesnt really get after what I was looking for. My vacuum supports multiple floors. I currently have to have an additional card to switch the floor that my vacuum is on. It works but would be amazing if there was a simple numbering on the vacuum card itself to simply select the floor i want the vacuum on. Also the ability to generate rooms for more than a single floor would be great!
![Screenshot 2024-12-11 140547](https://github.com/user-attachments/assets/c5f31c15-cfee-4c9f-a17f-8e6c7e50f8e0)

**Comment by PiotrMachowski** [comment]
Do you have a select entity for that changes the active floor?

**Comment by Tmatz27** [comment]
Yes the vacuum I have had an entity that allows me to change that so I created a drop-down card for it currently.
![Screenshot_20241211_215231_Home Assistant](https://github.com/user-attachments/assets/9353e7b6-6ca5-4dab-aaf7-98597be46388)
![Screenshot_20241211_215224_Home Assistant](https://github.com/user-attachments/assets/97f455bc-4f39-4606-9b34-ebad6568e06c)

**Comment by PiotrMachowski** [comment]
Add this to your config:
```yaml
append_icons: true
icons:
  - type: "menu"
    menu_id: "selected_map"
    icon_id: "selected_map"
    entity: "select.rosie_selected_map"
    available_values_attribute: "options"
    icon: "mdi:map"
    tap_action:
        action: "call-service"
        service: "select.select_option"
        service_data:
            option: "[[value]]"
            entity_id: "[[entity_id]]"
```
