### ISSUE TITLE
Cleaning mode and water level in map card

### ISSUE THREAD

**Issue by mkaflowski** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#784]
### Description

I cannot find cleaning mode and water level in map card.
Now I need to add second entity like that:

![Zrzut ekranu 2024-12-17 o 15 26 18](https://github.com/user-attachments/assets/a7f6394a-3ff5-416f-8db8-2ab62d7aa549)

### Solution

Adding option similar to suction power.

**Comment by remydumont** [comment]
Hi, I approve of this request, it is a useful feature for robots equipped with mops.

**Comment by Oleg-Yu** [comment]
I have Xiaomi X20+ and will be great to have 4h button with cleaning mode in this awesome lovelace card.
temporary add tile on card with code:
  - tile_id: cleaning_mode
    entity: vacuum.xiaomi_x20
    label: Режим прибирання
    attribute: cleaning_mode
    icon: mdi:broom
    tap_action:
        action: call-service
        service: select.select_next
        service_data:
            entity_id: select.xiaomi_x20_cleaning_mode
    translations:
        sweeping: Підмітання
        mopping: Миття
        sweeping and mopping: Підмітання та миття
        mopping after sweeping: Миття після підмітання

![Image](https://github.com/user-attachments/assets/dfc7e7a4-500e-48a3-b462-0ec737834adc)

**Comment by remydumont** [comment]
@Oleg-Yu Thanks, very useful. I was able to add tiles and icons menu for select cleaning mode and mop pad humidity.

**Comment by Oleg-Yu** [comment]
@remydumont  how did you add icons menu. share a yaml code

**Comment by PiotrMachowski** [comment]
@Oleg-Yu it's in the docs
https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card?tab=readme-ov-file#menu-icon-additional-options

**Comment by remydumont** [comment]
I just copy the code for fan-speed menu and change data inside:
``` yaml
 - menu_id: cleaning_mode
    icon: mdi:broom
    label: Aspiration
    conditions:
      - entity: vacuum.xiaomi_robot_vacuum_x20
        attribute: cleaning_mode
        value: Sweeping
    tooltip: Changer le mode de nettoyage
    tap_action:
      action: call-service
      service: select.select_option
      service_data:
        entity_id: select.xiaomi_robot_vacuum_x20_cleaning_mode
        option: sweeping
  - menu_id: cleaning_mode
    icon: mdi:cup-water
    label: Lavage
    conditions:
      - entity: vacuum.xiaomi_robot_vacuum_x20
        attribute: cleaning_mode
        value: Mopping
    tooltip: Changer le mode de nettoyage
    tap_action:
      action: call-service
      service: select.select_option
      service_data:
        entity_id: select.xiaomi_robot_vacuum_x20_cleaning_mode
        option: mopping
  - menu_id: cleaning_mode
    icon: mdi:hydro-power
    label: Aspiration et lavage
    conditions:
      - entity: vacuum.xiaomi_robot_vacuum_x20
        attribute: cleaning_mode
        value: Sweeping and mopping
    tooltip: Changer le mode de nettoyage
    tap_action:
      action: call-service
      service: select.select_option
      service_data:
        entity_id: select.xiaomi_robot_vacuum_x20_cleaning_mode
        option: sweeping_and_mopping
  - menu_id: cleaning_mode
    icon: mdi:water-polo
    label: Lavage après aspiration
    conditions:
      - entity: vacuum.xiaomi_robot_vacuum_x20
        attribute: cleaning_mode
        value: Mopping after sweeping
    tooltip: Changer le mode de nettoyage
    tap_action:
      action: call-service
      service: select.select_option
      service_data:
        entity_id: select.xiaomi_robot_vacuum_x20_cleaning_mode
        option: mopping_after_sweeping
```

And same for mop pad humidity, with conditions to not show the menu if mopping is disable


``` yaml
  - menu_id: mop_pad_humidity
    icon: mdi:water-minus
    label: Légèrement sec
    conditions:
      - entity: vacuum.xiaomi_robot_vacuum_x20
        attribute: mop_pad_humidity
        value: Slightly dry
      - entity: vacuum.xiaomi_robot_vacuum_x20
        attribute: cleaning_mode
        value_not: Sweeping
    tooltip: Changer humidité
    tap_action:
      action: call-service
      service: select.select_option
      service_data:
        entity_id: select.xiaomi_robot_vacuum_x20_mop_pad_humidity
        option: slightly_dry
  - menu_id: mop_pad_humidity
    icon: mdi:water
    label: Humide
    conditions:
      - entity: vacuum.xiaomi_robot_vacuum_x20
        attribute: mop_pad_humidity
        value: Moist
      - entity: vacuum.xiaomi_robot_vacuum_x20
        attribute: cleaning_mode
        value_not: Sweeping
    tooltip: Changer humidité
    tap_action:
      action: call-service
      service: select.select_option
      service_data:
        entity_id: select.xiaomi_robot_vacuum_x20_mop_pad_humidity
        option: moist
  - menu_id: mop_pad_humidity
    icon: mdi:water-plus
    label: Mouillé
    conditions:
      - entity: vacuum.xiaomi_robot_vacuum_x20
        attribute: mop_pad_humidity
        value: Wet
      - entity: vacuum.xiaomi_robot_vacuum_x20
        attribute: cleaning_mode
        value_not: Sweeping
    tooltip: Changer humidité
    tap_action:
      action: call-service
      service: select.select_option
      service_data:
        entity_id: select.xiaomi_robot_vacuum_x20_mop_pad_humidity
        option: wet
```
