### ISSUE TITLE
Can't select any rooms

### ISSUE THREAD

**Issue by spanky59** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#790]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Hello,
First, thanks for your job this card seem very nice !

But I've encounter a problem. Room seem well detected when I choice "generate rooms config" but rooms icons are note displayed and, can't clic/select any one of them.
Zone selection or Pin & Go seem works.

I've check and check again the card configuration I can't find what's wrong.

![image](https://github.com/user-attachments/assets/b2fdc950-975f-4d64-914b-6210784552b9)

### What version of a card has described problem?

v2.2.4

### What vacuum model do you have problems with?

valetudo dreame F9

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/mqtt/

### What browser (browsers/apps) does have this problem?

Chome/Compagnon application

### What version of Home Assistant do you use?

2024.12.5

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.cyclope_camera
calibration_source:
  identity: true
entity: vacuum.valetudo_cyclope
vacuum_platform: Hypfer/Valetudo
internal_variables:
  topic: valetudo/cyclope
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_clean_segment
    predefined_selections:
      - id: "1"
        icon:
          name: mdi:broom
          x: 3227
          "y": 3417
        label:
          text: Cuisine
          x: 3227
          "y": 3417
          offset_y: 35
        outline:
          - - 3140
            - 3240
          - - 3315
            - 3240
          - - 3315
            - 3595
          - - 3140
            - 3595
      - id: "2"
        icon:
          name: mdi:broom
          x: 3387
          "y": 3747
        label:
          text: Salon
          x: 3387
          "y": 3747
          offset_y: 35
        outline:
          - - 3095
            - 3570
          - - 3680
            - 3570
          - - 3680
            - 3925
          - - 3095
            - 3925
      - id: "3"
        icon:
          name: mdi:broom
          x: 3407
          "y": 4037
        label:
          text: Extension
          x: 3407
          "y": 4037
          offset_y: 35
        outline:
          - - 3130
            - 3905
          - - 3685
            - 3905
          - - 3685
            - 4170
          - - 3130
            - 4170
```
