### ISSUE TITLE
Invalid configuration sometimes appears - sometimes not

### ISSUE THREAD

**Issue by DeckardCain2014** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#792]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

With the following config, sometimes I get an 'invalid configuration' error resulting in an unusable map. 
However, when starting the robot manually, which updates the map for the camera entity, it works again.
Mostly this appears when not using the map for a longer time or starting the robot via script in between.
Is there any way to check WHAT exactly is wrong in the calibration / configuration?
```
- type: custom:xiaomi-vacuum-map-card
    map_source:
      camera: camera.moppie_map
    calibration_source:
      camera: true
    entity: vacuum.moppie
    vacuum_platform: Tasshack/dreame-vacuum
    title: EG
    map_modes:
      - template: vacuum_clean_zone
      - template: vacuum_clean_point
      - template: vacuum_clean_segment
        predefined_selections:
          - id: "1"
            icon:
              name: mdi:home-outline
              x: 950
              "y": 10200
            label:
              text: Draußen
              x: 950
              "y": 10200
              offset_y: 35
            outline:
              - - -1550
                - 7850
              - - 2900
                - 7850
              - - 2900
                - 12550
              - - -1550
                - 12550
          - id: "2"
            icon:
              name: mdi:home-outline
              x: 1000
              "y": 5650
            label:
              text: Küche
              x: 1000
              "y": 5650
              offset_y: 35
            outline:
              - - -800
                - 3400
              - - 3000
                - 3400
              - - 3000
                - 7850
              - - -800
                - 7850
          - id: "3"
            icon:
              name: mdi:home-outline
              x: 5300
              "y": 3100
            label:
              text: Wohnzimmer
              x: 5300
              "y": 3100
              offset_y: 35
            outline:
              - - 3000
                - 350
              - - 11600
                - 350
              - - 11600
                - 7750
              - - 3000
                - 7750
          - id: "4"
            icon:
              name: mdi:home-outline
              x: 1050
              "y": 1900
            label:
              text: Flur
              x: 1050
              "y": 1900
              offset_y: 35
            outline:
              - - -850
                - -750
              - - 3000
                - -750
              - - 3000
                - 3200
              - - -850
                - 3200
          - id: "5"
            icon:
              name: mdi:home-outline
              x: 900
              "y": -2000
            label:
              text: Technikraum
              x: 900
              "y": -2000
              offset_y: 35
            outline:
              - - -250
                - -3200
              - - 2050
                - -3200
              - - 2050
                - -750
              - - -250
                - -750
          - id: "6"
            icon:
              name: mdi:home-outline
              x: 10250
              "y": -1300
            label:
              text: Gästezimmer
              x: 10250
              "y": -1300
              offset_y: 35
            outline:
              - - 8800
                - -3100
              - - 11750
                - -3100
              - - 11750
                - 450
              - - 8800
                - 450
          - id: "7"
            icon:
              name: mdi:home-outline
              x: 3050
              "y": -1400
            label:
              text: Gästebad
              x: 3050
              "y": -1400
              offset_y: 35
            outline:
              - - 900
                - -3150
              - - 4700
                - -3150
              - - 4700
                - 650
              - - 900
                - 650
          - id: "8"
            icon:
              name: mdi:home-outline
              x: 6600
              "y": -1350
            label:
              text: Fitness
              x: 6600
              "y": -1350
              offset_y: 35
            outline:
              - - 3850
                - -3200
              - - 8600
                - -3200
              - - 8600
                - 500
              - - 3850
                - 500
      - template: vacuum_clean_zone_predefined
        predefined_selections:
          - zones:
              - - 2992
                - 366
                - 5206
                - 5463
              - - 5234
                - 298
                - 7459
                - 1806
              - - 5203
                - 4398
                - 7461
                - 5589
              - - 6728
                - 1792
                - 7555
                - 4349
              - - 7491
                - 965
                - 9717
                - 1552
            icon:
              name: mdi:toilet
              x: 5655
              "y": 1061
```

### What version of a card has described problem?

v2.2.4

### What vacuum model do you have problems with?

Xiaomi X10 Plus

### Which integration do you use to control your vacuum (link)?

https://github.com/Tasshack/dreame-vacuum

### What browser (browsers/apps) does have this problem?

Chrome/HA Android app

### What version of Home Assistant do you use?

2025.1.0

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
see above
```
