### ISSUE TITLE
Honiture Q6 Pro

### ISSUE THREAD

**Issue by enrico-stronati** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#796]
### Integration repository

https://www.home-assistant.io/integrations/xiaomi_miio/

### Supported features

- [x] Zone cleaning (using 4 coordinates)
- [x] Room cleaning (using room id/number)
- [x] Going to point (using 2 coordinates)
- [x] Cleaning a point (using 2 coordinates)
- [ ] Others

### Checklist

- [x] I have sent info about entities to `piotr.machowski.dev [at] gmail.com` ([Retrieving entities info](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/594); please provide your GitHub username in the email)

### Vacuum entity/entities

```yaml
fan_speed_list:
  - quiet
  - auto
  - strong
  - max
battery_level: 100
battery_icon: mdi:battery
fan_speed: auto
cleaning_mode_list:
  - smart
  - pose
  - zone
  - backcharge
  - curpointing
  - selectroom
  - "null"
cleaning_mode: "null"
clean_time: 257867
clean_area: 4896
clean_record: 174
fault: 0
icon: ""
friendly_name: Q6 Pro Robot
supported_features: 13052
```

### Service calls

```yaml
vacuum.clean_spot
vacuum.locate
vacuum.pause
vacuum.return_to_base
vacuum.send_command
vacuum.set_fan_spend
vacuum.start
vacuum.stop
```

### Other info

Hi, I am trying to integrate other commands, for instance: clena a point or clean an area.
I didn'find a model in the integration (vacuum plataform list) that works with my robot.
If you want, I could try to indagate how to have more information, but to do it I meed to have some information about how-to. 
Regards.
