### ISSUE TITLE
Can Not  Select  a map with Xiaomi Vacuum Card and Dreame Integration

### ISSUE THREAD

**Issue by BinGor2010** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#802]
### Checklist

- [x] I have updated the card to the latest version available
- [x] I have cleared the cache of my browser
- [x] I have checked if the problem is already reported

### The problem

Hey All, 

I’m new here and Home Assistant. 
I will use HA for my Dreame x40. 

I have two Problems at the Moment.

1. My Button to Select a map is grayed out. I don‘t know why. Maybe with the last update? 
HA reports that this attribute is no longer available. In other words, it no longer receives any data. 

2. My room config has  Problems when the map is changed.
    For example: from the 1.St. floor to the 2.nd floor. And now I will only clean one room, but    
    i see  room Lines from floor bevor the map is changed. 

According to the room config, only the rooms on the 1st floor are included, but Not from the 2.nd or 3.rd floor.  I have no idea how to add the rooms on the two floors, as I don't know the IDs or the coordinates. 

I have tried to explain this here, but I don't understand where and what exactly. 
https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/317
According to HA, the service “xiaomi_cloud_map_extractor.reload” does not exist. 

Can me help anyone? 

I do use it:
Lovelace Vacuum Map card2.2.4
DREAME 2.0.0b16 integration 

Greetings

### What version of a card has described problem?

2.2.4

### What vacuum model do you have problems with?

Dreame x40

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

IOS App

### What version of Home Assistant do you use?

2025.2.1

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.x40_map
calibration_source:
  camera: true
entity: vacuum.x40
vacuum_platform: Tasshack/dreame-vacuum
grid_options:
  columns: 24
  rows: auto
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_point
  - template: vacuum_clean_segment
    predefined_selections:
      - id: "1"
        icon:
          name: mdi:chef-hat
          x: 1200
          "y": 1600
        label:
          text: Kitchen
          x: 1200
          "y": 1600
          offset_y: 35
        outline:
          - - -150
            - -500
          - - 1800
            - -500
          - - 1800
            - 3150
          - - -150
            - 3150
      - id: "2"
        icon:
          name: mdi:foot-print
          x: -1200
          "y": 1650
        label:
          text: Corridor
          x: -1200
          "y": 1650
          offset_y: 35
        outline:
          - - -2300
            - -750
          - - -300
            - -750
          - - -300
            - 3900
          - - -2300
            - 3900
      - id: "3"
        icon:
          name: mdi:home-outline
          x: 100
          "y": -3850
        label:
          text: Wohn
          x: 100
          "y": -3850
          offset_y: 35
        outline:
          - - -2400
            - -7150
          - - 2300
            - -7150
          - - 2300
            - -500
          - - -2400
            - -500
      - id: "5"
        icon:
          name: mdi:home-outline
          x: -2400
          "y": 2800
        label:
          text: WC
          x: -2400
          "y": 2800
          offset_y: 35
        outline:
          - - -2850
            - 2050
          - - -1800
            - 2050
          - - -1800
            - 3500
          - - -2850
            - 3500
```

### Javascript errors shown in the browser's console (if applicable)

```shell

```
