### ISSUE TITLE
How to set zones for Deebot

### ISSUE THREAD

**Issue by dllfpp** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#806]
### Checklist

- [x] I have updated the card to the latest version available
- [x] I have cleared the cache of my browser
- [x] I have checked if the problem is already reported

### The problem

Hello, this is more of a distress call than an issue report, sorry.
I have this as my setup:

![Image](https://github.com/user-attachments/assets/634382b7-2cdb-4d17-ac63-ef632300c4aa)

![Image](https://github.com/user-attachments/assets/6e831392-00ad-4ce5-b8d2-3e84fcfa743e)

How can I link these attributes, which reflect my zones in the app, in the card so that if I chose the zone it automatically binds the corresponding area?

![Image](https://github.com/user-attachments/assets/f1950c7f-5dcb-4de1-a404-d05cfb5d82c1)
I know already which room is which zone in my house so it's not a problem matching them accordingly.

### What version of a card has described problem?

2.2.4

### What vacuum model do you have problems with?

DEEBOT N8 PRO+ (ifbw08)

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/ecovacs

### What browser (browsers/apps) does have this problem?

Edge/iOS app/Firefox

### What version of Home Assistant do you use?

core-2025.3.1

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
language: it
entity: vacuum.cenerentola
vacuum_platform: DeebotUniverse/Deebot-4-Home-Assistant
map_source:
  camera: image.cenerentola_map
map_locked: true
two_finger_pan: true
map_modes:
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 0
        icon:
          name: mdi:door
          label: Ingresso/Corridoio
          x: -8500
          "y": -11500
      - id: 1
        icon:
          name: mdi:knife
          label: Cucina
          x: -1000
          "y": -15000
      - id: 2
        icon:
          name: mdi:sofa
          label: Salotto
          x: -2900
          "y": -3000
      - id: 3
        icon:
          name: mdi:table-chair
          label: Sala da pranzo
          x: -2900
          "y": -9000
      - id: 4
        icon:
          name: mdi:bed
          label: Camera
          x: -15200
          "y": 0
      - id: 5
        icon:
          name: mdi:bed
          label: Cameretta
          x: -15200
          "y": -9000
      - id: 6
        icon:
          name: mdi:toilet
          label: Bagno Padronale
          x: -9000
          "y": 2200
      - id: 6
        icon:
          name: mdi:toilet
          label: Bagno Ospiti
          x: -17000
          "y": -14700
  - template: vacuum_clean_zone
  - template: vacuum_clean_zone_predefined
    predefined_selections:
      - zones:
          - - 239
            - 184
            - 1336
            - 665
        icon:
          name: mdi:rectangle
          x: -8500
          "y": -11500
```

### Javascript errors shown in the browser's console (if applicable)

```shell

```
