### ISSUE TITLE
Different map scale?

### ISSUE THREAD

**Issue by INPoppoRTUNE** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#813]
### Checklist

- [x] I have updated the card to the latest version available
- [x] I have cleared the cache of my browser
- [x] I have checked if the problem is already reported

### The problem

Map items, such as icons, appears in different spots when loading the map from different devices.
I attempted a manual [map calibration](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/wiki/Map-calibration-in-FloleVac) using [this function](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/318) to obtain the card's coordinates and Gimp to obtain the screenshot's coordinates.
### Laptop view

![Image](https://github.com/user-attachments/assets/de9fa12a-041b-49a0-a055-11c98680ee91)

### Companion app view (Android)

![Image](https://github.com/user-attachments/assets/1a185285-ae04-44f7-be5e-7a361714e5b4)

### What version of a card has described problem?

v2.2.4

### What vacuum model do you have problems with?

Ecovacs Deebot X1 OMNI

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/ecovacs/

### What browser (browsers/apps) does have this problem?

Firefox and Companion App

### What version of Home Assistant do you use?

2025.3.4

### What type of installation are you running?

Home Assistant Supervised

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.alfred
vacuum_platform: DeebotUniverse/Deebot-4-Home-Assistant
language: it
map_source:
  camera: image.alfred_map
map_locked: true
two_finger_pan: true
draw:
  - all
attributes:
  - rooms
debug: true
calibration_points:
  - vacuum:
      x: -19859
      "y": -19975
    map:
      x: 0
      "y": 0
  - vacuum:
      x: -14227
      "y": -12534
    map:
      x: 1045
      "y": 1340
  - vacuum:
      x: -19859
      "y": -12534
    map:
      x: 0
      "y": 1340
card_mod:
  style: |
    ha-card {
      --map-card-zoomer-background: rgba(155, 130, 131, 0.8);
      --map-card-room-outline-line-color: red;
      --map-card-room-outline-fill-color: rgba(255, 122, 122, 0.2);
    }
map_modes:
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 0
        icon:
          name: mdi:toilet
          label: Bagno
          x: -9000
          "y": -12500
      - id: 1
        icon:
          name: mdi:air-conditioner
          label: Corridoio
          x: -8500
          "y": -6000
      - id: 2
        icon:
          name: mdi:bed-double-outline
          x: -15900
          "y": 4000
          label:
            text: Salotto
            offset_y: 50
      - id: 4
        icon:
          name: mdi:toilet
          label: Bagno
          x: -15900
          "y": -4500
      - id: 5
        icon:
          name: mdi:bed
          label: Cameretta
          x: -19000
          "y": -19000
      - id: 6
        icon:
          name: mdi:silverware-fork-knife
          label: Cucina
          x: -8000
          "y": 4000
          outline:
            - - -19967
              - -19950
            - - -11183
              - -5900
      - id: 7
        icon:
          name: mdi:sofa-outline
          label: Salotto
          x: -1300
          "y": -9000
  - template: vacuum_clean_zone
  - template: vacuum_clean_zone_predefined
    predefined_selections:
      - zones:
          - - 239
            - 184
            - 1336
            - 665
        icon:
          name: mdi:rectangle
          x: -8000
          "y": 4000
```

### Javascript errors shown in the browser's console (if applicable)

```shell

```

### Additional information

If I try to add a zone to clean from the laptop it return:
```yaml
{
  "domain": "vacuum",
  "service": "send_command",
  "serviceData": {
    "entity_id": "vacuum.alfred",
    "command": "custom_area",
    "params": {
      "coordinates": "null,null,null,null"
    }
  }
}
```
With an inamovible rectangle stuck in the top right angle.
Works flawlessly on companion app.
