### ISSUE TITLE
Roborock core and - template: vacuum_clean_zone

### ISSUE THREAD

**Issue by poudenes** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#818]
### Checklist

- [x] I have updated the card to the latest version available
- [x] I have cleared the cache of my browser
- [x] I have checked if the problem is already reported

### The problem

Hi All,

Almost everything is working with core integration of Roborock. But vacuum_clean_zone is not working for me.
When I create a zone it is going to an other room to clean. Room cleaning works great so it's not a coordination problem I guess.

### What version of a card has described problem?

v2.3.0

### What was the last working version card?

v.2.3.0

### What vacuum model do you have problems with?

roborock.vacuum_s8

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/roborock

### What browser (browsers/apps) does have this problem?

Safar

### What version of Home Assistant do you use?

2025.3.4

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_locked: true
map_source:
  camera: image.roborock_s8_map_0
  crop:
    top: 220
    bottom: 150
    left: 185
    right: 225
calibration_source:
  calibration_points:
    - vacuum:
        x: 25500
        "y": 25500
      map:
        x: 230
        "y": 132
    - vacuum:
        x: 26500
        "y": 25500
      map:
        x: 250
        "y": 132
    - vacuum:
        x: 25500
        "y": 26500
      map:
        x: 230
        "y": 112
entity: vacuum.roborock_s8
vacuum_platform: Roborock
map_modes:

  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_clean_segment
    id_type: number
    predefined_selections:
      - id: "16"
        icon:
          name: mdi:broom
          x: 20750
          "y": 21500
        label:
          text: Hallway
          x: 20750
          "y": 21500
          offset_y: 35
        outline:
          - - 19200
            - 20500
          - - 22300
            - 20500
          - - 22300
            - 22500
          - - 19200
            - 22500
      - id: "17"
        icon:
          name: mdi:broom
          x: 19875
          "y": 19125
        label:
          text: Kitchen
          x: 19875
          "y": 19125
          offset_y: 35
        outline:
          - - 19200
            - 17750
          - - 20550
            - 17750
          - - 20550
            - 20500
          - - 19200
            - 20500
      - id: "18"
        icon:
          name: mdi:broom
          x: 20350
          "y": 26400
        label:
          text: Balcony
          x: 20350
          "y": 26400
          offset_y: 35
        outline:
          - - 18400
            - 25700
          - - 22300
            - 25700
          - - 22300
            - 27100
          - - 18400
            - 27100
      - id: "19"
        icon:
          name: mdi:broom
          x: 24150
          "y": 24075
        label:
          text: Livingroom
          x: 24150
          "y": 24075
          offset_y: 35
        outline:
          - - 22300
            - 21450
          - - 26000
            - 21450
          - - 26000
            - 26700
          - - 22300
            - 26700
      - id: "20"
        icon:
          name: mdi:broom
          x: 20175
          "y": 24025
        label:
          text: Diningroom
          x: 20175
          "y": 24025
          offset_y: 35
        outline:
          - - 18000
            - 22450
          - - 22350
            - 22450
          - - 22350
            - 25600
          - - 18000
            - 25600
      - id: "21"
        icon:
          name: mdi:broom
          x: 23600
          "y": 19600
        label:
          text: Bedroom
          x: 23600
          "y": 19600
          offset_y: 35
        outline:
          - - 21200
            - 17000
          - - 26000
            - 17000
          - - 26000
            - 22200
          - - 21200
            - 22200
      - id: "22"
        icon:
          name: mdi:broom
          x: 18675
          "y": 22075
        label:
          text: Toilet
          x: 18675
          "y": 22075
          offset_y: 35
        outline:
          - - 18250
            - 21700
          - - 19100
            - 21700
          - - 19100
            - 22450
          - - 18250
            - 22450
    variables: {}

            
icons:
  - icon: mdi:play
    conditions:
      - entity: vacuum.roborock_s8
        value_not: cleaning
      - entity: vacuum.roborock_s8
        value_not: error
      - entity: vacuum.roborock_s8
        value_not: returning
    tooltip: Start
    tap_action:
      action: call-service
      service: vacuum.start
      service_data:
        entity_id: vacuum.roborock_s8
  - icon: mdi:pause
    conditions:
      - entity: vacuum.roborock_s8
        value_not: docked
      - entity: vacuum.roborock_s8
        value_not: idle
      - entity: vacuum.roborock_s8
        value_not: error
      - entity: vacuum.roborock_s8
        value_not: paused
    tooltip: Pause
    tap_action:
      action: call-service
      service: vacuum.pause
      service_data:
        entity_id: vacuum.roborock_s8
  - icon: mdi:stop
    conditions:
      - entity: vacuum.roborock_s8
        value_not: docked
      - entity: vacuum.roborock_s8
        value_not: idle
      - entity: vacuum.roborock_s8
        value_not: error
      - entity: vacuum.roborock_s8
        value_not: paused
    tooltip: Stop
    tap_action:
      action: call-service
      service: vacuum.stop
      service_data:
        entity_id: vacuum.roborock_s8
  - icon: mdi:home-map-marker
    conditions:
      - entity: vacuum.roborock_s8
        value_not: docked
      - entity: vacuum.roborock_s8
        value_not: returning
    tooltip: Return to base
    tap_action:
      action: call-service
      service: vacuum.return_to_base
      service_data:
        entity_id: vacuum.roborock_s8
  - icon: mdi:target-variant
    conditions:
      - entity: vacuum.roborock_s8
        value_not: docked
      - entity: vacuum.roborock_s8
        value_not: error
      - entity: vacuum.roborock_s8
        value_not: cleaning
      - entity: vacuum.roborock_s8
        value_not: returning
    tooltip: Clean spot
    tap_action:
      action: call-service
      service: vacuum.clean_spot
      service_data:
        entity_id: vacuum.roborock_s8
  - menu_id: fan_speed
    icon: mdi:fan-alert
    label: "off"
    conditions:
      - entity: vacuum.roborock_s8
        attribute: fan_speed
        value: "off"
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_s8
        fan_speed: "off"
  - menu_id: fan_speed
    icon: mdi:fan-alert
    label: quiet
    conditions:
      - entity: vacuum.roborock_s8
        attribute: fan_speed
        value: quiet
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_s8
        fan_speed: quiet
  - menu_id: fan_speed
    icon: mdi:fan-alert
    label: balanced
    conditions:
      - entity: vacuum.roborock_s8
        attribute: fan_speed
        value: balanced
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_s8
        fan_speed: balanced
  - menu_id: fan_speed
    icon: mdi:fan-alert
    label: Turbo
    conditions:
      - entity: vacuum.roborock_s8
        attribute: fan_speed
        value: turbo
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_s8
        fan_speed: turbo
  - menu_id: fan_speed
    icon: mdi:fan-alert
    label: max
    conditions:
      - entity: vacuum.roborock_s8
        attribute: fan_speed
        value: max
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_s8
        fan_speed: max
  - menu_id: fan_speed
    icon: mdi:fan-alert
    label: custom
    conditions:
      - entity: vacuum.roborock_s8
        attribute: fan_speed
        value: custom
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_s8
        fan_speed: custom
  - menu_id: fan_speed
    icon: mdi:fan-alert
    label: max_plus
    conditions:
      - entity: vacuum.roborock_s8
        attribute: fan_speed
        value: max_plus
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_s8
        fan_speed: max_plus
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.roborock_s8
        attribute: fan_speed
        value_not: "off"
      - entity: vacuum.roborock_s8
        attribute: fan_speed
        value_not: quiet
      - entity: vacuum.roborock_s8
        attribute: fan_speed
        value_not: balanced
      - entity: vacuum.roborock_s8
        attribute: fan_speed
        value_not: turbo
      - entity: vacuum.roborock_s8
        attribute: fan_speed
        value_not: max
      - entity: vacuum.roborock_s8
        attribute: fan_speed
        value_not: custom
      - entity: vacuum.roborock_s8
        attribute: fan_speed
        value_not: max_plus
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_s8
        fan_speed: "off"
  - type: menu
    menu_id: water_box_mode
    icon_id: water_box_mode
    available_values_attribute: options
    icon: mdi:water
    icon_mapping:
      "off": mdi:water-remove
      mild: mdi:water-minus
      moderate: mdi:water
      intense: mdi:water-plus
      custom: mdi:water-sync
    tap_action:
      action: call-service
      service: select.select_option
      service_data:
        option: "[[value]]"
        entity_id: "[[entity_id]]"
    entity: select.roborock_s8_mop_intensity
  - type: menu
    menu_id: mop_mode
    icon_id: mop_mode
    available_values_attribute: options
    icon: mdi:water
    icon_mapping:
      standard: mdi:standard-definition
      deep: mdi:high-definition
      deep_plus: mdi:ultra-high-definition
      custom: mdi:fit-to-screen-outline
    tap_action:
      action: call-service
      service: select.select_option
      service_data:
        option: "[[value]]"
        entity_id: "[[entity_id]]"
    entity: select.roborock_s8_mop_mode
tiles:
  - tile_id: status
    entity: vacuum.roborock_s8
    label: Status
    icon: mdi:robot-vacuum
    translations:
      starting: Starting
      charger disconnected: Charger disconnected
      idle: Idle
      remote control active: Remote control active
      cleaning: Cleaning
      returning home: Returning home
      manual mode: Manual mode
      charging: Charging
      charging problem: Charging problem
      paused: Paused
      spot cleaning: Spot cleaning
      error: Error
      shutting down: Shutting down
      updating: Updating
      docked: Docking
      going to target: Going to target
      zoned cleaning: Zoned cleaning
      segment cleaning: Segment cleaning
      emptying the bin: Emptying the bin
      charging complete: Charging complete
      device offline: Device offline
  - tile_id: battery_level
    entity: vacuum.roborock_s8
    label: Battery
    attribute: battery_level
    icon_source: vacuum.roborock_s8.attributes.battery_icon
    unit: "%"
  - tile_id: sensor_dirty_left
    label: Sensors left
    unit: h
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: {}
      service_data:
        command: reset_consumable
        params: sensor_dirty_time
        entity_id: vacuum.roborock_s7_maxv
    entity: sensor.roborock_s8_sensor_time_left
    icon: mdi:eye-outline
    precision: 0
    translations: {}
  - tile_id: filter_left
    label: Filter left
    unit: h
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: {}
      service_data:
        command: reset_consumable
        params: filter_work_time
        entity_id: vacuum.roborock_s8
    entity: sensor.roborock_s8_filter_time_left
    icon: mdi:air-filter
    precision: 0
    translations: {}
  - tile_id: main_brush_left
    label: Main brush left
    unit: h
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: {}
      service_data:
        command: reset_consumable
        params: main_brush_work_time
        entity_id: vacuum.roborock_s8
    entity: sensor.roborock_s8_main_brush_time_left
    icon: mdi:brush
    precision: 0
    translations: {}
  - tile_id: side_brush_left
    label: Side brush left
    unit: h
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: {}
      service_data:
        command: reset_consumable
        params: side_brush_work_time
        entity_id: vacuum.roborock_s8
    entity: sensor.roborock_s8_side_brush_time_left
    icon: mdi:brush
    precision: 0
    translations: {}
  - tile_id: cleaning_count
    label: Cleaning count
    entity: sensor.roborock_s8_total_cleaning_count
    icon: mdi:counter
    precision: 0
    translations: {}
```

### Javascript errors shown in the browser's console (if applicable)

```shell

```

**Comment by PiotrMachowski** [comment]
I suspect the problem is with the calibration - it might be out of date. Please recalibrate the card and try again

**Comment by poudenes** [comment]
<img width="474" alt="Image" src="https://github.com/user-attachments/assets/d9b75d10-dda9-46ae-af53-ab2e33f656f9" />

The card seems ok.  Goto point working correct. Room selection working correct.

**Comment by poudenes** [comment]
Wanna clean this zone

<img width="478" alt="Image" src="https://github.com/user-attachments/assets/b90e8fd4-54b2-49d4-967b-1d59c1d2038f" />

And its gonna clean my bedroom:

<img width="476" alt="Image" src="https://github.com/user-attachments/assets/871f0e6b-6607-4747-82c0-d6cb4c6130a8" />

**Comment by PiotrMachowski** [comment]
Have you confirmed that going to point is executed correctly for all points?
Room cleaning doesn't really matter in this case - it uses room id, not coordinates.

**Comment by poudenes** [comment]
> Have you confirmed that going to point is executed correctly for all points (try 3 of them)? Room cleaning doesn't really matter in this case - it uses room id, not coordinates.

But when I select a area (zone) and hit the start button then why is it moving to my bedroom and is gonna clean the "room" 

But let me dig into it more...

**Comment by tzagim** [comment]
I have the same thing, I also initially thought the problem was in my settings....

**Comment by poudenes** [comment]
I tried selective zone cleaning on 9 different places. All the time it is starting at the first room to clean (order from Roborock App) 
It seems that the start button not start the zone cleaning but is just the cleaning the house action.

**Comment by tzagim** [comment]
> Can you show the service call? You can get it using "Copy service call" button from the card editor

```json
{
  "domain": "vacuum",
  "service": "send_command",
  "serviceData": {
    "command": "app_zoned_clean",
    "params": [
      {
        "zone": [
          [
            21948,
            25994,
            24907,
            27463
          ]
        ],
        "repeats": 1
      }
    ],
    "entity_id": "vacuum.my_robot_name"
  }
}
````

BTW.I use YAML and not in the UI.

**Comment by PiotrMachowski** [comment]
Thanks @tzagim 

> BTW.I use YAML and not UI.

In such case you can add `debug: true` to card's config to get the data

**Comment by poudenes** [comment]
Here mine when I select a zone to clean:

```
{
  "domain": "vacuum",
  "service": "send_command",
  "serviceData": {
    "command": "app_zoned_clean",
    "params": [
      {
        "zone": [
          [
            22050,
            23349,
            22698,
            23825
          ]
        ],
        "repeats": 1
      }
    ],
    "entity_id": "vacuum.roborock_s8"
  }
}
```

Its it going to clean the bedroom instead of the part I selected.

**Comment by PiotrMachowski** [comment]
I know the solution for this problem, I will release the fix soon 👍

**Comment by poudenes** [comment]
Thanks for all the affort!

**Comment by poudenes** [comment]
Seems not work here. Did a clean card config:

```
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: image.roborock_s8_map_0
  crop:
    top: 220
    bottom: 150
    left: 185
    right: 225
calibration_source:
  calibration_points:
    - vacuum:
        x: 25500
        "y": 25500
      map:
        x: 230
        "y": 132
    - vacuum:
        x: 26500
        "y": 25500
      map:
        x: 250
        "y": 132
    - vacuum:
        x: 25500
        "y": 26500
      map:
        x: 230
        "y": 112
entity: vacuum.roborock_s8
identity: true
platform: Roborock
tiles: []
map_modes:
  - template: vacuum_clean_zone
```

I see now this error:
```
Action: xiaomi_milo.vacuum_clean_zone not found.
```

**Comment by PiotrMachowski** [comment]
> I see now this error:
> 
> ```
> Action: xiaomi_milo.vacuum_clean_zone not found.
> ```

That's because your config includes `platform` key instead of `vacuum_platform`, so it uses the `default` platform which is Xiaomi Miio.

Additionally `identity` key should be removed and if you use [Roborock Cusotm Map](https://github.com/Lash-L/RoborockCustomMap/) integration then you should use camera's calibration instead:
```yaml
calibration_source:
  camera: true
```

**Comment by poudenes** [comment]
With this config card no errors on screen. But selecting a area and hit run nothing happen:
```
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: image.roborock_s8_map_0
  crop:
    top: 220
    bottom: 150
    left: 185
    right: 225
calibration_source:
  calibration_points:
    - vacuum:
        x: 25500
        "y": 25500
      map:
        x: 230
        "y": 132
    - vacuum:
        x: 26500
        "y": 25500
      map:
        x: 250
        "y": 132
    - vacuum:
        x: 25500
        "y": 26500
      map:
        x: 230
        "y": 112
entity: vacuum.roborock_s8
vacuum_platform: Roborock
tiles: []
map_modes:
  - name: vacuum_clean_zone
    icon: mdi:select-drag
    selection_type: MANUAL_RECTANGLE
    max_selections: 999
    coordinates_rounding": true
    coordinates_to_meters_divider": 1000
    repeats_type: EXTERNAL
    max_repeats: 1
    service_call_schema:
      service: vacuum.send_command
      service_data:
        command: app_zoned_clean
        params:
          zone: "[[selection]]"
          repeats: "[[repeats]]"
      target:
        entity_id: "[[entity_id]]"
```

with this:
```
calibration_source:
  camera: true
```
I get a error: Invalid calibration, please check your configuration

**Comment by PiotrMachowski** [comment]
What is returned when you use "Copy service call" button?

**Comment by poudenes** [comment]
I was already there to show it :)

Very strange coordinates
```
{
  "domain": "vacuum",
  "service": "send_command",
  "serviceData": {
    "command": "app_zoned_clean",
    "params": [
      [
        40894,
        -3299,
        44034,
        -287,
        1
      ]
    ],
    "entity_id": "vacuum.roborock_s8"
  }
}
```

**Comment by poudenes** [comment]
Rooms are not showing anymore at all

**Comment by PiotrMachowski** [comment]
For room cleaning the position of the room on the map doesn't really matter - they use IDs instead of coordinates.

Does the zone cleaning work correctly now?

**Comment by poudenes** [comment]
The zone cleaning isn't working at all. And the rooms you can't select them if you have the map nice in scale...
Its strange because with your card en the Roborock custom Integration everything work correct on my production HA

I test now the Roborock core with your card and have those issues.

**Comment by PiotrMachowski** [comment]
Have you this?

> if you use [Roborock Cusotm Map](https://github.com/Lash-L/RoborockCustomMap/) integration then you should use camera's calibration instead:
> ```yaml
> calibration_source:
>   camera: true
> ```

**Comment by poudenes** [comment]
> Have you tried this?
> 
> > if you use [Roborock Cusotm Map](https://github.com/Lash-L/RoborockCustomMap/) integration then you should use camera's calibration instead:
> > calibration_source:
> >   camera: true

Now everything is working. Room, Zone, Pin&Go

**Comment by PiotrMachowski** [comment]
> Only the image is not updating correctly
> 
> map size and locking is also not working

Can you please describe it more?

**Comment by poudenes** [comment]
> > Only the image is not updating correctly
> > map size and locking is also not working
> 
> Can you please describe it more?

When I resize the map zo its nice without all the blue around. Then hit the lock icon. When refresh the browsers map size is back in old size
(let me clear the browser cache)

**Comment by PiotrMachowski** [comment]
Ok, that's how it always worked.

https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/824

**Comment by poudenes** [comment]
> Ok, that's how it always worked.
> 
> [#824](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/824)

Sorry my fault... forgotten to add:

```
          crop:
            top: 220
            bottom: 150
            left: 185
            right: 225
```
