### ISSUE TITLE
Dreame Vacuum  2 suction level icons

### ISSUE THREAD

**Issue by chertvl** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#819]
### Checklist

- [x] I have updated the card to the latest version available
- [x] I have cleared the cache of my browser
- [x] I have checked if the problem is already reported

### The problem

Hello Piotr!
Some reason, after update card to 2.3.0 version,
there is 2 suction mode icons for Dreame Vacuum platform.
Old one, and new one from:
(Added suction level and cleaning mode icons to [Tasshack/dreame-vacuum](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/blob/master/docs/templates/tasshackDreameVacuum.md) vacuum platform (thanks, @jimjaeger!))

How can we hide one of them? :p 

### What version of a card has described problem?

2.3.0

### What was the last working version card?

previous 2.2.4 i think

### What vacuum model do you have problems with?

dreame.vacuum.r2416a

### Which integration do you use to control your vacuum (link)?

https://github.com/Tasshack/dreame-vacuum/

### What browser (browsers/apps) does have this problem?

Chrome

### What version of Home Assistant do you use?

core-2025.3.4

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
Minimum requied configuration:

type: custom:xiaomi-vacuum-map-card
vacuum_platform: Tasshack/dreame-vacuum
entity: vacuum.vacuum
map_source:
  camera: camera.vacuum_map
calibration_source:
  camera: true
tiles: []
append_icons: true
```

### Javascript errors shown in the browser's console (if applicable)

```shell

```

### Additional information

![Image](https://github.com/user-attachments/assets/7c613826-cf1c-4c20-afa0-0873a3cb6f27)

![Image](https://github.com/user-attachments/assets/ee96d278-d662-4edd-b6a7-0bbfee881ae6)

![Image](https://github.com/user-attachments/assets/6e4bcd34-6ca4-472c-9758-f747603fe2ec)
