### ISSUE TITLE
Roborock

### ISSUE THREAD

**Issue by Inforhome** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#820]
### Integration repository

https://www.home-assistant.io/integrations/xiaomi_miio/

### Supported features

- [x] Zone cleaning (using 4 coordinates)
- [x] Room cleaning (using room id/number)
- [x] Going to point (using 2 coordinates)
- [x] Cleaning a point (using 2 coordinates)
- [x] Others

### Checklist

- [x] I have sent info about entities to `piotr.machowski.dev [at] gmail.com` ([Retrieving entities info](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/594); please provide your GitHub username in the email)

### Vacuum entity/entities

```yaml
type: "menu",
menu_id: "water_box_mode",
icon_id: "water_box_mode",
entity: "select.water_box_mode"
available_values_attribute: "options"
icon: "mdi:water",
icon_mapping:
    off: "mdi:water-remove"
    mild: "mdi:water-minus"
    moderate: "mdi:water"
    intense: "mdi:water-plus"
    custom: "mdi:water-sync"
tap_action:
    action: "call-service"
    service: "select.select_option"
    service_data:
        option: "[[value]]"
        entity_id: "[[entity_id]]"
```

### Service calls

```yaml
variables:
  test_variable: 123
service_call_schema:
  service: fake.service
  service_data:
    var: "[[test_variable]]"
```
