### ISSUE TITLE
"roborock.vacuum_goto - command not exist" in template "following a specified path" for Roborock core integration.

### ISSUE THREAD

**Issue by zerofull56** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#828]
### Checklist

- [x] I have updated the card to the latest version available
- [x] I have cleared the cache of my browser
- [x] I have checked if the problem is already reported

### The problem

Thank you for this wonderful card! I have Roborock Qrevo Master vacuum and Roborock core integration work fine with this. But not template "following a specified path" . This template not working with error:
"Error executing script. Service not found for repeat at pos 1: Action roborock.vacuum_goto not found".

### What version of a card has described problem?

2.3.1

### What was the last working version card?

2.3.1

### What vacuum model do you have problems with?

Roborock Qrevo Master

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/roborock/

### What browser (browsers/apps) does have this problem?

HA android app

### What version of Home Assistant do you use?

2025.4.1

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
debug: false
entity: vacuum.roborock
map_source:
  camera: image.roborock_qrevo_master_map_custom
  crop:
    top: 195
    bottom: 125
    left: 200
    right: 197
calibration_source:
  camera: true
vacuum_platform: Roborock
two_finger_pan: true
map_locked: true
tiles:
  - tile_id: status
    entity: sensor.roborock_qrevo_master_status
    label: Статус
    icon: mdi:robot-vacuum
    tooltip: Статус пылесоса
    translations:
      starting: Старт
      charger disconnected: Автономный режим
      idle: Неактивен
      remote control active: Активно ручное управление
      cleaning: Очистка
      returning home: Возвращается на базу
      manual mode: Ручной режим
      charging: Заряжается
      charging problem: Ошибка зарядки
      paused: Пауза
      spot cleaning: Точечная очистка
      error: Ошибка
      shutting down: Отключение
      updating: Обновление
      docking: Парковка
      going to target: Едет к месту назначения
      segment cleaning: Уборка комнат
      zoned cleaning: Зональная очистка
      emptying the bin: Очистка бака
      charging complete: Зарядка закончена
      device offline: Недостпен
  - tile_id: battery_level
    entity: vacuum.roborock
    label: Батарея
    attribute: battery_level
    icon_source: vacuum.roborock.attributes.battery_icon
    unit: "%"
    tooltip: Уровень батареи
  - tile_id: ai_mode
    entity: vacuum.roborock
    label: Режим работы
    attribute: fan_speed
    icon: mdi:vacuum-outline
    tooltip: Режим работы пылесоса
    conditions:
      - entity: vacuum.roborock
        attribute: fan_speed
        value: smart_mode
    translations:
      smartplan: Режим ИИ
  - tile_id: fan_mode
    entity: vacuum.roborock
    label: Режим работы пылесоса
    attribute: fan_speed
    icon: mdi:vacuum-outline
    tooltip: Режим работы пылесоса
    conditions:
      - entity: vacuum.roborock
        attribute: fan_speed
        value_not: "off"
      - entity: vacuum.roborock
        attribute: fan_speed
        value_not: smart_mode
  - tile_id: mop_mode
    entity: select.roborock_qrevo_master_mop_intensity
    label: Режим работы швабр
    icon: mdi:water-sync
    tooltip: Влажность швабр
    conditions:
      - entity: select.roborock_qrevo_master_mop_intensity
        value_not: "off"
      - entity: vacuum.roborock
        attribute: fan_speed
        value_not: smart_mode
  - tile_id: sensor_dirty_left
    label: Ресурс датчиков
    tooltip: Зажать чтобы сбросить ресурс
    unit: ч
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: true
      service_data:
        command: reset_consumable
        params: sensor_dirty_time
        entity_id: vacuum.roborock
    entity: sensor.roborock_qrevo_master_sensor_time_left
    icon: mdi:eye-outline
    precision: 0
    translations: {}
  - tile_id: filter_left
    label: Ресурс фильтра
    tooltip: Зажать чтобы сбросить ресурс
    unit: ч
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: true
      service_data:
        command: reset_consumable
        params: filter_work_time
        entity_id: vacuum.roborock
    entity: sensor.roborock_qrevo_master_filter_time_left
    icon: mdi:air-filter
    precision: 0
    translations: {}
  - tile_id: main_brush_left
    label: Ресурс щётки
    tooltip: Зажать чтобы сбросить ресурс
    unit: ч
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: true
      service_data:
        command: reset_consumable
        params: main_brush_work_time
        entity_id: vacuum.roborock
    entity: sensor.roborock_qrevo_master_main_brush_time_left
    icon: mdi:brush
    precision: 0
    translations: {}
  - tile_id: side_brush_left
    label: Ресурс боковой щётки
    tooltip: Зажать чтобы сбросить ресурс
    unit: ч
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: true
      service_data:
        command: reset_consumable
        params: side_brush_work_time
        entity_id: vacuum.roborock
    entity: sensor.roborock_qrevo_master_side_brush_time_left
    icon: mdi:brush
    precision: 0
    translations: {}
  - tile_id: mob_try_left
    label: До конца сушки швабр
    unit: мин
    multiplier: 0.0166666667
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: true
      service_data:
        command: reset_consumable
        params: side_brush_work_time
        entity_id: vacuum.roborock
    entity: sensor.roborock_qrevo_master_mop_drying_remaining_time
    icon: mdi:brush
    precision: 0
    translations: {}
icons:
  - icon: mdi:play
    conditions:
      - entity: vacuum.roborock
        value_not: cleaning
      - entity: vacuum.roborock
        value_not: error
      - entity: vacuum.roborock
        value_not: returning
    tooltip: Старт
    tap_action:
      action: call-service
      service: vacuum.start
      service_data:
        entity_id: vacuum.roborock
  - icon: mdi:pause
    conditions:
      - entity: vacuum.roborock
        value_not: docked
      - entity: vacuum.roborock
        value_not: idle
      - entity: vacuum.roborock
        value_not: error
      - entity: vacuum.roborock
        value_not: paused
    tooltip: Пауза
    tap_action:
      action: call-service
      service: vacuum.pause
      service_data:
        entity_id: vacuum.roborock
  - icon: mdi:stop
    conditions:
      - entity: vacuum.roborock
        value_not: docked
      - entity: vacuum.roborock
        value_not: idle
      - entity: vacuum.roborock
        value_not: error
      - entity: vacuum.roborock
        value_not: paused
    tooltip: Стоп
    tap_action:
      action: call-service
      service: vacuum.stop
      service_data:
        entity_id: vacuum.roborock
  - icon: mdi:home-map-marker
    conditions:
      - entity: vacuum.roborock
        value_not: docked
      - entity: vacuum.roborock
        value_not: returning
    tooltip: Вернуть на базу
    tap_action:
      action: call-service
      service: vacuum.return_to_base
      service_data:
        entity_id: vacuum.roborock
  - icon: mdi:target-variant
    conditions:
      - entity: vacuum.roborock
        value_not: docked
      - entity: vacuum.roborock
        value_not: error
      - entity: vacuum.roborock
        value_not: cleaning
      - entity: vacuum.roborock
        value_not: returning
    tooltip: Точечная очистка
    tap_action:
      action: call-service
      service: vacuum.clean_spot
      service_data:
        entity_id: vacuum.roborock
  - icon: mdi:map-marker
    tooltip: Найти
    tap_action:
      action: call-service
      service: vacuum.locate
      service_data:
        entity_id: vacuum.roborock
  - menu_id: work_mode
    icon: mdi:account-check
    label: Ручной режим
    conditions:
      - entity: vacuum.roborock
        attribute: fan_speed
        value_not: smart_mode
    tooltip: Сменить режим пылесоса
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.roborock
        command: set_custom_mode
        params: 106
  - menu_id: work_mode
    icon: mdi:robot-vacuum
    label: Режим AI
    tooltip: Сменить режим пылесоса на AI
    conditions:
      - entity: vacuum.roborock
        attribute: fan_speed
        value_not: custom
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.roborock
        command: set_custom_mode
        params: 110
  - menu_id: fan_speed
    icon: mdi:fan-chevron-down
    label: Выбрать режим
    conditions:
      - entity: vacuum.roborock
        attribute: fan_speed
        value: custom
      - entity: vacuum.roborock
        attribute: fan_speed
        value_not: smart_mode
  - menu_id: fan_speed
    icon: mdi:fan-off
    label: Выключить
    conditions:
      - entity: vacuum.roborock
        attribute: fan_speed
        value: "off"
      - entity: vacuum.roborock
        attribute: fan_speed
        value_not: smart_mode
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock
        fan_speed: "off"
  - menu_id: fan_speed
    icon: mdi:fan-minus
    label: Тихо
    conditions:
      - entity: vacuum.roborock
        attribute: fan_speed
        value: quiet
      - entity: vacuum.roborock
        attribute: fan_speed
        value_not: smart_mode
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock
        fan_speed: quiet
  - menu_id: fan_speed
    icon: mdi:fan-speed-1
    label: Сбалансированная
    conditions:
      - entity: vacuum.roborock
        attribute: fan_speed
        value: balanced
      - entity: vacuum.roborock
        attribute: fan_speed
        value_not: smart_mode
    tooltip: Сменить режим пылесоса
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock
        fan_speed: balanced
  - menu_id: fan_speed
    icon: mdi:fan-speed-2
    label: Турбо
    conditions:
      - entity: vacuum.roborock
        attribute: fan_speed
        value: turbo
      - entity: vacuum.roborock
        attribute: fan_speed
        value_not: smart_mode
    tooltip: Сменить режим пылесоса
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock
        fan_speed: turbo
  - menu_id: fan_speed
    icon: mdi:fan-speed-3
    label: Максимальный
    conditions:
      - entity: vacuum.roborock
        attribute: fan_speed
        value: max
      - entity: vacuum.roborock
        attribute: fan_speed
        value_not: smart_mode
    tooltip: Сменить режим пылесоса
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock
        fan_speed: max
  - menu_id: fan_speed
    icon: mdi:fan-plus
    label: Максимальный+
    conditions:
      - entity: vacuum.roborock
        attribute: fan_speed
        value: max_plus
      - entity: vacuum.roborock
        attribute: fan_speed
        value_not: smart_mode
    tooltip: Сменить режим пылесоса
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock
        fan_speed: max_plus
  - menu_id: mop_mode
    icon: mdi:water-check
    label: Выбрать режим швабры
    conditions:
      - entity: select.roborock_qrevo_master_mop_intensity
        value: custom
      - entity: vacuum.roborock
        attribute: fan_speed
        value_not: smart_mode
    tooltip: Выбор режима работы швабры
  - menu_id: mop_mode
    icon: mdi:water-off
    label: Выключить
    conditions:
      - entity: select.roborock_qrevo_master_mop_intensity
        value: "off"
      - entity: vacuum.roborock
        attribute: fan_speed
        value_not: smart_mode
    tooltip: Выключить влажную уборку.
    tap_action:
      action: call-service
      service: select.select_option
      service_data:
        entity_id: select.roborock_qrevo_master_mop_intensity
        option: "off"
  - menu_id: mop_mode
    icon: mdi:water-minus
    label: Низкая влажность
    conditions:
      - entity: select.roborock_qrevo_master_mop_intensity
        value: low
      - entity: vacuum.roborock
        attribute: fan_speed
        value_not: smart_mode
    tooltip: Выбрать низкий режим увлажнения тряпок.
    tap_action:
      action: call-service
      service: select.select_option
      service_data:
        entity_id: select.roborock_qrevo_master_mop_intensity
        option: low
  - menu_id: mop_mode
    icon: mdi:water-opacity
    label: Средняя влажность
    conditions:
      - entity: select.roborock_qrevo_master_mop_intensity
        value: medium
      - entity: vacuum.roborock
        attribute: fan_speed
        value_not: smart_mode
    tooltip: Выбрать средний режим увлажнения тряпок.
    tap_action:
      action: call-service
      service: select.select_option
      service_data:
        entity_id: select.roborock_qrevo_master_mop_intensity
        option: medium
  - menu_id: mop_mode
    icon: mdi:water-plus
    label: Максимум
    conditions:
      - entity: select.roborock_qrevo_master_mop_intensity
        value: high
      - entity: vacuum.roborock
        attribute: fan_speed
        value_not: smart_mode
    tooltip: Выбрать самый влажный режим тряпок.
    tap_action:
      action: call-service
      service: select.select_option
      service_data:
        entity_id: select.roborock_qrevo_master_mop_intensity
        option: high
map_modes:
  - template: vacuum_clean_segment
    name: Комнаты
    predefined_selections:
      - id: "17"
        icon:
          name: mdi:bed
          x: 26500
          "y": 24500
        label:
          text: " "
          x: 26500
          "y": 24500
          offset_y: 30
        outline:
          - - 24900
            - 21550
          - - 28200
            - 21550
          - - 28200
            - 26900
          - - 24900
            - 26900
      - id: "18"
        icon:
          name: mdi:table-chair
          x: 30100
          "y": 23200
        label:
          text: " "
          x: 30100
          "y": 23200
          offset_y: 30
        outline:
          - - 28250
            - 21550
          - - 31750
            - 21550
          - - 31750
            - 24700
          - - 28250
            - 24700
      - id: "19"
        icon:
          name: mdi:bathtub
          x: 31100
          "y": 25800
        label:
          text: " "
          x: 31100
          "y": 25800
          offset_y: 30
        outline:
          - - 30150
            - 24750
          - - 31750
            - 24750
          - - 31750
            - 26900
          - - 30150
            - 26900
      - id: "16"
        icon:
          name: mdi:transit-transfer
          x: 29100
          "y": 25800
        label:
          text: " "
          x: 29100
          "y": 25800
          offset_y: 30
        outline:
          - - 28250
            - 24750
          - - 30100
            - 24750
          - - 30100
            - 26900
          - - 28250
            - 26900
  - template: vacuum_clean_zone_predefined
    name: Зоны
    predefined_selections:
      - zones:
          - - 24800
            - 26900
            - 28200
            - 21600
        icon:
          name: mdi:bed
          x: 26500
          "y": 24500
        label:
          text: " "
          x: 26500
          "y": 24500
          offset_y: 30
      - zones:
          - - 28300
            - 24700
            - 31750
            - 21600
        icon:
          name: mdi:bathtub
          x: 31100
          "y": 25800
        label:
          text: " "
          x: 31100
          "y": 25800
          offset_y: 30
      - zones:
          - - 30200
            - 26900
            - 31750
            - 24800
        icon:
          name: mdi:table-chair
          x: 30100
          "y": 23200
        label:
          text: " "
          x: 30100
          "y": 23200
          offset_y: 30
      - zones:
          - - 28300
            - 26900
            - 30100
            - 24800
        icon:
          name: mdi:transit-transfer
          x: 29100
          "y": 25800
        label:
          text: " "
          x: 29100
          "y": 25800
          offset_y: 30
      - zones:
          - - 28351
            - 26193
            - 29535
            - 26874
        icon:
          name: mdi:approximately-equal-box
          x: 28900
          "y": 26550
        label:
          text: " "
          x: 30100
          "y": 23200
          offset_y: 30
  - template: vacuum_clean_zone
    name: Произвольно
  - template: vacuum_goto
    name: Следовать
  - template: vacuum_follow_path
    name: Следовать по пути
title: Пылесос
```

### Javascript errors shown in the browser's console (if applicable)

```shell

```

**Comment by MGorelovs** [comment]
Hi there!
I would like to also tell you thanks for a great job!

Similar problem happens for me with the in combination with different integration.
Please let me know if any additional information is needed.

### What version of a card has described problem?
2.3.1

### What was the last working version card?
Never used it before

### What vacuum model do you have problems with?
Xiaomi S10+ (dreame.vacuum.r2211o)

### Which integration do you use to control your vacuum (link)?
https://github.com/Tasshack/dreame-vacuum

### What browser (browsers/apps) does have this problem?
Google Chrome

### What version of Home Assistant do you use?
2026.1.2

### What type of installation are you running?
Docker Container on Ubuntu

### Card's configuration

```yaml
title: Xiaomi Vacuum Map Card
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.cleaner_map
calibration_source:
  camera: true
entity: vacuum.cleaner
vacuum_platform: Tasshack/dreame-vacuum
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_follow_path
  - template: vacuum_clean_segment
    predefined_selections:
      - id: 1
        outline:
          - - 3550
            - 1300
          - - 6650
            - 1300
          - - 6650
            - 3850
          - - 3550
            - 3850
        label:
          text: Ванная
          x: 5300
          "y": 2700
          offset_y: 35
        icon:
          name: mdi:bathtub-outline
          x: 5300
          "y": 2700
      - id: 2
        icon:
          name: mdi:bed-double-outline
          x: 1750
          "y": 50
        label:
          text: Спальня
          x: 1750
          "y": 50
          offset_y: 35
        outline:
          - - -600
            - -2250
          - - 4500
            - -2250
          - - 4500
            - 2350
          - - -600
            - 2350
      - id: 3
        icon:
          name: mdi:toilet
          x: 4300
          "y": 3700
        label:
          text: Туалет
          x: 4300
          "y": 3700
          offset_y: 35
        outline:
          - - 3600
            - 2950
          - - 5150
            - 2950
          - - 5150
            - 4550
          - - 3600
            - 4550
      - id: 4
        icon:
          name: mdi:door
          x: 4250
          "y": 6200
        label:
          text: Прихожая
          x: 4250
          "y": 6200
          offset_y: 35
        outline:
          - - 2650
            - 3700
          - - 5050
            - 3700
          - - 5050
            - 7900
          - - 2650
            - 7900
      - id: 5
        icon:
          name: mdi:balcony
          x: -3050
          "y": 5050
        label:
          text: Балкон
          x: -3050
          "y": 5050
          offset_y: 35
        outline:
          - - -6000
            - 3750
          - - -2500
            - 3750
          - - -2500
            - 6750
          - - -6000
            - 6750
      - id: 6
        icon:
          name: mdi:laptop
          x: -450
          "y": 1800
        label:
          text: Кабинет
          x: -450
          "y": 1800
          offset_y: 35
        outline:
          - - -2250
            - 100
          - - 1850
            - 100
          - - 1850
            - 3650
          - - -2250
            - 3650
      - id: 7
        icon:
          name: mdi:home-outline
          x: 250
          "y": 5300
        label:
          text: Гостиная
          x: 250
          "y": 5300
          offset_y: 35
        outline:
          - - -2500
            - 1800
          - - 4000
            - 1800
          - - 4000
            - 7400
          - - -2500
            - 7400
```
