### ISSUE TITLE
Roborock: Multiple Room cleaning not working

### ISSUE THREAD

**Issue by BeFygo** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#830]
### Checklist

- [x] I have updated the card to the latest version available
- [x] I have cleared the cache of my browser
- [x] I have checked if the problem is already reported

### The problem

When selecting Rooms and x2 or x3 the robot only cleans once.

### What version of a card has described problem?

v2.3.1

### What was the last working version card?

?

### What vacuum model do you have problems with?

roborock.vacuum.a38

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/roborock/

### What browser (browsers/apps) does have this problem?

Chrome/android app

### What version of Home Assistant do you use?

2025.4.2

### What type of installation are you running?

Home Assistant Container

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: image.roborock_q7_max_map1_custom
calibration_source:
  camera: true
entity: vacuum.roborock_q7_max
vacuum_platform: Roborock
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_segment
    predefined_selections:
      - id: "16"
        icon:
          name: mdi:broom
          x: 20700
          "y": 23975
        label:
          text: Bathroom
          x: 20700
          "y": 23975
          offset_y: 35
        outline:
          - - 19500
            - 23200
          - - 21900
            - 23200
          - - 21900
            - 24750
          - - 19500
            - 24750
      - id: "17"
        icon:
          name: mdi:broom
          x: 21325
          "y": 27425
        label:
          text: Bedroom
          x: 21325
          "y": 27425
          offset_y: 35
        outline:
          - - 19850
            - 26000
          - - 22800
            - 26000
          - - 22800
            - 28850
          - - 19850
            - 28850
      - id: "18"
        icon:
          name: mdi:broom
          x: 22775
          "y": 25350
        label:
          text: Corridor
          x: 22775
          "y": 25350
          offset_y: 35
        outline:
          - - 19750
            - 24800
          - - 25800
            - 24800
          - - 25800
            - 25900
          - - 19750
            - 25900
      - id: "19"
        icon:
          name: mdi:broom
          x: 24275
          "y": 27400
        label:
          text: Guest bedroom
          x: 24275
          "y": 27400
          offset_y: 35
        outline:
          - - 23050
            - 25950
          - - 25500
            - 25950
          - - 25500
            - 28850
          - - 23050
            - 28850
      - id: "20"
        icon:
          name: mdi:broom
          x: 18175
          "y": 26850
        label:
          text: Master bedroom
          x: 18175
          "y": 26850
          offset_y: 35
        outline:
          - - 16700
            - 24900
          - - 19650
            - 24900
          - - 19650
            - 28800
          - - 16700
            - 28800
      - id: "22"
        icon:
          name: mdi:broom
          x: 25150
          "y": 23650
        label:
          text: Room 22
          x: 25150
          "y": 23650
          offset_y: 35
        outline:
          - - 24600
            - 22550
          - - 25700
            - 22550
          - - 25700
            - 24750
          - - 24600
            - 24750
  - template: vacuum_goto
```

### Javascript errors shown in the browser's console (if applicable)

```shell

```

**Comment by PiotrMachowski** [comment]
Temporary fix: 

Replace the line:
```yaml
  - template: vacuum_clean_segment
```
with:
```yaml
  - template: vacuum_clean_segment
    service_call_schema:
      service: vacuum.send_command
      service_data:
        command: app_segment_clean
        params:
          - segments: "[[selection]]"
            repeat: "[[repeats]]"
        entity_id: "[[entity_id]]"
```
