### ISSUE TITLE
Reaching to defined area is impossible - roidmi v60

### ISSUE THREAD

**Issue by darek203** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#833]
### Checklist

- [x] I have updated the card to the latest version available
- [x] I have cleared the cache of my browser
- [x] I have checked if the problem is already reported

### The problem

When launching cleaning of the **manually predefined area** (as per [this movie](https://www.youtube.com/watch?v=CqlEKCv-EBI) (~12 min 20s )) vacuum starts, and few seconds later after detaching from its dock it says "Reaching to defined area is impossible", then it goes back to the dock.

I'm using latest version of Map Card, my vacuum roidmi v60.

 All perfectly works when choosing the areas that were taken directly from the Xiaomi App.

### What version of a card has described problem?

2.3.1

### What was the last working version card?

thats the first version I'm using at all

### What vacuum model do you have problems with?

Roidmi Eve Plus - detected as roidmi v60

### Which integration do you use to control your vacuum (link)?

https://my.home-assistant.io/redirect/hacs_repository/?owner=al-one&repository=hass-xiaomi-miot

### What browser (browsers/apps) does have this problem?

same behavior on Chrome and in iOS app

### What version of Home Assistant do you use?

2025.4.1

### What type of installation are you running?

Home Assistant Supervised

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.roidmi_v60_1c28_robot_cleaner
internal_variables:
  map_id: null
vacuum_platform: al-one/hass-xiaomi-miot
map_locked: true
map_modes:
  - template: vacuum_clean_segment
    name: Rooms
    icon: mdi:floor-plan
    run_immediately: false
    selection_type: ROOM
    id_type: number
    max_selections: 0
    service_call_schema:
      service: xiaomi_miot.call_action
      service_data:
        entity_id: "[[entity_id]]"
        siid: 14
        aiid: 1
        params:
          - 2
          - "{\"mapId\":[[map_id]],\"segmentId\":[[[selection_unwrapped]]]}"
        force_params: true
    predefined_selections:
      - id: "1"
        icon:
          name: mdi:floor-plan
          x: 1600.0002156943083
          "y": -2700.0000786036253
        label:
          text: Ground Floor
          x: 1600.0002156943083
          "y": -2700.0000786036253
          offset_y: 35
        outline:
          - - -1174.999825656414
            - -10525.000177323818
          - - 4375.000257045031
            - -10525.000177323818
          - - 4375.000257045031
            - 2725.000020116567
          - - -1174.999825656414
            - 2725.000020116567
      - id: "2"
        icon:
          name: mdi:home-import-outline
          x: 3400.0002425163984
          "y": -8950.00015385449
        label:
          text: Entrance
          x: 3400.0002425163984
          "y": -8950.00015385449
          offset_y: 35
        outline:
          - - 2525.0002294778824
            - -10625.000178813934
          - - 4275.0002555549145
            - -10625.000178813934
          - - 4275.0002555549145
            - -7275.000128895044
          - - 2525.0002294778824
            - -7275.000128895044
      - id: "3"
        icon:
          name: mdi:fridge-outline
          x: 3125.000238418579
          "y": -6200.000112876296
        label:
          text: Fridge
          x: 3125.000238418579
          "y": -6200.000112876296
          offset_y: 35
        outline:
          - - 2525.0002294778824
            - -7225.000128149986
          - - 3725.000247359276
            - -7225.000128149986
          - - 3725.000247359276
            - -5175.000097602606
          - - 2525.0002294778824
            - -5175.000097602606
      - id: "4"
        icon:
          name: mdi:countertop-outline
          x: 1500
          "y": -1100
        label:
          text: Kitchen
          x: 1500
          "y": -1100
          offset_y: 35
        outline:
          - - 630
            - -122
          - - 1891
            - -122
          - - 1891
            - 1204
          - - 630
            - 1204
  - name: Manual Zone
    icon: mdi:select-drag
    selection_type: MANUAL_RECTANGLE
    max_selections: 1
    service_call_schema:
      evaluate_data_as_template: true
      service: xiaomi_miot.call_action
      service_data:
        entity_id: "[[entity_id]]"
        siid: 14
        aiid: 1
        params:
          - 2
          - >-
            {"MapId":[[map_id]],"ExtraAreas":[{"vertexs":[[{% set
            s=[[[selection_unwrapped]]]
            %}{{s[0]}},{{s[3]}}],[{{s[2]}},{{s[3]}}],[{{s[2]}},{{s[1]}}],[{{s[0]}},{{s[1]}}]],"active":"normal","mode":"area"}]}
        force_params: true
    variables: {}
    predefined_selections: []
  - name: Single Point
    icon: mdi:map-marker-radius-outline
    selection_type: MANUAL_POINT
    run_immediately: true
    service_call_schema:
      evaluate_data_as_template: true
      service: xiaomi_miot.call_action
      service_data:
        entity_id: "[[entity_id]]"
        siid: 14
        aiid: 1
        params:
          - 4
          - >-
            {"MapId":[[map_id]],"ExtraAreas":[{"name":"point","id":301,"tag":"5","vertexs":
            {% set s=[[[selection_unwrapped]]]%}
            [[{{s[0]-[[point_size]]}},{{s[1]+[[point_size]]}}],
            [{{s[0]+[[point_size]]}},{{s[1]+[[point_size]]}}],
            [{{s[0]+[[point_size]]}},{{s[1]-[[point_size]]}}],
            [{{s[0]-[[point_size]]}},{{s[1]-[[point_size]]}}]],"active":"normal","mode":"point"}]}
    predefined_selections: []
    variables:
      point_size: 200
icons:
  - icon: mdi:play
    conditions:
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        value_not: cleaning
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        value_not: error
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        value_not: returning
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        value_not: paused
    tooltip: Start
    tap_action:
      action: call-service
      service: vacuum.start
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
  - icon: mdi:play
    conditions:
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        value: paused
    tooltip: Continue
    tap_action:
      action: call-service
      service: xiaomi_miot.call_action
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
        siid: 8
        aiid: 5
  - icon: mdi:pause
    conditions:
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        value_not: docked
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        value_not: idle
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        value_not: error
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        value_not: returning
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        value_not: paused
    tooltip: Pause
    tap_action:
      action: call-service
      service: xiaomi_miot.call_action
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
        siid: 8
        aiid: 8
  - icon: mdi:stop
    conditions:
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        value_not: docked
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        value_not: idle
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        value_not: error
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        value_not: paused
    tooltip: Stop
    tap_action:
      action: call-service
      service: vacuum.stop
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
  - icon: mdi:home-map-marker
    conditions:
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        value_not: docked
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        value_not: returning
    tooltip: Return to base
    tap_action:
      action: call-service
      service: vacuum.return_to_base
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
  - menu_id: water_level
    icon: mdi:water-off
    label: No Water
    conditions:
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: custom.water_level
        value: "0"
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: custom.mop
        value_not: "0"
    tooltip: Change Water level
    tap_action:
      action: call-service
      service: xiaomi_miot.set_miot_property
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
        siid: 8
        piid: 11
        value: 0
  - menu_id: water_level
    icon: mdi:wave
    label: Small
    conditions:
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: custom.water_level
        value: "1"
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: custom.mop
        value_not: "0"
    tooltip: Change Water level
    tap_action:
      action: call-service
      service: xiaomi_miot.set_miot_property
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
        siid: 8
        piid: 11
        value: 1
  - menu_id: water_level
    icon: mdi:waves
    label: Middle
    conditions:
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: custom.water_level
        value: "2"
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: custom.mop
        value_not: "0"
    tooltip: Change Water level
    tap_action:
      action: call-service
      service: xiaomi_miot.set_miot_property
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
        siid: 8
        piid: 11
        value: 2
  - menu_id: water_level
    icon: mdi:water
    label: Max
    conditions:
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: custom.water_level
        value: "3"
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: custom.mop
        value_not: "0"
    tooltip: Change Water level
    tap_action:
      action: call-service
      service: xiaomi_miot.set_miot_property
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
        siid: 8
        piid: 11
        value: 3
  - icon: mdi:water-off
    conditions:
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: custom.mop
        value_not: "0"
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: custom.water_level
        value_not: "0"
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: custom.water_level
        value_not: "1"
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: custom.water_level
        value_not: "2"
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: custom.water_level
        value_not: "3"
    tooltip: Change Water level
    tap_action:
      action: call-service
      service: xiaomi_miot.set_miot_property
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
        siid: 8
        piid: 11
        value: 0
  - menu_id: fan_speed
    icon: mdi:fan-alert
    label: Disabled
    conditions:
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: fan_speed
        value: Sweep
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
        fan_speed: Sweep
  - menu_id: fan_speed
    icon: mdi:fan-remove
    label: Silent
    conditions:
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: fan_speed
        value: Silent
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
        fan_speed: Silent
  - menu_id: fan_speed
    icon: mdi:fan-speed-1
    label: Basic
    conditions:
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: fan_speed
        value: Basic
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
        fan_speed: Basic
  - menu_id: fan_speed
    icon: mdi:fan-speed-2
    label: Strong
    conditions:
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: fan_speed
        value: Strong
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
        fan_speed: Strong
  - menu_id: fan_speed
    icon: mdi:fan-speed-3
    label: Full Speed
    conditions:
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: fan_speed
        value: Full Speed
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
        fan_speed: Full Speed
  - icon: mdi:land-plots-marker
    tooltip: Find robot
    tap_action:
      action: call-service
      service: xiaomi_miot.call_action
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
        siid: 8
        aiid: 1
  - menu_id: dust_collection
    icon: mdi:download-off
    label: Disabled
    conditions:
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: custom.work_station_freq
        value: "0"
    tooltip: Change Dust collection times
    tap_action:
      action: call-service
      service: xiaomi_miot.set_miot_property
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
        siid: 8
        piid: 2
        value: 0
  - menu_id: dust_collection
    icon: mdi:download
    label: Every time
    conditions:
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: custom.work_station_freq
        value: "1"
    tooltip: Change Dust collection times
    tap_action:
      action: call-service
      service: xiaomi_miot.set_miot_property
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
        siid: 8
        piid: 2
        value: 1
  - menu_id: dust_collection
    icon: mdi:download
    label: Every 2 times
    conditions:
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: custom.work_station_freq
        value: "2"
    tooltip: Change Dust collection times
    tap_action:
      action: call-service
      service: xiaomi_miot.set_miot_property
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
        siid: 8
        piid: 2
        value: 2
  - menu_id: dust_collection
    icon: mdi:download
    label: Every 3 times
    conditions:
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: custom.work_station_freq
        value: "3"
    tooltip: Change Dust collection times
    tap_action:
      action: call-service
      service: xiaomi_miot.set_miot_property
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
        siid: 8
        piid: 2
        value: 3
  - icon: mdi:download-box-outline
    tooltip: Clear vacuum
    conditions:
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        value: docked
    tap_action:
      action: call-service
      service: xiaomi_miot.call_action
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
        siid: 8
        aiid: 6
  - icon: mdi:numeric-2-box-multiple-outline
    tooltip: Double Clean ON
    conditions:
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: custom.double_clean
        value: true
    tap_action:
      action: call-service
      service: xiaomi_miot.set_miot_property
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
        siid: 8
        piid: 20
        value: false
  - icon: mdi:numeric-1-box-outline
    tooltip: Double Clean OFF
    conditions:
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: custom.double_clean
        value_not: true
    tap_action:
      action: call-service
      service: xiaomi_miot.set_miot_property
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
        siid: 8
        piid: 20
        value: true
  - icon: mdi:alarm-light-off
    tooltip: Radar priority OFF
    conditions:
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: custom.lidar_collision
        value_not: 1
    tap_action:
      action: call-service
      service: xiaomi_miot.set_miot_property
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
        siid: 8
        piid: 23
        value: 1
  - icon: mdi:alarm-light
    tooltip: Radar priority ON
    conditions:
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: custom.lidar_collision
        value: 1
    tap_action:
      action: call-service
      service: xiaomi_miot.set_miot_property
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
        siid: 8
        piid: 23
        value: 0
  - icon: mdi:transit-detour
    tooltip: Y mopping ON
    conditions:
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: custom.mop
        value: "1"
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: map.path_type
        value: "1"
    tap_action:
      action: call-service
      service: xiaomi_miot.set_miot_property
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
        siid: 13
        piid: 8
        value: 0
  - icon: mdi:transit-connection-horizontal
    tooltip: Y mopping OFF
    conditions:
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: custom.mop
        value: "1"
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: map.path_type
        value_not: "1"
    tap_action:
      action: call-service
      service: xiaomi_miot.set_miot_property
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
        siid: 13
        piid: 8
        value: 1
  - icon: mdi:vacuum
    tooltip: Carpet boost ON
    conditions:
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: custom.auto_boost
        value: "1"
    tap_action:
      action: call-service
      service: xiaomi_miot.set_miot_property
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
        siid: 8
        piid: 9
        value: 0
  - icon: mdi:vacuum-outline
    tooltip: Carpet boost OFF
    conditions:
      - entity: vacuum.roidmi_v60_1c28_robot_cleaner
        attribute: custom.auto_boost
        value: "0"
    tap_action:
      action: call-service
      service: xiaomi_miot.set_miot_property
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
        siid: 8
        piid: 9
        value: 1
  - icon: mdi:cloud-refresh-variant-outline
    tooltip: Refresh
    tap_action:
      action: call-service
      service: homeassistant.update_entity
      target:
        entity_id: camera.xiaomi_cloud_map_extractor
tiles:
  - tile_id: status
    entity: vacuum.roidmi_v60_1c28_robot_cleaner
    label: Status
    attribute: vacuum.status_desc
    icon: mdi:robot-vacuum
  - tile_id: status
    entity: vacuum.roidmi_v60_1c28_robot_cleaner
    label: Sweep Type
    attribute: vacuum.sweep_type
    icon: mdi:broom
    translations:
      "0": Sweep
      "1": Mop
      "2": Mop And Sweep
  - tile_id: battery_level
    entity: sensor.roidmi_v60_1c28_battery_level
    icon: mdi:battery
    label: Battery
  - tile_id: main_brush_level
    entity: vacuum.roidmi_v60_1c28_robot_cleaner
    attribute: brush_cleaner.brush_life_level
    unit: "%"
    label: Main brush
    icon: mdi:spirit-level
    tap_action:
      action: call-service
      confirmation:
        text: Are you sure you replaced Main Brush?
      service: xiaomi_miot.call_action
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
        siid: 11
        aiid: 1
  - tile_id: side_brush_level
    entity: vacuum.roidmi_v60_1c28_robot_cleaner
    attribute: brush_life_level-12-2
    unit: "%"
    label: Side brush
    icon: mdi:ceiling-fan
    tap_action:
      action: call-service
      confirmation:
        text: Are you sure you replaced Side Brush?
      service: xiaomi_miot.call_action
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
        siid: 12
        aiid: 1
  - tile_id: sensor_level
    entity: vacuum.roidmi_v60_1c28_robot_cleaner
    attribute: brush_life_level-15-2
    unit: "%"
    label: Sensors
    icon: mdi:leak
    tap_action:
      action: call-service
      confirmation:
        text: Are you sure you wiped sensor?
      service: xiaomi_miot.call_action
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
        siid: 15
        aiid: 1
  - tile_id: filter_level
    entity: vacuum.roidmi_v60_1c28_robot_cleaner
    attribute: filter.filter_life_level
    unit: "%"
    label: Filter
    icon: mdi:air-filter
    tap_action:
      action: call-service
      confirmation:
        text: Are you sure you replaced Filter?
      service: xiaomi_miot.call_action
      service_data:
        entity_id: vacuum.roidmi_v60_1c28_robot_cleaner
        siid: 10
        aiid: 1
  - tile_id: total_clean_time
    entity: vacuum.roidmi_v60_1c28_robot_cleaner
    attribute: custom.total_clean_time
    multiplier: 0.01666666666
    precision: 0
    unit: min
    icon: mdi:timer
    label: Cleaning time
  - tile_id: clean_counts
    entity: vacuum.roidmi_v60_1c28_robot_cleaner
    attribute: custom.clean_counts
    unit: Times
    icon: mdi:vacuum
    label: Clean times
  - tile_id: total_clean_areas
    entity: vacuum.roidmi_v60_1c28_robot_cleaner
    attribute: custom.total_clean_areas
    unit: m²
    icon: mdi:square-opacity
    label: Cleaning area
  - tile_id: fault
    entity: vacuum.roidmi_v60_1c28_robot_cleaner
    label: Fault
    attribute: vacuum.fault
    icon: mdi:alert-circle
    translations:
      "0": None
      "1": Low battery, start recharging
      "2": Low power, start shutting down
      "3": The main wheel is abnormal, please check whether the main wheel is stuck
      "4": Please check if the edge is jammed
      "5": Machine tilt, please move to level and start
      "6": Please check whether the top radar is blocked or jammed
      "7": Front collision sensor abnormal
      "8": Abnormal sensor on the right side along the wall
      "9": Please check whether the main brush is entangled or jammed
      "10": Please check whether the side brush is entangled or jammed
      "11": Abnormal fan
      "12": The radar cover is jammed
      "13": >-
        Please clean the dust box and filter screen, or check whether the dust
        box and filter screen are in place
      "14": Take out the dust box
      "15": Please clean the dust box and filter screen
      "16": The machine is trapped, please move to the new position and start
      "17": >-
        The machine is suspended. Please put it back on the level ground before
        starting
      "18": >-
        The water tank has been taken out. Please put it back into the water
        tank before starting
      "19": There is not enough water in the tank
      "20": The specified area cannot be reached
      "21": Please move out of the restricted area before starting
      "22": Please stay away from the cliff before starting
      "23": Pump current error
      "24": Recharge failed, charging point not found
      "25": Radar speed error
      "27": Please check whether the top radar is jammed
      "30": Radar open circuit abnormal
      "31": Battery abnormal
      "32": Middle brush abnormal
      "33": Main wheel abnormal
      "34": Side brush abnormal
      "35": Fan abnormal
      "37": Firmware upgrade failed due to insufficient conditions
additional_presets: []
```

### Javascript errors shown in the browser's console (if applicable)

```shell
no errors in console
```
