### ISSUE TITLE
Roborock Core Status always on "unknow"

### ISSUE THREAD

**Issue by diverudi** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#835]
### Checklist

- [x] I have updated the card to the latest version available
- [x] I have cleared the cache of my browser
- [x] I have checked if the problem is already reported

### The problem

Since I updated my Roborock S7 Max Ultra to core and installed the Roborock Custom Map the status 
on the Map shows always "unknown", then I click on status I get the vacuum menu and the stuas is shown as it should.

### What version of a card has described problem?

2.3.1

### What vacuum model do you have problems with?

roborock.vacuum.a27

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/roborock

### What browser (browsers/apps) does have this problem?

Chrome

### What version of Home Assistant do you use?

2025.4.2

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: image.roborock_s7_maxv_erdgeschoss_custom
calibration_source:
  camera: true
entity: vacuum.roborock_s7_maxv
vacuum_platform: Roborock
map_modes:
  - template: vacuum_clean_segment
    name: Erdgeschoß
    icon: mdi:home-floor-0
    predefined_selections:
      - id: "16"
        icon:
          name: mdi:sofa
          x: 23500
          "y": 25950
        label:
          text: Wohnzimmer
          x: 23500
          "y": 25950
          offset_y: 35
        outline:
          - - 19250
            - 23900
          - - 27750
            - 23900
          - - 27750
            - 28000
          - - 19250
            - 28000
      - id: "17"
        icon:
          name: mdi:table-furniture
          x: 31550
          "y": 25500
        label:
          text: Esszimmer
          x: 31550
          "y": 25500
          offset_y: 35
        outline:
          - - 27800
            - 22700
          - - 35300
            - 22700
          - - 35300
            - 28300
          - - 27800
            - 28300
      - id: "18"
        icon:
          name: mdi:toilet
          x: 26750
          "y": 19775
        label:
          text: Gäste WC
          x: 26750
          "y": 19775
          offset_y: 35
        outline:
          - - 26100
            - 19300
          - - 27400
            - 19300
          - - 27400
            - 20250
          - - 26100
            - 20250
      - id: "19"
        icon:
          name: mdi:desk
          x: 21675
          "y": 22750
        label:
          text: Arbeitszimmer
          x: 21675
          "y": 22750
          offset_y: 35
        outline:
          - - 20150
            - 21600
          - - 23200
            - 21600
          - - 23200
            - 23900
          - - 20150
            - 23900
      - id: "20"
        icon:
          name: mdi:floor-plan
          x: 23900
          "y": 22225
        label:
          text: EG Flur
          x: 23900
          "y": 22225
          offset_y: 35
        outline:
          - - 21700
            - 19250
          - - 26100
            - 19250
          - - 26100
            - 25200
          - - 21700
            - 25200
      - id: "21"
        icon:
          name: mdi:countertop
          x: 26925
          "y": 22500
        label:
          text: Küche
          x: 26925
          "y": 22500
          offset_y: 35
        outline:
          - - 25950
            - 20900
          - - 27900
            - 20900
          - - 27900
            - 24100
          - - 25950
            - 24100
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - name: Pfad
    icon: mdi:map-marker-path
    run_immediately: false
    coordinates_rounding: true
    selection_type: MANUAL_PATH
    max_selections: 999
    repeats_type: NONE
    max_repeats: 1
    service_call_schema:
      service: script.vacuum_follow_path
      service_data:
        service: vacuum.send_command
        mode: send_command
        path: "[[selection]]"
        entity_id: "[[entity_id]]"
    predefined_selections: []
    variables: {}
tiles:
  - tile_id: status
    entity: vacuum.roborock_s7_maxv
    label: Status
    attribute: status
    icon: mdi:robot-vacuum
    translations:
      starting: Starting
      charger disconnected: Charger disconnected
      idle: Idle
      remote control active: Remote control active
      cleaning: Cleaning
      returning home: Returning home
      manual mode: Manual mode
      charging: Charging
      charging problem: Charging problem
      paused: Paused
      spot cleaning: Spot cleaning
      error: Error
      shutting down: Shutting down
      updating: Updating
      docking: Docking
      going to target: Going to target
      zoned cleaning: Zoned cleaning
      segment cleaning: Segment cleaning
      emptying the bin: Emptying the bin
      charging complete: Charging complete
      device offline: Device offline
  - tile_id: battery_level
    entity: vacuum.roborock_s7_maxv
    label: Battery
    attribute: battery_level
    icon: mdi:battery-charging-100
    unit: "%"
  - tile_id: fan_speed
    entity: vacuum.roborock_s7_maxv
    label: Fan speed
    attribute: fan_speed
    icon: mdi:fan
    translations:
      silent: Silent
      standard: Standard
      medium: Medium
      turbo: Turbo
      auto: Auto
      gentle: Gentle
icons:
  - icon: mdi:play
    conditions:
      - entity: vacuum.roborock_s7_maxv
        value_not: cleaning
      - entity: vacuum.roborock_s7_maxv
        value_not: error
      - entity: vacuum.roborock_s7_maxv
        value_not: returning
    tooltip: Start
    tap_action:
      action: call-service
      service: vacuum.start
      service_data:
        entity_id: vacuum.roborock_s7_maxv
  - icon: mdi:pause
    conditions:
      - entity: vacuum.roborock_s7_maxv
        value_not: docked
      - entity: vacuum.roborock_s7_maxv
        value_not: idle
      - entity: vacuum.roborock_s7_maxv
        value_not: error
      - entity: vacuum.roborock_s7_maxv
        value_not: paused
    tooltip: Pause
    tap_action:
      action: call-service
      service: vacuum.pause
      service_data:
        entity_id: vacuum.roborock_s7_maxv
  - icon: mdi:stop
    conditions:
      - entity: vacuum.roborock_s7_maxv
        value_not: docked
      - entity: vacuum.roborock_s7_maxv
        value_not: idle
      - entity: vacuum.roborock_s7_maxv
        value_not: error
      - entity: vacuum.roborock_s7_maxv
        value_not: paused
    tooltip: Stop
    tap_action:
      action: call-service
      service: vacuum.stop
      service_data:
        entity_id: vacuum.roborock_s7_maxv
  - icon: mdi:home-map-marker
    conditions:
      - entity: vacuum.roborock_s7_maxv
        value_not: docked
      - entity: vacuum.roborock_s7_maxv
        value_not: returning
    tooltip: Return to base
    tap_action:
      action: call-service
      service: vacuum.return_to_base
      service_data:
        entity_id: vacuum.roborock_s7_maxv
  - icon: mdi:target-variant
    conditions:
      - entity: vacuum.roborock_s7_maxv
        value_not: docked
      - entity: vacuum.roborock_s7_maxv
        value_not: error
      - entity: vacuum.roborock_s7_maxv
        value_not: cleaning
      - entity: vacuum.roborock_s7_maxv
        value_not: returning
    tooltip: Clean spot
    tap_action:
      action: call-service
      service: vacuum.clean_spot
      service_data:
        entity_id: vacuum.roborock_s7_maxv
  - icon: mdi:map-marker
    tooltip: Finden
    tap_action:
      action: call-service
      service: vacuum.locate
      service_data:
        entity_id: vacuum.roborock_s7_maxv
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.roborock_s7_maxv
        attribute: fan_speed
        value: "off"
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_s7_maxv
        fan_speed: silent
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.roborock_s7_maxv
        attribute: fan_speed
        value: silent
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_s7_maxv
        fan_speed: balanced
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.roborock_s7_maxv
        attribute: fan_speed
        value: balanced
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_s7_maxv
        fan_speed: turbo
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.roborock_s7_maxv
        attribute: fan_speed
        value: turbo
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_s7_maxv
        fan_speed: max
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.roborock_s7_maxv
        attribute: fan_speed
        value: max
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_s7_maxv
        fan_speed: max_plus
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.roborock_s7_maxv
        attribute: fan_speed
        value: max_plus
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_s7_maxv
        fan_speed: custom
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.roborock_s7_maxv
        attribute: fan_speed
        value: custom
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_s7_maxv
        fan_speed: "off"
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.roborock_s7_maxv
        attribute: fan_speed
        value_not: "off"
      - entity: vacuum.roborock_s7_maxv
        attribute: fan_speed
        value_not: silent
      - entity: vacuum.roborock_s7_maxv
        attribute: fan_speed
        value_not: balanced
      - entity: vacuum.roborock_s7_maxv
        attribute: fan_speed
        value_not: turbo
      - entity: vacuum.roborock_s7_maxv
        attribute: fan_speed
        value_not: max
      - entity: vacuum.roborock_s7_maxv
        attribute: fan_speed
        value_not: max_plus
      - entity: vacuum.roborock_s7_maxv
        attribute: fan_speed
        value_not: custom
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_s7_maxv
  - icon: mdi:water-off
    conditions:
      - entity: vacuum.roborock_s7_maxv
        attribute: waterBoxMode
        value: 200
    tooltip: Change mop intensity
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        command: set_water_box_custom_mode
        params: 201
      target:
        entity_id: vacuum.roborock_s7_maxv
  - icon: mdi:wave
    conditions:
      - entity: vacuum.roborock_s7_maxv
        attribute: waterBoxMode
        value: 201
    tooltip: Change mop intensity
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        command: set_water_box_custom_mode
        params: 202
      target:
        entity_id: vacuum.roborock_s7_maxv
  - icon: mdi:waves-arrow-up
    conditions:
      - entity: vacuum.roborock_s7_maxv
        attribute: waterBoxMode
        value: 202
    tooltip: Change mop intensity
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        command: set_water_box_custom_mode
        params: 203
      target:
        entity_id: vacuum.roborock_s7_maxv
  - icon: mdi:waves
    conditions:
      - entity: vacuum.roborock_s7_maxv
        attribute: waterBoxMode
        value: 203
    tooltip: Mopp Intensität
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        command: set_water_box_custom_mode
        params: 200
      target:
        entity_id: vacuum.roborock_s7_maxv
  - icon: mdi:waves
    conditions:
      - entity: vacuum.roborock_s7_maxv
        attribute: waterBoxMode
        value_not: 200
      - entity: vacuum.roborock_s7_maxv
        attribute: waterBoxMode
        value_not: 201
      - entity: vacuum.roborock_s7_maxv
        attribute: waterBoxMode
        value_not: 202
      - entity: vacuum.roborock_s7_maxv
        attribute: waterBoxMode
        value_not: 203
visibility:
  - condition: state
    entity: select.roborock_s7_maxv_ausgewahlte_karte
    state: Keller
title: Erdgeschoß
map_locked: true
```

### Javascript errors shown in the browser's console (if applicable)

```shell

```
