### ISSUE TITLE
Add support for setting default repeat count for repeats_type: EXTERNAL

### ISSUE THREAD

**Issue by zane-lazare** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#836]
### 🚀 Feature Request: Set default repeat count for `repeats_type: EXTERNAL`

---

#### Problem

When using `repeats_type: EXTERNAL` in a `map_mode` (e.g., `ROOM`, `MANUAL_RECTANGLE`), the repeat selector always defaults to `1`. There is currently **no configuration option** to define a different default value (e.g., 2 or 3), even if `max_repeats` allows it.

This forces an extra manual step for users who consistently want multiple passes — a common use case for room cleaning. 

In contrast, `repeats_type: INTERNAL` allows a hardcoded repeat value via `variables.repeats`, but this disables user input and prevents adjustment.

---

#### Proposed Solution

Add support for an optional parameter:

```yaml
default_repeats: 2
```

When used with `repeats_type: EXTERNAL`, this would:

- Set the initial/default value of the repeat dropdown to 2
- Allow the user to still adjust the value up to `max_repeats`

#### Example Configuration
```yaml
map_modes:
  - name: Rooms
    selection_type: ROOM
    repeats_type: EXTERNAL
    max_repeats: 3
    default_repeats: 2
    service_call_schema:
      service: vacuum.send_command
      service_data:
        command: app_segment_clean
        params:
          - segments: "[[selection]]"
            repeats: "[[repeats]]"
        entity_id: "[[entity_id]]"
```

#### Benefits
- Provides a smoother user experience for common multi-pass cleaning workflows
- Aligns `EXTERNAL` repeat behavior with the flexibility already possible using `INTERNAL`
- Avoids requiring hidden values while still letting users customize per-clean
- Supports opportunities for increase `Spouse Approval Factor`
