### ISSUE TITLE
xiaomi_miio.vacuum_clean_segment not found

### ISSUE THREAD

**Issue by KiloDelta0** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#838]
### Checklist

- [x] I have updated the card to the latest version available
- [x] I have cleared the cache of my browser
- [x] I have checked if the problem is already reported

### The problem

Hi All,

Trying to use the goto, or room clean results in this error. Failed to call service Service xiaomi_miio.vacuum_clean_segment not found Action xiaomi_miio.vacuum_clean_segment not found

i assume the same for zones but dont have any set up.

### What version of a card has described problem?

v2.3.1

### What vacuum model do you have problems with?

Dreambot.d10.plus

### Which integration do you use to control your vacuum (link)?

https://community.home-assistant.io/t/custom-component-dreame-vacuum/473026

### What browser (browsers/apps) does have this problem?

Chrome/Homeassistant app

### What version of Home Assistant do you use?

core-2025.4.4

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.dreamebot_d10_plus_map
calibration_source:
  camera: true
entity: vacuum.dreamebot_d10_plus
vacuum_platform: Xiaomi Miio
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_clean_segment
    predefined_selections:
      - id: "1"
        icon:
          name: mdi:room-service-outline
          x: -3500
          "y": 600
        label:
          text: Dining Hall
          x: -3500
          "y": 600
          offset_y: 35
        outline:
          - - -4700
            - -950
          - - -2300
            - -950
          - - -2300
            - 1600
          - - -4700
            - 1600
      - id: "2"
        icon:
          name: mdi:foot-print
          x: -1600
          "y": -1200
        label:
          text: Corridor
          x: -1600
          "y": -1200
          offset_y: 35
        outline:
          - - -2300
            - -2000
          - - -950
            - -2000
          - - -950
            - -500
          - - -2300
            - -500
      - id: "3"
        icon:
          name: mdi:chef-hat
          x: -3350
          "y": -2300
        label:
          text: Kitchen
          x: -3350
          "y": -2300
          offset_y: 35
        outline:
          - - -3950
            - -3650
          - - -2250
            - -3650
          - - -2250
            - -950
          - - -3950
            - -950
      - id: "4"
        icon:
          name: mdi:monitor-shimmer
          x: 1650
          "y": 150
        label:
          text: Office
          x: 1650
          "y": 150
          offset_y: 35
        outline:
          - - -1000
            - -1000
          - - 3900
            - -1000
          - - 3900
            - 1500
          - - -1000
            - 1500
      - id: "5"
        icon:
          name: mdi:toilet
          x: -1550
          "y": -2850
        label:
          text: Bathroom
          x: -1550
          "y": -2850
          offset_y: 35
        outline:
          - - -1950
            - -3950
          - - -1100
            - -3950
          - - -1100
            - -2000
          - - -1950
            - -2000
      - id: "6"
        icon:
          name: mdi:sofa-outline
          x: -100
          "y": -2700
        label:
          text: Living Room
          x: -100
          "y": -2700
          offset_y: 35
        outline:
          - - -1000
            - -4300
          - - 3850
            - -4300
          - - 3850
            - -1000
          - - -1000
            - -1000
  - template: vacuum_clean_segment
    predefined_selections:
      - id: "1"
        icon:
          name: mdi:room-service-outline
          x: -3500
          "y": 600
        label:
          text: Dining Hall
          x: -3500
          "y": 600
          offset_y: 35
        outline:
          - - -4700
            - -950
          - - -2300
            - -950
          - - -2300
            - 1600
          - - -4700
            - 1600
      - id: "2"
        icon:
          name: mdi:foot-print
          x: -1600
          "y": -1200
        label:
          text: Corridor
          x: -1600
          "y": -1200
          offset_y: 35
        outline:
          - - -2300
            - -2000
          - - -950
            - -2000
          - - -950
            - -500
          - - -2300
            - -500
      - id: "3"
        icon:
          name: mdi:chef-hat
          x: -3350
          "y": -2300
        label:
          text: Kitchen
          x: -3350
          "y": -2300
          offset_y: 35
        outline:
          - - -3950
            - -3650
          - - -2250
            - -3650
          - - -2250
            - -950
          - - -3950
            - -950
      - id: "4"
        icon:
          name: mdi:monitor-shimmer
          x: 1650
          "y": 150
        label:
          text: Office
          x: 1650
          "y": 150
          offset_y: 35
        outline:
          - - -1000
            - -1000
          - - 3900
            - -1000
          - - 3900
            - 1500
          - - -1000
            - 1500
      - id: "5"
        icon:
          name: mdi:toilet
          x: -1550
          "y": -2850
        label:
          text: Bathroom
          x: -1550
          "y": -2850
          offset_y: 35
        outline:
          - - -1950
            - -3950
          - - -1100
            - -3950
          - - -1100
            - -2000
          - - -1950
            - -2000
      - id: "6"
        icon:
          name: mdi:sofa-outline
          x: -100
          "y": -2700
        label:
          text: Living Room
          x: -100
          "y": -2700
          offset_y: 35
        outline:
          - - -1000
            - -4300
          - - 3850
            - -4300
          - - 3850
            - -1000
          - - -1000
            - -1000
map_locked: true
```

### Javascript errors shown in the browser's console (if applicable)

```shell

```
