### ISSUE TITLE
Invalid calibration, please check your configuration Error

### ISSUE THREAD

**Issue by filipcoja** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#840]
### Checklist

- [x] I have updated the card to the latest version available
- [x] I have cleared the cache of my browser
- [x] I have checked if the problem is already reported

### The problem

I'm using my Roborock S5 Max via the official Roborock Integration.

I've installed this integration via HACS and the [](https://github.com/Lash-L/RoborockCustomMap#roborock-custom-map).

This is my config:

```
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: image.roborock_s5_max_map_0
calibration_source:
  camera: true
entity: vacuum.roborock_s5_max
vacuum_platform: Roborock

```

So the same config as shown in the README here:  [](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/blob/master/docs/templates/Roborock.md )

And I get the error: "nvalid calibration, please check your configuration"

Here an image:

![Image](https://github.com/user-attachments/assets/8976467a-4c58-4f99-a99c-99b2e459a5a5)

### What version of a card has described problem?

2.3.1

### What vacuum model do you have problems with?

Roborock S5 Max

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/roborock/

### What browser (browsers/apps) does have this problem?

Firefox

### What version of Home Assistant do you use?

2025.4.4

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: image.roborock_s5_max_map_0
calibration_source:
  camera: true
entity: vacuum.roborock_s5_max
vacuum_platform: Roborock
```

### Javascript errors shown in the browser's console (if applicable)

```shell

```
