### ISSUE TITLE
Eufy RobovVac

### ISSUE THREAD

**Issue by mikefincher76** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#842]
### Integration repository

https://github.com/CodeFoodPixels/robovac

### Supported features

- [x] Zone cleaning (using 4 coordinates)
- [x] Room cleaning (using room id/number)
- [ ] Going to point (using 2 coordinates)
- [ ] Cleaning a point (using 2 coordinates)
- [ ] Others

### Checklist

- [ ] I have sent info about entities to `piotr.machowski.dev [at] gmail.com` ([Retrieving entities info](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/594); please provide your GitHub username in the email)

### Vacuum entity/entities

```yaml
Eufy Robovac X8

Entity: sensor.robovac_battery
State: 100
Attributes:
unit_of_measurement: %
device_class: battery
friendly_name: RovoVac

Entity: update.eufy_robovac_update
State: off
Attributes:
auto_update: false
display_precision: 0
installed_version: v1.2.11
in_progress: false
latest_version: v1.2.11
release_summary: null
release_url: https://github.com/CodeFoodPixels/robovac/releases/v1.2.11
skipped_version: null
title: null
update_percentage: null
entity_picture: https://brands.home-assistant.io/_/robovac/icon.png
friendly_name: Eufy RoboVac update
supported_features: 23

Entity: vacuum.robovac
State: idle
Attributes:
fan_speed_list: Pure, Standard, Turbo, Max
battery_level: 100
battery_icon: mdi:battery
fan_speed: Turbo
friendly_name: RoboVac
supported_features: 16252
cleaning_area: 108
cleaning_time: 5340
auto_return: true
boost_iq: true
mode: room
```

### Service calls

```yaml
action: vacuum.pause
data: {}

action: vacuum.return_to_base
data: {}

action: vacuum.stop
data: {}

action: vacuum.start
data: {}

action: vacuum.set_fan_speed
data: {}

action: vacuum.locate
data: {}
```
