### ISSUE TITLE
Rotate map

### ISSUE THREAD

**Issue by Maximus97** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#843]
### Description

Possibility to rotate the map, in some card layouts it makes more sense to have it horizontal instead of vertical and vice versa

### Solution

Possibility to rotate the map 90, 180, or 270 degrees

**Comment by PiotrMachowski** [comment]
Which integration do you use to get the map?

**Comment by Maximus97** [comment]
I use this https://github.com/Lash-L/RoborockCustomMap

**Comment by Maximus97** [comment]
Any news on this?

**Comment by PiotrMachowski** [comment]
https://github.com/Lash-L/RoborockCustomMap/issues/7

**Comment by ramaxa9** [comment]
my card displayed in vertical mode, even if im rotating map-image with card-mod

<img width="500" height="792" alt="Image" src="https://github.com/user-attachments/assets/78df5dcc-43ec-4138-945f-599045cd6836" />

**Comment by DohmenICT** [comment]
I was able to get the map rotation with adding this card_mod to my yaml:

card_mod:
  style: |
    #map-image {
      transform: rotate(90deg);        
    }

![image](https://github.com/user-attachments/assets/8b1995d3-3d39-4747-a08d-4132ca9b4a69)

![image](https://github.com/user-attachments/assets/00483298-00be-4f22-9973-a4f5fc129f6b)

**Comment by loryanstrant** [comment]
> I was able to get the map rotation with adding this card_mod to my yaml:
> 
> card_mod: style: | #map-image { transform: rotate(90deg); }
> 

Thank you for sharing that!
It's been bugging me for ages, but this did the trick (180 degrees in my case).

**Comment by wecoyote5** [comment]
Unfortunately, that doesn't help with the smart start overlay and associated icon/text identifiers. For all the wonderful work put into this card that feature may be too much of an ask so we'll have to dig deeper into the UIX (newer card_mod integration) config.

**Comment by cataseven** [comment]
@DohmenICT @PiotrMachowski @loryanstrant @wecoyote5 @ramaxa9 @Maximus97 

Opened PR https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/pull/949

for quick install to test here is the js file: 

[xiaomi-vacuum-map-card.js](https://github.com/user-attachments/files/30677783/xiaomi-vacuum-map-card.js)

```
type: custom:xiaomi-vacuum-map-card
entity: vacuum.roborock
preset_name: Ground floor
map_source:
  camera: camera.roborock_ground_floor
calibration_source:
  camera: true
vacuum_platform: Roborock
map_rotation: 90
additional_presets:
  - preset_name: First floor
    entity: vacuum.roborock
    map_source:
      camera: camera.roborock_first_floor
    calibration_source:
      camera: true
    vacuum_platform: Roborock
map_view_storage_key: vacuum-overview 
```
