### ISSUE TITLE
The Dream X40 map has no walls

### ISSUE THREAD

**Issue by sgeneralov13** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#847]
### Checklist

- [x] I have updated the card to the latest version available
- [x] I have cleared the cache of my browser
- [x] I have checked if the problem is already reported

### The problem

map_source:
  camera: camera.x40_pro_map
![Image](https://github.com/user-attachments/assets/9e06641b-0ac4-4196-8544-4ca550cef1a5)

Dreame Vacuum v2.0.0b19

### What version of a card has described problem?

2.3.1

### What vacuum model do you have problems with?

dreame.vacuum.r2310e

### Which integration do you use to control your vacuum (link)?

https://github.com/Tasshack/dreame-vacuum

### What browser (browsers/apps) does have this problem?

Chrome 

### What version of Home Assistant do you use?

 2025.3.3

### What type of installation are you running?

Home Assistant Core

### Card's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.x40_pro_map
calibration_source:
  camera: true
entity: vacuum.x40_pro
vacuum_platform: Tasshack/dreame-vacuum
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_point
  - template: vacuum_goto
  - template: vacuum_clean_segment
    predefined_selections:
      - id: "1"
        icon:
          name: mdi:room-service-outline
          x: -750
          "y": 3400
        label:
          text: Dining Hall
          x: -750
          "y": 3400
          offset_y: 35
        outline:
          - - -3100
            - 800
          - - 1550
            - 800
          - - 1550
            - 4650
          - - -3100
            - 4650
      - id: "2"
        icon:
          name: mdi:foot-print
          x: 1250
          "y": -700
        label:
          text: Corridor
          x: 1250
          "y": -700
          offset_y: 35
        outline:
          - - -1850
            - -2250
          - - 2150
            - -2250
          - - 2150
            - 800
          - - -1850
            - 800
      - id: "3"
        icon:
          name: mdi:sofa-outline
          x: 3100
          "y": 1300
        label:
          text: Living Room
          x: 3100
          "y": 1300
          offset_y: 35
        outline:
          - - 2150
            - -2750
          - - 7300
            - -2750
          - - 7300
            - 4650
          - - 2150
            - 4650
      - id: "4"
        icon:
          name: mdi:bed-king-outline
          x: 3300
          "y": -4350
        label:
          text: Primary Bedroom
          x: 3300
          "y": -4350
          offset_y: 35
        outline:
          - - 2300
            - -6300
          - - 4250
            - -6300
          - - 4250
            - -2450
          - - 2300
            - -2450
  - template: vacuum_clean_segment
    predefined_selections:
      - id: "1"
        icon:
          name: mdi:room-service-outline
          x: -750
          "y": 3400
        label:
          text: Dining Hall
          x: -750
          "y": 3400
          offset_y: 35
        outline:
          - - -3100
            - 800
          - - 1550
            - 800
          - - 1550
            - 4650
          - - -3100
            - 4650
      - id: "2"
        icon:
          name: mdi:foot-print
          x: 1250
          "y": -700
        label:
          text: Corridor
          x: 1250
          "y": -700
          offset_y: 35
        outline:
          - - -1850
            - -2250
          - - 2150
            - -2250
          - - 2150
            - 800
          - - -1850
            - 800
      - id: "3"
        icon:
          name: mdi:sofa-outline
          x: 3100
          "y": 1300
        label:
          text: Living Room
          x: 3100
          "y": 1300
          offset_y: 35
        outline:
          - - 2150
            - -2750
          - - 7300
            - -2750
          - - 7300
            - 4650
          - - 2150
            - 4650
      - id: "4"
        icon:
          name: mdi:bed-king-outline
          x: 3300
          "y": -4350
        label:
          text: Primary Bedroom
          x: 3300
          "y": -4350
          offset_y: 35
        outline:
          - - 2300
            - -6300
          - - 4250
            - -6300
          - - 4250
            - -2450
          - - 2300
            - -2450
  - template: vacuum_clean_segment
    predefined_selections:
      - id: "1"
        icon:
          name: mdi:room-service-outline
          x: -750
          "y": 3400
        label:
          text: Dining Hall
          x: -750
          "y": 3400
          offset_y: 35
        outline:
          - - -3100
            - 800
          - - 1550
            - 800
          - - 1550
            - 4650
          - - -3100
            - 4650
      - id: "2"
        icon:
          name: mdi:foot-print
          x: 1250
          "y": -700
        label:
          text: Corridor
          x: 1250
          "y": -700
          offset_y: 35
        outline:
          - - -1850
            - -2250
          - - 2150
            - -2250
          - - 2150
            - 800
          - - -1850
            - 800
      - id: "3"
        icon:
          name: mdi:sofa-outline
          x: 3100
          "y": 1300
        label:
          text: Living Room
          x: 3100
          "y": 1300
          offset_y: 35
        outline:
          - - 2150
            - -2750
          - - 7300
            - -2750
          - - 7300
            - 4650
          - - 2150
            - 4650
      - id: "4"
        icon:
          name: mdi:bed-king-outline
          x: 3300
          "y": -4350
        label:
          text: Primary Bedroom
          x: 3300
          "y": -4350
          offset_y: 35
        outline:
          - - 2300
            - -6300
          - - 4250
            - -6300
          - - 4250
            - -2450
          - - 2300
            - -2450
  - template: vacuum_clean_segment
    predefined_selections:
      - id: "1"
        icon:
          name: mdi:room-service-outline
          x: -750
          "y": 3400
        label:
          text: Dining Hall
          x: -750
          "y": 3400
          offset_y: 35
        outline:
          - - -3100
            - 800
          - - 1550
            - 800
          - - 1550
            - 4650
          - - -3100
            - 4650
      - id: "2"
        icon:
          name: mdi:foot-print
          x: 1250
          "y": -700
        label:
          text: Corridor
          x: 1250
          "y": -700
          offset_y: 35
        outline:
          - - -1850
            - -2250
          - - 2150
            - -2250
          - - 2150
            - 800
          - - -1850
            - 800
      - id: "3"
        icon:
          name: mdi:sofa-outline
          x: 3100
          "y": 1300
        label:
          text: Living Room
          x: 3100
          "y": 1300
          offset_y: 35
        outline:
          - - 2150
            - -2750
          - - 7300
            - -2750
          - - 7300
            - 4650
          - - 2150
            - 4650
      - id: "4"
        icon:
          name: mdi:bed-king-outline
          x: 3300
          "y": -4350
        label:
          text: Primary Bedroom
          x: 3300
          "y": -4350
          offset_y: 35
        outline:
          - - 2300
            - -6300
          - - 4250
            - -6300
          - - 4250
            - -2450
          - - 2300
            - -2450
  - template: vacuum_clean_segment
    predefined_selections:
      - id: "1"
        icon:
          name: mdi:room-service-outline
          x: -750
          "y": 3400
        label:
          text: Dining Hall
          x: -750
          "y": 3400
          offset_y: 35
        outline:
          - - -3100
            - 800
          - - 1550
            - 800
          - - 1550
            - 4650
          - - -3100
            - 4650
      - id: "2"
        icon:
          name: mdi:foot-print
          x: 1250
          "y": -700
        label:
          text: Corridor
          x: 1250
          "y": -700
          offset_y: 35
        outline:
          - - -1850
            - -2250
          - - 2150
            - -2250
          - - 2150
            - 800
          - - -1850
            - 800
      - id: "3"
        icon:
          name: mdi:sofa-outline
          x: 3100
          "y": 1300
        label:
          text: Living Room
          x: 3100
          "y": 1300
          offset_y: 35
        outline:
          - - 2150
            - -2750
          - - 7300
            - -2750
          - - 7300
            - 4650
          - - 2150
            - 4650
      - id: "4"
        icon:
          name: mdi:bed-king-outline
          x: 3300
          "y": -4350
        label:
          text: Primary Bedroom
          x: 3300
          "y": -4350
          offset_y: 35
        outline:
          - - 2300
            - -6300
          - - 4250
            - -6300
          - - 4250
            - -2450
          - - 2300
            - -2450
grid_options:
  columns: full
```

### Javascript errors shown in the browser's console (if applicable)

```shell

```

### Additional information

![Image](https://github.com/user-attachments/assets/7aaf6f89-73df-400f-89ee-49ba8bc46689)

map_source:
  camera: camera.x40_pro_map_1
![Image](https://github.com/user-attachments/assets/b5098990-a030-45a7-b983-fb9d724a2cc5)

map_source:
  camera: camera.x40_pro_map_data
![Image](https://github.com/user-attachments/assets/50bf3e80-cff1-4156-b75b-6eda10d66045)

map_source:
  camera: camera.x40_pro_wifi_map_1
![Image](https://github.com/user-attachments/assets/47d63b38-df02-40ea-a21a-a9c1725fb932)
