### ISSUE TITLE
Problem with Camera_Calibration

### ISSUE THREAD

**Issue by Nicols07** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#85]
I have a problem when Camera_Calibration is at True !

Xiaomi Cloud Map Extractor send good values :
```
calibration_points:
  - vacuum:
      x: 25500
      'y': 25500
    map:
      x: 372
      'y': 322
  - vacuum:
      x: 26500
      'y': 25500
    map:
      x: 412
      'y': 322
  - vacuum:
      x: 26500
      'y': 26500
    map:
      x: 412
      'y': 282
charger:
  x: 25605
  'y': 25221
image:
  size: 201627
  offset_y: 323
  offset_x: 324
  height: 349
  scale: 2
  rotation: 0
  width: 391
```
But i don't know why it's impossible to configure a manual map with this parameters.... i must force the same parameters in calibration_points !

![image](https://user-images.githubusercontent.com/75591361/103711360-8c83f600-4fb7-11eb-8d18-202ddd553b6e.png)

![image](https://user-images.githubusercontent.com/75591361/103711399-a3c2e380-4fb7-11eb-82d1-8f293020f7a1.png)
