### ISSUE TITLE
Is it possible to get zone data from the extractor/map_camera, so I can click on a zone and start a cleanup?

### ISSUE THREAD

**Issue by mortenmoulder** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#90]
So I'm a bit unsure what to do here. Everything has been implemented and `Go to target` and `Zoned cleanup` works. I am using `map_camera` from the extractor:

```
type: entities
entities:
  - type: 'custom:xiaomi-vacuum-map-card'
    entity: vacuum.xiaomi_vacuum
    map_camera: camera.xiaomi_cloud_map_extractor
    camera_calibration: true
```

However, I would like to be able to click on each zone and start a cleanup. Exactly the same as in the app. If I do `debug: true` in the card, I can only get zone data that is rectangular (4 values: x1, x2, y1, y2 right?), but my zones are essentially rooms. In the app I can select a zone and clean it up, but there is only 1 room, because I have an S5 that only supports 1 room.

If I use miiocli and `get_room_mapping` I get an empty array back, because I have an S5 that doesn't support rooms.

So how would I go about creating custom zones that are identical to the zones in the app, so I can simply click on 3 rooms and start a cleanup?

Thanks!

**Comment by PiotrMachowski** [comment]
Do you have "colorful" map in extractor?

**Comment by mortenmoulder** [comment]
@PiotrMachowski Hello. I have this, so I doubt it:

```
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    country: "de"
    draw: ['all']
    attributes:
      - calibration_points
```

**Comment by PiotrMachowski** [comment]
There are default colors, so config doesn't matter. I was talking about map image itself:
![image](https://user-images.githubusercontent.com/6118709/105034451-c940fa00-5a59-11eb-8c7d-7746bb014b4c.png)

**Comment by mortenmoulder** [comment]
@PiotrMachowski Ah, right. Yes:

![image](https://user-images.githubusercontent.com/1304665/105035107-c2ff4d80-5a5a-11eb-8368-a3c8c684f55e.png)

And yes, we do have windows all around that large area

**Comment by PiotrMachowski** [comment]
Right now you can extract room numbers by using `room_numbers` attribute, I will add vacuuming by number to this card (someday).

Yes, windows and mirrors are problematic :)

**Comment by mortenmoulder** [comment]
@PiotrMachowski How can I extract room numbers by using `room_numbers` attribute? Sorry, I'm still quite new to Home Assistant and integrations like these. Also, my S5 does not have rooms. Only zones. Rooms is not a thing on the S5 (except the ONE room). I can't give each "room" (zone) a name, for example.

**Comment by PiotrMachowski** [comment]
You have to add it in your config:
```
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    country: "de"
    draw: ['all']
    attributes:
      - calibration_points
      - room_numbers
```
From map perspective it looks like rooms, maybe it just doesn't support naming
