### ISSUE TITLE
Predefined Zones are not shown in map

### ISSUE THREAD

**Issue by senex44** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#92]
Hi!
I've tried a lot by myself, but cannot figure out, why the zones do not show up.
I have a Xiaomi Vacuum (SDJQR02RR), so the live map is always created new for xiaomi-vacuum-map-extractor, which is why I would like to use xiaomi-vacuum-map-card
I have created a map and it is shown in the card. I have configured zones, interestingly it is transformed into a different format once I save the card - see below.

```
type: 'custom:xiaomi-vacuum-map-card'
entity: vacuum.xiaomi_vacuum
map_image: /local/custom_lovelace/xiaomi_vacuum_map_card/map.png
calibration_points:
  - vacuum:
      x: 26576
      'y': 30123
    map:
      x: 14
      'y': 11
  - vacuum:
      x: 26576
      'y': 22093
    map:
      x: 14
      'y': 716
  - vacuum:
      x: 26576
      'y': 22093
    map:
      x: 1340
      'y': 716
zones:
  - - - 22605
      - 22003
      - 26576
      - 30257
      - 1
  - - - 18456
      - 22048
      - 22337
      - 26153
      - 1
  - - - 14574
      - 26153
      - 22516
      - 28071
      - 1
  - - - 11808
      - 22003
      - 16047
      - 26242
      - 1
```

The files are put at this path and map is shown properly

`/config/www/custom_lovelace/xiaomi_vacuum_map_card`

![grafik](https://user-images.githubusercontent.com/63457786/106178014-8ab5e880-6199-11eb-963f-ae666c5da4cc.png)

Resource has been added

```
resources:
  - url: /local/custom_lovelace/xiaomi_vacuum_map_card/xiaomi-vacuum-map-card.js
    type: module
```

But nothing is shown
![grafik](https://user-images.githubusercontent.com/63457786/106178358-f5ffba80-6199-11eb-8997-9df85dcd1cfd.png)

Interestingly, for xiaomi-vacuum-map-extractor, this is working (though not usable to newly created map (map was tilted last time)
![grafik](https://user-images.githubusercontent.com/63457786/106178454-1596e300-619a-11eb-8c45-35d34da5c2de.png)

Do you have any idea, what's wrong here?

**Comment by PiotrMachowski** [comment]
You have to remove `- 1` from your zones' definitions

**Comment by senex44** [comment]
Unfortunately, this does not change something. Still, it works with ´-1´ in the map-extractor card

**Comment by PiotrMachowski** [comment]
Have you copied calibration from an extractor entity?

**Comment by senex44** [comment]
I have used the map-extractor in debug mode to draw the zones in zoned cleanup mode. like this
![grafik](https://user-images.githubusercontent.com/63457786/106179931-f6995080-619b-11eb-880d-ae3a3a1b17b6.png)

**Comment by PiotrMachowski** [comment]
I am talking about `calibration_points` section:
```
calibration_points:
  - vacuum:
      x: 26576
      'y': 30123
    map:
      x: 14
      'y': 11
  - vacuum:
      x: 26576
      'y': 22093
    map:
      x: 14
      'y': 716
  - vacuum:
      x: 26576
      'y': 22093
    map:
      x: 1340
      'y': 716
```
