### ISSUE TITLE
Question regarding Map Cards for 2 separate vacuums

### ISSUE THREAD

**Issue by jpsmith16** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#95]
Hi

Firstly, thanks very much for all the work you've put into this and the cloud map extractor. Very much appreciated. Am hoping you (or someone else who's come across the same issue) can help

I have 2 separate Roborock vacuums. One Downstairs & one Upstairs. I have 2 map cards set up in Lovelace and within "camera" in _configuration.yaml_ I have map extractor code for 2 separate platforms, pointing to the different 2 IP address / tokens

```
camera:
  - platform: xiaomi_cloud_map_extractor
    host: XXX.XXX.X.XXX
    token: UpstairsToken
    username: XXXXXX@XXX.com
    password: -
    country: de
    draw: ['all']
    map_transformation:
      scale: 2
    attributes:
      - calibration_points

  - platform: xiaomi_cloud_map_extractor
    host: XXX.XXX.X.XXX
    token: DownstairsToken
    username: XXXXXX@XXX.com
    password: -
    country: de
    draw: ['all']
    map_transformation:
      scale: 2
    attributes:
      - calibration_points
```
When I enable the 2 cards in Lovelace I can only get the Upstairs map image on both cards. Not sure if this is linked to Issue #50 (multi-level maps) or not, but as this is slightly different (2 vacuums with 2 separate maps v 1 vacuum with multi level maps), am wondering is there a solution to this?

Thanks in advance!

[Screenshot 2021-02-07 at 15 01 09](https://user-images.githubusercontent.com/52608556/107150372-6904f000-6955-11eb-9566-92334f2c042b.png)

**Comment by PiotrMachowski** [comment]
You have to add a `name` section in camera configuration, it will generate 2 separate entities that can be used in 2 separate cards:

```
camera:
  - platform: xiaomi_cloud_map_extractor
    name: Upstairs Vacuum Map
    host: XXX.XXX.X.XXX
    token: UpstairsToken
    username: XXXXXX@XXX.com
    password: -
    country: de
    draw: ['all']
    map_transformation:
      scale: 2
    attributes:
      - calibration_points

  - platform: xiaomi_cloud_map_extractor
    name: Downstairs Vacuum Map
    host: XXX.XXX.X.XXX
    token: DownstairsToken
    username: XXXXXX@XXX.com
    password: -
    country: de
    draw: ['all']
    map_transformation:
      scale: 2
    attributes:
      - calibration_points
```
